// Generated segment profile for ABS (v2.8)

export const segmentId = "ABS";
export const fields = [
  {
    sequence: 1,
    id: "ABS-1",
    required: false,
    repeatable: false,
    datatype: "XCN",
    table: "HL70010",
    name: "Discharge Care Provider",
    item: "1514",
  },
  {
    sequence: 2,
    id: "ABS-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70069",
    name: "Transfer Medical Service Code",
    item: "1515",
  },
  {
    sequence: 3,
    id: "ABS-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70421",
    name: "Severity of Illness Code",
    item: "1516",
  },
  {
    sequence: 4,
    id: "ABS-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Date/Time of Attestation",
    item: "1517",
  },
  {
    sequence: 5,
    id: "ABS-5",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Attested By",
    item: "1518",
  },
  {
    sequence: 6,
    id: "ABS-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70422",
    name: "Triage Code",
    item: "1519",
  },
  {
    sequence: 7,
    id: "ABS-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Abstract Completion Date/Time",
    item: "1520",
  },
  {
    sequence: 8,
    id: "ABS-8",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Abstracted By",
    item: "1521",
  },
  {
    sequence: 9,
    id: "ABS-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70423",
    name: "Case Category Code",
    item: "1522",
  },
  {
    sequence: 10,
    id: "ABS-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Caesarian Section Indicator",
    item: "1523",
  },
  {
    sequence: 11,
    id: "ABS-11",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70424",
    name: "Gestation Category Code",
    item: "1524",
  },
  {
    sequence: 12,
    id: "ABS-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Gestation Period - Weeks",
    item: "1525",
  },
  {
    sequence: 13,
    id: "ABS-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70425",
    name: "Newborn Code",
    item: "1526",
  },
  {
    sequence: 14,
    id: "ABS-14",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Stillborn Indicator",
    item: "1527",
  },
] as const;
