// Generated segment profile for BHS (v2.8)

export const segmentId = "BHS";
export const fields = [
  {
    sequence: 1,
    id: "BHS-1",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 1,
    name: "Batch Field Separator",
    item: "81",
  },
  {
    sequence: 2,
    id: "BHS-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 5,
    name: "Batch Encoding Characters",
    item: "82",
  },
  {
    sequence: 3,
    id: "BHS-3",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Batch Sending Application",
    item: "83",
  },
  {
    sequence: 4,
    id: "BHS-4",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Batch Sending Facility",
    item: "84",
  },
  {
    sequence: 5,
    id: "BHS-5",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Batch Receiving Application",
    item: "85",
  },
  {
    sequence: 6,
    id: "BHS-6",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Batch Receiving Facility",
    item: "86",
  },
  {
    sequence: 7,
    id: "BHS-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Batch Creation Date/Time",
    item: "87",
  },
  {
    sequence: 8,
    id: "BHS-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Batch Security",
    item: "88",
  },
  {
    sequence: 9,
    id: "BHS-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Batch Name/ID/Type",
    item: "89",
  },
  {
    sequence: 10,
    id: "BHS-10",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Batch Comment",
    item: "90",
  },
  {
    sequence: 11,
    id: "BHS-11",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Batch Control ID",
    item: "91",
  },
  {
    sequence: 12,
    id: "BHS-12",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Reference Batch Control ID",
    item: "92",
  },
  {
    sequence: 13,
    id: "BHS-13",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Batch Sending Network Address",
    item: "2271",
  },
  {
    sequence: 14,
    id: "BHS-14",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Batch Receiving Network Address",
    item: "2272",
  },
] as const;
