// Generated segment profile for BUI (v2.8)

export const segmentId = "BUI";
export const fields = [
  {
    datatype: "SI",
    id: "BUI-1",
    item: "3373",
    maxLength: 4,
    name: "Set ID - BUI",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "BUI-2",
    item: "3374",
    name: "Blood Unit Identifier",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "BUI-3",
    item: "3375",
    name: "Blood Unit Type",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70566",
  },
  {
    datatype: "NM",
    id: "BUI-4",
    item: "3376",
    name: "Blood Unit Weight",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CNE",
    id: "BUI-5",
    item: "3377",
    name: "Weight Units",
    repeatable: false,
    required: true,
    sequence: 5,
    table: "HL70929",
  },
  {
    datatype: "NM",
    id: "BUI-6",
    item: "3378",
    name: "Blood Unit Volume",
    repeatable: false,
    required: true,
    sequence: 6,
  },
  {
    datatype: "CNE",
    id: "BUI-7",
    item: "3379",
    name: "Volume Units",
    repeatable: false,
    required: true,
    sequence: 7,
    table: "HL70930",
  },
  {
    datatype: "ST",
    id: "BUI-8",
    item: "3380",
    name: "Container Catalog Number",
    repeatable: false,
    required: true,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "BUI-9",
    item: "3381",
    name: "Container Lot Number",
    repeatable: false,
    required: true,
    sequence: 9,
  },
  {
    datatype: "XON",
    id: "BUI-10",
    item: "3382",
    name: "Container Manufacturer",
    repeatable: false,
    required: true,
    sequence: 10,
  },
  {
    datatype: "NR",
    id: "BUI-11",
    item: "3383",
    name: "Transport Temperature",
    repeatable: false,
    required: true,
    sequence: 11,
  },
  {
    datatype: "CNE",
    id: "BUI-12",
    item: "3384",
    name: "Transport Temperature Units",
    repeatable: false,
    required: true,
    sequence: 12,
    table: "HL70931",
  },
] as const;
