// Generated segment profile for CER (v2.8)

export const segmentId = "CER";
export const fields = [
  {
    datatype: "SI",
    id: "CER-1",
    item: "1856",
    maxLength: 4,
    name: "Set ID - CER",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "CER-2",
    item: "1857",
    name: "Serial Number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "CER-3",
    item: "1858",
    name: "Version",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "XON",
    id: "CER-4",
    item: "1859",
    name: "Granting Authority",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XCN",
    id: "CER-5",
    item: "1860",
    name: "Issuing Authority",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ED",
    id: "CER-6",
    item: "1861",
    name: "Signature",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "CER-7",
    item: "1862",
    maxLength: 3,
    name: "Granting Country",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70399",
  },
  {
    datatype: "CWE",
    id: "CER-8",
    item: "1863",
    name: "Granting State/Province",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70347",
  },
  {
    datatype: "CWE",
    id: "CER-9",
    item: "1864",
    name: "Granting County/Parish",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70289",
  },
  {
    datatype: "CWE",
    id: "CER-10",
    item: "1865",
    name: "Certificate Type",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "CER-11",
    item: "1866",
    name: "Certificate Domain",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "EI",
    id: "CER-12",
    item: "1867",
    name: "Subject ID",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "CER-13",
    item: "1907",
    name: "Subject Name",
    repeatable: false,
    required: true,
    sequence: 13,
  },
  {
    datatype: "CWE",
    id: "CER-14",
    item: "1868",
    name: "Subject Directory Attribute Extension",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "CER-15",
    item: "1869",
    name: "Subject Public Key Info",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CWE",
    id: "CER-16",
    item: "1870",
    name: "Authority Key Identifier",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "CER-17",
    item: "1871",
    maxLength: 1,
    name: "Basic Constraint",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "CER-18",
    item: "1872",
    name: "CRL Distribution Point",
    repeatable: true,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ID",
    id: "CER-19",
    item: "1875",
    maxLength: 3,
    name: "Jurisdiction Country",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70399",
  },
  {
    datatype: "CWE",
    id: "CER-20",
    item: "1873",
    name: "Jurisdiction State/Province",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70347",
  },
  {
    datatype: "CWE",
    id: "CER-21",
    item: "1874",
    name: "Jurisdiction County/Parish",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70289",
  },
  {
    datatype: "CWE",
    id: "CER-22",
    item: "1895",
    name: "Jurisdiction Breadth",
    repeatable: true,
    required: false,
    sequence: 22,
    table: "HL70547",
  },
  {
    datatype: "DTM",
    id: "CER-23",
    item: "1876",
    name: "Granting Date",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "DTM",
    id: "CER-24",
    item: "1877",
    name: "Issuing Date",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "DTM",
    id: "CER-25",
    item: "1878",
    name: "Activation Date",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "DTM",
    id: "CER-26",
    item: "1879",
    name: "Inactivation Date",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "DTM",
    id: "CER-27",
    item: "1880",
    name: "Expiration Date",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "DTM",
    id: "CER-28",
    item: "1881",
    name: "Renewal Date",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "DTM",
    id: "CER-29",
    item: "1882",
    name: "Revocation Date",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CWE",
    id: "CER-30",
    item: "1883",
    name: "Revocation Reason Code",
    repeatable: false,
    required: false,
    sequence: 30,
  },
  {
    datatype: "CWE",
    id: "CER-31",
    item: "1884",
    name: "Certificate Status Code",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70536",
  },
] as const;
