// Generated segment profile for CM0 (v2.8)

export const segmentId = "CM0";
export const fields = [
  {
    datatype: "SI",
    id: "CM0-1",
    item: "1010",
    maxLength: 4,
    name: "Set ID - CM0",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "CM0-2",
    item: "1011",
    name: "Sponsor Study ID",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "CM0-3",
    item: "1036",
    name: "Alternate Study ID",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "CM0-4",
    item: "1013",
    name: "Title of Study",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "XCN",
    id: "CM0-5",
    item: "1014",
    name: "Chairman of Study",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DT",
    id: "CM0-6",
    item: "1015",
    name: "Last IRB Approval Date",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "CM0-7",
    item: "1016",
    name: "Total Accrual to Date",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DT",
    id: "CM0-8",
    item: "1017",
    name: "Last Accrual Date",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "XCN",
    id: "CM0-9",
    item: "1018",
    name: "Contact for Study",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XTN",
    id: "CM0-10",
    item: "1019",
    name: "Contact's Telephone Number",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XAD",
    id: "CM0-11",
    item: "1020",
    name: "Contact's Address",
    repeatable: true,
    required: false,
    sequence: 11,
  },
] as const;
