// Generated segment profile for DB1 (v2.8)

export const segmentId = "DB1";
export const fields = [
  {
    sequence: 1,
    id: "DB1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - DB1",
    item: "1283",
  },
  {
    sequence: 2,
    id: "DB1-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70334",
    name: "Disabled Person Code",
    item: "1284",
  },
  {
    sequence: 3,
    id: "DB1-3",
    required: false,
    repeatable: true,
    datatype: "CX",
    name: "Disabled Person Identifier",
    item: "1285",
  },
  {
    sequence: 4,
    id: "DB1-4",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Disability Indicator",
    item: "1286",
  },
  {
    sequence: 5,
    id: "DB1-5",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Disability Start Date",
    item: "1287",
  },
  {
    sequence: 6,
    id: "DB1-6",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Disability End Date",
    item: "1288",
  },
  {
    sequence: 7,
    id: "DB1-7",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Disability Return to Work Date",
    item: "1289",
  },
  {
    sequence: 8,
    id: "DB1-8",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Disability Unable to Work Date",
    item: "1290",
  },
] as const;
