// Generated segment profile for ERR (v2.8)

export const segmentId = "ERR";
export const fields = [
  {
    datatype: "ELD",
    deprecated: true,
    id: "ERR-1",
    item: "24",
    name: "Error Code and Location",
    repeatable: true,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ERL",
    id: "ERR-2",
    item: "1812",
    name: "Error Location",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "ERR-3",
    item: "1813",
    name: "HL7 Error Code",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70357",
  },
  {
    datatype: "ID",
    id: "ERR-4",
    item: "1814",
    maxLength: 1,
    name: "Severity",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70516",
  },
  {
    datatype: "CWE",
    id: "ERR-5",
    item: "1815",
    name: "Application Error Code",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70533",
  },
  {
    datatype: "ST",
    id: "ERR-6",
    item: "1816",
    name: "Application Error Parameter",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TX",
    id: "ERR-7",
    item: "1817",
    name: "Diagnostic Information",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "TX",
    id: "ERR-8",
    item: "1818",
    name: "User Message",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "ERR-9",
    item: "1819",
    name: "Inform Person Indicator",
    repeatable: true,
    required: false,
    sequence: 9,
    table: "HL70517",
  },
  {
    datatype: "CWE",
    id: "ERR-10",
    item: "1820",
    name: "Override Type",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70518",
  },
  {
    datatype: "CWE",
    id: "ERR-11",
    item: "1821",
    name: "Override Reason Code",
    repeatable: true,
    required: false,
    sequence: 11,
    table: "HL70519",
  },
  {
    datatype: "XTN",
    id: "ERR-12",
    item: "1822",
    name: "Help Desk Contact Point",
    repeatable: true,
    required: false,
    sequence: 12,
  },
] as const;
