// Generated segment profile for IIM (v2.8)

export const segmentId = "IIM";
export const fields = [
  {
    datatype: "CWE",
    id: "IIM-1",
    item: "1897",
    name: "Primary Key Value - IIM",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "IIM-2",
    item: "1799",
    name: "Service Item Code",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "IIM-3",
    item: "1800",
    name: "Inventory Lot Number",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "DTM",
    id: "IIM-4",
    item: "1801",
    name: "Inventory Expiration Date",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "IIM-5",
    item: "1802",
    name: "Inventory Manufacturer Name",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "IIM-6",
    item: "1803",
    name: "Inventory Location",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "IIM-7",
    item: "1804",
    name: "Inventory Received Date",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "IIM-8",
    item: "1805",
    name: "Inventory Received Quantity",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "IIM-9",
    item: "1806",
    name: "Inventory Received Quantity Unit",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "MO",
    id: "IIM-10",
    item: "1807",
    name: "Inventory Received Item Cost",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DTM",
    id: "IIM-11",
    item: "1808",
    name: "Inventory On Hand Date",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "NM",
    id: "IIM-12",
    item: "1809",
    name: "Inventory On Hand Quantity",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "IIM-13",
    item: "1810",
    name: "Inventory On Hand Quantity Unit",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CNE",
    id: "IIM-14",
    item: "393",
    name: "Procedure Code",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70088",
  },
  {
    datatype: "CNE",
    id: "IIM-15",
    item: "1316",
    name: "Procedure Code Modifier",
    repeatable: true,
    required: false,
    sequence: 15,
    table: "HL70340",
  },
] as const;
