// Generated segment profile for MRG (v2.8)

export const segmentId = "MRG";
export const fields = [
  {
    datatype: "CX",
    id: "MRG-1",
    item: "211",
    name: "Prior Patient Identifier List",
    repeatable: true,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CX",
    deprecated: true,
    id: "MRG-2",
    item: "212",
    name: "Prior Alternate Patient ID",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CX",
    id: "MRG-3",
    item: "213",
    name: "Prior Patient Account Number",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CX",
    deprecated: true,
    id: "MRG-4",
    item: "214",
    name: "Prior Patient ID",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CX",
    id: "MRG-5",
    item: "1279",
    name: "Prior Visit Number",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CX",
    id: "MRG-6",
    item: "1280",
    name: "Prior Alternate Visit ID",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XPN",
    id: "MRG-7",
    item: "1281",
    name: "Prior Patient Name",
    repeatable: true,
    required: false,
    sequence: 7,
  },
] as const;
