// Generated segment profile for OM4 (v2.8)

export const segmentId = "OM4";
export const fields = [
  {
    datatype: "NM",
    id: "OM4-1",
    item: "586",
    name: "Sequence Number - Test/Observation Master File",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "OM4-2",
    item: "642",
    maxLength: 1,
    name: "Derived Specimen",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70170",
  },
  {
    datatype: "TX",
    id: "OM4-3",
    item: "643",
    maxLength: 60,
    name: "Container Description",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "OM4-4",
    item: "644",
    name: "Container Volume",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "OM4-5",
    item: "645",
    name: "Container Units",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "OM4-6",
    item: "646",
    name: "Specimen",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "OM4-7",
    item: "647",
    name: "Additive",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70371",
  },
  {
    datatype: "TX",
    id: "OM4-8",
    item: "648",
    name: "Preparation",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "TX",
    id: "OM4-9",
    item: "649",
    name: "Special Handling Requirements",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CQ",
    id: "OM4-10",
    item: "650",
    name: "Normal Collection Volume",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CQ",
    id: "OM4-11",
    item: "651",
    name: "Minimum Collection Volume",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "TX",
    id: "OM4-12",
    item: "652",
    name: "Specimen Requirements",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ID",
    id: "OM4-13",
    item: "653",
    maxLength: 1,
    name: "Specimen Priorities",
    repeatable: true,
    required: false,
    sequence: 13,
    table: "HL70027",
  },
  {
    datatype: "CQ",
    id: "OM4-14",
    item: "654",
    name: "Specimen Retention Time",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "OM4-15",
    item: "1908",
    name: "Specimen Handling Code",
    repeatable: true,
    required: false,
    sequence: 15,
    table: "HL70376",
  },
  {
    datatype: "ID",
    id: "OM4-16",
    item: "3311",
    name: "Specimen Preference",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70920",
  },
  {
    datatype: "NM",
    id: "OM4-17",
    item: "3312",
    name: "Preferred Specimen/Attribture Sequence ID",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CWE",
    id: "OM4-18",
    item: "1539",
    name: "Taxonomic Classification Code",
    repeatable: true,
    required: false,
    sequence: 18,
  },
] as const;
