// Generated segment profile for ORG (v2.8)

export const segmentId = "ORG";
export const fields = [
  {
    sequence: 1,
    id: "ORG-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - ORG",
    item: "1459",
  },
  {
    sequence: 2,
    id: "ORG-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70405",
    name: "Organization Unit Code",
    item: "1460",
  },
  {
    sequence: 3,
    id: "ORG-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70474",
    name: "Organization Unit Type Code",
    item: "1625",
  },
  {
    sequence: 4,
    id: "ORG-4",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Primary Org Unit Indicator",
    item: "1462",
  },
  {
    sequence: 5,
    id: "ORG-5",
    required: false,
    repeatable: false,
    datatype: "CX",
    name: "Practitioner Org Unit Identifier",
    item: "1463",
  },
  {
    sequence: 6,
    id: "ORG-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70452",
    name: "Health Care Provider Type Code",
    item: "1464",
  },
  {
    sequence: 7,
    id: "ORG-7",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70453",
    name: "Health Care Provider Classification Code",
    item: "1614",
  },
  {
    sequence: 8,
    id: "ORG-8",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70454",
    name: "Health Care Provider Area of Specialization Code",
    item: "1615",
  },
  {
    sequence: 9,
    id: "ORG-9",
    required: false,
    repeatable: false,
    datatype: "DR",
    name: "Effective Date Range",
    item: "1465",
  },
  {
    sequence: 10,
    id: "ORG-10",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70066",
    name: "Employment Status Code",
    item: "1276",
  },
  {
    sequence: 11,
    id: "ORG-11",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Board Approval Indicator",
    item: "1467",
  },
  {
    sequence: 12,
    id: "ORG-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Primary Care Physician Indicator",
    item: "1468",
  },
  {
    sequence: 13,
    id: "ORG-13",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70539",
    name: "Cost Center Code",
    item: "1891",
  },
] as const;
