// Generated segment profile for PID (v2.8)

export const segmentId = "PID";
export const fields = [
  {
    datatype: "SI",
    id: "PID-1",
    item: "104",
    maxLength: 4,
    name: "Set ID - PID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CX",
    deprecated: true,
    id: "PID-2",
    item: "105",
    name: "Patient ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CX",
    id: "PID-3",
    item: "106",
    name: "Patient Identifier List",
    repeatable: true,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CX",
    deprecated: true,
    id: "PID-4",
    item: "107",
    name: "Alternate Patient ID - PID",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XPN",
    id: "PID-5",
    item: "108",
    name: "Patient Name",
    repeatable: true,
    required: true,
    sequence: 5,
  },
  {
    datatype: "XPN",
    id: "PID-6",
    item: "109",
    name: "Mother's Maiden Name",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "PID-7",
    item: "110",
    name: "Date/Time of Birth",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CWE",
    id: "PID-8",
    item: "111",
    name: "Administrative Sex",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70001",
  },
  {
    datatype: "XPN",
    deprecated: true,
    id: "PID-9",
    item: "112",
    name: "Patient Alias",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CWE",
    id: "PID-10",
    item: "113",
    name: "Race",
    repeatable: true,
    required: false,
    sequence: 10,
    table: "HL70005",
  },
  {
    datatype: "XAD",
    id: "PID-11",
    item: "114",
    name: "Patient Address",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "IS",
    deprecated: true,
    id: "PID-12",
    item: "115",
    name: "County Code",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70289",
  },
  {
    datatype: "XTN",
    id: "PID-13",
    item: "116",
    name: "Phone Number - Home",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XTN",
    id: "PID-14",
    item: "117",
    name: "Phone Number - Business",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "PID-15",
    item: "118",
    name: "Primary Language",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70296",
  },
  {
    datatype: "CWE",
    id: "PID-16",
    item: "119",
    name: "Marital Status",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70002",
  },
  {
    datatype: "CWE",
    id: "PID-17",
    item: "120",
    name: "Religion",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70006",
  },
  {
    datatype: "CX",
    id: "PID-18",
    item: "121",
    name: "Patient Account Number",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    deprecated: true,
    id: "PID-19",
    item: "122",
    name: "SSN Number - Patient",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "DLN",
    deprecated: true,
    id: "PID-20",
    item: "123",
    name: "Driver's License Number - Patient",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CX",
    id: "PID-21",
    item: "124",
    name: "Mother's Identifier",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "CWE",
    id: "PID-22",
    item: "125",
    name: "Ethnic Group",
    repeatable: true,
    required: false,
    sequence: 22,
    table: "HL70189",
  },
  {
    datatype: "ST",
    id: "PID-23",
    item: "126",
    name: "Birth Place",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ID",
    id: "PID-24",
    item: "127",
    maxLength: 1,
    name: "Multiple Birth Indicator",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70136",
  },
  {
    datatype: "NM",
    id: "PID-25",
    item: "128",
    name: "Birth Order",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "CWE",
    id: "PID-26",
    item: "129",
    name: "Citizenship",
    repeatable: true,
    required: false,
    sequence: 26,
    table: "HL70171",
  },
  {
    datatype: "CWE",
    id: "PID-27",
    item: "130",
    name: "Veterans Military Status",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70172",
  },
  {
    datatype: "CWE",
    deprecated: true,
    id: "PID-28",
    item: "739",
    name: "Nationality",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70212",
  },
  {
    datatype: "DTM",
    id: "PID-29",
    item: "740",
    name: "Patient Death Date and Time",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "ID",
    id: "PID-30",
    item: "741",
    maxLength: 1,
    name: "Patient Death Indicator",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "PID-31",
    item: "1535",
    maxLength: 1,
    name: "Identity Unknown Indicator",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "PID-32",
    item: "1536",
    name: "Identity Reliability Code",
    repeatable: true,
    required: false,
    sequence: 32,
    table: "HL70445",
  },
  {
    datatype: "DTM",
    id: "PID-33",
    item: "1537",
    name: "Last Update Date/Time",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "HD",
    id: "PID-34",
    item: "1538",
    name: "Last Update Facility",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "CWE",
    id: "PID-35",
    item: "1539",
    name: "Taxonomic Classification Code",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "CWE",
    id: "PID-36",
    item: "1540",
    name: "Breed Code",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL70447",
  },
  {
    datatype: "ST",
    id: "PID-37",
    item: "1541",
    name: "Strain",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "CWE",
    id: "PID-38",
    item: "1542",
    name: "Production Class Code",
    repeatable: false,
    required: false,
    sequence: 38,
    table: "HL70429",
  },
  {
    datatype: "CWE",
    id: "PID-39",
    item: "1840",
    name: "Tribal Citizenship",
    repeatable: true,
    required: false,
    sequence: 39,
    table: "HL70171",
  },
  {
    datatype: "XTN",
    id: "PID-40",
    item: "2289",
    name: "Patient Telecommunication Information",
    repeatable: true,
    required: false,
    sequence: 40,
  },
] as const;
