// Generated segment profile for PRT (v2.8)

export const segmentId = "PRT";
export const fields = [
  {
    datatype: "EI",
    id: "PRT-1",
    item: "2379",
    maxLength: 4,
    name: "Participation Instance ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "PRT-2",
    item: "816",
    maxLength: 2,
    name: "Action Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "CWE",
    id: "PRT-3",
    item: "2380",
    name: "Action Reason",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "PRT-4",
    item: "2381",
    name: "Participation",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70912",
  },
  {
    datatype: "XCN",
    id: "PRT-5",
    item: "2382",
    name: "Participation Person",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "PRT-6",
    item: "2383",
    name: "Participation Person Provider Type",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "PRT-7",
    item: "2384",
    name: "Participant Organization Unit Type",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70406",
  },
  {
    datatype: "XON",
    id: "PRT-8",
    item: "2385",
    name: "Participation Organization",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "PL",
    id: "PRT-9",
    item: "2386",
    name: "Participant Location",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "EI",
    id: "PRT-10",
    item: "2348",
    name: "Participation Device",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DTM",
    id: "PRT-11",
    item: "2387",
    name: "Participation Begin Date/Time (arrival time)",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "DTM",
    id: "PRT-12",
    item: "2388",
    name: "Participation End Date/Time (departure time)",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "PRT-13",
    item: "2389",
    name: "Participation Qualitative Duration",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XAD",
    id: "PRT-14",
    item: "2390",
    name: "Participation Address",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "XTN",
    id: "PRT-15",
    item: "2391",
    name: "Participant Telecommunication Address",
    repeatable: true,
    required: false,
    sequence: 15,
  },
] as const;
