// Generated segment profile for PTH (v2.8)

export const segmentId = "PTH";
export const fields = [
  {
    datatype: "ID",
    id: "PTH-1",
    item: "816",
    maxLength: 2,
    name: "Action Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70206",
  },
  {
    datatype: "CWE",
    id: "PTH-2",
    item: "1207",
    name: "Pathway ID",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "PTH-3",
    item: "1208",
    name: "Pathway Instance ID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "DTM",
    id: "PTH-4",
    item: "1209",
    name: "Pathway Established Date/Time",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "PTH-5",
    item: "1210",
    name: "Pathway Life Cycle Status",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DTM",
    id: "PTH-6",
    item: "1211",
    name: "Change Pathway Life Cycle Status Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CNE",
    id: "PTH-7",
    item: "2239",
    name: "Mood Code",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70725",
  },
] as const;
