// Generated segment profile for REL (v2.8)

export const segmentId = "REL";
export const fields = [
  {
    datatype: "SI",
    id: "REL-1",
    item: "2240",
    maxLength: 4,
    name: "Set ID -REL",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "REL-2",
    item: "2241",
    name: "Relationship Type",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "REL-3",
    item: "2242",
    name: "This Relationship Instance Identifier",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "REL-4",
    item: "2243",
    name: "Source Information Instance Identifier",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "EI",
    id: "REL-5",
    item: "2244",
    name: "Target Information Instance Identifier",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "EI",
    id: "REL-6",
    item: "2245",
    name: "Asserting Entity Instance ID",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XCN",
    id: "REL-7",
    item: "2246",
    name: "Asserting Person",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "XON",
    id: "REL-8",
    item: "2247",
    name: "Asserting Organization",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "XAD",
    id: "REL-9",
    item: "2248",
    name: "Assertor Address",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XTN",
    id: "REL-10",
    item: "2249",
    name: "Assertor Contact",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DR",
    id: "REL-11",
    item: "2250",
    name: "Assertion Date Range",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "REL-12",
    item: "2251",
    maxLength: 1,
    name: "Negation Indicator",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "REL-13",
    item: "2252",
    name: "Certainty of Relationship",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NM",
    id: "REL-14",
    item: "2253",
    name: "Priority No",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "REL-15",
    item: "2254",
    name: "Priority  Sequence No (rel preference for consideration)",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "REL-16",
    item: "2255",
    maxLength: 1,
    name: "Separability Indicator",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70136",
  },
] as const;
