// Generated segment profile for TCD (v2.8)

export const segmentId = "TCD";
export const fields = [
  {
    datatype: "CWE",
    id: "TCD-1",
    item: "238",
    name: "Universal Service Identifier",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "SN",
    id: "TCD-2",
    item: "1420",
    name: "Auto-Dilution Factor",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "SN",
    id: "TCD-3",
    item: "1421",
    name: "Rerun Dilution Factor",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "SN",
    id: "TCD-4",
    item: "1422",
    name: "Pre-Dilution Factor",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "SN",
    id: "TCD-5",
    item: "1413",
    name: "Endogenous Content of Pre-Dilution Diluent",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "TCD-6",
    item: "1416",
    maxLength: 1,
    name: "Automatic Repeat Allowed",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "TCD-7",
    item: "1424",
    maxLength: 1,
    name: "Reflex Allowed",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "TCD-8",
    item: "1425",
    name: "Analyte Repeat Status",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70389",
  },
] as const;
