// Generated profile automaton for EHC_E01 (v2.8.1)

export const start = 0;
export const finals = new Set<number>([
  13, 18, 19, 20, 21, 22, 23, 24, 25, 30, 31, 32,
]);
export const alphabet = new Set<string>([
  "ACC",
  "ADJ",
  "AUT",
  "CTD",
  "DG1",
  "IN1",
  "IN2",
  "IPR",
  "IVC",
  "LOC",
  "MSH",
  "NTE",
  "OBX",
  "PID",
  "PR1",
  "PRT",
  "PSG",
  "PSL",
  "PSS",
  "PV1",
  "PV2",
  "PYE",
  "ROL",
  "SFT",
  "UAC",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["IVC", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [
    2,
    new Map([
      ["AUT", 9],
      ["CTD", 10],
      ["LOC", 8],
      ["PRT", 7],
      ["PSS", 5],
      ["PYE", 11],
      ["ROL", 6],
    ]),
  ],
  [
    3,
    new Map([
      ["IVC", 2],
      ["UAC", 3],
    ]),
  ],
  [
    4,
    new Map([
      ["IVC", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [5, new Map([["PSG", 12]])],
  [
    6,
    new Map([
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    7,
    new Map([
      ["PRT", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    8,
    new Map([
      ["LOC", 8],
      ["PRT", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    9,
    new Map([
      ["LOC", 8],
      ["PRT", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    10,
    new Map([
      ["AUT", 9],
      ["CTD", 10],
      ["LOC", 8],
      ["PRT", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    11,
    new Map([
      ["AUT", 9],
      ["CTD", 10],
      ["LOC", 8],
      ["PRT", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    12,
    new Map([
      ["LOC", 17],
      ["PID", 14],
      ["PRT", 16],
      ["PSL", 13],
      ["ROL", 15],
    ]),
  ],
  [
    13,
    new Map([
      ["ADJ", 24],
      ["AUT", 23],
      ["IPR", 18],
      ["LOC", 22],
      ["NTE", 25],
      ["PR1", 19],
      ["PRT", 21],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    14,
    new Map([
      ["ACC", 27],
      ["IN1", 26],
      ["PV1", 29],
      ["PV2", 28],
    ]),
  ],
  [
    15,
    new Map([
      ["PID", 14],
      ["PSL", 13],
      ["ROL", 15],
    ]),
  ],
  [
    16,
    new Map([
      ["PID", 14],
      ["PRT", 16],
      ["PSL", 13],
      ["ROL", 15],
    ]),
  ],
  [
    17,
    new Map([
      ["LOC", 17],
      ["PID", 14],
      ["PRT", 16],
      ["PSL", 13],
      ["ROL", 15],
    ]),
  ],
  [
    18,
    new Map([
      ["IPR", 18],
      ["PSG", 12],
      ["PSS", 5],
    ]),
  ],
  [
    19,
    new Map([
      ["IPR", 18],
      ["NTE", 32],
      ["PR1", 19],
      ["PRT", 31],
      ["PSG", 12],
      ["PSS", 5],
      ["ROL", 30],
    ]),
  ],
  [
    20,
    new Map([
      ["IPR", 18],
      ["PR1", 19],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    21,
    new Map([
      ["IPR", 18],
      ["PR1", 19],
      ["PRT", 21],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    22,
    new Map([
      ["IPR", 18],
      ["LOC", 22],
      ["PR1", 19],
      ["PRT", 21],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    23,
    new Map([
      ["IPR", 18],
      ["LOC", 22],
      ["PR1", 19],
      ["PRT", 21],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    24,
    new Map([
      ["ADJ", 24],
      ["AUT", 23],
      ["IPR", 18],
      ["LOC", 22],
      ["PR1", 19],
      ["PRT", 21],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    25,
    new Map([
      ["ADJ", 24],
      ["AUT", 23],
      ["IPR", 18],
      ["LOC", 22],
      ["NTE", 25],
      ["PR1", 19],
      ["PRT", 21],
      ["PSG", 12],
      ["PSL", 13],
      ["PSS", 5],
      ["ROL", 20],
    ]),
  ],
  [
    26,
    new Map([
      ["DG1", 34],
      ["IN1", 26],
      ["IN2", 35],
      ["OBX", 33],
      ["PID", 14],
      ["PSL", 13],
    ]),
  ],
  [
    27,
    new Map([
      ["ACC", 27],
      ["IN1", 26],
    ]),
  ],
  [
    28,
    new Map([
      ["ACC", 27],
      ["IN1", 26],
    ]),
  ],
  [
    29,
    new Map([
      ["ACC", 27],
      ["IN1", 26],
      ["PV2", 28],
    ]),
  ],
  [
    30,
    new Map([
      ["IPR", 18],
      ["PR1", 19],
      ["PSG", 12],
      ["PSS", 5],
      ["ROL", 30],
    ]),
  ],
  [
    31,
    new Map([
      ["IPR", 18],
      ["PR1", 19],
      ["PRT", 31],
      ["PSG", 12],
      ["PSS", 5],
      ["ROL", 30],
    ]),
  ],
  [
    32,
    new Map([
      ["IPR", 18],
      ["NTE", 32],
      ["PR1", 19],
      ["PRT", 31],
      ["PSG", 12],
      ["PSS", 5],
      ["ROL", 30],
    ]),
  ],
  [
    33,
    new Map([
      ["OBX", 33],
      ["PID", 14],
      ["PSL", 13],
    ]),
  ],
  [
    34,
    new Map([
      ["DG1", 34],
      ["NTE", 36],
      ["OBX", 33],
      ["PID", 14],
      ["PSL", 13],
    ]),
  ],
  [
    35,
    new Map([
      ["DG1", 34],
      ["IN1", 26],
      ["OBX", 33],
      ["PID", 14],
      ["PSL", 13],
    ]),
  ],
  [
    36,
    new Map([
      ["DG1", 34],
      ["NTE", 36],
      ["OBX", 33],
      ["PID", 14],
      ["PSL", 13],
    ]),
  ],
]);
export const effects = {
  "10:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "11:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "12:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "12:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "13:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "13:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "13:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "13:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "13:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "14:IN1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "15:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "15:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "16:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "16:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "17:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "17:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "18:PSG": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "18:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "19:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [],
  },
  "19:PR1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "19:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "19:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "1:IVC": {
    groupsClosed: [],
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION_SUBMIT"],
  },
  "20:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "20:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "20:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "20:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "20:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "21:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "21:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "21:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "21:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "21:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "22:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "22:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "22:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "22:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "22:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "23:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "23:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "23:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "23:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "23:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "24:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "24:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "24:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "24:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "24:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "25:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [],
  },
  "25:PR1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "25:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "25:PSL": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "25:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "26:DG1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "26:IN1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "26:OBX": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsOpened: [],
  },
  "26:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "26:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "27:IN1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "28:IN1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "29:IN1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "2:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "30:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [],
  },
  "30:PR1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "30:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "30:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "31:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [],
  },
  "31:PR1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "31:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "31:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "32:IPR": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [],
  },
  "32:PR1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "32:PSG": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "32:PSS": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "33:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "33:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "34:DG1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "34:OBX": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsOpened: [],
  },
  "34:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "34:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "35:DG1": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "35:IN1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "35:OBX": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsOpened: [],
  },
  "35:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "35:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "36:DG1": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "36:OBX": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsOpened: [],
  },
  "36:PID": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "36:PSL": {
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "3:IVC": {
    groupsClosed: [],
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION_SUBMIT"],
  },
  "4:IVC": {
    groupsClosed: [],
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION_SUBMIT"],
  },
  "5:PSG": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
  },
  "6:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "7:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "8:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
  "9:PSS": {
    groupsClosed: [],
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION_SUBMIT/PRODUCT_SERVICE_SECTION",
    ],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
