// Generated profile automaton for EHC_E01 (v2.7.1)

export const start = 0;
export const finals = new Set<number>([12, 16, 17, 18, 19, 20, 21, 22, 27, 28]);
export const alphabet = new Set<string>([
  "ACC",
  "ADJ",
  "AUT",
  "CTD",
  "DG1",
  "IN1",
  "IN2",
  "IPR",
  "IVC",
  "LOC",
  "MSH",
  "NTE",
  "OBX",
  "PID",
  "PR1",
  "PSG",
  "PSL",
  "PSS",
  "PV1",
  "PV2",
  "PYE",
  "ROL",
  "SFT",
  "UAC",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["IVC", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [
    2,
    new Map([
      ["AUT", 8],
      ["CTD", 9],
      ["LOC", 7],
      ["PSS", 5],
      ["PYE", 10],
      ["ROL", 6],
    ]),
  ],
  [
    3,
    new Map([
      ["IVC", 2],
      ["UAC", 3],
    ]),
  ],
  [
    4,
    new Map([
      ["IVC", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [5, new Map([["PSG", 11]])],
  [
    6,
    new Map([
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    7,
    new Map([
      ["LOC", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    8,
    new Map([
      ["LOC", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    9,
    new Map([
      ["AUT", 8],
      ["CTD", 9],
      ["LOC", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    10,
    new Map([
      ["AUT", 8],
      ["CTD", 9],
      ["LOC", 7],
      ["PSS", 5],
      ["ROL", 6],
    ]),
  ],
  [
    11,
    new Map([
      ["LOC", 15],
      ["PID", 13],
      ["PSL", 12],
      ["ROL", 14],
    ]),
  ],
  [
    12,
    new Map([
      ["ADJ", 21],
      ["AUT", 20],
      ["IPR", 16],
      ["LOC", 19],
      ["NTE", 22],
      ["PR1", 17],
      ["PSG", 11],
      ["PSL", 12],
      ["PSS", 5],
      ["ROL", 18],
    ]),
  ],
  [
    13,
    new Map([
      ["ACC", 24],
      ["IN1", 23],
      ["PV1", 26],
      ["PV2", 25],
    ]),
  ],
  [
    14,
    new Map([
      ["PID", 13],
      ["PSL", 12],
      ["ROL", 14],
    ]),
  ],
  [
    15,
    new Map([
      ["LOC", 15],
      ["PID", 13],
      ["PSL", 12],
      ["ROL", 14],
    ]),
  ],
  [
    16,
    new Map([
      ["IPR", 16],
      ["PSG", 11],
      ["PSS", 5],
    ]),
  ],
  [
    17,
    new Map([
      ["IPR", 16],
      ["NTE", 28],
      ["PR1", 17],
      ["PSG", 11],
      ["PSS", 5],
      ["ROL", 27],
    ]),
  ],
  [
    18,
    new Map([
      ["IPR", 16],
      ["PR1", 17],
      ["PSG", 11],
      ["PSL", 12],
      ["PSS", 5],
      ["ROL", 18],
    ]),
  ],
  [
    19,
    new Map([
      ["IPR", 16],
      ["LOC", 19],
      ["PR1", 17],
      ["PSG", 11],
      ["PSL", 12],
      ["PSS", 5],
      ["ROL", 18],
    ]),
  ],
  [
    20,
    new Map([
      ["IPR", 16],
      ["LOC", 19],
      ["PR1", 17],
      ["PSG", 11],
      ["PSL", 12],
      ["PSS", 5],
      ["ROL", 18],
    ]),
  ],
  [
    21,
    new Map([
      ["ADJ", 21],
      ["AUT", 20],
      ["IPR", 16],
      ["LOC", 19],
      ["PR1", 17],
      ["PSG", 11],
      ["PSL", 12],
      ["PSS", 5],
      ["ROL", 18],
    ]),
  ],
  [
    22,
    new Map([
      ["ADJ", 21],
      ["AUT", 20],
      ["IPR", 16],
      ["LOC", 19],
      ["NTE", 22],
      ["PR1", 17],
      ["PSG", 11],
      ["PSL", 12],
      ["PSS", 5],
      ["ROL", 18],
    ]),
  ],
  [
    23,
    new Map([
      ["DG1", 30],
      ["IN1", 23],
      ["IN2", 31],
      ["OBX", 29],
      ["PID", 13],
      ["PSL", 12],
    ]),
  ],
  [
    24,
    new Map([
      ["ACC", 24],
      ["IN1", 23],
    ]),
  ],
  [
    25,
    new Map([
      ["ACC", 24],
      ["IN1", 23],
    ]),
  ],
  [
    26,
    new Map([
      ["ACC", 24],
      ["IN1", 23],
      ["PV2", 25],
    ]),
  ],
  [
    27,
    new Map([
      ["IPR", 16],
      ["PR1", 17],
      ["PSG", 11],
      ["PSS", 5],
      ["ROL", 27],
    ]),
  ],
  [
    28,
    new Map([
      ["IPR", 16],
      ["NTE", 28],
      ["PR1", 17],
      ["PSG", 11],
      ["PSS", 5],
      ["ROL", 27],
    ]),
  ],
  [
    29,
    new Map([
      ["OBX", 29],
      ["PID", 13],
      ["PSL", 12],
    ]),
  ],
  [
    30,
    new Map([
      ["DG1", 30],
      ["NTE", 32],
      ["OBX", 29],
      ["PID", 13],
      ["PSL", 12],
    ]),
  ],
  [
    31,
    new Map([
      ["DG1", 30],
      ["IN1", 23],
      ["OBX", 29],
      ["PID", 13],
      ["PSL", 12],
    ]),
  ],
  [
    32,
    new Map([
      ["DG1", 30],
      ["NTE", 32],
      ["OBX", 29],
      ["PID", 13],
      ["PSL", 12],
    ]),
  ],
]);
export const effects = {
  "10:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [],
  },
  "11:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "11:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "12:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "12:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "12:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "12:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [],
  },
  "12:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "13:IN1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsClosed: [],
  },
  "14:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "14:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "15:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "15:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "16:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [],
  },
  "16:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
  },
  "16:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
  },
  "17:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "17:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [],
  },
  "17:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "17:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "18:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "18:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "18:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "18:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [],
  },
  "18:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "19:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "19:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "19:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "19:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [],
  },
  "19:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "1:IVC": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION"],
    groupsClosed: [],
  },
  "20:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "20:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "20:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "20:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [],
  },
  "20:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "21:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "21:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "21:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "21:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [],
  },
  "21:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "22:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "22:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "22:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "22:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [],
  },
  "22:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "23:DG1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "23:IN1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsClosed: [],
  },
  "23:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "23:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "23:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "24:IN1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsClosed: [],
  },
  "25:IN1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsClosed: [],
  },
  "26:IN1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsClosed: [],
  },
  "27:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "27:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [],
  },
  "27:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "27:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "28:IPR": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "28:PR1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
    groupsClosed: [],
  },
  "28:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "28:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/INVOICE_PROCESSING",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PROCEDURE",
    ],
  },
  "29:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "29:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
  },
  "2:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [],
  },
  "30:DG1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsClosed: [],
  },
  "30:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "30:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "30:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "31:DG1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "31:IN1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
    groupsClosed: [],
  },
  "31:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "31:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "31:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/INSURANCE",
    ],
  },
  "32:DG1": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
    groupsClosed: [],
  },
  "32:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "32:PID": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
  },
  "32:PSL": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PRODUCT_SERVICE_LINE_ITEM",
    ],
    groupsClosed: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO",
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP/PATIENT_INFO/DIAGNOSIS",
    ],
  },
  "3:IVC": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION"],
    groupsClosed: [],
  },
  "4:IVC": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION"],
    groupsClosed: [],
  },
  "5:PSG": {
    groupsOpened: [
      "EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION/PRODUCT_SERVICE_GROUP",
    ],
    groupsClosed: [],
  },
  "6:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [],
  },
  "7:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [],
  },
  "8:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [],
  },
  "9:PSS": {
    groupsOpened: ["EHC_E01/INVOICE_INFORMATION/PRODUCT_SERVICE_SECTION"],
    groupsClosed: [],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
