// Generated UTG code system profile for v2-0070

export const id = "v2-0070";
export const url = "http://terminology.hl7.org/CodeSystem/v2-0070";
export const oid = "2.16.840.1.113883.18.28";
export const name = "SpecimenSourceCodes";
export const title = "specimenSourceCodes";
export const codes = [
  { code: "ABLD", display: "Arterial blood", status: "active" },
  { code: "ABS", display: "Abscess", status: "active" },
  { code: "AMN", display: "Amniotic fluid", status: "active" },
  { code: "ASP", display: "Aspirate", status: "active" },
  { code: "BBL", display: "Blood bag", status: "active" },
  { code: "BDY", display: "Whole body", status: "active" },
  { code: "BIFL", display: "Bile fluid", status: "active" },
  { code: "BLD", display: "Whole blood", status: "active" },
  { code: "BLDA", display: "Blood  arterial", status: "active" },
  { code: "BLDC", display: "Blood  capillary", status: "active" },
  { code: "BLDCO", display: "Cord blood", status: "active" },
  { code: "BLDV", display: "Blood  venous", status: "active" },
  { code: "BON", display: "Bone", status: "active" },
  { code: "BPH", display: "Basophils", status: "active" },
  { code: "BPU", display: "Blood product unit", status: "active" },
  { code: "BRN", display: "Burn", status: "active" },
  { code: "BRO", display: "Bronchial", status: "active" },
  { code: "BRTH", display: "Breath (use EXHLD)", status: "active" },
  { code: "CALC", display: "Calculus (=Stone)", status: "active" },
  { code: "CBLD", display: "Cord blood", status: "active" },
  { code: "CDM", display: "Cardiac muscle", status: "active" },
  { code: "CNJT", display: "Conjunctiva", status: "active" },
  { code: "CNL", display: "Cannula", status: "active" },
  { code: "COL", display: "Colostrum", status: "active" },
  { code: "CSF", display: "Cerebral spinal fluid", status: "active" },
  { code: "CTP", display: "Catheter tip", status: "active" },
  { code: "CUR", display: "Curettage", status: "active" },
  { code: "CVM", display: "Cervical mucus", status: "active" },
  { code: "CVX", display: "Cervix", status: "active" },
  { code: "CYST", display: "Cyst", status: "active" },
  { code: "DIAF", display: "Dialysis fluid", status: "active" },
  { code: "DOSE", display: "Dose med or substance", status: "active" },
  { code: "DRN", display: "Drain", status: "active" },
  { code: "DUFL", display: "Duodenal fluid", status: "active" },
  { code: "EAR", display: "Ear", status: "active" },
  { code: "EARW", display: "Ear wax (cerumen)", status: "active" },
  { code: "ELT", display: "Electrode", status: "active" },
  { code: "ENDC", display: "Endocardium", status: "active" },
  { code: "ENDM", display: "Endometrium", status: "active" },
  { code: "EOS", display: "Eosinophils", status: "active" },
  { code: "EXG", display: "Exhaled gas (=breath)", status: "active" },
  { code: "EXHLD", display: "Exhaled gas (=breath)", status: "active" },
  { code: "EYE", display: "Eye", status: "active" },
  { code: "FIB", display: "Fibroblasts", status: "active" },
  { code: "FIST", display: "Fistula", status: "active" },
  { code: "FLT", display: "Filter", status: "active" },
  { code: "FLU", display: "Body fluid, unsp", status: "active" },
  { code: "GAS", display: "Gas", status: "active" },
  { code: "GAST", display: "Gastric fluid/contents", status: "active" },
  { code: "GEN", display: "Genital", status: "active" },
  { code: "GENC", display: "Genital cervix", status: "active" },
  { code: "GENL", display: "Genital lochia", status: "active" },
  { code: "GENV", display: "Genital vaginal", status: "active" },
  { code: "HAR", display: "Hair", status: "active" },
  { code: "IHG", display: "Inhaled Gas", status: "active" },
  { code: "ISLT", display: "Isolate", status: "active" },
  { code: "IT", display: "Intubation tube", status: "active" },
  { code: "LAM", display: "Lamella", status: "active" },
  { code: "LIQ", display: "Liquid NOS", status: "active" },
  { code: "LN", display: "Line", status: "active" },
  { code: "LNA", display: "Line arterial", status: "active" },
  { code: "LNV", display: "Line venous", status: "active" },
  { code: "LYM", display: "Lymphocytes", status: "active" },
  { code: "MAC", display: "Macrophages", status: "active" },
  { code: "MAR", display: "Marrow", status: "active" },
  { code: "MBLD", display: "Menstrual blood", status: "active" },
  { code: "MEC", display: "Meconium", status: "active" },
  { code: "MILK", display: "Breast milk", status: "active" },
  { code: "MLK", display: "Milk", status: "active" },
  { code: "MN", display: "Amniotic Fluid", status: "active" },
  { code: "NAIL", display: "Nail", status: "active" },
  { code: "NOS", display: "Nose (nasal passage)", status: "active" },
  { code: "ORH", display: "Other", status: "active" },
  { code: "OTH", display: "Other", status: "active" },
  { code: "PAFL", display: "Pancreatic fluid", status: "active" },
  { code: "PAT", display: "Patient", status: "active" },
  { code: "PER", display: "Peritoneum", status: "active" },
  { code: "PLAS", display: "Plasma", status: "active" },
  { code: "PLB", display: "Plasma bag", status: "active" },
  { code: "PLC", display: "Placenta", status: "active" },
  {
    code: "PLR",
    display: "Pleural fluid (thoracentesis fld)",
    status: "active",
  },
  { code: "PMN", display: "Polymorphonuclear neutrophils", status: "active" },
  { code: "PPP", display: "Platelet poor plasma", status: "active" },
  { code: "PRP", display: "Platelet rich plasma", status: "active" },
  { code: "PRT", display: "Peritoneal fluid /ascites", status: "active" },
  { code: "PUS", display: "Pus", status: "active" },
  { code: "RBC", display: "Erythrocytes", status: "active" },
  { code: "RT", display: "Route of medicine", status: "active" },
  { code: "SAL", display: "Saliva", status: "active" },
  { code: "SEM", display: "Seminal fluid", status: "active" },
  { code: "SER", display: "Serum", status: "active" },
  { code: "SKM", display: "Skeletal muscle", status: "active" },
  { code: "SKN", display: "Skin", status: "active" },
  { code: "SMN", display: "Seminal fluid", status: "active" },
  { code: "SNV", display: "Synovial fluid (Joint fluid)", status: "active" },
  { code: "SPRM", display: "Spermatozoa", status: "active" },
  { code: "SPT", display: "Sputum", status: "active" },
  { code: "SPTC", display: "Sputum - coughed", status: "active" },
  { code: "SPTT", display: "Sputum - tracheal aspirate", status: "active" },
  { code: "STL", display: "Stool = Fecal", status: "active" },
  { code: "STON", display: "Stone (use CALC)", status: "active" },
  { code: "SWT", display: "Sweat", status: "active" },
  { code: "TEAR", display: "Tears", status: "active" },
  { code: "THRB", display: "Thrombocyte (platelet)", status: "active" },
  { code: "THRT", display: "Throat", status: "active" },
  { code: "TIS", display: "Tissue", status: "active" },
  { code: "TISB", display: "Tissue bone marrow", status: "active" },
  { code: "TISC", display: "Tissue curettage", status: "active" },
  { code: "TISG", display: "Tissue gall bladder", status: "active" },
  { code: "TISL", display: "Tissue lung", status: "active" },
  { code: "TISP", display: "Tissue peritoneum", status: "active" },
  { code: "TISPL", display: "Tissue placenta", status: "active" },
  { code: "TISS", display: "Tissue", status: "active" },
  { code: "TISU", display: "Tissue ulcer", status: "active" },
  { code: "TLGI", display: "Tissue large intestine", status: "active" },
  { code: "TLNG", display: "Tissue lung", status: "active" },
  { code: "TSMI", display: "Tissue small intestine", status: "active" },
  { code: "TUB", display: "Tube NOS", status: "active" },
  { code: "ULC", display: "Ulcer", status: "active" },
  { code: "UMB", display: "Umbilical blood", status: "active" },
  { code: "UMED", display: "Unknown medicine", status: "active" },
  { code: "UR", display: "Urine", status: "active" },
  { code: "URC", display: "Urine clean catch", status: "active" },
  { code: "URNS", display: "Urine sediment", status: "active" },
  { code: "URT", display: "Urine catheter", status: "active" },
  { code: "URTH", display: "Urethra", status: "active" },
  { code: "USUB", display: "Unknown substance", status: "active" },
  { code: "VITF", display: "Vitreous Fluid", status: "active" },
  { code: "VOM", display: "Vomitus", status: "active" },
  { code: "WAT", display: "Water", status: "active" },
  { code: "WBC", display: "Leukocytes", status: "active" },
  { code: "WICK", display: "Wick", status: "active" },
  { code: "WND", display: "Wound", status: "active" },
  { code: "WNDA", display: "Wound abscess", status: "active" },
  { code: "WNDD", display: "Wound drainage", status: "active" },
  { code: "WNDE", display: "Wound exudate", status: "active" },
  {
    code: "XXX",
    display: "To be specified in another part of the message",
    status: "active",
  },
] as const;
