// Generated UTG code system profile for v2-0354

export const id = "v2-0354";
export const url = "http://terminology.hl7.org/CodeSystem/v2-0354";
export const oid = "2.16.840.1.113883.18.214";
export const name = "MessageStructure";
export const title = "messageStructure";
export const codes = [
  { code: "ACK", display: "Varies", status: "active" },
  { code: "ADR_A19", display: "A19", status: "deprecated" },
  { code: "ADT_A01", display: "A01, A04, A08, A13", status: "active" },
  { code: "ADT_A02", display: "A02", status: "active" },
  { code: "ADT_A03", display: "A03", status: "active" },
  { code: "ADT_A05", display: "A05, A14, A28, A31", status: "active" },
  { code: "ADT_A06", display: "A06, A07", status: "active" },
  { code: "ADT_A09", display: "A09, A10, A11", status: "active" },
  { code: "ADT_A12", display: "A12", status: "active" },
  { code: "ADT_A15", display: "A15", status: "active" },
  { code: "ADT_A16", display: "A16", status: "active" },
  { code: "ADT_A17", display: "A17", status: "active" },
  { code: "ADT_A18", display: "A18", status: "deprecated" },
  { code: "ADT_A20", display: "A20", status: "active" },
  {
    code: "ADT_A21",
    display: "A21, A22, A23, A25, A26, A27, A29, A32, A33",
    status: "active",
  },
  { code: "ADT_A24", display: "A24", status: "active" },
  { code: "ADT_A28", display: "A28, A31", status: "active" },
  {
    code: "ADT_A30",
    display: "A30, A34, A35, A36, A46, A47, A48, A49",
    status: "deprecated",
  },
  { code: "ADT_A37", display: "A37", status: "active" },
  { code: "ADT_A38", display: "A38", status: "active" },
  { code: "ADT_A39", display: "A39, A40, A41, A42", status: "active" },
  { code: "ADT_A43", display: "A43", status: "active" },
  { code: "ADT_A44", display: "A44", status: "active" },
  { code: "ADT_A45", display: "A45", status: "active" },
  { code: "ADT_A50", display: "A50, A51", status: "active" },
  { code: "ADT_A52", display: "A52, A53", status: "active" },
  { code: "ADT_A54", display: "A54, A55", status: "active" },
  { code: "ADT_A60", display: "A60", status: "active" },
  { code: "ADT_A61", display: "A61, A62", status: "active" },
  { code: "ARD_A19", display: "A19", status: "deprecated" },
  { code: "BAR_P01", display: "P01", status: "active" },
  { code: "BAR_P02", display: "P02", status: "active" },
  { code: "BAR_P05", display: "P05", status: "active" },
  { code: "BAR_P06", display: "P06", status: "active" },
  { code: "BAR_P10", display: "P10", status: "active" },
  { code: "BAR_P12", display: "P12", status: "active" },
  { code: "BPS_O29", display: "O29", status: "active" },
  { code: "BRP_030", display: "O30", status: "deprecated" },
  { code: "BRP_O30", display: "O30", status: "active" },
  { code: "BRT_O32", display: "O32", status: "active" },
  { code: "BTS_O31", display: "O31", status: "active" },
  { code: "CCF_I22", display: "I22", status: "active" },
  { code: "CCI_I22", display: "I22", status: "active" },
  { code: "CCM_I21", display: "I21", status: "active" },
  { code: "CCQ_I19", display: "I19", status: "active" },
  { code: "CCR_I16", display: "I16, |17, |18", status: "active" },
  { code: "CCU_I20", display: "I20", status: "active" },
  { code: "CQU_I19", display: "I19", status: "active" },
  {
    code: "CRM_C01",
    display: "C01, C02, C03, C04, C05, C06, C07, C08",
    status: "active",
  },
  { code: "CSU_C09", display: "C09, C10, C11, C12", status: "active" },
  { code: "DBC_O41", display: "O41", status: "active" },
  { code: "DBC_O42", display: "O42", status: "active" },
  { code: "DEL_O46", display: "O46", status: "active" },
  { code: "DEO_O45", display: "O45", status: "active" },
  { code: "DER_O44", display: "O44", status: "active" },
  { code: "DFT_P03", display: "P03", status: "active" },
  { code: "DFT_P11", display: "P11", status: "active" },
  { code: "DOC_T12", display: "T12", status: "deprecated" },
  { code: "DPR_O48", display: "O48", status: "active" },
  { code: "DRC_O47", display: "O47", status: "active" },
  { code: "DRG_O43", display: "O43", status: "active" },
  { code: "DSR_P04", display: "P04", status: "active" },
  { code: "DSR_Q01", display: "Q01", status: "active" },
  { code: "DSR_Q03", display: "Q03", status: "active" },
  { code: "EAC_U07", display: "U07", status: "active" },
  { code: "EAN_U09", display: "U09", status: "active" },
  { code: "EAR_U08", display: "U08", status: "active" },
  { code: "EDR_R07", display: "R07", status: "active" },
  { code: "EHC_E01", display: "E01", status: "active" },
  { code: "EHC_E02", display: "E02", status: "active" },
  { code: "EHC_E04", display: "E04", status: "active" },
  { code: "EHC_E10", display: "E10", status: "active" },
  { code: "EHC_E12", display: "E12", status: "active" },
  { code: "EHC_E13", display: "E13", status: "active" },
  { code: "EHC_E15", display: "E15", status: "active" },
  { code: "EHC_E20", display: "E20", status: "active" },
  { code: "EHC_E21", display: "E21", status: "active" },
  { code: "EHC_E24", display: "E24", status: "active" },
  { code: "EQQ_Q04", display: "Q04", status: "active" },
  { code: "ERP_R09", display: "R09", status: "active" },
  { code: "ESR_U02", display: "U02", status: "active" },
  { code: "ESU_U01", display: "U01", status: "active" },
  { code: "INR_U06", display: "U06", status: "active" },
  { code: "INU_U05", display: "U05", status: "active" },
  { code: "INV_U14", display: "Events U14", status: "active" },
  { code: "LSU_U12", display: "U12, U13", status: "active" },
  {
    code: "MDM_T01",
    display: "T01, T03, T05, T07, T09, T11",
    status: "active",
  },
  { code: "MDM_T02", display: "T02, T04, T06, T08, T10", status: "active" },
  { code: "MFD_MFA", display: "MFA", status: "active" },
  { code: "MFD_P09", display: "P09", status: "deprecated" },
  {
    code: "MFK_M01",
    display: "M01, M02, M03, M04, M05, M06, M07, M08, M09, M10, M11",
    status: "active",
  },
  { code: "MFN_M01", display: "M01", status: "deprecated" },
  { code: "MFN_M02", display: "M02", status: "active" },
  { code: "MFN_M03", display: "M03", status: "deprecated" },
  { code: "MFN_M04", display: "M04", status: "active" },
  { code: "MFN_M05", display: "M05", status: "active" },
  { code: "MFN_M06", display: "M06", status: "active" },
  { code: "MFN_M07", display: "M07", status: "active" },
  { code: "MFN_M08", display: "M08", status: "active" },
  { code: "MFN_M09", display: "M09", status: "active" },
  { code: "MFN_M10", display: "M10", status: "active" },
  { code: "MFN_M11", display: "M11", status: "active" },
  { code: "MFN_M12", display: "M12", status: "active" },
  { code: "MFN_M13", display: "M13", status: "active" },
  { code: "MFN_M15", display: "M15", status: "active" },
  { code: "MFN_M16", display: "M16", status: "active" },
  { code: "MFN_M17", display: "M17", status: "active" },
  { code: "MFN_M18", display: "M18", status: "active" },
  {
    code: "MFQ_M01",
    display: "M01, M02, M03, M04, M05, M06",
    status: "deprecated",
  },
  { code: "MFR_M01", display: "M01, M02, M03,", status: "deprecated" },
  { code: "MFR_M04", display: "M04", status: "deprecated" },
  { code: "MFR_M05", display: "M05", status: "deprecated" },
  { code: "MFR_M06", display: "M06", status: "deprecated" },
  { code: "MFR_M07", display: "M07", status: "deprecated" },
  { code: "NMD_N02", display: "N02", status: "active" },
  { code: "NMQ_N01", display: "N01", status: "deprecated" },
  { code: "NMR_N01", display: "N01", status: "deprecated" },
  { code: "OMB_O27", display: "O27", status: "active" },
  { code: "OMD_O01", display: "", status: "active" },
  { code: "OMD_O03", display: "O03", status: "active" },
  { code: "OMG_O19", display: "O19", status: "active" },
  { code: "OMI_O23", display: "O23", status: "active" },
  { code: "OML_O21", display: "O21", status: "active" },
  { code: "OML_O33", display: "O33", status: "active" },
  { code: "OML_O35", display: "O35", status: "active" },
  { code: "OML_O39", display: "O39", status: "active" },
  {
    code: "OML_O59",
    display: "Laboratory Fulfillment request with REL segment",
    status: "N",
  },
  { code: "OMN_O01", display: "", status: "active" },
  { code: "OMN_O07", display: "O07", status: "active" },
  { code: "OMP_O09", display: "O09", status: "active" },
  { code: "OMQ_O42", display: "O42", status: "deprecated" },
  { code: "OMQ_O57", display: "O57", status: "N" },
  { code: "OMS_O01", display: "", status: "active" },
  { code: "OMS_O05", display: "O05", status: "active" },
  { code: "OPL_O37", display: "O37", status: "active" },
  { code: "OPR_O38", display: "O38", status: "active" },
  { code: "OPU_R25", display: "R25", status: "active" },
  { code: "ORA_R33", display: "R33", status: "active" },
  { code: "ORA_R41", display: "R41", status: "active" },
  { code: "ORB_O28", display: "O28", status: "active" },
  { code: "ORD_O02", display: "", status: "active" },
  { code: "ORD_O04", display: "O04", status: "active" },
  { code: "ORF_R02", display: "R02, R04", status: "active" },
  { code: "ORF_R04", display: "R04", status: "deprecated" },
  { code: "ORG_O20", display: "O20", status: "active" },
  { code: "ORI_O24", display: "O24", status: "active" },
  { code: "ORL_O22", display: "O22", status: "active" },
  { code: "ORL_O34", display: "O34", status: "active" },
  { code: "ORL_O36", display: "O36", status: "active" },
  { code: "ORL_O40", display: "O40", status: "active" },
  { code: "ORL_O41", display: "O41", status: "deprecated" },
  { code: "ORL_O42", display: "O42", status: "deprecated" },
  { code: "ORL_O43", display: "O43", status: "deprecated" },
  { code: "ORL_O44", display: "O44", status: "deprecated" },
  { code: "ORL_O53", display: "O53", status: "N" },
  { code: "ORL_O54", display: "O54", status: "N" },
  { code: "ORL_O55", display: "O55", status: "N" },
  { code: "ORL_O56", display: "O56", status: "N" },
  { code: "ORM_O01", display: "O01", status: "deprecated" },
  { code: "ORM_Q06", display: "Q06", status: "active" },
  { code: "ORN_O02", display: "", status: "active" },
  { code: "ORN_O08", display: "O08", status: "active" },
  { code: "ORP_O10", display: "O10", status: "active" },
  { code: "ORR_O02", display: "O02", status: "deprecated" },
  { code: "ORR_Q06", display: "Q06", status: "active" },
  { code: "ORS_O02", display: "", status: "active" },
  { code: "ORS_O06", display: "O06", status: "active" },
  { code: "ORU_R01", display: "R01", status: "active" },
  { code: "ORU_R30", display: "R30", status: "active" },
  { code: "ORU_R31", display: "R31", status: "active" },
  { code: "ORU_R32", display: "R32", status: "active" },
  { code: "ORU_W01", display: "W01", status: "deprecated" },
  { code: "ORX_O43", display: "O43", status: "deprecated" },
  { code: "ORX_O58", display: "O58", status: "N" },
  { code: "OSM_R26", display: "R26", status: "active" },
  { code: "OSQ_Q06", display: "Q06", status: "deprecated" },
  { code: "OSR_Q06", display: "Q06", status: "deprecated" },
  { code: "OSU_O41", display: "O41", status: "deprecated" },
  { code: "OSU_O51", display: "O51", status: "N" },
  { code: "OSU_O52", display: "O52", status: "N" },
  { code: "OUL_R21", display: "R21", status: "deprecated" },
  { code: "OUL_R22", display: "R22", status: "active" },
  { code: "OUL_R23", display: "R23", status: "active" },
  { code: "OUL_R24", display: "R24", status: "active" },
  { code: "PEX_P07", display: "P07, P08", status: "active" },
  { code: "PGL_PC6", display: "PC6, PC7, PC8", status: "active" },
  { code: "PIN_I07", display: "I07", status: "active" },
  { code: "PMU_B01", display: "B01, B02", status: "active" },
  { code: "PMU_B03", display: "B03", status: "active" },
  { code: "PMU_B04", display: "B04, B05, B06", status: "active" },
  { code: "PMU_B07", display: "B07", status: "active" },
  { code: "PMU_B08", display: "B08", status: "active" },
  { code: "PPG_PCG", display: "PCC, PCG, PCH, PCJ", status: "active" },
  { code: "PPP_PCB", display: "PCB, PCD", status: "active" },
  { code: "PPR_PC1", display: "PC1, PC2, PC3", status: "active" },
  { code: "PPT_PCL", display: "PCL", status: "deprecated" },
  { code: "PPV_PCA", display: "PCA", status: "deprecated" },
  { code: "PRR_PC5", display: "PC5", status: "deprecated" },
  { code: "PTR_PCF", display: "PCF", status: "deprecated" },
  { code: "QBP_E03", display: "E03", status: "active" },
  { code: "QBP_E22", display: "E22", status: "active" },
  { code: "QBP_O33", display: "O33", status: "active" },
  { code: "QBP_O34", display: "O34", status: "active" },
  { code: "QBP_Q11", display: "Q11", status: "active" },
  { code: "QBP_Q13", display: "Q13", status: "active" },
  { code: "QBP_Q15", display: "Q15", status: "active" },
  { code: "QBP_Q21", display: "Q21, Q22, Q23,Q24, Q25", status: "active" },
  { code: "QBP_Qnn", display: "Qnn", status: "active" },
  { code: "QBP_Z73", display: "Z73", status: "active" },
  { code: "QCK_Q02", display: "Q02", status: "deprecated" },
  { code: "QCN_J01", display: "J01, J02", status: "active" },
  { code: "QRF_W02", display: "W02", status: "deprecated" },
  { code: "QRY_A19", display: "A19", status: "deprecated" },
  { code: "QRY_P04", display: "P04", status: "active" },
  { code: "QRY_PC4", display: "PC4, PC9, PCE, PCK", status: "deprecated" },
  {
    code: "QRY_Q01",
    display: "Q01, Q26, Q27, Q28, Q29, Q30",
    status: "deprecated",
  },
  { code: "QRY_Q02", display: "Q02", status: "deprecated" },
  { code: "QRY_R02", display: "R02", status: "deprecated" },
  { code: "QRY_T12", display: "T12", status: "deprecated" },
  { code: "QSB_Q16", display: "Q16", status: "active" },
  { code: "QVR_Q17", display: "Q17", status: "active" },
  { code: "RAR_RAR", display: "RAR", status: "deprecated" },
  { code: "RAS_O01", display: "O01", status: "active" },
  { code: "RAS_O02", display: "O022", status: "active" },
  { code: "RAS_O17", display: "O17", status: "active" },
  { code: "RCI_I05", display: "I05", status: "deprecated" },
  { code: "RCL_I06", display: "I06", status: "deprecated" },
  { code: "RDE_O01", display: "O01", status: "active" },
  { code: "RDE_O11", display: "O11, O25", status: "active" },
  { code: "RDE_O49", display: "Events O49", status: "active" },
  { code: "RDO_O01", display: "", status: "active" },
  { code: "RDR_RDR", display: "RDR", status: "active" },
  { code: "RDS_O01", display: "O01", status: "active" },
  { code: "RDS_O13", display: "O13", status: "active" },
  { code: "RDY_K11", display: "K11", status: "active" },
  { code: "RDY_K15", display: "K15", status: "active" },
  { code: "REF_I12", display: "I12, I13, I14, I15", status: "active" },
  { code: "RER_RER", display: "RER", status: "deprecated" },
  { code: "RGR_RGR", display: "RGR", status: "deprecated" },
  { code: "RGV_O01", display: "O01", status: "active" },
  { code: "RGV_O15", display: "O15", status: "active" },
  { code: "ROR_ROR", display: "ROR", status: "deprecated" },
  { code: "RPA_I08", display: "I08, I09. I10, I11", status: "active" },
  { code: "RPI_I01", display: "I01, I04", status: "active" },
  { code: "RPI_I04", display: "I04", status: "active" },
  { code: "RPI_I0I", display: "I01, I04", status: "active" },
  { code: "RPL_I02", display: "I02", status: "active" },
  { code: "RPR_I03", display: "I03", status: "active" },
  { code: "RQA_I08", display: "I08, I09, I10, I11", status: "active" },
  { code: "RQC_I05", display: "I05, I06", status: "deprecated" },
  { code: "RQC_I06", display: "I06", status: "active" },
  { code: "RQI_I01", display: "I01, I02, I03, I07", status: "active" },
  { code: "RQI_I0I", display: "I01, I02, I03", status: "active" },
  { code: "RQP_I04", display: "I04", status: "active" },
  { code: "RQQ_Q09", display: "Q09", status: "active" },
  { code: "RRA_O02", display: "O02", status: "active" },
  { code: "RRA_O18", display: "O18", status: "active" },
  { code: "RRD_O02", display: "O02", status: "active" },
  { code: "RRD_O14", display: "O14", status: "active" },
  { code: "RRE_O02", display: "O02", status: "active" },
  { code: "RRE_O12", display: "O12, O26", status: "active" },
  { code: "RRE_O50", display: "Events O50", status: "active" },
  { code: "RRG_O02", display: "O02", status: "active" },
  { code: "RRG_O16", display: "O16", status: "active" },
  { code: "RRI_I12", display: "I12, I13, I14, I15", status: "active" },
  { code: "RRO_O02", display: "", status: "active" },
  { code: "RSP_E03", display: "E03", status: "active" },
  { code: "RSP_E22", display: "E22", status: "active" },
  { code: "RSP_K11", display: "K11", status: "active" },
  { code: "RSP_K21", display: "K21", status: "active" },
  { code: "RSP_K22", display: "K22", status: "active" },
  { code: "RSP_K23", display: "K23, K24", status: "active" },
  { code: "RSP_K24", display: "K24", status: "active" },
  { code: "RSP_K25", display: "K25", status: "active" },
  { code: "RSP_K31", display: "K31", status: "active" },
  { code: "RSP_K32", display: "K32", status: "active" },
  { code: "RSP_O33", display: "O33", status: "active" },
  { code: "RSP_O34", display: "O34", status: "active" },
  { code: "RSP_Q11", display: "Q11", status: "deprecated" },
  { code: "RSP_Z82", display: "Z82", status: "active" },
  { code: "RSP_Z86", display: "Z86", status: "active" },
  { code: "RSP_Z88", display: "Z88", status: "active" },
  { code: "RSP_Z90", display: "Z90", status: "active" },
  { code: "RTB_K13", display: "K13", status: "active" },
  { code: "RTB_Knn", display: "Knn", status: "active" },
  { code: "RTB_Z74", display: "Z74", status: "active" },
  { code: "SDR_S31", display: "S31, S36", status: "active" },
  { code: "SDR_S32", display: "S32, S37", status: "active" },
  {
    code: "SET_S38",
    display: "Specimen Container Preparation and Specimen Collection Event",
    status: "N",
  },
  {
    code: "SET_S40",
    display: "Specimen Collection Event unsuccessful",
    status: "N",
  },
  { code: "SET_S41", display: "Specimen Movement Event", status: "N" },
  { code: "SET_S45", display: "Specimen Identification Events", status: "N" },
  {
    code: "SET_S50",
    display: "Specimen Procedure Step successful",
    status: "N",
  },
  {
    code: "SET_S52",
    display: "Specimen Procedure Step unsuccessful",
    status: "N",
  },
  {
    code: "SIU_S12",
    display:
      "S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S26",
    status: "active",
  },
  { code: "SLR_S28", display: "S28, S29, S30, S34, S35", status: "active" },
  { code: "SPQ_Q08", display: "Q08", status: "active" },
  { code: "SQM_S25", display: "S25", status: "deprecated" },
  { code: "SQR_S25", display: "S25", status: "deprecated" },
  {
    code: "SRM_S01",
    display: "S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11",
    status: "active",
  },
  { code: "SRM_T12", display: "T12", status: "active" },
  {
    code: "SRR_S01",
    display: "S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11",
    status: "active",
  },
  { code: "SRR_T12", display: "T12", status: "active" },
  { code: "SSR_U04", display: "U04", status: "active" },
  { code: "SSU_U03", display: "U03", status: "active" },
  { code: "STC_S33", display: "S33", status: "active" },
  { code: "SUR_P09", display: "P09", status: "deprecated" },
  { code: "TBR_R08", display: "R08", status: "active" },
  { code: "TBR_R09", display: "R09", status: "active" },
  { code: "TCU_U10", display: "U10, U11", status: "active" },
  { code: "UDM_Q05", display: "Q05", status: "active" },
  { code: "VQQ_Q07", display: "Q07", status: "active" },
  { code: "VXQ_V01", display: "V01", status: "deprecated" },
  { code: "VXR_V03", display: "V03", status: "deprecated" },
  { code: "VXU_V04", display: "V04", status: "active" },
  { code: "VXX_V02", display: "V02", status: "deprecated" },
] as const;
