// Generated profile automaton for BAR_P05 (v2.8)

export const start = 0;
export const finals = new Set<number>([
  5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
  26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
]);
export const alphabet = new Set<string>([
  "ABS",
  "ACC",
  "AL1",
  "BLC",
  "DB1",
  "DG1",
  "DRG",
  "EVN",
  "GT1",
  "IN1",
  "IN2",
  "IN3",
  "MSH",
  "NK1",
  "OBX",
  "PD1",
  "PID",
  "PR1",
  "PRT",
  "PV1",
  "PV2",
  "RMI",
  "ROL",
  "SFT",
  "UAC",
  "UB1",
  "UB2",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["EVN", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [2, new Map([["PID", 5]])],
  [3, new Map([["EVN", 2]])],
  [
    4,
    new Map([
      ["EVN", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [
    5,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PD1", 25],
      ["PR1", 15],
      ["PRT", 22],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 21],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    6,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    7,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    8,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    9,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    10,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    11,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    12,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["IN2", 31],
      ["IN3", 30],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 29],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 28],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    13,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    14,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    15,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 33],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 32],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    16,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    17,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    18,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    19,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    20,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    21,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 34],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    22,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 35],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 21],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    23,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    24,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    25,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 22],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 21],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    26,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    27,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 26],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    28,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 36],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    29,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 37],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 28],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    30,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["IN3", 30],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 29],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 28],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    31,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["IN3", 30],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 29],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 28],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    32,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 38],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    33,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 39],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 32],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    34,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 21],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    35,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 22],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 21],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    36,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 28],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    37,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 29],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 28],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    38,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 27],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 32],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
  [
    39,
    new Map([
      ["ABS", 8],
      ["ACC", 11],
      ["AL1", 18],
      ["BLC", 7],
      ["DB1", 20],
      ["DG1", 17],
      ["DRG", 16],
      ["GT1", 14],
      ["IN1", 12],
      ["NK1", 13],
      ["OBX", 19],
      ["PR1", 15],
      ["PRT", 33],
      ["PV1", 24],
      ["PV2", 23],
      ["RMI", 6],
      ["ROL", 32],
      ["UB1", 10],
      ["UB2", 9],
    ]),
  ],
]);
export const effects = {
  "10:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "10:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "10:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "11:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "11:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "12:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "12:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "13:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "13:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "14:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "14:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "15:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "15:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "16:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "16:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "17:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "17:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "18:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "18:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "19:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "19:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "20:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "20:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "21:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "21:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "22:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "22:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "23:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "23:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "23:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "23:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "24:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "24:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "25:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "25:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "26:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "26:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "27:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "27:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "28:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "28:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "29:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "29:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "30:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "30:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "31:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "31:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "31:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "32:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "32:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "32:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "33:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "33:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "33:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "34:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "34:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "34:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "34:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "34:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "34:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "35:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "35:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "35:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "35:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "35:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "36:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "36:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "36:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "36:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "36:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "36:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "37:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "37:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "37:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "37:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "37:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "38:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "38:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "38:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "38:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "38:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "38:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "39:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "39:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "39:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "39:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "39:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "5:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "5:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "6:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "6:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "7:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "7:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "8:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "8:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "9:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "9:PRT": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
