// Generated segment profile for ARQ (v2.3)

export const segmentId = "ARQ";
export const fields = [
  {
    datatype: "EI",
    id: "ARQ-1",
    item: "860",
    maxLength: 22,
    name: "Placer Appointment ID",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "ARQ-2",
    item: "861",
    maxLength: 22,
    name: "Filler Appointment ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "NM",
    id: "ARQ-3",
    item: "862",
    maxLength: 5,
    name: "Occurrence Number",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "ARQ-4",
    item: "863",
    maxLength: 37,
    name: "Placer Group Number",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "ARQ-5",
    item: "864",
    maxLength: 200,
    name: "Schedule ID",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "ARQ-6",
    item: "865",
    maxLength: 200,
    name: "Request Event Reason",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "ARQ-7",
    item: "866",
    maxLength: 200,
    name: "Appointment Reason",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70276",
  },
  {
    datatype: "CE",
    id: "ARQ-8",
    item: "867",
    maxLength: 200,
    name: "Appointment Type",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70277",
  },
  {
    datatype: "NM",
    id: "ARQ-9",
    item: "868",
    maxLength: 20,
    name: "Appointment Duration",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CE",
    id: "ARQ-10",
    item: "869",
    maxLength: 200,
    name: "Appointment Duration Units",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DR",
    id: "ARQ-11",
    item: "870",
    maxLength: 53,
    name: "Requested Start Date/Time Range",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "ARQ-12",
    item: "871",
    maxLength: 5,
    name: "Priority",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "RI",
    id: "ARQ-13",
    item: "872",
    maxLength: 100,
    name: "Repeating Interval",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "ARQ-14",
    item: "873",
    maxLength: 5,
    name: "Repeating Interval Duration",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "XCN",
    id: "ARQ-15",
    item: "874",
    maxLength: 48,
    name: "Placer Contact Person",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "XTN",
    id: "ARQ-16",
    item: "875",
    maxLength: 40,
    name: "Placer Contact Phone Number",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "XAD",
    id: "ARQ-17",
    item: "876",
    maxLength: 106,
    name: "Placer Contact Address",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "PL",
    id: "ARQ-18",
    item: "877",
    maxLength: 80,
    name: "Placer Contact Location",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "XCN",
    id: "ARQ-19",
    item: "878",
    maxLength: 48,
    name: "Entered By Person",
    repeatable: false,
    required: true,
    sequence: 19,
  },
  {
    datatype: "XTN",
    id: "ARQ-20",
    item: "879",
    maxLength: 40,
    name: "Entered By Phone Number",
    repeatable: true,
    required: false,
    sequence: 20,
  },
  {
    datatype: "PL",
    id: "ARQ-21",
    item: "880",
    maxLength: 80,
    name: "Entered By Location",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "EI",
    id: "ARQ-22",
    item: "881",
    maxLength: 75,
    name: "Parent Placer Appointment ID",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "EI",
    id: "ARQ-23",
    item: "882",
    maxLength: 75,
    name: "Parent Filler Appointment ID",
    repeatable: false,
    required: false,
    sequence: 23,
  },
] as const;
