// Generated segment profile for CDM (v2.3)

export const segmentId = "CDM";
export const fields = [
  {
    datatype: "CE",
    id: "CDM-1",
    item: "982",
    maxLength: 200,
    name: "Primary Key Value",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70132",
  },
  {
    datatype: "CE",
    id: "CDM-2",
    item: "983",
    maxLength: 200,
    name: "Charge Code Alias",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "CDM-3",
    item: "984",
    maxLength: 20,
    name: "Charge Description Short",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "CDM-4",
    item: "985",
    maxLength: 250,
    name: "Charge Description Long",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ID",
    id: "CDM-5",
    item: "986",
    maxLength: 1,
    name: "Description Override Indicator",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70268",
  },
  {
    datatype: "CE",
    id: "CDM-6",
    item: "987",
    maxLength: 60,
    name: "Exploding Charges",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "CDM-7",
    item: "988",
    maxLength: 200,
    name: "Procedure Code",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "CDM-8",
    item: "675",
    maxLength: 1,
    name: "Active/Inactive Flag",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70183",
  },
  {
    datatype: "CE",
    id: "CDM-9",
    item: "990",
    maxLength: 60,
    name: "Inventory Number",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "CDM-10",
    item: "991",
    maxLength: 12,
    name: "Resource Load",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CK",
    id: "CDM-11",
    item: "992",
    maxLength: 200,
    name: "Contract Number",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "XON",
    id: "CDM-12",
    item: "993",
    maxLength: 200,
    name: "Contract Organization",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ID",
    id: "CDM-13",
    item: "994",
    maxLength: 1,
    name: "Room Fee Indicator",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70136",
  },
] as const;
