// Generated segment profile for DB1 (v2.3)

export const segmentId = "DB1";
export const fields = [
  {
    datatype: "SI",
    id: "DB1-1",
    item: "1283",
    maxLength: 4,
    name: "Set ID - DB1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "IS",
    id: "DB1-2",
    item: "1284",
    maxLength: 2,
    name: "Disabled person code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70033",
  },
  {
    datatype: "CX",
    id: "DB1-3",
    item: "1285",
    maxLength: 32,
    name: "Disabled person identifier",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "DB1-4",
    item: "1286",
    maxLength: 1,
    name: "Disabled Indicator",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70136",
  },
  {
    datatype: "DT",
    id: "DB1-5",
    item: "1287",
    maxLength: 8,
    name: "Disability start date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DT",
    id: "DB1-6",
    item: "1288",
    maxLength: 8,
    name: "Disability end date",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DT",
    id: "DB1-7",
    item: "1289",
    maxLength: 8,
    name: "Disability return to work date",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DT",
    id: "DB1-8",
    item: "1290",
    maxLength: 8,
    name: "Disability unable to work date",
    repeatable: false,
    required: false,
    sequence: 8,
  },
] as const;
