// Generated segment profile for FT1 (v2.3)

export const segmentId = "FT1";
export const fields = [
  {
    datatype: "SI",
    id: "FT1-1",
    item: "355",
    maxLength: 4,
    name: "Set ID - Financial Transaction",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "FT1-2",
    item: "356",
    maxLength: 12,
    name: "Transaction ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "FT1-3",
    item: "357",
    maxLength: 10,
    name: "Transaction Batch ID",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "FT1-4",
    item: "358",
    maxLength: 26,
    name: "Transaction Date",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "FT1-5",
    item: "359",
    maxLength: 26,
    name: "Transaction Posting Date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "FT1-6",
    item: "360",
    maxLength: 8,
    name: "Transaction Type",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70017",
  },
  {
    datatype: "CE",
    id: "FT1-7",
    item: "361",
    maxLength: 80,
    name: "Transaction Code",
    repeatable: false,
    required: true,
    sequence: 7,
    table: "HL70132",
  },
  {
    datatype: "ST",
    id: "FT1-8",
    item: "362",
    maxLength: 40,
    name: "Transaction Description",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "FT1-9",
    item: "363",
    maxLength: 40,
    name: "Transaction Description - alternate",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "FT1-10",
    item: "364",
    maxLength: 6,
    name: "Transaction Quantity",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CP",
    id: "FT1-11",
    item: "365",
    maxLength: 12,
    name: "Transaction Amount - Extended",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CP",
    id: "FT1-12",
    item: "366",
    maxLength: 12,
    name: "Transaction Amount - Unit",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CE",
    id: "FT1-13",
    item: "367",
    maxLength: 60,
    name: "Department Code",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70049",
  },
  {
    datatype: "CE",
    id: "FT1-14",
    item: "368",
    maxLength: 8,
    name: "Insurance Plan ID",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70072",
  },
  {
    datatype: "CP",
    id: "FT1-15",
    item: "369",
    maxLength: 12,
    name: "Insurance Amount",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "PL",
    id: "FT1-16",
    item: "133",
    maxLength: 12,
    name: "Assigned Patient Location",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "FT1-17",
    item: "370",
    maxLength: 1,
    name: "Fee Schedule",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70024",
  },
  {
    datatype: "ID",
    id: "FT1-18",
    item: "148",
    maxLength: 2,
    name: "Patient Type",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70018",
  },
  {
    datatype: "CE",
    id: "FT1-19",
    item: "371",
    maxLength: 60,
    name: "Diagnosis Code",
    repeatable: true,
    required: false,
    sequence: 19,
    table: "HL70051",
  },
  {
    datatype: "XCN",
    id: "FT1-20",
    item: "372",
    maxLength: 120,
    name: "Performed By Code",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70084",
  },
  {
    datatype: "XCN",
    id: "FT1-21",
    item: "373",
    maxLength: 120,
    name: "Ordered By Code",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "NM",
    id: "FT1-22",
    item: "374",
    maxLength: 12,
    name: "Unit Cost",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "EI",
    id: "FT1-23",
    item: "217",
    maxLength: 22,
    name: "Filler Order Number",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "XCN",
    id: "FT1-24",
    item: "765",
    maxLength: 120,
    name: "Entered By Code",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "CE",
    id: "FT1-25",
    item: "393",
    maxLength: 80,
    name: "Procedure Code",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70088",
  },
] as const;
