// Generated segment profile for LOC (v2.3)

export const segmentId = "LOC";
export const fields = [
  {
    datatype: "PL",
    id: "LOC-1",
    item: "943",
    maxLength: 20,
    name: "Primary Key Value",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "LOC-2",
    item: "944",
    maxLength: 48,
    name: "Location Description",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "IS",
    id: "LOC-3",
    item: "945",
    maxLength: 2,
    name: "Location Type",
    repeatable: true,
    required: true,
    sequence: 3,
    table: "HL70260",
  },
  {
    datatype: "XON",
    id: "LOC-4",
    item: "947",
    maxLength: 90,
    name: "Organization Name",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XAD",
    id: "LOC-5",
    item: "948",
    maxLength: 106,
    name: "Location Address",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "XTN",
    id: "LOC-6",
    item: "949",
    maxLength: 40,
    name: "Location Phone",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "LOC-7",
    item: "951",
    maxLength: 60,
    name: "License Number",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "LOC-8",
    item: "953",
    maxLength: 3,
    name: "Location Equipment",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70261",
  },
] as const;
