// Generated segment profile for LRL (v2.3)

export const segmentId = "LRL";
export const fields = [
  {
    datatype: "PL",
    id: "LRL-1",
    item: "943",
    maxLength: 20,
    name: "Primary Key Value",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "LRL-2",
    item: "763",
    maxLength: 3,
    name: "Segment Action Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "EI",
    id: "LRL-3",
    item: "764",
    maxLength: 80,
    name: "Segment Unique Key",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "LRL-4",
    item: "1227",
    maxLength: 80,
    name: "Location Relationship ID",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70325",
  },
  {
    datatype: "XON",
    id: "LRL-5",
    item: "1301",
    name: "Organizational Location Relationship Value",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "PL",
    id: "LRL-6",
    item: "1292",
    maxLength: 80,
    name: "Patient Location Relationship Value",
    repeatable: false,
    required: false,
    sequence: 6,
  },
] as const;
