// Generated segment profile for MFI (v2.3)

export const segmentId = "MFI";
export const fields = [
  {
    datatype: "CE",
    id: "MFI-1",
    item: "658",
    maxLength: 60,
    name: "Master File Identifier",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70175",
  },
  {
    datatype: "HD",
    id: "MFI-2",
    item: "659",
    maxLength: 180,
    name: "Master File Application Identifier",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70176",
  },
  {
    datatype: "ID",
    id: "MFI-3",
    item: "660",
    maxLength: 3,
    name: "File-Level Event Code",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70178",
  },
  {
    datatype: "TS",
    id: "MFI-4",
    item: "661",
    maxLength: 26,
    name: "Entered Date/Time",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "MFI-5",
    item: "662",
    maxLength: 26,
    name: "Effective Date/Time",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "MFI-6",
    item: "663",
    maxLength: 2,
    name: "Response Level Code",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70179",
  },
] as const;
