// Generated segment profile for OM4 (v2.3)

export const segmentId = "OM4";
export const fields = [
  {
    sequence: 1,
    id: "OM4-1",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Sequence Number - Test/ Observation Master File",
    item: "586",
  },
  {
    sequence: 2,
    id: "OM4-2",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70170",
    name: "Derived Specimen",
    item: "642",
  },
  {
    sequence: 3,
    id: "OM4-3",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 60,
    name: "Container Description",
    item: "643",
  },
  {
    sequence: 4,
    id: "OM4-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Container Volume",
    item: "644",
  },
  {
    sequence: 5,
    id: "OM4-5",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Container Units",
    item: "645",
  },
  {
    sequence: 6,
    id: "OM4-6",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Specimen",
    item: "646",
  },
  {
    sequence: 7,
    id: "OM4-7",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Additive",
    item: "647",
  },
  {
    sequence: 8,
    id: "OM4-8",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 10_240,
    name: "Preparation",
    item: "648",
  },
  {
    sequence: 9,
    id: "OM4-9",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 10_240,
    name: "Special Handling Requirements",
    item: "649",
  },
  {
    sequence: 10,
    id: "OM4-10",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 20,
    name: "Normal Collection Volume",
    item: "650",
  },
  {
    sequence: 11,
    id: "OM4-11",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 20,
    name: "Minimum Collection Volume",
    item: "651",
  },
  {
    sequence: 12,
    id: "OM4-12",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 10_240,
    name: "Specimen Requirements",
    item: "652",
  },
  {
    sequence: 13,
    id: "OM4-13",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70027",
    name: "Specimen Priorities",
    item: "653",
  },
  {
    sequence: 14,
    id: "OM4-14",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 20,
    name: "Specimen Retention Time",
    item: "654",
  },
] as const;
