// Generated segment profile for ORC (v2.3)

export const segmentId = "ORC";
export const fields = [
  {
    datatype: "ID",
    id: "ORC-1",
    item: "215",
    maxLength: 2,
    name: "Order Control",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70119",
  },
  {
    datatype: "EI",
    id: "ORC-2",
    item: "216",
    maxLength: 22,
    name: "Placer Order Number",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "ORC-3",
    item: "217",
    maxLength: 22,
    name: "Filler Order Number",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "ORC-4",
    item: "218",
    maxLength: 22,
    name: "Placer Group Number",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ID",
    id: "ORC-5",
    item: "219",
    maxLength: 2,
    name: "Order Status",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70038",
  },
  {
    datatype: "ID",
    id: "ORC-6",
    item: "220",
    maxLength: 1,
    name: "Response Flag",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70121",
  },
  {
    datatype: "TQ",
    id: "ORC-7",
    item: "221",
    maxLength: 200,
    name: "Quantity/Timing",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "CM",
    id: "ORC-8",
    item: "222",
    maxLength: 200,
    name: "Parent",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "TS",
    id: "ORC-9",
    item: "223",
    maxLength: 26,
    name: "Date/Time of Transaction",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XCN",
    id: "ORC-10",
    item: "224",
    maxLength: 120,
    name: "Entered By",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XCN",
    id: "ORC-11",
    item: "225",
    maxLength: 120,
    name: "Verified By",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "XCN",
    id: "ORC-12",
    item: "226",
    maxLength: 120,
    name: "Ordering Provider",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "PL",
    id: "ORC-13",
    item: "227",
    maxLength: 80,
    name: "Enterer&apos;s Location",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "TN",
    id: "ORC-14",
    item: "228",
    maxLength: 40,
    name: "Call Back Phone Number",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "TS",
    id: "ORC-15",
    item: "229",
    maxLength: 26,
    name: "Order Effective Date/Time",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CE",
    id: "ORC-16",
    item: "230",
    maxLength: 200,
    name: "Order Control Code Reason",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CE",
    id: "ORC-17",
    item: "231",
    maxLength: 60,
    name: "Entering Organization",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CE",
    id: "ORC-18",
    item: "232",
    maxLength: 60,
    name: "Entering Device",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "XCN",
    id: "ORC-19",
    item: "233",
    maxLength: 120,
    name: "Action By",
    repeatable: false,
    required: false,
    sequence: 19,
  },
] as const;
