// Generated segment profile for PID (v2.3)

export const segmentId = "PID";
export const fields = [
  {
    datatype: "SI",
    id: "PID-1",
    item: "104",
    maxLength: 4,
    name: "Set ID - Patient ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CX",
    id: "PID-2",
    item: "105",
    maxLength: 16,
    name: "Patient ID (External ID)",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CX",
    id: "PID-3",
    item: "106",
    maxLength: 20,
    name: "Patient ID (Internal ID)",
    repeatable: true,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CX",
    id: "PID-4",
    item: "107",
    maxLength: 12,
    name: "Alternate Patient ID",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XPN",
    id: "PID-5",
    item: "108",
    maxLength: 48,
    name: "Patient Name",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "XPN",
    id: "PID-6",
    item: "109",
    maxLength: 48,
    name: "Mother&apos;s Maiden Name",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "PID-7",
    item: "110",
    maxLength: 26,
    name: "Date of Birth",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "IS",
    id: "PID-8",
    item: "111",
    maxLength: 1,
    name: "Sex",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70001",
  },
  {
    datatype: "XPN",
    id: "PID-9",
    item: "112",
    maxLength: 48,
    name: "Patient Alias",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "IS",
    id: "PID-10",
    item: "113",
    maxLength: 1,
    name: "Race",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70005",
  },
  {
    datatype: "XAD",
    id: "PID-11",
    item: "114",
    maxLength: 106,
    name: "Patient Address",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "IS",
    id: "PID-12",
    item: "115",
    maxLength: 4,
    name: "County Code",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "XTN",
    id: "PID-13",
    item: "116",
    maxLength: 40,
    name: "Phone Number - Home",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XTN",
    id: "PID-14",
    item: "117",
    maxLength: 40,
    name: "Phone Number - Business",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CE",
    id: "PID-15",
    item: "118",
    maxLength: 60,
    name: "Primary Language",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70296",
  },
  {
    datatype: "IS",
    id: "PID-16",
    item: "119",
    maxLength: 1,
    name: "Marital Status",
    repeatable: true,
    required: false,
    sequence: 16,
    table: "HL70002",
  },
  {
    datatype: "IS",
    id: "PID-17",
    item: "120",
    maxLength: 3,
    name: "Religion",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70006",
  },
  {
    datatype: "CX",
    id: "PID-18",
    item: "121",
    maxLength: 20,
    name: "Patient Account Number",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    id: "PID-19",
    item: "122",
    maxLength: 16,
    name: "SSN Number - Patient",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "DLN",
    id: "PID-20",
    item: "123",
    maxLength: 25,
    name: "Driver&apos;s License Number",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CX",
    id: "PID-21",
    item: "124",
    maxLength: 20,
    name: "Mother&apos;s Identifier",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "IS",
    id: "PID-22",
    item: "125",
    maxLength: 1,
    name: "Ethnic Group",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70189",
  },
  {
    datatype: "ST",
    id: "PID-23",
    item: "126",
    maxLength: 60,
    name: "Birth Place",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ID",
    id: "PID-24",
    item: "127",
    maxLength: 2,
    name: "Multiple Birth Indicator",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70136",
  },
  {
    datatype: "NM",
    id: "PID-25",
    item: "128",
    maxLength: 2,
    name: "Birth Order",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "IS",
    id: "PID-26",
    item: "129",
    maxLength: 4,
    name: "Citizenship",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70171",
  },
  {
    datatype: "CE",
    id: "PID-27",
    item: "130",
    maxLength: 60,
    name: "Veterans Military Status",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70172",
  },
  {
    datatype: "CE",
    id: "PID-28",
    item: "739",
    maxLength: 80,
    name: "Nationality Code",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70212",
  },
  {
    datatype: "TS",
    id: "PID-29",
    item: "740",
    maxLength: 26,
    name: "Patient Death Date and Time",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "ID",
    id: "PID-30",
    item: "741",
    maxLength: 1,
    name: "Patient Death Indicator",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70136",
  },
] as const;
