// Generated segment profile for PRA (v2.3)

export const segmentId = "PRA";
export const fields = [
  {
    datatype: "ST",
    id: "PRA-1",
    item: "685",
    maxLength: 20,
    name: "PRA - Primary Key Value",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "PRA-2",
    item: "686",
    maxLength: 60,
    name: "Practioner Group",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ID",
    id: "PRA-3",
    item: "687",
    maxLength: 3,
    name: "Practioner Category",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "PRA-4",
    item: "688",
    maxLength: 1,
    name: "Provider Billing",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70186",
  },
  {
    datatype: "CM",
    id: "PRA-5",
    item: "689",
    maxLength: 100,
    name: "Specialty",
    repeatable: true,
    required: false,
    sequence: 5,
    table: "HL70187",
  },
  {
    datatype: "CM",
    id: "PRA-6",
    item: "690",
    maxLength: 100,
    name: "Practitioner ID Numbers",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CM",
    id: "PRA-7",
    item: "691",
    maxLength: 200,
    name: "Privileges",
    repeatable: true,
    required: false,
    sequence: 7,
  },
] as const;
