// Generated segment profile for PRD (v2.3)

export const segmentId = "PRD";
export const fields = [
  {
    sequence: 1,
    id: "PRD-1",
    required: true,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    table: "HL70286",
    name: "Role",
    item: "1155",
  },
  {
    sequence: 2,
    id: "PRD-2",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 106,
    name: "Provider Name",
    item: "1156",
  },
  {
    sequence: 3,
    id: "PRD-3",
    required: false,
    repeatable: false,
    datatype: "XAD",
    maxLength: 60,
    name: "Provider Address",
    item: "1157",
  },
  {
    sequence: 4,
    id: "PRD-4",
    required: false,
    repeatable: false,
    datatype: "PL",
    maxLength: 60,
    name: "Provider Location",
    item: "1158",
  },
  {
    sequence: 5,
    id: "PRD-5",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 20,
    name: "Provider Communication Information",
    item: "1159",
  },
  {
    sequence: 6,
    id: "PRD-6",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70185",
    name: "Preferred Method of Contact",
    item: "684",
  },
  {
    sequence: 7,
    id: "PRD-7",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 100,
    name: "Provider Identifiers",
    item: "1162",
  },
  {
    sequence: 8,
    id: "PRD-8",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective Start Date of Role",
    item: "1163",
  },
  {
    sequence: 9,
    id: "PRD-9",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective End Date of Role",
    item: "1164",
  },
] as const;
