// Generated segment profile for PSH (v2.3)

export const segmentId = "PSH";
export const fields = [
  {
    datatype: "ST",
    id: "PSH-1",
    item: "1233",
    maxLength: 60,
    name: "Report Type",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "PSH-2",
    item: "1234",
    maxLength: 60,
    name: "Report Form Identifier",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "PSH-3",
    item: "1235",
    maxLength: 26,
    name: "Report Date",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "PSH-4",
    item: "1236",
    maxLength: 26,
    name: "Report Interval Start Date",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "PSH-5",
    item: "1237",
    maxLength: 26,
    name: "Report Interval End Date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CQ",
    id: "PSH-6",
    item: "1238",
    maxLength: 12,
    name: "Quantity Manufactured",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CQ",
    id: "PSH-7",
    item: "1239",
    maxLength: 12,
    name: "Quantity Distributed",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "PSH-8",
    item: "1240",
    maxLength: 1,
    name: "Quantity Distributed Method",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70329",
  },
  {
    datatype: "FT",
    id: "PSH-9",
    item: "1241",
    maxLength: 600,
    name: "Quantity Distributed Comment",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CQ",
    id: "PSH-10",
    item: "1242",
    maxLength: 12,
    name: "Quantity in Use",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "PSH-11",
    item: "1243",
    maxLength: 1,
    name: "Quantity in Use Method",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70329",
  },
  {
    datatype: "FT",
    id: "PSH-12",
    item: "1244",
    maxLength: 600,
    name: "Quantity in Use Comment",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "PSH-13",
    item: "1245",
    maxLength: 2,
    name: "Number of Product Experience Reports Filed by Facility",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NM",
    id: "PSH-14",
    item: "1246",
    maxLength: 2,
    name: "Number of Product Experience Reports Filed by Distributor",
    repeatable: true,
    required: false,
    sequence: 14,
  },
] as const;
