// Generated segment profile for PV1 (v2.3)

export const segmentId = "PV1";
export const fields = [
  {
    datatype: "SI",
    id: "PV1-1",
    item: "131",
    maxLength: 4,
    name: "Set ID - Patient Visit",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "PV1-2",
    item: "132",
    maxLength: 1,
    name: "Patient Class",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70004",
  },
  {
    datatype: "PL",
    id: "PV1-3",
    item: "133",
    maxLength: 12,
    name: "Assigned Patient Location",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "PV1-4",
    item: "134",
    maxLength: 2,
    name: "Admission Type",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70007",
  },
  {
    datatype: "CX",
    id: "PV1-5",
    item: "135",
    maxLength: 20,
    name: "Preadmit Number",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "PL",
    id: "PV1-6",
    item: "136",
    maxLength: 12,
    name: "Prior Patient Location",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XCN",
    id: "PV1-7",
    item: "137",
    maxLength: 60,
    name: "Attending Doctor",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70010",
  },
  {
    datatype: "XCN",
    id: "PV1-8",
    item: "138",
    maxLength: 60,
    name: "Referring Doctor",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70010",
  },
  {
    datatype: "XCN",
    id: "PV1-9",
    item: "139",
    maxLength: 60,
    name: "Consulting Doctor",
    repeatable: true,
    required: false,
    sequence: 9,
    table: "HL70010",
  },
  {
    datatype: "ID",
    id: "PV1-10",
    item: "140",
    maxLength: 3,
    name: "Hospital Service",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70069",
  },
  {
    datatype: "PL",
    id: "PV1-11",
    item: "141",
    maxLength: 12,
    name: "Temporary Location",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "PV1-12",
    item: "142",
    maxLength: 2,
    name: "Preadmit Test Indicator",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70087",
  },
  {
    datatype: "ID",
    id: "PV1-13",
    item: "143",
    maxLength: 2,
    name: "Readmission Indicator",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70092",
  },
  {
    datatype: "ID",
    id: "PV1-14",
    item: "144",
    maxLength: 3,
    name: "Admit Source",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70023",
  },
  {
    datatype: "IS",
    id: "PV1-15",
    item: "145",
    maxLength: 2,
    name: "Ambulatory Status",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70009",
  },
  {
    datatype: "ID",
    id: "PV1-16",
    item: "146",
    maxLength: 2,
    name: "VIP Indicator",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70099",
  },
  {
    datatype: "XCN",
    id: "PV1-17",
    item: "147",
    maxLength: 60,
    name: "Admitting Doctor",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70010",
  },
  {
    datatype: "ID",
    id: "PV1-18",
    item: "148",
    maxLength: 2,
    name: "Patient Type",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70018",
  },
  {
    datatype: "CX",
    id: "PV1-19",
    item: "149",
    maxLength: 15,
    name: "Visit Number",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "FC",
    id: "PV1-20",
    item: "150",
    maxLength: 50,
    name: "Financial Class",
    repeatable: true,
    required: false,
    sequence: 20,
    table: "HL70064",
  },
  {
    datatype: "ID",
    id: "PV1-21",
    item: "151",
    maxLength: 2,
    name: "Charge Price Indicator",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70032",
  },
  {
    datatype: "ID",
    id: "PV1-22",
    item: "152",
    maxLength: 2,
    name: "Courtesy Code",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70045",
  },
  {
    datatype: "ID",
    id: "PV1-23",
    item: "153",
    maxLength: 2,
    name: "Credit Rating",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70046",
  },
  {
    datatype: "ID",
    id: "PV1-24",
    item: "154",
    maxLength: 2,
    name: "Contract Code",
    repeatable: true,
    required: false,
    sequence: 24,
    table: "HL70044",
  },
  {
    datatype: "DT",
    id: "PV1-25",
    item: "155",
    maxLength: 8,
    name: "Contract Effective Date",
    repeatable: true,
    required: false,
    sequence: 25,
  },
  {
    datatype: "NM",
    id: "PV1-26",
    item: "156",
    maxLength: 12,
    name: "Contract Amount",
    repeatable: true,
    required: false,
    sequence: 26,
  },
  {
    datatype: "NM",
    id: "PV1-27",
    item: "157",
    maxLength: 3,
    name: "Contract Period",
    repeatable: true,
    required: false,
    sequence: 27,
  },
  {
    datatype: "ID",
    id: "PV1-28",
    item: "158",
    maxLength: 2,
    name: "Interest Code",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70073",
  },
  {
    datatype: "ID",
    id: "PV1-29",
    item: "159",
    maxLength: 1,
    name: "Transfer to Bad Debt Code",
    repeatable: false,
    required: false,
    sequence: 29,
    table: "HL70110",
  },
  {
    datatype: "DT",
    id: "PV1-30",
    item: "160",
    maxLength: 8,
    name: "Transfer to Bad Debt Date",
    repeatable: false,
    required: false,
    sequence: 30,
  },
  {
    datatype: "ID",
    id: "PV1-31",
    item: "161",
    maxLength: 10,
    name: "Bad Debt Agency Code",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70021",
  },
  {
    datatype: "NM",
    id: "PV1-32",
    item: "162",
    maxLength: 12,
    name: "Bad Debt Transfer Amount",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "NM",
    id: "PV1-33",
    item: "163",
    maxLength: 12,
    name: "Bad Debt Recovery Amount",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "ID",
    id: "PV1-34",
    item: "164",
    maxLength: 1,
    name: "Delete Account Indicator",
    repeatable: false,
    required: false,
    sequence: 34,
    table: "HL70111",
  },
  {
    datatype: "DT",
    id: "PV1-35",
    item: "165",
    maxLength: 8,
    name: "Delete Account Date",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "ID",
    id: "PV1-36",
    item: "166",
    maxLength: 3,
    name: "Discharge Disposition",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL70112",
  },
  {
    datatype: "CM",
    id: "PV1-37",
    item: "167",
    maxLength: 25,
    name: "Discharged to Location",
    repeatable: false,
    required: false,
    sequence: 37,
    table: "HL70113",
  },
  {
    datatype: "ID",
    id: "PV1-38",
    item: "168",
    maxLength: 2,
    name: "Diet Type",
    repeatable: false,
    required: false,
    sequence: 38,
    table: "HL70114",
  },
  {
    datatype: "ID",
    id: "PV1-39",
    item: "169",
    maxLength: 2,
    name: "Servicing Facility",
    repeatable: false,
    required: false,
    sequence: 39,
    table: "HL70115",
  },
  {
    datatype: "IS",
    id: "PV1-40",
    item: "170",
    maxLength: 1,
    name: "Bed Status",
    repeatable: false,
    required: false,
    sequence: 40,
    table: "HL70116",
  },
  {
    datatype: "ID",
    id: "PV1-41",
    item: "171",
    maxLength: 2,
    name: "Account Status",
    repeatable: false,
    required: false,
    sequence: 41,
    table: "HL70117",
  },
  {
    datatype: "PL",
    id: "PV1-42",
    item: "172",
    maxLength: 12,
    name: "Pending Location",
    repeatable: false,
    required: false,
    sequence: 42,
  },
  {
    datatype: "PL",
    id: "PV1-43",
    item: "173",
    maxLength: 12,
    name: "Prior Temporary Location",
    repeatable: false,
    required: false,
    sequence: 43,
  },
  {
    datatype: "TS",
    id: "PV1-44",
    item: "174",
    maxLength: 26,
    name: "Admit Date/Time",
    repeatable: false,
    required: false,
    sequence: 44,
  },
  {
    datatype: "TS",
    id: "PV1-45",
    item: "175",
    maxLength: 26,
    name: "Discharge Date/Time",
    repeatable: false,
    required: false,
    sequence: 45,
  },
  {
    datatype: "NM",
    id: "PV1-46",
    item: "176",
    maxLength: 12,
    name: "Current Patient Balance",
    repeatable: false,
    required: false,
    sequence: 46,
  },
  {
    datatype: "NM",
    id: "PV1-47",
    item: "177",
    maxLength: 12,
    name: "Total Charges",
    repeatable: false,
    required: false,
    sequence: 47,
  },
  {
    datatype: "NM",
    id: "PV1-48",
    item: "178",
    maxLength: 12,
    name: "Total Adjustments",
    repeatable: false,
    required: false,
    sequence: 48,
  },
  {
    datatype: "NM",
    id: "PV1-49",
    item: "179",
    maxLength: 12,
    name: "Total Payments",
    repeatable: false,
    required: false,
    sequence: 49,
  },
  {
    datatype: "CX",
    id: "PV1-50",
    item: "180",
    maxLength: 20,
    name: "Alternate Visit ID",
    repeatable: false,
    required: false,
    sequence: 50,
    table: "HL70192",
  },
  {
    datatype: "IS",
    id: "PV1-51",
    item: "1226",
    maxLength: 1,
    name: "Visit Indicator",
    repeatable: false,
    required: false,
    sequence: 51,
    table: "HL70326",
  },
  {
    datatype: "XCN",
    id: "PV1-52",
    item: "1274",
    maxLength: 60,
    name: "Other Healthcare Provider",
    repeatable: true,
    required: false,
    sequence: 52,
    table: "HL70010",
  },
] as const;
