// Generated segment profile for UB2 (v2.3)

export const segmentId = "UB2";
export const fields = [
  {
    datatype: "SI",
    id: "UB2-1",
    item: "553",
    maxLength: 4,
    name: "Set ID - UB2",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "UB2-2",
    item: "554",
    maxLength: 3,
    name: "Co-Insurance Days (9)",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ID",
    id: "UB2-3",
    item: "555",
    maxLength: 2,
    name: "Condition Code (24-30)",
    repeatable: true,
    required: false,
    sequence: 3,
    table: "HL70043",
  },
  {
    datatype: "ST",
    id: "UB2-4",
    item: "556",
    maxLength: 3,
    name: "Covered Days (7)",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "UB2-5",
    item: "557",
    maxLength: 4,
    name: "Non-Covered Days (8)",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CM",
    id: "UB2-6",
    item: "558",
    maxLength: 11,
    name: "Value Amount &amp; Code",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CM",
    id: "UB2-7",
    item: "559",
    maxLength: 11,
    name: "Occurrence Code &amp; Date (32-35)",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CM",
    id: "UB2-8",
    item: "560",
    maxLength: 28,
    name: "Occurrence Span Code/Dates (36)",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "UB2-9",
    item: "561",
    maxLength: 29,
    name: "UB92 Locator 2 (State)",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "UB2-10",
    item: "562",
    maxLength: 12,
    name: "UB92 Locator 11 (State)",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "UB2-11",
    item: "563",
    maxLength: 5,
    name: "UB92 Locator 31 (National)",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "UB2-12",
    item: "564",
    maxLength: 23,
    name: "Document Control Number",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "UB2-13",
    item: "565",
    maxLength: 4,
    name: "UB92 Locator 49 (National)",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "UB2-14",
    item: "566",
    maxLength: 14,
    name: "UB92 Locator 56 (State)",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "UB2-15",
    item: "567",
    maxLength: 27,
    name: "UB92 Locator 57 (National)",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ST",
    id: "UB2-16",
    item: "568",
    maxLength: 2,
    name: "UB92 Locator 78 (State)",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "NM",
    id: "UB2-17",
    item: "815",
    maxLength: 3,
    name: "Special Visit Count",
    repeatable: false,
    required: false,
    sequence: 17,
  },
] as const;
