// Generated segment profile for VTQ (v2.3)

export const segmentId = "VTQ";
export const fields = [
  {
    datatype: "ST",
    id: "VTQ-1",
    item: "696",
    maxLength: 32,
    name: "Query tag",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "VTQ-2",
    item: "697",
    maxLength: 1,
    name: "Query/ Response Format Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70106",
  },
  {
    datatype: "CE",
    id: "VTQ-3",
    item: "698",
    maxLength: 60,
    name: "VT Query Name",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "VTQ-4",
    item: "699",
    maxLength: 60,
    name: "Virtual Table Name",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "QSC",
    id: "VTQ-5",
    item: "700",
    maxLength: 256,
    name: "Selection Criteria",
    repeatable: true,
    required: false,
    sequence: 5,
  },
] as const;
