// Generated segment profile for CTD (v2.3.1)

export const segmentId = "CTD";
export const fields = [
  {
    datatype: "CE",
    id: "CTD-1",
    item: "196",
    maxLength: 200,
    name: "Contact Role",
    repeatable: true,
    required: false,
    sequence: 1,
    table: "HL70131",
  },
  {
    datatype: "XPN",
    id: "CTD-2",
    item: "1165",
    maxLength: 106,
    name: "Contact Name",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XAD",
    id: "CTD-3",
    item: "1166",
    maxLength: 200,
    name: "Contact Address",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "PL",
    id: "CTD-4",
    item: "1167",
    maxLength: 60,
    name: "Contact Location",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XTN",
    id: "CTD-5",
    item: "1168",
    maxLength: 100,
    name: "Contact Communication Information",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "CTD-6",
    item: "684",
    maxLength: 200,
    name: "Preferred Method Of Contact",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70185",
  },
  {
    datatype: "PI",
    id: "CTD-7",
    item: "1171",
    maxLength: 100,
    name: "Contact Identifiers",
    repeatable: true,
    required: false,
    sequence: 7,
  },
] as const;
