// Generated segment profile for DRG (v2.3.1)

export const segmentId = "DRG";
export const fields = [
  {
    sequence: 1,
    id: "DRG-1",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70055",
    name: "Diagnostic Related Group",
    item: "382",
  },
  {
    sequence: 2,
    id: "DRG-2",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "DRG Assigned Date/Time",
    item: "769",
  },
  {
    sequence: 3,
    id: "DRG-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "DRG Approval Indicator",
    item: "383",
  },
  {
    sequence: 4,
    id: "DRG-4",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70056",
    name: "DRG Grouper Review Code",
    item: "384",
  },
  {
    sequence: 5,
    id: "DRG-5",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70083",
    name: "Outlier Type",
    item: "385",
  },
  {
    sequence: 6,
    id: "DRG-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    name: "Outlier Days",
    item: "386",
  },
  {
    sequence: 7,
    id: "DRG-7",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    name: "Outlier Cost",
    item: "387",
  },
  {
    sequence: 8,
    id: "DRG-8",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70229",
    name: "DRG Payor",
    item: "770",
  },
  {
    sequence: 9,
    id: "DRG-9",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 9,
    name: "Outlier Reimbursement",
    item: "771",
  },
  {
    sequence: 10,
    id: "DRG-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Confidential Indicator",
    item: "767",
  },
] as const;
