// Generated segment profile for NSC (v2.3.1)

export const segmentId = "NSC";
export const fields = [
  {
    datatype: "IS",
    id: "NSC-1",
    item: "1188",
    name: "Network Change Type",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70333",
  },
  {
    datatype: "ST",
    id: "NSC-2",
    item: "1189",
    name: "Current CPU",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "NSC-3",
    item: "1190",
    name: "Current Fileserver",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "NSC-4",
    item: "1191",
    name: "Current Application",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "NSC-5",
    item: "1192",
    name: "Current Facility",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "NSC-6",
    item: "1193",
    name: "New CPU",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "NSC-7",
    item: "1194",
    name: "New Fileserver",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "NSC-8",
    item: "1195",
    name: "New Application",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "NSC-9",
    item: "1196",
    name: "New Facility",
    repeatable: false,
    required: false,
    sequence: 9,
  },
] as const;
