// Generated segment profile for PD1 (v2.3.1)

export const segmentId = "PD1";
export const fields = [
  {
    datatype: "IS",
    id: "PD1-1",
    item: "755",
    maxLength: 2,
    name: "Living Dependency",
    repeatable: true,
    required: false,
    sequence: 1,
    table: "HL70223",
  },
  {
    datatype: "IS",
    id: "PD1-2",
    item: "742",
    maxLength: 2,
    name: "Living Arrangement",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70220",
  },
  {
    datatype: "XON",
    id: "PD1-3",
    item: "756",
    maxLength: 90,
    name: "Patient Primary Facility",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "XCN",
    id: "PD1-4",
    item: "757",
    maxLength: 90,
    name: "Patient Primary Care Provider Name &amp; ID No.",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "IS",
    id: "PD1-5",
    item: "745",
    maxLength: 2,
    name: "Student Indicator",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70231",
  },
  {
    datatype: "IS",
    id: "PD1-6",
    item: "753",
    maxLength: 2,
    name: "Handicap",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70295",
  },
  {
    datatype: "IS",
    id: "PD1-7",
    item: "759",
    maxLength: 2,
    name: "Living Will",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70315",
  },
  {
    datatype: "IS",
    id: "PD1-8",
    item: "760",
    maxLength: 2,
    name: "Organ Donor",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70316",
  },
  {
    datatype: "ID",
    id: "PD1-9",
    item: "761",
    maxLength: 1,
    name: "Separate Bill",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70136",
  },
  {
    datatype: "CX",
    id: "PD1-10",
    item: "762",
    maxLength: 20,
    name: "Duplicate Patient",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CE",
    id: "PD1-11",
    item: "743",
    maxLength: 80,
    name: "Publicity Code",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70215",
  },
  {
    datatype: "ID",
    id: "PD1-12",
    item: "744",
    maxLength: 1,
    name: "Protection Indicator",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70136",
  },
] as const;
