// Generated segment profile for PDC (v2.3.1)

export const segmentId = "PDC";
export const fields = [
  {
    datatype: "XON",
    id: "PDC-1",
    item: "1247",
    maxLength: 80,
    name: "Manufacturer/Distributor",
    repeatable: true,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "PDC-2",
    item: "1248",
    maxLength: 60,
    name: "Country",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "PDC-3",
    item: "1249",
    maxLength: 60,
    name: "Brand Name",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "PDC-4",
    item: "1250",
    maxLength: 60,
    name: "Device Family Name",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "PDC-5",
    item: "1251",
    maxLength: 60,
    name: "Generic Name",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "PDC-6",
    item: "1252",
    maxLength: 60,
    name: "Model Identifier",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "PDC-7",
    item: "1253",
    maxLength: 60,
    name: "Catalogue Identifier",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "PDC-8",
    item: "1254",
    maxLength: 60,
    name: "Other Identifier",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CE",
    id: "PDC-9",
    item: "1255",
    maxLength: 60,
    name: "Product Code",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "PDC-10",
    item: "1256",
    maxLength: 4,
    name: "Marketing Basis",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70330",
  },
  {
    datatype: "ST",
    id: "PDC-11",
    item: "1257",
    maxLength: 60,
    name: "Marketing Approval ID",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CQ",
    id: "PDC-12",
    item: "1258",
    maxLength: 12,
    name: "Labeled Shelf Life",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CQ",
    id: "PDC-13",
    item: "1259",
    maxLength: 12,
    name: "Expected Shelf Life",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "TS",
    id: "PDC-14",
    item: "1260",
    maxLength: 26,
    name: "Date First Marketed",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "TS",
    id: "PDC-15",
    item: "1261",
    maxLength: 26,
    name: "Date Last Marketed",
    repeatable: false,
    required: false,
    sequence: 15,
  },
] as const;
