// Generated segment profile for PES (v2.3.1)

export const segmentId = "PES";
export const fields = [
  {
    sequence: 1,
    id: "PES-1",
    required: false,
    repeatable: true,
    datatype: "XON",
    maxLength: 80,
    name: "Sender Organization Name",
    item: "1059",
  },
  {
    sequence: 2,
    id: "PES-2",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 60,
    name: "Sender Individual Name",
    item: "1060",
  },
  {
    sequence: 3,
    id: "PES-3",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 200,
    name: "Sender Address",
    item: "1062",
  },
  {
    sequence: 4,
    id: "PES-4",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 44,
    name: "Sender Telephone",
    item: "1063",
  },
  {
    sequence: 5,
    id: "PES-5",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 75,
    name: "Sender Event Identifier",
    item: "1064",
  },
  {
    sequence: 6,
    id: "PES-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    name: "Sender Sequence Number",
    item: "1065",
  },
  {
    sequence: 7,
    id: "PES-7",
    required: false,
    repeatable: true,
    datatype: "FT",
    maxLength: 600,
    name: "Sender Event Description",
    item: "1066",
  },
  {
    sequence: 8,
    id: "PES-8",
    required: false,
    repeatable: false,
    datatype: "FT",
    maxLength: 600,
    name: "Sender Comment",
    item: "1067",
  },
  {
    sequence: 9,
    id: "PES-9",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Sender Aware Date/Time",
    item: "1068",
  },
  {
    sequence: 10,
    id: "PES-10",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Event Report Date",
    item: "1069",
  },
  {
    sequence: 11,
    id: "PES-11",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 3,
    table: "HL70234",
    name: "Event Report Timing/Type",
    item: "1070",
  },
  {
    sequence: 12,
    id: "PES-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70235",
    name: "Event Report Source",
    item: "1071",
  },
  {
    sequence: 13,
    id: "PES-13",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 1,
    table: "HL70236",
    name: "Event Reported To",
    item: "1072",
  },
] as const;
