// Generated segment profile for PID (v2.3.1)

export const segmentId = "PID";
export const fields = [
  {
    sequence: 1,
    id: "PID-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - PID",
    item: "104",
  },
  {
    sequence: 2,
    id: "PID-2",
    required: false,
    repeatable: false,
    datatype: "CX",
    maxLength: 20,
    name: "Patient ID",
    item: "105",
  },
  {
    sequence: 3,
    id: "PID-3",
    required: true,
    repeatable: true,
    datatype: "CX",
    maxLength: 20,
    name: "Patient Identifier List",
    item: "106",
  },
  {
    sequence: 4,
    id: "PID-4",
    required: false,
    repeatable: true,
    datatype: "CX",
    maxLength: 20,
    name: "Alternate Patient ID - PID",
    item: "107",
  },
  {
    sequence: 5,
    id: "PID-5",
    required: true,
    repeatable: true,
    datatype: "XPN",
    maxLength: 48,
    name: "Patient Name",
    item: "108",
  },
  {
    sequence: 6,
    id: "PID-6",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 48,
    name: "Mother’s Maiden Name",
    item: "109",
  },
  {
    sequence: 7,
    id: "PID-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Date/Time Of Birth",
    item: "110",
  },
  {
    sequence: 8,
    id: "PID-8",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70001",
    name: "Sex",
    item: "111",
  },
  {
    sequence: 9,
    id: "PID-9",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 48,
    name: "Patient Alias",
    item: "112",
  },
  {
    sequence: 10,
    id: "PID-10",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 80,
    table: "HL70005",
    name: "Race",
    item: "113",
  },
  {
    sequence: 11,
    id: "PID-11",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 106,
    name: "Patient Address",
    item: "114",
  },
  {
    sequence: 12,
    id: "PID-12",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 4,
    table: "HL70289",
    name: "County Code",
    item: "115",
  },
  {
    sequence: 13,
    id: "PID-13",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 40,
    name: "Phone Number - Home",
    item: "116",
  },
  {
    sequence: 14,
    id: "PID-14",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 40,
    name: "Phone Number - Business",
    item: "117",
  },
  {
    sequence: 15,
    id: "PID-15",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70296",
    name: "Primary Language",
    item: "118",
  },
  {
    sequence: 16,
    id: "PID-16",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    table: "HL70002",
    name: "Marital Status",
    item: "119",
  },
  {
    sequence: 17,
    id: "PID-17",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    table: "HL70006",
    name: "Religion",
    item: "120",
  },
  {
    sequence: 18,
    id: "PID-18",
    required: false,
    repeatable: false,
    datatype: "CX",
    maxLength: 20,
    name: "Patient Account Number",
    item: "121",
  },
  {
    sequence: 19,
    id: "PID-19",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 16,
    name: "SSN Number - Patient",
    item: "122",
  },
  {
    sequence: 20,
    id: "PID-20",
    required: false,
    repeatable: false,
    datatype: "DLN",
    maxLength: 25,
    name: "Driver&apos;s License Number - Patient",
    item: "123",
  },
  {
    sequence: 21,
    id: "PID-21",
    required: false,
    repeatable: true,
    datatype: "CX",
    maxLength: 20,
    name: "Mother&apos;s Identifier",
    item: "124",
  },
  {
    sequence: 22,
    id: "PID-22",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 80,
    table: "HL70189",
    name: "Ethnic Group",
    item: "125",
  },
  {
    sequence: 23,
    id: "PID-23",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Birth Place",
    item: "126",
  },
  {
    sequence: 24,
    id: "PID-24",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Multiple Birth Indicator",
    item: "127",
  },
  {
    sequence: 25,
    id: "PID-25",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    name: "Birth Order",
    item: "128",
  },
  {
    sequence: 26,
    id: "PID-26",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 80,
    table: "HL70171",
    name: "Citizenship",
    item: "129",
  },
  {
    sequence: 27,
    id: "PID-27",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70172",
    name: "Veterans Military Status",
    item: "130",
  },
  {
    sequence: 28,
    id: "PID-28",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    table: "HL70212",
    name: "Nationality",
    item: "739",
  },
  {
    sequence: 29,
    id: "PID-29",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Patient Death Date and Time",
    item: "740",
  },
  {
    sequence: 30,
    id: "PID-30",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Patient Death Indicator",
    item: "741",
  },
] as const;
