// Generated segment profile for PRC (v2.3.1)

export const segmentId = "PRC";
export const fields = [
  {
    datatype: "CE",
    id: "PRC-1",
    item: "982",
    maxLength: 200,
    name: "Primary Key Value - PRC",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70132",
  },
  {
    datatype: "CE",
    id: "PRC-2",
    item: "995",
    maxLength: 60,
    name: "Facility ID - PRC",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CE",
    id: "PRC-3",
    item: "676",
    maxLength: 200,
    name: "Department",
    repeatable: true,
    required: false,
    sequence: 3,
    table: "HL70184",
  },
  {
    datatype: "IS",
    id: "PRC-4",
    item: "967",
    maxLength: 1,
    name: "Valid Patient Classes",
    repeatable: true,
    required: false,
    sequence: 4,
    table: "HL70004",
  },
  {
    datatype: "CP",
    id: "PRC-5",
    item: "998",
    maxLength: 12,
    name: "Price",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "PRC-6",
    item: "999",
    maxLength: 200,
    name: "Formula",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "PRC-7",
    item: "1000",
    maxLength: 4,
    name: "Minimum Quantity",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "PRC-8",
    item: "1001",
    maxLength: 4,
    name: "Maximum Quantity",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "MO",
    id: "PRC-9",
    item: "1002",
    maxLength: 12,
    name: "Minimum Price",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "MO",
    id: "PRC-10",
    item: "1003",
    maxLength: 12,
    name: "Maximum Price",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "TS",
    id: "PRC-11",
    item: "1004",
    maxLength: 26,
    name: "Effective Start Date",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "TS",
    id: "PRC-12",
    item: "1005",
    maxLength: 26,
    name: "Effective End Date",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "IS",
    id: "PRC-13",
    item: "1006",
    maxLength: 1,
    name: "Price Override Flag",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70268",
  },
  {
    datatype: "CE",
    id: "PRC-14",
    item: "1007",
    maxLength: 60,
    name: "Billing Category",
    repeatable: true,
    required: false,
    sequence: 14,
    table: "HL70293",
  },
  {
    datatype: "ID",
    id: "PRC-15",
    item: "1008",
    maxLength: 1,
    name: "Chargeable Flag",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "PRC-16",
    item: "675",
    maxLength: 1,
    name: "Active/Inactive Flag",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70183",
  },
  {
    datatype: "MO",
    id: "PRC-17",
    item: "989",
    maxLength: 12,
    name: "Cost",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "IS",
    id: "PRC-18",
    item: "1009",
    maxLength: 1,
    name: "Charge On Indicator",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70269",
  },
] as const;
