// Generated segment profile for QRF (v2.3.1)

export const segmentId = "QRF";
export const fields = [
  {
    datatype: "ST",
    id: "QRF-1",
    item: "37",
    maxLength: 20,
    name: "Where Subject Filter",
    repeatable: true,
    required: true,
    sequence: 1,
  },
  {
    datatype: "TS",
    id: "QRF-2",
    item: "38",
    maxLength: 26,
    name: "When Data Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "QRF-3",
    item: "39",
    maxLength: 26,
    name: "When Data End Date/Time",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "QRF-4",
    item: "40",
    maxLength: 60,
    name: "What User Qualifier",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "QRF-5",
    item: "41",
    maxLength: 60,
    name: "Other QRY Subject Filter",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "QRF-6",
    item: "42",
    maxLength: 12,
    name: "Which Date/Time Qualifier",
    repeatable: true,
    required: false,
    sequence: 6,
    table: "HL70156",
  },
  {
    datatype: "ID",
    id: "QRF-7",
    item: "43",
    maxLength: 12,
    name: "Which Date/Time Status Qualifier",
    repeatable: true,
    required: false,
    sequence: 7,
    table: "HL70157",
  },
  {
    datatype: "ID",
    id: "QRF-8",
    item: "44",
    maxLength: 12,
    name: "Date/Time Selection Qualifier",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70158",
  },
  {
    datatype: "TQ",
    id: "QRF-9",
    item: "694",
    maxLength: 60,
    name: "When Quantity/Timing Qualifier",
    repeatable: false,
    required: false,
    sequence: 9,
  },
] as const;
