// Generated segment profile for ROL (v2.3.1)

export const segmentId = "ROL";
export const fields = [
  {
    datatype: "EI",
    id: "ROL-1",
    item: "1206",
    maxLength: 60,
    name: "Role Instance ID",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "ROL-2",
    item: "816",
    maxLength: 2,
    name: "Action Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70287",
  },
  {
    datatype: "CE",
    id: "ROL-3",
    item: "1197",
    maxLength: 80,
    name: "Role-ROL",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "XCN",
    id: "ROL-4",
    item: "1198",
    maxLength: 80,
    name: "Role Person",
    repeatable: true,
    required: true,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "ROL-5",
    item: "1199",
    maxLength: 26,
    name: "Role Begin Date/Time",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TS",
    id: "ROL-6",
    item: "1200",
    maxLength: 26,
    name: "Role End Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "ROL-7",
    item: "1201",
    maxLength: 80,
    name: "Role Duration",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CE",
    id: "ROL-8",
    item: "1205",
    maxLength: 80,
    name: "Role Action Reason",
    repeatable: false,
    required: false,
    sequence: 8,
  },
] as const;
