// Generated segment profile for RQ1 (v2.3.1)

export const segmentId = "RQ1";
export const fields = [
  {
    datatype: "ST",
    id: "RQ1-1",
    item: "285",
    maxLength: 10,
    name: "Anticipated Price",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "RQ1-2",
    item: "286",
    maxLength: 60,
    name: "Manufacturer ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "RQ1-3",
    item: "287",
    maxLength: 16,
    name: "Manufacturer’s Catalog",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "RQ1-4",
    item: "288",
    maxLength: 60,
    name: "Vendor ID",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "RQ1-5",
    item: "289",
    maxLength: 16,
    name: "Vendor Catalog",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "RQ1-6",
    item: "290",
    maxLength: 1,
    name: "Taxable",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "RQ1-7",
    item: "291",
    maxLength: 1,
    name: "Substitute Allowed",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70136",
  },
] as const;
