// Generated segment profile for RXA (v2.3.1)

export const segmentId = "RXA";
export const fields = [
  {
    datatype: "NM",
    id: "RXA-1",
    item: "342",
    maxLength: 4,
    name: "Give Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "RXA-2",
    item: "344",
    maxLength: 4,
    name: "Administration Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "RXA-3",
    item: "345",
    maxLength: 26,
    name: "Date/Time Start of Administration",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "RXA-4",
    item: "346",
    maxLength: 26,
    name: "Date/Time End of Administration",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "RXA-5",
    item: "347",
    maxLength: 100,
    name: "Administered Code",
    repeatable: false,
    required: true,
    sequence: 5,
    table: "HL70292",
  },
  {
    datatype: "NM",
    id: "RXA-6",
    item: "348",
    maxLength: 20,
    name: "Administered Amount",
    repeatable: false,
    required: true,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "RXA-7",
    item: "349",
    maxLength: 60,
    name: "Administered Units",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CE",
    id: "RXA-8",
    item: "350",
    maxLength: 60,
    name: "Administered Dosage Form",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CE",
    id: "RXA-9",
    item: "351",
    maxLength: 200,
    name: "Administration Notes",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XCN",
    id: "RXA-10",
    item: "352",
    maxLength: 200,
    name: "Administering Provider",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "LA2",
    id: "RXA-11",
    item: "353",
    maxLength: 200,
    name: "Administered-at Location",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "RXA-12",
    item: "354",
    maxLength: 20,
    name: "Administered Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "RXA-13",
    item: "1134",
    maxLength: 20,
    name: "Administered Strength",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CE",
    id: "RXA-14",
    item: "1135",
    maxLength: 60,
    name: "Administered Strength Units",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "RXA-15",
    item: "1129",
    maxLength: 20,
    name: "Substance Lot Number",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "TS",
    id: "RXA-16",
    item: "1130",
    maxLength: 26,
    name: "Substance Expiration Date",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CE",
    id: "RXA-17",
    item: "1131",
    maxLength: 60,
    name: "Substance Manufacturer Name",
    repeatable: true,
    required: false,
    sequence: 17,
    table: "HL70227",
  },
  {
    datatype: "CE",
    id: "RXA-18",
    item: "1136",
    maxLength: 200,
    name: "Substance Refusal Reason",
    repeatable: true,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CE",
    id: "RXA-19",
    item: "1123",
    maxLength: 200,
    name: "Indication",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "RXA-20",
    item: "1223",
    maxLength: 2,
    name: "Completion Status",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70322",
  },
  {
    datatype: "ID",
    id: "RXA-21",
    item: "1224",
    maxLength: 2,
    name: "Action Code-RXA",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70323",
  },
  {
    datatype: "TS",
    id: "RXA-22",
    item: "1225",
    maxLength: 26,
    name: "System Entry Date/Time",
    repeatable: false,
    required: false,
    sequence: 22,
  },
] as const;
