// Generated segment profile for AUT (v2.8.1)

export const segmentId = "AUT";
export const fields = [
  {
    datatype: "CWE",
    id: "AUT-1",
    item: "1146",
    name: "Authorizing Payor, Plan ID",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70072",
  },
  {
    datatype: "CWE",
    id: "AUT-2",
    item: "1147",
    name: "Authorizing Payor, Company ID",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70285",
  },
  {
    datatype: "ST",
    id: "AUT-3",
    item: "1148",
    name: "Authorizing Payor, Company Name",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "DTM",
    id: "AUT-4",
    item: "1149",
    name: "Authorization Effective Date",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "DTM",
    id: "AUT-5",
    item: "1150",
    name: "Authorization Expiration Date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "EI",
    id: "AUT-6",
    item: "1151",
    name: "Authorization Identifier",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CP",
    id: "AUT-7",
    item: "1152",
    name: "Reimbursement Limit",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CQ",
    id: "AUT-8",
    item: "1153",
    name: "Requested Number of Treatments",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CQ",
    id: "AUT-9",
    item: "1154",
    name: "Authorized Number of Treatments",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "DTM",
    id: "AUT-10",
    item: "1145",
    name: "Process Date",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "AUT-11",
    item: "2375",
    name: "Requested Discipline(s)",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "AUT-12",
    item: "2376",
    name: "Authorized Discipline(s)",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "AUT-13",
    item: "3413",
    maxLength: 250,
    name: "Authorization Referral Type",
    repeatable: false,
    required: true,
    sequence: 13,
  },
  {
    datatype: "CWE",
    id: "AUT-14",
    item: "3414",
    maxLength: 250,
    name: "Approval Status",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "DTM",
    id: "AUT-15",
    item: "3415",
    maxLength: 24,
    name: "Planned Treatment Stop Date",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CWE",
    id: "AUT-16",
    item: "3416",
    maxLength: 250,
    name: "Clinical Service",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ST",
    id: "AUT-17",
    item: "3417",
    maxLength: 60,
    name: "Reason Text",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CQ",
    id: "AUT-18",
    item: "3418",
    maxLength: 721,
    name: "Number of Authorized Treatments/Units",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CQ",
    id: "AUT-19",
    item: "3419",
    maxLength: 721,
    name: "Number of Used Treatments/Units",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CQ",
    id: "AUT-20",
    item: "3420",
    maxLength: 721,
    name: "Number of Schedule Treatments/Units",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CWE",
    id: "AUT-21",
    item: "3421",
    maxLength: 250,
    name: "Encounter Type",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "MO",
    id: "AUT-22",
    item: "3422",
    maxLength: 20,
    name: "Remaining Benefit Amount",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "XON",
    id: "AUT-23",
    item: "3423",
    maxLength: 250,
    name: "Authorized Provider",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "XCN",
    id: "AUT-24",
    item: "3424",
    maxLength: 250,
    name: "Authorized Health Professional",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ST",
    id: "AUT-25",
    item: "3425",
    maxLength: 60,
    name: "Source Text",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "DTM",
    id: "AUT-26",
    item: "3426",
    maxLength: 24,
    name: "Source Date",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "XTN",
    id: "AUT-27",
    item: "3427",
    maxLength: 250,
    name: "Source Phone",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "ST",
    id: "AUT-28",
    item: "3428",
    maxLength: 254,
    name: "Comment",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "ID",
    id: "AUT-29",
    item: "3429",
    maxLength: 1,
    name: "Action Code",
    repeatable: false,
    required: false,
    sequence: 29,
    table: "HL70206",
  },
] as const;
