// Generated segment profile for EVN (v2.8.1)

export const segmentId = "EVN";
export const fields = [
  {
    datatype: "ID",
    deprecated: true,
    id: "EVN-1",
    item: "99",
    name: "Event Type Code",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70003",
  },
  {
    datatype: "DTM",
    id: "EVN-2",
    item: "100",
    name: "Recorded Date/Time",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "DTM",
    id: "EVN-3",
    item: "101",
    name: "Date/Time Planned Event",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "EVN-4",
    item: "102",
    name: "Event Reason Code",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70062",
  },
  {
    datatype: "XCN",
    id: "EVN-5",
    item: "103",
    name: "Operator ID",
    repeatable: true,
    required: false,
    sequence: 5,
    table: "HL70188",
  },
  {
    datatype: "DTM",
    id: "EVN-6",
    item: "1278",
    name: "Event Occurred",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "HD",
    id: "EVN-7",
    item: "1534",
    name: "Event Facility",
    repeatable: false,
    required: false,
    sequence: 7,
  },
] as const;
