// Generated segment profile for FHS (v2.8.1)

export const segmentId = "FHS";
export const fields = [
  {
    datatype: "ST",
    id: "FHS-1",
    item: "67",
    maxLength: 1,
    name: "File Field Separator",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "FHS-2",
    item: "68",
    maxLength: 5,
    name: "File Encoding Characters",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "HD",
    id: "FHS-3",
    item: "69",
    name: "File Sending Application",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "HD",
    id: "FHS-4",
    item: "70",
    name: "File Sending Facility",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "HD",
    id: "FHS-5",
    item: "71",
    name: "File Receiving Application",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "HD",
    id: "FHS-6",
    item: "72",
    name: "File Receiving Facility",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "FHS-7",
    item: "73",
    name: "File Creation Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "FHS-8",
    item: "74",
    name: "File Security",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "FHS-9",
    item: "75",
    name: "File Name/ID",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "FHS-10",
    item: "76",
    name: "File Header Comment",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "FHS-11",
    item: "77",
    name: "File Control ID",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "FHS-12",
    item: "78",
    name: "Reference File Control ID",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "HD",
    id: "FHS-13",
    item: "2269",
    name: "File Sending Network Address",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "HD",
    id: "FHS-14",
    item: "2270",
    name: "File Receiving Network Address",
    repeatable: false,
    required: false,
    sequence: 14,
  },
] as const;
