// Generated segment profile for IN3 (v2.8.1)

export const segmentId = "IN3";
export const fields = [
  {
    datatype: "SI",
    id: "IN3-1",
    item: "502",
    maxLength: 4,
    name: "Set ID - IN3",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CX",
    id: "IN3-2",
    item: "503",
    name: "Certification Number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XCN",
    id: "IN3-3",
    item: "504",
    name: "Certified By",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "IN3-4",
    item: "505",
    maxLength: 1,
    name: "Certification Required",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70136",
  },
  {
    datatype: "MOP",
    id: "IN3-5",
    item: "506",
    name: "Penalty",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DTM",
    id: "IN3-6",
    item: "507",
    name: "Certification Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "IN3-7",
    item: "508",
    name: "Certification Modify Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "XCN",
    id: "IN3-8",
    item: "509",
    name: "Operator",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DT",
    id: "IN3-9",
    item: "510",
    name: "Certification Begin Date",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "DT",
    id: "IN3-10",
    item: "511",
    name: "Certification End Date",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DTN",
    id: "IN3-11",
    item: "512",
    name: "Days",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "IN3-12",
    item: "513",
    name: "Non-Concur Code/Description",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70233",
  },
  {
    datatype: "DTM",
    id: "IN3-13",
    item: "514",
    name: "Non-Concur Effective Date/Time",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XCN",
    id: "IN3-14",
    item: "515",
    name: "Physician Reviewer",
    repeatable: true,
    required: false,
    sequence: 14,
    table: "HL70010",
  },
  {
    datatype: "ST",
    id: "IN3-15",
    item: "516",
    name: "Certification Contact",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "XTN",
    id: "IN3-16",
    item: "517",
    name: "Certification Contact Phone Number",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CWE",
    id: "IN3-17",
    item: "518",
    name: "Appeal Reason",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70345",
  },
  {
    datatype: "CWE",
    id: "IN3-18",
    item: "519",
    name: "Certification Agency",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70346",
  },
  {
    datatype: "XTN",
    id: "IN3-19",
    item: "520",
    name: "Certification Agency Phone Number",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ICD",
    id: "IN3-20",
    item: "521",
    name: "Pre-Certification Requirement",
    repeatable: true,
    required: false,
    sequence: 20,
  },
  {
    datatype: "ST",
    id: "IN3-21",
    item: "522",
    name: "Case Manager",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "DT",
    id: "IN3-22",
    item: "523",
    name: "Second Opinion Date",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "CWE",
    id: "IN3-23",
    item: "524",
    name: "Second Opinion Status",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70151",
  },
  {
    datatype: "CWE",
    id: "IN3-24",
    item: "525",
    name: "Second Opinion Documentation Received",
    repeatable: true,
    required: false,
    sequence: 24,
    table: "HL70152",
  },
  {
    datatype: "XCN",
    id: "IN3-25",
    item: "526",
    name: "Second Opinion Physician",
    repeatable: true,
    required: false,
    sequence: 25,
    table: "HL70010",
  },
  {
    datatype: "CWE",
    id: "IN3-26",
    item: "3336",
    name: "Certification Type",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70921",
  },
  {
    datatype: "CWE",
    id: "IN3-27",
    item: "3337",
    name: "Certification Category",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70922",
  },
] as const;
