// Generated segment profile for IPR (v2.8.1)

export const segmentId = "IPR";
export const fields = [
  {
    datatype: "EI",
    id: "IPR-1",
    item: "2030",
    name: "IPR Identifier",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "IPR-2",
    item: "2031",
    name: "Provider Cross Reference Identifier",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "IPR-3",
    item: "2032",
    name: "Payer Cross Reference Identifier",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "IPR-4",
    item: "2033",
    name: "IPR Status",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70571",
  },
  {
    datatype: "DTM",
    id: "IPR-5",
    item: "2034",
    name: "IPR Date/Time",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "CP",
    id: "IPR-6",
    item: "2035",
    name: "Adjudicated/Paid Amount",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "IPR-7",
    item: "2036",
    name: "Expected Payment Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "IPR-8",
    item: "2037",
    name: "IPR Checksum",
    repeatable: false,
    required: true,
    sequence: 8,
  },
] as const;
