// Generated segment profile for OM7 (v2.8.1)

export const segmentId = "OM7";
export const fields = [
  {
    datatype: "NM",
    id: "OM7-1",
    item: "586",
    name: "Sequence Number - Test/Observation Master File",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "OM7-2",
    item: "238",
    name: "Universal Service Identifier",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "OM7-3",
    item: "1481",
    name: "Category Identifier",
    repeatable: true,
    required: false,
    sequence: 3,
    table: "HL70412",
  },
  {
    datatype: "TX",
    id: "OM7-4",
    item: "1482",
    name: "Category Description",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "OM7-5",
    item: "1483",
    name: "Category Synonym",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DTM",
    id: "OM7-6",
    item: "1484",
    name: "Effective Test/Service Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "OM7-7",
    item: "1485",
    name: "Effective Test/Service End Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "OM7-8",
    item: "1486",
    name: "Test/Service Default Duration Quantity",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "OM7-9",
    item: "1487",
    name: "Test/Service Default Duration Units",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CWE",
    id: "OM7-10",
    item: "1488",
    name: "Test/Service Default Frequency",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "OM7-11",
    item: "1489",
    maxLength: 1,
    name: "Consent Indicator",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "OM7-12",
    item: "1490",
    name: "Consent Identifier",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70413",
  },
  {
    datatype: "DTM",
    id: "OM7-13",
    item: "1491",
    name: "Consent Effective Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DTM",
    id: "OM7-14",
    item: "1492",
    name: "Consent Effective End Date/Time",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "OM7-15",
    item: "1493",
    name: "Consent Interval Quantity",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CWE",
    id: "OM7-16",
    item: "1494",
    name: "Consent Interval Units",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70414",
  },
  {
    datatype: "NM",
    id: "OM7-17",
    item: "1495",
    name: "Consent Waiting Period Quantity",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CWE",
    id: "OM7-18",
    item: "1496",
    name: "Consent Waiting Period Units",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70414",
  },
  {
    datatype: "DTM",
    id: "OM7-19",
    item: "607",
    name: "Effective Date/Time of Change",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "XCN",
    id: "OM7-20",
    item: "224",
    name: "Entered By",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "PL",
    id: "OM7-21",
    item: "1497",
    name: "Orderable-at Location",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "CWE",
    id: "OM7-22",
    item: "1498",
    name: "Formulary Status",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70473",
  },
  {
    datatype: "ID",
    id: "OM7-23",
    item: "1499",
    maxLength: 1,
    name: "Special Order Indicator",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "OM7-24",
    item: "1306",
    name: "Primary Key Value - CDM",
    repeatable: true,
    required: false,
    sequence: 24,
  },
] as const;
