// Generated segment profile for PD1 (v2.8.1)

export const segmentId = "PD1";
export const fields = [
  {
    datatype: "CWE",
    id: "PD1-1",
    item: "755",
    name: "Living Dependency",
    repeatable: true,
    required: false,
    sequence: 1,
    table: "HL70223",
  },
  {
    datatype: "CWE",
    id: "PD1-2",
    item: "742",
    name: "Living Arrangement",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70220",
  },
  {
    datatype: "XON",
    id: "PD1-3",
    item: "756",
    name: "Patient Primary Facility",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "XCN",
    deprecated: true,
    id: "PD1-4",
    item: "757",
    name: "Patient Primary Care Provider Name &amp; ID No.",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "PD1-5",
    item: "745",
    name: "Student Indicator",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70231",
  },
  {
    datatype: "CWE",
    id: "PD1-6",
    item: "753",
    name: "Handicap",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70295",
  },
  {
    datatype: "CWE",
    id: "PD1-7",
    item: "759",
    name: "Living Will Code",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70315",
  },
  {
    datatype: "CWE",
    id: "PD1-8",
    item: "760",
    name: "Organ Donor Code",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70316",
  },
  {
    datatype: "ID",
    id: "PD1-9",
    item: "761",
    maxLength: 1,
    name: "Separate Bill",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70136",
  },
  {
    datatype: "CX",
    id: "PD1-10",
    item: "762",
    name: "Duplicate Patient",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "PD1-11",
    item: "743",
    name: "Publicity Code",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70215",
  },
  {
    datatype: "ID",
    id: "PD1-12",
    item: "744",
    maxLength: 1,
    name: "Protection Indicator",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70136",
  },
  {
    datatype: "DT",
    id: "PD1-13",
    item: "1566",
    name: "Protection Indicator Effective Date",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XON",
    id: "PD1-14",
    item: "1567",
    name: "Place of Worship",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "PD1-15",
    item: "1548",
    name: "Advance Directive Code",
    repeatable: true,
    required: false,
    sequence: 15,
    table: "HL70435",
  },
  {
    datatype: "CWE",
    id: "PD1-16",
    item: "1569",
    name: "Immunization Registry Status",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70441",
  },
  {
    datatype: "DT",
    id: "PD1-17",
    item: "1570",
    name: "Immunization Registry Status Effective Date",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "DT",
    id: "PD1-18",
    item: "1571",
    name: "Publicity Code Effective Date",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CWE",
    id: "PD1-19",
    item: "1572",
    name: "Military Branch",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70140",
  },
  {
    datatype: "CWE",
    id: "PD1-20",
    item: "486",
    name: "Military Rank/Grade",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70141",
  },
  {
    datatype: "CWE",
    id: "PD1-21",
    item: "1573",
    name: "Military Status",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70142",
  },
  {
    datatype: "DT",
    id: "PD1-22",
    item: "2141",
    name: "Advance Directive Last Verified Date",
    repeatable: false,
    required: false,
    sequence: 22,
  },
] as const;
