// Generated segment profile for RXV (v2.8.1)

export const segmentId = "RXV";
export const fields = [
  {
    datatype: "SI",
    id: "RXV-1",
    item: "3318",
    name: "Set ID - RXV",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "RXV-2",
    item: "3319",
    maxLength: 1,
    name: "Bolus Type",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70917",
  },
  {
    datatype: "NM",
    id: "RXV-3",
    item: "3320",
    name: "Bolus Dose Amount",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "RXV-4",
    item: "3321",
    name: "Bolus Dose Amount Units",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "RXV-5",
    item: "3322",
    name: "Bolus Dose Volume",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "RXV-6",
    item: "3323",
    name: "Bolus Dose Volume Units",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "RXV-7",
    item: "3324",
    maxLength: 2,
    name: "PCA Type",
    repeatable: false,
    required: true,
    sequence: 7,
    table: "HL70918",
  },
  {
    datatype: "NM",
    id: "RXV-8",
    item: "3325",
    name: "PCA Dose Amount",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "RXV-9",
    item: "3326",
    name: "PCA Dose Amount Units",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "RXV-10",
    item: "3327",
    name: "PCA Dose Amount Volume",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "RXV-11",
    item: "3328",
    name: "PCA Dose Amount Volume Units",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "NM",
    id: "RXV-12",
    item: "3329",
    name: "Max Dose Amount",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "RXV-13",
    item: "3330",
    name: "Max Dose Amount Units",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NM",
    id: "RXV-14",
    item: "3331",
    name: "Max Dose Amount Volume",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "RXV-15",
    item: "3332",
    name: "Max Dose Amount Volume Units",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CQ",
    id: "RXV-16",
    item: "3333",
    name: "Max Dose per Time",
    repeatable: false,
    required: true,
    sequence: 16,
  },
  {
    datatype: "CQ",
    id: "RXV-17",
    item: "3334",
    name: "Lockout Interval",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CWE",
    id: "RXV-18",
    item: "3339",
    name: "Syringe Manufacturer",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CWE",
    id: "RXV-19",
    item: "3385",
    name: "Syringe Model Number",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "NM",
    id: "RXV-20",
    item: "3386",
    name: "Syringe Size",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CWE",
    id: "RXV-21",
    item: "3431",
    name: "Syringe Size Units",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "ID",
    id: "RXV-22",
    item: "816",
    name: "Action Code",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70206",
  },
] as const;
