// Generated segment profile for GT1 (v2.2)

export const segmentId = "GT1";
export const fields = [
  {
    datatype: "SI",
    id: "GT1-1",
    item: "405",
    maxLength: 4,
    name: "Set ID - guarantor",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CK",
    id: "GT1-2",
    item: "406",
    maxLength: 20,
    name: "Guarantor number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "PN",
    id: "GT1-3",
    item: "407",
    maxLength: 48,
    name: "Guarantor name",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "PN",
    id: "GT1-4",
    item: "408",
    maxLength: 48,
    name: "Guarantor spouse name",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "AD",
    id: "GT1-5",
    item: "409",
    maxLength: 106,
    name: "Guarantor address",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TN",
    id: "GT1-6",
    item: "410",
    maxLength: 40,
    name: "Guarantor phone number - home",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TN",
    id: "GT1-7",
    item: "411",
    maxLength: 40,
    name: "Guarantor phone number - business",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DT",
    id: "GT1-8",
    item: "412",
    maxLength: 8,
    name: "Guarantor date of birth",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ID",
    id: "GT1-9",
    item: "413",
    maxLength: 1,
    name: "Guarantor sex",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70001",
  },
  {
    datatype: "ID",
    id: "GT1-10",
    item: "414",
    maxLength: 2,
    name: "Guarantor type",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70068",
  },
  {
    datatype: "ID",
    id: "GT1-11",
    item: "415",
    maxLength: 2,
    name: "Guarantor relationship",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70063",
  },
  {
    datatype: "ST",
    id: "GT1-12",
    item: "416",
    maxLength: 11,
    name: "Guarantor social security number",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DT",
    id: "GT1-13",
    item: "417",
    maxLength: 8,
    name: "Guarantor date - begin",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DT",
    id: "GT1-14",
    item: "418",
    maxLength: 8,
    name: "Guarantor date - end",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "GT1-15",
    item: "419",
    maxLength: 2,
    name: "Guarantor priority",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ST",
    id: "GT1-16",
    item: "420",
    maxLength: 45,
    name: "Guarantor employer name",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "AD",
    id: "GT1-17",
    item: "421",
    maxLength: 106,
    name: "Guarantor employer address",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "TN",
    id: "GT1-18",
    item: "422",
    maxLength: 40,
    name: "Guarantor employ phone number",
    repeatable: true,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    id: "GT1-19",
    item: "423",
    maxLength: 20,
    name: "Guarantor employee ID number",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "GT1-20",
    item: "424",
    maxLength: 2,
    name: "Guarantor employment status",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70066",
  },
  {
    datatype: "ST",
    id: "GT1-21",
    item: "425",
    maxLength: 60,
    name: "Guarantor organization",
    repeatable: false,
    required: false,
    sequence: 21,
  },
] as const;
