// Generated segment profile for IN1 (v2.2)

export const segmentId = "IN1";
export const fields = [
  {
    sequence: 1,
    id: "IN1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - insurance",
    item: "426",
  },
  {
    sequence: 2,
    id: "IN1-2",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70072",
    name: "Insurance plan ID",
    item: "368",
  },
  {
    sequence: 3,
    id: "IN1-3",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 9,
    name: "Insurance company ID",
    item: "428",
  },
  {
    sequence: 4,
    id: "IN1-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 45,
    name: "Insurance company name",
    item: "429",
  },
  {
    sequence: 5,
    id: "IN1-5",
    required: false,
    repeatable: false,
    datatype: "AD",
    maxLength: 106,
    name: "Insurance company address",
    item: "430",
  },
  {
    sequence: 6,
    id: "IN1-6",
    required: false,
    repeatable: false,
    datatype: "PN",
    maxLength: 48,
    name: "Insurance company contact pers",
    item: "431",
  },
  {
    sequence: 7,
    id: "IN1-7",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 40,
    name: "Insurance company phone number",
    item: "432",
  },
  {
    sequence: 8,
    id: "IN1-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    name: "Group number",
    item: "433",
  },
  {
    sequence: 9,
    id: "IN1-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 35,
    name: "Group name",
    item: "434",
  },
  {
    sequence: 10,
    id: "IN1-10",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    name: "Insured&apos;s group employer ID",
    item: "435",
  },
  {
    sequence: 11,
    id: "IN1-11",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 45,
    name: "Insured&apos;s group employer name",
    item: "436",
  },
  {
    sequence: 12,
    id: "IN1-12",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Plan effective date",
    item: "437",
  },
  {
    sequence: 13,
    id: "IN1-13",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Plan expiration date",
    item: "438",
  },
  {
    sequence: 14,
    id: "IN1-14",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 55,
    name: "Authorization information",
    item: "439",
  },
  {
    sequence: 15,
    id: "IN1-15",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 5,
    table: "HL70086",
    name: "Plan type",
    item: "440",
  },
  {
    sequence: 16,
    id: "IN1-16",
    required: false,
    repeatable: false,
    datatype: "PN",
    maxLength: 48,
    name: "Name of insured",
    item: "441",
  },
  {
    sequence: 17,
    id: "IN1-17",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70063",
    name: "Insured&apos;s relationship to patient",
    item: "442",
  },
  {
    sequence: 18,
    id: "IN1-18",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Insured&apos;s date of birth",
    item: "443",
  },
  {
    sequence: 19,
    id: "IN1-19",
    required: false,
    repeatable: false,
    datatype: "AD",
    maxLength: 106,
    name: "Insured&apos;s address",
    item: "444",
  },
  {
    sequence: 20,
    id: "IN1-20",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70135",
    name: "Assignment of benefits",
    item: "445",
  },
  {
    sequence: 21,
    id: "IN1-21",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70173",
    name: "Coordination of benefits",
    item: "446",
  },
  {
    sequence: 22,
    id: "IN1-22",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 2,
    name: "Coordination of benefits - priority",
    item: "447",
  },
  {
    sequence: 23,
    id: "IN1-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70136",
    name: "Notice of admission code",
    item: "448",
  },
  {
    sequence: 24,
    id: "IN1-24",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Notice of admission date",
    item: "449",
  },
  {
    sequence: 25,
    id: "IN1-25",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 4,
    name: "Report of eligibility code",
    item: "450",
  },
  {
    sequence: 26,
    id: "IN1-26",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Report of eligibility date",
    item: "451",
  },
  {
    sequence: 27,
    id: "IN1-27",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70093",
    name: "Release information code",
    item: "452",
  },
  {
    sequence: 28,
    id: "IN1-28",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "Pre-admit certification (PAC)",
    item: "453",
  },
  {
    sequence: 29,
    id: "IN1-29",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Verification date / time",
    item: "454",
  },
  {
    sequence: 30,
    id: "IN1-30",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Verification by",
    item: "455",
  },
  {
    sequence: 31,
    id: "IN1-31",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70098",
    name: "Type of agreement code",
    item: "456",
  },
  {
    sequence: 32,
    id: "IN1-32",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70022",
    name: "Billing status",
    item: "457",
  },
  {
    sequence: 33,
    id: "IN1-33",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Lifetime reserve days",
    item: "458",
  },
  {
    sequence: 34,
    id: "IN1-34",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Delay before lifetime reserve days",
    item: "459",
  },
  {
    sequence: 35,
    id: "IN1-35",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70042",
    name: "Company plan code",
    item: "460",
  },
  {
    sequence: 36,
    id: "IN1-36",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "Policy number",
    item: "461",
  },
  {
    sequence: 37,
    id: "IN1-37",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Policy deductible",
    item: "462",
  },
  {
    sequence: 38,
    id: "IN1-38",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Policy limit - amount",
    item: "463",
  },
  {
    sequence: 39,
    id: "IN1-39",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Policy limit - days",
    item: "464",
  },
  {
    sequence: 40,
    id: "IN1-40",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Room rate - semi-private",
    item: "465",
  },
  {
    sequence: 41,
    id: "IN1-41",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Room rate - private",
    item: "466",
  },
  {
    sequence: 42,
    id: "IN1-42",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70066",
    name: "Insured&apos;s employment status",
    item: "467",
  },
  {
    sequence: 43,
    id: "IN1-43",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70001",
    name: "Insured&apos;s sex",
    item: "468",
  },
  {
    sequence: 44,
    id: "IN1-44",
    required: false,
    repeatable: false,
    datatype: "AD",
    maxLength: 106,
    name: "Insured&apos;s employer address",
    item: "469",
  },
  {
    sequence: 45,
    id: "IN1-45",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 2,
    name: "Verification status",
    item: "470",
  },
  {
    sequence: 46,
    id: "IN1-46",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70072",
    name: "Prior insurance plan ID",
    item: "471",
  },
] as const;
