// Generated segment profile for IN1 (v2.2)

export const segmentId = "IN1";
export const fields = [
  {
    datatype: "SI",
    id: "IN1-1",
    item: "426",
    maxLength: 4,
    name: "Set ID - insurance",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "IN1-2",
    item: "368",
    maxLength: 8,
    name: "Insurance plan ID",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70072",
  },
  {
    datatype: "ST",
    id: "IN1-3",
    item: "428",
    maxLength: 9,
    name: "Insurance company ID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "IN1-4",
    item: "429",
    maxLength: 45,
    name: "Insurance company name",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "AD",
    id: "IN1-5",
    item: "430",
    maxLength: 106,
    name: "Insurance company address",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "PN",
    id: "IN1-6",
    item: "431",
    maxLength: 48,
    name: "Insurance company contact pers",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TN",
    id: "IN1-7",
    item: "432",
    maxLength: 40,
    name: "Insurance company phone number",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "IN1-8",
    item: "433",
    maxLength: 12,
    name: "Group number",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "IN1-9",
    item: "434",
    maxLength: 35,
    name: "Group name",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "IN1-10",
    item: "435",
    maxLength: 12,
    name: "Insured&apos;s group employer ID",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "IN1-11",
    item: "436",
    maxLength: 45,
    name: "Insured&apos;s group employer name",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "DT",
    id: "IN1-12",
    item: "437",
    maxLength: 8,
    name: "Plan effective date",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DT",
    id: "IN1-13",
    item: "438",
    maxLength: 8,
    name: "Plan expiration date",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CM",
    id: "IN1-14",
    item: "439",
    maxLength: 55,
    name: "Authorization information",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ID",
    id: "IN1-15",
    item: "440",
    maxLength: 5,
    name: "Plan type",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70086",
  },
  {
    datatype: "PN",
    id: "IN1-16",
    item: "441",
    maxLength: 48,
    name: "Name of insured",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "IN1-17",
    item: "442",
    maxLength: 2,
    name: "Insured&apos;s relationship to patient",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70063",
  },
  {
    datatype: "DT",
    id: "IN1-18",
    item: "443",
    maxLength: 8,
    name: "Insured&apos;s date of birth",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "AD",
    id: "IN1-19",
    item: "444",
    maxLength: 106,
    name: "Insured&apos;s address",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "IN1-20",
    item: "445",
    maxLength: 2,
    name: "Assignment of benefits",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70135",
  },
  {
    datatype: "ID",
    id: "IN1-21",
    item: "446",
    maxLength: 2,
    name: "Coordination of benefits",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70173",
  },
  {
    datatype: "ST",
    id: "IN1-22",
    item: "447",
    maxLength: 2,
    name: "Coordination of benefits - priority",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ID",
    id: "IN1-23",
    item: "448",
    maxLength: 2,
    name: "Notice of admission code",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70136",
  },
  {
    datatype: "DT",
    id: "IN1-24",
    item: "449",
    maxLength: 8,
    name: "Notice of admission date",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ID",
    id: "IN1-25",
    item: "450",
    maxLength: 4,
    name: "Report of eligibility code",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "DT",
    id: "IN1-26",
    item: "451",
    maxLength: 8,
    name: "Report of eligibility date",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "ID",
    id: "IN1-27",
    item: "452",
    maxLength: 2,
    name: "Release information code",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70093",
  },
  {
    datatype: "ST",
    id: "IN1-28",
    item: "453",
    maxLength: 15,
    name: "Pre-admit certification (PAC)",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "TS",
    id: "IN1-29",
    item: "454",
    maxLength: 26,
    name: "Verification date / time",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CN",
    id: "IN1-30",
    item: "455",
    maxLength: 60,
    name: "Verification by",
    repeatable: false,
    required: false,
    sequence: 30,
  },
  {
    datatype: "ID",
    id: "IN1-31",
    item: "456",
    maxLength: 2,
    name: "Type of agreement code",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70098",
  },
  {
    datatype: "ID",
    id: "IN1-32",
    item: "457",
    maxLength: 2,
    name: "Billing status",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70022",
  },
  {
    datatype: "NM",
    id: "IN1-33",
    item: "458",
    maxLength: 4,
    name: "Lifetime reserve days",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "NM",
    id: "IN1-34",
    item: "459",
    maxLength: 4,
    name: "Delay before lifetime reserve days",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "ID",
    id: "IN1-35",
    item: "460",
    maxLength: 8,
    name: "Company plan code",
    repeatable: false,
    required: false,
    sequence: 35,
    table: "HL70042",
  },
  {
    datatype: "ST",
    id: "IN1-36",
    item: "461",
    maxLength: 15,
    name: "Policy number",
    repeatable: false,
    required: false,
    sequence: 36,
  },
  {
    datatype: "NM",
    id: "IN1-37",
    item: "462",
    maxLength: 12,
    name: "Policy deductible",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "NM",
    id: "IN1-38",
    item: "463",
    maxLength: 12,
    name: "Policy limit - amount",
    repeatable: false,
    required: false,
    sequence: 38,
  },
  {
    datatype: "NM",
    id: "IN1-39",
    item: "464",
    maxLength: 4,
    name: "Policy limit - days",
    repeatable: false,
    required: false,
    sequence: 39,
  },
  {
    datatype: "NM",
    id: "IN1-40",
    item: "465",
    maxLength: 12,
    name: "Room rate - semi-private",
    repeatable: false,
    required: false,
    sequence: 40,
  },
  {
    datatype: "NM",
    id: "IN1-41",
    item: "466",
    maxLength: 12,
    name: "Room rate - private",
    repeatable: false,
    required: false,
    sequence: 41,
  },
  {
    datatype: "CE",
    id: "IN1-42",
    item: "467",
    maxLength: 60,
    name: "Insured&apos;s employment status",
    repeatable: false,
    required: false,
    sequence: 42,
    table: "HL70066",
  },
  {
    datatype: "ID",
    id: "IN1-43",
    item: "468",
    maxLength: 1,
    name: "Insured&apos;s sex",
    repeatable: false,
    required: false,
    sequence: 43,
    table: "HL70001",
  },
  {
    datatype: "AD",
    id: "IN1-44",
    item: "469",
    maxLength: 106,
    name: "Insured&apos;s employer address",
    repeatable: false,
    required: false,
    sequence: 44,
  },
  {
    datatype: "ST",
    id: "IN1-45",
    item: "470",
    maxLength: 2,
    name: "Verification status",
    repeatable: false,
    required: false,
    sequence: 45,
  },
  {
    datatype: "ID",
    id: "IN1-46",
    item: "471",
    maxLength: 8,
    name: "Prior insurance plan ID",
    repeatable: false,
    required: false,
    sequence: 46,
    table: "HL70072",
  },
] as const;
