// Generated segment profile for IN2 (v2.2)

export const segmentId = "IN2";
export const fields = [
  {
    datatype: "ST",
    id: "IN2-1",
    item: "472",
    maxLength: 15,
    name: "Insured&apos;s employee ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "IN2-2",
    item: "473",
    maxLength: 9,
    name: "Insured&apos;s social security number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CN",
    id: "IN2-3",
    item: "474",
    maxLength: 60,
    name: "Insured&apos;s employer name",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "IN2-4",
    item: "475",
    maxLength: 1,
    name: "Employer information data",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70139",
  },
  {
    datatype: "ID",
    id: "IN2-5",
    item: "476",
    maxLength: 1,
    name: "Mail claim party",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70137",
  },
  {
    datatype: "NM",
    id: "IN2-6",
    item: "477",
    maxLength: 15,
    name: "Medicare health insurance card number",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "PN",
    id: "IN2-7",
    item: "478",
    maxLength: 48,
    name: "Medicaid case name",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "IN2-8",
    item: "479",
    maxLength: 15,
    name: "Medicaid case number",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "PN",
    id: "IN2-9",
    item: "480",
    maxLength: 48,
    name: "Champus sponsor name",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "IN2-10",
    item: "481",
    maxLength: 20,
    name: "Champus ID number",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "IN2-11",
    item: "482",
    maxLength: 1,
    name: "Dependent of champus recipient",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "IN2-12",
    item: "483",
    maxLength: 25,
    name: "Champus organization",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "IN2-13",
    item: "484",
    maxLength: 25,
    name: "Champus station",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ID",
    id: "IN2-14",
    item: "485",
    maxLength: 14,
    name: "Champus service",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70140",
  },
  {
    datatype: "ID",
    id: "IN2-15",
    item: "486",
    maxLength: 2,
    name: "Champus rank / grade",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70141",
  },
  {
    datatype: "ID",
    id: "IN2-16",
    item: "487",
    maxLength: 3,
    name: "Champus status",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70142",
  },
  {
    datatype: "DT",
    id: "IN2-17",
    item: "488",
    maxLength: 8,
    name: "Champus retire date",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "ID",
    id: "IN2-18",
    item: "489",
    maxLength: 1,
    name: "Champus non-availability certification on file",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "IN2-19",
    item: "490",
    maxLength: 1,
    name: "Baby coverage",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "IN2-20",
    item: "491",
    maxLength: 1,
    name: "Combine baby bill",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70136",
  },
  {
    datatype: "NM",
    id: "IN2-21",
    item: "531",
    maxLength: 1,
    name: "Blood deductible",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "PN",
    id: "IN2-22",
    item: "493",
    maxLength: 48,
    name: "Special coverage approval name",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ST",
    id: "IN2-23",
    item: "494",
    maxLength: 30,
    name: "Special coverage approval title",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ID",
    id: "IN2-24",
    item: "495",
    maxLength: 8,
    name: "Non-covered insurance code",
    repeatable: true,
    required: false,
    sequence: 24,
    table: "HL70143",
  },
  {
    datatype: "ST",
    id: "IN2-25",
    item: "496",
    maxLength: 6,
    name: "Payor ID",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "ST",
    id: "IN2-26",
    item: "497",
    maxLength: 6,
    name: "Payor subscriber ID",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "ID",
    id: "IN2-27",
    item: "498",
    maxLength: 1,
    name: "Eligibility source",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70144",
  },
  {
    datatype: "CM",
    id: "IN2-28",
    item: "499",
    maxLength: 25,
    name: "Room coverage type / amount",
    repeatable: true,
    required: false,
    sequence: 28,
    table: "HL70145",
  },
  {
    datatype: "CM",
    id: "IN2-29",
    item: "500",
    maxLength: 25,
    name: "Policy type / amount",
    repeatable: true,
    required: false,
    sequence: 29,
    table: "HL70147",
  },
  {
    datatype: "CM",
    id: "IN2-30",
    item: "501",
    maxLength: 25,
    name: "Daily deductible",
    repeatable: false,
    required: false,
    sequence: 30,
  },
] as const;
