// Generated segment profile for IN3 (v2.2)

export const segmentId = "IN3";
export const fields = [
  {
    sequence: 1,
    id: "IN3-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - insurance certification",
    item: "502",
  },
  {
    sequence: 2,
    id: "IN3-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 25,
    name: "Certification number",
    item: "503",
  },
  {
    sequence: 3,
    id: "IN3-3",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Certified by",
    item: "504",
  },
  {
    sequence: 4,
    id: "IN3-4",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Certification required",
    item: "505",
  },
  {
    sequence: 5,
    id: "IN3-5",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 10,
    table: "HL70148",
    name: "Penalty",
    item: "506",
  },
  {
    sequence: 6,
    id: "IN3-6",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Certification date / time",
    item: "507",
  },
  {
    sequence: 7,
    id: "IN3-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Certification modify date / time",
    item: "508",
  },
  {
    sequence: 8,
    id: "IN3-8",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Operator",
    item: "509",
  },
  {
    sequence: 9,
    id: "IN3-9",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Certification begin date",
    item: "510",
  },
  {
    sequence: 10,
    id: "IN3-10",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Certification end date",
    item: "511",
  },
  {
    sequence: 11,
    id: "IN3-11",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 3,
    table: "HL70149",
    name: "Days",
    item: "512",
  },
  {
    sequence: 12,
    id: "IN3-12",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Non-concur code / description",
    item: "513",
  },
  {
    sequence: 13,
    id: "IN3-13",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Non-concur effective date / time",
    item: "514",
  },
  {
    sequence: 14,
    id: "IN3-14",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Physician reviewer",
    item: "515",
  },
  {
    sequence: 15,
    id: "IN3-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 48,
    name: "Certification contact",
    item: "516",
  },
  {
    sequence: 16,
    id: "IN3-16",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 40,
    name: "Certification contact phone number",
    item: "517",
  },
  {
    sequence: 17,
    id: "IN3-17",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Appeal reason",
    item: "518",
  },
  {
    sequence: 18,
    id: "IN3-18",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Certification agency",
    item: "519",
  },
  {
    sequence: 19,
    id: "IN3-19",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 40,
    name: "Certification agency phone number",
    item: "520",
  },
  {
    sequence: 20,
    id: "IN3-20",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 40,
    table: "HL70150",
    name: "Pre-certification required / window",
    item: "521",
  },
  {
    sequence: 21,
    id: "IN3-21",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 48,
    name: "Case manager",
    item: "522",
  },
  {
    sequence: 22,
    id: "IN3-22",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Second opinion date",
    item: "523",
  },
  {
    sequence: 23,
    id: "IN3-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70151",
    name: "Second opinion status",
    item: "524",
  },
  {
    sequence: 24,
    id: "IN3-24",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70152",
    name: "Second opinion documentation received",
    item: "525",
  },
  {
    sequence: 25,
    id: "IN3-25",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Second opinion practitioner",
    item: "526",
  },
] as const;
