// Generated segment profile for MSH (v2.2)

export const segmentId = "MSH";
export const fields = [
  {
    sequence: 1,
    id: "MSH-1",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 1,
    name: "Field separator",
    item: "1",
  },
  {
    sequence: 2,
    id: "MSH-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    name: "Encoding characters",
    item: "2",
  },
  {
    sequence: 3,
    id: "MSH-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "Sending application",
    item: "3",
  },
  {
    sequence: 4,
    id: "MSH-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Sending facility",
    item: "4",
  },
  {
    sequence: 5,
    id: "MSH-5",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "Receiving application",
    item: "5",
  },
  {
    sequence: 6,
    id: "MSH-6",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "Receiving facility",
    item: "6",
  },
  {
    sequence: 7,
    id: "MSH-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Date / Time of message",
    item: "7",
  },
  {
    sequence: 8,
    id: "MSH-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Security",
    item: "8",
  },
  {
    sequence: 9,
    id: "MSH-9",
    required: true,
    repeatable: false,
    datatype: "CM",
    maxLength: 7,
    table: "HL70076",
    name: "Message type",
    item: "9",
  },
  {
    sequence: 10,
    id: "MSH-10",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Message Control ID",
    item: "10",
  },
  {
    sequence: 11,
    id: "MSH-11",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70103",
    name: "Processing ID",
    item: "11",
  },
  {
    sequence: 12,
    id: "MSH-12",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70104",
    name: "Version ID",
    item: "12",
  },
  {
    sequence: 13,
    id: "MSH-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 15,
    name: "Sequence number",
    item: "13",
  },
  {
    sequence: 14,
    id: "MSH-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 180,
    name: "Continuation pointer",
    item: "14",
  },
  {
    sequence: 15,
    id: "MSH-15",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70155",
    name: "Accept acknowledgement type",
    item: "15",
  },
  {
    sequence: 16,
    id: "MSH-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70155",
    name: "Application acknowledgement type",
    item: "16",
  },
  {
    sequence: 17,
    id: "MSH-17",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    name: "Country code",
    item: "17",
  },
] as const;
