// Generated segment profile for MSH (v2.2)

export const segmentId = "MSH";
export const fields = [
  {
    datatype: "ST",
    id: "MSH-1",
    item: "1",
    maxLength: 1,
    name: "Field separator",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "MSH-2",
    item: "2",
    maxLength: 4,
    name: "Encoding characters",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "MSH-3",
    item: "3",
    maxLength: 15,
    name: "Sending application",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "MSH-4",
    item: "4",
    maxLength: 20,
    name: "Sending facility",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "MSH-5",
    item: "5",
    maxLength: 30,
    name: "Receiving application",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "MSH-6",
    item: "6",
    maxLength: 30,
    name: "Receiving facility",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "MSH-7",
    item: "7",
    maxLength: 26,
    name: "Date / Time of message",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "MSH-8",
    item: "8",
    maxLength: 40,
    name: "Security",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CM",
    id: "MSH-9",
    item: "9",
    maxLength: 7,
    name: "Message type",
    repeatable: false,
    required: true,
    sequence: 9,
    table: "HL70076",
  },
  {
    datatype: "ST",
    id: "MSH-10",
    item: "10",
    maxLength: 20,
    name: "Message Control ID",
    repeatable: false,
    required: true,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "MSH-11",
    item: "11",
    maxLength: 1,
    name: "Processing ID",
    repeatable: false,
    required: true,
    sequence: 11,
    table: "HL70103",
  },
  {
    datatype: "ID",
    id: "MSH-12",
    item: "12",
    maxLength: 8,
    name: "Version ID",
    repeatable: false,
    required: true,
    sequence: 12,
    table: "HL70104",
  },
  {
    datatype: "NM",
    id: "MSH-13",
    item: "13",
    maxLength: 15,
    name: "Sequence number",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "MSH-14",
    item: "14",
    maxLength: 180,
    name: "Continuation pointer",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ID",
    id: "MSH-15",
    item: "15",
    maxLength: 2,
    name: "Accept acknowledgement type",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70155",
  },
  {
    datatype: "ID",
    id: "MSH-16",
    item: "16",
    maxLength: 2,
    name: "Application acknowledgement type",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70155",
  },
  {
    datatype: "ID",
    id: "MSH-17",
    item: "17",
    maxLength: 2,
    name: "Country code",
    repeatable: false,
    required: false,
    sequence: 17,
  },
] as const;
