// Generated segment profile for NST (v2.2)

export const segmentId = "NST";
export const fields = [
  {
    datatype: "ID",
    id: "NST-1",
    item: "743",
    maxLength: 1,
    name: "Statistics Available",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70136",
  },
  {
    datatype: "ST",
    id: "NST-2",
    item: "744",
    maxLength: 30,
    name: "Source Identifier",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ID",
    id: "NST-3",
    item: "745",
    maxLength: 3,
    name: "Source Type",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "NST-4",
    item: "746",
    maxLength: 26,
    name: "Statistics Start",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "NST-5",
    item: "747",
    maxLength: 26,
    name: "Statistics End",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "NST-6",
    item: "748",
    maxLength: 10,
    name: "Receive Character Count",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "NST-7",
    item: "749",
    maxLength: 10,
    name: "Send Character Count",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "NST-8",
    item: "750",
    maxLength: 10,
    name: "Message Received",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "NM",
    id: "NST-9",
    item: "751",
    maxLength: 10,
    name: "Message Sent",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "NST-10",
    item: "752",
    maxLength: 10,
    name: "Checksum Errors Received",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "NST-11",
    item: "753",
    maxLength: 10,
    name: "Length Errors Received",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "NM",
    id: "NST-12",
    item: "754",
    maxLength: 10,
    name: "Other Errors Received",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "NST-13",
    item: "755",
    maxLength: 10,
    name: "Connect Timeouts",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NM",
    id: "NST-14",
    item: "756",
    maxLength: 10,
    name: "Receive Timeouts",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "NST-15",
    item: "757",
    maxLength: 10,
    name: "Network Errors",
    repeatable: false,
    required: false,
    sequence: 15,
  },
] as const;
