// Generated segment profile for NST (v2.2)

export const segmentId = "NST";
export const fields = [
  {
    sequence: 1,
    id: "NST-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Statistics Available",
    item: "743",
  },
  {
    sequence: 2,
    id: "NST-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "Source Identifier",
    item: "744",
  },
  {
    sequence: 3,
    id: "NST-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 3,
    name: "Source Type",
    item: "745",
  },
  {
    sequence: 4,
    id: "NST-4",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Statistics Start",
    item: "746",
  },
  {
    sequence: 5,
    id: "NST-5",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Statistics End",
    item: "747",
  },
  {
    sequence: 6,
    id: "NST-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Receive Character Count",
    item: "748",
  },
  {
    sequence: 7,
    id: "NST-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Send Character Count",
    item: "749",
  },
  {
    sequence: 8,
    id: "NST-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Message Received",
    item: "750",
  },
  {
    sequence: 9,
    id: "NST-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Message Sent",
    item: "751",
  },
  {
    sequence: 10,
    id: "NST-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Checksum Errors Received",
    item: "752",
  },
  {
    sequence: 11,
    id: "NST-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Length Errors Received",
    item: "753",
  },
  {
    sequence: 12,
    id: "NST-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Other Errors Received",
    item: "754",
  },
  {
    sequence: 13,
    id: "NST-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Connect Timeouts",
    item: "755",
  },
  {
    sequence: 14,
    id: "NST-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Receive Timeouts",
    item: "756",
  },
  {
    sequence: 15,
    id: "NST-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Network Errors",
    item: "757",
  },
] as const;
