// Generated segment profile for OBX (v2.2)

export const segmentId = "OBX";
export const fields = [
  {
    datatype: "SI",
    id: "OBX-1",
    item: "569",
    maxLength: 4,
    name: "Set ID - Observational Simple",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "OBX-2",
    item: "570",
    maxLength: 2,
    name: "Value Type",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70125",
  },
  {
    datatype: "CE",
    id: "OBX-3",
    item: "571",
    maxLength: 80,
    name: "Observation Identifier",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "OBX-4",
    item: "572",
    maxLength: 20,
    name: "Observation Sub-ID",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "*",
    id: "OBX-5",
    item: "573",
    maxLength: 65_536,
    name: "Observation Value",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "OBX-6",
    item: "574",
    maxLength: 60,
    name: "Units",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "OBX-7",
    item: "575",
    maxLength: 60,
    name: "References Range",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "OBX-8",
    item: "576",
    maxLength: 10,
    name: "Abnormal Flags",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70078",
  },
  {
    datatype: "NM",
    id: "OBX-9",
    item: "577",
    maxLength: 5,
    name: "Probability",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "OBX-10",
    item: "578",
    maxLength: 5,
    name: "Nature of Abnormal Test",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70080",
  },
  {
    datatype: "ID",
    id: "OBX-11",
    item: "579",
    maxLength: 2,
    name: "Observation result status",
    repeatable: false,
    required: true,
    sequence: 11,
    table: "HL70085",
  },
  {
    datatype: "TS",
    id: "OBX-12",
    item: "580",
    maxLength: 26,
    name: "Effective date last observation normal values",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "OBX-13",
    item: "581",
    maxLength: 20,
    name: "User Defined Access Checks",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "TS",
    id: "OBX-14",
    item: "582",
    maxLength: 26,
    name: "Date / time of the observation",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CE",
    id: "OBX-15",
    item: "583",
    maxLength: 60,
    name: "Producer&apos;s ID",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CN",
    id: "OBX-16",
    item: "584",
    maxLength: 60,
    name: "Responsible Observer",
    repeatable: false,
    required: false,
    sequence: 16,
  },
] as const;
