// Generated segment profile for OM1 (v2.2)

export const segmentId = "OM1";
export const fields = [
  {
    sequence: 1,
    id: "OM1-1",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 3,
    name: "Segment Type ID",
    item: "585",
  },
  {
    sequence: 2,
    id: "OM1-2",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Sequence Number - Test/ Observation Master File",
    item: "586",
  },
  {
    sequence: 3,
    id: "OM1-3",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Producer&apos;s test / observation ID",
    item: "587",
  },
  {
    sequence: 4,
    id: "OM1-4",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 12,
    table: "HL70125",
    name: "Permitted Data Types",
    item: "588",
  },
  {
    sequence: 5,
    id: "OM1-5",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Specimen Required",
    item: "589",
  },
  {
    sequence: 6,
    id: "OM1-6",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Producer ID",
    item: "590",
  },
  {
    sequence: 7,
    id: "OM1-7",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 200,
    name: "Observation Description",
    item: "591",
  },
  {
    sequence: 8,
    id: "OM1-8",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Other test / observation IDs for the observation",
    item: "592",
  },
  {
    sequence: 9,
    id: "OM1-9",
    required: true,
    repeatable: true,
    datatype: "ST",
    maxLength: 200,
    name: "Other Names",
    item: "593",
  },
  {
    sequence: 10,
    id: "OM1-10",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "Preferred Report Name for the Observation",
    item: "594",
  },
  {
    sequence: 11,
    id: "OM1-11",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 8,
    name: "Preferred Short Name or Mnemonic for Observation",
    item: "595",
  },
  {
    sequence: 12,
    id: "OM1-12",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 200,
    name: "Preferred Long Name for the Observation",
    item: "596",
  },
  {
    sequence: 13,
    id: "OM1-13",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Orderability",
    item: "597",
  },
  {
    sequence: 14,
    id: "OM1-14",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 60,
    name: "Identity of instrument used to perform this study",
    item: "598",
  },
  {
    sequence: 15,
    id: "OM1-15",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Coded Representation of Method",
    item: "599",
  },
  {
    sequence: 16,
    id: "OM1-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Portable",
    item: "600",
  },
  {
    sequence: 17,
    id: "OM1-17",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 1,
    name: "Observation producing department / section",
    item: "601",
  },
  {
    sequence: 18,
    id: "OM1-18",
    required: false,
    repeatable: false,
    datatype: "TN",
    maxLength: 40,
    name: "Telephone Number of Section",
    item: "602",
  },
  {
    sequence: 19,
    id: "OM1-19",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70174",
    name: "Nature of test / observation",
    item: "603",
  },
  {
    sequence: 20,
    id: "OM1-20",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Report Subheader",
    item: "604",
  },
  {
    sequence: 21,
    id: "OM1-21",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Report Display Order",
    item: "605",
  },
  {
    sequence: 22,
    id: "OM1-22",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Date / time stamp for any change in definition for obs",
    item: "606",
  },
  {
    sequence: 23,
    id: "OM1-23",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective date / time of change",
    item: "607",
  },
  {
    sequence: 24,
    id: "OM1-24",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Typical Turn-around Time",
    item: "608",
  },
  {
    sequence: 25,
    id: "OM1-25",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Processing Time",
    item: "609",
  },
  {
    sequence: 26,
    id: "OM1-26",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 40,
    table: "HL70168",
    name: "Processing Priority",
    item: "610",
  },
  {
    sequence: 27,
    id: "OM1-27",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 5,
    table: "HL70169",
    name: "Reporting Priority",
    item: "611",
  },
  {
    sequence: 28,
    id: "OM1-28",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Outside Site(s) Where Observation may be Performed",
    item: "612",
  },
  {
    sequence: 29,
    id: "OM1-29",
    required: false,
    repeatable: true,
    datatype: "AD",
    maxLength: 1000,
    name: "Address of Outside Site(s)",
    item: "613",
  },
  {
    sequence: 30,
    id: "OM1-30",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 400,
    name: "Phone Number of Outside Site",
    item: "614",
  },
  {
    sequence: 31,
    id: "OM1-31",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70177",
    name: "Confidentiality Code",
    item: "615",
  },
  {
    sequence: 32,
    id: "OM1-32",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Observations required to interpret the observation",
    item: "616",
  },
  {
    sequence: 33,
    id: "OM1-33",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 65_536,
    name: "Interpretation of Observations",
    item: "617",
  },
  {
    sequence: 34,
    id: "OM1-34",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 65_536,
    name: "Contraindications to Observations",
    item: "618",
  },
  {
    sequence: 35,
    id: "OM1-35",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Reflex tests / observations",
    item: "619",
  },
  {
    sequence: 36,
    id: "OM1-36",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 80,
    name: "Rules that Trigger Reflex Testing",
    item: "620",
  },
  {
    sequence: 37,
    id: "OM1-37",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 65_536,
    name: "Fixed Canned Message",
    item: "621",
  },
  {
    sequence: 38,
    id: "OM1-38",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 200,
    name: "Patient Preparation",
    item: "622",
  },
  {
    sequence: 39,
    id: "OM1-39",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Procedure Medication",
    item: "623",
  },
  {
    sequence: 40,
    id: "OM1-40",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 200,
    name: "Factors that may affect the observation",
    item: "624",
  },
  {
    sequence: 41,
    id: "OM1-41",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 60,
    name: "Test / observation performance schedule",
    item: "625",
  },
  {
    sequence: 42,
    id: "OM1-42",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 65_536,
    name: "Description of Test Methods",
    item: "626",
  },
] as const;
