// Generated segment profile for OM2 (v2.2)

export const segmentId = "OM2";
export const fields = [
  {
    sequence: 1,
    id: "OM2-1",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 3,
    name: "Segment Type ID",
    item: "585",
  },
  {
    sequence: 2,
    id: "OM2-2",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Sequence Number - Test/ Observation Master File",
    item: "586",
  },
  {
    sequence: 3,
    id: "OM2-3",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Units of Measure",
    item: "627",
  },
  {
    sequence: 4,
    id: "OM2-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Range of Decimal Precision",
    item: "628",
  },
  {
    sequence: 5,
    id: "OM2-5",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Corresponding SI Units of Measure",
    item: "629",
  },
  {
    sequence: 6,
    id: "OM2-6",
    required: true,
    repeatable: true,
    datatype: "TX",
    maxLength: 20,
    name: "SI Conversion Factor",
    item: "630",
  },
  {
    sequence: 7,
    id: "OM2-7",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 200,
    name: "Reference (normal) range - ordinal &amp; continuous observations",
    item: "631",
  },
  {
    sequence: 8,
    id: "OM2-8",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 200,
    name: "Critical range for ordinal and continuous observations",
    item: "632",
  },
  {
    sequence: 9,
    id: "OM2-9",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 200,
    name: "Absolute range for ordinal and continuous observations",
    item: "633",
  },
  {
    sequence: 10,
    id: "OM2-10",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 200,
    name: "Delta Check Criteria",
    item: "634",
  },
  {
    sequence: 11,
    id: "OM2-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Minimum Meaningful Increments",
    item: "635",
  },
] as const;
