// Generated segment profile for OM2 (v2.2)

export const segmentId = "OM2";
export const fields = [
  {
    datatype: "ST",
    id: "OM2-1",
    item: "585",
    maxLength: 3,
    name: "Segment Type ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "OM2-2",
    item: "586",
    maxLength: 4,
    name: "Sequence Number - Test/ Observation Master File",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CE",
    id: "OM2-3",
    item: "627",
    maxLength: 60,
    name: "Units of Measure",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "OM2-4",
    item: "628",
    maxLength: 10,
    name: "Range of Decimal Precision",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "OM2-5",
    item: "629",
    maxLength: 60,
    name: "Corresponding SI Units of Measure",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TX",
    id: "OM2-6",
    item: "630",
    maxLength: 20,
    name: "SI Conversion Factor",
    repeatable: true,
    required: true,
    sequence: 6,
  },
  {
    datatype: "CM",
    id: "OM2-7",
    item: "631",
    maxLength: 200,
    name: "Reference (normal) range - ordinal &amp; continuous observations",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CM",
    id: "OM2-8",
    item: "632",
    maxLength: 200,
    name: "Critical range for ordinal and continuous observations",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CM",
    id: "OM2-9",
    item: "633",
    maxLength: 200,
    name: "Absolute range for ordinal and continuous observations",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CM",
    id: "OM2-10",
    item: "634",
    maxLength: 200,
    name: "Delta Check Criteria",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "OM2-11",
    item: "635",
    maxLength: 20,
    name: "Minimum Meaningful Increments",
    repeatable: false,
    required: false,
    sequence: 11,
  },
] as const;
