// Generated segment profile for OM3 (v2.2)

export const segmentId = "OM3";
export const fields = [
  {
    datatype: "ST",
    id: "OM3-1",
    item: "585",
    maxLength: 3,
    name: "Segment Type ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "OM3-2",
    item: "586",
    maxLength: 4,
    name: "Sequence Number - Test/ Observation Master File",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ID",
    id: "OM3-3",
    item: "636",
    maxLength: 5,
    name: "Preferred Coding System",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "OM3-4",
    item: "637",
    maxLength: 60,
    name: "Valid coded answers",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "OM3-5",
    item: "638",
    maxLength: 200,
    name: "Normal test codes for categorical observations",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "OM3-6",
    item: "639",
    maxLength: 200,
    name: "Abnormal test codes for categorical observations",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "OM3-7",
    item: "640",
    maxLength: 200,
    name: "Critical test codes for categorical observations",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "OM3-8",
    item: "641",
    maxLength: 2,
    name: "Data Type",
    repeatable: false,
    required: false,
    sequence: 8,
  },
] as const;
