// Generated segment profile for OM3 (v2.2)

export const segmentId = "OM3";
export const fields = [
  {
    sequence: 1,
    id: "OM3-1",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 3,
    name: "Segment Type ID",
    item: "585",
  },
  {
    sequence: 2,
    id: "OM3-2",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Sequence Number - Test/ Observation Master File",
    item: "586",
  },
  {
    sequence: 3,
    id: "OM3-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 5,
    name: "Preferred Coding System",
    item: "636",
  },
  {
    sequence: 4,
    id: "OM3-4",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 60,
    name: "Valid coded answers",
    item: "637",
  },
  {
    sequence: 5,
    id: "OM3-5",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Normal test codes for categorical observations",
    item: "638",
  },
  {
    sequence: 6,
    id: "OM3-6",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Abnormal test codes for categorical observations",
    item: "639",
  },
  {
    sequence: 7,
    id: "OM3-7",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    name: "Critical test codes for categorical observations",
    item: "640",
  },
  {
    sequence: 8,
    id: "OM3-8",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    name: "Data Type",
    item: "641",
  },
] as const;
