// Generated segment profile for PR1 (v2.2)

export const segmentId = "PR1";
export const fields = [
  {
    datatype: "SI",
    id: "PR1-1",
    item: "391",
    maxLength: 4,
    name: "Set ID - procedure",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "PR1-2",
    item: "392",
    maxLength: 2,
    name: "Procedure coding method",
    repeatable: true,
    required: true,
    sequence: 2,
    table: "HL70089",
  },
  {
    datatype: "ID",
    id: "PR1-3",
    item: "393",
    maxLength: 10,
    name: "Procedure code",
    repeatable: true,
    required: true,
    sequence: 3,
    table: "HL70088",
  },
  {
    datatype: "ST",
    id: "PR1-4",
    item: "394",
    maxLength: 40,
    name: "Procedure description",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "PR1-5",
    item: "395",
    maxLength: 26,
    name: "Procedure date / time",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "PR1-6",
    item: "396",
    maxLength: 2,
    name: "Procedure type",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70090",
  },
  {
    datatype: "NM",
    id: "PR1-7",
    item: "397",
    maxLength: 4,
    name: "Procedure minutes",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CN",
    id: "PR1-8",
    item: "398",
    maxLength: 60,
    name: "Anesthesiologist",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70010",
  },
  {
    datatype: "ID",
    id: "PR1-9",
    item: "399",
    maxLength: 2,
    name: "Anesthesia code",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70019",
  },
  {
    datatype: "NM",
    id: "PR1-10",
    item: "400",
    maxLength: 4,
    name: "Anesthesia minutes",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CN",
    id: "PR1-11",
    item: "401",
    maxLength: 60,
    name: "Surgeon",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70010",
  },
  {
    datatype: "CM",
    id: "PR1-12",
    item: "402",
    maxLength: 60,
    name: "Procedure Practitioner",
    repeatable: true,
    required: false,
    sequence: 12,
    table: "HL70010",
  },
  {
    datatype: "ID",
    id: "PR1-13",
    item: "403",
    maxLength: 2,
    name: "Consent code",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70059",
  },
  {
    datatype: "NM",
    id: "PR1-14",
    item: "404",
    maxLength: 2,
    name: "Procedure priority",
    repeatable: false,
    required: false,
    sequence: 14,
  },
] as const;
