// Generated segment profile for PR1 (v2.2)

export const segmentId = "PR1";
export const fields = [
  {
    sequence: 1,
    id: "PR1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - procedure",
    item: "391",
  },
  {
    sequence: 2,
    id: "PR1-2",
    required: true,
    repeatable: true,
    datatype: "ID",
    maxLength: 2,
    table: "HL70089",
    name: "Procedure coding method",
    item: "392",
  },
  {
    sequence: 3,
    id: "PR1-3",
    required: true,
    repeatable: true,
    datatype: "ID",
    maxLength: 10,
    table: "HL70088",
    name: "Procedure code",
    item: "393",
  },
  {
    sequence: 4,
    id: "PR1-4",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 40,
    name: "Procedure description",
    item: "394",
  },
  {
    sequence: 5,
    id: "PR1-5",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Procedure date / time",
    item: "395",
  },
  {
    sequence: 6,
    id: "PR1-6",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70090",
    name: "Procedure type",
    item: "396",
  },
  {
    sequence: 7,
    id: "PR1-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Procedure minutes",
    item: "397",
  },
  {
    sequence: 8,
    id: "PR1-8",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    table: "HL70010",
    name: "Anesthesiologist",
    item: "398",
  },
  {
    sequence: 9,
    id: "PR1-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70019",
    name: "Anesthesia code",
    item: "399",
  },
  {
    sequence: 10,
    id: "PR1-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Anesthesia minutes",
    item: "400",
  },
  {
    sequence: 11,
    id: "PR1-11",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    table: "HL70010",
    name: "Surgeon",
    item: "401",
  },
  {
    sequence: 12,
    id: "PR1-12",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 60,
    table: "HL70010",
    name: "Procedure Practitioner",
    item: "402",
  },
  {
    sequence: 13,
    id: "PR1-13",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70059",
    name: "Consent code",
    item: "403",
  },
  {
    sequence: 14,
    id: "PR1-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    name: "Procedure priority",
    item: "404",
  },
] as const;
