// Generated segment profile for PV2 (v2.2)

export const segmentId = "PV2";
export const fields = [
  {
    datatype: "CM",
    id: "PV2-1",
    item: "181",
    maxLength: 12,
    name: "Prior Pending Location",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "PV2-2",
    item: "182",
    maxLength: 60,
    name: "Accommodation Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70129",
  },
  {
    datatype: "CE",
    id: "PV2-3",
    item: "183",
    maxLength: 60,
    name: "Admit Reason",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "PV2-4",
    item: "184",
    maxLength: 60,
    name: "Transfer Reason",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "PV2-5",
    item: "185",
    maxLength: 25,
    name: "Patient Valuables",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "PV2-6",
    item: "186",
    maxLength: 25,
    name: "Patient Valuables Location",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "PV2-7",
    item: "187",
    maxLength: 2,
    name: "Visit User Code",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70130",
  },
  {
    datatype: "DT",
    id: "PV2-8",
    item: "188",
    maxLength: 8,
    name: "Expected Admit Date",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DT",
    id: "PV2-9",
    item: "189",
    maxLength: 8,
    name: "Expected Discharge Date",
    repeatable: false,
    required: false,
    sequence: 9,
  },
] as const;
