// Generated segment profile for RXA (v2.2)

export const segmentId = "RXA";
export const fields = [
  {
    datatype: "NM",
    id: "RXA-1",
    item: "342",
    maxLength: 4,
    name: "Give Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "RXA-2",
    item: "344",
    maxLength: 4,
    name: "Administration Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "RXA-3",
    item: "345",
    maxLength: 26,
    name: "Date / time start of administration",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "RXA-4",
    item: "346",
    maxLength: 26,
    name: "Date / time end of administration",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "RXA-5",
    item: "347",
    maxLength: 100,
    name: "Administered Code",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "RXA-6",
    item: "348",
    maxLength: 20,
    name: "Administered Amount",
    repeatable: false,
    required: true,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "RXA-7",
    item: "349",
    maxLength: 60,
    name: "Administered Units",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CE",
    id: "RXA-8",
    item: "350",
    maxLength: 60,
    name: "Administered Dosage Form",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "RXA-9",
    item: "351",
    maxLength: 200,
    name: "Administration Notes",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CN",
    id: "RXA-10",
    item: "352",
    maxLength: 200,
    name: "Administering Provider",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CM",
    id: "RXA-11",
    item: "353",
    maxLength: 12,
    name: "Administered-at Location",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "RXA-12",
    item: "354",
    maxLength: 20,
    name: "Administered Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 12,
  },
] as const;
