// Generated segment profile for RXD (v2.2)

export const segmentId = "RXD";
export const fields = [
  {
    datatype: "NM",
    id: "RXD-1",
    item: "334",
    maxLength: 4,
    name: "Dispense Sub-ID Counter",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "RXD-2",
    item: "335",
    maxLength: 100,
    name: "Dispense / give code",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "RXD-3",
    item: "336",
    maxLength: 26,
    name: "Date / time dispensed",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "RXD-4",
    item: "337",
    maxLength: 20,
    name: "Actual Dispense Amount",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "RXD-5",
    item: "338",
    maxLength: 60,
    name: "Actual Dispense Units",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "RXD-6",
    item: "339",
    maxLength: 60,
    name: "Actual Dosage Form",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "RXD-7",
    item: "325",
    maxLength: 20,
    name: "Prescription Number",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "RXD-8",
    item: "326",
    maxLength: 20,
    name: "Number of Refills Remaining",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "RXD-9",
    item: "340",
    maxLength: 200,
    name: "Dispense Notes",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CN",
    id: "RXD-10",
    item: "341",
    maxLength: 200,
    name: "Dispensing Provider",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "RXD-11",
    item: "322",
    maxLength: 1,
    name: "Substitution Status",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70167",
  },
  {
    datatype: "CQ",
    id: "RXD-12",
    item: "329",
    maxLength: 10,
    name: "Total Daily Dose",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CM",
    id: "RXD-13",
    item: "299",
    maxLength: 12,
    name: "Deliver-to location",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ID",
    id: "RXD-14",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CE",
    id: "RXD-15",
    item: "330",
    maxLength: 200,
    name: "Pharmacy Special Dispensing Instructions",
    repeatable: false,
    required: false,
    sequence: 15,
  },
] as const;
