// Generated segment profile for RXG (v2.2)

export const segmentId = "RXG";
export const fields = [
  {
    datatype: "NM",
    id: "RXG-1",
    item: "342",
    maxLength: 4,
    name: "Give Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "RXG-2",
    item: "334",
    maxLength: 4,
    name: "Dispense Sub-ID Counter",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TQ",
    id: "RXG-3",
    item: "221",
    maxLength: 200,
    name: "Quantity / timing",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "RXG-4",
    item: "317",
    maxLength: 100,
    name: "Give Code",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "RXG-5",
    item: "318",
    maxLength: 20,
    name: "Give Amount - Minimum",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "RXG-6",
    item: "319",
    maxLength: 20,
    name: "Give Amount - Maximum",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "RXG-7",
    item: "320",
    maxLength: 60,
    name: "Give Units",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "CE",
    id: "RXG-8",
    item: "321",
    maxLength: 60,
    name: "Give Dosage Form",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "RXG-9",
    item: "351",
    maxLength: 200,
    name: "Administration Notes",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "RXG-10",
    item: "322",
    maxLength: 1,
    name: "Substitution Status",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70167",
  },
  {
    datatype: "CM",
    id: "RXG-11",
    item: "299",
    maxLength: 12,
    name: "Deliver-to location",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "RXG-12",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CE",
    id: "RXG-13",
    item: "343",
    maxLength: 200,
    name: "Pharmacy Special Administration Instructions",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "RXG-14",
    item: "331",
    maxLength: 20,
    name: "Give Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CE",
    id: "RXG-15",
    item: "332",
    maxLength: 6,
    name: "Give Rate Amount",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CE",
    id: "RXG-16",
    item: "333",
    maxLength: 60,
    name: "Give Rate Units",
    repeatable: false,
    required: false,
    sequence: 16,
  },
] as const;
