// Generated segment profile for RXO (v2.2)

export const segmentId = "RXO";
export const fields = [
  {
    datatype: "CE",
    id: "RXO-1",
    item: "292",
    maxLength: 100,
    name: "Requested Give Code",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "RXO-2",
    item: "293",
    maxLength: 20,
    name: "Requested Give Amount - Minimum",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "NM",
    id: "RXO-3",
    item: "294",
    maxLength: 20,
    name: "Requested Give Amount - Maximum",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "RXO-4",
    item: "295",
    maxLength: 60,
    name: "Requested Give Units",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "RXO-5",
    item: "296",
    maxLength: 60,
    name: "Requested Dosage Form",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "RXO-6",
    item: "297",
    maxLength: 200,
    name: "Provider&apos;s Pharmacy Instructions",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "RXO-7",
    item: "298",
    maxLength: 200,
    name: "Provider&apos;s Administration Instructions",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CM",
    id: "RXO-8",
    item: "299",
    maxLength: 12,
    name: "Deliver-to location",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ID",
    id: "RXO-9",
    item: "300",
    maxLength: 1,
    name: "Allow Substitutions",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70161",
  },
  {
    datatype: "CE",
    id: "RXO-10",
    item: "301",
    maxLength: 100,
    name: "Requested Dispense Code",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "RXO-11",
    item: "302",
    maxLength: 20,
    name: "Requested Dispense Amount",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CE",
    id: "RXO-12",
    item: "303",
    maxLength: 60,
    name: "Requested Dispense Units",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "RXO-13",
    item: "304",
    maxLength: 3,
    name: "Number of Refills",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CN",
    id: "RXO-14",
    item: "305",
    maxLength: 60,
    name: "Ordering Provider&apos;s DEA Number",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CN",
    id: "RXO-15",
    item: "306",
    maxLength: 60,
    name: "Pharmacist Verifier ID",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "RXO-16",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ST",
    id: "RXO-17",
    item: "308",
    maxLength: 20,
    name: "Requested Give Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 17,
  },
] as const;
