// Generated segment profile for STF (v2.2)

export const segmentId = "STF";
export const fields = [
  {
    datatype: "CE",
    id: "STF-1",
    item: "671",
    maxLength: 60,
    name: "STF - primary key value",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "STF-2",
    item: "672",
    maxLength: 60,
    name: "Staff ID Code",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "PN",
    id: "STF-3",
    item: "673",
    maxLength: 48,
    name: "Staff Name",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "STF-4",
    item: "674",
    maxLength: 2,
    name: "Staff Type",
    repeatable: true,
    required: false,
    sequence: 4,
    table: "HL70182",
  },
  {
    datatype: "ID",
    id: "STF-5",
    item: "111",
    maxLength: 1,
    name: "Sex",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70001",
  },
  {
    datatype: "TS",
    id: "STF-6",
    item: "110",
    maxLength: 26,
    name: "Date of Birth",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "STF-7",
    item: "675",
    maxLength: 1,
    name: "Active / inactive",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70183",
  },
  {
    datatype: "CE",
    id: "STF-8",
    item: "676",
    maxLength: 200,
    name: "Department",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70184",
  },
  {
    datatype: "CE",
    id: "STF-9",
    item: "677",
    maxLength: 200,
    name: "Service",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "TN",
    id: "STF-10",
    item: "678",
    maxLength: 40,
    name: "Phone",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "AD",
    id: "STF-11",
    item: "679",
    maxLength: 106,
    name: "Office / home address",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CM",
    id: "STF-12",
    item: "680",
    maxLength: 19,
    name: "Activation Date",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CM",
    id: "STF-13",
    item: "681",
    maxLength: 19,
    name: "Inactivation Date",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CE",
    id: "STF-14",
    item: "682",
    maxLength: 60,
    name: "Backup Person ID",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "STF-15",
    item: "683",
    maxLength: 40,
    name: "E-mail Address",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "STF-16",
    item: "684",
    maxLength: 1,
    name: "Preferred method of Contact",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70185",
  },
] as const;
