// Generated profile automaton for RSP_Z86 (v2.4)

export const start = 0;
export const finals = new Set<number>([
  5, 6, 8, 12, 13, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
]);
export const alphabet = new Set<string>([
  "AL1",
  "DSC",
  "ERR",
  "MSA",
  "MSH",
  "NTE",
  "OBX",
  "ORC",
  "PD1",
  "PID",
  "QAK",
  "QPD",
  "RXA",
  "RXC",
  "RXD",
  "RXE",
  "RXG",
  "RXO",
  "RXR",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [1, new Map([["MSA", 2]])],
  [
    2,
    new Map([
      ["ERR", 4],
      ["QAK", 3],
    ]),
  ],
  [3, new Map([["QPD", 5]])],
  [4, new Map([["QAK", 3]])],
  [
    5,
    new Map([
      ["DSC", 6],
      ["PID", 7],
    ]),
  ],
  [6, new Map([])],
  [
    7,
    new Map([
      ["AL1", 9],
      ["NTE", 10],
      ["ORC", 8],
      ["PD1", 11],
    ]),
  ],
  [
    8,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXD", 16],
      ["RXE", 17],
      ["RXG", 15],
      ["RXO", 18],
    ]),
  ],
  [
    9,
    new Map([
      ["AL1", 9],
      ["ORC", 8],
    ]),
  ],
  [
    10,
    new Map([
      ["AL1", 9],
      ["NTE", 10],
      ["ORC", 8],
    ]),
  ],
  [
    11,
    new Map([
      ["AL1", 9],
      ["NTE", 10],
      ["ORC", 8],
    ]),
  ],
  [
    12,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
    ]),
  ],
  [
    13,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
    ]),
  ],
  [14, new Map([["RXR", 19]])],
  [15, new Map([["RXR", 20]])],
  [16, new Map([["RXR", 21]])],
  [17, new Map([["RXR", 22]])],
  [18, new Map([["RXR", 23]])],
  [
    19,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXC", 24],
      ["RXR", 19],
    ]),
  ],
  [
    20,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 25],
      ["RXR", 20],
    ]),
  ],
  [
    21,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 26],
      ["RXG", 15],
      ["RXR", 21],
    ]),
  ],
  [
    22,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 27],
      ["RXD", 16],
      ["RXG", 15],
      ["RXR", 22],
    ]),
  ],
  [
    23,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 28],
      ["RXD", 16],
      ["RXE", 17],
      ["RXG", 15],
      ["RXR", 23],
    ]),
  ],
  [
    24,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXC", 24],
    ]),
  ],
  [
    25,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 25],
    ]),
  ],
  [
    26,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 26],
      ["RXG", 15],
    ]),
  ],
  [
    27,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 27],
      ["RXD", 16],
      ["RXG", 15],
    ]),
  ],
  [
    28,
    new Map([
      ["DSC", 6],
      ["NTE", 12],
      ["OBX", 13],
      ["ORC", 8],
      ["PID", 7],
      ["RXA", 14],
      ["RXC", 28],
      ["RXD", 16],
      ["RXE", 17],
      ["RXG", 15],
    ]),
  ],
]);
export const effects = {
  "10:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "11:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "12:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "12:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [],
  },
  "12:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [],
  },
  "12:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "12:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
  },
  "13:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "13:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [],
  },
  "13:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "13:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
  },
  "19:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "19:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
  },
  "19:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
  },
  "19:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "19:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "20:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "20:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "20:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "20:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "20:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "20:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "21:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "21:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "21:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "21:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "21:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "21:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "21:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "22:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "22:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "22:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "22:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "22:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "22:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "22:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "22:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "23:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "23:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "23:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "24:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "24:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
  },
  "24:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
  },
  "24:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "24:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "25:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "25:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "25:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "25:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "25:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "25:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "26:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "26:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "26:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "26:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "26:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "26:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "26:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "27:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "27:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "27:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
    ],
  },
  "27:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "27:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "27:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "27:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "27:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "28:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "28:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "28:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "5:DSC": {
    groupsOpened: [],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "5:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [],
  },
  "7:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "8:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
  "8:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:RXA": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
    ],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "8:RXO": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ORDER_DETAIL"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER/OBSERVATION",
    ],
  },
  "9:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/PATIENT/COMMON_ORDER"],
    groupsClosed: [],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
