// Generated table profile for 0396 (v2.8)

export const id = "0396";
export const description = "Coding System";
export const type = "hl7";
export const codes = [
  {
    description: "Local general code where z is an alphanumeric character",
    name: "99zzz",
  },
  { description: "American College of Radiology finding codes", name: "ACR" },
  { description: "German Alpha-ID v2006", name: "ALPHAID2006" },
  { description: "German Alpha-ID v2007", name: "ALPHAID2007" },
  { description: "German Alpha-ID v2008", name: "ALPHAID2008" },
  { description: "German Alpha-ID v2009", name: "ALPHAID2009" },
  { description: "German Alpha-ID v2010", name: "ALPHAID2010" },
  { description: "German Alpha-ID v2011", name: "ALPHAID2011" },
  { description: "HL7 set of units of measure", name: "ANS+" },
  { description: "WHO Adverse Reaction Terms", name: "ART" },
  { description: "ASTM E1238/ E1467 Universal", name: "AS4" },
  { description: "AS4 Neurophysiology Codes", name: "AS4E" },
  { description: "American Type Culture Collection", name: "ATC" },
  { description: "CPT-4", name: "C4" },
  {
    description: "College of American Pathologists Electronic Cancer Checklist",
    name: "CAPECC",
  },
  { description: "Chemical abstract codes", name: "CAS" },
  { description: "Clinical Care Classification system", name: "CCC" },
  { description: "CDT-2 Codes", name: "CD2" },
  { description: "CDC Analyte Codes", name: "CDCA" },
  { description: "CDC Emergency Department Acuity", name: "CDCEDACUITY" },
  { description: "CDC Methods/Instruments Codes", name: "CDCM" },
  {
    description: "CDC BioSense RT observations (Census) - CDC",
    name: "CDCOBS",
  },
  { description: "CDC PHIN Vocabulary Coding System", name: "CDCPHINVS" },
  { description: "Race & Ethnicity - CDC", name: "CDCREC" },
  { description: "CDC Surveillance", name: "CDS" },
  { description: "CEN ECG diagnostic codes", name: "CE (obsolete)" },
  { description: "CLIP", name: "CLP" },
  { description: "CPT Modifier Code", name: "CPTM" },
  { description: "COSTART", name: "CST" },
  { description: "CDC Vaccine Codes", name: "CVX" },
  { description: "DICOM Controlled Terminology", name: "DCM" },
  { description: "EUCLIDES", name: "E" },
  { description: "Euclides  quantity codes", name: "E5" },
  { description: "Euclides Lab method codes", name: "E6" },
  { description: "Euclides Lab equipment codes", name: "E7" },
  { description: "Enzyme Codes", name: "ENZC" },
  { description: "EPA SRS", name: "EPASRS" },
  { description: "Unique Ingredient Identifier (UNII)", name: "FDAUNII" },
  { description: "First DataBank Drug Codes", name: "FDDC" },
  { description: "First DataBank Diagnostic Codes", name: "FDDX" },
  { description: "FDA K10", name: "FDK" },
  { description: "FIPS 5-2 (State)", name: "FIPS5_2" },
  { description: "FIPS 6-4 (County)", name: "FIPS6_4" },
  { description: "G-DRG German DRG Codes v2004", name: "GDRG2004" },
  { description: "G-DRG German DRG Codes v2005", name: "GDRG2005" },
  { description: "G-DRG German DRG Codes v2006", name: "GDRG2006" },
  { description: "G-DRG German DRG Codes v2007", name: "GDRG2007" },
  { description: "G-DRG German DRG Codes v2008", name: "GDRG2008" },
  { description: "G-DRG German DRG Codes v2009", name: "GDRG2009" },
  { description: "German Major Diagnostic Codes v2004", name: "GMDC2004" },
  { description: "German Major Diagnostic Codes v2005", name: "GMDC2005" },
  { description: "German Major Diagnostic Codes v2006", name: "GMDC2006" },
  { description: "German Major Diagnostic Codes v2007", name: "GMDC2007" },
  { description: "German Major Diagnostic Codes v2008", name: "GMDC2008" },
  { description: "German Major Diagnostic Codes v2009", name: "GMDC2009" },
  { description: "HIBCC", name: "HB" },
  {
    description: "CMS (formerly HCFA)  Common Procedure Coding System",
    name: "HCPCS",
  },
  { description: "Health Care Provider Taxonomy", name: "HCPT" },
  { description: "Home Health Care", name: "HHC" },
  { description: "Health Outcomes", name: "HI" },
  {
    description: "HL7 Defined Codes where nnnn is the HL7 table number",
    name: "HL7nnnn",
  },
  { description: "Japanese Nationwide Medicine Code", name: "HOT" },
  { description: "CMS (formerly HCFA )Procedure Codes (HCPCS)", name: "HPC" },
  { description: "ICD-10", name: "I10" },
  { description: "ICD 10 Germany 2004", name: "I10G2004" },
  { description: "ICD 10 Germany 2005", name: "I10G2005" },
  { description: "ICD 10 Germany 2006", name: "I10G2006" },
  { description: "ICD-10  Procedure Codes", name: "I10P" },
  { description: "ICD9", name: "I9" },
  { description: "ICD-9CM", name: "I9C" },
  { description: "ICD-9CM Diagnosis codes", name: "I9CDX" },
  { description: "ICD-9CM Procedure codes", name: "I9CP" },
  { description: "ISBT", name: "IBT" },
  {
    description:
      "ISBT 128 codes where nnnn  specifies a specific table within ISBT 128.",
    name: "IBTnnnn",
  },
  { description: "ICHPPC-2", name: "IC2" },
  { description: "ICD-10 Australian modification", name: "ICD10AM" },
  { description: "ICD-10 Canada", name: "ICD10CA" },
  { description: "ICD 10 Germany v2007", name: "ICD10GM2007" },
  { description: "ICD 10 Germany v2008", name: "ICD10GM2008" },
  { description: "ICD 10 Germany v2009", name: "ICD10GM2009" },
  { description: "ICD 10 Germany v2010", name: "ICD10GM2010" },
  { description: "ICD 10 Germany v2011", name: "ICD10GM2011" },
  {
    description: "International Classification of Diseases for Oncology",
    name: "ICDO",
  },
  {
    description:
      "International Classification of Disease for Oncology Second Edition",
    name: "ICDO2",
  },
  {
    description:
      "International Classification of Disease for Oncology Third Edition",
    name: "ICDO3",
  },
  { description: "ICCS", name: "ICS" },
  {
    description: "International Classification of Sleep Disorders",
    name: "ICSD",
  },
  {
    description: "ISO 2955.83 (units of measure) with HL7 extensions",
    name: "ISO",
  },
  { description: "ISO 3166-1 Country Codes", name: "ISO3166_1" },
  { description: "ISO 3166-2 Country subdivisions", name: "ISO3166_2" },
  { description: "ISO4217 Currency Codes", name: "ISO4217" },
  { description: "ISO 639 Language", name: "ISO639" },
  {
    description: "ISO Defined Codes where nnnn is the ISO table number",
    name: "ISOnnnn (deprecated)",
  },
  { description: "Integrated Taxonomic Information System", name: "ITIS" },
  { description: "IUPAC/IFCC Component Codes", name: "IUPC" },
  { description: "IUPAC/IFCC Property Codes", name: "IUPP" },
  { description: "JLAC/JSLM, nationwide laboratory code", name: "JC10" },
  { description: "Japanese Chemistry", name: "JC8" },
  { description: "Japanese Image Examination Cache", name: "JJ1017" },
  { description: "Local general code", name: "L" },
  { description: "Local billing code", name: "LB" },
  {
    description: "Logical Observation Identifier Names and Codes (LOINCÂ®)",
    name: "LN",
  },
  { description: "Medicaid", name: "MCD" },
  { description: "Medicare", name: "MCR" },
  { description: "Medical Device Communication", name: "MDC" },
  { description: "Medispan Diagnostic Codes", name: "MDDX" },
  { description: "Medical Economics Drug Codes", name: "MEDC" },
  {
    description: "Medical Dictionary for Drug Regulatory Affairs (MEDDRA)",
    name: "MEDR",
  },
  { description: "Medical Economics Diagnostic Codes", name: "MEDX" },
  { description: "Medispan GPI", name: "MGPI" },
  { description: "CDC Vaccine Manufacturer Codes", name: "MVX" },
  { description: "Industry (NAICS)", name: "NAICS" },
  {
    description:
      "NCPDP code list for data element nnnn [as used in segment sss]",
    name: "NCPDPnnnnsss",
  },
  { description: "NANDA", name: "NDA" },
  { description: "National drug codes", name: "NDC" },
  { description: "NDF-RT (Drug Classification)", name: "NDFRT" },
  { description: "Nursing Interventions Classification", name: "NIC" },
  { description: "Source of Information (Immunization)", name: "NIP001" },
  { description: "Substance refusal reason", name: "NIP002" },
  {
    description: "Vaccination - Contraindications, Precautions, and Immunities",
    name: "NIP004",
  },
  { description: "Vaccinated at location (facility)", name: "NIP007" },
  { description: "Vaccine purchased with (Type of funding)", name: "NIP008" },
  { description: "Reported adverse event previously", name: "NIP009" },
  { description: "VAERS Report type", name: "NIP010" },
  {
    description: "Notifiable Event (Disease/Condition) Code List",
    name: "NND",
  },
  { description: "National Provider Identifier", name: "NPI" },
  { description: "National Uniform Billing Committee", name: "NUBC" },
  { description: "Null Flavor", name: "NULLFL" },
  { description: "German Procedure Codes", name: "O301" },
  { description: "OPS Germany v2004", name: "O3012004" },
  { description: "OPS Germany v2005", name: "O3012005" },
  { description: "OPS Germany v2006", name: "O3012006" },
  { description: "Omaha System", name: "OHA" },
  { description: "OPS Germany v2007", name: "OPS2007" },
  { description: "OPS Germany v2008", name: "OPS2008" },
  { description: "OPS Germany v2009", name: "OPS2009" },
  { description: "OPS Germany v2010", name: "OPS2010" },
  { description: "OPS Germany v2011", name: "OPS2011" },
  {
    description: "CDC Public Health Information Network (PHIN) Question",
    name: "PHINQUESTION",
  },
  {
    description:
      "CDC PHLIP Lab result codes that are not covered in SNOMED at the time of this implementation",
    name: "PLR",
  },
  {
    description:
      "CDC PHLIP Lab test codes, where LOINC concept is too broad or not yet available, especially as needed for ordering and or lab to lab reporting )",
    name: "PLT",
  },
  { description: "POS Codes", name: "POS" },
  { description: "Read Classification", name: "RC" },
  { description: "RxNorm", name: "RXNORM" },
  { description: "SNOMED Clinical Terms", name: "SCT" },
  { description: "SNOMED Clinical Terms alphanumeric codes", name: "SCT2" },
  { description: "SNOMED- DICOM Microglossary", name: "SDM" },
  { description: "Industry (SIC)", name: "SIC" },
  { description: "Systemized Nomenclature of Medicine (SNOMED)", name: "SNM" },
  { description: "SNOMED International", name: "SNM3" },
  { description: "SNOMED topology codes (anatomic sites)", name: "SNT" },
  { description: "Occupation (SOC 2000)", name: "SOC" },
  { description: "Priority (Type) of Visit", name: "UB04FL14" },
  { description: "Point of Origin", name: "UB04FL15" },
  { description: "Patient Discharge Status", name: "UB04FL17" },
  { description: "Occurrence Code", name: "UB04FL31" },
  { description: "Occurrence Span", name: "UB04FL35" },
  { description: "Value Code", name: "UB04FL39" },
  { description: "UCDS", name: "UC" },
  {
    description: "UCUM code set for units of measure(from Regenstrief)",
    name: "UCUM",
  },
  { description: "MDNS", name: "UMD" },
  { description: "Unified Medical Language", name: "UML" },
  { description: "Universal Product Code", name: "UPC" },
  { description: "UPIN", name: "UPIN" },
  { description: "United States Postal Service", name: "USPS" },
  { description: "WHO record # drug codes (6 digit)", name: "W1" },
  { description: "WHO record # drug codes (8 digit)", name: "W2" },
  { description: "WHO record # code with ASTM extension", name: "W4" },
  { description: "WHO ATC", name: "WC" },
  { description: "ASC X12 Code List nnnn", name: "X12Dennnn" },
] as const;
