// Generated table profile for 0487 (v2.8)

export const id = "0487";
export const description = "Specimen Type";
export const type = "hl7";
export const codes = [
  { description: "Abscess", name: "ABS" },
  { description: "Tissue, Acne", name: "ACNE" },
  { description: "Fluid, Acne", name: "ACNFLD" },
  { description: "Air Sample", name: "AIRS" },
  { description: "Allograft", name: "ALL" },
  { description: "Amputation", name: "AMP" },
  { description: "Catheter Tip, Angio", name: "ANGI" },
  { description: "Catheter Tip, Arterial", name: "ARTC" },
  { description: "Serum, Acute", name: "ASERU" },
  { description: "Aspirate", name: "ASP" },
  { description: "Environment, Attest", name: "ATTE" },
  { description: "Environmental, Autoclave Ampule", name: "AUTOA" },
  { description: "Environmental, Autoclave Capsule", name: "AUTOC" },
  { description: "Autopsy", name: "AUTP" },
  { description: "Blood bag", name: "BBL" },
  { description: "Cyst, Baker's", name: "BCYST" },
  { description: "Bite", name: "BITE" },
  { description: "Bleb", name: "BLEB" },
  { description: "Blister", name: "BLIST" },
  { description: "Boil", name: "BOIL" },
  { description: "Bone", name: "BON" },
  { description: "Bowel contents", name: "BOWL" },
  { description: "Blood product unit", name: "BPU" },
  { description: "Burn", name: "BRN" },
  { description: "Brush", name: "BRSH" },
  { description: "Breath (use EXHLD)", name: "BRTH" },
  { description: "Brushing", name: "BRUS" },
  { description: "Bubo", name: "BUB" },
  { description: "Bulla/Bullae", name: "BULLA" },
  { description: "Biopsy", name: "BX" },
  { description: "Calculus (=Stone)", name: "CALC" },
  { description: "Carbuncle", name: "CARBU" },
  { description: "Catheter", name: "CAT" },
  { description: "Bite, Cat", name: "CBITE" },
  { description: "Clippings", name: "CLIPP" },
  { description: "Conjunctiva", name: "CNJT" },
  { description: "Colostrum", name: "COL" },
  { description: "Biospy, Cone", name: "CONE" },
  { description: "Scratch, Cat", name: "CSCR" },
  { description: "Serum, Convalescent", name: "CSERU" },
  { description: "Catheter Insertion Site", name: "CSITE" },
  { description: "Fluid,  Cystostomy Tube", name: "CSMY" },
  { description: "Fluid, Cyst", name: "CST" },
  { description: "Blood, Cell Saver", name: "CSVR" },
  { description: "Catheter tip", name: "CTP" },
  { description: "Site, CVP", name: "CVPS" },
  { description: "Catheter Tip, CVP", name: "CVPT" },
  { description: "Nodule, Cystic", name: "CYN" },
  { description: "Cyst", name: "CYST" },
  { description: "Bite, Dog", name: "DBITE" },
  { description: "Sputum, Deep Cough", name: "DCS" },
  { description: "Ulcer, Decubitus", name: "DEC" },
  { description: "Environmental, Water  (Deionized)", name: "DEION" },
  { description: "Dialysate", name: "DIA" },
  { description: "Discharge", name: "DISCHG" },
  { description: "Diverticulum", name: "DIV" },
  { description: "Drain", name: "DRN" },
  { description: "Drainage, Tube", name: "DRNG" },
  { description: "Drainage, Penrose", name: "DRNGP" },
  { description: "Ear wax (cerumen)", name: "EARW" },
  { description: "Brush, Esophageal", name: "EBRUSH" },
  { description: "Environmental, Eye Wash", name: "EEYE" },
  { description: "Environmental, Effluent", name: "EFF" },
  { description: "Effusion", name: "EFFUS" },
  { description: "Environmental, Food", name: "EFOD" },
  { description: "Environmental, Isolette", name: "EISO" },
  { description: "Electrode", name: "ELT" },
  { description: "Environmental, Unidentified Substance", name: "ENVIR" },
  { description: "Environmental, Other Substance", name: "EOTH" },
  { description: "Environmental, Soil", name: "ESOI" },
  { description: "Environmental, Solution (Sterile)", name: "ESOS" },
  { description: "Aspirate,  Endotrach", name: "ETA" },
  { description: "Catheter Tip, Endotracheal", name: "ETTP" },
  { description: "Tube, Endotracheal", name: "ETTUB" },
  { description: "Environmental, Whirlpool", name: "EWHI" },
  { description: "Gas, exhaled (=breath)", name: "EXG" },
  { description: "Shunt, External", name: "EXS" },
  { description: "Exudate", name: "EXUDTE" },
  { description: "Environmental, Water  (Well)", name: "FAW" },
  { description: "Blood, Fetal", name: "FBLOOD" },
  { description: "Fluid,  Abdomen", name: "FGA" },
  { description: "Fistula", name: "FIST" },
  { description: "Fluid, Other", name: "FLD" },
  { description: "Filter", name: "FLT" },
  { description: "Fluid, Body unsp", name: "FLU" },
  { description: "Fluid", name: "FLUID" },
  { description: "Catheter Tip, Foley", name: "FOLEY" },
  { description: "Fluid, Respiratory", name: "FRS" },
  { description: "Scalp, Fetal", name: "FSCLP" },
  { description: "Furuncle", name: "FUR" },
  { description: "Gas", name: "GAS" },
  { description: "Aspirate, Gastric", name: "GASA" },
  { description: "Antrum, Gastric", name: "GASAN" },
  { description: "Brushing, Gastric", name: "GASBR" },
  { description: "Drainage, Gastric", name: "GASD" },
  { description: "Fluid/contents, Gastric", name: "GAST" },
  { description: "Genital vaginal", name: "GENV" },
  { description: "Graft", name: "GRAFT" },
  { description: "Graft Site", name: "GRAFTS" },
  { description: "Granuloma", name: "GRANU" },
  { description: "Catheter, Groshong", name: "GROSH" },
  { description: "Solution, Gastrostomy", name: "GSOL" },
  { description: "Biopsy, Gastric", name: "GSPEC" },
  { description: "Tube, Gastric", name: "GT" },
  { description: "Drainage Tube, Drainage (Gastrostomy)", name: "GTUBE" },
  { description: "Bite, Human", name: "HBITE" },
  { description: "Blood, Autopsy", name: "HBLUD" },
  { description: "Catheter Tip, Hemaquit", name: "HEMAQ" },
  { description: "Catheter Tip, Hemovac", name: "HEMO" },
  { description: "Tissue, Herniated", name: "HERNI" },
  { description: "Drain, Hemovac", name: "HEV" },
  { description: "Catheter, Hickman", name: "HIC" },
  { description: "Fluid, Hydrocele", name: "HYDC" },
  { description: "Bite, Insect", name: "IBITE" },
  { description: "Cyst, Inclusion", name: "ICYST" },
  { description: "Catheter Tip, Indwelling", name: "IDC" },
  { description: "Gas, Inhaled", name: "IHG" },
  { description: "Drainage, Ileostomy", name: "ILEO" },
  { description: "Source of Specimen Is Illegible", name: "ILLEG" },
  { description: "Implant", name: "IMP" },
  { description: "Site, Incision/Surgical", name: "INCI" },
  { description: "Infiltrate", name: "INFIL" },
  { description: "Insect", name: "INS" },
  { description: "Catheter Tip, Introducer", name: "INTRD" },
  { description: "Intubation tube", name: "IT" },
  { description: "Intrauterine Device", name: "IUD" },
  { description: "Catheter Tip, IV", name: "IVCAT" },
  { description: "Fluid, IV", name: "IVFLD" },
  { description: "Tubing Tip, IV", name: "IVTIP" },
  { description: "Drainage, Jejunal", name: "JEJU" },
  { description: "Fluid, Joint", name: "JNTFLD" },
  { description: "Drainage, Jackson Pratt", name: "JP" },
  { description: "Lavage", name: "KELOI" },
  { description: "Fluid, Kidney", name: "KIDFLD" },
  { description: "Lavage, Bronhial", name: "LAVG" },
  { description: "Lavage, Gastric", name: "LAVGG" },
  { description: "Lavage, Peritoneal", name: "LAVGP" },
  { description: "Lavage, Pre-Bronch", name: "LAVPG" },
  { description: "Contact Lens", name: "LENS1" },
  { description: "Contact Lens Case", name: "LENS2" },
  { description: "Lesion", name: "LESN" },
  { description: "Liquid, Unspecified", name: "LIQ" },
  { description: "Liquid, Other", name: "LIQO" },
  { description: "Fluid, Lumbar Sac", name: "LSAC" },
  { description: "Catheter Tip, Makurkour", name: "MAHUR" },
  { description: "Mass", name: "MASS" },
  { description: "Blood, Menstrual", name: "MBLD" },
  { description: "Mucosa", name: "MUCOS" },
  { description: "Mucus", name: "MUCUS" },
  { description: "Drainage, Nasal", name: "NASDR" },
  { description: "Needle", name: "NEDL" },
  { description: "Site, Nephrostomy", name: "NEPH" },
  { description: "Aspirate, Nasogastric", name: "NGASP" },
  { description: "Drainage, Nasogastric", name: "NGAST" },
  { description: "Site, Naso/Gastric", name: "NGS" },
  { description: "Nodule(s)", name: "NODUL" },
  { description: "Secretion, Nasal", name: "NSECR" },
  { description: "Other", name: "ORH" },
  { description: "Lesion, Oral", name: "ORL" },
  { description: "Source, Other", name: "OTH" },
  { description: "Pacemaker", name: "PACEM" },
  { description: "Fluid, Pericardial", name: "PCFL" },
  { description: "Site, Peritoneal Dialysis", name: "PDSIT" },
  { description: "Site, Peritoneal Dialysis Tunnel", name: "PDTS" },
  { description: "Abscess, Pelvic", name: "PELVA" },
  { description: "Lesion, Penile", name: "PENIL" },
  { description: "Abscess, Perianal", name: "PERIA" },
  { description: "Cyst, Pilonidal", name: "PILOC" },
  { description: "Site, Pin", name: "PINS" },
  { description: "Site, Pacemaker Insetion", name: "PIS" },
  { description: "Plant Material", name: "PLAN" },
  { description: "Plasma", name: "PLAS" },
  { description: "Plasma bag", name: "PLB" },
  { description: "Serum, Peak Level", name: "PLEVS" },
  { description: "Drainage, Penile", name: "PND" },
  { description: "Polyps", name: "POL" },
  { description: "Graft Site, Popliteal", name: "POPGS" },
  { description: "Graft, Popliteal", name: "POPLG" },
  { description: "Site, Popliteal Vein", name: "POPLV" },
  { description: "Catheter, Porta", name: "PORTA" },
  { description: "Plasma, Platelet poor", name: "PPP" },
  { description: "Prosthetic Device", name: "PROST" },
  { description: "Plasma, Platelet rich", name: "PRP" },
  { description: "Pseudocyst", name: "PSC" },
  { description: "Wound, Puncture", name: "PUNCT" },
  { description: "Pus", name: "PUS" },
  { description: "Pustule", name: "PUSFR" },
  { description: "Pus", name: "PUST" },
  { description: "Quality Control", name: "QC3" },
  { description: "Urine, Random", name: "RANDU" },
  { description: "Bite, Reptile", name: "RBITE" },
  { description: "Drainage, Rectal", name: "RECT" },
  { description: "Abscess, Rectal", name: "RECTA" },
  { description: "Cyst, Renal", name: "RENALC" },
  { description: "Fluid, Renal Cyst", name: "RENC" },
  { description: "Respiratory", name: "RES" },
  { description: "Saliva", name: "SAL" },
  { description: "Tissue, Keloid (Scar)", name: "SCAR" },
  { description: "Catheter Tip, Subclavian", name: "SCLV" },
  { description: "Abscess, Scrotal", name: "SCROA" },
  { description: "Secretion(s)", name: "SECRE" },
  { description: "Serum", name: "SER" },
  { description: "Site, Shunt", name: "SHU" },
  { description: "Fluid, Shunt", name: "SHUNF" },
  { description: "Shunt", name: "SHUNT" },
  { description: "Site", name: "SITE" },
  { description: "Biopsy, Skin", name: "SKBP" },
  { description: "Skin", name: "SKN" },
  { description: "Mass, Sub-Mandibular", name: "SMM" },
  { description: "Fluid, synovial (Joint fluid)", name: "SNV" },
  { description: "Spermatozoa", name: "SPRM" },
  { description: "Catheter Tip, Suprapubic", name: "SPRP" },
  { description: "Cathether Tip, Suprapubic", name: "SPRPB" },
  { description: "Environmental, Spore Strip", name: "SPS" },
  { description: "Sputum", name: "SPT" },
  { description: "Sputum - coughed", name: "SPTC" },
  { description: "Sputum - tracheal aspirate", name: "SPTT" },
  { description: "Sputum, Simulated", name: "SPUT1" },
  { description: "Sputum, Inducted", name: "SPUTIN" },
  { description: "Sputum, Spontaneous", name: "SPUTSP" },
  { description: "Environmental, Sterrad", name: "STER" },
  { description: "Stool = Fecal", name: "STL" },
  { description: "Stone, Kidney", name: "STONE" },
  { description: "Abscess, Submandibular", name: "SUBMA" },
  { description: "Abscess, Submaxillary", name: "SUBMX" },
  { description: "Drainage, Sump", name: "SUMP" },
  { description: "Suprapubic Tap", name: "SUP" },
  { description: "Suture", name: "SUTUR" },
  { description: "Catheter Tip, Swan Gantz", name: "SWGZ" },
  { description: "Aspirate, Tracheal", name: "TASP" },
  { description: "Tissue", name: "TISS" },
  { description: "Tissue ulcer", name: "TISU" },
  { description: "Cathether Tip, Triple Lumen", name: "TLC" },
  { description: "Site, Tracheostomy", name: "TRAC" },
  { description: "Transudate", name: "TRANS" },
  { description: "Serum, Trough", name: "TSERU" },
  { description: "Abscess, Testicular", name: "TSTES" },
  { description: "Aspirate, Transtracheal", name: "TTRA" },
  { description: "Tubes", name: "TUBES" },
  { description: "Tumor", name: "TUMOR" },
  { description: "Smear, Tzanck", name: "TZANC" },
  { description: "Source, Unidentified", name: "UDENT" },
  { description: "Urine", name: "UR" },
  { description: "Urine clean catch", name: "URC" },
  { description: "Urine, Bladder Washings", name: "URINB" },
  { description: "Urine, Catheterized", name: "URINC" },
  { description: "Urine, Midstream", name: "URINM" },
  { description: "Urine, Nephrostomy", name: "URINN" },
  { description: "Urine, Pedibag", name: "URINP" },
  { description: "Urine catheter", name: "URT" },
  { description: "Urine, Cystoscopy", name: "USCOP" },
  { description: "Source, Unspecified", name: "USPEC" },
  { description: "Catheter Tip, Vas", name: "VASTIP" },
  { description: "Catheter Tip, Ventricular", name: "VENT" },
  { description: "Vitreous Fluid", name: "VITF" },
  { description: "Vomitus", name: "VOM" },
  { description: "Wash", name: "WASH" },
  { description: "Washing, e.g. bronchial washing", name: "WASI" },
  { description: "Water", name: "WAT" },
  { description: "Blood, Whole", name: "WB" },
  { description: "Wen", name: "WEN" },
  { description: "Wick", name: "WICK" },
  { description: "Wound", name: "WND" },
  { description: "Wound abscess", name: "WNDA" },
  { description: "Wound drainage", name: "WNDD" },
  { description: "Wound exudate", name: "WNDE" },
  { description: "Worm", name: "WORM" },
  { description: "Wart", name: "WRT" },
  { description: "Environmental, Water", name: "WWA" },
  { description: "Environmental, Water (Ocean)", name: "WWO" },
  { description: "Environmental, Water  (Tap)", name: "WWT" },
] as const;
