// Generated table profile for 0119 (v2.5)

export const id = "0119";
export const description = "Order control codes";
export const type = "hl7";
export const codes = [
  { description: "Order/service refill request approval", name: "AF" },
  { description: "Cancel order/service request", name: "CA" },
  { description: "Child order/service", name: "CH" },
  { description: "Combined result", name: "CN" },
  { description: "Canceled as requested", name: "CR" },
  { description: "Discontinue order/service request", name: "DC" },
  { description: "Data errors", name: "DE" },
  { description: "Order/service refill request denied", name: "DF" },
  { description: "Discontinued as requested", name: "DR" },
  { description: "Order/service refilled, unsolicited", name: "FU" },
  { description: "Hold order request", name: "HD" },
  { description: "On hold as requested", name: "HR" },
  {
    description: "Link order/service to patient care problem or goal",
    name: "LI",
  },
  { description: "Number assigned", name: "NA" },
  { description: "New order/service", name: "NW" },
  { description: "Order/service canceled", name: "OC" },
  { description: "Order/service discontinued", name: "OD" },
  { description: "Order/service released", name: "OE" },
  { description: "Order/service refilled as requested", name: "OF" },
  { description: "Order/service held", name: "OH" },
  { description: "Order/service accepted & OK", name: "OK" },
  { description: "Notification of order for outside dispense", name: "OP" },
  { description: "Released as requested", name: "OR" },
  { description: "Parent order/service", name: "PA" },
  { description: "Previous Results with new order/service", name: "PR" },
  {
    description: "Notification of replacement order for outside dispense",
    name: "PY",
  },
  { description: "Observations/Performed Service to follow", name: "RE" },
  { description: "Refill order/service request", name: "RF" },
  { description: "Release previous hold", name: "RL" },
  { description: "Replacement order", name: "RO" },
  { description: "Order/service replace request", name: "RP" },
  { description: "Replaced as requested", name: "RQ" },
  { description: "Request received", name: "RR" },
  { description: "Replaced unsolicited", name: "RU" },
  { description: "Status changed", name: "SC" },
  { description: "Send order/service number", name: "SN" },
  { description: "Response to send order/service status request", name: "SR" },
  { description: "Send order/service status request", name: "SS" },
  { description: "Unable to accept order/service", name: "UA" },
  { description: "Unable to cancel", name: "UC" },
  { description: "Unable to discontinue", name: "UD" },
  { description: "Unable to refill", name: "UF" },
  { description: "Unable to put on hold", name: "UH" },
  { description: "Unable to replace", name: "UM" },
  {
    description: "Unlink order/service from patient care problem or goal",
    name: "UN",
  },
  { description: "Unable to release", name: "UR" },
  { description: "Unable to change", name: "UX" },
  { description: "Change order/service request", name: "XO" },
  { description: "Changed as requested", name: "XR" },
  { description: "Order/service changed, unsol.", name: "XX" },
] as const;
