// Generated table profile for 0292 (v2.5)

export const id = "0292";
export const description = "Vaccines administered";
export const type = "hl7";
export const codes = [
  { description: "DTP", name: "01" },
  { description: "OPV", name: "02" },
  { description: "MMR", name: "03" },
  { description: "M/R", name: "04" },
  { description: "measles", name: "05" },
  { description: "rubella", name: "06" },
  { description: "mumps", name: "07" },
  { description: "Hep B, adolescent or pediatric", name: "08" },
  { description: "Td (adult)", name: "09" },
  { description: "IPV", name: "10" },
  { description: "pneumococcal conjugate", name: "100" },
  { description: "typhoid, ViCPs", name: "101" },
  { description: "DTP-Hib-Hep B", name: "102" },
  { description: "meningococcal C conjugate", name: "103" },
  { description: "Hep A-Hep B", name: "104" },
  { description: "smallpox, diluted", name: "105" },
  { description: "DTaP, 5 pertussis antigens", name: "106" },
  { description: "DTaP, NOS", name: "107" },
  { description: "meningococcal, NOS", name: "108" },
  { description: "pneumococcal, NOS", name: "109" },
  { description: "pertussis", name: "11" },
  { description: "diphtheria antitoxin", name: "12" },
  { description: "TIG", name: "13" },
  { description: "IG, NOS", name: "14" },
  {
    description: "influenza, split (incl. purified surface antigen)",
    name: "15",
  },
  { description: "influenza, whole", name: "16" },
  { description: "Hib, NOS", name: "17" },
  { description: "rabies, intramuscular injection", name: "18" },
  { description: "BCG", name: "19" },
  { description: "DTaP", name: "20" },
  { description: "Varicella", name: "21" },
  { description: "DTP-Hib", name: "22" },
  { description: "plague", name: "23" },
  { description: "anthrax", name: "24" },
  { description: "typhoid, oral", name: "25" },
  { description: "cholera", name: "26" },
  { description: "botulinum antitoxin", name: "27" },
  { description: "DT (pediatric)", name: "28" },
  { description: "CMVIG", name: "29" },
  { description: "HBIG", name: "30" },
  { description: "Hep A, pediatric, NOS", name: "31" },
  { description: "meningococcal", name: "32" },
  { description: "pneumococcal", name: "33" },
  { description: "RIG", name: "34" },
  { description: "tetanus toxoid", name: "35" },
  { description: "VZIG", name: "36" },
  { description: "yellow fever", name: "37" },
  { description: "rubella/mumps", name: "38" },
  { description: "Japanese encephalitis", name: "39" },
  { description: "rabies, intradermal injection", name: "40" },
  { description: "typhoid, parenteral", name: "41" },
  { description: "Hep B, adolescent/high risk infant2", name: "42" },
  { description: "Hep B, adult4", name: "43" },
  { description: "Hep B, dialysis", name: "44" },
  { description: "Hep B, NOS", name: "45" },
  { description: "Hib (PRP-D)", name: "46" },
  { description: "Hib (HbOC)", name: "47" },
  { description: "Hib (PRP-T)", name: "48" },
  { description: "Hib (PRP-OMP)", name: "49" },
  { description: "DTaP-Hib ", name: "50" },
  { description: "Hib-Hep B", name: "51" },
  { description: "Hep A, adult", name: "52" },
  { description: "typhoid, parenteral, AKD (U.S. military)", name: "53" },
  { description: "adenovirus, type 4", name: "54" },
  { description: "adenovirus, type 7", name: "55" },
  { description: "dengue fever", name: "56" },
  { description: "hantavirus", name: "57" },
  { description: "Hep C", name: "58" },
  { description: "Hep E", name: "59" },
  { description: "herpes simplex 2", name: "60" },
  { description: "HIV", name: "61" },
  { description: "HPV", name: "62" },
  { description: "Junin virus", name: "63" },
  { description: "leishmaniasis", name: "64" },
  { description: "leprosy", name: "65" },
  { description: "Lyme disease", name: "66" },
  { description: "malaria", name: "67" },
  { description: "melanoma", name: "68" },
  { description: "parainfluenza-3", name: "69" },
  { description: "Q fever", name: "70" },
  { description: "RSV-IGIV ", name: "71" },
  { description: "rheumatic fever", name: "72" },
  { description: "Rift Valley fever", name: "73" },
  { description: "rotavirus", name: "74" },
  { description: "smallpox", name: "75" },
  { description: "Staphylococcus bacterio lysate", name: "76" },
  { description: "tick-borne encephalitis", name: "77" },
  { description: "tularemia vaccine", name: "78" },
  { description: "vaccinia immune globulin", name: "79" },
  { description: "VEE, live", name: "80" },
  { description: "VEE, inactivated", name: "81" },
  { description: "adenovirus, NOS1", name: "82" },
  { description: "Hep A, ped/adol, 2 dose", name: "83" },
  { description: "Hep A, ped/adol, 3 dose", name: "84" },
  { description: "Hep A, NOS", name: "85" },
  { description: "IG", name: "86" },
  { description: "IGIV", name: "87" },
  { description: "influenza, NOS", name: "88" },
  { description: "polio, NOS", name: "89" },
  { description: "rabies, NOS", name: "90" },
  { description: "typhoid, NOS", name: "91" },
  { description: "VEE, NOS", name: "92" },
  { description: "RSV-MAb", name: "93" },
  { description: "MMRV", name: "94" },
  { description: "TST-OT tine test", name: "95" },
  { description: "TST-PPD intradermal", name: "96" },
  { description: "TST-PPD tine test", name: "97" },
  { description: "TST, NOS", name: "98" },
  { description: "RESERVED - do not use", name: "99" },
  { description: "no vaccine administered", name: "998" },
  { description: "Unknown", name: "999" },
] as const;
