// Generated segment profile for ECD (v2.8)

export const segmentId = "ECD";
export const fields = [
  {
    sequence: 1,
    id: "ECD-1",
    required: true,
    repeatable: false,
    datatype: "NM",
    name: "Reference Command Number",
    item: "1390",
  },
  {
    sequence: 2,
    id: "ECD-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70368",
    name: "Remote Control Command",
    item: "1391",
  },
  {
    sequence: 3,
    id: "ECD-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Response Required",
    item: "1392",
  },
  {
    sequence: 4,
    id: "ECD-4",
    deprecated: true,
    required: false,
    repeatable: false,
    datatype: "TQ",
    table: "HL70000",
    name: "Requested Completion Time",
    item: "1393",
  },
  {
    sequence: 5,
    id: "ECD-5",
    required: false,
    repeatable: true,
    datatype: "TX",
    name: "Parameters",
    item: "1394",
  },
] as const;
