// Generated segment profile for QAK (v2.8)

export const segmentId = "QAK";
export const fields = [
  {
    sequence: 1,
    id: "QAK-1",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Query Tag",
    item: "696",
  },
  {
    sequence: 2,
    id: "QAK-2",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70208",
    name: "Query Response Status",
    item: "708",
  },
  {
    sequence: 3,
    id: "QAK-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70471",
    name: "Message Query Name",
    item: "1375",
  },
  {
    sequence: 4,
    id: "QAK-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Hit Count Total",
    item: "1434",
  },
  {
    sequence: 5,
    id: "QAK-5",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "This payload",
    item: "1622",
  },
  {
    sequence: 6,
    id: "QAK-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Hits remaining",
    item: "1623",
  },
] as const;
