// Generated segment profile for REL (v2.8)

export const segmentId = "REL";
export const fields = [
  {
    sequence: 1,
    id: "REL-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID -REL",
    item: "2240",
  },
  {
    sequence: 2,
    id: "REL-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    name: "Relationship Type",
    item: "2241",
  },
  {
    sequence: 3,
    id: "REL-3",
    required: true,
    repeatable: false,
    datatype: "EI",
    name: "This Relationship Instance Identifier",
    item: "2242",
  },
  {
    sequence: 4,
    id: "REL-4",
    required: true,
    repeatable: false,
    datatype: "EI",
    name: "Source Information Instance Identifier",
    item: "2243",
  },
  {
    sequence: 5,
    id: "REL-5",
    required: true,
    repeatable: false,
    datatype: "EI",
    name: "Target Information Instance Identifier",
    item: "2244",
  },
  {
    sequence: 6,
    id: "REL-6",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Asserting Entity Instance ID",
    item: "2245",
  },
  {
    sequence: 7,
    id: "REL-7",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Asserting Person",
    item: "2246",
  },
  {
    sequence: 8,
    id: "REL-8",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "Asserting Organization",
    item: "2247",
  },
  {
    sequence: 9,
    id: "REL-9",
    required: false,
    repeatable: false,
    datatype: "XAD",
    name: "Assertor Address",
    item: "2248",
  },
  {
    sequence: 10,
    id: "REL-10",
    required: false,
    repeatable: false,
    datatype: "XTN",
    name: "Assertor Contact",
    item: "2249",
  },
  {
    sequence: 11,
    id: "REL-11",
    required: false,
    repeatable: false,
    datatype: "DR",
    name: "Assertion Date Range",
    item: "2250",
  },
  {
    sequence: 12,
    id: "REL-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Negation Indicator",
    item: "2251",
  },
  {
    sequence: 13,
    id: "REL-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Certainty of Relationship",
    item: "2252",
  },
  {
    sequence: 14,
    id: "REL-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Priority No",
    item: "2253",
  },
  {
    sequence: 15,
    id: "REL-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Priority  Sequence No (rel preference for consideration)",
    item: "2254",
  },
  {
    sequence: 16,
    id: "REL-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Separability Indicator",
    item: "2255",
  },
] as const;
