// Generated table profile for 0163 (v2.7)

export const id = "0163";
export const description = "Body Site";
export const type = "hl7";
export const codes = [
  { description: "Bilateral Ears", name: "BE" },
  { description: "Bilateral Nares", name: "BN" },
  { description: "Buttock", name: "BU" },
  { description: "Chest Tube", name: "CT" },
  { description: "Left Arm", name: "LA" },
  { description: "Left Anterior Chest", name: "LAC" },
  { description: "Left Antecubital Fossa", name: "LACF" },
  { description: "Left Deltoid", name: "LD" },
  { description: "Left Ear", name: "LE" },
  { description: "Left External Jugular", name: "LEJ" },
  { description: "Left Foot", name: "LF" },
  { description: "Left Gluteus Medius", name: "LG" },
  { description: "Left Hand", name: "LH" },
  { description: "Left Internal Jugular", name: "LIJ" },
  { description: "Left Lower Abd Quadrant", name: "LLAQ" },
  { description: "Left Lower Forearm", name: "LLFA" },
  { description: "Left Mid Forearm", name: "LMFA" },
  { description: "Left Naris", name: "LN" },
  { description: "Left Posterior Chest", name: "LPC" },
  { description: "Left Subclavian", name: "LSC" },
  { description: "Left Thigh", name: "LT" },
  { description: "Left Upper Arm", name: "LUA" },
  { description: "Left Upper Abd Quadrant", name: "LUAQ" },
  { description: "Left Upper Forearm", name: "LUFA" },
  { description: "Left Ventragluteal", name: "LVG" },
  { description: "Left Vastus Lateralis", name: "LVL" },
  { description: "Nebulized", name: "NB" },
  { description: "Right Eye", name: "OD" },
  { description: "Left Eye", name: "OS" },
  { description: "Bilateral Eyes", name: "OU" },
  { description: "Perianal", name: "PA" },
  { description: "Perineal", name: "PERIN" },
  { description: "Right Arm", name: "RA" },
  { description: "Right Anterior Chest", name: "RAC" },
  { description: "Right Antecubital Fossa", name: "RACF" },
  { description: "Right Deltoid", name: "RD" },
  { description: "Right Ear", name: "RE" },
  { description: "Right External Jugular", name: "REJ" },
  { description: "Right Foot", name: "RF" },
  { description: "Right Gluteus Medius", name: "RG" },
  { description: "Right Hand", name: "RH" },
  { description: "Right Internal Jugular", name: "RIJ" },
  { description: "Rt Lower Abd Quadrant", name: "RLAQ" },
  { description: "Right Lower Forearm", name: "RLFA" },
  { description: "Right Mid Forearm", name: "RMFA" },
  { description: "Right Naris", name: "RN" },
  { description: "Right Posterior Chest", name: "RPC" },
  { description: "Right Subclavian", name: "RSC" },
  { description: "Right Thigh", name: "RT" },
  { description: "Right Upper Arm", name: "RUA" },
  { description: "Right Upper Abd Quadrant", name: "RUAQ" },
  { description: "Right Upper Forearm", name: "RUFA" },
  { description: "Right Ventragluteal", name: "RVG" },
  { description: "Right Vastus Lateralis", name: "RVL" },
] as const;
