// Generated table profile for 0227 (v2.7)

export const id = "0227";
export const description = "Manufacturers of Vaccines (code=MVX)";
export const type = "user";
export const codes = [
  { description: "Abbott Laboratories", name: "AB" },
  { description: "Adams Laboratories, Inc.", name: "AD" },
  { description: "Alpha Therapeutic Corporation", name: "ALP" },
  { description: "Armour", name: "AR" },
  { description: "Aventis Behring L.L.C.", name: "AVB" },
  { description: "Aviron", name: "AVI" },
  { description: "Baxter Healthcare Corporation", name: "BA" },
  { description: "Baxter Healthcare Corporation", name: "BAH" },
  { description: "Bayer Corporation", name: "BAY" },
  { description: "Berna Products", name: "BP" },
  { description: "Berna Products Corporation", name: "BPC" },
  { description: "Centeon L.L.C.", name: "CEN" },
  { description: "Chiron Corporation", name: "CHI" },
  { description: "Celltech Medeva Pharmaceuticals", name: "CMP" },
  { description: "Cangene Corporation", name: "CNJ" },
  { description: "Connaught", name: "CON" },
  { description: "DynPort Vaccine Company, LLC", name: "DVC" },
  { description: "Evans Medical Limited", name: "EVN" },
  { description: "GeoVax Labs, Inc.", name: "GEO" },
  { description: "Greer Laboratories, Inc.", name: "GRE" },
  { description: "Immuno International AG", name: "IAG" },
  { description: "Merieux", name: "IM" },
  { description: "Immuno-U.S., Inc.", name: "IUS" },
  {
    description:
      "The Research Foundation for Microbial Diseases of Osaka University",
    name: "JPN",
  },
  { description: "Korea Green Cross Corporation", name: "KGC" },
  { description: "Lederle", name: "LED" },
  {
    description: "Massachusetts Public Health Biologic Laboratories",
    name: "MA",
  },
  { description: "Massachusetts Biologic Laboratories", name: "MBL" },
  { description: "MedImmune, Inc.", name: "MED" },
  { description: "Miles", name: "MIL" },
  { description: "Bioport Corporation", name: "MIP" },
  { description: "Merck & Co., Inc.", name: "MSD" },
  { description: "NABI", name: "NAB" },
  { description: "North American Vaccine, Inc.", name: "NAV" },
  { description: "Novartis Pharmaceutical Corporation", name: "NOV" },
  { description: "Novavax, Inc.", name: "NVX" },
  { description: "New York Blood Center", name: "NYB" },
  { description: "Ortho-Clinical Diagnostics", name: "ORT" },
  { description: "Organon Teknika Corporation", name: "OTC" },
  { description: "Other manufacturer", name: "OTH" },
  { description: "Parkedale Pharmaceuticals", name: "PD" },
  { description: "sanofi pasteur", name: "PMC" },
  { description: "Praxis Biologics", name: "PRX" },
  { description: "PowderJect Pharmaceuticals", name: "PWJ" },
  { description: "Sclavo, Inc.", name: "SCL" },
  { description: "Swiss Serum and Vaccine Inst.", name: "SI" },
  { description: "GlaxoSmithKline", name: "SKB" },
  { description: "Solvay Pharmaceuticals", name: "SOL" },
  { description: "Talecris Biotherapeutics", name: "TAL" },
  { description: "Unknown manufacturer", name: "UNK" },
  {
    description: "United States Army Medical Research and Material Command",
    name: "USA",
  },
  { description: "VaxGen", name: "VXG" },
  { description: "Wyeth-Ayerst", name: "WA" },
  { description: "Wyeth-Ayerst", name: "WAL" },
  { description: "ZLB Behring", name: "ZLB" },
] as const;
