// Generated segment definitions for v2.3.1
export const segments = [
  { id: "ACC", title: "Accident" },
  { id: "ADD", title: "Addendum" },
  { id: "AIG", title: "Appointment Information - General Resource" },
  { id: "AIL", title: "Appointment Information - Location Resource" },
  { id: "AIP", title: "Appointment Information - Personnel Resource" },
  { id: "AIS", title: "Appointment Information - Service" },
  { id: "AL1", title: "Patient Allergy Information" },
  { id: "APR", title: "Appointment Preferences" },
  { id: "ARQ", title: "Appointment Request" },
  { id: "AUT", title: "Authorization Information" },
  { id: "BHS", title: "Batch Header" },
  { id: "BLG", title: "Billing" },
  { id: "BTS", title: "Batch Trailer" },
  { id: "CDM", title: "Charge Description Master" },
  { id: "CM0", title: "Clinical Study Master" },
  { id: "CM1", title: "Clinical Study Phase Master" },
  { id: "CM2", title: "Clinical Study Schedule Master" },
  { id: "CSP", title: "Clinical Study Phase" },
  { id: "CSR", title: "Clinical Study Registration" },
  { id: "CSS", title: "Clinical Study Data Schedule Segment" },
  { id: "CTD", title: "Contact Data" },
  { id: "CTI", title: "Clinical Trial Identification" },
  { id: "DB1", title: "Disability" },
  { id: "DG1", title: "Diagnosis" },
  { id: "DRG", title: "Diagnosis Related Group" },
  { id: "DSC", title: "Continuation Pointer" },
  { id: "DSP", title: "Display Data" },
  { id: "EQL", title: "EQL" },
  { id: "ERQ", title: "ERQ" },
  { id: "ERR", title: "Error" },
  { id: "EVN", title: "Event Type" },
  { id: "FAC", title: "Facility" },
  { id: "FHS", title: "File Header" },
  { id: "FT1", title: "Financial Transaction" },
  { id: "FTS", title: "File Trailer" },
  { id: "GOL", title: "Goal Detail" },
  { id: "GT1", title: "Guarantor" },
  { id: "IN1", title: "Insurance" },
  { id: "IN2", title: "Insurance Additional Information" },
  { id: "IN3", title: "Insurance Additional Information, Certification" },
  { id: "LCC", title: "Location Charge Code" },
  { id: "LCH", title: "Location Characteristic" },
  { id: "LDP", title: "Location Department" },
  { id: "LOC", title: "Location Identification" },
  { id: "LRL", title: "Location Relationship" },
  { id: "MFA", title: "Master File Acknowledgment" },
  { id: "MFE", title: "Master File Entry" },
  { id: "MFI", title: "Master File Identification" },
  { id: "MRG", title: "Merge Patient Information" },
  { id: "MSA", title: "Message Acknowledgment" },
  { id: "MSH", title: "Message Header" },
  { id: "NCK", title: "System Clock" },
  { id: "NK1", title: "Next of Kin / Associated Parties" },
  { id: "NPU", title: "Bed Status Update" },
  { id: "NSC", title: "Application Status Change" },
  { id: "NST", title: "Application Control Level Statistics" },
  { id: "NTE", title: "Notes and Comments" },
  { id: "OBR", title: "Observation Request" },
  { id: "OBX", title: "Observation/Result" },
  { id: "ODS", title: "Dietary Orders, Supplements, and Preferences" },
  { id: "ODT", title: "Diet Tray Instructions" },
  { id: "OM1", title: "General Segment" },
  { id: "OM2", title: "Numeric Observation" },
  { id: "OM3", title: "Categorical Service/Test/Observation" },
  { id: "OM4", title: "Observations That Require Specimens" },
  { id: "OM5", title: "Observation Batteries (Sets)" },
  {
    id: "OM6",
    title: "Observations That Are Calculated from Other Observations",
  },
  { id: "ORC", title: "Common Order" },
  { id: "PCR", title: "Possible Causal Relationship" },
  { id: "PD1", title: "Patient Additional Demographic" },
  { id: "PDC", title: "Product Detail Country" },
  { id: "PEO", title: "Product Experience Observation" },
  { id: "PES", title: "Product Experience Sender" },
  { id: "PID", title: "Patient Identification" },
  { id: "PR1", title: "Procedures" },
  { id: "PRA", title: "Practitioner Detail" },
  { id: "PRB", title: "Problem Details" },
  { id: "PRC", title: "Pricing" },
  { id: "PRD", title: "Provider Data" },
  { id: "PSH", title: "Product Summary Header" },
  { id: "PTH", title: "Pathway" },
  { id: "PV1", title: "Patient Visit" },
  { id: "PV2", title: "Patient Visit - Additional Information" },
  { id: "QAK", title: "Query Acknowledgment" },
  { id: "QRD", title: "QRD" },
  { id: "QRF", title: "QRF" },
  { id: "RDF", title: "Table Row Definition" },
  { id: "RDT", title: "Table Row Data" },
  { id: "RF1", title: "Referral Information" },
  { id: "RGS", title: "Resource Group" },
  { id: "ROL", title: "Role" },
  { id: "RQ1", title: "Requisition Detail-1" },
  { id: "RQD", title: "Requisition Detail" },
  { id: "RXA", title: "Pharmacy/Treatment Administration" },
  { id: "RXC", title: "Pharmacy/Treatment Component Order" },
  { id: "RXD", title: "Pharmacy/Treatment Dispense" },
  { id: "RXE", title: "Pharmacy/Treatment Encoded Order" },
  { id: "RXG", title: "Pharmacy/Treatment Give" },
  { id: "RXO", title: "Pharmacy/Treatment Order" },
  { id: "RXR", title: "Pharmacy/Treatment Route" },
  { id: "SCH", title: "Scheduling Activity Information" },
  { id: "SPR", title: "SPR" },
  { id: "STF", title: "Staff Identification" },
  { id: "TXA", title: "Transcription Document Header" },
  { id: "UB1", title: "UB82" },
  { id: "UB2", title: "Uniform Billing Data" },
  { id: "URD", title: "Results/Update Definition" },
  { id: "URS", title: "Unsolicited Selection" },
  { id: "VAR", title: "Variance" },
  { id: "VTQ", title: "VTQ" },
] as const;
