// Generated segment profile for AIS (v2.8.2)

export const segmentId = "AIS";
export const fields = [
  {
    datatype: "SI",
    id: "AIS-1",
    item: "890",
    maxLength: 4,
    name: "Set ID - AIS",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "AIS-2",
    item: "763",
    name: "Segment Action Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "CWE",
    id: "AIS-3",
    item: "238",
    name: "Universal Service Identifier",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "DTM",
    id: "AIS-4",
    item: "1202",
    name: "Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "AIS-5",
    item: "891",
    name: "Start Date/Time Offset",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CNE",
    id: "AIS-6",
    item: "892",
    name: "Start Date/Time Offset Units",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "AIS-7",
    item: "893",
    name: "Duration",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CNE",
    id: "AIS-8",
    item: "894",
    name: "Duration Units",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "AIS-9",
    item: "895",
    name: "Allow Substitution Code",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70279",
  },
  {
    datatype: "CWE",
    id: "AIS-10",
    item: "889",
    name: "Filler Status Code",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70278",
  },
  {
    datatype: "CWE",
    id: "AIS-11",
    item: "1474",
    name: "Placer Supplemental Service Information",
    repeatable: true,
    required: false,
    sequence: 11,
    table: "HL70411",
  },
  {
    datatype: "CWE",
    id: "AIS-12",
    item: "1475",
    name: "Filler Supplemental Service Information",
    repeatable: true,
    required: false,
    sequence: 12,
    table: "HL70411",
  },
] as const;
