// Generated segment profile for AL1 (v2.8.2)

export const segmentId = "AL1";
export const fields = [
  {
    datatype: "SI",
    id: "AL1-1",
    item: "203",
    maxLength: 4,
    name: "Set ID - AL1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "AL1-2",
    item: "204",
    name: "Allergen Type Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70127",
  },
  {
    datatype: "CWE",
    id: "AL1-3",
    item: "205",
    name: "Allergen Code/Mnemonic/Description",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "AL1-4",
    item: "206",
    name: "Allergy Severity Code",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70128",
  },
  {
    datatype: "ST",
    id: "AL1-5",
    item: "207",
    name: "Allergy Reaction Code",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DT",
    deprecated: true,
    id: "AL1-6",
    item: "208",
    name: "Identification Date",
    repeatable: false,
    required: false,
    sequence: 6,
  },
] as const;
