// Generated segment profile for ARV (v2.8.2)

export const segmentId = "ARV";
export const fields = [
  {
    datatype: "SI",
    id: "ARV-1",
    item: "2143",
    maxLength: 4,
    name: "Set ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CNE",
    id: "ARV-2",
    item: "2144",
    name: "Access Restriction Action Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "CWE",
    id: "ARV-3",
    item: "2145",
    name: "Access Restriction Value",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70717",
  },
  {
    datatype: "CWE",
    id: "ARV-4",
    item: "2146",
    name: "Access Restriction Reason",
    repeatable: true,
    required: false,
    sequence: 4,
    table: "HL70719",
  },
  {
    datatype: "ST",
    id: "ARV-5",
    item: "2147",
    name: "Special Access Restriction Instructions",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DR",
    id: "ARV-6",
    item: "2148",
    name: "Access Restriction Date Range",
    repeatable: false,
    required: false,
    sequence: 6,
  },
] as const;
