// Generated segment profile for AUT (v2.8.2)

export const segmentId = "AUT";
export const fields = [
  {
    sequence: 1,
    id: "AUT-1",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70072",
    name: "Authorizing Payor, Plan ID",
    item: "1146",
  },
  {
    sequence: 2,
    id: "AUT-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70285",
    name: "Authorizing Payor, Company ID",
    item: "1147",
  },
  {
    sequence: 3,
    id: "AUT-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Authorizing Payor, Company Name",
    item: "1148",
  },
  {
    sequence: 4,
    id: "AUT-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Authorization Effective Date",
    item: "1149",
  },
  {
    sequence: 5,
    id: "AUT-5",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Authorization Expiration Date",
    item: "1150",
  },
  {
    sequence: 6,
    id: "AUT-6",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Authorization Identifier",
    item: "1151",
  },
  {
    sequence: 7,
    id: "AUT-7",
    required: false,
    repeatable: false,
    datatype: "CP",
    name: "Reimbursement Limit",
    item: "1152",
  },
  {
    sequence: 8,
    id: "AUT-8",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Requested Number of Treatments",
    item: "1153",
  },
  {
    sequence: 9,
    id: "AUT-9",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Authorized Number of Treatments",
    item: "1154",
  },
  {
    sequence: 10,
    id: "AUT-10",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Process Date",
    item: "1145",
  },
  {
    sequence: 11,
    id: "AUT-11",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Requested Discipline(s)",
    item: "2375",
  },
  {
    sequence: 12,
    id: "AUT-12",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Authorized Discipline(s)",
    item: "2376",
  },
  {
    sequence: 13,
    id: "AUT-13",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Authorization Referral Type",
    item: "3413",
  },
  {
    sequence: 14,
    id: "AUT-14",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Approval Status",
    item: "3414",
  },
  {
    sequence: 15,
    id: "AUT-15",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Planned Treatment Stop Date",
    item: "3415",
  },
  {
    sequence: 16,
    id: "AUT-16",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Clinical Service",
    item: "3416",
  },
  {
    sequence: 17,
    id: "AUT-17",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Reason Text",
    item: "3417",
  },
  {
    sequence: 18,
    id: "AUT-18",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 721,
    name: "Number of Authorized Treatments/Units",
    item: "3418",
  },
  {
    sequence: 19,
    id: "AUT-19",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 721,
    name: "Number of Used Treatments/Units",
    item: "3419",
  },
  {
    sequence: 20,
    id: "AUT-20",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 721,
    name: "Number of Schedule Treatments/Units",
    item: "3420",
  },
  {
    sequence: 21,
    id: "AUT-21",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Encounter Type",
    item: "3421",
  },
  {
    sequence: 22,
    id: "AUT-22",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 20,
    name: "Remaining Benefit Amount",
    item: "3422",
  },
  {
    sequence: 23,
    id: "AUT-23",
    required: false,
    repeatable: false,
    datatype: "XON",
    maxLength: 250,
    name: "Authorized Provider",
    item: "3423",
  },
  {
    sequence: 24,
    id: "AUT-24",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    name: "Authorized Health Professional",
    item: "3424",
  },
  {
    sequence: 25,
    id: "AUT-25",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Source Text",
    item: "3425",
  },
  {
    sequence: 26,
    id: "AUT-26",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Source Date",
    item: "3426",
  },
  {
    sequence: 27,
    id: "AUT-27",
    required: false,
    repeatable: false,
    datatype: "XTN",
    maxLength: 250,
    name: "Source Phone",
    item: "3427",
  },
  {
    sequence: 28,
    id: "AUT-28",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 254,
    name: "Comment",
    item: "3428",
  },
  {
    sequence: 29,
    id: "AUT-29",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70206",
    name: "Action Code",
    item: "3429",
  },
] as const;
