// Generated segment profile for DG1 (v2.8.2)

export const segmentId = "DG1";
export const fields = [
  {
    datatype: "SI",
    id: "DG1-1",
    item: "375",
    maxLength: 4,
    name: "Set ID - DG1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    deprecated: true,
    id: "DG1-2",
    item: "376",
    maxLength: 2,
    name: "Diagnosis Coding Method",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70053",
  },
  {
    datatype: "CWE",
    id: "DG1-3",
    item: "377",
    name: "Diagnosis Code - DG1",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70051",
  },
  {
    datatype: "ST",
    deprecated: true,
    id: "DG1-4",
    item: "378",
    maxLength: 40,
    name: "Diagnosis Description",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "DTM",
    id: "DG1-5",
    item: "379",
    name: "Diagnosis Date/Time",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "DG1-6",
    item: "380",
    name: "Diagnosis Type",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70052",
  },
  {
    datatype: "CE",
    deprecated: true,
    id: "DG1-7",
    item: "381",
    maxLength: 250,
    name: "Major Diagnostic Category",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70118",
  },
  {
    datatype: "CE",
    deprecated: true,
    id: "DG1-8",
    item: "382",
    maxLength: 250,
    name: "Diagnostic Related Group",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70055",
  },
  {
    datatype: "ID",
    deprecated: true,
    id: "DG1-9",
    item: "383",
    maxLength: 1,
    name: "DRG Approval Indicator",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70136",
  },
  {
    datatype: "IS",
    deprecated: true,
    id: "DG1-10",
    item: "384",
    maxLength: 2,
    name: "DRG Grouper Review Code",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70056",
  },
  {
    datatype: "CE",
    deprecated: true,
    id: "DG1-11",
    item: "385",
    maxLength: 250,
    name: "Outlier Type",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70083",
  },
  {
    datatype: "NM",
    deprecated: true,
    id: "DG1-12",
    item: "386",
    maxLength: 3,
    name: "Outlier Days",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CP",
    deprecated: true,
    id: "DG1-13",
    item: "387",
    maxLength: 12,
    name: "Outlier Cost",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    deprecated: true,
    id: "DG1-14",
    item: "388",
    maxLength: 4,
    name: "Grouper Version And Type",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "DG1-15",
    item: "389",
    name: "Diagnosis Priority",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70359",
  },
  {
    datatype: "XCN",
    id: "DG1-16",
    item: "390",
    name: "Diagnosing Clinician",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CWE",
    id: "DG1-17",
    item: "766",
    name: "Diagnosis Classification",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70228",
  },
  {
    datatype: "ID",
    id: "DG1-18",
    item: "767",
    maxLength: 1,
    name: "Confidential Indicator",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70136",
  },
  {
    datatype: "DTM",
    id: "DG1-19",
    item: "768",
    name: "Attestation Date/Time",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "EI",
    id: "DG1-20",
    item: "1850",
    name: "Diagnosis Identifier",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "ID",
    id: "DG1-21",
    item: "1894",
    maxLength: 1,
    name: "Diagnosis Action Code",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70206",
  },
  {
    datatype: "EI",
    id: "DG1-22",
    item: "2152",
    name: "Parent Diagnosis",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "CWE",
    id: "DG1-23",
    item: "2153",
    name: "DRG CCL Value Code",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70728",
  },
  {
    datatype: "ID",
    id: "DG1-24",
    item: "2154",
    maxLength: 1,
    name: "DRG Grouping Usage",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "DG1-25",
    item: "2155",
    name: "DRG Diagnosis Determination Status",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70731",
  },
  {
    datatype: "CWE",
    id: "DG1-26",
    item: "2288",
    name: "Present On Admission (POA) Indicator",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70895",
  },
] as const;
