// Generated segment profile for IAM (v2.8.2)

export const segmentId = "IAM";
export const fields = [
  {
    sequence: 1,
    id: "IAM-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - IAM",
    item: "1612",
  },
  {
    sequence: 2,
    id: "IAM-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70127",
    name: "Allergen Type Code",
    item: "204",
  },
  {
    sequence: 3,
    id: "IAM-3",
    required: true,
    repeatable: false,
    datatype: "CWE",
    name: "Allergen Code/Mnemonic/Description",
    item: "205",
  },
  {
    sequence: 4,
    id: "IAM-4",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70128",
    name: "Allergy Severity Code",
    item: "206",
  },
  {
    sequence: 5,
    id: "IAM-5",
    required: false,
    repeatable: true,
    datatype: "ST",
    name: "Allergy Reaction Code",
    item: "207",
  },
  {
    sequence: 6,
    id: "IAM-6",
    required: true,
    repeatable: false,
    datatype: "CNE",
    table: "HL70206",
    name: "Allergy Action Code",
    item: "1551",
  },
  {
    sequence: 7,
    id: "IAM-7",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Allergy Unique Identifier",
    item: "1552",
  },
  {
    sequence: 8,
    id: "IAM-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Action Reason",
    item: "1553",
  },
  {
    sequence: 9,
    id: "IAM-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70436",
    name: "Sensitivity to Causative Agent Code",
    item: "1554",
  },
  {
    sequence: 10,
    id: "IAM-10",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Allergen Group Code/Mnemonic/Description",
    item: "1555",
  },
  {
    sequence: 11,
    id: "IAM-11",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Onset Date",
    item: "1556",
  },
  {
    sequence: 12,
    id: "IAM-12",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Onset Date Text",
    item: "1557",
  },
  {
    sequence: 13,
    id: "IAM-13",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Reported Date/Time",
    item: "1558",
  },
  {
    sequence: 14,
    id: "IAM-14",
    required: false,
    repeatable: false,
    datatype: "XPN",
    name: "Reported By",
    item: "1559",
  },
  {
    sequence: 15,
    id: "IAM-15",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70063",
    name: "Relationship to Patient Code",
    item: "1560",
  },
  {
    sequence: 16,
    id: "IAM-16",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70437",
    name: "Alert Device Code",
    item: "1561",
  },
  {
    sequence: 17,
    id: "IAM-17",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70438",
    name: "Allergy Clinical Status Code",
    item: "1562",
  },
  {
    sequence: 18,
    id: "IAM-18",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Statused by Person",
    item: "1563",
  },
  {
    sequence: 19,
    id: "IAM-19",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "Statused by Organization",
    item: "1564",
  },
  {
    sequence: 20,
    id: "IAM-20",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Statused at Date/Time",
    item: "1565",
  },
  {
    sequence: 21,
    id: "IAM-21",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Inactivated by Person",
    item: "2294",
  },
  {
    sequence: 22,
    id: "IAM-22",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Inactivated Date/Time",
    item: "2295",
  },
  {
    sequence: 23,
    id: "IAM-23",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Initially Recorded by Person",
    item: "2296",
  },
  {
    sequence: 24,
    id: "IAM-24",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Initially Recorded Date/Time",
    item: "2297",
  },
  {
    sequence: 25,
    id: "IAM-25",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Modified by Person",
    item: "2298",
  },
  {
    sequence: 26,
    id: "IAM-26",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Modified Date/Time",
    item: "2299",
  },
  {
    sequence: 27,
    id: "IAM-27",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Clinician Identified Code",
    item: "2300",
  },
  {
    sequence: 28,
    id: "IAM-28",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "Initially Recorded by Organization",
    item: "3293",
  },
  {
    sequence: 29,
    id: "IAM-29",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "Modified by Organization",
    item: "3294",
  },
  {
    sequence: 30,
    id: "IAM-30",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "Inactivated by Organization",
    item: "3295",
  },
] as const;
