// Generated segment profile for IPC (v2.8.2)

export const segmentId = "IPC";
export const fields = [
  {
    datatype: "EI",
    id: "IPC-1",
    item: "1330",
    name: "Accession Identifier",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "IPC-2",
    item: "1658",
    name: "Requested Procedure ID",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "IPC-3",
    item: "1659",
    name: "Study Instance UID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "IPC-4",
    item: "1660",
    name: "Scheduled Procedure Step ID",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "IPC-5",
    item: "1661",
    name: "Modality",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "IPC-6",
    item: "1662",
    name: "Protocol Code",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "EI",
    id: "IPC-7",
    item: "1663",
    name: "Scheduled Station Name",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CWE",
    id: "IPC-8",
    item: "1664",
    name: "Scheduled Procedure Step Location",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "IPC-9",
    item: "1665",
    name: "Scheduled Station AE Title",
    repeatable: false,
    required: false,
    sequence: 9,
  },
] as const;
