// Generated segment profile for OMC (v2.8.2)

export const segmentId = "OMC";
export const fields = [
  {
    datatype: "NM",
    id: "OMC-1",
    item: "586",
    name: "Sequence Number - Test/Observation Master File",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "OMC-2",
    item: "763",
    name: "Segment Action Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "EI",
    id: "OMC-3",
    item: "764",
    name: "Segment Unique Key",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "OMC-4",
    item: "3444",
    name: "Clinical Information Request",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "OMC-5",
    item: "3445",
    name: "Collection Event/Process Step",
    repeatable: true,
    required: true,
    sequence: 5,
    table: "HL70938",
  },
  {
    datatype: "CWE",
    id: "OMC-6",
    item: "3446",
    name: "Communication Location",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70939",
  },
  {
    datatype: "ID",
    id: "OMC-7",
    item: "3447",
    name: "Answer Required",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70136",
  },
  {
    datatype: "ST",
    id: "OMC-8",
    item: "3448",
    name: "Hint/Help Text",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "varies",
    id: "OMC-9",
    item: "3449",
    name: "Type of Answer",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70125",
  },
  {
    datatype: "ID",
    id: "OMC-10",
    item: "3450",
    name: "Multiple Answers Allowed",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "OMC-11",
    item: "3451",
    name: "Answer Choices",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "NM",
    id: "OMC-12",
    item: "3452",
    name: "Character Limit",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "OMC-13",
    item: "3453",
    name: "Number of Decimals",
    repeatable: false,
    required: false,
    sequence: 13,
  },
] as const;
