// Generated segment profile for PES (v2.8.2)

export const segmentId = "PES";
export const fields = [
  {
    datatype: "XON",
    id: "PES-1",
    item: "1059",
    name: "Sender Organization Name",
    repeatable: true,
    required: false,
    sequence: 1,
  },
  {
    datatype: "XCN",
    id: "PES-2",
    item: "1060",
    name: "Sender Individual Name",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XAD",
    id: "PES-3",
    item: "1062",
    name: "Sender Address",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "XTN",
    id: "PES-4",
    item: "1063",
    name: "Sender Telephone",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "EI",
    id: "PES-5",
    item: "1064",
    name: "Sender Event Identifier",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "PES-6",
    item: "1065",
    name: "Sender Sequence Number",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "FT",
    id: "PES-7",
    item: "1066",
    name: "Sender Event Description",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "FT",
    id: "PES-8",
    item: "1067",
    name: "Sender Comment",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DTM",
    id: "PES-9",
    item: "1068",
    name: "Sender Aware Date/Time",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "DTM",
    id: "PES-10",
    item: "1069",
    name: "Event Report Date",
    repeatable: false,
    required: true,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "PES-11",
    item: "1070",
    maxLength: 3,
    name: "Event Report Timing/Type",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70234",
  },
  {
    datatype: "ID",
    id: "PES-12",
    item: "1071",
    maxLength: 1,
    name: "Event Report Source",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70235",
  },
  {
    datatype: "ID",
    id: "PES-13",
    item: "1072",
    maxLength: 1,
    name: "Event Reported To",
    repeatable: true,
    required: false,
    sequence: 13,
    table: "HL70236",
  },
] as const;
