// Generated segment profile for PRD (v2.8.2)

export const segmentId = "PRD";
export const fields = [
  {
    sequence: 1,
    id: "PRD-1",
    required: true,
    repeatable: true,
    datatype: "CWE",
    table: "HL70286",
    name: "Provider Role",
    item: "1155",
  },
  {
    sequence: 2,
    id: "PRD-2",
    required: false,
    repeatable: true,
    datatype: "XPN",
    name: "Provider Name",
    item: "1156",
  },
  {
    sequence: 3,
    id: "PRD-3",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Provider Address",
    item: "1157",
  },
  {
    sequence: 4,
    id: "PRD-4",
    required: false,
    repeatable: false,
    datatype: "PL",
    name: "Provider Location",
    item: "1158",
  },
  {
    sequence: 5,
    id: "PRD-5",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Provider Communication Information",
    item: "1159",
  },
  {
    sequence: 6,
    id: "PRD-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70185",
    name: "Preferred Method of Contact",
    item: "684",
  },
  {
    sequence: 7,
    id: "PRD-7",
    required: false,
    repeatable: true,
    datatype: "PLN",
    name: "Provider Identifiers",
    item: "1162",
  },
  {
    sequence: 8,
    id: "PRD-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Effective Start Date of Provider Role",
    item: "1163",
  },
  {
    sequence: 9,
    id: "PRD-9",
    required: false,
    repeatable: true,
    datatype: "DTM",
    name: "Effective End Date of Provider Role",
    item: "1164",
  },
  {
    sequence: 10,
    id: "PRD-10",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "Provider Organization Name and Identifier",
    item: "2256",
  },
  {
    sequence: 11,
    id: "PRD-11",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Provider Organization Address",
    item: "2257",
  },
  {
    sequence: 12,
    id: "PRD-12",
    required: false,
    repeatable: true,
    datatype: "PL",
    name: "Provider Organization Location Information",
    item: "2258",
  },
  {
    sequence: 13,
    id: "PRD-13",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Provider Organization Communication Information",
    item: "2259",
  },
  {
    sequence: 14,
    id: "PRD-14",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70185",
    name: "Provider Organization Method of Contact",
    item: "2260",
  },
] as const;
