// Generated segment profile for SAC (v2.8.2)

export const segmentId = "SAC";
export const fields = [
  {
    datatype: "EI",
    id: "SAC-1",
    item: "1329",
    name: "External Accession Identifier",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "SAC-2",
    item: "1330",
    name: "Accession Identifier",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "SAC-3",
    item: "1331",
    name: "Container Identifier",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "SAC-4",
    item: "1332",
    name: "Primary (Parent) Container Identifier",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "EI",
    id: "SAC-5",
    item: "1333",
    name: "Equipment Container Identifier",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "SPS",
    deprecated: true,
    id: "SAC-6",
    item: "249",
    name: "Specimen Source",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "SAC-7",
    item: "1334",
    name: "Registration Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CWE",
    id: "SAC-8",
    item: "1335",
    name: "Container Status",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70370",
  },
  {
    datatype: "CWE",
    id: "SAC-9",
    item: "1336",
    name: "Carrier Type",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70378",
  },
  {
    datatype: "EI",
    id: "SAC-10",
    item: "1337",
    name: "Carrier Identifier",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NA",
    id: "SAC-11",
    item: "1338",
    name: "Position in Carrier",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "SAC-12",
    item: "1339",
    name: "Tray Type - SAC",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70379",
  },
  {
    datatype: "EI",
    id: "SAC-13",
    item: "1340",
    name: "Tray Identifier",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NA",
    id: "SAC-14",
    item: "1341",
    name: "Position in Tray",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "SAC-15",
    item: "1342",
    name: "Location",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "NM",
    id: "SAC-16",
    item: "1343",
    name: "Container Height",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "NM",
    id: "SAC-17",
    item: "1344",
    name: "Container Diameter",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "NM",
    id: "SAC-18",
    item: "1345",
    name: "Barrier Delta",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "NM",
    id: "SAC-19",
    item: "1346",
    name: "Bottom Delta",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CWE",
    id: "SAC-20",
    item: "1347",
    name: "Container Height/Diameter/Delta Units",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "NM",
    id: "SAC-21",
    item: "644",
    name: "Container Volume",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "NM",
    id: "SAC-22",
    item: "1349",
    name: "Available Specimen Volume",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "NM",
    id: "SAC-23",
    item: "1350",
    name: "Initial Specimen Volume",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "CWE",
    id: "SAC-24",
    item: "1351",
    name: "Volume Units",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "CWE",
    id: "SAC-25",
    item: "1352",
    name: "Separator Type",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70380",
  },
  {
    datatype: "CWE",
    id: "SAC-26",
    item: "1353",
    name: "Cap Type",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70381",
  },
  {
    datatype: "CWE",
    id: "SAC-27",
    item: "647",
    name: "Additive",
    repeatable: true,
    required: false,
    sequence: 27,
    table: "HL70371",
  },
  {
    datatype: "CWE",
    id: "SAC-28",
    item: "1355",
    name: "Specimen Component",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70372",
  },
  {
    datatype: "SN",
    id: "SAC-29",
    item: "1356",
    name: "Dilution Factor",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CWE",
    id: "SAC-30",
    item: "1357",
    name: "Treatment",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70373",
  },
  {
    datatype: "SN",
    id: "SAC-31",
    item: "1358",
    name: "Temperature",
    repeatable: false,
    required: false,
    sequence: 31,
  },
  {
    datatype: "NM",
    id: "SAC-32",
    item: "1359",
    name: "Hemolysis Index",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "CWE",
    id: "SAC-33",
    item: "1360",
    name: "Hemolysis Index Units",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "NM",
    id: "SAC-34",
    item: "1361",
    name: "Lipemia Index",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "CWE",
    id: "SAC-35",
    item: "1362",
    name: "Lipemia Index Units",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "NM",
    id: "SAC-36",
    item: "1363",
    name: "Icterus Index",
    repeatable: false,
    required: false,
    sequence: 36,
  },
  {
    datatype: "CWE",
    id: "SAC-37",
    item: "1364",
    name: "Icterus Index Units",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "NM",
    id: "SAC-38",
    item: "1365",
    name: "Fibrin Index",
    repeatable: false,
    required: false,
    sequence: 38,
  },
  {
    datatype: "CWE",
    id: "SAC-39",
    item: "1366",
    name: "Fibrin Index Units",
    repeatable: false,
    required: false,
    sequence: 39,
  },
  {
    datatype: "CWE",
    id: "SAC-40",
    item: "1367",
    name: "System Induced Contaminants",
    repeatable: true,
    required: false,
    sequence: 40,
    table: "HL70374",
  },
  {
    datatype: "CWE",
    id: "SAC-41",
    item: "1368",
    name: "Drug Interference",
    repeatable: true,
    required: false,
    sequence: 41,
    table: "HL70382",
  },
  {
    datatype: "CWE",
    id: "SAC-42",
    item: "1369",
    name: "Artificial Blood",
    repeatable: false,
    required: false,
    sequence: 42,
    table: "HL70375",
  },
  {
    datatype: "CWE",
    id: "SAC-43",
    item: "1370",
    name: "Special Handling Code",
    repeatable: true,
    required: false,
    sequence: 43,
    table: "HL70376",
  },
  {
    datatype: "CWE",
    id: "SAC-44",
    item: "1371",
    name: "Other Environmental Factors",
    repeatable: true,
    required: false,
    sequence: 44,
    table: "HL70377",
  },
] as const;
