// Generated segment profile for TQ1 (v2.8.2)

export const segmentId = "TQ1";
export const fields = [
  {
    datatype: "SI",
    id: "TQ1-1",
    item: "1627",
    maxLength: 4,
    name: "Set ID - TQ1",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CQ",
    id: "TQ1-2",
    item: "1628",
    name: "Quantity",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "RPT",
    id: "TQ1-3",
    item: "1629",
    name: "Repeat Pattern",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "TM",
    id: "TQ1-4",
    item: "1630",
    name: "Explicit Time",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CQ",
    id: "TQ1-5",
    item: "1631",
    name: "Relative Time and Units",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CQ",
    id: "TQ1-6",
    item: "1632",
    name: "Service Duration",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "TQ1-7",
    item: "1633",
    name: "Start date/time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DTM",
    id: "TQ1-8",
    item: "1634",
    name: "End date/time",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "TQ1-9",
    item: "1635",
    name: "Priority",
    repeatable: true,
    required: false,
    sequence: 9,
    table: "HL70485",
  },
  {
    datatype: "TX",
    id: "TQ1-10",
    item: "1636",
    name: "Condition text",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "TX",
    id: "TQ1-11",
    item: "1637",
    name: "Text instruction",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "TQ1-12",
    item: "1638",
    maxLength: 1,
    name: "Conjunction",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70472",
  },
  {
    datatype: "CQ",
    id: "TQ1-13",
    item: "1639",
    name: "Occurrence duration",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NM",
    id: "TQ1-14",
    item: "1640",
    name: "Total occurrences",
    repeatable: false,
    required: false,
    sequence: 14,
  },
] as const;
