// Generated table profile for 0292 (v2.7.1)

export const id = "0292";
export const description = "Vaccines administered";
export const type = "user";
export const codes = [
  { name: "01", description: "DTP" },
  { name: "02", description: "OPV" },
  { name: "03", description: "MMR" },
  { name: "04", description: "M/R" },
  { name: "05", description: "measles" },
  { name: "06", description: "rubella" },
  { name: "07", description: "mumps" },
  { name: "08", description: "Hep B, adolescent or pediatric" },
  { name: "09", description: "Td (adult)" },
  { name: "10", description: "IPV" },
  { name: "100", description: "pneumococcal conjugate" },
  { name: "101", description: "typhoid, ViCPs" },
  { name: "102", description: "DTP-Hib-Hep B" },
  { name: "103", description: "meningococcal C conjugate" },
  { name: "104", description: "Hep A-Hep B" },
  { name: "105", description: "vaccinia (smallpox) diluted" },
  { name: "106", description: "DTaP, 5 pertussis antigens6" },
  { name: "107", description: "DTaP, NOS" },
  { name: "108", description: "meningococcal, NOS" },
  { name: "109", description: "pneumococcal, NOS" },
  { name: "11", description: "pertussis" },
  { name: "110", description: "DTaP-Hep B-IPV" },
  { name: "111", description: "influenza, live, intranasal" },
  { name: "112", description: "tetanus toxoid, NOS" },
  { name: "113", description: "Td (adult)" },
  {
    name: "114",
    description: "meningococcal A,C,Y,W-135 diphtheria conjugate",
  },
  { name: "115", description: "Tdap" },
  { name: "116", description: "rotavirus, pentavalent" },
  { name: "117", description: "VZIG (IND)" },
  { name: "118", description: "HPV, bivalent" },
  { name: "119", description: "rotavirus, monovalent" },
  { name: "12", description: "diphtheria antitoxin" },
  { name: "120", description: "DTaP-Hib-IPV" },
  { name: "121", description: "zoster" },
  { name: "122", description: "rotavirus, NOS1" },
  { name: "13", description: "TIG" },
  { name: "14", description: "IG, NOS" },
  {
    name: "15",
    description: "influenza, split (incl. purified surface antigen)",
  },
  { name: "16", description: "influenza, whole" },
  { name: "17", description: "Hib, NOS" },
  { name: "18", description: "rabies, intramuscular injection" },
  { name: "19", description: "BCG" },
  { name: "20", description: "DTaP" },
  { name: "21", description: "varicella" },
  { name: "22", description: "DTP-Hib" },
  { name: "23", description: "plague" },
  { name: "24", description: "anthrax" },
  { name: "25", description: "typhoid, oral" },
  { name: "26", description: "cholera" },
  { name: "27", description: "botulinum antitoxin" },
  { name: "28", description: "DT (pediatric)" },
  { name: "29", description: "CMVIG" },
  { name: "30", description: "HBIG" },
  { name: "31", description: "Hep A, pediatric, NOS" },
  { name: "32", description: "meningococcal" },
  { name: "33", description: "pneumococcal" },
  { name: "34", description: "RIG" },
  { name: "35", description: "tetanus toxoid" },
  { name: "36", description: "VZIG" },
  { name: "37", description: "yellow fever" },
  { name: "38", description: "rubella/mumps" },
  { name: "39", description: "Japanese encephalitis" },
  { name: "40", description: "rabies, intradermal injection" },
  { name: "41", description: "typhoid, parenteral" },
  { name: "42", description: "Hep B, adolescent/high risk infant2" },
  { name: "43", description: "Hep B, adult4" },
  { name: "44", description: "Hep B, dialysis" },
  { name: "45", description: "Hep B, NOS" },
  { name: "46", description: "Hib (PRP-D)" },
  { name: "47", description: "Hib (HbOC)" },
  { name: "48", description: "Hib (PRP-T)" },
  { name: "49", description: "Hib (PRP-OMP)" },
  { name: "50", description: "DTaP-Hib" },
  { name: "51", description: "Hib-Hep B" },
  { name: "52", description: "Hep A, adult" },
  { name: "53", description: "typhoid, parenteral, AKD (U.S. military)" },
  { name: "54", description: "adenovirus, type 4" },
  { name: "55", description: "adenovirus, type 7" },
  { name: "56", description: "dengue fever" },
  { name: "57", description: "hantavirus" },
  { name: "58", description: "Hep C" },
  { name: "59", description: "Hep E" },
  { name: "60", description: "herpes simplex 2" },
  { name: "61", description: "HIV" },
  { name: "62", description: "HPV, quadrivalent" },
  { name: "63", description: "Junin virus" },
  { name: "64", description: "leishmaniasis" },
  { name: "65", description: "leprosy" },
  { name: "66", description: "Lyme disease" },
  { name: "67", description: "malaria" },
  { name: "68", description: "melanoma" },
  { name: "69", description: "parainfluenza-3" },
  { name: "70", description: "Q fever" },
  { name: "71", description: "RSV-IGIV" },
  { name: "72", description: "rheumatic fever" },
  { name: "73", description: "Rift Valley fever" },
  { name: "74", description: "rotavirus, tetravalent" },
  { name: "75", description: "vaccinia (smallpox)" },
  { name: "76", description: "Staphylococcus bacterio lysate" },
  { name: "77", description: "tick-borne encephalitis" },
  { name: "78", description: "tularemia vaccine" },
  { name: "79", description: "vaccinia immune globulin" },
  { name: "80", description: "VEE, live" },
  { name: "81", description: "VEE, inactivated" },
  { name: "82", description: "adenovirus, NOS1" },
  { name: "83", description: "Hep A, ped/adol, 2 dose" },
  { name: "84", description: "Hep A, ped/adol, 3 dose" },
  { name: "85", description: "Hep A, NOS" },
  { name: "86", description: "IG" },
  { name: "87", description: "IGIV" },
  { name: "88", description: "influenza, NOS" },
  { name: "89", description: "polio, NOS" },
  { name: "90", description: "rabies, NOS" },
  { name: "91", description: "typhoid, NOS" },
  { name: "92", description: "VEE, NOS" },
  { name: "93", description: "RSV-MAb" },
  { name: "94", description: "MMRV" },
  { name: "95", description: "TST-OT tine test" },
  { name: "96", description: "TST-PPD intradermal" },
  { name: "97", description: "TST-PPD tine test" },
  { name: "98", description: "TST, NOS" },
  { name: "99", description: "RESERVED - do not use3" },
  { name: "998", description: "no vaccine administered5" },
  { name: "999", description: "unknown" },
] as const;
