// Generated segment profile for LOC (v2.5.1)

export const segmentId = "LOC";
export const fields = [
  {
    sequence: 1,
    id: "LOC-1",
    required: true,
    repeatable: false,
    datatype: "PL",
    maxLength: 200,
    name: "Primary Key Value - LOC",
    item: "1307",
  },
  {
    sequence: 2,
    id: "LOC-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 48,
    name: "Location Description",
    item: "944",
  },
  {
    sequence: 3,
    id: "LOC-3",
    required: true,
    repeatable: true,
    datatype: "IS",
    maxLength: 2,
    table: "HL70260",
    name: "Location Type - LOC",
    item: "945",
  },
  {
    sequence: 4,
    id: "LOC-4",
    required: false,
    repeatable: true,
    datatype: "XON",
    maxLength: 250,
    name: "Organization Name - LOC",
    item: "947",
  },
  {
    sequence: 5,
    id: "LOC-5",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 250,
    name: "Location Address",
    item: "948",
  },
  {
    sequence: 6,
    id: "LOC-6",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 250,
    name: "Location Phone",
    item: "949",
  },
  {
    sequence: 7,
    id: "LOC-7",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    table: "HL70461",
    name: "License Number",
    item: "951",
  },
  {
    sequence: 8,
    id: "LOC-8",
    required: false,
    repeatable: true,
    datatype: "IS",
    maxLength: 3,
    table: "HL70261",
    name: "Location Equipment",
    item: "953",
  },
  {
    sequence: 9,
    id: "LOC-9",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70442",
    name: "Location Service Code",
    item: "1583",
  },
] as const;
