// Generated segment profile for MSA (v2.5.1)

export const segmentId = "MSA";
export const fields = [
  {
    sequence: 1,
    id: "MSA-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70008",
    name: "Acknowledgment Code",
    item: "18",
  },
  {
    sequence: 2,
    id: "MSA-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Message Control ID",
    item: "10",
  },
  {
    sequence: 3,
    id: "MSA-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 80,
    name: "Text Message",
    item: "20",
  },
  {
    sequence: 4,
    id: "MSA-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 15,
    name: "Expected Sequence Number",
    item: "21",
  },
  {
    sequence: 5,
    id: "MSA-5",
    required: false,
    repeatable: false,
    datatype: "NUL",
    name: "Delayed Acknowledgment Type",
    item: "22",
  },
  {
    sequence: 6,
    id: "MSA-6",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70357",
    name: "Error Condition",
    item: "23",
  },
] as const;
