// Generated segment profile for RXG (v2.5.1)

export const segmentId = "RXG";
export const fields = [
  {
    sequence: 1,
    id: "RXG-1",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Give Sub-ID Counter",
    item: "342",
  },
  {
    sequence: 2,
    id: "RXG-2",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Dispense Sub-ID Counter",
    item: "334",
  },
  {
    sequence: 3,
    id: "RXG-3",
    required: false,
    repeatable: false,
    datatype: "TQ",
    maxLength: 200,
    name: "Quantity/Timing",
    item: "221",
  },
  {
    sequence: 4,
    id: "RXG-4",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70292",
    name: "Give Code",
    item: "317",
  },
  {
    sequence: 5,
    id: "RXG-5",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Give Amount - Minimum",
    item: "318",
  },
  {
    sequence: 6,
    id: "RXG-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Give Amount - Maximum",
    item: "319",
  },
  {
    sequence: 7,
    id: "RXG-7",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "Give Units",
    item: "320",
  },
  {
    sequence: 8,
    id: "RXG-8",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "Give Dosage Form",
    item: "321",
  },
  {
    sequence: 9,
    id: "RXG-9",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    name: "Administration Notes",
    item: "351",
  },
  {
    sequence: 10,
    id: "RXG-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70167",
    name: "Substitution Status",
    item: "322",
  },
  {
    sequence: 11,
    id: "RXG-11",
    required: false,
    repeatable: false,
    datatype: "LA2",
    maxLength: 200,
    name: "Dispense-to Location",
    item: "1303",
  },
  {
    sequence: 12,
    id: "RXG-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Needs Human Review",
    item: "307",
  },
  {
    sequence: 13,
    id: "RXG-13",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    name: "Pharmacy/Treatment Supplier&apos;s Special Administration Instructions",
    item: "343",
  },
  {
    sequence: 14,
    id: "RXG-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Give Per (Time Unit)",
    item: "331",
  },
  {
    sequence: 15,
    id: "RXG-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 6,
    name: "Give Rate Amount",
    item: "332",
  },
  {
    sequence: 16,
    id: "RXG-16",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "Give Rate Units",
    item: "333",
  },
  {
    sequence: 17,
    id: "RXG-17",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Give Strength",
    item: "1126",
  },
  {
    sequence: 18,
    id: "RXG-18",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "Give Strength Units",
    item: "1127",
  },
  {
    sequence: 19,
    id: "RXG-19",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 20,
    name: "Substance Lot Number",
    item: "1129",
  },
  {
    sequence: 20,
    id: "RXG-20",
    required: false,
    repeatable: true,
    datatype: "TS",
    maxLength: 26,
    name: "Substance Expiration Date",
    item: "1130",
  },
  {
    sequence: 21,
    id: "RXG-21",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    table: "HL70227",
    name: "Substance Manufacturer Name",
    item: "1131",
  },
  {
    sequence: 22,
    id: "RXG-22",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    name: "Indication",
    item: "1123",
  },
  {
    sequence: 23,
    id: "RXG-23",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "Give Drug Strength Volume",
    item: "1692",
  },
  {
    sequence: 24,
    id: "RXG-24",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Give Drug Strength Volume Units",
    item: "1693",
  },
  {
    sequence: 25,
    id: "RXG-25",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 60,
    name: "Give Barcode Identifier",
    item: "1694",
  },
  {
    sequence: 26,
    id: "RXG-26",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70480",
    name: "Pharmacy Order Type",
    item: "1695",
  },
] as const;
