// Generated segment profile for STF (v2.5.1)

export const segmentId = "STF";
export const fields = [
  {
    sequence: 1,
    id: "STF-1",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL79999",
    name: "Primary Key Value - STF",
    item: "671",
  },
  {
    sequence: 2,
    id: "STF-2",
    required: false,
    repeatable: true,
    datatype: "CX",
    maxLength: 250,
    name: "Staff Identifier List",
    item: "672",
  },
  {
    sequence: 3,
    id: "STF-3",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 250,
    name: "Staff Name",
    item: "673",
  },
  {
    sequence: 4,
    id: "STF-4",
    required: false,
    repeatable: true,
    datatype: "IS",
    maxLength: 2,
    table: "HL70182",
    name: "Staff Type",
    item: "674",
  },
  {
    sequence: 5,
    id: "STF-5",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70001",
    name: "Administrative Sex",
    item: "111",
  },
  {
    sequence: 6,
    id: "STF-6",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Date/Time of Birth",
    item: "110",
  },
  {
    sequence: 7,
    id: "STF-7",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70183",
    name: "Active/Inactive Flag",
    item: "675",
  },
  {
    sequence: 8,
    id: "STF-8",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    table: "HL70184",
    name: "Department",
    item: "676",
  },
  {
    sequence: 9,
    id: "STF-9",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    table: "HL70069",
    name: "Hospital Service - STF",
    item: "677",
  },
  {
    sequence: 10,
    id: "STF-10",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 250,
    name: "Phone",
    item: "678",
  },
  {
    sequence: 11,
    id: "STF-11",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 250,
    name: "Office/Home Address/Birthplace",
    item: "679",
  },
  {
    sequence: 12,
    id: "STF-12",
    required: false,
    repeatable: true,
    datatype: "DIN",
    maxLength: 276,
    table: "HL70537",
    name: "Institution Activation Date",
    item: "680",
  },
  {
    sequence: 13,
    id: "STF-13",
    required: false,
    repeatable: true,
    datatype: "DIN",
    maxLength: 276,
    table: "HL70537",
    name: "Institution Inactivation Date",
    item: "681",
  },
  {
    sequence: 14,
    id: "STF-14",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    name: "Backup Person ID",
    item: "682",
  },
  {
    sequence: 15,
    id: "STF-15",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 40,
    name: "E-Mail Address",
    item: "683",
  },
  {
    sequence: 16,
    id: "STF-16",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70185",
    name: "Preferred Method of Contact",
    item: "684",
  },
  {
    sequence: 17,
    id: "STF-17",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70002",
    name: "Marital Status",
    item: "119",
  },
  {
    sequence: 18,
    id: "STF-18",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Job Title",
    item: "785",
  },
  {
    sequence: 19,
    id: "STF-19",
    required: false,
    repeatable: false,
    datatype: "JCC",
    maxLength: 20,
    name: "Job Code/Class",
    item: "786",
  },
  {
    sequence: 20,
    id: "STF-20",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70066",
    name: "Employment Status Code",
    item: "1276",
  },
  {
    sequence: 21,
    id: "STF-21",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Additional Insured on Auto",
    item: "1275",
  },
  {
    sequence: 22,
    id: "STF-22",
    required: false,
    repeatable: false,
    datatype: "DLN",
    maxLength: 25,
    name: "Driver&apos;s License Number - Staff",
    item: "1302",
  },
  {
    sequence: 23,
    id: "STF-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Copy Auto Ins",
    item: "1229",
  },
  {
    sequence: 24,
    id: "STF-24",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Auto Ins. Expires",
    item: "1232",
  },
  {
    sequence: 25,
    id: "STF-25",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Date Last DMV Review",
    item: "1298",
  },
  {
    sequence: 26,
    id: "STF-26",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Date Next DMV Review",
    item: "1234",
  },
  {
    sequence: 27,
    id: "STF-27",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70005",
    name: "Race",
    item: "113",
  },
  {
    sequence: 28,
    id: "STF-28",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70189",
    name: "Ethnic Group",
    item: "125",
  },
  {
    sequence: 29,
    id: "STF-29",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Re-activation Approval Indicator",
    item: "1596",
  },
  {
    sequence: 30,
    id: "STF-30",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    table: "HL70171",
    name: "Citizenship",
    item: "129",
  },
  {
    sequence: 31,
    id: "STF-31",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 8,
    name: "Death Date and Time",
    item: "1886",
  },
  {
    sequence: 32,
    id: "STF-32",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Death Indicator",
    item: "1887",
  },
  {
    sequence: 33,
    id: "STF-33",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70538",
    name: "Institution Relationship Type Code",
    item: "1888",
  },
  {
    sequence: 34,
    id: "STF-34",
    required: false,
    repeatable: false,
    datatype: "DR",
    maxLength: 52,
    name: "Institution Relationship Period",
    item: "1889",
  },
  {
    sequence: 35,
    id: "STF-35",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Expected Return Date",
    item: "1890",
  },
  {
    sequence: 36,
    id: "STF-36",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70539",
    name: "Cost Center Code",
    item: "1891",
  },
  {
    sequence: 37,
    id: "STF-37",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Generic Classification Indicator",
    item: "1892",
  },
  {
    sequence: 38,
    id: "STF-38",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70540",
    name: "Inactive Reason Code",
    item: "1893",
  },
] as const;
