// Generated table profile for 0203 (v2.4)

export const id = "0203";
export const description = "Identifier type";
export const type = "user";
export const codes = [
  { description: "American Express", name: "AM" },
  { description: "Account number", name: "AN" },
  { description: "Bank Account Number", name: "BA" },
  { description: "Birth registry number", name: "BR" },
  { description: "Breed Registry Number", name: "BRN" },
  { description: "Diner's Club card", name: "DI" },
  { description: "Driver's license number", name: "DL" },
  { description: "Doctor number", name: "DN" },
  { description: "Donor Registration Number", name: "DR" },
  { description: "Discover Card", name: "DS" },
  { description: "Employee number", name: "EI" },
  { description: "Employer number", name: "EN" },
  { description: "Facility ID", name: "FI" },
  { description: "Guarantor internal identifier", name: "GI" },
  { description: "Guarantor external  identifier", name: "GN" },
  { description: "Health Card Number", name: "HC" },
  { description: "Jurisdictional health number (Canada)", name: "JHN" },
  { description: "License number", name: "LN" },
  { description: "Local Registry ID", name: "LR" },
  { description: "Medicaid number", name: "MA" },
  { description: "Medicare number", name: "MC" },
  { description: "Microchip Number", name: "MCN" },
  { description: "Medical record number", name: "MR" },
  { description: "MasterCard", name: "MS" },
  { description: "National employer identifier", name: "NE" },
  { description: "National Health Plan Identifier", name: "NH" },
  { description: "National unique individual identifier", name: "NI" },
  {
    description:
      "National Person Identifier where the xxx is the ISO table 3166  3-character (alphabetic) country code",
    name: "NNxxx",
  },
  { description: "National provider identifier", name: "NPI" },
  { description: "Pension Number", name: "PEN" },
  { description: "Patient internal identifier", name: "PI" },
  { description: "Person number", name: "PN" },
  { description: "Provider number", name: "PRN" },
  { description: "Patient external identifier", name: "PT" },
  { description: "Railroad Retirement number", name: "RR" },
  { description: "Regional registry ID", name: "RRI" },
  { description: "State license", name: "SL" },
  { description: "State registry ID", name: "SR" },
  { description: "Social Security number", name: "SS" },
  { description: "Unspecified", name: "U" },
  {
    description: "Medicare/HCFA's Universal Physician Identification numbers",
    name: "UPIN",
  },
  { description: "Visit number", name: "VN" },
  { description: "VISA", name: "VS" },
  { description: "WIC identifier", name: "WC" },
  { description: "Workers' Comp Number", name: "WCN" },
  { description: "Organization identifier", name: "XX" },
] as const;
