// Generated table profile for 0290 (v2.4)

export const id = "0290";
export const description = "MIME base64 encoding characters";
export const type = "hl7";
export const codes = [
  { description: "=", name: "(pad)" },
  { description: "A", name: "0" },
  { description: "B", name: "1" },
  { description: "K", name: "10" },
  { description: "L", name: "11" },
  { description: "M", name: "12" },
  { description: "N", name: "13" },
  { description: "O", name: "14" },
  { description: "P", name: "15" },
  { description: "Q", name: "16" },
  { description: "R", name: "17" },
  { description: "S", name: "18" },
  { description: "T", name: "19" },
  { description: "C", name: "2" },
  { description: "U", name: "20" },
  { description: "V", name: "21" },
  { description: "W", name: "22" },
  { description: "X", name: "23" },
  { description: "Y", name: "24" },
  { description: "Z", name: "25" },
  { description: "a", name: "26" },
  { description: "b", name: "27" },
  { description: "c", name: "28" },
  { description: "d", name: "29" },
  { description: "D", name: "3" },
  { description: "e", name: "30" },
  { description: "f", name: "31" },
  { description: "g", name: "32" },
  { description: "h", name: "33" },
  { description: "I", name: "34" },
  { description: "j", name: "35" },
  { description: "k", name: "36" },
  { description: "l", name: "37" },
  { description: "m", name: "38" },
  { description: "n", name: "39" },
  { description: "E", name: "4" },
  { description: "o", name: "40" },
  { description: "p", name: "41" },
  { description: "q", name: "42" },
  { description: "r", name: "43" },
  { description: "s", name: "44" },
  { description: "t", name: "45" },
  { description: "u", name: "46" },
  { description: "v", name: "47" },
  { description: "w", name: "48" },
  { description: "x", name: "49" },
  { description: "F", name: "5" },
  { description: "y", name: "50" },
  { description: "z", name: "51" },
  { description: "0", name: "52" },
  { description: "1", name: "53" },
  { description: "2", name: "54" },
  { description: "3", name: "55" },
  { description: "4", name: "56" },
  { description: "5", name: "57" },
  { description: "6", name: "58" },
  { description: "7", name: "59" },
  { description: "G", name: "6" },
  { description: "8", name: "60" },
  { description: "9", name: "61" },
  { description: "+", name: "62" },
  { description: "/", name: "63" },
  { description: "H", name: "7" },
  { description: "I", name: "8" },
  { description: "J", name: "9" },
] as const;
