// Generated table profile for 0360 (v2.4)

export const id = "0360";
export const description = "Degree";
export const type = "user";
export const codes = [
  { description: "Associate of Arts", name: "AA" },
  { description: "Associate of Applied Science", name: "AAS" },
  { description: "Associate of Business Administration", name: "ABA" },
  { description: "Associate of Engineering", name: "AE" },
  { description: "Associate of Science", name: "AS" },
  { description: "Bachelor of Arts", name: "BA" },
  { description: "Bachelor of Business Administration", name: "BBA" },
  { description: "Bachelor or Engineering", name: "BE" },
  { description: "Bachelor of Fine Arts", name: "BFA" },
  { description: "Bachelor of Nursing", name: "BN" },
  { description: "Bachelor of Science", name: "BS" },
  { description: "Bachelor of Science - Law", name: "BSL" },
  { description: "Bachelor of Theology", name: "BT" },
  { description: "Certificate", name: "CER" },
  { description: "Doctor of Business Administration", name: "DBA" },
  { description: "Doctor of Education", name: "DED" },
  { description: "Diploma", name: "DIP" },
  { description: "Doctor of Osteopathy", name: "DO" },
  { description: "High School Graduate", name: "HS" },
  { description: "Juris Doctor", name: "JD" },
  { description: "Master of Arts", name: "MA" },
  { description: "Master of Business Administration", name: "MBA" },
  { description: "Master of Civil Engineering", name: "MCE" },
  { description: "Doctor of Medicine", name: "MD" },
  { description: "Master of Divinity", name: "MDI" },
  { description: "Master of Engineering", name: "ME" },
  { description: "Master of Education", name: "MED" },
  { description: "Master of Electrical Engineering", name: "MEE" },
  { description: "Master of Fine Arts", name: "MFA" },
  { description: "Master of Mechanical Engineering", name: "MME" },
  { description: "Master of Science", name: "MS" },
  { description: "Master of Science - Law", name: "MSL" },
  { description: "Master of Theology", name: "MT" },
  { description: "Non-Graduate", name: "NG" },
  { description: "Doctor of Pharmacy", name: "PharmD" },
  { description: "Doctor of Philosophy", name: "PHD" },
  { description: "Doctor of Engineering", name: "PHE" },
  { description: "Doctor of Science", name: "PHS" },
  { description: "Secretarial Certificate", name: "SEC" },
  { description: "Trade School Graduate", name: "TS" },
] as const;
