// Generated segment profile for ARV (v2.7.1)

export const segmentId = "ARV";
export const fields = [
  {
    sequence: 1,
    id: "ARV-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID",
    item: "2143",
  },
  {
    sequence: 2,
    id: "ARV-2",
    required: true,
    repeatable: false,
    datatype: "CNE",
    table: "HL70206",
    name: "Access Restriction Action Code",
    item: "2144",
  },
  {
    sequence: 3,
    id: "ARV-3",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70717",
    name: "Access Restriction Value",
    item: "2145",
  },
  {
    sequence: 4,
    id: "ARV-4",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70719",
    name: "Access Restriction Reason",
    item: "2146",
  },
  {
    sequence: 5,
    id: "ARV-5",
    required: false,
    repeatable: true,
    datatype: "ST",
    name: "Special Access Restriction Instructions",
    item: "2147",
  },
  {
    sequence: 6,
    id: "ARV-6",
    required: false,
    repeatable: false,
    datatype: "DR",
    name: "Access Restriction Date Range",
    item: "2148",
  },
] as const;
