// Generated segment profile for AUT (v2.7.1)

export const segmentId = "AUT";
export const fields = [
  {
    sequence: 1,
    id: "AUT-1",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70072",
    name: "Authorizing Payor, Plan ID",
    item: "1146",
  },
  {
    sequence: 2,
    id: "AUT-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70285",
    name: "Authorizing Payor, Company ID",
    item: "1147",
  },
  {
    sequence: 3,
    id: "AUT-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Authorizing Payor, Company Name",
    item: "1148",
  },
  {
    sequence: 4,
    id: "AUT-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Authorization Effective Date",
    item: "1149",
  },
  {
    sequence: 5,
    id: "AUT-5",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Authorization Expiration Date",
    item: "1150",
  },
  {
    sequence: 6,
    id: "AUT-6",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Authorization Identifier",
    item: "1151",
  },
  {
    sequence: 7,
    id: "AUT-7",
    required: false,
    repeatable: false,
    datatype: "CP",
    name: "Reimbursement Limit",
    item: "1152",
  },
  {
    sequence: 8,
    id: "AUT-8",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Requested Number of Treatments",
    item: "1153",
  },
  {
    sequence: 9,
    id: "AUT-9",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Authorized Number of Treatments",
    item: "1154",
  },
  {
    sequence: 10,
    id: "AUT-10",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Process Date",
    item: "1145",
  },
  {
    sequence: 11,
    id: "AUT-11",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Requested Discipline(s)",
    item: "2375",
  },
  {
    sequence: 12,
    id: "AUT-12",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Authorized Discipline(s)",
    item: "2376",
  },
] as const;
