// Generated segment profile for EVN (v2.7.1)

export const segmentId = "EVN";
export const fields = [
  {
    sequence: 1,
    id: "EVN-2",
    required: true,
    repeatable: false,
    datatype: "DTM",
    name: "Recorded Date/Time",
    item: "100",
  },
  {
    sequence: 2,
    id: "EVN-3",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Date/Time Planned Event",
    item: "101",
  },
  {
    sequence: 3,
    id: "EVN-4",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70062",
    name: "Event Reason Code",
    item: "102",
  },
  {
    sequence: 4,
    id: "EVN-5",
    required: false,
    repeatable: true,
    datatype: "XCN",
    table: "HL70188",
    name: "Operator ID",
    item: "103",
  },
  {
    sequence: 5,
    id: "EVN-6",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Event Occurred",
    item: "1278",
  },
  {
    sequence: 6,
    id: "EVN-7",
    required: false,
    repeatable: false,
    datatype: "HD",
    name: "Event Facility",
    item: "1534",
  },
] as const;
