// Generated segment profile for GT1 (v2.7.1)

export const segmentId = "GT1";
export const fields = [
  {
    sequence: 1,
    id: "GT1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - GT1",
    item: "405",
  },
  {
    sequence: 2,
    id: "GT1-2",
    required: false,
    repeatable: true,
    datatype: "CX",
    name: "Guarantor Number",
    item: "406",
  },
  {
    sequence: 3,
    id: "GT1-3",
    required: true,
    repeatable: true,
    datatype: "XPN",
    name: "Guarantor Name",
    item: "407",
  },
  {
    sequence: 4,
    id: "GT1-4",
    required: false,
    repeatable: true,
    datatype: "XPN",
    name: "Guarantor Spouse Name",
    item: "408",
  },
  {
    sequence: 5,
    id: "GT1-5",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Guarantor Address",
    item: "409",
  },
  {
    sequence: 6,
    id: "GT1-6",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Guarantor Ph Num - Home",
    item: "410",
  },
  {
    sequence: 7,
    id: "GT1-7",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Guarantor Ph Num - Business",
    item: "411",
  },
  {
    sequence: 8,
    id: "GT1-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Guarantor Date/Time Of Birth",
    item: "412",
  },
  {
    sequence: 9,
    id: "GT1-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70001",
    name: "Guarantor Administrative Sex",
    item: "413",
  },
  {
    sequence: 10,
    id: "GT1-10",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70068",
    name: "Guarantor Type",
    item: "414",
  },
  {
    sequence: 11,
    id: "GT1-11",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70063",
    name: "Guarantor Relationship",
    item: "415",
  },
  {
    sequence: 12,
    id: "GT1-12",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Guarantor SSN",
    item: "416",
  },
  {
    sequence: 13,
    id: "GT1-13",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Guarantor Date - Begin",
    item: "417",
  },
  {
    sequence: 14,
    id: "GT1-14",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Guarantor Date - End",
    item: "418",
  },
  {
    sequence: 15,
    id: "GT1-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    name: "Guarantor Priority",
    item: "419",
  },
  {
    sequence: 16,
    id: "GT1-16",
    required: false,
    repeatable: true,
    datatype: "XPN",
    name: "Guarantor Employer Name",
    item: "420",
  },
  {
    sequence: 17,
    id: "GT1-17",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Guarantor Employer Address",
    item: "421",
  },
  {
    sequence: 18,
    id: "GT1-18",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Guarantor Employer Phone Number",
    item: "422",
  },
  {
    sequence: 19,
    id: "GT1-19",
    required: false,
    repeatable: true,
    datatype: "CX",
    name: "Guarantor Employee ID Number",
    item: "423",
  },
  {
    sequence: 20,
    id: "GT1-20",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70066",
    name: "Guarantor Employment Status",
    item: "424",
  },
  {
    sequence: 21,
    id: "GT1-21",
    required: false,
    repeatable: true,
    datatype: "XON",
    name: "Guarantor Organization Name",
    item: "425",
  },
  {
    sequence: 22,
    id: "GT1-22",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Guarantor Billing Hold Flag",
    item: "773",
  },
  {
    sequence: 23,
    id: "GT1-23",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70341",
    name: "Guarantor Credit Rating Code",
    item: "774",
  },
  {
    sequence: 24,
    id: "GT1-24",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Guarantor Death Date And Time",
    item: "775",
  },
  {
    sequence: 25,
    id: "GT1-25",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Guarantor Death Flag",
    item: "776",
  },
  {
    sequence: 26,
    id: "GT1-26",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70218",
    name: "Guarantor Charge Adjustment Code",
    item: "777",
  },
  {
    sequence: 27,
    id: "GT1-27",
    required: false,
    repeatable: false,
    datatype: "CP",
    name: "Guarantor Household Annual Income",
    item: "778",
  },
  {
    sequence: 28,
    id: "GT1-28",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Guarantor Household Size",
    item: "779",
  },
  {
    sequence: 29,
    id: "GT1-29",
    required: false,
    repeatable: true,
    datatype: "CX",
    name: "Guarantor Employer ID Number",
    item: "780",
  },
  {
    sequence: 30,
    id: "GT1-30",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70002",
    name: "Guarantor Marital Status Code",
    item: "781",
  },
  {
    sequence: 31,
    id: "GT1-31",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Guarantor Hire Effective Date",
    item: "782",
  },
  {
    sequence: 32,
    id: "GT1-32",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Employment Stop Date",
    item: "783",
  },
  {
    sequence: 33,
    id: "GT1-33",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70223",
    name: "Living Dependency",
    item: "755",
  },
  {
    sequence: 34,
    id: "GT1-34",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70009",
    name: "Ambulatory Status",
    item: "145",
  },
  {
    sequence: 35,
    id: "GT1-35",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70171",
    name: "Citizenship",
    item: "129",
  },
  {
    sequence: 36,
    id: "GT1-36",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70296",
    name: "Primary Language",
    item: "118",
  },
  {
    sequence: 37,
    id: "GT1-37",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70220",
    name: "Living Arrangement",
    item: "742",
  },
  {
    sequence: 38,
    id: "GT1-38",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70215",
    name: "Publicity Code",
    item: "743",
  },
  {
    sequence: 39,
    id: "GT1-39",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Protection Indicator",
    item: "744",
  },
  {
    sequence: 40,
    id: "GT1-40",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70231",
    name: "Student Indicator",
    item: "745",
  },
  {
    sequence: 41,
    id: "GT1-41",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70006",
    name: "Religion",
    item: "120",
  },
  {
    sequence: 42,
    id: "GT1-42",
    required: false,
    repeatable: true,
    datatype: "XPN",
    name: "Mother's Maiden Name",
    item: "109",
  },
  {
    sequence: 43,
    id: "GT1-43",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70212",
    name: "Nationality",
    item: "739",
  },
  {
    sequence: 44,
    id: "GT1-44",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70189",
    name: "Ethnic Group",
    item: "125",
  },
  {
    sequence: 45,
    id: "GT1-45",
    required: false,
    repeatable: true,
    datatype: "XPN",
    name: "Contact Person's Name",
    item: "748",
  },
  {
    sequence: 46,
    id: "GT1-46",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Contact Person's Telephone Number",
    item: "749",
  },
  {
    sequence: 47,
    id: "GT1-47",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70222",
    name: "Contact Reason",
    item: "747",
  },
  {
    sequence: 48,
    id: "GT1-48",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70063",
    name: "Contact Relationship",
    item: "784",
  },
  {
    sequence: 49,
    id: "GT1-49",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Job Title",
    item: "785",
  },
  {
    sequence: 50,
    id: "GT1-50",
    required: false,
    repeatable: false,
    datatype: "JCC",
    name: "Job Code/Class",
    item: "786",
  },
  {
    sequence: 51,
    id: "GT1-51",
    required: false,
    repeatable: true,
    datatype: "XON",
    name: "Guarantor Employer's Organization Name",
    item: "1299",
  },
  {
    sequence: 52,
    id: "GT1-52",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70295",
    name: "Handicap",
    item: "753",
  },
  {
    sequence: 53,
    id: "GT1-53",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70311",
    name: "Job Status",
    item: "752",
  },
  {
    sequence: 54,
    id: "GT1-54",
    required: false,
    repeatable: false,
    datatype: "FC",
    name: "Guarantor Financial Class",
    item: "1231",
  },
  {
    sequence: 55,
    id: "GT1-55",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70005",
    name: "Guarantor Race",
    item: "1291",
  },
  {
    sequence: 56,
    id: "GT1-56",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Guarantor Birth Place",
    item: "1851",
  },
  {
    sequence: 57,
    id: "GT1-57",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70099",
    name: "VIP Indicator",
    item: "146",
  },
] as const;
