// Generated segment profile for PEO (v2.7.1)

export const segmentId = "PEO";
export const fields = [
  {
    sequence: 1,
    id: "PEO-1",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Event Identifiers Used",
    item: "1073",
  },
  {
    sequence: 2,
    id: "PEO-2",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Event Symptom/Diagnosis Code",
    item: "1074",
  },
  {
    sequence: 3,
    id: "PEO-3",
    required: true,
    repeatable: false,
    datatype: "DTM",
    name: "Event Onset Date/Time",
    item: "1075",
  },
  {
    sequence: 4,
    id: "PEO-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Event Exacerbation Date/Time",
    item: "1076",
  },
  {
    sequence: 5,
    id: "PEO-5",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Event Improved Date/Time",
    item: "1077",
  },
  {
    sequence: 6,
    id: "PEO-6",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Event Ended Data/Time",
    item: "1078",
  },
  {
    sequence: 7,
    id: "PEO-7",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Event Location Occurred Address",
    item: "1079",
  },
  {
    sequence: 8,
    id: "PEO-8",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 1,
    table: "HL70237",
    name: "Event Qualification",
    item: "1080",
  },
  {
    sequence: 9,
    id: "PEO-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70238",
    name: "Event Serious",
    item: "1081",
  },
  {
    sequence: 10,
    id: "PEO-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70239",
    name: "Event Expected",
    item: "1082",
  },
  {
    sequence: 11,
    id: "PEO-11",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 1,
    table: "HL70240",
    name: "Event Outcome",
    item: "1083",
  },
  {
    sequence: 12,
    id: "PEO-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70241",
    name: "Patient Outcome",
    item: "1084",
  },
  {
    sequence: 13,
    id: "PEO-13",
    required: false,
    repeatable: true,
    datatype: "FT",
    name: "Event Description from Others",
    item: "1085",
  },
  {
    sequence: 14,
    id: "PEO-14",
    required: false,
    repeatable: true,
    datatype: "FT",
    name: "Event Description from Original Reporter",
    item: "1086",
  },
  {
    sequence: 15,
    id: "PEO-15",
    required: false,
    repeatable: true,
    datatype: "FT",
    name: "Event Description from Patient",
    item: "1087",
  },
  {
    sequence: 16,
    id: "PEO-16",
    required: false,
    repeatable: true,
    datatype: "FT",
    name: "Event Description from Practitioner",
    item: "1088",
  },
  {
    sequence: 17,
    id: "PEO-17",
    required: false,
    repeatable: true,
    datatype: "FT",
    name: "Event Description from Autopsy",
    item: "1089",
  },
  {
    sequence: 18,
    id: "PEO-18",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Cause Of Death",
    item: "1090",
  },
  {
    sequence: 19,
    id: "PEO-19",
    required: false,
    repeatable: true,
    datatype: "XPN",
    name: "Primary Observer Name",
    item: "1091",
  },
  {
    sequence: 20,
    id: "PEO-20",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Primary Observer Address",
    item: "1092",
  },
  {
    sequence: 21,
    id: "PEO-21",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Primary Observer Telephone",
    item: "1093",
  },
  {
    sequence: 22,
    id: "PEO-22",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70242",
    name: "Primary Observer's Qualification",
    item: "1094",
  },
  {
    sequence: 23,
    id: "PEO-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70242",
    name: "Confirmation Provided By",
    item: "1095",
  },
  {
    sequence: 24,
    id: "PEO-24",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Primary Observer Aware Date/Time",
    item: "1096",
  },
  {
    sequence: 25,
    id: "PEO-25",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70243",
    name: "Primary Observer's identity May Be Divulged",
    item: "1097",
  },
] as const;
