// Generated table profile for 0074 (v2.6)

export const id = "0074";
export const description = "Diagnostic Service Section ID";
export const type = "hl7";
export const codes = [
  { description: "Audiology", name: "AU" },
  { description: "Blood Gases", name: "BG" },
  { description: "Blood Bank", name: "BLB" },
  { description: "Chemistry", name: "CH" },
  { description: "Cytopathology", name: "CP" },
  { description: "CAT Scan", name: "CT" },
  { description: "Cardiac Catheterization", name: "CTH" },
  { description: "Cardiac Ultrasound", name: "CUS" },
  { description: "Electrocardiac (e.g., EKG,  EEC, Holter)", name: "EC" },
  { description: "Electroneuro (EEG, EMG,EP,PSG)", name: "EN" },
  { description: "Hematology", name: "HM" },
  { description: "Bedside ICU Monitoring", name: "ICU" },
  { description: "Immunology", name: "IMM" },
  { description: "Laboratory", name: "LAB" },
  { description: "Microbiology", name: "MB" },
  { description: "Mycobacteriology", name: "MCB" },
  { description: "Mycology", name: "MYC" },
  { description: "Nuclear Magnetic Resonance", name: "NMR" },
  { description: "Nuclear Medicine Scan", name: "NMS" },
  { description: "Nursing Service Measures", name: "NRS" },
  { description: "Outside Lab", name: "OSL" },
  { description: "Occupational Therapy", name: "OT" },
  { description: "Other", name: "OTH" },
  { description: "OB Ultrasound", name: "OUS" },
  { description: "Pulmonary Function", name: "PF" },
  { description: "Pharmacy", name: "PHR" },
  { description: "Physician (Hx. Dx, admission note, etc.)", name: "PHY" },
  { description: "Physical Therapy", name: "PT" },
  { description: "Radiology", name: "RAD" },
  { description: "Respiratory Care (therapy)", name: "RC" },
  { description: "Radiation Therapy", name: "RT" },
  { description: "Radiology Ultrasound", name: "RUS" },
  { description: "Radiograph", name: "RX" },
  { description: "Surgical Pathology", name: "SP" },
  { description: "Serology", name: "SR" },
  { description: "Toxicology", name: "TX" },
  { description: "Virology", name: "VR" },
  { description: "Vascular Ultrasound", name: "VUS" },
  { description: "Cineradiograph", name: "XRC" },
] as const;
