// Generated table profile for 0203 (v2.6)

export const id = "0203";
export const description = "Identifier type";
export const type = "hl7";
export const codes = [
  { description: "American Express", name: "AM" },
  { description: "American Medical Association Number", name: "AMA" },
  { description: "Account number", name: "AN" },
  { description: "Account number Creditor", name: "ANC" },
  { description: "Account number debitor", name: "AND" },
  { description: "Anonymous identifier", name: "ANON" },
  { description: "Temporary Account Number", name: "ANT" },
  { description: "Advanced Practice Registered Nurse number", name: "APRN" },
  { description: "Bank Account Number", name: "BA" },
  { description: "Bank Card Number", name: "BC" },
  { description: "Birth Certificate", name: "BCT" },
  { description: "Birth registry number", name: "BR" },
  { description: "Breed Registry Number", name: "BRN" },
  { description: "Cost Center number", name: "CC" },
  { description: "Change of Name Document", name: "CONM" },
  { description: "County number", name: "CY" },
  { description: "Citizenship Card", name: "CZ" },
  { description: "Dentist license number", name: "DDS" },
  {
    description: "Drug Enforcement Administration registration number",
    name: "DEA",
  },
  {
    description: "Drug Furnishing or prescriptive authority Number",
    name: "DFN",
  },
  { description: "Diner's Club card", name: "DI" },
  { description: "Driver's license number", name: "DL" },
  { description: "Doctor number", name: "DN" },
  { description: "Osteopathic License number", name: "DO" },
  { description: "Diplomatic Passport", name: "DP" },
  { description: "Podiatrist license number", name: "DPM" },
  { description: "Donor Registration Number", name: "DR" },
  { description: "Discover Card", name: "DS" },
  { description: "Employee number", name: "EI" },
  { description: "Employer number", name: "EN" },
  { description: "Staff Enterprise Number", name: "ESN" },
  { description: "Facility ID", name: "FI" },
  { description: "Guarantor internal identifier", name: "GI" },
  { description: "General ledger number", name: "GL" },
  { description: "Guarantor external  identifier", name: "GN" },
  { description: "Health Card Number", name: "HC" },
  { description: "Indigenous/Aboriginal", name: "IND" },
  { description: "Jurisdictional health number (Canada)", name: "JHN" },
  { description: "Labor and industries number", name: "LI" },
  { description: "License number", name: "LN" },
  { description: "Local Registry ID", name: "LR" },
  { description: "Patient Medicaid number", name: "MA" },
  { description: "Member Number", name: "MB" },
  { description: "Patient's Medicare number", name: "MC" },
  { description: "Practitioner Medicaid number", name: "MCD" },
  { description: "Microchip Number", name: "MCN" },
  { description: "Practitioner Medicare number", name: "MCR" },
  { description: "Marriage Certificate", name: "MCT" },
  { description: "Medical License number", name: "MD" },
  { description: "Military ID number", name: "MI" },
  { description: "Medical record number", name: "MR" },
  { description: "Temporary Medical Record Number", name: "MRT" },
  { description: "MasterCard", name: "MS" },
  { description: "Naturalization Certificate", name: "NCT" },
  { description: "National employer identifier", name: "NE" },
  { description: "National Health Plan Identifier", name: "NH" },
  { description: "National unique individual identifier", name: "NI" },
  { description: "National Insurance Organization Identifier", name: "NII" },
  { description: "National Insurance Payor Identifier (Payor)", name: "NIIP" },
  {
    description:
      "National Person Identifier where the xxx is the ISO table 3166 3-character (alphabetic) country code",
    name: "NNxxx",
  },
  { description: "Nurse practitioner number", name: "NP" },
  { description: "National provider identifier", name: "NPI" },
  { description: "Optometrist license number", name: "OD" },
  { description: "Physician Assistant number", name: "PA" },
  { description: "Parole Card", name: "PC" },
  { description: "Penitentiary/correctional institution Number", name: "PCN" },
  { description: "Living Subject Enterprise Number", name: "PE" },
  { description: "Pension Number", name: "PEN" },
  { description: "Patient internal identifier", name: "PI" },
  { description: "Person number", name: "PN" },
  { description: "Temporary Living Subject Number", name: "PNT" },
  {
    description: "Medicare/CMS Performing Provider Identification Number",
    name: "PPIN",
  },
  { description: "Passport number", name: "PPN" },
  { description: "Permanent Resident Card Number", name: "PRC" },
  { description: "Provider number", name: "PRN" },
  { description: "Patient external identifier", name: "PT" },
  { description: "QA number", name: "QA" },
  { description: "Resource identifier", name: "RI" },
  { description: "Registered Nurse Number", name: "RN" },
  { description: "Pharmacist license number", name: "RPH" },
  { description: "Railroad Retirement number", name: "RR" },
  { description: "Regional registry ID", name: "RRI" },
  { description: "Railroad Retirement Provider", name: "RRP" },
  { description: "State license", name: "SL" },
  { description: "Subscriber Number", name: "SN" },
  { description: "Study Permit", name: "SP" },
  { description: "State registry ID", name: "SR" },
  { description: "Social Security number", name: "SS" },
  { description: "Tax ID number", name: "TAX" },
  { description: "Treaty Number/ (Canada)", name: "TN" },
  { description: "Temporary Permanent Resident (Canada)", name: "TPR" },
  { description: "Unspecified identifier", name: "U" },
  {
    description:
      "Medicare/CMS (formerly HCFA)'s Universal Physician Identification numbers",
    name: "UPIN",
  },
  { description: "Visit number", name: "VN" },
  { description: "Visitor Permit", name: "VP" },
  { description: "VISA", name: "VS" },
  { description: "WIC identifier", name: "WC" },
  { description: "Workers' Comp Number", name: "WCN" },
  { description: "Work Permit", name: "WP" },
  { description: "Organization identifier", name: "XX" },
] as const;
