// Generated profile automaton for PEX_P07 (v2.5)

export const start = 0;
export const finals = new Set<number>([
  11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31,
]);
export const alphabet = new Set<string>([
  "CSP",
  "CSR",
  "EVN",
  "MSH",
  "NK1",
  "NTE",
  "OBX",
  "PCR",
  "PD1",
  "PEO",
  "PES",
  "PID",
  "PRB",
  "PV1",
  "PV2",
  "RXA",
  "RXE",
  "RXR",
  "SFT",
  "TQ1",
  "TQ2",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["EVN", 2],
      ["SFT", 3],
    ]),
  ],
  [2, new Map([["PID", 4]])],
  [
    3,
    new Map([
      ["EVN", 2],
      ["SFT", 3],
    ]),
  ],
  [
    4,
    new Map([
      ["NTE", 7],
      ["PD1", 8],
      ["PES", 5],
      ["PV1", 6],
    ]),
  ],
  [5, new Map([["PEO", 9]])],
  [
    6,
    new Map([
      ["PES", 5],
      ["PV2", 10],
    ]),
  ],
  [
    7,
    new Map([
      ["NTE", 7],
      ["PES", 5],
      ["PV1", 6],
    ]),
  ],
  [
    8,
    new Map([
      ["NTE", 7],
      ["PES", 5],
      ["PV1", 6],
    ]),
  ],
  [9, new Map([["PCR", 11]])],
  [10, new Map([["PES", 5]])],
  [
    11,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
      ["RXA", 17],
      ["RXE", 18],
    ]),
  ],
  [
    12,
    new Map([
      ["CSP", 19],
      ["CSR", 12],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
    ]),
  ],
  [
    13,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
      ["RXA", 22],
      ["RXE", 23],
    ]),
  ],
  [
    14,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
    ]),
  ],
  [
    15,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
    ]),
  ],
  [
    16,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
    ]),
  ],
  [
    17,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
      ["RXA", 17],
      ["RXR", 24],
    ]),
  ],
  [18, new Map([["TQ1", 25]])],
  [
    19,
    new Map([
      ["CSP", 19],
      ["CSR", 12],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
    ]),
  ],
  [
    20,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
    ]),
  ],
  [
    21,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
    ]),
  ],
  [
    22,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
      ["RXA", 22],
      ["RXR", 26],
    ]),
  ],
  [23, new Map([["TQ1", 27]])],
  [
    24,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
      ["RXA", 17],
    ]),
  ],
  [
    25,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
      ["RXA", 17],
      ["RXR", 28],
      ["TQ1", 25],
      ["TQ2", 29],
    ]),
  ],
  [
    26,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
      ["RXA", 22],
    ]),
  ],
  [
    27,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
      ["RXA", 22],
      ["RXR", 30],
      ["TQ1", 27],
      ["TQ2", 31],
    ]),
  ],
  [
    28,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
      ["RXA", 17],
      ["RXR", 28],
    ]),
  ],
  [
    29,
    new Map([
      ["CSR", 12],
      ["NK1", 13],
      ["NTE", 14],
      ["OBX", 15],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 16],
      ["RXA", 17],
      ["RXR", 28],
      ["TQ1", 25],
      ["TQ2", 29],
    ]),
  ],
  [
    30,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
      ["RXA", 22],
      ["RXR", 30],
    ]),
  ],
  [
    31,
    new Map([
      ["CSR", 12],
      ["OBX", 20],
      ["PCR", 11],
      ["PEO", 9],
      ["PES", 5],
      ["PRB", 21],
      ["RXA", 22],
      ["RXR", 30],
      ["TQ1", 27],
      ["TQ2", 31],
    ]),
  ],
]);
export const effects = {
  "10:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: ["PEX_P07/VISIT"],
  },
  "11:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "11:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "11:NTE": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "11:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "11:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "11:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "11:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "11:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "11:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
    groupsClosed: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER"],
  },
  "11:RXE": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "12:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [],
  },
  "12:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "12:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
  },
  "12:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "13:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "13:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "13:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "13:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "13:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "13:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "13:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "13:RXE": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "14:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
  },
  "14:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [],
  },
  "14:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "14:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "14:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "15:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
  },
  "15:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [],
  },
  "15:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "15:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "15:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "16:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
  },
  "16:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [],
  },
  "16:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "16:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "16:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "17:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "17:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "17:NTE": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "17:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "17:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "17:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "17:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "17:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "17:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
    groupsClosed: [],
  },
  "18:TQ1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
    groupsClosed: [],
  },
  "19:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [],
  },
  "19:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "19:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
  },
  "19:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "20:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
  },
  "20:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "20:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "20:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "21:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
  },
  "21:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "21:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "21:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "22:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "22:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "22:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "22:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "22:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "22:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "22:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
    groupsClosed: [],
  },
  "23:TQ1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
    groupsClosed: [],
  },
  "24:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "24:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "24:NTE": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "24:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "24:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "24:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "24:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "24:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
  },
  "24:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
    groupsClosed: [],
  },
  "25:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:NTE": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "25:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "25:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "25:TQ1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
    groupsClosed: [],
  },
  "26:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "26:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "26:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "26:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "26:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "26:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
  },
  "26:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
    groupsClosed: [],
  },
  "27:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "27:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "27:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "27:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "27:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "27:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "27:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "27:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "27:TQ1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
    groupsClosed: [],
  },
  "28:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "28:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "28:NTE": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "28:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "28:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
  "28:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "28:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "28:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
    ],
  },
  "28:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
    groupsClosed: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER"],
  },
  "29:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:NK1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:NTE": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "29:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "29:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ADMINISTRATION",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
  },
  "29:TQ1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/RX_ORDER/TIMING_QTY",
    ],
    groupsClosed: [],
  },
  "30:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "30:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "30:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "30:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "30:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "30:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "30:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
    ],
  },
  "31:CSR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "31:OBX": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "31:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "31:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "31:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/STUDY",
    ],
  },
  "31:PRB": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "31:RXA": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ADMIN",
    ],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER",
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "31:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
  },
  "31:TQ1": {
    groupsOpened: [
      "PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE/ASSOCIATED_PERSON/ASSOCIATED_RX_ORDER/NK1_TIMING_QTY",
    ],
    groupsClosed: [],
  },
  "4:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: ["PEX_P07/VISIT"],
  },
  "4:PV1": {
    groupsOpened: ["PEX_P07/VISIT"],
    groupsClosed: [],
  },
  "5:PEO": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION"],
    groupsClosed: [],
  },
  "6:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: ["PEX_P07/VISIT"],
  },
  "7:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: ["PEX_P07/VISIT"],
  },
  "7:PV1": {
    groupsOpened: ["PEX_P07/VISIT"],
    groupsClosed: [],
  },
  "8:PES": {
    groupsOpened: ["PEX_P07/EXPERIENCE"],
    groupsClosed: ["PEX_P07/VISIT"],
  },
  "8:PV1": {
    groupsOpened: ["PEX_P07/VISIT"],
    groupsClosed: [],
  },
  "9:PCR": {
    groupsOpened: ["PEX_P07/EXPERIENCE/PEX_OBSERVATION/PEX_CAUSE"],
    groupsClosed: [],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
