// Generated profile automaton for RSP_Z86 (v2.5)

export const start = 0;
export const finals = new Set<number>([
  7, 9, 10, 11, 17, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 33,
]);
export const alphabet = new Set<string>([
  "AL1",
  "DSC",
  "ERR",
  "MSA",
  "MSH",
  "NTE",
  "OBX",
  "ORC",
  "PD1",
  "PID",
  "QAK",
  "QPD",
  "RXA",
  "RXC",
  "RXD",
  "RXE",
  "RXG",
  "RXO",
  "RXR",
  "SFT",
  "TQ1",
  "TQ2",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["MSA", 2],
      ["SFT", 3],
    ]),
  ],
  [
    2,
    new Map([
      ["ERR", 5],
      ["QAK", 4],
    ]),
  ],
  [
    3,
    new Map([
      ["MSA", 2],
      ["SFT", 3],
    ]),
  ],
  [4, new Map([["QPD", 6]])],
  [5, new Map([["QAK", 4]])],
  [
    6,
    new Map([
      ["ORC", 7],
      ["PID", 8],
    ]),
  ],
  [
    7,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXD", 14],
      ["RXE", 15],
      ["RXG", 13],
      ["RXO", 16],
      ["TQ1", 17],
    ]),
  ],
  [
    8,
    new Map([
      ["AL1", 18],
      ["NTE", 19],
      ["ORC", 7],
      ["PD1", 20],
    ]),
  ],
  [9, new Map([])],
  [
    10,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
    ]),
  ],
  [
    11,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
    ]),
  ],
  [12, new Map([["RXR", 21]])],
  [13, new Map([["RXR", 22]])],
  [14, new Map([["RXR", 23]])],
  [
    15,
    new Map([
      ["RXR", 24],
      ["TQ1", 25],
    ]),
  ],
  [16, new Map([["RXR", 26]])],
  [
    17,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXD", 14],
      ["RXE", 15],
      ["RXG", 13],
      ["RXO", 16],
      ["TQ1", 17],
      ["TQ2", 27],
    ]),
  ],
  [
    18,
    new Map([
      ["AL1", 18],
      ["ORC", 7],
    ]),
  ],
  [
    19,
    new Map([
      ["AL1", 18],
      ["NTE", 19],
      ["ORC", 7],
    ]),
  ],
  [
    20,
    new Map([
      ["AL1", 18],
      ["NTE", 19],
      ["ORC", 7],
    ]),
  ],
  [
    21,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXC", 28],
      ["RXR", 21],
    ]),
  ],
  [
    22,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 29],
      ["RXR", 22],
    ]),
  ],
  [
    23,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 30],
      ["RXG", 13],
      ["RXR", 23],
    ]),
  ],
  [
    24,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 31],
      ["RXD", 14],
      ["RXG", 13],
      ["RXR", 24],
    ]),
  ],
  [
    25,
    new Map([
      ["RXR", 24],
      ["TQ1", 25],
      ["TQ2", 32],
    ]),
  ],
  [
    26,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 33],
      ["RXD", 14],
      ["RXE", 15],
      ["RXG", 13],
      ["RXR", 26],
    ]),
  ],
  [
    27,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXD", 14],
      ["RXE", 15],
      ["RXG", 13],
      ["RXO", 16],
      ["TQ1", 17],
      ["TQ2", 27],
    ]),
  ],
  [
    28,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXC", 28],
    ]),
  ],
  [
    29,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 29],
    ]),
  ],
  [
    30,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 30],
      ["RXG", 13],
    ]),
  ],
  [
    31,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 31],
      ["RXD", 14],
      ["RXG", 13],
    ]),
  ],
  [
    32,
    new Map([
      ["RXR", 24],
      ["TQ1", 25],
      ["TQ2", 32],
    ]),
  ],
  [
    33,
    new Map([
      ["DSC", 9],
      ["NTE", 10],
      ["OBX", 11],
      ["ORC", 7],
      ["PID", 8],
      ["RXA", 12],
      ["RXC", 33],
      ["RXD", 14],
      ["RXE", 15],
      ["RXG", 13],
    ]),
  ],
]);
export const effects = {
  "6:ORC": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
    ],
    groupsClosed: [],
  },
  "6:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [],
  },
  "7:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "7:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "7:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "7:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "7:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "7:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "7:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "7:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "7:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "7:RXO": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "7:TQ1": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING"],
    groupsClosed: [],
  },
  "8:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "10:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [],
  },
  "10:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [],
  },
  "10:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "10:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "10:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "11:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [],
  },
  "11:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "11:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "11:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "15:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
  },
  "15:TQ1": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
    groupsClosed: [],
  },
  "17:TQ1": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING"],
    groupsClosed: [],
  },
  "17:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "17:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "17:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "17:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "17:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "17:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "17:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "17:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "17:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "17:RXO": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "18:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "19:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "20:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "21:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "21:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "21:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "21:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "21:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "22:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "22:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "22:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "22:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "22:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "22:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "23:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "23:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "23:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "23:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "23:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "23:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "23:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "24:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "24:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "24:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "24:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "24:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "24:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "24:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "24:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "25:TQ1": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
    groupsClosed: [],
  },
  "25:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
  },
  "26:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "26:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "26:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "26:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "26:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "26:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "26:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "26:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "26:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "27:TQ1": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING"],
    groupsClosed: [],
  },
  "27:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "27:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "27:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "27:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "27:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
  },
  "27:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "27:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "27:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "27:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "27:RXO": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "28:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "28:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "28:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "28:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "28:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "29:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "29:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "29:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "29:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "29:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "29:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "30:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "30:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "30:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "30:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "30:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "30:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "30:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "31:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "31:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
  },
  "31:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "31:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "31:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
  },
  "31:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "31:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "31:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "32:TQ1": {
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
    groupsClosed: [],
  },
  "32:RXR": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
  },
  "33:ORC": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
    groupsClosed: [],
  },
  "33:PID": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "33:DSC": {
    groupsOpened: [],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "33:NTE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "33:OBX": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
  },
  "33:RXA": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "33:RXG": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "33:RXD": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
  "33:RXE": {
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
