// Generated segment profile for BHS (v2.1)

export const segmentId = "BHS";
export const fields = [
  {
    datatype: "ST",
    id: "BHS-1",
    item: "685",
    maxLength: 1,
    name: "BATCH FIELD SEPARATOR",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "BHS-2",
    item: "686",
    maxLength: 3,
    name: "BATCH ENCODING CHARACTERS",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "BHS-3",
    item: "687",
    maxLength: 15,
    name: "BATCH SENDING APPLICATION",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "BHS-4",
    item: "688",
    maxLength: 20,
    name: "BATCH SENDING FACILITY",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "BHS-5",
    item: "689",
    maxLength: 15,
    name: "BATCH RECEIVING APPLICATION",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "BHS-6",
    item: "690",
    maxLength: 20,
    name: "BATCH RECEIVING FACILITY",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "BHS-7",
    item: "655",
    maxLength: 19,
    name: "BATCH CREATION DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "BHS-8",
    item: "691",
    maxLength: 40,
    name: "BATCH SECURITY",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "BHS-9",
    item: "656",
    maxLength: 20,
    name: "BATCH NAME/ID/TYPE",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "BHS-10",
    item: "657",
    maxLength: 80,
    name: "BATCH COMMENT",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "BHS-11",
    item: "658",
    maxLength: 20,
    name: "BATCH CONTROL ID",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "BHS-12",
    item: "659",
    maxLength: 20,
    name: "REFERENCE BATCH CONTROL ID",
    repeatable: false,
    required: false,
    sequence: 12,
  },
] as const;
