// Generated segment profile for DG1 (v2.1)

export const segmentId = "DG1";
export const fields = [
  {
    datatype: "SI",
    id: "DG1-1",
    item: "506",
    maxLength: 4,
    name: "SET ID - DIAGNOSIS",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "DG1-2",
    item: "394",
    maxLength: 2,
    name: "DIAGNOSIS CODING METHOD",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70053",
  },
  {
    datatype: "ID",
    id: "DG1-3",
    item: "293",
    maxLength: 8,
    name: "DIAGNOSIS CODE",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70051",
  },
  {
    datatype: "ST",
    id: "DG1-4",
    item: "294",
    maxLength: 40,
    name: "DIAGNOSIS DESCRIPTION",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "DG1-5",
    item: "295",
    maxLength: 19,
    name: "DIAGNOSIS DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "DG1-6",
    item: "297",
    maxLength: 2,
    name: "DIAGNOSIS/DRG TYPE",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70052",
  },
  {
    datatype: "ST",
    id: "DG1-7",
    item: "298",
    maxLength: 4,
    name: "MAJOR DIAGNOSTIC CATEGORY",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70118",
  },
  {
    datatype: "ID",
    id: "DG1-8",
    item: "299",
    maxLength: 4,
    name: "DIAGNOSTIC RELATED GROUP",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70055",
  },
  {
    datatype: "ID",
    id: "DG1-9",
    item: "373",
    maxLength: 2,
    name: "DRG APPROVAL INDICATOR",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "DG1-10",
    item: "374",
    maxLength: 2,
    name: "DRG GROUPER REVIEW CODE",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70056",
  },
  {
    datatype: "ID",
    id: "DG1-11",
    item: "375",
    maxLength: 2,
    name: "OUTLIER TYPE",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70083",
  },
  {
    datatype: "NM",
    id: "DG1-12",
    item: "300",
    maxLength: 3,
    name: "OUTLIER DAYS",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "DG1-13",
    item: "376",
    maxLength: 12,
    name: "OUTLIER COST",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "DG1-14",
    item: "781",
    maxLength: 4,
    name: "GROUPER VERSION AND TYPE",
    repeatable: false,
    required: false,
    sequence: 14,
  },
] as const;
