// Generated segment profile for DSP (v2.1)

export const segmentId = "DSP";
export const fields = [
  {
    datatype: "SI",
    id: "DSP-1",
    item: "570",
    maxLength: 4,
    name: "SET ID - DISPLAY DATA",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "SI",
    id: "DSP-2",
    item: "571",
    maxLength: 4,
    name: "DISPLAY LEVEL",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TX",
    id: "DSP-3",
    item: "153",
    maxLength: 300,
    name: "DATA LINE",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "DSP-4",
    item: "154",
    maxLength: 2,
    name: "LOGICAL BREAK POINT",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TX",
    id: "DSP-5",
    item: "599",
    maxLength: 20,
    name: "RESULT ID",
    repeatable: false,
    required: false,
    sequence: 5,
  },
] as const;
