// Generated segment profile for FT1 (v2.1)

export const segmentId = "FT1";
export const fields = [
  {
    datatype: "SI",
    id: "FT1-1",
    item: "507",
    maxLength: 4,
    name: "SET ID - FINANCIAL TRANSACTION",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "FT1-2",
    item: "366",
    maxLength: 12,
    name: "TRANSACTION ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "FT1-3",
    item: "503",
    maxLength: 5,
    name: "TRANSACTION BATCH ID",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "DT",
    id: "FT1-4",
    item: "351",
    maxLength: 8,
    name: "TRANSACTION DATE",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "DT",
    id: "FT1-5",
    item: "352",
    maxLength: 8,
    name: "TRANSACTION POSTING DATE",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "FT1-6",
    item: "353",
    maxLength: 8,
    name: "TRANSACTION TYPE",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70017",
  },
  {
    datatype: "ID",
    id: "FT1-7",
    item: "354",
    maxLength: 20,
    name: "TRANSACTION CODE",
    repeatable: false,
    required: true,
    sequence: 7,
    table: "HL70096",
  },
  {
    datatype: "ST",
    id: "FT1-8",
    item: "356",
    maxLength: 40,
    name: "TRANSACTION DESCRIPTION",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "FT1-9",
    item: "706",
    maxLength: 40,
    name: "TRANSACTION DESCRIPTION - ALT",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "FT1-10",
    item: "358",
    maxLength: 12,
    name: "TRANSACTION AMOUNT - EXTENDED",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "FT1-11",
    item: "357",
    maxLength: 4,
    name: "TRANSACTION QUANTITY",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "NM",
    id: "FT1-12",
    item: "782",
    maxLength: 12,
    name: "TRANSACTION AMOUNT - UNIT",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "FT1-13",
    item: "355",
    maxLength: 16,
    name: "DEPARTMENT CODE",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70049",
  },
  {
    datatype: "ID",
    id: "FT1-14",
    item: "359",
    maxLength: 8,
    name: "INSURANCE PLAN ID",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70072",
  },
  {
    datatype: "NM",
    id: "FT1-15",
    item: "360",
    maxLength: 12,
    name: "INSURANCE AMOUNT",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ST",
    id: "FT1-16",
    item: "361",
    maxLength: 12,
    name: "PATIENT LOCATION",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70079",
  },
  {
    datatype: "ID",
    id: "FT1-17",
    item: "362",
    maxLength: 1,
    name: "FEE SCHEDULE",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70024",
  },
  {
    datatype: "ID",
    id: "FT1-18",
    item: "363",
    maxLength: 2,
    name: "PATIENT TYPE",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70018",
  },
  {
    datatype: "ID",
    id: "FT1-19",
    item: "364",
    maxLength: 8,
    name: "DIAGNOSIS CODE",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70051",
  },
  {
    datatype: "CN",
    id: "FT1-20",
    item: "377",
    maxLength: 60,
    name: "PERFORMED BY CODE",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70084",
  },
  {
    datatype: "CN",
    id: "FT1-21",
    item: "783",
    maxLength: 60,
    name: "ORDERED BY CODE",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "NM",
    id: "FT1-22",
    item: "784",
    maxLength: 12,
    name: "UNIT COST",
    repeatable: false,
    required: false,
    sequence: 22,
  },
] as const;
