// Generated segment profile for GT1 (v2.1)

export const segmentId = "GT1";
export const fields = [
  {
    datatype: "SI",
    id: "GT1-1",
    item: "321",
    maxLength: 4,
    name: "SET ID - GUARANTOR",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "GT1-2",
    item: "322",
    maxLength: 20,
    name: "GUARANTOR NUMBER",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "PN",
    id: "GT1-3",
    item: "323",
    maxLength: 48,
    name: "GUARANTOR NAME",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "PN",
    id: "GT1-4",
    item: "707",
    maxLength: 48,
    name: "GUARANTOR SPOUSE NAME",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "AD",
    id: "GT1-5",
    item: "324",
    maxLength: 106,
    name: "GUARANTOR ADDRESS",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TN",
    id: "GT1-6",
    item: "329",
    maxLength: 40,
    name: "GUARANTOR PH. NUM.- HOME",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TN",
    id: "GT1-7",
    item: "330",
    maxLength: 40,
    name: "GUARANTOR PH. NUM-BUSINESS",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DT",
    id: "GT1-8",
    item: "331",
    maxLength: 8,
    name: "GUARANTOR DATE OF BIRTH",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ID",
    id: "GT1-9",
    item: "332",
    maxLength: 1,
    name: "GUARANTOR SEX",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70001",
  },
  {
    datatype: "ID",
    id: "GT1-10",
    item: "333",
    maxLength: 2,
    name: "GUARANTOR TYPE",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70068",
  },
  {
    datatype: "ID",
    id: "GT1-11",
    item: "334",
    maxLength: 2,
    name: "GUARANTOR RELATIONSHIP",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70063",
  },
  {
    datatype: "ST",
    id: "GT1-12",
    item: "335",
    maxLength: 11,
    name: "GUARANTOR SSN",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DT",
    id: "GT1-13",
    item: "338",
    maxLength: 8,
    name: "GUARANTOR DATE - BEGIN",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DT",
    id: "GT1-14",
    item: "339",
    maxLength: 8,
    name: "GUARANTOR DATE - END",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "GT1-15",
    item: "340",
    maxLength: 2,
    name: "GUARANTOR PRIORITY",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ST",
    id: "GT1-16",
    item: "341",
    maxLength: 45,
    name: "GUARANTOR EMPLOYER NAME",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "AD",
    id: "GT1-17",
    item: "342",
    maxLength: 106,
    name: "GUARANTOR EMPLOYER ADDRESS",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "TN",
    id: "GT1-18",
    item: "347",
    maxLength: 40,
    name: "GUARANTOR EMPLOY PHONE #",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    id: "GT1-19",
    item: "391",
    maxLength: 20,
    name: "GUARANTOR EMPLOYEE ID NUM",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "GT1-20",
    item: "392",
    maxLength: 2,
    name: "GUARANTOR EMPLOYMENT STATUS",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70066",
  },
] as const;
