// Generated segment profile for IN1 (v2.1)

export const segmentId = "IN1";
export const fields = [
  {
    datatype: "SI",
    id: "IN1-1",
    item: "234",
    maxLength: 4,
    name: "SET ID - INSURANCE",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "IN1-2",
    item: "378",
    maxLength: 8,
    name: "INSURANCE PLAN ID",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70072",
  },
  {
    datatype: "ST",
    id: "IN1-3",
    item: "235",
    maxLength: 6,
    name: "INSURANCE COMPANY ID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "IN1-4",
    item: "236",
    maxLength: 45,
    name: "INSURANCE COMPANY NAME",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "AD",
    id: "IN1-5",
    item: "237",
    maxLength: 106,
    name: "INSURANCE COMPANY ADDRESS",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "PN",
    id: "IN1-6",
    item: "242",
    maxLength: 48,
    name: "INSURANCE CO. CONTACT PERS",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TN",
    id: "IN1-7",
    item: "243",
    maxLength: 40,
    name: "INSURANCE CO PHONE NUMBER",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "IN1-8",
    item: "248",
    maxLength: 12,
    name: "GROUP NUMBER",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "IN1-9",
    item: "249",
    maxLength: 35,
    name: "GROUP NAME",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "IN1-10",
    item: "250",
    maxLength: 12,
    name: "INSURED&apos;S GROUP EMP. ID",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "IN1-11",
    item: "251",
    maxLength: 45,
    name: "INSURED&apos;S GROUP EMP. NAME",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "DT",
    id: "IN1-12",
    item: "252",
    maxLength: 8,
    name: "PLAN EFFECTIVE DATE",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DT",
    id: "IN1-13",
    item: "253",
    maxLength: 8,
    name: "PLAN EXPIRATION DATE",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "IN1-14",
    item: "254",
    maxLength: 55,
    name: "AUTHORIZATION INFORMATION",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ID",
    id: "IN1-15",
    item: "260",
    maxLength: 2,
    name: "PLAN TYPE",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70086",
  },
  {
    datatype: "PN",
    id: "IN1-16",
    item: "261",
    maxLength: 48,
    name: "NAME OF INSURED",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "IN1-17",
    item: "262",
    maxLength: 2,
    name: "INSURED&apos;S RELATIONSHIP TO PATIENT",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70063",
  },
  {
    datatype: "DT",
    id: "IN1-18",
    item: "708",
    maxLength: 8,
    name: "INSURED&apos;S DATE OF BIRTH",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "AD",
    id: "IN1-19",
    item: "709",
    maxLength: 106,
    name: "INSURED&apos;S ADDRESS",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "IN1-20",
    item: "263",
    maxLength: 2,
    name: "ASSIGNMENT OF BENEFITS",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "ID",
    id: "IN1-21",
    item: "264",
    maxLength: 2,
    name: "COORDINATION OF BENEFITS",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "ST",
    id: "IN1-22",
    item: "265",
    maxLength: 2,
    name: "COORD OF BEN. PRIORITY",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ID",
    id: "IN1-23",
    item: "266",
    maxLength: 2,
    name: "NOTICE OF ADMISSION CODE",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70081",
  },
  {
    datatype: "DT",
    id: "IN1-24",
    item: "267",
    maxLength: 8,
    name: "NOTICE OF ADMISSION DATE",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ID",
    id: "IN1-25",
    item: "268",
    maxLength: 2,
    name: "RPT OF ELIGIBILITY CODE",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70094",
  },
  {
    datatype: "DT",
    id: "IN1-26",
    item: "269",
    maxLength: 8,
    name: "RPT OF ELIGIBILITY DATE",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "ID",
    id: "IN1-27",
    item: "270",
    maxLength: 2,
    name: "RELEASE INFORMATION CODE",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70093",
  },
  {
    datatype: "ST",
    id: "IN1-28",
    item: "271",
    maxLength: 15,
    name: "PRE-ADMIT CERT. (PAC)",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "DT",
    id: "IN1-29",
    item: "272",
    maxLength: 8,
    name: "VERIFICATION DATE",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CM",
    id: "IN1-30",
    item: "273",
    maxLength: 60,
    name: "VERIFICATION BY",
    repeatable: false,
    required: false,
    sequence: 30,
  },
  {
    datatype: "ID",
    id: "IN1-31",
    item: "277",
    maxLength: 2,
    name: "TYPE OF AGREEMENT CODE",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70098",
  },
  {
    datatype: "ID",
    id: "IN1-32",
    item: "278",
    maxLength: 2,
    name: "BILLING STATUS",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70022",
  },
  {
    datatype: "NM",
    id: "IN1-33",
    item: "280",
    maxLength: 4,
    name: "LIFETIME RESERVE DAYS",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "NM",
    id: "IN1-34",
    item: "281",
    maxLength: 4,
    name: "DELAY BEFORE L. R. DAY",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "ST",
    id: "IN1-35",
    item: "282",
    maxLength: 8,
    name: "COMPANY PLAN CODE",
    repeatable: false,
    required: false,
    sequence: 35,
    table: "HL70042",
  },
  {
    datatype: "ST",
    id: "IN1-36",
    item: "283",
    maxLength: 15,
    name: "POLICY NUMBER",
    repeatable: false,
    required: false,
    sequence: 36,
  },
  {
    datatype: "NM",
    id: "IN1-37",
    item: "284",
    maxLength: 12,
    name: "POLICY DEDUCTIBLE",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "NM",
    id: "IN1-38",
    item: "285",
    maxLength: 12,
    name: "POLICY LIMIT - AMOUNT",
    repeatable: false,
    required: false,
    sequence: 38,
  },
  {
    datatype: "NM",
    id: "IN1-39",
    item: "286",
    maxLength: 4,
    name: "POLICY LIMIT - DAYS",
    repeatable: false,
    required: false,
    sequence: 39,
  },
  {
    datatype: "NM",
    id: "IN1-40",
    item: "287",
    maxLength: 12,
    name: "ROOM RATE - SEMI-PRIVATE",
    repeatable: false,
    required: false,
    sequence: 40,
  },
  {
    datatype: "NM",
    id: "IN1-41",
    item: "288",
    maxLength: 12,
    name: "ROOM RATE - PRIVATE",
    repeatable: false,
    required: false,
    sequence: 41,
  },
  {
    datatype: "ID",
    id: "IN1-42",
    item: "710",
    maxLength: 1,
    name: "INSURED&apos;S EMPLOYMENT STATUS",
    repeatable: false,
    required: false,
    sequence: 42,
    table: "HL70066",
  },
  {
    datatype: "ID",
    id: "IN1-43",
    item: "711",
    maxLength: 1,
    name: "INSURED&apos;S SEX",
    repeatable: false,
    required: false,
    sequence: 43,
    table: "HL70001",
  },
  {
    datatype: "AD",
    id: "IN1-44",
    item: "713",
    maxLength: 106,
    name: "INSURED&apos;S EMPLOYER ADDRESS",
    repeatable: false,
    required: false,
    sequence: 44,
  },
] as const;
