// Generated segment profile for MSH (v2.1)

export const segmentId = "MSH";
export const fields = [
  {
    datatype: "ST",
    id: "MSH-1",
    item: "5",
    maxLength: 1,
    name: "FIELD SEPARATOR",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "MSH-2",
    item: "509",
    maxLength: 4,
    name: "ENCODING CHARACTERS",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "MSH-3",
    item: "6",
    maxLength: 15,
    name: "SENDING APPLICATION",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "MSH-4",
    item: "512",
    maxLength: 20,
    name: "SENDING FACILITY",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "MSH-5",
    item: "9",
    maxLength: 15,
    name: "RECEIVING APPLICATION",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "MSH-6",
    item: "513",
    maxLength: 30,
    name: "RECEIVING FACILITY",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "MSH-7",
    item: "10",
    maxLength: 19,
    name: "DATE/TIME OF MESSAGE",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "MSH-8",
    item: "8",
    maxLength: 40,
    name: "Security",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ID",
    id: "MSH-9",
    item: "12",
    maxLength: 7,
    name: "MESSAGE TYPE",
    repeatable: false,
    required: true,
    sequence: 9,
    table: "HL70076",
  },
  {
    datatype: "ST",
    id: "MSH-10",
    item: "13",
    maxLength: 20,
    name: "MESSAGE CONTROL ID",
    repeatable: false,
    required: true,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "MSH-11",
    item: "14",
    maxLength: 1,
    name: "PROCESSING ID",
    repeatable: false,
    required: true,
    sequence: 11,
    table: "HL70103",
  },
  {
    datatype: "NM",
    id: "MSH-12",
    item: "15",
    maxLength: 8,
    name: "VERSION ID",
    repeatable: false,
    required: true,
    sequence: 12,
    table: "HL70104",
  },
  {
    datatype: "NM",
    id: "MSH-13",
    item: "633",
    maxLength: 15,
    name: "SEQUENCE NUMBER",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "MSH-14",
    item: "699",
    maxLength: 180,
    name: "CONTINUATION POINTER",
    repeatable: false,
    required: false,
    sequence: 14,
  },
] as const;
