// Generated segment profile for NSC (v2.1)

export const segmentId = "NSC";
export const fields = [
  {
    datatype: "ID",
    id: "NSC-1",
    item: "758",
    maxLength: 4,
    name: "NETWORK CHANGE TYPE",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "NSC-2",
    item: "759",
    maxLength: 30,
    name: "CURRENT CPU",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "NSC-3",
    item: "760",
    maxLength: 30,
    name: "CURRENT FILESERVER",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "NSC-4",
    item: "761",
    maxLength: 30,
    name: "CURRENT APPLICATION",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "NSC-5",
    item: "762",
    maxLength: 30,
    name: "CURRENT FACILITY",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "NSC-6",
    item: "763",
    maxLength: 30,
    name: "NEW CPU",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "NSC-7",
    item: "764",
    maxLength: 30,
    name: "NEW FILESERVER",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "NSC-8",
    item: "765",
    maxLength: 30,
    name: "NEW APPLICATION",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "NSC-9",
    item: "766",
    maxLength: 30,
    name: "NEW FACILITY",
    repeatable: false,
    required: false,
    sequence: 9,
  },
] as const;
