// Generated segment profile for NST (v2.1)

export const segmentId = "NST";
export const fields = [
  {
    sequence: 1,
    id: "NST-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    name: "STATISTICS AVAILABLE",
    item: "743",
  },
  {
    sequence: 2,
    id: "NST-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "SOURCE IDENTIFIER",
    item: "744",
  },
  {
    sequence: 3,
    id: "NST-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 3,
    name: "SOURCE TYPE",
    item: "745",
  },
  {
    sequence: 4,
    id: "NST-4",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 19,
    name: "STATISTICS START",
    item: "746",
  },
  {
    sequence: 5,
    id: "NST-5",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 19,
    name: "STATISTICS END",
    item: "747",
  },
  {
    sequence: 6,
    id: "NST-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "RECEIVE CHARACTER COUNT",
    item: "748",
  },
  {
    sequence: 7,
    id: "NST-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "SEND CHARACTER COUNT",
    item: "749",
  },
  {
    sequence: 8,
    id: "NST-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "MESSAGES RECEIVED",
    item: "750",
  },
  {
    sequence: 9,
    id: "NST-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "MESSAGES SENT",
    item: "751",
  },
  {
    sequence: 10,
    id: "NST-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "CHECKSUM ERRORS RECEIVED",
    item: "752",
  },
  {
    sequence: 11,
    id: "NST-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "LENGTH ERRORS RECEIVED",
    item: "753",
  },
  {
    sequence: 12,
    id: "NST-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "OTHER ERRORS RECEIVED",
    item: "754",
  },
  {
    sequence: 13,
    id: "NST-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "CONNECT TIMEOUTS",
    item: "755",
  },
  {
    sequence: 14,
    id: "NST-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "RECEIVE TIMEOUTS",
    item: "756",
  },
  {
    sequence: 15,
    id: "NST-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "NETWORK ERRORS",
    item: "757",
  },
] as const;
