// Generated segment profile for OBR (v2.1)

export const segmentId = "OBR";
export const fields = [
  {
    datatype: "SI",
    id: "OBR-1",
    item: "520",
    maxLength: 4,
    name: "SET ID - OBSERVATION REQUEST",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CM",
    id: "OBR-2",
    item: "732",
    maxLength: 75,
    name: "PLACER ORDER #",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CM",
    id: "OBR-3",
    item: "733",
    maxLength: 75,
    name: "FILLER ORDER #",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "OBR-4",
    item: "523",
    maxLength: 200,
    name: "UNIVERSAL SERVICE IDENT.",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "OBR-5",
    item: "524",
    maxLength: 2,
    name: "PRIORITY",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TS",
    id: "OBR-6",
    item: "529",
    maxLength: 19,
    name: "REQUESTED DATE-TIME",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "OBR-7",
    item: "530",
    maxLength: 19,
    name: "OBSERVATION DATE/TIME",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "TS",
    id: "OBR-8",
    item: "531",
    maxLength: 19,
    name: "OBSERVATION END DATE/TIME",
    repeatable: false,
    required: true,
    sequence: 8,
  },
  {
    datatype: "CQ",
    id: "OBR-9",
    item: "532",
    maxLength: 20,
    name: "COLLECTION VOLUME",
    repeatable: false,
    required: true,
    sequence: 9,
    table: "HL70036",
  },
  {
    datatype: "CN",
    id: "OBR-10",
    item: "533",
    maxLength: 60,
    name: "COLLECTOR IDENTIFIER",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "OBR-11",
    item: "534",
    maxLength: 1,
    name: "SPECIMEN ACTION CODE",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70065",
  },
  {
    datatype: "CM",
    id: "OBR-12",
    item: "535",
    maxLength: 60,
    name: "DANGER CODE",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70047",
  },
  {
    datatype: "ST",
    id: "OBR-13",
    item: "536",
    maxLength: 300,
    name: "RELEVANT CLINICAL INFO.",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "TS",
    id: "OBR-14",
    item: "537",
    maxLength: 19,
    name: "SPECIMEN RECEIVED DATE/TIME",
    repeatable: false,
    required: true,
    sequence: 14,
  },
  {
    datatype: "CM",
    id: "OBR-15",
    item: "538",
    maxLength: 300,
    name: "SPECIMEN SOURCE",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70070",
  },
  {
    datatype: "CN",
    id: "OBR-16",
    item: "539",
    maxLength: 60,
    name: "ORDERING PROVIDER",
    repeatable: true,
    required: false,
    sequence: 16,
    table: "HL70010",
  },
  {
    datatype: "TN",
    id: "OBR-17",
    item: "540",
    maxLength: 40,
    name: "ORDER CALL-BACK PHONE NUM",
    repeatable: true,
    required: false,
    sequence: 17,
  },
  {
    datatype: "ST",
    id: "OBR-18",
    item: "541",
    maxLength: 60,
    name: "PLACERS FIELD #1",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    id: "OBR-19",
    item: "542",
    maxLength: 60,
    name: "PLACERS FIELD #2",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ST",
    id: "OBR-20",
    item: "543",
    maxLength: 60,
    name: "FILLERS FIELD #1",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "ST",
    id: "OBR-21",
    item: "544",
    maxLength: 60,
    name: "FILLERS FIELD #2",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "TS",
    id: "OBR-22",
    item: "546",
    maxLength: 19,
    name: "RESULTS RPT/STATUS CHNG - DATE/T",
    repeatable: false,
    required: true,
    sequence: 22,
  },
  {
    datatype: "CM",
    id: "OBR-23",
    item: "547",
    maxLength: 40,
    name: "CHARGE TO PRACTICE",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ID",
    id: "OBR-24",
    item: "548",
    maxLength: 10,
    name: "DIAGNOSTIC SERV SECT ID",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70074",
  },
  {
    datatype: "ID",
    id: "OBR-25",
    item: "734",
    maxLength: 1,
    name: "RESULT STATUS",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70123",
  },
  {
    datatype: "CE",
    id: "OBR-26",
    item: "550",
    maxLength: 200,
    name: "LINKED RESULTS",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CM",
    id: "OBR-27",
    item: "735",
    maxLength: 200,
    name: "QUANTITY/TIMING",
    repeatable: true,
    required: false,
    sequence: 27,
  },
  {
    datatype: "CN",
    id: "OBR-28",
    item: "551",
    maxLength: 80,
    name: "RESULT COPIES TO",
    repeatable: true,
    required: false,
    sequence: 28,
  },
  {
    datatype: "CM",
    id: "OBR-29",
    item: "737",
    maxLength: 150,
    name: "PARENT ACCESSION #",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "ID",
    id: "OBR-30",
    item: "625",
    maxLength: 20,
    name: "TRANSPORTATION MODE",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70124",
  },
  {
    datatype: "CE",
    id: "OBR-31",
    item: "626",
    maxLength: 300,
    name: "REASON FOR STUDY",
    repeatable: true,
    required: false,
    sequence: 31,
  },
  {
    datatype: "CN",
    id: "OBR-32",
    item: "627",
    maxLength: 60,
    name: "PRINCIPAL RESULT INTERPRETER",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "CN",
    id: "OBR-33",
    item: "628",
    maxLength: 60,
    name: "ASSISTANT RESULT INTERPRETER",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "CN",
    id: "OBR-34",
    item: "630",
    maxLength: 60,
    name: "TECHNICIAN",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "CN",
    id: "OBR-35",
    item: "629",
    maxLength: 60,
    name: "TRANSCRIPTIONIST",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "TS",
    id: "OBR-36",
    item: "736",
    maxLength: 19,
    name: "SCHEDULED - DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 36,
  },
] as const;
