// Generated segment profile for PID (v2.1)

export const segmentId = "PID";
export const fields = [
  {
    datatype: "SI",
    id: "PID-1",
    item: "572",
    maxLength: 4,
    name: "SET ID - PATIENT ID",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CK",
    id: "PID-2",
    item: "581",
    maxLength: 16,
    name: "PATIENT ID EXTERNAL (EXTERNAL ID)",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70061",
  },
  {
    datatype: "CK",
    id: "PID-3",
    item: "34",
    maxLength: 16,
    name: "PATIENT ID INTERNAL (INTERNAL ID)",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70061",
  },
  {
    datatype: "ST",
    id: "PID-4",
    item: "38",
    maxLength: 12,
    name: "ALTERNATE PATIENT ID",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "PN",
    id: "PID-5",
    item: "41",
    maxLength: 48,
    name: "PATIENT NAME",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "PID-6",
    item: "582",
    maxLength: 30,
    name: "MOTHER&apos;S MAIDEN NAME",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DT",
    id: "PID-7",
    item: "43",
    maxLength: 8,
    name: "DATE OF BIRTH",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "PID-8",
    item: "42",
    maxLength: 1,
    name: "SEX",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70001",
  },
  {
    datatype: "PN",
    id: "PID-9",
    item: "597",
    maxLength: 48,
    name: "PATIENT ALIAS",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "PID-10",
    item: "44",
    maxLength: 1,
    name: "ETHNIC GROUP",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70005",
  },
  {
    datatype: "AD",
    id: "PID-11",
    item: "20",
    maxLength: 106,
    name: "PATIENT ADDRESS",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "PID-12",
    item: "26",
    maxLength: 4,
    name: "COUNTY CODE",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "TN",
    id: "PID-13",
    item: "49",
    maxLength: 40,
    name: "PHONE NUMBER - HOME",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "TN",
    id: "PID-14",
    item: "50",
    maxLength: 40,
    name: "PHONE NUMBER - BUSINESS",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "PID-15",
    item: "464",
    maxLength: 25,
    name: "LANGUAGE - PATIENT",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "PID-16",
    item: "46",
    maxLength: 1,
    name: "MARITAL STATUS",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70002",
  },
  {
    datatype: "ID",
    id: "PID-17",
    item: "45",
    maxLength: 3,
    name: "RELIGION",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70006",
  },
  {
    datatype: "CK",
    id: "PID-18",
    item: "35",
    maxLength: 20,
    name: "PATIENT ACCOUNT NUMBER",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70061",
  },
  {
    datatype: "ST",
    id: "PID-19",
    item: "457",
    maxLength: 16,
    name: "SSN NUMBER - PATIENT",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CM",
    id: "PID-20",
    item: "453",
    maxLength: 25,
    name: "DRIVER&apos;S LIC NUM - PATIENT",
    repeatable: false,
    required: false,
    sequence: 20,
  },
] as const;
