// Generated segment profile for PR1 (v2.1)

export const segmentId = "PR1";
export const fields = [
  {
    datatype: "SI",
    id: "PR1-1",
    item: "304",
    maxLength: 4,
    name: "SET ID - PROCEDURE",
    repeatable: true,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "PR1-2",
    item: "393",
    maxLength: 2,
    name: "PROCEDURE CODING METHOD.",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70089",
  },
  {
    datatype: "ID",
    id: "PR1-3",
    item: "305",
    maxLength: 10,
    name: "PROCEDURE CODE",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70088",
  },
  {
    datatype: "ST",
    id: "PR1-4",
    item: "306",
    maxLength: 40,
    name: "PROCEDURE DESCRIPTION",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "PR1-5",
    item: "307",
    maxLength: 19,
    name: "PROCEDURE DATE/TIME",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "PR1-6",
    item: "309",
    maxLength: 2,
    name: "PROCEDURE TYPE",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70090",
  },
  {
    datatype: "NM",
    id: "PR1-7",
    item: "310",
    maxLength: 4,
    name: "PROCEDURE MINUTES",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CN",
    id: "PR1-8",
    item: "311",
    maxLength: 60,
    name: "ANESTHESIOLOGIST",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70010",
  },
  {
    datatype: "ID",
    id: "PR1-9",
    item: "313",
    maxLength: 2,
    name: "ANESTHESIA CODE",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70019",
  },
  {
    datatype: "NM",
    id: "PR1-10",
    item: "314",
    maxLength: 4,
    name: "ANESTHESIA MINUTES",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CN",
    id: "PR1-11",
    item: "315",
    maxLength: 60,
    name: "SURGEON",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70010",
  },
  {
    datatype: "CN",
    id: "PR1-12",
    item: "318",
    maxLength: 60,
    name: "RESIDENT CODE",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70010",
  },
  {
    datatype: "ID",
    id: "PR1-13",
    item: "317",
    maxLength: 2,
    name: "CONSENT CODE",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70059",
  },
] as const;
