// Generated segment profile for QRD (v2.1)

export const segmentId = "QRD";
export const fields = [
  {
    sequence: 1,
    id: "QRD-1",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 19,
    name: "QUERY DATE/TIME",
    item: "156",
  },
  {
    sequence: 2,
    id: "QRD-2",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70106",
    name: "QUERY FORMAT CODE",
    item: "158",
  },
  {
    sequence: 3,
    id: "QRD-3",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70091",
    name: "QUERY PRIORITY",
    item: "159",
  },
  {
    sequence: 4,
    id: "QRD-4",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 10,
    name: "QUERY ID",
    item: "160",
  },
  {
    sequence: 5,
    id: "QRD-5",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70107",
    name: "DEFERRED RESPONSE TYPE",
    item: "161",
  },
  {
    sequence: 6,
    id: "QRD-6",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 19,
    name: "DEFERRED RESPONSE DATE/TIME",
    item: "162",
  },
  {
    sequence: 7,
    id: "QRD-7",
    required: true,
    repeatable: false,
    datatype: "CQ",
    maxLength: 5,
    table: "HL70126",
    name: "QUANTITY LIMITED REQUEST",
    item: "164",
  },
  {
    sequence: 8,
    id: "QRD-8",
    required: true,
    repeatable: true,
    datatype: "ST",
    maxLength: 20,
    name: "WHO SUBJECT FILTER",
    item: "168",
  },
  {
    sequence: 9,
    id: "QRD-9",
    required: true,
    repeatable: true,
    datatype: "ID",
    maxLength: 3,
    table: "HL70048",
    name: "WHAT SUBJECT FILTER",
    item: "169",
  },
  {
    sequence: 10,
    id: "QRD-10",
    required: true,
    repeatable: true,
    datatype: "ST",
    maxLength: 20,
    name: "WHAT DEPARTMENT DATA CODE",
    item: "170",
  },
  {
    sequence: 11,
    id: "QRD-11",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 20,
    name: "WHAT DATA CODE VALUE QUAL.",
    item: "171",
  },
  {
    sequence: 12,
    id: "QRD-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70108",
    name: "QUERY RESULTS LEVEL",
    item: "701",
  },
] as const;
