// Generated segment profile for QRF (v2.1)

export const segmentId = "QRF";
export const fields = [
  {
    datatype: "ST",
    id: "QRF-1",
    item: "173",
    maxLength: 20,
    name: "WHERE SUBJECT FILTER",
    repeatable: true,
    required: true,
    sequence: 1,
  },
  {
    datatype: "TS",
    id: "QRF-2",
    item: "174",
    maxLength: 19,
    name: "WHEN DATA START DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "QRF-3",
    item: "176",
    maxLength: 19,
    name: "WHEN DATA END DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "QRF-4",
    item: "178",
    maxLength: 20,
    name: "WHAT USER QUALIFIER",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "QRF-5",
    item: "179",
    maxLength: 20,
    name: "OTHER QRY SUBJECT FILTER",
    repeatable: true,
    required: false,
    sequence: 5,
  },
] as const;
