// Generated segment profile for RX1 (v2.1)

export const segmentId = "RX1";
export const fields = [
  {
    datatype: "ST",
    id: "RX1-1",
    item: "770",
    name: "UNUSED",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "RX1-2",
    item: "771",
    name: "UNUSED",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "RX1-3",
    item: "129",
    maxLength: 8,
    name: "ROUTE",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70033",
  },
  {
    datatype: "ST",
    id: "RX1-4",
    item: "130",
    maxLength: 20,
    name: "SITE ADMINISTERED",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70034",
  },
  {
    datatype: "CQ",
    id: "RX1-5",
    item: "131",
    maxLength: 10,
    name: "IV SOLUTION RATE",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CQ",
    id: "RX1-6",
    item: "133",
    maxLength: 14,
    name: "DRUG STRENGTH",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "RX1-7",
    item: "137",
    maxLength: 10,
    name: "FINAL CONCENTRATION",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "RX1-8",
    item: "138",
    maxLength: 10,
    name: "FINAL VOLUME IN ML.",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CM",
    id: "RX1-9",
    item: "135",
    maxLength: 10,
    name: "DRUG DOSE",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "RX1-10",
    item: "139",
    maxLength: 1,
    name: "DRUG ROLE",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "RX1-11",
    item: "469",
    maxLength: 3,
    name: "PRESCRIPTION SEQUENCE #",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CQ",
    id: "RX1-12",
    item: "470",
    maxLength: 4,
    name: "QUANTITY DISPENSED",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "RX1-13",
    item: "772",
    name: "UNUSED",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CE",
    id: "RX1-14",
    item: "473",
    maxLength: 5,
    name: "DRUG ID",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70057",
  },
  {
    datatype: "ID",
    id: "RX1-15",
    item: "474",
    maxLength: 5,
    name: "COMPONENT DRUG IDS",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "RX1-16",
    item: "479",
    maxLength: 2,
    name: "PRESCRIPTION TYPE",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "RX1-17",
    item: "480",
    maxLength: 1,
    name: "SUBSTITUTION STATUS",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "ID",
    id: "RX1-18",
    item: "588",
    maxLength: 2,
    name: "RX ORDER STATUS",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70038",
  },
  {
    datatype: "NM",
    id: "RX1-19",
    item: "481",
    maxLength: 3,
    name: "NUMBER OF REFILLS",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ST",
    id: "RX1-20",
    item: "773",
    name: "UNUSED",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "NM",
    id: "RX1-21",
    item: "482",
    maxLength: 3,
    name: "REFILLS REMAINING",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "ID",
    id: "RX1-22",
    item: "619",
    maxLength: 5,
    name: "DEA CLASS",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "NM",
    id: "RX1-23",
    item: "620",
    maxLength: 10,
    name: "ORDERING MD&apos;S DEA NUMBER",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ST",
    id: "RX1-24",
    item: "774",
    name: "UNUSED",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "TS",
    id: "RX1-25",
    item: "483",
    maxLength: 19,
    name: "LAST REFILL DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "ST",
    id: "RX1-26",
    item: "596",
    maxLength: 20,
    name: "RX NUMBER",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "ID",
    id: "RX1-27",
    item: "621",
    maxLength: 5,
    name: "PRN STATUS",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "TX",
    id: "RX1-28",
    item: "484",
    maxLength: 80,
    name: "PHARMACY INSTRUCTIONS",
    repeatable: true,
    required: false,
    sequence: 28,
  },
  {
    datatype: "TX",
    id: "RX1-29",
    item: "489",
    maxLength: 80,
    name: "PATIENT INSTRUCTIONS",
    repeatable: true,
    required: false,
    sequence: 29,
  },
  {
    datatype: "TX",
    id: "RX1-30",
    item: "618",
    maxLength: 500,
    name: "INSTRUCTIONS (SIG)",
    repeatable: true,
    required: false,
    sequence: 30,
  },
] as const;
