// Generated segment profile for URD (v2.1)

export const segmentId = "URD";
export const fields = [
  {
    datatype: "TS",
    id: "URD-1",
    item: "600",
    maxLength: 19,
    name: "R/U DATE/TIME",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "URD-2",
    item: "601",
    maxLength: 1,
    name: "REPORT PRIORITY",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70109",
  },
  {
    datatype: "ST",
    id: "URD-3",
    item: "602",
    maxLength: 20,
    name: "R/U WHO SUBJECT DEFINITION",
    repeatable: true,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ID",
    id: "URD-4",
    item: "603",
    maxLength: 3,
    name: "R/U WHAT SUBJECT DEFINITION",
    repeatable: true,
    required: false,
    sequence: 4,
    table: "HL70048",
  },
  {
    datatype: "ST",
    id: "URD-5",
    item: "605",
    maxLength: 20,
    name: "R/U WHAT DEPARTMENT CODE",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "URD-6",
    item: "607",
    maxLength: 20,
    name: "R/U DISPLAY/PRINT LOCATIONS",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "URD-7",
    item: "702",
    maxLength: 1,
    name: "R/U RESULTS LEVEL",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70108",
  },
] as const;
