// Generated segment profile for LDP (v2.8.2)

export const segmentId = "LDP";
export const fields = [
  {
    sequence: 1,
    id: "LDP-1",
    required: true,
    repeatable: false,
    datatype: "PL",
    name: "Primary Key Value - LDP",
    item: "963",
  },
  {
    sequence: 2,
    id: "LDP-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70264",
    name: "Location Department",
    item: "964",
  },
  {
    sequence: 3,
    id: "LDP-3",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70069",
    name: "Location Service",
    item: "965",
  },
  {
    sequence: 4,
    id: "LDP-4",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70265",
    name: "Specialty Type",
    item: "966",
  },
  {
    sequence: 5,
    id: "LDP-5",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70004",
    name: "Valid Patient Classes",
    item: "967",
  },
  {
    sequence: 6,
    id: "LDP-6",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70183",
    name: "Active/Inactive Flag",
    item: "675",
  },
  {
    sequence: 7,
    id: "LDP-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Activation Date - LDP",
    item: "969",
  },
  {
    sequence: 8,
    id: "LDP-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Inactivation Date - LDP",
    item: "970",
  },
  {
    sequence: 9,
    id: "LDP-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Inactivated Reason",
    item: "971",
  },
  {
    sequence: 10,
    id: "LDP-10",
    required: false,
    repeatable: true,
    datatype: "VH",
    table: "HL70267",
    name: "Visiting Hours",
    item: "976",
  },
  {
    sequence: 11,
    id: "LDP-11",
    required: false,
    repeatable: false,
    datatype: "XTN",
    name: "Contact Phone",
    item: "978",
  },
  {
    sequence: 12,
    id: "LDP-12",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70462",
    name: "Location Cost Center",
    item: "1584",
  },
] as const;
