// Generated segment profile for MFE (v2.8.2)

export const segmentId = "MFE";
export const fields = [
  {
    sequence: 1,
    id: "MFE-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 3,
    table: "HL70180",
    name: "Record-Level Event Code",
    item: "664",
  },
  {
    sequence: 2,
    id: "MFE-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "MFN Control ID",
    item: "665",
  },
  {
    sequence: 3,
    id: "MFE-3",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Effective Date/Time",
    item: "662",
  },
  {
    sequence: 4,
    id: "MFE-4",
    required: true,
    repeatable: true,
    datatype: "varies",
    name: "Primary Key Value - MFE",
    item: "667",
  },
  {
    sequence: 5,
    id: "MFE-5",
    required: true,
    repeatable: true,
    datatype: "ID",
    maxLength: 3,
    table: "HL70355",
    name: "Primary Key Value Type",
    item: "1319",
  },
  {
    sequence: 6,
    id: "MFE-6",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Entered Date/Time",
    item: "661",
  },
  {
    sequence: 7,
    id: "MFE-7",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Entered By",
    item: "224",
  },
] as const;
