// Generated segment profile for NTE (v2.8.2)

export const segmentId = "NTE";
export const fields = [
  {
    sequence: 1,
    id: "NTE-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    name: "Set ID - NTE",
    item: "96",
  },
  {
    sequence: 2,
    id: "NTE-2",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70105",
    name: "Source of Comment",
    item: "97",
  },
  {
    sequence: 3,
    id: "NTE-3",
    required: false,
    repeatable: true,
    datatype: "FT",
    name: "Comment",
    item: "98",
  },
  {
    sequence: 4,
    id: "NTE-4",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70364",
    name: "Comment Type",
    item: "1318",
  },
  {
    sequence: 5,
    id: "NTE-5",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Entered By",
    item: "224",
  },
  {
    sequence: 6,
    id: "NTE-6",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Entered Date/Time",
    item: "661",
  },
  {
    sequence: 7,
    id: "NTE-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Effective Start Date",
    item: "1004",
  },
  {
    sequence: 8,
    id: "NTE-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Expiration Date",
    item: "2185",
  },
] as const;
