// Generated segment profile for PR1 (v2.8.2)

export const segmentId = "PR1";
export const fields = [
  {
    sequence: 1,
    id: "PR1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - PR1",
    item: "391",
  },
  {
    sequence: 2,
    id: "PR1-3",
    required: true,
    repeatable: false,
    datatype: "CNE",
    table: "HL70088",
    name: "Procedure Code",
    item: "393",
  },
  {
    sequence: 3,
    id: "PR1-5",
    required: true,
    repeatable: false,
    datatype: "DTM",
    name: "Procedure Date/Time",
    item: "395",
  },
  {
    sequence: 4,
    id: "PR1-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70230",
    name: "Procedure Functional Type",
    item: "396",
  },
  {
    sequence: 5,
    id: "PR1-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Procedure Minutes",
    item: "397",
  },
  {
    sequence: 6,
    id: "PR1-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70019",
    name: "Anesthesia Code",
    item: "399",
  },
  {
    sequence: 7,
    id: "PR1-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Anesthesia Minutes",
    item: "400",
  },
  {
    sequence: 8,
    id: "PR1-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70059",
    name: "Consent Code",
    item: "403",
  },
  {
    sequence: 9,
    id: "PR1-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    table: "HL70418",
    name: "Procedure Priority",
    item: "404",
  },
  {
    sequence: 10,
    id: "PR1-15",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70051",
    name: "Associated Diagnosis Code",
    item: "772",
  },
  {
    sequence: 11,
    id: "PR1-16",
    required: false,
    repeatable: true,
    datatype: "CNE",
    table: "HL70340",
    name: "Procedure Code Modifier",
    item: "1316",
  },
  {
    sequence: 12,
    id: "PR1-17",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70416",
    name: "Procedure DRG Type",
    item: "1501",
  },
  {
    sequence: 13,
    id: "PR1-18",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70417",
    name: "Tissue Type Code",
    item: "1502",
  },
  {
    sequence: 14,
    id: "PR1-19",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Procedure Identifier",
    item: "1848",
  },
  {
    sequence: 15,
    id: "PR1-20",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70206",
    name: "Procedure Action Code",
    item: "1849",
  },
  {
    sequence: 16,
    id: "PR1-21",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70761",
    name: "DRG Procedure Determination Status",
    item: "2177",
  },
  {
    sequence: 17,
    id: "PR1-22",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70763",
    name: "DRG Procedure Relevance",
    item: "2178",
  },
  {
    sequence: 18,
    id: "PR1-23",
    required: false,
    repeatable: true,
    datatype: "PL",
    name: "Treating Organizational Unit",
    item: "2371",
  },
  {
    sequence: 19,
    id: "PR1-24",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Respiratory Within Surgery",
    item: "2372",
  },
  {
    sequence: 20,
    id: "PR1-25",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Parent Procedure ID",
    item: "2373",
  },
] as const;
