// Generated segment profile for PRA (v2.8.2)

export const segmentId = "PRA";
export const fields = [
  {
    sequence: 1,
    id: "PRA-1",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Primary Key Value - PRA",
    item: "685",
  },
  {
    sequence: 2,
    id: "PRA-2",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70358",
    name: "Practitioner Group",
    item: "686",
  },
  {
    sequence: 3,
    id: "PRA-3",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70186",
    name: "Practitioner Category",
    item: "687",
  },
  {
    sequence: 4,
    id: "PRA-4",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70187",
    name: "Provider Billing",
    item: "688",
  },
  {
    sequence: 5,
    id: "PRA-5",
    required: false,
    repeatable: true,
    datatype: "SPD",
    name: "Specialty",
    item: "689",
  },
  {
    sequence: 6,
    id: "PRA-6",
    required: false,
    repeatable: true,
    datatype: "PLN",
    name: "Practitioner ID Numbers",
    item: "690",
  },
  {
    sequence: 7,
    id: "PRA-7",
    required: false,
    repeatable: true,
    datatype: "PIP",
    name: "Privileges",
    item: "691",
  },
  {
    sequence: 8,
    id: "PRA-8",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Date Entered Practice",
    item: "1296",
  },
  {
    sequence: 9,
    id: "PRA-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70537",
    name: "Institution",
    item: "1613",
  },
  {
    sequence: 10,
    id: "PRA-10",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Date Left Practice",
    item: "1348",
  },
  {
    sequence: 11,
    id: "PRA-11",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70401",
    name: "Government Reimbursement Billing Eligibility",
    item: "1388",
  },
  {
    sequence: 12,
    id: "PRA-12",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - PRA",
    item: "1616",
  },
] as const;
