// Generated table profile for 0003 (v2.2)

export const id = "0003";
export const description = "EVENT TYPE CODE";
export const type = "hl7";
export const codes = [
  { description: "Admit a patient", name: "A01" },
  { description: "Transfer a patient", name: "A02" },
  { description: "Discharge a patient", name: "A03" },
  { description: "Register a patient", name: "A04" },
  { description: "Pre-admit a Patient", name: "A05" },
  { description: "Transfer an outpatient to inpatient", name: "A06" },
  { description: "Transfer an inpatient to outpatient", name: "A07" },
  { description: "Update patient information", name: "A08" },
  { description: "Patient departing", name: "A09" },
  { description: "Patient arriving", name: "A10" },
  { description: "Cancel admit", name: "A11" },
  { description: "Cancel transfer", name: "A12" },
  { description: "Cancel discharge", name: "A13" },
  { description: "Pending admit", name: "A14" },
  { description: "Pending transfer", name: "A15" },
  { description: "Pending discharge", name: "A16" },
  { description: "Swap patients", name: "A17" },
  { description: "Merge patient information", name: "A18" },
  { description: "Patient query", name: "A19" },
  { description: "Bed Status Update", name: "A20" },
  { description: "Leave of absence - out (leaving)", name: "A21" },
  { description: "Leave of absence - in (returning)", name: "A22" },
  { description: "Delete a patient record", name: "A23" },
  { description: "Link patient information", name: "A24" },
  { description: "Cancel pending discharge", name: "A25" },
  { description: "Cancel pending transfer", name: "A26" },
  { description: "Cancel pending admit", name: "A27" },
  { description: "Add person information", name: "A28" },
  { description: "Delete person information", name: "A29" },
  { description: "Merge Patient information", name: "A30" },
  { description: "Update person information", name: "A31" },
  { description: "Cancel patient arriving", name: "A32" },
  { description: "Cancel patient departing", name: "A33" },
  { description: "Merge patient information - patient ID only", name: "A34" },
  {
    description: "Merge patient information - account number only",
    name: "A35",
  },
  {
    description: "Merge patient information - patient ID and account number",
    name: "A36",
  },
  { description: "Unlink patient information", name: "A37" },
  {
    description:
      "Master file not otherwise specified (for backwards compatibility only)",
    name: "M01",
  },
  { description: "Master file - Staff Practioner", name: "M02" },
  { description: "Master file - test / observation", name: "M03" },
  { description: "Order message", name: "O01" },
  { description: "Order response", name: "O02" },
  { description: "Add and Update Patient Accounts", name: "P01" },
  { description: "Purge Patient Accounts", name: "P02" },
  { description: "Post detail financial transaction", name: "P03" },
  {
    description: "Generate bill and accounts receivable statements",
    name: "P04",
  },
  { description: "Immediate access", name: "Q01" },
  { description: "Deferred access", name: "Q02" },
  { description: "Deferred response to query", name: "Q03" },
  { description: "Unsolicited display update", name: "Q05" },
  {
    description: "Unsolicited transmission of requested observation",
    name: "R01",
  },
  { description: "Query for results of observation", name: "R02" },
  {
    description: "Display-oriented results (query / unsolicited update)",
    name: "R03",
  },
  {
    description: "Response to query / transmission of requested observation",
    name: "R04",
  },
] as const;
