// Generated table profile for 0074 (v2.2)

export const id = "0074";
export const description = "DIAGNOSTIC SERVICE SECTION ID";
export const type = "hl7";
export const codes = [
  { description: "Audiology", name: "AU" },
  { description: "Blood gases", name: "BG" },
  { description: "Blood bank", name: "BLB" },
  { description: "Chemistry", name: "CH" },
  { description: "Cytopathology", name: "CP" },
  { description: "CAT scan", name: "CT" },
  { description: "Cardiac catheterization", name: "CTH" },
  { description: "Cardiac Ultrasound", name: "CUS" },
  { description: "Electrocardiac (e.g., EKG, EEC, Holter)", name: "EC" },
  { description: "Electroneuro (EEG, EMG)", name: "EN" },
  { description: "Hematology", name: "HM" },
  { description: "Immunology", name: "IMM" },
  { description: "Microbiology", name: "MB" },
  { description: "Mycobacteriology", name: "MCB" },
  { description: "Mycology", name: "MYC" },
  { description: "Nuclear magnetic resonance", name: "NMR" },
  { description: "Nuclear medicine scan", name: "NMS" },
  { description: "Nursing service measures", name: "NRS" },
  { description: "Outside Lab", name: "OSL" },
  { description: "Occupational therapy", name: "OT" },
  { description: "Other", name: "OTH" },
  { description: "OB Ultrasound", name: "OUS" },
  { description: "Pulmonary function", name: "PF" },
  { description: "Pharmacy", name: "PHR" },
  { description: "Physician (Hx, Dx, admission note, etc.)", name: "PHY" },
  { description: "Physical therapy", name: "PT" },
  { description: "Respiratory care (therapy)", name: "RC" },
  { description: "Radiation therapy", name: "RT" },
  { description: "Radiology ultrasound", name: "RUS" },
  { description: "Radiograph", name: "RX" },
  { description: "Surgical Pathology", name: "SP" },
  { description: "Serology", name: "SR" },
  { description: "Toxicology", name: "TX" },
  { description: "Virology", name: "VR" },
  { description: "Vascular Ultrasound", name: "VUS" },
  { description: "Cineradiograph", name: "XRC" },
] as const;
