// Generated table profile for 0076 (v2.2)

export const id = "0076";
export const description = "MESSAGE TYPE";
export const type = "hl7";
export const codes = [
  { description: "General acknowledgement message", name: "ACK" },
  { description: "ADT response", name: "ADR" },
  { description: "ADT message", name: "ADT" },
  { description: "Ancillary report (display)", name: "ARD" },
  { description: "Add / change billing account", name: "BAR" },
  { description: "Detail financial transaction", name: "DFT" },
  { description: "Display response", name: "DSR" },
  { description: "Delayed acknowledgement", name: "MCF" },
  {
    description: "Master files delayed application acknowledgement",
    name: "MFD",
  },
  { description: "Master file application acknowledgement", name: "MFK" },
  { description: "Master files notification", name: "MFN" },
  { description: "Master files response", name: "MFR" },
  { description: "Network management data", name: "NMD" },
  { description: "Network management query", name: "NMQ" },
  { description: "Network management response", name: "NMR" },
  { description: "Observational result (record response)", name: "ORF" },
  { description: "Order message", name: "ORM" },
  { description: "Order acknowledgement message", name: "ORR" },
  { description: "Observational result (unsolicited)", name: "ORU" },
  { description: "Order status query", name: "OSQ" },
  { description: "Query", name: "QRY" },
  { description: "Pharmacy administration information", name: "RAR" },
  { description: "Pharmacy administration message", name: "RAS" },
  { description: "Pharmacy encoded order message", name: "RDE" },
  { description: "Pharmacy dispense information", name: "RDR" },
  { description: "Pharmacy dispense message", name: "RDS" },
  { description: "Pharmacy encoded order information", name: "RER" },
  { description: "Pharmacy dose information", name: "RGR" },
  { description: "Pharmacy give message", name: "RGV" },
  { description: "Pharmacy prescription order response", name: "ROR" },
  { description: "Pharmacy administration acknowledgment", name: "RRA" },
  { description: "Pharmacy dispense acknowledgment", name: "RRD" },
  { description: "Pharmacy encoded order acknowledgment", name: "RRE" },
  { description: "Pharmacy give acknowledgment", name: "RRG" },
  { description: "Unsolicited display message", name: "UDM" },
] as const;
