// Generated table profile for 0119 (v2.2)

export const id = "0119";
export const description = "ORDER CONTROL";
export const type = "hl7";
export const codes = [
  { description: "Cancel order request", name: "CA" },
  { description: "Child order", name: "CH" },
  { description: "Combined result", name: "CN" },
  { description: "Canceled as requested", name: "CR" },
  { description: "Discontinue order request", name: "DC" },
  { description: "Data Errors", name: "DE" },
  { description: "Discontinued as requested", name: "DR" },
  { description: "Hold order request", name: "HD" },
  { description: "On hold as requested", name: "HR" },
  { description: "Number assigned", name: "NA" },
  { description: "New Order", name: "NW" },
  { description: "Order canceled", name: "OC" },
  { description: "Order discontinued", name: "OD" },
  { description: "Order held", name: "OH" },
  { description: "Order accepted and OK", name: "OK" },
  { description: "Released as requested", name: "OR" },
  { description: "Parent order", name: "PA" },
  { description: "Observations to follow", name: "RE" },
  { description: "Release previous hold", name: "RL" },
  { description: "Replacement order", name: "RO" },
  { description: "Order replace request", name: "RP" },
  { description: "Replaced as requested", name: "RQ" },
  { description: "Request received", name: "RR" },
  { description: "Replaced unsolicited", name: "RU" },
  { description: "Status changed", name: "SC" },
  { description: "Send order number", name: "SN" },
  { description: "Response to send order status request", name: "SR" },
  { description: "Send order status request", name: "SS" },
  { description: "Unable to cancel", name: "UC" },
  { description: "Unable to discontinue", name: "UD" },
  { description: "Unable to put on hold", name: "UH" },
  { description: "Unable to replace", name: "UM" },
  { description: "Unable to release", name: "UR" },
  { description: "Unable to change", name: "UX" },
  { description: "Change order request", name: "XO" },
  { description: "Changed as requested", name: "XR" },
  { description: "Order changed, unsolicited", name: "XX" },
] as const;
