// Generated segment profile for AL1 (v2.4)

export const segmentId = "AL1";
export const fields = [
  {
    sequence: 1,
    id: "AL1-1",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "Set ID - AL1",
    item: "203",
  },
  {
    sequence: 2,
    id: "AL1-2",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70127",
    name: "Allergen Type Code",
    item: "204",
  },
  {
    sequence: 3,
    id: "AL1-3",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "Allergen Code/Mnemonic/Description",
    item: "205",
  },
  {
    sequence: 4,
    id: "AL1-4",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70128",
    name: "Allergy Severity Code",
    item: "206",
  },
  {
    sequence: 5,
    id: "AL1-5",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 15,
    name: "Allergy Reaction Code",
    item: "207",
  },
  {
    sequence: 6,
    id: "AL1-6",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Identification Date",
    item: "208",
  },
] as const;
