// Generated segment profile for DG1 (v2.4)

export const segmentId = "DG1";
export const fields = [
  {
    sequence: 1,
    id: "DG1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - DG1",
    item: "375",
  },
  {
    sequence: 2,
    id: "DG1-2",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70053",
    name: "Diagnosis Coding Method",
    item: "376",
  },
  {
    sequence: 3,
    id: "DG1-3",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70051",
    name: "Diagnosis Code - DG1",
    item: "377",
  },
  {
    sequence: 4,
    id: "DG1-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Diagnosis Description",
    item: "378",
  },
  {
    sequence: 5,
    id: "DG1-5",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Diagnosis Date/Time",
    item: "379",
  },
  {
    sequence: 6,
    id: "DG1-6",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70052",
    name: "Diagnosis Type",
    item: "380",
  },
  {
    sequence: 7,
    id: "DG1-7",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70118",
    name: "Major Diagnostic Category",
    item: "381",
  },
  {
    sequence: 8,
    id: "DG1-8",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70055",
    name: "Diagnostic Related Group",
    item: "382",
  },
  {
    sequence: 9,
    id: "DG1-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "DRG Approval Indicator",
    item: "383",
  },
  {
    sequence: 10,
    id: "DG1-10",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70056",
    name: "DRG Grouper Review Code",
    item: "384",
  },
  {
    sequence: 11,
    id: "DG1-11",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70083",
    name: "Outlier Type",
    item: "385",
  },
  {
    sequence: 12,
    id: "DG1-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    name: "Outlier Days",
    item: "386",
  },
  {
    sequence: 13,
    id: "DG1-13",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    name: "Outlier Cost",
    item: "387",
  },
  {
    sequence: 14,
    id: "DG1-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    name: "Grouper Version And Type",
    item: "388",
  },
  {
    sequence: 15,
    id: "DG1-15",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70359",
    name: "Diagnosis Priority",
    item: "389",
  },
  {
    sequence: 16,
    id: "DG1-16",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    name: "Diagnosing Clinician",
    item: "390",
  },
  {
    sequence: 17,
    id: "DG1-17",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 3,
    table: "HL70228",
    name: "Diagnosis Classification",
    item: "766",
  },
  {
    sequence: 18,
    id: "DG1-18",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Confidential Indicator",
    item: "767",
  },
  {
    sequence: 19,
    id: "DG1-19",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Attestation Date/Time",
    item: "768",
  },
] as const;
