// Generated profile automaton for BAR_P05 (v2.4)

export const start = 0;
export const finals = new Set<number>([
  3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
  24, 25, 26, 27, 28, 29, 30,
]);
export const alphabet = new Set<string>([
  "ABS",
  "ACC",
  "AL1",
  "BLC",
  "DB1",
  "DG1",
  "DRG",
  "EVN",
  "GT1",
  "IN1",
  "IN2",
  "IN3",
  "MSH",
  "NK1",
  "OBX",
  "PD1",
  "PID",
  "PR1",
  "PV1",
  "PV2",
  "RMI",
  "ROL",
  "UB1",
  "UB2",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [1, new Map([["EVN", 2]])],
  [2, new Map([["PID", 3]])],
  [
    3,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PD1", 22],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 19],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    4,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    5,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    6,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    7,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    8,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    9,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    10,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["IN2", 26],
      ["IN3", 25],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 24],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    11,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    12,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    13,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 27],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    14,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    15,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    16,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    17,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    18,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    19,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 28],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    20,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    21,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    22,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 19],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    23,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 23],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    24,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 29],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    25,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["IN3", 25],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 24],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    26,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["IN3", 25],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 24],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    27,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 30],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    28,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 19],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    29,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 24],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
  [
    30,
    new Map([
      ["ABS", 6],
      ["ACC", 9],
      ["AL1", 16],
      ["BLC", 5],
      ["DB1", 18],
      ["DG1", 15],
      ["DRG", 14],
      ["GT1", 12],
      ["IN1", 10],
      ["NK1", 11],
      ["OBX", 17],
      ["PR1", 13],
      ["PV1", 21],
      ["PV2", 20],
      ["RMI", 4],
      ["ROL", 27],
      ["UB1", 8],
      ["UB2", 7],
    ]),
  ],
]);
export const effects = {
  "3:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "3:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "3:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "3:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "4:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "4:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "4:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "5:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "5:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "5:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "6:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "6:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "6:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "7:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "7:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "7:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "8:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "8:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "8:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "9:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "9:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "9:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "10:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "10:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "10:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "11:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "11:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "12:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "12:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "12:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "13:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "13:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "13:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "14:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "14:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "14:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "15:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "15:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "15:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "16:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "16:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "16:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "17:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "17:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "17:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "18:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "18:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "18:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "19:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "19:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "19:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "19:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "20:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "20:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "21:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "21:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "21:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "22:RMI": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:BLC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:ABS": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:UB2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:UB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:ACC": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:IN1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "22:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "22:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "22:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "23:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "23:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "23:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "23:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "23:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "24:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "24:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "24:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "24:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "25:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "25:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "25:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "26:NK1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:GT1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:PR1": {
    groupsOpened: ["BAR_P05/VISIT", "BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "26:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "26:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "27:DRG": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:DG1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:AL1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:OBX": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:DB1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "27:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "28:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "28:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "28:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "29:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "29:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "29:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
  "30:ROL": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:PV2": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:PV1": {
    groupsOpened: ["BAR_P05/VISIT"],
    groupsClosed: [],
  },
  "30:IN1": {
    groupsOpened: ["BAR_P05/VISIT/INSURANCE"],
    groupsClosed: [],
  },
  "30:PR1": {
    groupsOpened: ["BAR_P05/VISIT/PROCEDURE"],
    groupsClosed: [],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
