// Generated segment profile for FHS (v2.3.1)

export const segmentId = "FHS";
export const fields = [
  {
    sequence: 1,
    id: "FHS-1",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 1,
    name: "File Field Separator",
    item: "67",
  },
  {
    sequence: 2,
    id: "FHS-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    name: "File Encoding Characters",
    item: "68",
  },
  {
    sequence: 3,
    id: "FHS-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "File Sending Application",
    item: "69",
  },
  {
    sequence: 4,
    id: "FHS-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "File Sending Facility",
    item: "70",
  },
  {
    sequence: 5,
    id: "FHS-5",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "File Receiving Application",
    item: "71",
  },
  {
    sequence: 6,
    id: "FHS-6",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "File Receiving Facility",
    item: "72",
  },
  {
    sequence: 7,
    id: "FHS-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "File Creation Date/Time",
    item: "73",
  },
  {
    sequence: 8,
    id: "FHS-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "File Security",
    item: "74",
  },
  {
    sequence: 9,
    id: "FHS-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "File Name/ID",
    item: "75",
  },
  {
    sequence: 10,
    id: "FHS-10",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 80,
    name: "File Header Comment",
    item: "76",
  },
  {
    sequence: 11,
    id: "FHS-11",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "File Control ID",
    item: "77",
  },
  {
    sequence: 12,
    id: "FHS-12",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Reference File Control ID",
    item: "78",
  },
] as const;
