// Generated segment profile for FT1 (v2.3.1)

export const segmentId = "FT1";
export const fields = [
  {
    sequence: 1,
    id: "FT1-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - FT1",
    item: "355",
  },
  {
    sequence: 2,
    id: "FT1-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    name: "Transaction ID",
    item: "356",
  },
  {
    sequence: 3,
    id: "FT1-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 10,
    name: "Transaction Batch ID",
    item: "357",
  },
  {
    sequence: 4,
    id: "FT1-4",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Transaction Date",
    item: "358",
  },
  {
    sequence: 5,
    id: "FT1-5",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Transaction Posting Date",
    item: "359",
  },
  {
    sequence: 6,
    id: "FT1-6",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 8,
    table: "HL70017",
    name: "Transaction Type",
    item: "360",
  },
  {
    sequence: 7,
    id: "FT1-7",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    table: "HL70132",
    name: "Transaction Code",
    item: "361",
  },
  {
    sequence: 8,
    id: "FT1-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Transaction Description",
    item: "362",
  },
  {
    sequence: 9,
    id: "FT1-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Transaction Description - Alt",
    item: "363",
  },
  {
    sequence: 10,
    id: "FT1-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 6,
    name: "Transaction Quantity",
    item: "364",
  },
  {
    sequence: 11,
    id: "FT1-11",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    name: "Transaction Amount - Extended",
    item: "365",
  },
  {
    sequence: 12,
    id: "FT1-12",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    name: "Transaction Amount - Unit",
    item: "366",
  },
  {
    sequence: 13,
    id: "FT1-13",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70049",
    name: "Department Code",
    item: "367",
  },
  {
    sequence: 14,
    id: "FT1-14",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70072",
    name: "Insurance Plan ID",
    item: "368",
  },
  {
    sequence: 15,
    id: "FT1-15",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    name: "Insurance Amount",
    item: "369",
  },
  {
    sequence: 16,
    id: "FT1-16",
    required: false,
    repeatable: false,
    datatype: "PL",
    maxLength: 80,
    name: "Assigned Patient Location",
    item: "133",
  },
  {
    sequence: 17,
    id: "FT1-17",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70024",
    name: "Fee Schedule",
    item: "370",
  },
  {
    sequence: 18,
    id: "FT1-18",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70018",
    name: "Patient Type",
    item: "148",
  },
  {
    sequence: 19,
    id: "FT1-19",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 60,
    table: "HL70051",
    name: "Diagnosis Code - FT1",
    item: "371",
  },
  {
    sequence: 20,
    id: "FT1-20",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 120,
    table: "HL70084",
    name: "Performed By Code",
    item: "372",
  },
  {
    sequence: 21,
    id: "FT1-21",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 120,
    name: "Ordered By Code",
    item: "373",
  },
  {
    sequence: 22,
    id: "FT1-22",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    name: "Unit Cost",
    item: "374",
  },
  {
    sequence: 23,
    id: "FT1-23",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 22,
    name: "Filler Order Number",
    item: "217",
  },
  {
    sequence: 24,
    id: "FT1-24",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 120,
    name: "Entered By Code",
    item: "765",
  },
  {
    sequence: 25,
    id: "FT1-25",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    table: "HL70088",
    name: "Procedure Code",
    item: "393",
  },
  {
    sequence: 26,
    id: "FT1-26",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 80,
    table: "HL70340",
    name: "Procedure Code Modifier",
    item: "1316",
  },
] as const;
