// Generated segment profile for RF1 (v2.3.1)

export const segmentId = "RF1";
export const fields = [
  {
    sequence: 1,
    id: "RF1-1",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70283",
    name: "Referral Status",
    item: "1137",
  },
  {
    sequence: 2,
    id: "RF1-2",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70280",
    name: "Referral Priority",
    item: "1138",
  },
  {
    sequence: 3,
    id: "RF1-3",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70281",
    name: "Referral Type",
    item: "1139",
  },
  {
    sequence: 4,
    id: "RF1-4",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    table: "HL70282",
    name: "Referral Disposition",
    item: "1140",
  },
  {
    sequence: 5,
    id: "RF1-5",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70284",
    name: "Referral Category",
    item: "1141",
  },
  {
    sequence: 6,
    id: "RF1-6",
    required: true,
    repeatable: false,
    datatype: "EI",
    maxLength: 30,
    name: "Originating Referral Identifier",
    item: "1142",
  },
  {
    sequence: 7,
    id: "RF1-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective Date",
    item: "1143",
  },
  {
    sequence: 8,
    id: "RF1-8",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Expiration Date",
    item: "1144",
  },
  {
    sequence: 9,
    id: "RF1-9",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Process Date",
    item: "1145",
  },
  {
    sequence: 10,
    id: "RF1-10",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    table: "HL70336",
    name: "Referral Reason",
    item: "1228",
  },
  {
    sequence: 11,
    id: "RF1-11",
    required: false,
    repeatable: true,
    datatype: "EI",
    maxLength: 30,
    name: "External Referral Identifier",
    item: "1300",
  },
] as const;
