// Generated segment profile for STF (v2.3.1)

export const segmentId = "STF";
export const fields = [
  {
    sequence: 1,
    id: "STF-1",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Primary Key Value - STF",
    item: "671",
  },
  {
    sequence: 2,
    id: "STF-2",
    required: false,
    repeatable: true,
    datatype: "CX",
    maxLength: 60,
    name: "Staff ID Code",
    item: "672",
  },
  {
    sequence: 3,
    id: "STF-3",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 48,
    name: "Staff Name",
    item: "673",
  },
  {
    sequence: 4,
    id: "STF-4",
    required: false,
    repeatable: true,
    datatype: "IS",
    maxLength: 2,
    table: "HL70182",
    name: "Staff Type",
    item: "674",
  },
  {
    sequence: 5,
    id: "STF-5",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70001",
    name: "Sex",
    item: "111",
  },
  {
    sequence: 6,
    id: "STF-6",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Date/Time Of Birth",
    item: "110",
  },
  {
    sequence: 7,
    id: "STF-7",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70183",
    name: "Active/Inactive Flag",
    item: "675",
  },
  {
    sequence: 8,
    id: "STF-8",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    table: "HL70184",
    name: "Department",
    item: "676",
  },
  {
    sequence: 9,
    id: "STF-9",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    table: "HL70069",
    name: "Hospital Service",
    item: "677",
  },
  {
    sequence: 10,
    id: "STF-10",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 40,
    name: "Phone",
    item: "678",
  },
  {
    sequence: 11,
    id: "STF-11",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 106,
    name: "Office/Home Address",
    item: "679",
  },
  {
    sequence: 12,
    id: "STF-12",
    required: false,
    repeatable: true,
    datatype: "DIN",
    maxLength: 26,
    name: "Institution Activation Date",
    item: "680",
  },
  {
    sequence: 13,
    id: "STF-13",
    required: false,
    repeatable: true,
    datatype: "DIN",
    maxLength: 26,
    name: "Institution Inactivation Date",
    item: "681",
  },
  {
    sequence: 14,
    id: "STF-14",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 60,
    name: "Backup Person ID",
    item: "682",
  },
  {
    sequence: 15,
    id: "STF-15",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 40,
    name: "E-Mail Address",
    item: "683",
  },
  {
    sequence: 16,
    id: "STF-16",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70185",
    name: "Preferred Method Of Contact",
    item: "684",
  },
  {
    sequence: 17,
    id: "STF-17",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    table: "HL70002",
    name: "Marital Status",
    item: "119",
  },
  {
    sequence: 18,
    id: "STF-18",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Job Title",
    item: "785",
  },
  {
    sequence: 19,
    id: "STF-19",
    required: false,
    repeatable: false,
    datatype: "JCC",
    maxLength: 20,
    table: "HL70327",
    name: "Job Code/Class",
    item: "786",
  },
  {
    sequence: 20,
    id: "STF-20",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70066",
    name: "Employment Status",
    item: "1276",
  },
  {
    sequence: 21,
    id: "STF-21",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Additional Insured on  Auto",
    item: "1275",
  },
  {
    sequence: 22,
    id: "STF-22",
    required: false,
    repeatable: false,
    datatype: "DLN",
    maxLength: 25,
    name: "Driver’s License Number - Staff",
    item: "1302",
  },
  {
    sequence: 23,
    id: "STF-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Copy  Auto Ins",
    item: "1229",
  },
  {
    sequence: 24,
    id: "STF-24",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Auto Ins. Expires",
    item: "1232",
  },
  {
    sequence: 25,
    id: "STF-25",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Date Last DMV Review",
    item: "1298",
  },
  {
    sequence: 26,
    id: "STF-26",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Date Next DMV Review",
    item: "1234",
  },
] as const;
