// Generated segment profile for MSH (v2.1)

export const segmentId = "MSH";
export const fields = [
  {
    sequence: 1,
    id: "MSH-1",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 1,
    name: "FIELD SEPARATOR",
    item: "5",
  },
  {
    sequence: 2,
    id: "MSH-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    name: "ENCODING CHARACTERS",
    item: "509",
  },
  {
    sequence: 3,
    id: "MSH-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "SENDING APPLICATION",
    item: "6",
  },
  {
    sequence: 4,
    id: "MSH-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "SENDING FACILITY",
    item: "512",
  },
  {
    sequence: 5,
    id: "MSH-5",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "RECEIVING APPLICATION",
    item: "9",
  },
  {
    sequence: 6,
    id: "MSH-6",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "RECEIVING FACILITY",
    item: "513",
  },
  {
    sequence: 7,
    id: "MSH-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 19,
    name: "DATE/TIME OF MESSAGE",
    item: "10",
  },
  {
    sequence: 8,
    id: "MSH-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Security",
    item: "8",
  },
  {
    sequence: 9,
    id: "MSH-9",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 7,
    table: "HL70076",
    name: "MESSAGE TYPE",
    item: "12",
  },
  {
    sequence: 10,
    id: "MSH-10",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "MESSAGE CONTROL ID",
    item: "13",
  },
  {
    sequence: 11,
    id: "MSH-11",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70103",
    name: "PROCESSING ID",
    item: "14",
  },
  {
    sequence: 12,
    id: "MSH-12",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 8,
    table: "HL70104",
    name: "VERSION ID",
    item: "15",
  },
  {
    sequence: 13,
    id: "MSH-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 15,
    name: "SEQUENCE NUMBER",
    item: "633",
  },
  {
    sequence: 14,
    id: "MSH-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 180,
    name: "CONTINUATION POINTER",
    item: "699",
  },
] as const;
