// Generated segment profile for OBX (v2.1)

export const segmentId = "OBX";
export const fields = [
  {
    sequence: 1,
    id: "OBX-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "SET ID - OBSERVATION SIMPLE",
    item: "559",
  },
  {
    sequence: 2,
    id: "OBX-2",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70125",
    name: "VALUE TYPE",
    item: "676",
  },
  {
    sequence: 3,
    id: "OBX-3",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    name: "OBSERVATION IDENTIFIER",
    item: "560",
  },
  {
    sequence: 4,
    id: "OBX-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "OBSERVATION SUB-ID",
    item: "769",
  },
  {
    sequence: 5,
    id: "OBX-5",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 65,
    name: "OBSERVATION RESULTS",
    item: "561",
  },
  {
    sequence: 6,
    id: "OBX-6",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 20,
    name: "UNITS",
    item: "562",
  },
  {
    sequence: 7,
    id: "OBX-7",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "REFERENCES RANGE",
    item: "563",
  },
  {
    sequence: 8,
    id: "OBX-8",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 10,
    table: "HL70078",
    name: "ABNORMAL FLAGS",
    item: "564",
  },
  {
    sequence: 9,
    id: "OBX-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "PROBABILITY",
    item: "639",
  },
  {
    sequence: 10,
    id: "OBX-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 5,
    table: "HL70080",
    name: "NATURE OF ABNORMAL TEST",
    item: "565",
  },
  {
    sequence: 11,
    id: "OBX-11",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70085",
    name: "OBSERV RESULT STATUS",
    item: "566",
  },
  {
    sequence: 12,
    id: "OBX-12",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 19,
    name: "DATE LAST OBS NORMAL VALUES",
    item: "567",
  },
] as const;
