// Generated segment profile for PID (v2.1)

export const segmentId = "PID";
export const fields = [
  {
    sequence: 1,
    id: "PID-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "SET ID - PATIENT ID",
    item: "572",
  },
  {
    sequence: 2,
    id: "PID-2",
    required: false,
    repeatable: false,
    datatype: "CK",
    maxLength: 16,
    table: "HL70061",
    name: "PATIENT ID EXTERNAL (EXTERNAL ID)",
    item: "581",
  },
  {
    sequence: 3,
    id: "PID-3",
    required: true,
    repeatable: false,
    datatype: "CK",
    maxLength: 16,
    table: "HL70061",
    name: "PATIENT ID INTERNAL (INTERNAL ID)",
    item: "34",
  },
  {
    sequence: 4,
    id: "PID-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    name: "ALTERNATE PATIENT ID",
    item: "38",
  },
  {
    sequence: 5,
    id: "PID-5",
    required: true,
    repeatable: false,
    datatype: "PN",
    maxLength: 48,
    name: "PATIENT NAME",
    item: "41",
  },
  {
    sequence: 6,
    id: "PID-6",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 30,
    name: "MOTHER&apos;S MAIDEN NAME",
    item: "582",
  },
  {
    sequence: 7,
    id: "PID-7",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "DATE OF BIRTH",
    item: "43",
  },
  {
    sequence: 8,
    id: "PID-8",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70001",
    name: "SEX",
    item: "42",
  },
  {
    sequence: 9,
    id: "PID-9",
    required: false,
    repeatable: true,
    datatype: "PN",
    maxLength: 48,
    name: "PATIENT ALIAS",
    item: "597",
  },
  {
    sequence: 10,
    id: "PID-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70005",
    name: "ETHNIC GROUP",
    item: "44",
  },
  {
    sequence: 11,
    id: "PID-11",
    required: false,
    repeatable: false,
    datatype: "AD",
    maxLength: 106,
    name: "PATIENT ADDRESS",
    item: "20",
  },
  {
    sequence: 12,
    id: "PID-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 4,
    name: "COUNTY CODE",
    item: "26",
  },
  {
    sequence: 13,
    id: "PID-13",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 40,
    name: "PHONE NUMBER - HOME",
    item: "49",
  },
  {
    sequence: 14,
    id: "PID-14",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 40,
    name: "PHONE NUMBER - BUSINESS",
    item: "50",
  },
  {
    sequence: 15,
    id: "PID-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 25,
    name: "LANGUAGE - PATIENT",
    item: "464",
  },
  {
    sequence: 16,
    id: "PID-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70002",
    name: "MARITAL STATUS",
    item: "46",
  },
  {
    sequence: 17,
    id: "PID-17",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 3,
    table: "HL70006",
    name: "RELIGION",
    item: "45",
  },
  {
    sequence: 18,
    id: "PID-18",
    required: false,
    repeatable: false,
    datatype: "CK",
    maxLength: 20,
    table: "HL70061",
    name: "PATIENT ACCOUNT NUMBER",
    item: "35",
  },
  {
    sequence: 19,
    id: "PID-19",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 16,
    name: "SSN NUMBER - PATIENT",
    item: "457",
  },
  {
    sequence: 20,
    id: "PID-20",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 25,
    name: "DRIVER&apos;S LIC NUM - PATIENT",
    item: "453",
  },
] as const;
