// Generated segment profile for DG1 (v2.6)

export const segmentId = "DG1";
export const fields = [
  {
    sequence: 1,
    id: "DG1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Set ID - DG1",
    item: "375",
  },
  {
    sequence: 2,
    id: "DG1-3",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70051",
    name: "Diagnosis Code - DG1",
    item: "377",
  },
  {
    sequence: 3,
    id: "DG1-5",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Diagnosis Date/Time",
    item: "379",
  },
  {
    sequence: 4,
    id: "DG1-6",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70052",
    name: "Diagnosis Type",
    item: "380",
  },
  {
    sequence: 5,
    id: "DG1-15",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70359",
    name: "Diagnosis Priority",
    item: "389",
  },
  {
    sequence: 6,
    id: "DG1-16",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70000",
    name: "Diagnosing Clinician",
    item: "390",
  },
  {
    sequence: 7,
    id: "DG1-17",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 3,
    table: "HL70228",
    name: "Diagnosis Classification",
    item: "766",
  },
  {
    sequence: 8,
    id: "DG1-18",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Confidential Indicator",
    item: "767",
  },
  {
    sequence: 9,
    id: "DG1-19",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Attestation Date/Time",
    item: "768",
  },
  {
    sequence: 10,
    id: "DG1-20",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 427,
    table: "HL70000",
    name: "Diagnosis Identifier",
    item: "1850",
  },
  {
    sequence: 11,
    id: "DG1-21",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70206",
    name: "Diagnosis Action Code",
    item: "1894",
  },
  {
    sequence: 12,
    id: "DG1-22",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 427,
    table: "HL70000",
    name: "Parent Diagnosis",
    item: "2152",
  },
  {
    sequence: 13,
    id: "DG1-23",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL70728",
    name: "DRG CCL Value Code",
    item: "2153",
  },
  {
    sequence: 14,
    id: "DG1-24",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 20,
    table: "HL70136",
    name: "DRG Grouping Usage",
    item: "2154",
  },
  {
    sequence: 15,
    id: "DG1-25",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70731",
    name: "DRG Diagnosis Determination Status",
    item: "2155",
  },
  {
    sequence: 16,
    id: "DG1-26",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70895",
    name: "Present On Admission (POA) Indicator",
    item: "2288",
  },
] as const;
