// Generated segment profile for DRG (v2.6)

export const segmentId = "DRG";
export const fields = [
  {
    sequence: 1,
    id: "DRG-1",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 250,
    table: "HL70055",
    name: "Diagnostic Related Group",
    item: "382",
  },
  {
    sequence: 2,
    id: "DRG-2",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "DRG Assigned Date/Time",
    item: "769",
  },
  {
    sequence: 3,
    id: "DRG-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "DRG Approval Indicator",
    item: "383",
  },
  {
    sequence: 4,
    id: "DRG-4",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70056",
    name: "DRG Grouper Review Code",
    item: "384",
  },
  {
    sequence: 5,
    id: "DRG-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70083",
    name: "Outlier Type",
    item: "385",
  },
  {
    sequence: 6,
    id: "DRG-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    table: "HL70000",
    name: "Outlier Days",
    item: "386",
  },
  {
    sequence: 7,
    id: "DRG-7",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    table: "HL70000",
    name: "Outlier Cost",
    item: "387",
  },
  {
    sequence: 8,
    id: "DRG-8",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70229",
    name: "DRG Payor",
    item: "770",
  },
  {
    sequence: 9,
    id: "DRG-9",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 9,
    table: "HL70000",
    name: "Outlier Reimbursement",
    item: "771",
  },
  {
    sequence: 10,
    id: "DRG-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Confidential Indicator",
    item: "767",
  },
  {
    sequence: 11,
    id: "DRG-11",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 21,
    table: "HL70415",
    name: "DRG Transfer Type",
    item: "1500",
  },
  {
    sequence: 12,
    id: "DRG-12",
    required: false,
    repeatable: false,
    datatype: "XPN",
    maxLength: 1103,
    table: "HL70000",
    name: "Name of Coder",
    item: "2156",
  },
  {
    sequence: 13,
    id: "DRG-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL70734",
    name: "Grouper Status",
    item: "2157",
  },
  {
    sequence: 14,
    id: "DRG-14",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 20,
    table: "HL70728",
    name: "PCCL Value Code",
    item: "2158",
  },
  {
    sequence: 15,
    id: "DRG-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    table: "HL70000",
    name: "Effective Weight",
    item: "2159",
  },
  {
    sequence: 16,
    id: "DRG-16",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 20,
    table: "HL70000",
    name: "Monetary Amount",
    item: "2160",
  },
  {
    sequence: 17,
    id: "DRG-17",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70739",
    name: "Status Patient",
    item: "2161",
  },
  {
    sequence: 18,
    id: "DRG-18",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 100,
    table: "HL70000",
    name: "Grouper Software Name",
    item: "2162",
  },
  {
    sequence: 19,
    id: "DRG-19",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 100,
    table: "HL70000",
    name: "Grouper Software Version",
    item: "2282",
  },
  {
    sequence: 20,
    id: "DRG-20",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70742",
    name: "Status Financial Calculation",
    item: "2163",
  },
  {
    sequence: 21,
    id: "DRG-21",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 20,
    table: "HL70000",
    name: "Relative Discount/Surcharge",
    item: "2164",
  },
  {
    sequence: 22,
    id: "DRG-22",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 20,
    table: "HL70000",
    name: "Basic Charge",
    item: "2165",
  },
  {
    sequence: 23,
    id: "DRG-23",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 20,
    table: "HL70000",
    name: "Total Charge",
    item: "2166",
  },
  {
    sequence: 24,
    id: "DRG-24",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 20,
    table: "HL70000",
    name: "Discount/Surcharge",
    item: "2167",
  },
  {
    sequence: 25,
    id: "DRG-25",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    table: "HL70000",
    name: "Calculated Days",
    item: "2168",
  },
  {
    sequence: 26,
    id: "DRG-26",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70749",
    name: "Status Gender",
    item: "2169",
  },
  {
    sequence: 27,
    id: "DRG-27",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70749",
    name: "Status Age",
    item: "2170",
  },
  {
    sequence: 28,
    id: "DRG-28",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70749",
    name: "Status Length of Stay",
    item: "2171",
  },
  {
    sequence: 29,
    id: "DRG-29",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70749",
    name: "Status Same Day Flag",
    item: "2172",
  },
  {
    sequence: 30,
    id: "DRG-30",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70749",
    name: "Status Separation Mode",
    item: "2173",
  },
  {
    sequence: 31,
    id: "DRG-31",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70755",
    name: "Status Weight at Birth",
    item: "2174",
  },
  {
    sequence: 32,
    id: "DRG-32",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70757",
    name: "Status Respiration Minutes",
    item: "2175",
  },
  {
    sequence: 33,
    id: "DRG-33",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70759",
    name: "Status Admission",
    item: "2176",
  },
] as const;
