// Generated segment profile for DSP (v2.6)

export const segmentId = "DSP";
export const fields = [
  {
    sequence: 1,
    id: "DSP-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Set ID - DSP",
    item: "61",
  },
  {
    sequence: 2,
    id: "DSP-2",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Display Level",
    item: "62",
  },
  {
    sequence: 3,
    id: "DSP-3",
    required: true,
    repeatable: false,
    datatype: "TX",
    maxLength: 300,
    table: "HL70000",
    name: "Data Line",
    item: "63",
  },
  {
    sequence: 4,
    id: "DSP-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 2,
    table: "HL70000",
    name: "Logical Break Point",
    item: "64",
  },
  {
    sequence: 5,
    id: "DSP-5",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 20,
    table: "HL70000",
    name: "Result ID",
    item: "65",
  },
] as const;
