// Generated segment profile for FT1 (v2.6)

export const segmentId = "FT1";
export const fields = [
  {
    sequence: 1,
    id: "FT1-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Set ID - FT1",
    item: "355",
  },
  {
    sequence: 2,
    id: "FT1-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    table: "HL70000",
    name: "Transaction ID",
    item: "356",
  },
  {
    sequence: 3,
    id: "FT1-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 10,
    table: "HL70000",
    name: "Transaction Batch ID",
    item: "357",
  },
  {
    sequence: 4,
    id: "FT1-4",
    required: true,
    repeatable: false,
    datatype: "DR",
    maxLength: 53,
    table: "HL70000",
    name: "Transaction Date",
    item: "358",
  },
  {
    sequence: 5,
    id: "FT1-5",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Transaction Posting Date",
    item: "359",
  },
  {
    sequence: 6,
    id: "FT1-6",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 8,
    table: "HL70017",
    name: "Transaction Type",
    item: "360",
  },
  {
    sequence: 7,
    id: "FT1-7",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70132",
    name: "Transaction Code",
    item: "361",
  },
  {
    sequence: 8,
    id: "FT1-8",
    deprecated: true,
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Transaction Description",
    item: "362",
  },
  {
    sequence: 9,
    id: "FT1-9",
    deprecated: true,
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Transaction Description - Alt",
    item: "363",
  },
  {
    sequence: 10,
    id: "FT1-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 6,
    table: "HL70000",
    name: "Transaction Quantity",
    item: "364",
  },
  {
    sequence: 11,
    id: "FT1-11",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    table: "HL70000",
    name: "Transaction Amount - Extended",
    item: "365",
  },
  {
    sequence: 12,
    id: "FT1-12",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    table: "HL70000",
    name: "Transaction amount - unit",
    item: "366",
  },
  {
    sequence: 13,
    id: "FT1-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70049",
    name: "Department Code",
    item: "367",
  },
  {
    sequence: 14,
    id: "FT1-14",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70072",
    name: "Insurance Plan ID",
    item: "368",
  },
  {
    sequence: 15,
    id: "FT1-15",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    table: "HL70000",
    name: "Insurance Amount",
    item: "369",
  },
  {
    sequence: 16,
    id: "FT1-16",
    required: false,
    repeatable: false,
    datatype: "PL",
    maxLength: 80,
    table: "HL70000",
    name: "Assigned Patient Location",
    item: "133",
  },
  {
    sequence: 17,
    id: "FT1-17",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70024",
    name: "Fee Schedule",
    item: "370",
  },
  {
    sequence: 18,
    id: "FT1-18",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70018",
    name: "Patient Type",
    item: "148",
  },
  {
    sequence: 19,
    id: "FT1-19",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70051",
    name: "Diagnosis Code - FT1",
    item: "371",
  },
  {
    sequence: 20,
    id: "FT1-20",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70084",
    name: "Performed By Code",
    item: "372",
  },
  {
    sequence: 21,
    id: "FT1-21",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70000",
    name: "Ordered By Code",
    item: "373",
  },
  {
    sequence: 22,
    id: "FT1-22",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    table: "HL70000",
    name: "Unit Cost",
    item: "374",
  },
  {
    sequence: 23,
    id: "FT1-23",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 427,
    table: "HL70000",
    name: "Filler Order Number",
    item: "217",
  },
  {
    sequence: 24,
    id: "FT1-24",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70000",
    name: "Entered By Code",
    item: "765",
  },
  {
    sequence: 25,
    id: "FT1-25",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 705,
    table: "HL70088",
    name: "Procedure Code",
    item: "393",
  },
  {
    sequence: 26,
    id: "FT1-26",
    required: false,
    repeatable: true,
    datatype: "CNE",
    maxLength: 705,
    table: "HL70340",
    name: "Procedure Code Modifier",
    item: "1316",
  },
  {
    sequence: 27,
    id: "FT1-27",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70339",
    name: "Advanced Beneficiary Notice Code",
    item: "1310",
  },
  {
    sequence: 28,
    id: "FT1-28",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL70476",
    name: "Medically Necessary Duplicate Procedure Reason",
    item: "1646",
  },
  {
    sequence: 29,
    id: "FT1-29",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70549",
    name: "NDC Code",
    item: "1845",
  },
  {
    sequence: 30,
    id: "FT1-30",
    required: false,
    repeatable: false,
    datatype: "CX",
    maxLength: 250,
    table: "HL70000",
    name: "Payment Reference ID",
    item: "1846",
  },
  {
    sequence: 31,
    id: "FT1-31",
    required: false,
    repeatable: true,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Transaction Reference Key",
    item: "1847",
  },
] as const;
