// Generated segment profile for IN1 (v2.6)

export const segmentId = "IN1";
export const fields = [
  {
    sequence: 1,
    id: "IN1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Set ID - IN1",
    item: "426",
  },
  {
    sequence: 2,
    id: "IN1-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70072",
    name: "Insurance Plan ID",
    item: "368",
  },
  {
    sequence: 3,
    id: "IN1-3",
    required: true,
    repeatable: true,
    datatype: "CX",
    maxLength: 250,
    table: "HL70000",
    name: "Insurance Company ID",
    item: "428",
  },
  {
    sequence: 4,
    id: "IN1-4",
    required: false,
    repeatable: true,
    datatype: "XON",
    maxLength: 250,
    table: "HL70000",
    name: "Insurance Company Name",
    item: "429",
  },
  {
    sequence: 5,
    id: "IN1-5",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 250,
    table: "HL70000",
    name: "Insurance Company Address",
    item: "430",
  },
  {
    sequence: 6,
    id: "IN1-6",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 250,
    table: "HL70000",
    name: "Insurance Co Contact Person",
    item: "431",
  },
  {
    sequence: 7,
    id: "IN1-7",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 250,
    table: "HL70000",
    name: "Insurance Co Phone Number",
    item: "432",
  },
  {
    sequence: 8,
    id: "IN1-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    table: "HL70000",
    name: "Group Number",
    item: "433",
  },
  {
    sequence: 9,
    id: "IN1-9",
    required: false,
    repeatable: true,
    datatype: "XON",
    maxLength: 250,
    table: "HL70000",
    name: "Group Name",
    item: "434",
  },
  {
    sequence: 10,
    id: "IN1-10",
    required: false,
    repeatable: true,
    datatype: "CX",
    maxLength: 250,
    table: "HL70000",
    name: "Insured's Group Emp ID",
    item: "435",
  },
  {
    sequence: 11,
    id: "IN1-11",
    required: false,
    repeatable: true,
    datatype: "XON",
    maxLength: 250,
    table: "HL70000",
    name: "Insured's Group Emp Name",
    item: "436",
  },
  {
    sequence: 12,
    id: "IN1-12",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "Plan Effective Date",
    item: "437",
  },
  {
    sequence: 13,
    id: "IN1-13",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "Plan Expiration Date",
    item: "438",
  },
  {
    sequence: 14,
    id: "IN1-14",
    required: false,
    repeatable: false,
    datatype: "AUI",
    maxLength: 239,
    table: "HL70000",
    name: "Authorization Information",
    item: "439",
  },
  {
    sequence: 15,
    id: "IN1-15",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 3,
    table: "HL70086",
    name: "Plan Type",
    item: "440",
  },
  {
    sequence: 16,
    id: "IN1-16",
    required: false,
    repeatable: true,
    datatype: "XPN",
    maxLength: 250,
    table: "HL70000",
    name: "Name Of Insured",
    item: "441",
  },
  {
    sequence: 17,
    id: "IN1-17",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70063",
    name: "Insured's Relationship To Patient",
    item: "442",
  },
  {
    sequence: 18,
    id: "IN1-18",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Insured's Date Of Birth",
    item: "443",
  },
  {
    sequence: 19,
    id: "IN1-19",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 250,
    table: "HL70000",
    name: "Insured's Address",
    item: "444",
  },
  {
    sequence: 20,
    id: "IN1-20",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70135",
    name: "Assignment Of Benefits",
    item: "445",
  },
  {
    sequence: 21,
    id: "IN1-21",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70173",
    name: "Coordination Of Benefits",
    item: "446",
  },
  {
    sequence: 22,
    id: "IN1-22",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 2,
    table: "HL70000",
    name: "Coord Of Ben. Priority",
    item: "447",
  },
  {
    sequence: 23,
    id: "IN1-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Notice Of Admission Flag",
    item: "448",
  },
  {
    sequence: 24,
    id: "IN1-24",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "Notice Of Admission Date",
    item: "449",
  },
  {
    sequence: 25,
    id: "IN1-25",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Report Of Eligibility Flag",
    item: "450",
  },
  {
    sequence: 26,
    id: "IN1-26",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "Report Of Eligibility Date",
    item: "451",
  },
  {
    sequence: 27,
    id: "IN1-27",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70093",
    name: "Release Information Code",
    item: "452",
  },
  {
    sequence: 28,
    id: "IN1-28",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    table: "HL70000",
    name: "Pre-Admit Cert (PAC)",
    item: "453",
  },
  {
    sequence: 29,
    id: "IN1-29",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Verification Date/Time",
    item: "454",
  },
  {
    sequence: 30,
    id: "IN1-30",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70000",
    name: "Verification By",
    item: "455",
  },
  {
    sequence: 31,
    id: "IN1-31",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70098",
    name: "Type Of Agreement Code",
    item: "456",
  },
  {
    sequence: 32,
    id: "IN1-32",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70022",
    name: "Billing Status",
    item: "457",
  },
  {
    sequence: 33,
    id: "IN1-33",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    table: "HL70000",
    name: "Lifetime Reserve Days",
    item: "458",
  },
  {
    sequence: 34,
    id: "IN1-34",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    table: "HL70000",
    name: "Delay Before L.R. Day",
    item: "459",
  },
  {
    sequence: 35,
    id: "IN1-35",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 20,
    table: "HL70042",
    name: "Company Plan Code",
    item: "460",
  },
  {
    sequence: 36,
    id: "IN1-36",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    table: "HL70000",
    name: "Policy Number",
    item: "461",
  },
  {
    sequence: 37,
    id: "IN1-37",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 12,
    table: "HL70000",
    name: "Policy Deductible",
    item: "462",
  },
  {
    sequence: 38,
    id: "IN1-39",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    table: "HL70000",
    name: "Policy Limit - Days",
    item: "464",
  },
  {
    sequence: 39,
    id: "IN1-42",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70066",
    name: "Insured's Employment Status",
    item: "467",
  },
  {
    sequence: 40,
    id: "IN1-43",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70001",
    name: "Insured's Administrative Sex",
    item: "468",
  },
  {
    sequence: 41,
    id: "IN1-44",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 250,
    table: "HL70000",
    name: "Insured's Employer's Address",
    item: "469",
  },
  {
    sequence: 42,
    id: "IN1-45",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 2,
    table: "HL70000",
    name: "Verification Status",
    item: "470",
  },
  {
    sequence: 43,
    id: "IN1-46",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 8,
    table: "HL70072",
    name: "Prior Insurance Plan ID",
    item: "471",
  },
  {
    sequence: 44,
    id: "IN1-47",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 3,
    table: "HL70309",
    name: "Coverage Type",
    item: "1227",
  },
  {
    sequence: 45,
    id: "IN1-48",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70295",
    name: "Handicap",
    item: "753",
  },
  {
    sequence: 46,
    id: "IN1-49",
    required: false,
    repeatable: true,
    datatype: "CX",
    maxLength: 250,
    table: "HL70000",
    name: "Insured's ID Number",
    item: "1230",
  },
  {
    sequence: 47,
    id: "IN1-50",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70535",
    name: "Signature Code",
    item: "1854",
  },
  {
    sequence: 48,
    id: "IN1-51",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "Signature Code Date",
    item: "1855",
  },
  {
    sequence: 49,
    id: "IN1-52",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 250,
    table: "HL70000",
    name: "Insured's Birth Place",
    item: "1899",
  },
  {
    sequence: 50,
    id: "IN1-53",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70099",
    name: "VIP Indicator",
    item: "1852",
  },
] as const;
