// Generated segment profile for IVC (v2.6)

export const segmentId = "IVC";
export const fields = [
  {
    sequence: 1,
    id: "IVC-1",
    required: true,
    repeatable: false,
    datatype: "EI",
    maxLength: 74,
    name: "Provider Invoice Number",
    item: "1914",
  },
  {
    sequence: 2,
    id: "IVC-2",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 74,
    name: "Payer Invoice Number",
    item: "1915",
  },
  {
    sequence: 3,
    id: "IVC-3",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 74,
    name: "Contract/Agreement Number",
    item: "1916",
  },
  {
    sequence: 4,
    id: "IVC-4",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70553",
    name: "Invoice Control",
    item: "1917",
  },
  {
    sequence: 5,
    id: "IVC-5",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 4,
    table: "HL70554",
    name: "Invoice Reason",
    item: "1918",
  },
  {
    sequence: 6,
    id: "IVC-6",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 2,
    table: "HL70555",
    name: "Invoice Type",
    item: "1919",
  },
  {
    sequence: 7,
    id: "IVC-7",
    required: true,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Invoice Date/Time",
    item: "1920",
  },
  {
    sequence: 8,
    id: "IVC-8",
    required: true,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Invoice Amount",
    item: "1921",
  },
  {
    sequence: 9,
    id: "IVC-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 80,
    name: "Payment Terms",
    item: "1922",
  },
  {
    sequence: 10,
    id: "IVC-10",
    required: true,
    repeatable: false,
    datatype: "XON",
    maxLength: 183,
    name: "Provider Organization",
    item: "1923",
  },
  {
    sequence: 11,
    id: "IVC-11",
    required: true,
    repeatable: false,
    datatype: "XON",
    maxLength: 183,
    name: "Payer Organization",
    item: "1924",
  },
  {
    sequence: 12,
    id: "IVC-12",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 637,
    name: "Attention",
    item: "1925",
  },
  {
    sequence: 13,
    id: "IVC-13",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Last Invoice Indicator",
    item: "1926",
  },
  {
    sequence: 14,
    id: "IVC-14",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Invoice Booking Period",
    item: "1927",
  },
  {
    sequence: 15,
    id: "IVC-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 250,
    name: "Origin",
    item: "1928",
  },
  {
    sequence: 16,
    id: "IVC-16",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Invoice Fixed Amount",
    item: "1929",
  },
  {
    sequence: 17,
    id: "IVC-17",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Special Costs",
    item: "1930",
  },
  {
    sequence: 18,
    id: "IVC-18",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Amount for Doctors Treatment",
    item: "1931",
  },
  {
    sequence: 19,
    id: "IVC-19",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    name: "Responsible Physician",
    item: "1932",
  },
  {
    sequence: 20,
    id: "IVC-20",
    required: false,
    repeatable: false,
    datatype: "CX",
    maxLength: 250,
    name: "Cost Center",
    item: "1933",
  },
  {
    sequence: 21,
    id: "IVC-21",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Invoice Prepaid Amount",
    item: "1934",
  },
  {
    sequence: 22,
    id: "IVC-22",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Total Invoice Amount without Prepaid Amount",
    item: "1935",
  },
  {
    sequence: 23,
    id: "IVC-23",
    required: false,
    repeatable: false,
    datatype: "CP",
    maxLength: 254,
    name: "Total-Amount of VAT",
    item: "1936",
  },
  {
    sequence: 24,
    id: "IVC-24",
    required: false,
    repeatable: true,
    datatype: "NM",
    maxLength: 1024,
    name: "VAT-Rates applied",
    item: "1937",
  },
  {
    sequence: 25,
    id: "IVC-25",
    required: true,
    repeatable: false,
    datatype: "IS",
    maxLength: 4,
    table: "HL70556",
    name: "Benefit Group",
    item: "1938",
  },
  {
    sequence: 26,
    id: "IVC-26",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Provider Tax ID",
    item: "2038",
  },
  {
    sequence: 27,
    id: "IVC-27",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Payer Tax ID",
    item: "2039",
  },
  {
    sequence: 28,
    id: "IVC-28",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 4,
    table: "HL70572",
    name: "Provider Tax status",
    item: "2040",
  },
  {
    sequence: 29,
    id: "IVC-29",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 4,
    table: "HL70572",
    name: "Payer Tax status",
    item: "2041",
  },
  {
    sequence: 30,
    id: "IVC-30",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Sales Tax ID",
    item: "2042",
  },
] as const;
