// Generated segment profile for MSH (v2.6)

export const segmentId = "MSH";
export const fields = [
  {
    sequence: 1,
    id: "MSH-1",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 1,
    table: "HL70000",
    name: "Field Separator",
    item: "1",
  },
  {
    sequence: 2,
    id: "MSH-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    table: "HL70000",
    name: "Encoding Characters",
    item: "2",
  },
  {
    sequence: 3,
    id: "MSH-3",
    required: false,
    repeatable: false,
    datatype: "HD",
    maxLength: 227,
    table: "HL70361",
    name: "Sending Application",
    item: "3",
  },
  {
    sequence: 4,
    id: "MSH-4",
    required: false,
    repeatable: false,
    datatype: "HD",
    maxLength: 227,
    table: "HL70362",
    name: "Sending Facility",
    item: "4",
  },
  {
    sequence: 5,
    id: "MSH-5",
    required: false,
    repeatable: false,
    datatype: "HD",
    maxLength: 227,
    table: "HL70361",
    name: "Receiving Application",
    item: "5",
  },
  {
    sequence: 6,
    id: "MSH-6",
    required: false,
    repeatable: false,
    datatype: "HD",
    maxLength: 227,
    table: "HL70362",
    name: "Receiving Facility",
    item: "6",
  },
  {
    sequence: 7,
    id: "MSH-7",
    required: true,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Date/Time of Message",
    item: "7",
  },
  {
    sequence: 8,
    id: "MSH-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    table: "HL70000",
    name: "Security",
    item: "8",
  },
  {
    sequence: 9,
    id: "MSH-9",
    required: true,
    repeatable: false,
    datatype: "MSG",
    maxLength: 15,
    table: "HL70000",
    name: "Message Type",
    item: "9",
  },
  {
    sequence: 10,
    id: "MSH-10",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 199,
    table: "HL70000",
    name: "Message Control ID",
    item: "10",
  },
  {
    sequence: 11,
    id: "MSH-11",
    required: true,
    repeatable: false,
    datatype: "PT",
    maxLength: 3,
    table: "HL70000",
    name: "Processing ID",
    item: "11",
  },
  {
    sequence: 12,
    id: "MSH-12",
    required: true,
    repeatable: false,
    datatype: "VID",
    maxLength: 60,
    table: "HL70000",
    name: "Version ID",
    item: "12",
  },
  {
    sequence: 13,
    id: "MSH-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 15,
    table: "HL70000",
    name: "Sequence Number",
    item: "13",
  },
  {
    sequence: 14,
    id: "MSH-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 180,
    table: "HL70000",
    name: "Continuation Pointer",
    item: "14",
  },
  {
    sequence: 15,
    id: "MSH-15",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70155",
    name: "Accept Acknowledgment Type",
    item: "15",
  },
  {
    sequence: 16,
    id: "MSH-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70155",
    name: "Application Acknowledgment Type",
    item: "16",
  },
  {
    sequence: 17,
    id: "MSH-17",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 3,
    table: "HL70399",
    name: "Country Code",
    item: "17",
  },
  {
    sequence: 18,
    id: "MSH-18",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 16,
    table: "HL70211",
    name: "Character Set",
    item: "692",
  },
  {
    sequence: 19,
    id: "MSH-19",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70000",
    name: "Principal Language Of Message",
    item: "693",
  },
  {
    sequence: 20,
    id: "MSH-20",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 20,
    table: "HL70356",
    name: "Alternate Character Set Handling Scheme",
    item: "1317",
  },
  {
    sequence: 21,
    id: "MSH-21",
    required: false,
    repeatable: true,
    datatype: "EI",
    maxLength: 427,
    table: "HL70000",
    name: "Message Profile Identifier",
    item: "1598",
  },
  {
    sequence: 22,
    id: "MSH-22",
    required: false,
    repeatable: false,
    datatype: "XON",
    maxLength: 567,
    table: "HL70000",
    name: "Sending Responsible Organization",
    item: "1823",
  },
  {
    sequence: 23,
    id: "MSH-23",
    required: false,
    repeatable: false,
    datatype: "XON",
    maxLength: 567,
    table: "HL70000",
    name: "Receiving Responsible Organization",
    item: "1824",
  },
  {
    sequence: 24,
    id: "MSH-24",
    required: false,
    repeatable: false,
    datatype: "HD",
    maxLength: 227,
    table: "HL70000",
    name: "Sending Network Address",
    item: "1825",
  },
  {
    sequence: 25,
    id: "MSH-25",
    required: false,
    repeatable: false,
    datatype: "HD",
    maxLength: 227,
    table: "HL70000",
    name: "Receiving Network Address",
    item: "1826",
  },
] as const;
