// Generated segment profile for OBX (v2.6)

export const segmentId = "OBX";
export const fields = [
  {
    sequence: 1,
    id: "OBX-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Set ID - OBX",
    item: "569",
  },
  {
    sequence: 2,
    id: "OBX-2",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 3,
    table: "HL70125",
    name: "Value Type",
    item: "570",
  },
  {
    sequence: 3,
    id: "OBX-3",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL79999",
    name: "Observation Identifier",
    item: "571",
  },
  {
    sequence: 4,
    id: "OBX-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    table: "HL70000",
    name: "Observation Sub-ID",
    item: "572",
  },
  {
    sequence: 5,
    id: "OBX-5",
    required: false,
    repeatable: true,
    datatype: "varies",
    maxLength: 65_536,
    table: "HL70000",
    name: "Observation Value",
    item: "573",
  },
  {
    sequence: 6,
    id: "OBX-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL79999",
    name: "Units",
    item: "574",
  },
  {
    sequence: 7,
    id: "OBX-7",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    table: "HL70000",
    name: "References Range",
    item: "575",
  },
  {
    sequence: 8,
    id: "OBX-8",
    required: false,
    repeatable: true,
    datatype: "IS",
    maxLength: 5,
    table: "HL70078",
    name: "Abnormal Flags",
    item: "576",
  },
  {
    sequence: 9,
    id: "OBX-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    table: "HL70000",
    name: "Probability",
    item: "577",
  },
  {
    sequence: 10,
    id: "OBX-10",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 2,
    table: "HL70080",
    name: "Nature of Abnormal Test",
    item: "578",
  },
  {
    sequence: 11,
    id: "OBX-11",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70085",
    name: "Observation Result Status",
    item: "579",
  },
  {
    sequence: 12,
    id: "OBX-12",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Effective Date of Reference Range",
    item: "580",
  },
  {
    sequence: 13,
    id: "OBX-13",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    table: "HL70000",
    name: "User Defined Access Checks",
    item: "581",
  },
  {
    sequence: 14,
    id: "OBX-14",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Date/Time of the Observation",
    item: "582",
  },
  {
    sequence: 15,
    id: "OBX-15",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL79999",
    name: "Producer's ID",
    item: "583",
  },
  {
    sequence: 16,
    id: "OBX-16",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 3220,
    table: "HL70000",
    name: "Responsible Observer",
    item: "584",
  },
  {
    sequence: 17,
    id: "OBX-17",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 705,
    table: "HL79999",
    name: "Observation Method",
    item: "936",
  },
  {
    sequence: 18,
    id: "OBX-18",
    required: false,
    repeatable: true,
    datatype: "EI",
    maxLength: 427,
    table: "HL70000",
    name: "Equipment Instance Identifier",
    item: "1479",
  },
  {
    sequence: 19,
    id: "OBX-19",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Date/Time of the Analysis",
    item: "1480",
  },
  {
    sequence: 20,
    id: "OBX-20",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 705,
    table: "HL70163",
    name: "Observation Site",
    item: "2179",
  },
  {
    sequence: 21,
    id: "OBX-21",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 427,
    table: "HL70000",
    name: "Observation Instance Identifier",
    item: "2180",
  },
  {
    sequence: 22,
    id: "OBX-22",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 705,
    table: "HL70725",
    name: "Mood Code",
    item: "2182",
  },
  {
    sequence: 23,
    id: "OBX-23",
    required: false,
    repeatable: true,
    datatype: "XON",
    maxLength: 570,
    table: "HL70000",
    name: "Performing Organization Name",
    item: "2283",
  },
  {
    sequence: 24,
    id: "OBX-24",
    required: false,
    repeatable: true,
    datatype: "XAD",
    maxLength: 2915,
    table: "HL70000",
    name: "Performing Organization Address",
    item: "2284",
  },
  {
    sequence: 25,
    id: "OBX-25",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 3220,
    table: "HL70000",
    name: "Performing Organization Medical Director",
    item: "2285",
  },
] as const;
