// Generated segment profile for PDA (v2.6)

export const segmentId = "PDA";
export const fields = [
  {
    sequence: 1,
    id: "PDA-1",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 705,
    table: "HL70000",
    name: "Death Cause Code",
    item: "1574",
  },
  {
    sequence: 2,
    id: "PDA-2",
    required: false,
    repeatable: false,
    datatype: "PL",
    maxLength: 80,
    table: "HL70000",
    name: "Death Location",
    item: "1575",
  },
  {
    sequence: 3,
    id: "PDA-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Death Certified Indicator",
    item: "1576",
  },
  {
    sequence: 4,
    id: "PDA-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    table: "HL70000",
    name: "Death Certificate Signed Date/Time",
    item: "1577",
  },
  {
    sequence: 5,
    id: "PDA-5",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70000",
    name: "Death Certified By",
    item: "1578",
  },
  {
    sequence: 6,
    id: "PDA-6",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Autopsy Indicator",
    item: "1579",
  },
  {
    sequence: 7,
    id: "PDA-7",
    required: false,
    repeatable: false,
    datatype: "DR",
    maxLength: 53,
    table: "HL70000",
    name: "Autopsy Start and End Date/Time",
    item: "1580",
  },
  {
    sequence: 8,
    id: "PDA-8",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70000",
    name: "Autopsy Performed By",
    item: "1581",
  },
  {
    sequence: 9,
    id: "PDA-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Coroner Indicator",
    item: "1582",
  },
] as const;
