// Generated segment profile for RQD (v2.6)

export const segmentId = "RQD";
export const fields = [
  {
    sequence: 1,
    id: "RQD-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Requisition Line Number",
    item: "275",
  },
  {
    sequence: 2,
    id: "RQD-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Item Code - Internal",
    item: "276",
  },
  {
    sequence: 3,
    id: "RQD-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Item Code - External",
    item: "277",
  },
  {
    sequence: 4,
    id: "RQD-4",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Hospital Item Code",
    item: "278",
  },
  {
    sequence: 5,
    id: "RQD-5",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 6,
    table: "HL70000",
    name: "Requisition Quantity",
    item: "279",
  },
  {
    sequence: 6,
    id: "RQD-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Requisition Unit of Measure",
    item: "280",
  },
  {
    sequence: 7,
    id: "RQD-7",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 30,
    table: "HL70319",
    name: "Cost Center Account Number",
    item: "281",
  },
  {
    sequence: 8,
    id: "RQD-8",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 30,
    table: "HL70320",
    name: "Item Natural Account Code",
    item: "282",
  },
  {
    sequence: 9,
    id: "RQD-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Deliver To ID",
    item: "283",
  },
  {
    sequence: 10,
    id: "RQD-10",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "Date Needed",
    item: "284",
  },
] as const;
