// Generated segment profile for RXE (v2.6)

export const segmentId = "RXE";
export const fields = [
  {
    sequence: 1,
    id: "RXE-1",
    required: false,
    repeatable: false,
    datatype: "TQ",
    name: "Quantity/Timing",
    item: "221",
  },
  {
    sequence: 2,
    id: "RXE-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70292",
    name: "Give Code",
    item: "317",
  },
  {
    sequence: 3,
    id: "RXE-3",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Give Amount - Minimum",
    item: "318",
  },
  {
    sequence: 4,
    id: "RXE-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Give Amount - Maximum",
    item: "319",
  },
  {
    sequence: 5,
    id: "RXE-5",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Give Units",
    item: "320",
  },
  {
    sequence: 6,
    id: "RXE-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Give Dosage Form",
    item: "321",
  },
  {
    sequence: 7,
    id: "RXE-7",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Provider's Administration Instructions",
    item: "298",
  },
  {
    sequence: 8,
    id: "RXE-8",
    required: false,
    repeatable: false,
    datatype: "LA1",
    name: "Deliver-To Location",
    item: "299",
  },
  {
    sequence: 9,
    id: "RXE-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70167",
    name: "Substitution Status",
    item: "322",
  },
  {
    sequence: 10,
    id: "RXE-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Dispense Amount",
    item: "323",
  },
  {
    sequence: 11,
    id: "RXE-11",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Dispense Units",
    item: "324",
  },
  {
    sequence: 12,
    id: "RXE-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    name: "Number Of Refills",
    item: "304",
  },
  {
    sequence: 13,
    id: "RXE-13",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    name: "Ordering Provider's DEA Number",
    item: "305",
  },
  {
    sequence: 14,
    id: "RXE-14",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    name: "Pharmacist/Treatment Supplier's Verifier ID",
    item: "306",
  },
  {
    sequence: 15,
    id: "RXE-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Prescription Number",
    item: "325",
  },
  {
    sequence: 16,
    id: "RXE-16",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Number of Refills Remaining",
    item: "326",
  },
  {
    sequence: 17,
    id: "RXE-17",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Number of Refills/Doses Dispensed",
    item: "327",
  },
  {
    sequence: 18,
    id: "RXE-18",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "D/T of Most Recent Refill or Dose Dispensed",
    item: "328",
  },
  {
    sequence: 19,
    id: "RXE-19",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 10,
    name: "Total Daily Dose",
    item: "329",
  },
  {
    sequence: 20,
    id: "RXE-20",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Needs Human Review",
    item: "307",
  },
  {
    sequence: 21,
    id: "RXE-21",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Pharmacy/Treatment Supplier's Special Dispensing Instructions",
    item: "330",
  },
  {
    sequence: 22,
    id: "RXE-22",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Give Per (Time Unit)",
    item: "331",
  },
  {
    sequence: 23,
    id: "RXE-23",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 6,
    name: "Give Rate Amount",
    item: "332",
  },
  {
    sequence: 24,
    id: "RXE-24",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Give Rate Units",
    item: "333",
  },
  {
    sequence: 25,
    id: "RXE-25",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Give Strength",
    item: "1126",
  },
  {
    sequence: 26,
    id: "RXE-26",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Give Strength Units",
    item: "1127",
  },
  {
    sequence: 27,
    id: "RXE-27",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Give Indication",
    item: "1128",
  },
  {
    sequence: 28,
    id: "RXE-28",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Dispense Package Size",
    item: "1220",
  },
  {
    sequence: 29,
    id: "RXE-29",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Dispense Package Size Unit",
    item: "1221",
  },
  {
    sequence: 30,
    id: "RXE-30",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70321",
    name: "Dispense Package Method",
    item: "1222",
  },
  {
    sequence: 31,
    id: "RXE-31",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Supplementary Code",
    item: "1476",
  },
  {
    sequence: 32,
    id: "RXE-32",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Original Order Date/Time",
    item: "1673",
  },
  {
    sequence: 33,
    id: "RXE-33",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "Give Drug Strength Volume",
    item: "1674",
  },
  {
    sequence: 34,
    id: "RXE-34",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Give Drug Strength Volume Units",
    item: "1675",
  },
  {
    sequence: 35,
    id: "RXE-35",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 60,
    table: "HL70477",
    name: "Controlled Substance Schedule",
    item: "1676",
  },
  {
    sequence: 36,
    id: "RXE-36",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70478",
    name: "Formulary Status",
    item: "1677",
  },
  {
    sequence: 37,
    id: "RXE-37",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 60,
    table: "HL79999",
    name: "Pharmaceutical Substance Alternative",
    item: "1678",
  },
  {
    sequence: 38,
    id: "RXE-38",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Pharmacy of Most Recent Fill",
    item: "1679",
  },
  {
    sequence: 39,
    id: "RXE-39",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 250,
    name: "Initial Dispense Amount",
    item: "1680",
  },
  {
    sequence: 40,
    id: "RXE-40",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL79999",
    name: "Dispensing Pharmacy",
    item: "1681",
  },
  {
    sequence: 41,
    id: "RXE-41",
    required: false,
    repeatable: false,
    datatype: "XAD",
    maxLength: 250,
    name: "Dispensing Pharmacy Address",
    item: "1682",
  },
  {
    sequence: 42,
    id: "RXE-42",
    required: false,
    repeatable: false,
    datatype: "PL",
    maxLength: 80,
    name: "Deliver-to Patient Location",
    item: "1683",
  },
  {
    sequence: 43,
    id: "RXE-43",
    required: false,
    repeatable: false,
    datatype: "XAD",
    maxLength: 250,
    name: "Deliver-to Address",
    item: "1684",
  },
  {
    sequence: 44,
    id: "RXE-44",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70480",
    name: "Pharmacy Order Type",
    item: "1685",
  },
] as const;
