// Generated segment profile for SCP (v2.6)

export const segmentId = "SCP";
export const fields = [
  {
    sequence: 1,
    id: "SCP-1",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    table: "HL70000",
    name: "Number Of Decontamination/Sterilization Devices",
    item: "2087",
  },
  {
    sequence: 2,
    id: "SCP-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70651",
    name: "Labor Calculation Type",
    item: "2088",
  },
  {
    sequence: 3,
    id: "SCP-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70653",
    name: "Date Format",
    item: "2089",
  },
  {
    sequence: 4,
    id: "SCP-4",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 8,
    table: "HL70000",
    name: "Device Number",
    item: "2090",
  },
  {
    sequence: 5,
    id: "SCP-5",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 999,
    table: "HL70000",
    name: "Device Name",
    item: "2279",
  },
  {
    sequence: 6,
    id: "SCP-6",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 2,
    table: "HL70000",
    name: "Device Model Name",
    item: "2091",
  },
  {
    sequence: 7,
    id: "SCP-7",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70657",
    name: "Device Type",
    item: "2092",
  },
  {
    sequence: 8,
    id: "SCP-8",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70659",
    name: "Lot Control",
    item: "2093",
  },
] as const;
