// Generated segment profile for SDD (v2.6)

export const segmentId = "SDD";
export const fields = [
  {
    sequence: 1,
    id: "SDD-1",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 11,
    name: "Lot Number",
    item: "2098",
  },
  {
    sequence: 2,
    id: "SDD-2",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 8,
    name: "Device Number",
    item: "2099",
  },
  {
    sequence: 3,
    id: "SDD-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 999,
    name: "Device Name",
    item: "2281",
  },
  {
    sequence: 4,
    id: "SDD-4",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70667",
    name: "Device Data State",
    item: "2100",
  },
  {
    sequence: 5,
    id: "SDD-5",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 3,
    table: "HL70669",
    name: "Load Status",
    item: "2101",
  },
  {
    sequence: 6,
    id: "SDD-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    name: "Control Code",
    item: "2102",
  },
  {
    sequence: 7,
    id: "SDD-7",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 15,
    name: "Operator Name",
    item: "2103",
  },
] as const;
