// Generated segment profile for TCD (v2.6)

export const segmentId = "TCD";
export const fields = [
  {
    sequence: 1,
    id: "TCD-1",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    name: "Universal Service Identifier",
    item: "238",
  },
  {
    sequence: 2,
    id: "TCD-2",
    required: false,
    repeatable: false,
    datatype: "SN",
    maxLength: 36,
    name: "Auto-Dilution Factor",
    item: "1420",
  },
  {
    sequence: 3,
    id: "TCD-3",
    required: false,
    repeatable: false,
    datatype: "SN",
    maxLength: 36,
    name: "Rerun Dilution Factor",
    item: "1421",
  },
  {
    sequence: 4,
    id: "TCD-4",
    required: false,
    repeatable: false,
    datatype: "SN",
    maxLength: 36,
    name: "Pre-Dilution Factor",
    item: "1422",
  },
  {
    sequence: 5,
    id: "TCD-5",
    required: false,
    repeatable: false,
    datatype: "SN",
    maxLength: 36,
    name: "Endogenous Content of Pre-Dilution Diluent",
    item: "1413",
  },
  {
    sequence: 6,
    id: "TCD-6",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Automatic Repeat Allowed",
    item: "1416",
  },
  {
    sequence: 7,
    id: "TCD-7",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Reflex Allowed",
    item: "1424",
  },
  {
    sequence: 8,
    id: "TCD-8",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    table: "HL70389",
    name: "Analyte Repeat Status",
    item: "1425",
  },
] as const;
