// Generated segment profile for UB1 (v2.6)

export const segmentId = "UB1";
export const fields = [
  {
    sequence: 1,
    id: "UB1-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    table: "HL70000",
    name: "Set ID - UB1",
    item: "530",
  },
  {
    sequence: 2,
    id: "UB1-3",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    table: "HL70000",
    name: "Blood Furnished-Pints",
    item: "532",
  },
  {
    sequence: 3,
    id: "UB1-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    table: "HL70000",
    name: "Blood Replaced-Pints",
    item: "533",
  },
  {
    sequence: 4,
    id: "UB1-5",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    table: "HL70000",
    name: "Blood Not Replaced-Pints",
    item: "534",
  },
  {
    sequence: 5,
    id: "UB1-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    table: "HL70000",
    name: "Co-Insurance Days",
    item: "535",
  },
  {
    sequence: 6,
    id: "UB1-7",
    required: false,
    repeatable: false,
    datatype: "IS",
    table: "HL70043",
    name: "Condition Code",
    item: "536",
  },
  {
    sequence: 7,
    id: "UB1-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    table: "HL70000",
    name: "Covered Days",
    item: "537",
  },
  {
    sequence: 8,
    id: "UB1-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    table: "HL70000",
    name: "Non Covered Days",
    item: "538",
  },
  {
    sequence: 9,
    id: "UB1-10",
    required: false,
    repeatable: false,
    datatype: "UVC",
    table: "HL70000",
    name: "Value Amount &amp; Code",
    item: "539",
  },
  {
    sequence: 10,
    id: "UB1-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    table: "HL70000",
    name: "Number Of Grace Days",
    item: "540",
  },
  {
    sequence: 11,
    id: "UB1-12",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70348",
    name: "Special Program Indicator",
    item: "541",
  },
  {
    sequence: 12,
    id: "UB1-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70349",
    name: "PSRO/UR Approval Indicator",
    item: "542",
  },
  {
    sequence: 13,
    id: "UB1-14",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "PSRO/UR Approved Stay-Fm",
    item: "543",
  },
  {
    sequence: 14,
    id: "UB1-15",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    table: "HL70000",
    name: "PSRO/UR Approved Stay-To",
    item: "544",
  },
  {
    sequence: 15,
    id: "UB1-16",
    required: false,
    repeatable: false,
    datatype: "OCD",
    table: "HL70000",
    name: "Occurrence",
    item: "545",
  },
  {
    sequence: 16,
    id: "UB1-17",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70351",
    name: "Occurrence Span",
    item: "546",
  },
  {
    sequence: 17,
    id: "UB1-18",
    required: false,
    repeatable: false,
    datatype: "DT",
    table: "HL70000",
    name: "Occur Span Start Date",
    item: "547",
  },
  {
    sequence: 18,
    id: "UB1-19",
    required: false,
    repeatable: false,
    datatype: "DT",
    table: "HL70000",
    name: "Occur Span End Date",
    item: "548",
  },
  {
    sequence: 19,
    id: "UB1-20",
    required: false,
    repeatable: false,
    datatype: "ST",
    table: "HL70000",
    name: "UB-82 Locator 2",
    item: "549",
  },
  {
    sequence: 20,
    id: "UB1-21",
    required: false,
    repeatable: false,
    datatype: "ST",
    table: "HL70000",
    name: "UB-82 Locator 9",
    item: "550",
  },
  {
    sequence: 21,
    id: "UB1-22",
    required: false,
    repeatable: false,
    datatype: "ST",
    table: "HL70000",
    name: "UB-82 Locator 27",
    item: "551",
  },
  {
    sequence: 22,
    id: "UB1-23",
    required: false,
    repeatable: false,
    datatype: "ST",
    table: "HL70000",
    name: "UB-82 Locator 45",
    item: "552",
  },
] as const;
