// Generated profile automaton for RSP_Z86 (v2.8)

export const start = 0;
export const finals = new Set<number>([
  8, 10, 11, 12, 18, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 34,
]);
export const alphabet = new Set<string>([
  "AL1",
  "DSC",
  "ERR",
  "MSA",
  "MSH",
  "NTE",
  "OBX",
  "ORC",
  "PD1",
  "PID",
  "QAK",
  "QPD",
  "RXA",
  "RXC",
  "RXD",
  "RXE",
  "RXG",
  "RXO",
  "RXR",
  "SFT",
  "TQ1",
  "TQ2",
  "UAC",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["MSA", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [
    2,
    new Map([
      ["ERR", 6],
      ["QAK", 5],
    ]),
  ],
  [3, new Map([["MSA", 2]])],
  [
    4,
    new Map([
      ["MSA", 2],
      ["SFT", 4],
      ["UAC", 3],
    ]),
  ],
  [5, new Map([["QPD", 7]])],
  [6, new Map([["QAK", 5]])],
  [
    7,
    new Map([
      ["ORC", 8],
      ["PID", 9],
    ]),
  ],
  [
    8,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXD", 15],
      ["RXE", 16],
      ["RXG", 14],
      ["RXO", 17],
      ["TQ1", 18],
    ]),
  ],
  [
    9,
    new Map([
      ["AL1", 19],
      ["NTE", 20],
      ["ORC", 8],
      ["PD1", 21],
    ]),
  ],
  [10, new Map([])],
  [
    11,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
    ]),
  ],
  [
    12,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
    ]),
  ],
  [13, new Map([["RXR", 22]])],
  [14, new Map([["RXR", 23]])],
  [15, new Map([["RXR", 24]])],
  [
    16,
    new Map([
      ["RXR", 25],
      ["TQ1", 26],
    ]),
  ],
  [17, new Map([["RXR", 27]])],
  [
    18,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXD", 15],
      ["RXE", 16],
      ["RXG", 14],
      ["RXO", 17],
      ["TQ1", 18],
      ["TQ2", 28],
    ]),
  ],
  [
    19,
    new Map([
      ["AL1", 19],
      ["ORC", 8],
    ]),
  ],
  [
    20,
    new Map([
      ["AL1", 19],
      ["NTE", 20],
      ["ORC", 8],
    ]),
  ],
  [
    21,
    new Map([
      ["AL1", 19],
      ["NTE", 20],
      ["ORC", 8],
    ]),
  ],
  [
    22,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXC", 29],
      ["RXR", 22],
    ]),
  ],
  [
    23,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 30],
      ["RXR", 23],
    ]),
  ],
  [
    24,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 31],
      ["RXG", 14],
      ["RXR", 24],
    ]),
  ],
  [
    25,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 32],
      ["RXD", 15],
      ["RXG", 14],
      ["RXR", 25],
    ]),
  ],
  [
    26,
    new Map([
      ["RXR", 25],
      ["TQ1", 26],
      ["TQ2", 33],
    ]),
  ],
  [
    27,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 34],
      ["RXD", 15],
      ["RXE", 16],
      ["RXG", 14],
      ["RXR", 27],
    ]),
  ],
  [
    28,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXD", 15],
      ["RXE", 16],
      ["RXG", 14],
      ["RXO", 17],
      ["TQ1", 18],
      ["TQ2", 28],
    ]),
  ],
  [
    29,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXC", 29],
    ]),
  ],
  [
    30,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 30],
    ]),
  ],
  [
    31,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 31],
      ["RXG", 14],
    ]),
  ],
  [
    32,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 32],
      ["RXD", 15],
      ["RXG", 14],
    ]),
  ],
  [
    33,
    new Map([
      ["RXR", 25],
      ["TQ1", 26],
      ["TQ2", 33],
    ]),
  ],
  [
    34,
    new Map([
      ["DSC", 10],
      ["NTE", 11],
      ["OBX", 12],
      ["ORC", 8],
      ["PID", 9],
      ["RXA", 13],
      ["RXC", 34],
      ["RXD", 15],
      ["RXE", 16],
      ["RXG", 14],
    ]),
  ],
]);
export const effects = {
  "11:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "11:NTE": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "11:OBX": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "11:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "11:PID": {
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "12:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "12:OBX": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "12:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "12:PID": {
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "16:RXR": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
    groupsOpened: [],
  },
  "16:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
  },
  "18:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "18:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "18:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "18:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "18:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "18:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "18:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "18:RXE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
  },
  "18:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "18:RXO": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL"],
  },
  "18:TQ1": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING"],
  },
  "19:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "20:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "21:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "22:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "22:NTE": {
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "22:OBX": {
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "22:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "22:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "23:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "23:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "23:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "23:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "23:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "23:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "24:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "24:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "24:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "24:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "24:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "24:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "24:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "25:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "25:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "25:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "25:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "25:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "25:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "25:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "25:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "26:RXR": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
    groupsOpened: [],
  },
  "26:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
  },
  "27:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "27:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "27:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "27:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "27:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "27:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "27:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "27:RXE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
  },
  "27:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "28:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "28:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "28:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "28:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "28:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "28:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "28:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "28:RXE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
  },
  "28:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "28:RXO": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL"],
  },
  "28:TQ1": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING"],
  },
  "29:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "29:NTE": {
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "29:OBX": {
    groupsClosed: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "29:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "29:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "30:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "30:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "30:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "30:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "30:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "30:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "31:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "31:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "31:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "31:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "31:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "31:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "31:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "32:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "32:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "32:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "32:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "32:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "32:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "32:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "32:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "33:RXR": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
    groupsOpened: [],
  },
  "33:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER/TIMING_ENCODED",
    ],
  },
  "34:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "34:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "34:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "34:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "34:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "34:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "34:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "34:RXE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
  },
  "34:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "7:ORC": {
    groupsClosed: [],
    groupsOpened: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
    ],
  },
  "7:PID": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "8:DSC": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: [],
  },
  "8:NTE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "8:OBX": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION"],
  },
  "8:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
  "8:PID": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE", "RSP_Z86/QUERY_RESPONSE/PATIENT"],
  },
  "8:RXA": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION"],
  },
  "8:RXD": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE"],
  },
  "8:RXE": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER"],
  },
  "8:RXG": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE"],
  },
  "8:RXO": {
    groupsClosed: [
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ADMINISTRATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/DISPENSE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ENCODED_ORDER",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/GIVE",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/OBSERVATION",
      "RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING",
      "RSP_Z86/QUERY_RESPONSE/PATIENT",
    ],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/ORDER_DETAIL"],
  },
  "8:TQ1": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER/TIMING"],
  },
  "9:ORC": {
    groupsClosed: [],
    groupsOpened: ["RSP_Z86/QUERY_RESPONSE/COMMON_ORDER"],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
