// Generated table profile for 0396 (v2.5.1)

export const id = "0396";
export const description = "Coding system";
export const type = "hl7";
export const codes = [
  {
    description: "Local general code (where z is an alphanumeric character)",
    name: "99zzz or L",
  },
  { description: "American College of Radiology finding codes", name: "ACR" },
  { description: "HL7 set of units of measure", name: "ANS+" },
  { description: "WHO Adverse Reaction Terms", name: "ART" },
  { description: "ASTM E1238/ E1467 Universal", name: "AS4" },
  { description: "AS4 Neurophysiology Codes", name: "AS4E" },
  { description: "American Type Culture Collection", name: "ATC" },
  { description: "CPT-4", name: "C4" },
  { description: "CPT-5", name: "C5" },
  { description: "Chemical abstract codes", name: "CAS" },
  { description: "CDT-2 Codes", name: "CD2" },
  { description: "CDC Analyte Codes", name: "CDCA" },
  { description: "CDC Methods/Instruments Codes", name: "CDCM" },
  { description: "CDC Surveillance", name: "CDS" },
  { description: "CEN ECG diagnostic codes", name: "CE" },
  { description: "CLIP", name: "CLP" },
  { description: "CPT Modifier Code", name: "CPTM" },
  { description: "COSTART", name: "CST" },
  { description: "CDC Vaccine Codes", name: "CVX" },
  { description: "DICOM Controlled Terminology", name: "DCM" },
  { description: "EUCLIDES", name: "E" },
  { description: "Euclides  quantity codes", name: "E5" },
  { description: "Euclides Lab method codes", name: "E6" },
  { description: "Euclides Lab equipment codes", name: "E7" },
  { description: "Enzyme Codes", name: "ENZC" },
  { description: "First DataBank Drug Codes", name: "FDDC" },
  { description: "First DataBank Diagnostic Codes", name: "FDDX" },
  { description: "FDA K10", name: "FDK" },
  { description: "HIBCC", name: "HB" },
  {
    description: "CMS (formerly HCFA)  Common Procedure Coding System",
    name: "HCPCS",
  },
  { description: "Health Care Provider Taxonomy", name: "HCPT" },
  { description: "Home Health Care", name: "HHC" },
  { description: "Health Outcomes", name: "HI" },
  {
    description: "HL7 Defined Codes where nnnn is the HL7 table number",
    name: "HL7nnnn",
  },
  { description: "Japanese Nationwide Medicine Code", name: "HOT" },
  { description: "CMS (formerly HCFA )Procedure Codes (HCPCS)", name: "HPC" },
  { description: "ICD-10", name: "I10" },
  { description: "ICD-10  Procedure Codes", name: "I10P" },
  { description: "ICD9", name: "I9" },
  { description: "ICD-9CM", name: "I9C" },
  { description: "ISBT", name: "IBT" },
  {
    description:
      "ISBT 128 codes where nnnn  specifies a specific table within ISBT 128.",
    name: "IBTnnnn",
  },
  { description: "ICHPPC-2", name: "IC2" },
  { description: "ICD-10 Australian modification", name: "ICD10AM" },
  { description: "ICD-10 Canada", name: "ICD10CA" },
  {
    description: "International Classification of Diseases for Oncology",
    name: "ICDO",
  },
  { description: "ICCS", name: "ICS" },
  {
    description: "International Classification of Sleep Disorders",
    name: "ICSD",
  },
  {
    description: "ISO 2955.83 (units of measure) with HL7 extensions",
    name: "ISO+",
  },
  {
    description: "ISO Defined Codes where nnnn is the ISO table number",
    name: "ISOnnnn",
  },
  { description: "IUPAC/IFCC Component Codes", name: "IUPC" },
  { description: "IUPAC/IFCC Property Codes", name: "IUPP" },
  { description: "JLAC/JSLM, nationwide laboratory code", name: "JC10" },
  { description: "Japanese Chemistry", name: "JC8" },
  { description: "Japanese Image Examination Cache", name: "JJ1017" },
  { description: "Local billing code", name: "LB" },
  {
    description: "Logical Observation Identifier Names and Codes (LOINCÂ®)",
    name: "LN",
  },
  { description: "Medicaid", name: "MCD" },
  { description: "Medicare", name: "MCR" },
  { description: "Medispan Diagnostic Codes", name: "MDDX" },
  { description: "Medical Economics Drug Codes", name: "MEDC" },
  {
    description: "Medical Dictionary for Drug Regulatory Affairs (MEDDRA)",
    name: "MEDR",
  },
  { description: "Medical Economics Diagnostic Codes", name: "MEDX" },
  { description: "Medispan GPI", name: "MGPI" },
  { description: "CDC Vaccine Manufacturer Codes", name: "MVX" },
  { description: "NANDA", name: "NDA" },
  { description: "National drug codes", name: "NDC" },
  { description: "Nursing Interventions Classification", name: "NIC" },
  { description: "National Provider Identifier", name: "NPI" },
  { description: "National Uniform Billing Committee Code", name: "NUBC" },
  { description: "Omaha System", name: "OHA" },
  { description: "POS Codes", name: "POS" },
  { description: "Read Classification", name: "RC" },
  { description: "SNOMED- DICOM Microglossary", name: "SDM" },
  { description: "Systemized Nomenclature of Medicine (SNOMED)", name: "SNM" },
  { description: "SNOMED International", name: "SNM3" },
  { description: "SNOMED topology codes (anatomic sites)", name: "SNT" },
  { description: "UCDS", name: "UC" },
  { description: "MDNS", name: "UMD" },
  { description: "Unified Medical Language", name: "UML" },
  { description: "Universal Product Code", name: "UPC" },
  { description: "UPIN", name: "UPIN" },
  { description: "United States Postal Service", name: "USPS" },
  { description: "WHO record # drug codes (6 digit)", name: "W1" },
  { description: "WHO record # drug codes (8 digit)", name: "W2" },
  { description: "WHO record # code with ASTM extension", name: "W4" },
  { description: "WHO ATC", name: "WC" },
] as const;
