// Generated segment profile for BHS (v2.5.1)

export const segmentId = "BHS";
export const fields = [
  {
    datatype: "ST",
    id: "BHS-1",
    item: "81",
    maxLength: 1,
    name: "Batch Field Separator",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "BHS-2",
    item: "82",
    maxLength: 3,
    name: "Batch Encoding Characters",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "HD",
    id: "BHS-3",
    item: "83",
    maxLength: 227,
    name: "Batch Sending Application",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "HD",
    id: "BHS-4",
    item: "84",
    maxLength: 227,
    name: "Batch Sending Facility",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "HD",
    id: "BHS-5",
    item: "85",
    maxLength: 227,
    name: "Batch Receiving Application",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "HD",
    id: "BHS-6",
    item: "86",
    maxLength: 227,
    name: "Batch Receiving Facility",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "BHS-7",
    item: "87",
    maxLength: 26,
    name: "Batch Creation Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "BHS-8",
    item: "88",
    maxLength: 40,
    name: "Batch Security",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "BHS-9",
    item: "89",
    maxLength: 20,
    name: "Batch Name/ID/Type",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "BHS-10",
    item: "90",
    maxLength: 80,
    name: "Batch Comment",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "BHS-11",
    item: "91",
    maxLength: 20,
    name: "Batch Control ID",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "BHS-12",
    item: "92",
    maxLength: 20,
    name: "Reference Batch Control ID",
    repeatable: false,
    required: false,
    sequence: 12,
  },
] as const;
