// Generated segment profile for BPX (v2.5.1)

export const segmentId = "BPX";
export const fields = [
  {
    datatype: "SI",
    id: "BPX-1",
    item: "1714",
    maxLength: 4,
    name: "Set ID - BPX",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "BPX-2",
    item: "1715",
    maxLength: 250,
    name: "BP Dispense Status",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70510",
  },
  {
    datatype: "ID",
    id: "BPX-3",
    item: "1716",
    maxLength: 1,
    name: "BP Status",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70511",
  },
  {
    datatype: "TS",
    id: "BPX-4",
    item: "1717",
    maxLength: 26,
    name: "BP Date/Time of Status",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "EI",
    id: "BPX-5",
    item: "1718",
    maxLength: 22,
    name: "BC Donation ID",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CNE",
    id: "BPX-6",
    item: "1719",
    maxLength: 250,
    name: "BC Component",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CNE",
    id: "BPX-7",
    item: "1720",
    maxLength: 250,
    name: "BC Donation Type / Intended Use",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CWE",
    id: "BPX-8",
    item: "1721",
    maxLength: 250,
    name: "CP Commercial Product",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70512",
  },
  {
    datatype: "XON",
    id: "BPX-9",
    item: "1722",
    maxLength: 250,
    name: "CP Manufacturer",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "EI",
    id: "BPX-10",
    item: "1723",
    maxLength: 22,
    name: "CP Lot Number",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CNE",
    id: "BPX-11",
    item: "1724",
    maxLength: 250,
    name: "BP Blood Group",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CNE",
    id: "BPX-12",
    item: "1725",
    maxLength: 250,
    name: "BC Special Testing",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "TS",
    id: "BPX-13",
    item: "1726",
    maxLength: 26,
    name: "BP Expiration Date/Time",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "NM",
    id: "BPX-14",
    item: "1727",
    maxLength: 5,
    name: "BP Quantity",
    repeatable: false,
    required: true,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "BPX-15",
    item: "1728",
    maxLength: 5,
    name: "BP Amount",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CE",
    id: "BPX-16",
    item: "1729",
    maxLength: 250,
    name: "BP Units",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "EI",
    id: "BPX-17",
    item: "1730",
    maxLength: 22,
    name: "BP Unique ID",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "PL",
    id: "BPX-18",
    item: "1731",
    maxLength: 80,
    name: "BP Actual Dispensed To Location",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "XAD",
    id: "BPX-19",
    item: "1732",
    maxLength: 250,
    name: "BP Actual Dispensed To Address",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "XCN",
    id: "BPX-20",
    item: "1733",
    maxLength: 250,
    name: "BP Dispensed to Receiver",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "XCN",
    id: "BPX-21",
    item: "1734",
    maxLength: 250,
    name: "BP Dispensing Individual",
    repeatable: false,
    required: false,
    sequence: 21,
  },
] as const;
