// Generated segment profile for EQP (v2.5.1)

export const segmentId = "EQP";
export const fields = [
  {
    sequence: 1,
    id: "EQP-1",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70450",
    name: "Event type",
    item: "1430",
  },
  {
    sequence: 2,
    id: "EQP-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "File Name",
    item: "1431",
  },
  {
    sequence: 3,
    id: "EQP-3",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Start Date/Time",
    item: "1202",
  },
  {
    sequence: 4,
    id: "EQP-4",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "End Date/Time",
    item: "1432",
  },
  {
    sequence: 5,
    id: "EQP-5",
    required: true,
    repeatable: false,
    datatype: "FT",
    maxLength: 65_536,
    name: "Transaction Data",
    item: "1433",
  },
] as const;
