// Generated segment profile for FAC (v2.5.1)

export const segmentId = "FAC";
export const fields = [
  {
    datatype: "EI",
    id: "FAC-1",
    item: "1262",
    maxLength: 20,
    name: "Facility ID-FAC",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "FAC-2",
    item: "1263",
    maxLength: 1,
    name: "Facility Type",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70331",
  },
  {
    datatype: "XAD",
    id: "FAC-3",
    item: "1264",
    maxLength: 250,
    name: "Facility Address",
    repeatable: true,
    required: true,
    sequence: 3,
  },
  {
    datatype: "XTN",
    id: "FAC-4",
    item: "1265",
    maxLength: 250,
    name: "Facility Telecommunication",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "XCN",
    id: "FAC-5",
    item: "1266",
    maxLength: 250,
    name: "Contact Person",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "FAC-6",
    item: "1267",
    maxLength: 60,
    name: "Contact Title",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XAD",
    id: "FAC-7",
    item: "1166",
    maxLength: 250,
    name: "Contact Address",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "XTN",
    id: "FAC-8",
    item: "1269",
    maxLength: 250,
    name: "Contact Telecommunication",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "XCN",
    id: "FAC-9",
    item: "1270",
    maxLength: 250,
    name: "Signature Authority",
    repeatable: true,
    required: true,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "FAC-10",
    item: "1271",
    maxLength: 60,
    name: "Signature Authority Title",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XAD",
    id: "FAC-11",
    item: "1272",
    maxLength: 250,
    name: "Signature Authority Address",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "XTN",
    id: "FAC-12",
    item: "1273",
    maxLength: 250,
    name: "Signature Authority Telecommunication",
    repeatable: false,
    required: false,
    sequence: 12,
  },
] as const;
