// Generated segment profile for OM1 (v2.5.1)

export const segmentId = "OM1";
export const fields = [
  {
    datatype: "NM",
    id: "OM1-1",
    item: "586",
    maxLength: 4,
    name: "Sequence Number - Test/Observation Master File",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "OM1-2",
    item: "587",
    maxLength: 250,
    name: "Producer&apos;s Service/Test/Observation ID",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL79999",
  },
  {
    datatype: "ID",
    id: "OM1-3",
    item: "588",
    maxLength: 12,
    name: "Permitted Data Types",
    repeatable: true,
    required: false,
    sequence: 3,
    table: "HL70125",
  },
  {
    datatype: "ID",
    id: "OM1-4",
    item: "589",
    maxLength: 1,
    name: "Specimen Required",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70136",
  },
  {
    datatype: "CE",
    id: "OM1-5",
    item: "590",
    maxLength: 250,
    name: "Producer ID",
    repeatable: false,
    required: true,
    sequence: 5,
    table: "HL79999",
  },
  {
    datatype: "TX",
    id: "OM1-6",
    item: "591",
    maxLength: 200,
    name: "Observation Description",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "OM1-7",
    item: "592",
    maxLength: 250,
    name: "Other Service/Test/Observation IDs for the Observation",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL79999",
  },
  {
    datatype: "ST",
    id: "OM1-8",
    item: "593",
    maxLength: 200,
    name: "Other Names",
    repeatable: true,
    required: true,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "OM1-9",
    item: "594",
    maxLength: 30,
    name: "Preferred Report Name for the Observation",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "OM1-10",
    item: "595",
    maxLength: 8,
    name: "Preferred Short Name or Mnemonic for Observation",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ST",
    id: "OM1-11",
    item: "596",
    maxLength: 200,
    name: "Preferred Long Name for the Observation",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "OM1-12",
    item: "597",
    maxLength: 1,
    name: "Orderability",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70136",
  },
  {
    datatype: "CE",
    id: "OM1-13",
    item: "598",
    maxLength: 250,
    name: "Identity of Instrument Used to Perform this Study",
    repeatable: true,
    required: false,
    sequence: 13,
    table: "HL79999",
  },
  {
    datatype: "CE",
    id: "OM1-14",
    item: "599",
    maxLength: 250,
    name: "Coded Representation of Method",
    repeatable: true,
    required: false,
    sequence: 14,
    table: "HL79999",
  },
  {
    datatype: "ID",
    id: "OM1-15",
    item: "600",
    maxLength: 1,
    name: "Portable Device Indicator",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70136",
  },
  {
    datatype: "CE",
    id: "OM1-16",
    item: "601",
    maxLength: 250,
    name: "Observation Producing Department/Section",
    repeatable: true,
    required: false,
    sequence: 16,
    table: "HL79999",
  },
  {
    datatype: "XTN",
    id: "OM1-17",
    item: "602",
    maxLength: 250,
    name: "Telephone Number of Section",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "IS",
    id: "OM1-18",
    item: "603",
    maxLength: 1,
    name: "Nature of Service/Test/Observation",
    repeatable: false,
    required: true,
    sequence: 18,
    table: "HL70174",
  },
  {
    datatype: "CE",
    id: "OM1-19",
    item: "604",
    maxLength: 250,
    name: "Report Subheader",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL79999",
  },
  {
    datatype: "ST",
    id: "OM1-20",
    item: "605",
    maxLength: 20,
    name: "Report Display Order",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "TS",
    id: "OM1-21",
    item: "606",
    maxLength: 26,
    name: "Date/Time Stamp for any change in Definition for the Observation",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "TS",
    id: "OM1-22",
    item: "607",
    maxLength: 26,
    name: "Effective Date/Time of Change",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "NM",
    id: "OM1-23",
    item: "608",
    maxLength: 20,
    name: "Typical Turn-Around Time",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "NM",
    id: "OM1-24",
    item: "609",
    maxLength: 20,
    name: "Processing Time",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ID",
    id: "OM1-25",
    item: "610",
    maxLength: 40,
    name: "Processing Priority",
    repeatable: true,
    required: false,
    sequence: 25,
    table: "HL70168",
  },
  {
    datatype: "ID",
    id: "OM1-26",
    item: "611",
    maxLength: 5,
    name: "Reporting Priority",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70169",
  },
  {
    datatype: "CE",
    id: "OM1-27",
    item: "612",
    maxLength: 250,
    name: "Outside Site(s) Where Observation may be Performed",
    repeatable: true,
    required: false,
    sequence: 27,
    table: "HL79999",
  },
  {
    datatype: "XAD",
    id: "OM1-28",
    item: "613",
    maxLength: 250,
    name: "Address of Outside Site(s)",
    repeatable: true,
    required: false,
    sequence: 28,
  },
  {
    datatype: "XTN",
    id: "OM1-29",
    item: "614",
    maxLength: 250,
    name: "Phone Number of Outside Site",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CWE",
    id: "OM1-30",
    item: "615",
    maxLength: 250,
    name: "Confidentiality Code",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70177",
  },
  {
    datatype: "CE",
    id: "OM1-31",
    item: "616",
    maxLength: 250,
    name: "Observations Required to Interpret the Observation",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL79999",
  },
  {
    datatype: "TX",
    id: "OM1-32",
    item: "617",
    maxLength: 65_536,
    name: "Interpretation of Observations",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "CE",
    id: "OM1-33",
    item: "618",
    maxLength: 250,
    name: "Contraindications to Observations",
    repeatable: false,
    required: false,
    sequence: 33,
    table: "HL79999",
  },
  {
    datatype: "CE",
    id: "OM1-34",
    item: "619",
    maxLength: 250,
    name: "Reflex Tests/Observations",
    repeatable: true,
    required: false,
    sequence: 34,
    table: "HL79999",
  },
  {
    datatype: "TX",
    id: "OM1-35",
    item: "620",
    maxLength: 80,
    name: "Rules that Trigger Reflex Testing",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "CE",
    id: "OM1-36",
    item: "621",
    maxLength: 250,
    name: "Fixed Canned Message",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL79999",
  },
  {
    datatype: "TX",
    id: "OM1-37",
    item: "622",
    maxLength: 200,
    name: "Patient Preparation",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "CE",
    id: "OM1-38",
    item: "623",
    maxLength: 250,
    name: "Procedure Medication",
    repeatable: false,
    required: false,
    sequence: 38,
    table: "HL79999",
  },
  {
    datatype: "TX",
    id: "OM1-39",
    item: "624",
    maxLength: 200,
    name: "Factors that may Affect the Observation",
    repeatable: false,
    required: false,
    sequence: 39,
  },
  {
    datatype: "ST",
    id: "OM1-40",
    item: "625",
    maxLength: 60,
    name: "Service/Test/Observation Performance Schedule",
    repeatable: true,
    required: false,
    sequence: 40,
  },
  {
    datatype: "TX",
    id: "OM1-41",
    item: "626",
    maxLength: 65_536,
    name: "Description of Test Methods",
    repeatable: false,
    required: false,
    sequence: 41,
  },
  {
    datatype: "CE",
    id: "OM1-42",
    item: "937",
    maxLength: 250,
    name: "Kind of Quantity Observed",
    repeatable: false,
    required: false,
    sequence: 42,
    table: "HL70254",
  },
  {
    datatype: "CE",
    id: "OM1-43",
    item: "938",
    maxLength: 250,
    name: "Point Versus Interval",
    repeatable: false,
    required: false,
    sequence: 43,
    table: "HL70255",
  },
  {
    datatype: "TX",
    id: "OM1-44",
    item: "939",
    maxLength: 200,
    name: "Challenge Information",
    repeatable: false,
    required: false,
    sequence: 44,
    table: "HL70256",
  },
  {
    datatype: "CE",
    id: "OM1-45",
    item: "940",
    maxLength: 250,
    name: "Relationship Modifier",
    repeatable: false,
    required: false,
    sequence: 45,
    table: "HL70258",
  },
  {
    datatype: "CE",
    id: "OM1-46",
    item: "941",
    maxLength: 250,
    name: "Target Anatomic Site Of Test",
    repeatable: false,
    required: false,
    sequence: 46,
    table: "HL79999",
  },
  {
    datatype: "CE",
    id: "OM1-47",
    item: "942",
    maxLength: 250,
    name: "Modality Of Imaging Measurement",
    repeatable: false,
    required: false,
    sequence: 47,
    table: "HL70259",
  },
] as const;
