// Generated segment profile for QRD (v2.5.1)

export const segmentId = "QRD";
export const fields = [
  {
    datatype: "TS",
    id: "QRD-1",
    item: "25",
    maxLength: 26,
    name: "Query Date/Time",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "QRD-2",
    item: "26",
    maxLength: 1,
    name: "Query Format Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70106",
  },
  {
    datatype: "ID",
    id: "QRD-3",
    item: "27",
    maxLength: 1,
    name: "Query Priority",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70091",
  },
  {
    datatype: "ST",
    id: "QRD-4",
    item: "28",
    maxLength: 10,
    name: "Query ID",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "ID",
    id: "QRD-5",
    item: "29",
    maxLength: 1,
    name: "Deferred Response Type",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70107",
  },
  {
    datatype: "TS",
    id: "QRD-6",
    item: "30",
    maxLength: 26,
    name: "Deferred Response Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CQ",
    id: "QRD-7",
    item: "31",
    maxLength: 10,
    name: "Quantity Limited Request",
    repeatable: false,
    required: true,
    sequence: 7,
    table: "HL70126",
  },
  {
    datatype: "XCN",
    id: "QRD-8",
    item: "32",
    maxLength: 250,
    name: "Who Subject Filter",
    repeatable: true,
    required: true,
    sequence: 8,
  },
  {
    datatype: "CE",
    id: "QRD-9",
    item: "33",
    maxLength: 250,
    name: "What Subject Filter",
    repeatable: true,
    required: true,
    sequence: 9,
    table: "HL70048",
  },
  {
    datatype: "CE",
    id: "QRD-10",
    item: "34",
    maxLength: 250,
    name: "What Department Data Code",
    repeatable: true,
    required: true,
    sequence: 10,
  },
  {
    datatype: "VR",
    id: "QRD-11",
    item: "35",
    maxLength: 20,
    name: "What Data Code Value Qual.",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "QRD-12",
    item: "36",
    maxLength: 1,
    name: "Query Results Level",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70108",
  },
] as const;
