// Generated segment profile for RCP (v2.5.1)

export const segmentId = "RCP";
export const fields = [
  {
    datatype: "ID",
    id: "RCP-1",
    item: "27",
    maxLength: 1,
    name: "Query Priority",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70091",
  },
  {
    datatype: "CQ",
    id: "RCP-2",
    item: "31",
    maxLength: 10,
    name: "Quantity Limited Request",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70126",
  },
  {
    datatype: "CE",
    id: "RCP-3",
    item: "1440",
    maxLength: 250,
    name: "Response Modality",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70394",
  },
  {
    datatype: "TS",
    id: "RCP-4",
    item: "1441",
    maxLength: 26,
    name: "Execution and Delivery Time",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ID",
    id: "RCP-5",
    item: "1443",
    maxLength: 1,
    name: "Modify Indicator",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70395",
  },
  {
    datatype: "SRT",
    id: "RCP-6",
    item: "1624",
    maxLength: 512,
    name: "Sort-by Field",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "RCP-7",
    item: "1594",
    maxLength: 256,
    name: "Segment group inclusion",
    repeatable: true,
    required: false,
    sequence: 7,
  },
] as const;
