// Generated segment profile for RQD (v2.5.1)

export const segmentId = "RQD";
export const fields = [
  {
    datatype: "SI",
    id: "RQD-1",
    item: "275",
    maxLength: 4,
    name: "Requisition Line Number",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "RQD-2",
    item: "276",
    maxLength: 250,
    name: "Item Code - Internal",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CE",
    id: "RQD-3",
    item: "277",
    maxLength: 250,
    name: "Item Code - External",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "RQD-4",
    item: "278",
    maxLength: 250,
    name: "Hospital Item Code",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "RQD-5",
    item: "279",
    maxLength: 6,
    name: "Requisition Quantity",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "RQD-6",
    item: "280",
    maxLength: 250,
    name: "Requisition Unit of Measure",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "IS",
    id: "RQD-7",
    item: "281",
    maxLength: 30,
    name: "Dept. Cost Center",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70319",
  },
  {
    datatype: "IS",
    id: "RQD-8",
    item: "282",
    maxLength: 30,
    name: "Item Natural Account Code",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70320",
  },
  {
    datatype: "CE",
    id: "RQD-9",
    item: "283",
    maxLength: 250,
    name: "Deliver To ID",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "DT",
    id: "RQD-10",
    item: "284",
    maxLength: 8,
    name: "Date Needed",
    repeatable: false,
    required: false,
    sequence: 10,
  },
] as const;
