// Generated table profile for 0119 (v2.3.1)

export const id = "0119";
export const description = "Order control codes";
export const type = "hl7";
export const codes = [
  { description: "Order refill request approval (O02)", name: "AF" },
  { description: "Cancel order request (O01)", name: "CA" },
  { description: "Child order (O01/ORU)", name: "CH" },
  { description: "Combined result (R01)", name: "CN" },
  { description: "Canceled as requested (O02)", name: "CR" },
  { description: "Discontinue order request (O01)", name: "DC" },
  { description: "Data errors (O01/O02)", name: "DE" },
  { description: "Order refill request denied (O02)", name: "DF" },
  { description: "Discontinued as requested (O02)", name: "DR" },
  { description: "Order refilled, unsolicited (O01)", name: "FU" },
  { description: "Hold order request (O01)", name: "HD" },
  { description: "On hold as requested (O02)", name: "HR" },
  { description: "Link order to patient care problem or goal", name: "LI" },
  { description: "Number assigned (O02)", name: "NA" },
  { description: "New order (O01)", name: "NW" },
  { description: "Order canceled (O01)", name: "OC" },
  { description: "Order discontinued (O01)", name: "OD" },
  { description: "Order released (O01)", name: "OE" },
  { description: "Order refilled as requested (O02)", name: "OF" },
  { description: "Order held (O01)", name: "OH" },
  { description: "Order accepted & OK (O02)", name: "OK" },
  { description: "Released as requested", name: "OR" },
  { description: "Parent order (O01/ORU)", name: "PA" },
  { description: "Observations to follow (O01/R01)", name: "RE" },
  { description: "Refill order request (O01)", name: "RF" },
  { description: "Release previous hold (O01)", name: "RL" },
  { description: "Replacement order (O01)", name: "RO" },
  { description: "Order replace request (O01)", name: "RP" },
  { description: "Replaced as requested (O02)", name: "RQ" },
  { description: "Request received (O02)", name: "RR" },
  { description: "Replaced unsolicited (O01)", name: "RU" },
  { description: "Status changed (O01)", name: "SC" },
  { description: "Send order number (O01)", name: "SN" },
  {
    description: "Response to send order status request (O02(Q06)",
    name: "SR",
  },
  { description: "Send order status request (O01)", name: "SS" },
  { description: "Unable to accept order (O02/ORR)", name: "UA" },
  { description: "Unable to cancel (O02)", name: "UC" },
  { description: "Unable to discontinue (O02)", name: "UD" },
  { description: "Unable to refill (O02)", name: "UF" },
  { description: "Unable to put on hold (O02)", name: "UH" },
  { description: "Unable to replace (O02)", name: "UM" },
  { description: "Unlink order from patient care problem or goal", name: "UN" },
  { description: "Unable to release (O02)", name: "UR" },
  { description: "Unable to change (O02)", name: "UX" },
  { description: "Change order request (O01)", name: "XO" },
  { description: "Changed as requested (O02)", name: "XR" },
  { description: "Order changed, unsol. (O01)", name: "XX" },
] as const;
