// Generated table profile for 0292 (v2.3.1)

export const id = "0292";
export const description = "Vaccines administered";
export const type = "hl7";
export const codes = [
  { description: "DTP", name: "01" },
  { description: "OPV", name: "02" },
  { description: "MMR", name: "03" },
  { description: "M/R", name: "04" },
  { description: "Measles", name: "05" },
  { description: "Rubella", name: "06" },
  { description: "Mumps", name: "07" },
  { description: "Hep B, adolescent or pediatric", name: "08" },
  { description: "Td (Adult)", name: "09" },
  { description: "IPV", name: "10" },
  { description: "Pertussis", name: "11" },
  { description: "Diphtheria antitoxin", name: "12" },
  { description: "TIG", name: "13" },
  { description: "IG, NOS", name: "14" },
  {
    description: "Influenza—split (incl. purified surface antigen)",
    name: "15",
  },
  { description: "Influenza—whole", name: "16" },
  { description: "Hib,  NOS", name: "17" },
  { description: "Rabies, intramuscular injection", name: "18" },
  { description: "BCG", name: "19" },
  { description: "DTaP", name: "20" },
  { description: "Varicella", name: "21" },
  { description: "DTP-Hib", name: "22" },
  { description: "Plague", name: "23" },
  { description: "Anthrax", name: "24" },
  { description: "Typhoid—oral", name: "25" },
  { description: "Cholera", name: "26" },
  { description: "Botulinum antitoxin", name: "27" },
  { description: "DT(pediatric)", name: "28" },
  { description: "CMVIG", name: "29" },
  { description: "HBIG", name: "30" },
  { description: "Hep A, pediatric, NOS", name: "31" },
  { description: "Meningococcal", name: "32" },
  { description: "Pneumococcal", name: "33" },
  { description: "RIG", name: "34" },
  { description: "Tetanus toxoid", name: "35" },
  { description: "VZIG", name: "36" },
  { description: "Yellow fever", name: "37" },
  { description: "Rubella/Mumps", name: "38" },
  { description: "Japanese encephalitis", name: "39" },
  { description: "Rabies, intradermal injection", name: "40" },
  { description: "Typhoid—parenteral", name: "41" },
  { description: "Hep B, adolescent/high risk infant", name: "42" },
  { description: "Hep B, adult", name: "43" },
  { description: "Hep B, dialysis", name: "44" },
  { description: "Hep B,  NOS", name: "45" },
  { description: "Hib (PRP-D)", name: "46" },
  { description: "Hib (HbOC)", name: "47" },
  { description: "Hib (PRP-T)", name: "48" },
  { description: "Hib (PRP-OMP)", name: "49" },
  { description: "DtaP-Hib", name: "50" },
  { description: "Hib-Hep B", name: "51" },
  { description: "Hep A - adult", name: "52" },
  { description: "Typhoid, parenteral, AKD (U.S. military)", name: "53" },
  { description: "Adenovirus, type 4", name: "54" },
  { description: "Adenovirus, type 7", name: "55" },
  { description: "Dengue fever", name: "56" },
  { description: "Hantavirus", name: "57" },
  { description: "Hep C", name: "58" },
  { description: "Hep E", name: "59" },
  { description: "Herpes simplex 2", name: "60" },
  { description: "HIV", name: "61" },
  { description: "HPV", name: "62" },
  { description: "Junin virus", name: "63" },
  { description: "Leishmaniasis", name: "64" },
  { description: "Leprosy", name: "65" },
  { description: "Lyme disease", name: "66" },
  { description: "Malaria", name: "67" },
  { description: "Melanoma", name: "68" },
  { description: "Parainfluenza-3", name: "69" },
  { description: "Q fever", name: "70" },
  { description: "RSV-IGIV", name: "71" },
  { description: "Rheumatic fever", name: "72" },
  { description: "Rift Valley fever", name: "73" },
  { description: "Rotavirus", name: "74" },
  { description: "Smallpox", name: "75" },
  { description: "Staphylococcus bacterio lysate", name: "76" },
  { description: "Tick-borne encephalitis", name: "77" },
  { description: "Tularemia vaccine", name: "78" },
  { description: "Vaccinia immune globulin", name: "79" },
  { description: "VEE, live", name: "80" },
  { description: "VEE, inactivated", name: "81" },
  { description: "Adenovirus, NOS", name: "82" },
  { description: "Hep A, ped/adol, 2 dose", name: "83" },
  { description: "Hep A, ped/adol, 3 dose", name: "84" },
  { description: "Hep A, NOS", name: "85" },
  { description: "IG", name: "86" },
  { description: "IGIV", name: "87" },
  { description: "Influenza, NOS", name: "88" },
  { description: "Polio, NOS", name: "89" },
  { description: "Rabies, NOS", name: "90" },
  { description: "Typhoid, NOS", name: "91" },
  { description: "VEE, NOS", name: "92" },
] as const;
