// Generated UTG code system profile for v2-0162

export const id = "v2-0162";
export const url = "http://terminology.hl7.org/CodeSystem/v2-0162";
export const oid = "2.16.840.1.113883.18.80";
export const name = "RouteOfAdministration";
export const title = "routeOfAdministration";
export const codes = [
  { code: "AP", display: "Apply Externally", status: "active" },
  { code: "B", display: "Buccal", status: "active" },
  { code: "DT", display: "Dental", status: "active" },
  { code: "EP", display: "Epidural", status: "active" },
  { code: "ET", display: "Endotrachial Tube", status: "active" },
  { code: "GTT", display: "Gastrostomy Tube", status: "active" },
  { code: "GU", display: "GU Irrigant", status: "active" },
  { code: "IA", display: "Intra-arterial", status: "active" },
  { code: "IB", display: "Intrabursal", status: "active" },
  { code: "IC", display: "Intracardiac", status: "active" },
  { code: "ICV", display: "Intracervical (uterus)", status: "active" },
  { code: "ID", display: "Intradermal", status: "active" },
  { code: "IH", display: "Inhalation", status: "active" },
  { code: "IHA", display: "Intrahepatic Artery", status: "active" },
  { code: "IM", display: "Intramuscular", status: "active" },
  { code: "IMR", display: "Immerse (Soak) Body Part", status: "active" },
  { code: "IN", display: "Intranasal", status: "active" },
  { code: "IO", display: "Intraocular", status: "active" },
  { code: "IP", display: "Intraperitoneal", status: "active" },
  { code: "IS", display: "Intrasynovial", status: "active" },
  { code: "IT", display: "Intrathecal", status: "active" },
  { code: "IU", display: "Intrauterine", status: "active" },
  { code: "IV", display: "Intravenous", status: "active" },
  { code: "MM", display: "Mucous Membrane", status: "active" },
  { code: "MTH", display: "Mouth/Throat", status: "active" },
  { code: "NG", display: "Nasogastric", status: "active" },
  { code: "NP", display: "Nasal Prongs", status: "active" },
  { code: "NS", display: "Nasal", status: "active" },
  { code: "NT", display: "Nasotrachial Tube", status: "active" },
  { code: "OP", display: "Ophthalmic", status: "active" },
  { code: "OT", display: "Otic", status: "active" },
  { code: "OTH", display: "Other/Miscellaneous", status: "active" },
  { code: "PF", display: "Perfusion", status: "active" },
  { code: "PO", display: "Oral", status: "active" },
  { code: "PR", display: "Rectal", status: "active" },
  { code: "RM", display: "Rebreather Mask", status: "active" },
  { code: "SC", display: "Subcutaneous", status: "active" },
  { code: "SD", display: "Soaked Dressing", status: "active" },
  { code: "SL", display: "Sublingual", status: "active" },
  { code: "TD", display: "Transdermal", status: "active" },
  { code: "TL", display: "Translingual", status: "active" },
  { code: "TP", display: "Topical", status: "active" },
  { code: "TRA", display: "Tracheostomy", status: "active" },
  { code: "UR", display: "Urethral", status: "active" },
  { code: "VG", display: "Vaginal", status: "active" },
  { code: "VM", display: "Ventimask", status: "active" },
  { code: "WND", display: "Wound", status: "active" },
] as const;
