// Generated UTG code system profile for v2-0550

export const id = "v2-0550";
export const url = "http://terminology.hl7.org/CodeSystem/v2-0550";
export const oid = "2.16.840.1.113883.18.356";
export const name = "BodyParts";
export const title = "bodyParts";
export const codes = [
  { code: "ACET", display: "Acetabulum", status: "active" },
  { code: "ACHIL", display: "Achilles", status: "active" },
  { code: "ADB", display: "Abdomen", status: "active" },
  { code: "ADE", display: "Adenoids", status: "active" },
  { code: "ADR", display: "Adrenal", status: "active" },
  { code: "AMN", display: "Amniotic fluid", status: "active" },
  { code: "AMS", display: "Amniotic Sac", status: "active" },
  { code: "ANAL", display: "Anal", status: "active" },
  { code: "ANKL", display: "Ankle", status: "active" },
  { code: "ANTEC", display: "Antecubital", status: "active" },
  { code: "ANTECF", display: "Antecubital Fossa", status: "active" },
  { code: "ANTR", display: "Antrum", status: "active" },
  { code: "ANUS", display: "Anus", status: "active" },
  { code: "AORTA", display: "Aorta", status: "active" },
  { code: "APDX", display: "Appendix", status: "active" },
  { code: "AR", display: "Aortic Rim", status: "active" },
  { code: "AREO", display: "Areola", status: "active" },
  { code: "ARM", display: "Arm", status: "active" },
  { code: "ARTE", display: "Artery", status: "active" },
  { code: "ASCIT", display: "Ascites", status: "active" },
  { code: "ASCT", display: "Ascitic Fluid", status: "active" },
  { code: "ATR", display: "Atrium", status: "active" },
  { code: "AURI", display: "Auricular", status: "active" },
  { code: "AV", display: "Aortic Valve", status: "active" },
  { code: "AXI", display: "Axilla", status: "active" },
  { code: "BACK", display: "Back", status: "active" },
  { code: "BARTD", display: "Bartholin Duct", status: "active" },
  { code: "BARTG", display: "Bartholin Gland", status: "active" },
  { code: "BCYS", display: "Brain Cyst Fluid", status: "active" },
  { code: "BDY", display: "Body, Whole", status: "active" },
  { code: "BID", display: "Bile Duct", status: "active" },
  { code: "BIFL", display: "Bile fluid", status: "active" },
  { code: "BLAD", display: "Bladder", status: "active" },
  { code: "BLD", display: "Blood, Whole", status: "active" },
  { code: "BLDA", display: "Blood,  Arterial", status: "active" },
  { code: "BLDC", display: "Blood,  Capillary", status: "active" },
  { code: "BLDV", display: "Blood,  Venous", status: "active" },
  { code: "BLOOD", display: "Blood", status: "active" },
  { code: "BMAR", display: "Bone marrow", status: "active" },
  { code: "BON", display: "Bone", status: "active" },
  { code: "BOWEL", display: "Bowel", status: "active" },
  { code: "BOWLA", display: "Bowel, Large", status: "active" },
  { code: "BOWSM", display: "Bowel, Small", status: "active" },
  { code: "BPH", display: "Basophils", status: "active" },
  { code: "BRA", display: "Brachial", status: "active" },
  { code: "BRAIN", display: "Brain", status: "active" },
  { code: "BRO", display: "Bronchial", status: "active" },
  { code: "BROCH", display: "Bronchiole/Bronchiolar", status: "active" },
  { code: "BRONC", display: "Bronchus/Bronchial", status: "active" },
  { code: "BROW", display: "Eyebrow", status: "active" },
  { code: "BRST", display: "Breast", status: "active" },
  { code: "BRSTFL", display: "Breast fluid", status: "active" },
  { code: "BRTGF", display: "Bartholin Gland Fluid", status: "active" },
  { code: "BRV", display: "Broviac", status: "active" },
  { code: "BUCCA", display: "Buccal", status: "active" },
  { code: "BURSA", display: "Bursa", status: "active" },
  { code: "BURSF", display: "Bursa Fluid", status: "active" },
  { code: "BUTT", display: "Buttocks", status: "active" },
  { code: "CALF", display: "Calf", status: "active" },
  { code: "CANAL", display: "Canal", status: "active" },
  { code: "CANLI", display: "Canaliculis", status: "active" },
  { code: "CANTH", display: "Canthus", status: "active" },
  { code: "CARO", display: "Carotid", status: "active" },
  { code: "CARP", display: "Carpal", status: "active" },
  { code: "CAVIT", display: "Cavity", status: "active" },
  { code: "CBLD", display: "Blood, Cord", status: "active" },
  { code: "CDM", display: "Cardiac Muscle", status: "active" },
  { code: "CDUCT", display: "Common Duct", status: "active" },
  { code: "CECUM", display: "Cecum/Cecal", status: "active" },
  { code: "CERVUT", display: "Cervix/Uterus", status: "active" },
  { code: "CHE", display: "Cavity, Chest", status: "active" },
  { code: "CHEEK", display: "Cheek", status: "active" },
  { code: "CHES", display: "Chest", status: "active" },
  { code: "CHEST", display: "Chest Tube", status: "active" },
  { code: "CHIN", display: "Chin", status: "active" },
  { code: "CIRCU", display: "Circumcision Site", status: "active" },
  { code: "CLAVI", display: "Clavicle/Clavicular", status: "active" },
  { code: "CLIT", display: "Clitoris", status: "active" },
  { code: "CLITO", display: "Clitoral", status: "active" },
  { code: "CNL", display: "Cannula", status: "active" },
  { code: "COCCG", display: "Coccygeal", status: "active" },
  { code: "COCCY", display: "Coccyx", status: "active" },
  { code: "COLON", display: "Colon", status: "active" },
  { code: "COLOS", display: "Colostomy", status: "active" },
  { code: "CONJ", display: "Conjunctiva", status: "active" },
  { code: "COR", display: "Cord", status: "active" },
  { code: "CORAL", display: "Coral", status: "active" },
  { code: "CORD", display: "Cord Blood", status: "active" },
  { code: "CORN", display: "Cornea", status: "active" },
  { code: "COS", display: "Colostomy Stoma", status: "active" },
  { code: "CRANE", display: "Cranium, ethmoid", status: "active" },
  { code: "CRANF", display: "Cranium, frontal", status: "active" },
  { code: "CRANO", display: "Cranium, occipital", status: "active" },
  { code: "CRANP", display: "Cranium, parietal", status: "active" },
  { code: "CRANS", display: "Cranium, sphenoid", status: "active" },
  { code: "CRANT", display: "Cranium, temporal", status: "active" },
  { code: "CSF", display: "Cerebral Spinal Fluid", status: "active" },
  { code: "CUBIT", display: "Cubitus", status: "active" },
  { code: "CUFF", display: "Cuff", status: "active" },
  { code: "CULD", display: "Cul De Sac", status: "active" },
  { code: "CULDO", display: "Culdocentesis", status: "active" },
  { code: "CVX", display: "Cervix", status: "active" },
  { code: "DELT", display: "Deltoid", status: "active" },
  { code: "DEN", display: "Dental Gingiva", status: "active" },
  { code: "DENTA", display: "Dental", status: "active" },
  { code: "DIAF", display: "Dialysis Fluid", status: "active" },
  { code: "DIGIT", display: "Digit", status: "active" },
  { code: "DISC", display: "Disc", status: "active" },
  { code: "DORS", display: "Dorsum/Dorsal", status: "active" },
  { code: "DPH", display: "Diaphragm", status: "active" },
  { code: "DUFL", display: "Duodenal Fluid", status: "active" },
  { code: "DUODE", display: "Duodenum/Duodenal", status: "active" },
  { code: "DUR", display: "Dura", status: "active" },
  { code: "EAR", display: "Ear", status: "active" },
  { code: "EARBI", display: "Ear bone, incus", status: "active" },
  { code: "EARBM", display: "Ear bone, malleus", status: "active" },
  { code: "EARBS", display: "Ear bone,stapes", status: "active" },
  { code: "EARLO", display: "Ear Lobe", status: "active" },
  { code: "EC", display: "Endocervical", status: "active" },
  { code: "ELBOW", display: "Elbow", status: "active" },
  { code: "ELBOWJ", display: "Elbow Joint", status: "active" },
  { code: "ENDC", display: "Endocardium", status: "active" },
  { code: "ENDM", display: "Endometrium", status: "active" },
  { code: "EOLPH", display: "endolpthamitis", status: "active" },
  { code: "EOS", display: "Eosinophils", status: "active" },
  { code: "EPD", display: "Epididymis", status: "active" },
  { code: "EPICA", display: "Epicardial", status: "active" },
  { code: "EPICM", display: "Epicardium", status: "active" },
  { code: "EPIDU", display: "Epidural", status: "active" },
  { code: "EPIGL", display: "Epiglottis", status: "active" },
  { code: "ESO", display: "Esophagus", status: "active" },
  { code: "ESOPG", display: "Esophageal", status: "active" },
  { code: "ET", display: "Endotracheal", status: "active" },
  { code: "ETHMO", display: "Ethmoid", status: "active" },
  { code: "EUR", display: "Endourethral", status: "active" },
  { code: "EYE", display: "Eye", status: "active" },
  { code: "EYELI", display: "Eyelid", status: "active" },
  { code: "FACE", display: "Face", status: "active" },
  { code: "FALLT", display: "Fallopian Tube", status: "active" },
  {
    code: "FBINC",
    display: "Facial bone, inferior nasal concha",
    status: "active",
  },
  { code: "FBLAC", display: "Facial bone, lacrimal", status: "active" },
  { code: "FBMAX", display: "Facial bone, maxilla", status: "active" },
  { code: "FBNAS", display: "Facial bone, nasal", status: "active" },
  { code: "FBPAL", display: "Facial bone, palatine", status: "active" },
  { code: "FBVOM", display: "Facial bone, vomer", status: "active" },
  { code: "FBZYG", display: "Facial bone, zygomatic", status: "active" },
  { code: "FEMOR", display: "Femoral", status: "active" },
  { code: "FEMUR", display: "Femur", status: "active" },
  { code: "FET", display: "Fetus", status: "active" },
  { code: "FIBU", display: "Fibula", status: "active" },
  { code: "FING", display: "Finger", status: "active" },
  { code: "FINGN", display: "Finger Nail", status: "active" },
  { code: "FMH", display: "Femoral Head", status: "active" },
  { code: "FOL", display: "Follicle", status: "active" },
  { code: "FOOT", display: "Foot", status: "active" },
  { code: "FOREA", display: "Forearm", status: "active" },
  { code: "FOREH", display: "Forehead", status: "active" },
  { code: "FORES", display: "Foreskin", status: "active" },
  { code: "FOURC", display: "Fourchette", status: "active" },
  { code: "GB", display: "Gall Bladder", status: "active" },
  { code: "GEN", display: "Genital", status: "active" },
  { code: "GENC", display: "Genital Cervix", status: "active" },
  { code: "GENL", display: "Genital Lochia", status: "active" },
  { code: "GL", display: "Genital Lesion", status: "active" },
  { code: "GLAND", display: "Gland", status: "active" },
  { code: "GLANS", display: "Glans", status: "active" },
  { code: "GLUT", display: "Gluteus", status: "active" },
  { code: "GLUTE", display: "Gluteal", status: "active" },
  { code: "GLUTM", display: "Gluteus Medius", status: "active" },
  { code: "GROIN", display: "Groin", status: "active" },
  { code: "GUM", display: "Gum", status: "active" },
  { code: "GVU", display: "Genital - Vulva", status: "active" },
  { code: "HAL", display: "Hallux", status: "active" },
  { code: "HAND", display: "Hand", status: "active" },
  { code: "HAR", display: "Hair", status: "active" },
  { code: "HART", display: "Heart", status: "active" },
  { code: "HEAD", display: "Head", status: "active" },
  { code: "HEEL", display: "Heel", status: "active" },
  { code: "HEM", display: "Hemorrhoid", status: "active" },
  { code: "HIP", display: "Hip", status: "active" },
  { code: "HIPJ", display: "Hip Joint", status: "active" },
  { code: "HUMER", display: "Humerus", status: "active" },
  { code: "HV", display: "Heart Valve", status: "active" },
  { code: "HVB", display: "Heart Valve, Bicuspid", status: "active" },
  { code: "HVT", display: "Heart Valve, Tricuspid", status: "active" },
  { code: "HYMEN", display: "Hymen", status: "active" },
  { code: "ICX", display: "Intracervical", status: "active" },
  { code: "ILC", display: "Ileal Conduit", status: "active" },
  { code: "ILCON", display: "Ilical Conduit", status: "active" },
  { code: "ILCR", display: "Iliac Crest", status: "active" },
  { code: "ILE", display: "Ileal Loop", status: "active" },
  { code: "ILEOS", display: "Ileostomy", status: "active" },
  { code: "ILEUM", display: "Ileum", status: "active" },
  { code: "ILIAC", display: "Iliac", status: "active" },
  { code: "INASA", display: "Intranasal", status: "active" },
  { code: "INGUI", display: "Inguinal", status: "active" },
  { code: "INSTL", display: "Intestine, Large", status: "active" },
  { code: "INSTS", display: "Intestine, Small", status: "active" },
  { code: "INT", display: "Intestine", status: "active" },
  { code: "INTRO", display: "Introitus", status: "active" },
  { code: "INTRU", display: "Intrauterine", status: "active" },
  { code: "ISCHI", display: "Ischium", status: "active" },
  { code: "ISH", display: "Loop, Ishial", status: "active" },
  { code: "JAW", display: "Jaw", status: "active" },
  { code: "JUGE", display: "Jugular, External", status: "active" },
  { code: "JUGI", display: "Jugular, Internal", status: "active" },
  { code: "KIDN", display: "Kidney", status: "active" },
  { code: "KNEE", display: "Knee", status: "active" },
  { code: "KNEEF", display: "Knee Fluid", status: "active" },
  { code: "KNEEJ", display: "Knee Joint", status: "active" },
  { code: "LABIA", display: "Labia", status: "active" },
  { code: "LABMA", display: "Labia Majora", status: "active" },
  { code: "LABMI", display: "Labia Minora", status: "active" },
  { code: "LACRI", display: "Lacrimal", status: "active" },
  { code: "LAM", display: "Lamella", status: "active" },
  { code: "LARYN", display: "Larynx", status: "active" },
  { code: "LEG", display: "Leg", status: "active" },
  { code: "LENS", display: "Lens", status: "active" },
  { code: "LING", display: "Lingual", status: "active" },
  { code: "LINGU", display: "Lingula", status: "active" },
  { code: "LIP", display: "Lip", status: "active" },
  { code: "LIVER", display: "Liver", status: "active" },
  { code: "LMN", display: "Lumen", status: "active" },
  { code: "LN", display: "Lymph Node", status: "active" },
  { code: "LNG", display: "Lymph Node, Groin", status: "active" },
  { code: "LOBE", display: "Lobe", status: "active" },
  { code: "LOCH", display: "Lochia", status: "active" },
  { code: "LUMBA", display: "Lumbar", status: "active" },
  { code: "LUNG", display: "Lung", status: "active" },
  { code: "LYM", display: "Lymphocytes", status: "active" },
  { code: "MAC", display: "Macrophages", status: "active" },
  { code: "MALLE", display: "Malleolus", status: "active" },
  { code: "MANDI", display: "Mandible/Mandibular", status: "active" },
  { code: "MAR", display: "Marrow", status: "active" },
  { code: "MAST", display: "Mastoid", status: "active" },
  { code: "MAXIL", display: "Maxilla/Maxillary", status: "active" },
  { code: "MAXS", display: "Maxillary Sinus", status: "active" },
  { code: "MEATU", display: "Meatus", status: "active" },
  { code: "MEC", display: "Meconium", status: "active" },
  { code: "MEDST", display: "Mediastinum", status: "active" },
  { code: "MEDU", display: "Medullary", status: "active" },
  { code: "METAC", display: "Metacarpal", status: "active" },
  { code: "METAT", display: "Metatarsal", status: "active" },
  { code: "MILK", display: "Milk, Breast", status: "active" },
  { code: "MITRL", display: "Mitral Valve", status: "active" },
  { code: "MOLAR", display: "Molar", status: "active" },
  { code: "MONSU", display: "Mons Ureteris", status: "active" },
  { code: "MONSV", display: "Mons Veneris(Mons Pubis)", status: "active" },
  { code: "MOU", display: "Membrane", status: "active" },
  { code: "MOUTH", display: "Mouth", status: "active" },
  { code: "MP", display: "Mons Pubis", status: "active" },
  { code: "MPB", display: "Meninges", status: "active" },
  { code: "MRSA2", display: "Mrsa:", status: "active" },
  { code: "MYO", display: "Myocardium", status: "active" },
  { code: "NAIL", display: "Nail", status: "active" },
  { code: "NAILB", display: "Nail Bed", status: "active" },
  { code: "NAILF", display: "Nail, Finger", status: "active" },
  { code: "NAILT", display: "Nail, Toe", status: "active" },
  { code: "NARES", display: "Nares", status: "active" },
  { code: "NASL", display: "Nasal", status: "active" },
  { code: "NAVEL", display: "Navel", status: "active" },
  { code: "NECK", display: "Neck", status: "active" },
  { code: "NERVE", display: "Nerve", status: "active" },
  { code: "NIPPL", display: "Nipple", status: "active" },
  { code: "NLACR", display: "Nasolacrimal", status: "active" },
  { code: "NOS", display: "Nose (Nasal Passage)", status: "active" },
  { code: "NOSE", display: "Nose/Nose(outside)", status: "active" },
  { code: "NOSTR", display: "Nostril", status: "active" },
  { code: "NP", display: "Nasopharyngeal/Nasopharynx", status: "active" },
  { code: "NSS", display: "Nasal Septum", status: "active" },
  { code: "NTRAC", display: "Nasotracheal", status: "active" },
  { code: "OCCIP", display: "Occipital", status: "active" },
  { code: "OLECR", display: "Olecranon", status: "active" },
  { code: "OMEN", display: "Omentum", status: "active" },
  { code: "ORBIT", display: "Orbit/Orbital", status: "active" },
  { code: "ORO", display: "Oropharynx", status: "active" },
  { code: "OSCOX", display: "Os coxa (pelvic girdle)", status: "active" },
  { code: "OVARY", display: "Ovary", status: "active" },
  { code: "PAFL", display: "Pancreatic Fluid", status: "active" },
  { code: "PALAT", display: "Palate", status: "active" },
  { code: "PALM", display: "Palm", status: "active" },
  { code: "PANAL", display: "Perianal/Perirectal", status: "active" },
  { code: "PANCR", display: "Pancreas", status: "active" },
  { code: "PARAT", display: "Paratracheal", status: "active" },
  { code: "PARIE", display: "Parietal", status: "active" },
  { code: "PARON", display: "Paronychia", status: "active" },
  { code: "PAROT", display: "Parotid/Parotid Gland", status: "active" },
  { code: "PAS", display: "Parasternal", status: "active" },
  { code: "PATEL", display: "Patella", status: "active" },
  { code: "PCARD", display: "Pericardium", status: "active" },
  { code: "PCLIT", display: "Periclitoral", status: "active" },
  { code: "PELV", display: "Pelvis", status: "active" },
  { code: "PENIS", display: "Penis", status: "active" },
  { code: "PENSH", display: "Penile Shaft", status: "active" },
  { code: "PER", display: "Peritoneal", status: "active" },
  { code: "PERI", display: "Pericardial Fluid", status: "active" },
  { code: "PERIH", display: "Perihepatic", status: "active" },
  { code: "PERIN", display: "Perineal Abscess", status: "active" },
  { code: "PERIS", display: "Perisplenic", status: "active" },
  { code: "PERIT", display: "Peritoneum", status: "active" },
  { code: "PERIU", display: "Periurethal", status: "active" },
  { code: "PERIV", display: "Perivesicular", status: "active" },
  { code: "PERRA", display: "Perirectal", status: "active" },
  { code: "PERT", display: "Peritoneal Fluid", status: "active" },
  { code: "PHALA", display: "Phalanyx", status: "active" },
  { code: "PILO", display: "Pilonidal", status: "active" },
  { code: "PINNA", display: "Pinna", status: "active" },
  { code: "PLACF", display: "Placenta (Fetal Side)", status: "active" },
  { code: "PLACM", display: "Placenta (Maternal Side)", status: "active" },
  { code: "PLANT", display: "Plantar", status: "active" },
  { code: "PLATH", display: "Palate, Hard", status: "active" },
  { code: "PLATS", display: "Palate, Soft", status: "active" },
  { code: "PLC", display: "Placenta", status: "active" },
  { code: "PLEU", display: "Pleural Fluid", status: "active" },
  { code: "PLEUR", display: "Pleura", status: "active" },
  {
    code: "PLR",
    display: "Pleural Fluid (Thoracentesis Fld)",
    status: "active",
  },
  { code: "PNEAL", display: "Perineal", status: "active" },
  { code: "PNEPH", display: "Perinephric", status: "active" },
  { code: "PNM", display: "Perineum", status: "active" },
  { code: "POPLI", display: "Popliteal", status: "active" },
  { code: "PORBI", display: "Periorbital", status: "active" },
  { code: "PREAU", display: "Preauricular", status: "active" },
  { code: "PRERE", display: "Prerenal", status: "active" },
  { code: "PROS", display: "Prostatic Fluid", status: "active" },
  { code: "PRST", display: "Prostate Gland", status: "active" },
  { code: "PTONS", display: "Peritonsillar", status: "active" },
  { code: "PUBIC", display: "Pubic", status: "active" },
  { code: "PUL", display: "Pulmonary Artery", status: "active" },
  { code: "RADI", display: "Radial", status: "active" },
  { code: "RADIUS", display: "Radius", status: "active" },
  { code: "RBC", display: "Red Blood Cells", status: "active" },
  { code: "RECTL", display: "Rectal", status: "active" },
  { code: "RECTU", display: "Rectum", status: "active" },
  { code: "RENL", display: "Renal", status: "active" },
  { code: "RIB", display: "Rib", status: "active" },
  { code: "RNP", display: "Renal Pelvis", status: "active" },
  { code: "RPERI", display: "Retroperitoneal", status: "active" },
  { code: "SAC", display: "Uterine Cul/De/Sac", status: "active" },
  { code: "SACIL", display: "Sacroiliac", status: "active" },
  { code: "SACRA", display: "Sacral", status: "active" },
  { code: "SACRO", display: "Sacrococcygeal", status: "active" },
  { code: "SACRU", display: "Sacrum", status: "active" },
  { code: "SALGL", display: "Salivary Gland", status: "active" },
  { code: "SCALP", display: "Scalp", status: "active" },
  { code: "SCAPU", display: "Scapula/Scapular", status: "active" },
  { code: "SCLAV", display: "Supraclavicle/Supraclavicular", status: "active" },
  { code: "SCLER", display: "Sclera", status: "active" },
  { code: "SCLV", display: "Sub Clavian", status: "active" },
  { code: "SCROT", display: "Scrotum/Scrotal", status: "active" },
  { code: "SDP", display: "Subdiaphramatic", status: "active" },
  { code: "SEM", display: "Seminal Fluid", status: "active" },
  { code: "SEMN", display: "Semen", status: "active" },
  { code: "SEPTU", display: "Septum/Septal", status: "active" },
  { code: "SEROM", display: "Seroma", status: "active" },
  { code: "SGF", display: "Subgaleal Fluid", status: "active" },
  { code: "SHIN", display: "Shin", status: "active" },
  { code: "SHOL", display: "Shoulder", status: "active" },
  { code: "SHOLJ", display: "Sholder Joint", status: "active" },
  { code: "SIGMO", display: "Sigmoid", status: "active" },
  { code: "SINUS", display: "Sinus", status: "active" },
  { code: "SKENE", display: "Skene&#39;s Gland", status: "active" },
  { code: "SKM", display: "Skeletal Muscle", status: "active" },
  { code: "SKULL", display: "Skull", status: "active" },
  { code: "SOLE", display: "Sole", status: "active" },
  { code: "SPCOR", display: "Spinal Cord", status: "active" },
  { code: "SPHEN", display: "Sphenoid", status: "active" },
  { code: "SPLN", display: "Spleen", status: "active" },
  { code: "SPRM", display: "Spermatozoa", status: "active" },
  { code: "SPX", display: "Supra Cervical", status: "active" },
  { code: "STER", display: "Sternum/Sternal", status: "active" },
  { code: "STOM", display: "Stoma", status: "active" },
  { code: "STOMA", display: "Stomach", status: "active" },
  { code: "STOOLL", display: "Liquid Stool", status: "active" },
  { code: "STUMP", display: "Stump", status: "active" },
  { code: "SUB", display: "Subdural", status: "active" },
  { code: "SUBD", display: "Subdural Fluid", status: "active" },
  { code: "SUBM", display: "Submandibular", status: "active" },
  { code: "SUBME", display: "Submental", status: "active" },
  { code: "SUBPH", display: "Subphrenic", status: "active" },
  { code: "SUBX", display: "Submaxillary", status: "active" },
  { code: "SUPB", display: "Suprapubic Specimen", status: "active" },
  { code: "SUPRA", display: "Suprapubic", status: "active" },
  { code: "SWT", display: "Sweat", status: "active" },
  { code: "SWTG", display: "Sweat Gland", status: "active" },
  { code: "SYN", display: "Synovial Fluid", status: "active" },
  { code: "SYNOL", display: "Synovial", status: "active" },
  { code: "SYNOV", display: "Synovium", status: "active" },
  { code: "TARS", display: "Tarsal", status: "active" },
  { code: "TBRON", display: "Transbronchial", status: "active" },
  { code: "TCN", display: "Transcarina Asp", status: "active" },
  { code: "TDUCT", display: "Tear Duct", status: "active" },
  { code: "TEAR", display: "Tears", status: "active" },
  { code: "TEMPL", display: "Temple", status: "active" },
  { code: "TEMPO", display: "Temporal", status: "active" },
  { code: "TESTI", display: "Testicle(Testis)", status: "active" },
  { code: "THIGH", display: "Thigh", status: "active" },
  { code: "THM", display: "Thymus", status: "active" },
  { code: "THORA", display: "Thorax/Thoracic/Thoracentesis", status: "active" },
  { code: "THRB", display: "Throat", status: "active" },
  { code: "THUMB", display: "Thumb", status: "active" },
  { code: "THYRD", display: "Thyroid", status: "active" },
  { code: "TIBIA", display: "Tibia", status: "active" },
  { code: "TML", display: "Temporal Lobe", status: "active" },
  { code: "TNL", display: "Thumbnail", status: "active" },
  { code: "TOE", display: "Toe", status: "active" },
  { code: "TOEN", display: "Toe Nail", status: "active" },
  { code: "TONG", display: "Tongue", status: "active" },
  { code: "TONS", display: "Tonsil", status: "active" },
  { code: "TOOTH", display: "Tooth", status: "active" },
  { code: "TRCHE", display: "Trachea/Tracheal", status: "active" },
  { code: "TSK", display: "Tooth Socket", status: "active" },
  { code: "ULNA", display: "Ulna/Ulnar", status: "active" },
  { code: "UMB", display: "Umbilical Blood", status: "active" },
  { code: "UMBL", display: "Umbilicus/Umbilical", status: "active" },
  { code: "URET", display: "Ureter", status: "active" },
  { code: "URTH", display: "Urethra", status: "active" },
  { code: "USTOM", display: "Stoma, Urinary", status: "active" },
  { code: "UTER", display: "Uterus", status: "active" },
  { code: "UTERI", display: "Uterine", status: "active" },
  { code: "VAGIN", display: "Vagina/Vaginal", status: "active" },
  { code: "VAL", display: "Valve", status: "active" },
  { code: "VAS", display: "Vas Deferens", status: "active" },
  { code: "VASTL", display: "Vastus Lateralis", status: "active" },
  { code: "VAULT", display: "Vault", status: "active" },
  { code: "VCSF", display: "Ventricular CSF", status: "active" },
  { code: "VCUFF", display: "Vaginal Cuff", status: "active" },
  { code: "VEIN", display: "Vein", status: "active" },
  { code: "VENTG", display: "Ventragluteal", status: "active" },
  { code: "VERMI", display: "Vermis Cerebelli", status: "active" },
  { code: "VERTC", display: "Vertebra, cervical", status: "active" },
  { code: "VERTL", display: "Vertebra, lumbar", status: "active" },
  { code: "VERTT", display: "Vertebra, thoracic", status: "active" },
  { code: "VESCL", display: "Vesicular", status: "active" },
  { code: "VESFLD", display: "Vesicular Fluid", status: "active" },
  { code: "VESI", display: "Vesicle", status: "active" },
  { code: "VESTI", display: "Vestibule(Genital)", status: "active" },
  { code: "VGV", display: "Vaginal Vault", status: "active" },
  { code: "VITR", display: "Vitreous Fluid", status: "active" },
  { code: "VOC", display: "Vocal Cord", status: "active" },
  { code: "VULVA", display: "Vulva", status: "active" },
  { code: "WBC", display: "Leukocytes", status: "active" },
  { code: "WRIST", display: "Wrist", status: "active" },
] as const;
