// Generated UTG code system profile for v2-0119

export const id = "v2-0119";
export const url = "http://terminology.hl7.org/CodeSystem/v2-0119";
export const oid = "2.16.840.1.113883.18.48";
export const name = "OrderControlCodes";
export const title = "orderControlCodes";
export const codes = [
  {
    code: "AF",
    display: "Order/service refill request approval",
    status: "active",
  },
  { code: "CA", display: "Cancel order/service request", status: "active" },
  { code: "CH", display: "Child order/service", status: "active" },
  { code: "CN", display: "Combined result", status: "active" },
  { code: "CP", display: "Cancel process step", status: "active" },
  { code: "CR", display: "Canceled as requested", status: "active" },
  {
    code: "DC",
    display: "Discontinue order/service request",
    status: "active",
  },
  { code: "DE", display: "Data errors", status: "active" },
  {
    code: "DF",
    display: "Order/service refill request denied",
    status: "active",
  },
  { code: "DR", display: "Discontinued as requested", status: "active" },
  {
    code: "FU",
    display: "Order/service refilled, unsolicited",
    status: "active",
  },
  { code: "HD", display: "Hold order request", status: "active" },
  { code: "HR", display: "On hold as requested", status: "active" },
  {
    code: "LI",
    display: "Link order/service to patient care problem or goal",
    status: "active",
  },
  {
    code: "MC",
    display: "Miscellaneous Charge - not associated with an order",
    status: "active",
  },
  { code: "NA", display: "Number assigned", status: "active" },
  { code: "NR", display: "Notification Received", status: "active" },
  { code: "NW", display: "New order/service", status: "active" },
  { code: "OC", display: "Order/service canceled", status: "active" },
  { code: "OD", display: "Order/service discontinued", status: "active" },
  { code: "OE", display: "Order/service released", status: "active" },
  {
    code: "OF",
    display: "Order/service refilled as requested",
    status: "active",
  },
  { code: "OH", display: "Order/service held", status: "active" },
  { code: "OK", display: "Order/service accepted &amp; OK", status: "active" },
  {
    code: "OP",
    display: "Notification of order for outside dispense",
    status: "active",
  },
  { code: "OR", display: "Released as requested", status: "active" },
  { code: "PA", display: "Parent order/service", status: "active" },
  {
    code: "PR",
    display: "Previous Results with new order/service",
    status: "active",
  },
  {
    code: "PY",
    display: "Notification of replacement order for outside dispense",
    status: "active",
  },
  { code: "RA", display: "Recommendation Accepted", status: "N" },
  { code: "RC", display: "Recommended Change", status: "N" },
  { code: "RD", display: "Recommendation Declined", status: "N" },
  {
    code: "RE",
    display: "Observations/Performed Service to follow",
    status: "active",
  },
  { code: "RF", display: "Refill order/service request", status: "active" },
  { code: "RL", display: "Release previous hold", status: "active" },
  { code: "RO", display: "Replacement order", status: "active" },
  { code: "RP", display: "Order/service replace request", status: "active" },
  { code: "RQ", display: "Replaced as requested", status: "active" },
  { code: "RR", display: "Request received", status: "active" },
  { code: "RU", display: "Replaced unsolicited", status: "active" },
  { code: "SC", display: "Status changed", status: "active" },
  { code: "SN", display: "Send order/service number", status: "active" },
  { code: "SQ", display: "Supplemented as requested", status: "N" },
  {
    code: "SR",
    display: "Response to send order/service status request",
    status: "active",
  },
  {
    code: "SS",
    display: "Send order/service status request",
    status: "active",
  },
  { code: "SU", display: "Supplement this order", status: "N" },
  { code: "UA", display: "Unable to accept order/service", status: "active" },
  { code: "UC", display: "Unable to cancel", status: "active" },
  { code: "UD", display: "Unable to discontinue", status: "active" },
  { code: "UF", display: "Unable to refill", status: "active" },
  { code: "UH", display: "Unable to put on hold", status: "active" },
  { code: "UM", display: "Unable to replace", status: "active" },
  {
    code: "UN",
    display: "Unlink order/service from patient care problem or goal",
    status: "active",
  },
  { code: "UR", display: "Unable to release", status: "active" },
  { code: "UX", display: "Unable to change", status: "active" },
  { code: "XO", display: "Change order/service request", status: "active" },
  { code: "XR", display: "Changed as requested", status: "active" },
  { code: "XX", display: "Order/service changed, unsol.", status: "active" },
] as const;
