// Generated UTG code system profile for v2-0440

export const id = "v2-0440";
export const url = "http://terminology.hl7.org/CodeSystem/v2-0440";
export const oid = "2.16.840.1.113883.18.280";
export const name = "DataTypes";
export const title = "dataTypes";
export const codes = [
  { code: "AD", display: "Address", status: "active" },
  { code: "AUI", display: "Authorization information", status: "active" },
  { code: "CCD", display: "Charge code and date", status: "active" },
  { code: "CCP", display: "Channel calibration parameters", status: "active" },
  { code: "CD", display: "Channel definition", status: "active" },
  { code: "CE", display: "Coded element", status: "active" },
  {
    code: "CF",
    display: "Coded element with formatted values",
    status: "active",
  },
  { code: "CK", display: "Composite ID with check digit", status: "active" },
  { code: "CM", display: "Composite", status: "active" },
  { code: "CN", display: "Composite ID number and name", status: "active" },
  { code: "CNE", display: "Coded with no exceptions", status: "active" },
  {
    code: "CNN",
    display: "Composite ID number and name simplified",
    status: "active",
  },
  {
    code: "CNS",
    display: "Composite ID number and name simplified",
    status: "active",
  },
  { code: "CP", display: "Composite price", status: "active" },
  { code: "CQ", display: "Composite quantity with units", status: "active" },
  { code: "CSU", display: "Channel sensitivity and units", status: "active" },
  { code: "CWE", display: "Coded with exceptions", status: "active" },
  {
    code: "CX",
    display: "Extended composite ID with check digit",
    status: "active",
  },
  { code: "DDI", display: "Daily deductible information", status: "active" },
  { code: "DIN", display: "Date and institution name", status: "active" },
  { code: "DLD", display: "Discharge to location and date", status: "active" },
  { code: "DLN", display: "Driver&#39;s license number", status: "active" },
  { code: "DLT", display: "Delta", status: "active" },
  { code: "DR", display: "Date/time range", status: "active" },
  { code: "DT", display: "Date", status: "active" },
  { code: "DTM", display: "Date/time", status: "active" },
  { code: "DTN", display: "Day type and number", status: "active" },
  { code: "ED", display: "Encapsulated data", status: "active" },
  { code: "EI", display: "Entity identifier", status: "active" },
  { code: "EIP", display: "Entity identifier pair", status: "active" },
  { code: "ELD", display: "Error location and description", status: "active" },
  { code: "ERL", display: "Error location", status: "active" },
  { code: "FC", display: "Financial class", status: "active" },
  { code: "FN", display: "Family name", status: "active" },
  { code: "FT", display: "Formatted text", status: "active" },
  { code: "GTS", display: "General timing specification", status: "active" },
  { code: "HD", display: "Hierarchic designator", status: "active" },
  {
    code: "ICD",
    display: "Insurance certification definition",
    status: "active",
  },
  { code: "ID", display: "Coded values for HL7 tables", status: "active" },
  {
    code: "IS",
    display: "Coded value for user-defined tables",
    status: "active",
  },
  { code: "JCC", display: "Job code/class", status: "active" },
  { code: "LA1", display: "Location with address variation 1", status: "B" },
  { code: "LA2", display: "Location with address variation 2", status: "B" },
  { code: "MA", display: "Multiplexed array", status: "active" },
  { code: "MO", display: "Money", status: "active" },
  { code: "MOC", display: "Money and charge code", status: "active" },
  { code: "MOP", display: "Money or percentage", status: "active" },
  { code: "MSG", display: "Message type", status: "active" },
  { code: "NA", display: "Numeric array", status: "active" },
  { code: "NDL", display: "Name with date and location", status: "active" },
  { code: "NM", display: "Numeric", status: "active" },
  { code: "NR", display: "Numeric range", status: "active" },
  { code: "OCD", display: "Occurrence code and date", status: "active" },
  { code: "OSD", display: "Order sequence definition", status: "active" },
  { code: "OSP", display: "Occurrence span code and date", status: "active" },
  {
    code: "PIP",
    display: "Practitioner institutional privileges",
    status: "active",
  },
  { code: "PL", display: "Person location", status: "active" },
  {
    code: "PLN",
    display: "Practitioner license or other ID number",
    status: "active",
  },
  { code: "PN", display: "Person name", status: "active" },
  { code: "PPN", display: "Performing person time stamp", status: "active" },
  { code: "PRL", display: "Parent result link", status: "active" },
  { code: "PT", display: "Processing type", status: "active" },
  { code: "PTA", display: "Policy type and amount", status: "active" },
  { code: "QIP", display: "Query input parameter list", status: "active" },
  { code: "QSC", display: "Query selection criteria", status: "active" },
  { code: "RCD", display: "Row column definition", status: "active" },
  { code: "RFR", display: "Reference range", status: "active" },
  { code: "RI", display: "Repeat interval", status: "active" },
  { code: "RMC", display: "Room coverage", status: "active" },
  { code: "RP", display: "Reference pointer", status: "active" },
  { code: "RPT", display: "Repeat pattern", status: "active" },
  { code: "SAD", display: "Street Address", status: "active" },
  { code: "SCV", display: "Scheduling class value pair", status: "active" },
  { code: "SI", display: "Sequence ID", status: "active" },
  { code: "SN", display: "Structured numeric", status: "active" },
  {
    code: "SNM",
    display: "String of telephone number digits",
    status: "active",
  },
  { code: "SPD", display: "Specialty description", status: "active" },
  { code: "SPS", display: "Specimen source", status: "active" },
  { code: "SRT", display: "Sort order", status: "active" },
  { code: "ST", display: "String data", status: "active" },
  { code: "TM", display: "Time", status: "active" },
  { code: "TN", display: "Telephone number", status: "active" },
  { code: "TQ", display: "Timing/quantity", status: "active" },
  { code: "TS", display: "Time stamp", status: "active" },
  { code: "TX", display: "Text data", status: "active" },
  { code: "UVC", display: "UB value code and amount", status: "active" },
  { code: "VH", display: "Visiting hours", status: "active" },
  { code: "VID", display: "Version identifier", status: "active" },
  { code: "VR", display: "Value range", status: "active" },
  { code: "WVI", display: "Channel Identifier", status: "active" },
  { code: "WVS", display: "Waveform source", status: "active" },
  { code: "XAD", display: "Extended address", status: "active" },
  {
    code: "XCN",
    display: "Extended composite ID number and name for persons",
    status: "active",
  },
  {
    code: "XON",
    display: "Extended composite name and ID number for organizations",
    status: "active",
  },
  { code: "XPN", display: "Extended person name", status: "active" },
  {
    code: "XTN",
    display: "Extended telecommunications number",
    status: "active",
  },
] as const;
