// Generated profile automaton for ORF_R04 (v2.5.1)

export const start = 0;
export const finals = new Set<number>([
  5, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19,
]);
export const alphabet = new Set<string>([
  "CTD",
  "CTI",
  "DSC",
  "ERR",
  "MSA",
  "MSH",
  "NTE",
  "OBR",
  "OBX",
  "ORC",
  "PID",
  "QAK",
  "QRD",
  "QRF",
  "SFT",
  "TQ1",
  "TQ2",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["MSA", 2],
      ["SFT", 3],
    ]),
  ],
  [2, new Map([["QRD", 4]])],
  [
    3,
    new Map([
      ["MSA", 2],
      ["SFT", 3],
    ]),
  ],
  [
    4,
    new Map([
      ["OBR", 5],
      ["ORC", 6],
      ["PID", 7],
      ["QRF", 8],
    ]),
  ],
  [
    5,
    new Map([
      ["CTD", 15],
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 13],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
      ["TQ1", 16],
    ]),
  ],
  [6, new Map([["OBR", 5]])],
  [
    7,
    new Map([
      ["NTE", 17],
      ["OBR", 5],
      ["ORC", 6],
    ]),
  ],
  [
    8,
    new Map([
      ["OBR", 5],
      ["ORC", 6],
      ["PID", 7],
    ]),
  ],
  [9, new Map([])],
  [10, new Map([["DSC", 9]])],
  [
    11,
    new Map([
      ["DSC", 9],
      ["ERR", 11],
      ["QAK", 10],
    ]),
  ],
  [
    12,
    new Map([
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["OBR", 5],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
    ]),
  ],
  [
    13,
    new Map([
      ["CTD", 15],
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 13],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
      ["TQ1", 16],
    ]),
  ],
  [
    14,
    new Map([
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 18],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
    ]),
  ],
  [
    15,
    new Map([
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 18],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
    ]),
  ],
  [
    16,
    new Map([
      ["CTD", 15],
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 18],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
      ["TQ1", 16],
      ["TQ2", 19],
    ]),
  ],
  [
    17,
    new Map([
      ["NTE", 17],
      ["OBR", 5],
      ["ORC", 6],
    ]),
  ],
  [
    18,
    new Map([
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 18],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
    ]),
  ],
  [
    19,
    new Map([
      ["CTD", 15],
      ["CTI", 12],
      ["DSC", 9],
      ["ERR", 11],
      ["NTE", 18],
      ["OBR", 5],
      ["OBX", 14],
      ["ORC", 6],
      ["PID", 7],
      ["QAK", 10],
      ["TQ1", 16],
      ["TQ2", 19],
    ]),
  ],
]);
export const effects = {
  "12:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "12:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "12:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "12:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "12:PID": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "12:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "13:CTD": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "13:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "13:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "13:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "13:NTE": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "13:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "13:OBX": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "13:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "13:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "13:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "13:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
  },
  "14:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "14:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "14:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "14:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "14:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "14:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "14:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "14:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "15:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "15:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "15:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "15:NTE": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "15:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "15:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "15:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "15:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "15:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:CTD": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:NTE": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "16:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "16:OBX": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "16:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "16:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "16:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
  },
  "17:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "17:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "18:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "18:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "18:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "18:NTE": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "18:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "18:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "18:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "18:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "18:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:CTD": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:NTE": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "19:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "19:OBX": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "19:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "19:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "19:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
  },
  "4:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "4:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "4:PID": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "5:CTD": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "5:CTI": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "5:DSC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "5:ERR": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "5:NTE": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "5:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "5:OBX": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
    ],
  },
  "5:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "5:PID": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
  "5:QAK": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/OBXNTE_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "5:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/TQ1TQ2_SUPPGRP",
    ],
  },
  "7:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "7:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "8:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "8:ORC": {
    groupsClosed: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/ORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
    ],
  },
  "8:PID": {
    groupsClosed: [],
    groupsOpened: [
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP",
      "ORF_R04/PIDNTEORCOBRNTETQ1TQ2CTDOBXNTECTI_SUPPGRP/PIDNTE_SUPPGRP",
    ],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
