// Generated profile automaton for OUL_R23 (v2.5.1)

export const start = 0;
export const finals = new Set<number>([
  12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
]);
export const alphabet = new Set<string>([
  "CTI",
  "DSC",
  "INV",
  "MSH",
  "NTE",
  "OBR",
  "OBX",
  "ORC",
  "PD1",
  "PID",
  "PV1",
  "PV2",
  "SAC",
  "SFT",
  "SID",
  "SPM",
  "TCD",
  "TQ1",
  "TQ2",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["NTE", 5],
      ["PID", 4],
      ["PV1", 3],
      ["SFT", 6],
      ["SPM", 2],
    ]),
  ],
  [
    2,
    new Map([
      ["OBX", 8],
      ["SAC", 7],
    ]),
  ],
  [
    3,
    new Map([
      ["PV2", 9],
      ["SPM", 2],
    ]),
  ],
  [
    4,
    new Map([
      ["NTE", 10],
      ["PD1", 11],
      ["PV1", 3],
      ["SPM", 2],
    ]),
  ],
  [
    5,
    new Map([
      ["PID", 4],
      ["PV1", 3],
      ["SPM", 2],
    ]),
  ],
  [
    6,
    new Map([
      ["NTE", 5],
      ["PID", 4],
      ["PV1", 3],
      ["SFT", 6],
      ["SPM", 2],
    ]),
  ],
  [
    7,
    new Map([
      ["INV", 13],
      ["OBR", 12],
    ]),
  ],
  [
    8,
    new Map([
      ["OBX", 8],
      ["SAC", 7],
    ]),
  ],
  [9, new Map([["SPM", 2]])],
  [
    10,
    new Map([
      ["NTE", 10],
      ["PV1", 3],
      ["SPM", 2],
    ]),
  ],
  [
    11,
    new Map([
      ["NTE", 10],
      ["PV1", 3],
      ["SPM", 2],
    ]),
  ],
  [
    12,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 18],
      ["OBR", 12],
      ["OBX", 16],
      ["ORC", 19],
      ["SAC", 7],
      ["SPM", 2],
      ["TQ1", 17],
    ]),
  ],
  [13, new Map([["OBR", 12]])],
  [14, new Map([])],
  [
    15,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["OBR", 12],
      ["SAC", 7],
      ["SPM", 2],
    ]),
  ],
  [
    16,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 20],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SID", 21],
      ["SPM", 2],
      ["TCD", 22],
    ]),
  ],
  [
    17,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SPM", 2],
      ["TQ1", 17],
      ["TQ2", 23],
    ]),
  ],
  [
    18,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 18],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SPM", 2],
      ["TQ1", 17],
    ]),
  ],
  [
    19,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 18],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SPM", 2],
      ["TQ1", 17],
    ]),
  ],
  [
    20,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 20],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SPM", 2],
    ]),
  ],
  [
    21,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 20],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SID", 21],
      ["SPM", 2],
    ]),
  ],
  [
    22,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["NTE", 20],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SID", 21],
      ["SPM", 2],
    ]),
  ],
  [
    23,
    new Map([
      ["CTI", 15],
      ["DSC", 14],
      ["OBR", 12],
      ["OBX", 16],
      ["SAC", 7],
      ["SPM", 2],
      ["TQ1", 17],
      ["TQ2", 23],
    ]),
  ],
]);
export const effects = {
  "10:PV1": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
    groupsOpened: ["OUL_R23/PV1PV2_SUPPGRP"],
  },
  "10:SPM": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP", "OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "11:PV1": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
    groupsOpened: ["OUL_R23/PV1PV2_SUPPGRP"],
  },
  "11:SPM": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP", "OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "12:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "12:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "12:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "12:OBX": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "12:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "12:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "12:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
  },
  "13:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "15:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
    groupsOpened: [],
  },
  "15:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "15:SAC": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "15:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "16:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "16:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "16:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "16:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "16:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "17:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "17:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "17:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "17:OBX": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "17:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "17:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "17:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
  },
  "18:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "18:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "18:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "18:OBX": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "18:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "18:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "18:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
  },
  "19:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "19:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "19:OBX": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "19:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "19:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "19:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
  },
  "1:PID": {
    groupsClosed: [],
    groupsOpened: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
  },
  "1:PV1": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
    groupsOpened: ["OUL_R23/PV1PV2_SUPPGRP"],
  },
  "1:SPM": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP", "OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "20:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "20:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "20:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "20:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "20:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "20:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "21:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "21:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "21:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "21:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "21:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "21:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "22:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "22:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "22:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "22:OBX": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "22:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "22:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "23:CTI": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "23:DSC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [],
  },
  "23:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "23:OBX": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
    ],
  },
  "23:SAC": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "23:SPM": {
    groupsClosed: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/OBXTCDSIDNTE_SUPPGRP",
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "23:TQ1": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER/TQ1TQ2_SUPPGRP",
    ],
  },
  "2:SAC": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "3:SPM": {
    groupsClosed: ["OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "4:PV1": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
    groupsOpened: ["OUL_R23/PV1PV2_SUPPGRP"],
  },
  "4:SPM": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP", "OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "5:PID": {
    groupsClosed: [],
    groupsOpened: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
  },
  "5:PV1": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
    groupsOpened: ["OUL_R23/PV1PV2_SUPPGRP"],
  },
  "5:SPM": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP", "OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "6:PID": {
    groupsClosed: [],
    groupsOpened: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
  },
  "6:PV1": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP"],
    groupsOpened: ["OUL_R23/PV1PV2_SUPPGRP"],
  },
  "6:SPM": {
    groupsClosed: ["OUL_R23/PIDPD1NTE_SUPPGRP", "OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
  "7:OBR": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER/ORDER",
    ],
  },
  "8:SAC": {
    groupsClosed: [],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP/CONTAINER",
    ],
  },
  "9:SPM": {
    groupsClosed: ["OUL_R23/PV1PV2_SUPPGRP"],
    groupsOpened: [
      "OUL_R23/SPMOBXSACINVOBRORCNTETQ1TQ2OBXTCDSIDNTECTI_SUPPGRP",
    ],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
