// Generated segment definitions for v2.1
export const segments = [
  { id: "ACC", title: "Accident" },
  { id: "ADD", title: "Addendum" },
  { id: "BHS", title: "Batch Header" },
  { id: "BLG", title: "Billing" },
  { id: "BTS", title: "Batch Trailer" },
  { id: "DG1", title: "Diagnosis" },
  { id: "DSC", title: "Continuation Pointer" },
  { id: "DSP", title: "Display Data" },
  { id: "ERR", title: "Error" },
  { id: "EVN", title: "Event Type" },
  { id: "FHS", title: "File Header" },
  { id: "FT1", title: "Financial Transaction" },
  { id: "FTS", title: "File Trailer" },
  { id: "GT1", title: "Guarantor" },
  { id: "IN1", title: "Insurance" },
  { id: "MRG", title: "Merge Patient Information" },
  { id: "MSA", title: "Message Acknowledgment" },
  { id: "MSH", title: "Message Header" },
  { id: "NCK", title: "System Clock" },
  { id: "NK1", title: "Next of Kin / Associated Parties" },
  { id: "NPU", title: "Bed Status Update" },
  { id: "NSC", title: "Application Status Change" },
  { id: "NST", title: "Application Control Level Statistics" },
  { id: "NTE", title: "Notes and Comments" },
  { id: "OBR", title: "Observation Request" },
  { id: "OBX", title: "Observation/Result" },
  { id: "ORC", title: "Common Order" },
  { id: "ORO", title: "ORO" },
  { id: "PID", title: "Patient Identification" },
  { id: "PR1", title: "Procedures" },
  { id: "PV1", title: "Patient Visit" },
  { id: "QRD", title: "QRD" },
  { id: "QRF", title: "QRF" },
  { id: "RX1", title: "RX1" },
  { id: "UB1", title: "UB82" },
  { id: "URD", title: "Results/Update Definition" },
  { id: "URS", title: "Unsolicited Selection" },
] as const;
