// Generated table profile for 0003 (v2.1)

export const id = "0003";
export const description = "EVENT TYPE CODE";
export const type = "hl7";
export const codes = [
  { description: "Admit a patient", name: "A01" },
  { description: "Transfer a Patient", name: "A02" },
  { description: "Discharge a Patient", name: "A03" },
  { description: "Register a Patient", name: "A04" },
  { description: "Pre-admit a Patient", name: "A05" },
  { description: "Transfer an outpatient to inpatient", name: "A06" },
  { description: "Transfer an Inpatient to Outpatient", name: "A07" },
  { description: "Update patient information", name: "A08" },
  { description: "Patient departing", name: "A09" },
  { description: "Patient arriving", name: "A10" },
  { description: "Cancel admit", name: "A11" },
  { description: "Cancel transfer", name: "A12" },
  { description: "Cancel discharge", name: "A13" },
  { description: "Pending admit", name: "A14" },
  { description: "Pending transfer", name: "A15" },
  { description: "Pending discharge", name: "A16" },
  { description: "Swap Patients", name: "A17" },
  { description: "Merge patient information", name: "A18" },
  { description: "Patient query", name: "A19" },
  { description: "Bed status updates", name: "A20" },
  { description: "Leave of Absence - Out (leaving)", name: "A21" },
  { description: "Leave of Absence - In (returning)", name: "A22" },
  { description: "Delete a Patient Record", name: "A23" },
  { description: "Link Patient Records", name: "A24" },
  { description: "Order message", name: "O01" },
  { description: "Order response", name: "O02" },
  { description: "Add and update patient account", name: "P01" },
  { description: "Purge Patient Accounts", name: "P02" },
  { description: "Post detail financial transaction", name: "P03" },
  { description: "Generate bills and A/R statements", name: "P04" },
  { description: "Immediate access", name: "Q01" },
  { description: "Deferred Access", name: "Q02" },
  { description: "Unsolicited transmission of requested Observ.", name: "R01" },
  { description: "Display oriented results, query/unsol. update", name: "R03" },
] as const;
