// Generated table profile for 0360 (v2.4)

export const id = "0360";
export const description = "Degree";
export const type = "user";
export const codes = [
  { name: "AA", description: "Associate of Arts" },
  { name: "AAS", description: "Associate of Applied Science" },
  { name: "ABA", description: "Associate of Business Administration" },
  { name: "AE", description: "Associate of Engineering" },
  { name: "AS", description: "Associate of Science" },
  { name: "BA", description: "Bachelor of Arts" },
  { name: "BBA", description: "Bachelor of Business Administration" },
  { name: "BE", description: "Bachelor or Engineering" },
  { name: "BFA", description: "Bachelor of Fine Arts" },
  { name: "BN", description: "Bachelor of Nursing" },
  { name: "BS", description: "Bachelor of Science" },
  { name: "BSL", description: "Bachelor of Science - Law" },
  { name: "BT", description: "Bachelor of Theology" },
  { name: "CER", description: "Certificate" },
  { name: "DBA", description: "Doctor of Business Administration" },
  { name: "DED", description: "Doctor of Education" },
  { name: "DIP", description: "Diploma" },
  { name: "DO", description: "Doctor of Osteopathy" },
  { name: "HS", description: "High School Graduate" },
  { name: "JD", description: "Juris Doctor" },
  { name: "MA", description: "Master of Arts" },
  { name: "MBA", description: "Master of Business Administration" },
  { name: "MCE", description: "Master of Civil Engineering" },
  { name: "MD", description: "Doctor of Medicine" },
  { name: "MDI", description: "Master of Divinity" },
  { name: "ME", description: "Master of Engineering" },
  { name: "MED", description: "Master of Education" },
  { name: "MEE", description: "Master of Electrical Engineering" },
  { name: "MFA", description: "Master of Fine Arts" },
  { name: "MME", description: "Master of Mechanical Engineering" },
  { name: "MS", description: "Master of Science" },
  { name: "MSL", description: "Master of Science - Law" },
  { name: "MT", description: "Master of Theology" },
  { name: "NG", description: "Non-Graduate" },
  { name: "PharmD", description: "Doctor of Pharmacy" },
  { name: "PHD", description: "Doctor of Philosophy" },
  { name: "PHE", description: "Doctor of Engineering" },
  { name: "PHS", description: "Doctor of Science" },
  { name: "SEC", description: "Secretarial Certificate" },
  { name: "TS", description: "Trade School Graduate" },
] as const;
