// Generated segment profile for BPX (v2.7)

export const segmentId = "BPX";
export const fields = [
  {
    sequence: 1,
    id: "BPX-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - BPX",
    item: "1714",
  },
  {
    sequence: 2,
    id: "BPX-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70510",
    name: "BP Dispense Status",
    item: "1715",
  },
  {
    sequence: 3,
    id: "BPX-3",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70511",
    name: "BP Status",
    item: "1716",
  },
  {
    sequence: 4,
    id: "BPX-4",
    required: true,
    repeatable: false,
    datatype: "DTM",
    name: "BP Date/Time of Status",
    item: "1717",
  },
  {
    sequence: 5,
    id: "BPX-5",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "BC Donation ID",
    item: "1718",
  },
  {
    sequence: 6,
    id: "BPX-6",
    required: false,
    repeatable: false,
    datatype: "CNE",
    table: "HL79999",
    name: "BC Component",
    item: "1719",
  },
  {
    sequence: 7,
    id: "BPX-7",
    required: false,
    repeatable: false,
    datatype: "CNE",
    table: "HL79999",
    name: "BC Donation Type / Intended Use",
    item: "1720",
  },
  {
    sequence: 8,
    id: "BPX-8",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70512",
    name: "CP Commercial Product",
    item: "1721",
  },
  {
    sequence: 9,
    id: "BPX-9",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "CP Manufacturer",
    item: "1722",
  },
  {
    sequence: 10,
    id: "BPX-10",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "CP Lot Number",
    item: "1723",
  },
  {
    sequence: 11,
    id: "BPX-11",
    required: false,
    repeatable: false,
    datatype: "CNE",
    table: "HL79999",
    name: "BP Blood Group",
    item: "1724",
  },
  {
    sequence: 12,
    id: "BPX-12",
    required: false,
    repeatable: true,
    datatype: "CNE",
    table: "HL79999",
    name: "BC Special Testing",
    item: "1725",
  },
  {
    sequence: 13,
    id: "BPX-13",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "BP Expiration Date/Time",
    item: "1726",
  },
  {
    sequence: 14,
    id: "BPX-14",
    required: true,
    repeatable: false,
    datatype: "NM",
    name: "BP Quantity",
    item: "1727",
  },
  {
    sequence: 15,
    id: "BPX-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "BP Amount",
    item: "1728",
  },
  {
    sequence: 16,
    id: "BPX-16",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL79999",
    name: "BP Units",
    item: "1729",
  },
  {
    sequence: 17,
    id: "BPX-17",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "BP Unique ID",
    item: "1730",
  },
  {
    sequence: 18,
    id: "BPX-18",
    required: false,
    repeatable: false,
    datatype: "PL",
    name: "BP Actual Dispensed To Location",
    item: "1731",
  },
  {
    sequence: 19,
    id: "BPX-19",
    required: false,
    repeatable: false,
    datatype: "XAD",
    name: "BP Actual Dispensed To Address",
    item: "1732",
  },
  {
    sequence: 20,
    id: "BPX-20",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "BP Dispensed to Receiver",
    item: "1733",
  },
  {
    sequence: 21,
    id: "BPX-21",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "BP Dispensing Individual",
    item: "1734",
  },
] as const;
