// Generated segment profile for EDU (v2.7)

export const segmentId = "EDU";
export const fields = [
  {
    sequence: 1,
    id: "EDU-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - EDU",
    item: "1448",
  },
  {
    sequence: 2,
    id: "EDU-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70360",
    name: "Academic Degree",
    item: "1449",
  },
  {
    sequence: 3,
    id: "EDU-3",
    required: false,
    repeatable: false,
    datatype: "DR",
    name: "Academic Degree Program Date Range",
    item: "1597",
  },
  {
    sequence: 4,
    id: "EDU-4",
    required: false,
    repeatable: false,
    datatype: "DR",
    name: "Academic Degree Program Participation Date Range",
    item: "1450",
  },
  {
    sequence: 5,
    id: "EDU-5",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Academic Degree Granted Date",
    item: "1451",
  },
  {
    sequence: 6,
    id: "EDU-6",
    required: false,
    repeatable: false,
    datatype: "XON",
    name: "School",
    item: "1452",
  },
  {
    sequence: 7,
    id: "EDU-7",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70402",
    name: "School Type Code",
    item: "1453",
  },
  {
    sequence: 8,
    id: "EDU-8",
    required: false,
    repeatable: false,
    datatype: "XAD",
    name: "School Address",
    item: "1454",
  },
  {
    sequence: 9,
    id: "EDU-9",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Major Field of Study",
    item: "1885",
  },
] as const;
