// Generated segment profile for NST (v2.7)

export const segmentId = "NST";
export const fields = [
  {
    sequence: 1,
    id: "NST-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Statistics Available",
    item: "1173",
  },
  {
    sequence: 2,
    id: "NST-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Source Identifier",
    item: "1174",
  },
  {
    sequence: 3,
    id: "NST-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    table: "HL70332",
    name: "Source Type",
    item: "1175",
  },
  {
    sequence: 4,
    id: "NST-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Statistics Start",
    item: "1176",
  },
  {
    sequence: 5,
    id: "NST-5",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Statistics End",
    item: "1177",
  },
  {
    sequence: 6,
    id: "NST-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Receive Character Count",
    item: "1178",
  },
  {
    sequence: 7,
    id: "NST-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Send Character Count",
    item: "1179",
  },
  {
    sequence: 8,
    id: "NST-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Messages Received",
    item: "1180",
  },
  {
    sequence: 9,
    id: "NST-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Messages Sent",
    item: "1181",
  },
  {
    sequence: 10,
    id: "NST-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Checksum Errors Received",
    item: "1182",
  },
  {
    sequence: 11,
    id: "NST-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Length Errors Received",
    item: "1183",
  },
  {
    sequence: 12,
    id: "NST-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Other Errors Received",
    item: "1184",
  },
  {
    sequence: 13,
    id: "NST-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Connect Timeouts",
    item: "1185",
  },
  {
    sequence: 14,
    id: "NST-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Receive Timeouts",
    item: "1186",
  },
  {
    sequence: 15,
    id: "NST-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Application control-level Errors",
    item: "1187",
  },
] as const;
