// Generated segment profile for PRB (v2.7)

export const segmentId = "PRB";
export const fields = [
  {
    sequence: 1,
    id: "PRB-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70287",
    name: "Action Code",
    item: "816",
  },
  {
    sequence: 2,
    id: "PRB-2",
    required: true,
    repeatable: false,
    datatype: "DTM",
    name: "Action Date/Time",
    item: "817",
  },
  {
    sequence: 3,
    id: "PRB-3",
    required: true,
    repeatable: false,
    datatype: "CWE",
    name: "Problem ID",
    item: "838",
  },
  {
    sequence: 4,
    id: "PRB-4",
    required: true,
    repeatable: false,
    datatype: "EI",
    name: "Problem Instance ID",
    item: "839",
  },
  {
    sequence: 5,
    id: "PRB-5",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Episode of Care ID",
    item: "820",
  },
  {
    sequence: 6,
    id: "PRB-6",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Problem List Priority",
    item: "841",
  },
  {
    sequence: 7,
    id: "PRB-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Problem Established Date/Time",
    item: "842",
  },
  {
    sequence: 8,
    id: "PRB-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Anticipated Problem Resolution Date/Time",
    item: "843",
  },
  {
    sequence: 9,
    id: "PRB-9",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Actual Problem Resolution Date/Time",
    item: "844",
  },
  {
    sequence: 10,
    id: "PRB-10",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Problem Classification",
    item: "845",
  },
  {
    sequence: 11,
    id: "PRB-11",
    required: false,
    repeatable: true,
    datatype: "CWE",
    name: "Problem Management Discipline",
    item: "846",
  },
  {
    sequence: 12,
    id: "PRB-12",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Problem Persistence",
    item: "847",
  },
  {
    sequence: 13,
    id: "PRB-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Problem Confirmation Status",
    item: "848",
  },
  {
    sequence: 14,
    id: "PRB-14",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Problem Life Cycle Status",
    item: "849",
  },
  {
    sequence: 15,
    id: "PRB-15",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Problem Life Cycle Status Date/Time",
    item: "850",
  },
  {
    sequence: 16,
    id: "PRB-16",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Problem Date of Onset",
    item: "851",
  },
  {
    sequence: 17,
    id: "PRB-17",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Problem Onset Text",
    item: "852",
  },
  {
    sequence: 18,
    id: "PRB-18",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Problem Ranking",
    item: "853",
  },
  {
    sequence: 19,
    id: "PRB-19",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Certainty of Problem",
    item: "854",
  },
  {
    sequence: 20,
    id: "PRB-20",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Probability of Problem (0-1)",
    item: "855",
  },
  {
    sequence: 21,
    id: "PRB-21",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Individual Awareness of Problem",
    item: "856",
  },
  {
    sequence: 22,
    id: "PRB-22",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Problem Prognosis",
    item: "857",
  },
  {
    sequence: 23,
    id: "PRB-23",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Individual Awareness of Prognosis",
    item: "858",
  },
  {
    sequence: 24,
    id: "PRB-24",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Family/Significant Other Awareness of Problem/Prognosis",
    item: "859",
  },
  {
    sequence: 25,
    id: "PRB-25",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Security/Sensitivity",
    item: "823",
  },
  {
    sequence: 26,
    id: "PRB-26",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70836",
    name: "Problem Severity",
    item: "2234",
  },
  {
    sequence: 27,
    id: "PRB-27",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70838",
    name: "Problem Perspective",
    item: "2235",
  },
  {
    sequence: 28,
    id: "PRB-28",
    required: false,
    repeatable: false,
    datatype: "CNE",
    table: "HL70725",
    name: "Mood Code",
    item: "2237",
  },
] as const;
