// Generated segment profile for RQ1 (v2.7)

export const segmentId = "RQ1";
export const fields = [
  {
    sequence: 1,
    id: "RQ1-1",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Anticipated Price",
    item: "285",
  },
  {
    sequence: 2,
    id: "RQ1-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70385",
    name: "Manufacturer Identifier",
    item: "286",
  },
  {
    sequence: 3,
    id: "RQ1-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Manufacturer's Catalog",
    item: "287",
  },
  {
    sequence: 4,
    id: "RQ1-4",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Vendor ID",
    item: "288",
  },
  {
    sequence: 5,
    id: "RQ1-5",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Vendor Catalog",
    item: "289",
  },
  {
    sequence: 6,
    id: "RQ1-6",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Taxable",
    item: "290",
  },
  {
    sequence: 7,
    id: "RQ1-7",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Substitute Allowed",
    item: "291",
  },
] as const;
