// Generated segment profile for TQ1 (v2.7)

export const segmentId = "TQ1";
export const fields = [
  {
    sequence: 1,
    id: "TQ1-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - TQ1",
    item: "1627",
  },
  {
    sequence: 2,
    id: "TQ1-2",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Quantity",
    item: "1628",
  },
  {
    sequence: 3,
    id: "TQ1-3",
    required: false,
    repeatable: true,
    datatype: "RPT",
    name: "Repeat Pattern",
    item: "1629",
  },
  {
    sequence: 4,
    id: "TQ1-4",
    required: false,
    repeatable: true,
    datatype: "TM",
    name: "Explicit Time",
    item: "1630",
  },
  {
    sequence: 5,
    id: "TQ1-5",
    required: false,
    repeatable: true,
    datatype: "CQ",
    name: "Relative Time and Units",
    item: "1631",
  },
  {
    sequence: 6,
    id: "TQ1-6",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Service Duration",
    item: "1632",
  },
  {
    sequence: 7,
    id: "TQ1-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Start date/time",
    item: "1633",
  },
  {
    sequence: 8,
    id: "TQ1-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "End date/time",
    item: "1634",
  },
  {
    sequence: 9,
    id: "TQ1-9",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70485",
    name: "Priority",
    item: "1635",
  },
  {
    sequence: 10,
    id: "TQ1-10",
    required: false,
    repeatable: false,
    datatype: "TX",
    name: "Condition text",
    item: "1636",
  },
  {
    sequence: 11,
    id: "TQ1-11",
    required: false,
    repeatable: false,
    datatype: "TX",
    name: "Text instruction",
    item: "1637",
  },
  {
    sequence: 12,
    id: "TQ1-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70472",
    name: "Conjunction",
    item: "1638",
  },
  {
    sequence: 13,
    id: "TQ1-13",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Occurrence duration",
    item: "1639",
  },
  {
    sequence: 14,
    id: "TQ1-14",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Total occurrences",
    item: "1640",
  },
] as const;
