// Generated segment profile for ACC (v2.7.1)

export const segmentId = "ACC";
export const fields = [
  {
    sequence: 1,
    id: "ACC-1",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Accident Date/Time",
    item: "527",
  },
  {
    sequence: 2,
    id: "ACC-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70050",
    name: "Accident Code",
    item: "528",
  },
  {
    sequence: 3,
    id: "ACC-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Accident Location",
    item: "529",
  },
  {
    sequence: 4,
    id: "ACC-4",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70347",
    name: "Auto Accident State",
    item: "812",
  },
  {
    sequence: 5,
    id: "ACC-5",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Accident Job Related Indicator",
    item: "813",
  },
  {
    sequence: 6,
    id: "ACC-6",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Accident Death Indicator",
    item: "814",
  },
  {
    sequence: 7,
    id: "ACC-7",
    required: false,
    repeatable: false,
    datatype: "XCN",
    name: "Entered By",
    item: "224",
  },
  {
    sequence: 8,
    id: "ACC-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Accident Description",
    item: "1503",
  },
  {
    sequence: 9,
    id: "ACC-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Brought In By",
    item: "1504",
  },
  {
    sequence: 10,
    id: "ACC-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Police Notified Indicator",
    item: "1505",
  },
  {
    sequence: 11,
    id: "ACC-11",
    required: false,
    repeatable: false,
    datatype: "XAD",
    name: "Accident Address",
    item: "1853",
  },
  {
    sequence: 12,
    id: "ACC-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Degree of patient liability",
    item: "2374",
  },
] as const;
