// Generated segment profile for AIL (v2.7.1)

export const segmentId = "AIL";
export const fields = [
  {
    datatype: "SI",
    id: "AIL-1",
    item: "902",
    maxLength: 4,
    name: "Set ID - AIL",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "AIL-2",
    item: "763",
    maxLength: 1,
    name: "Segment Action Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "PL",
    id: "AIL-3",
    item: "903",
    name: "Location Resource ID",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "AIL-4",
    item: "904",
    name: "Location Type - AIL",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70305",
  },
  {
    datatype: "CWE",
    id: "AIL-5",
    item: "905",
    name: "Location Group",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DTM",
    id: "AIL-6",
    item: "1202",
    name: "Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "AIL-7",
    item: "891",
    name: "Start Date/Time Offset",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CNE",
    id: "AIL-8",
    item: "892",
    name: "Start Date/Time Offset Units",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "NM",
    id: "AIL-9",
    item: "893",
    name: "Duration",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CNE",
    id: "AIL-10",
    item: "894",
    name: "Duration Units",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "AIL-11",
    item: "895",
    name: "Allow Substitution Code",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70279",
  },
  {
    datatype: "CWE",
    id: "AIL-12",
    item: "889",
    name: "Filler Status Code",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70278",
  },
] as const;
