// Generated segment profile for AUT (v2.7.1)

export const segmentId = "AUT";
export const fields = [
  {
    datatype: "CWE",
    id: "AUT-1",
    item: "1146",
    name: "Authorizing Payor, Plan ID",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70072",
  },
  {
    datatype: "CWE",
    id: "AUT-2",
    item: "1147",
    name: "Authorizing Payor, Company ID",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70285",
  },
  {
    datatype: "ST",
    id: "AUT-3",
    item: "1148",
    name: "Authorizing Payor, Company Name",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "DTM",
    id: "AUT-4",
    item: "1149",
    name: "Authorization Effective Date",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "DTM",
    id: "AUT-5",
    item: "1150",
    name: "Authorization Expiration Date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "EI",
    id: "AUT-6",
    item: "1151",
    name: "Authorization Identifier",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CP",
    id: "AUT-7",
    item: "1152",
    name: "Reimbursement Limit",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CQ",
    id: "AUT-8",
    item: "1153",
    name: "Requested Number of Treatments",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CQ",
    id: "AUT-9",
    item: "1154",
    name: "Authorized Number of Treatments",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "DTM",
    id: "AUT-10",
    item: "1145",
    name: "Process Date",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "AUT-11",
    item: "2375",
    name: "Requested Discipline(s)",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "AUT-12",
    item: "2376",
    name: "Authorized Discipline(s)",
    repeatable: true,
    required: false,
    sequence: 12,
  },
] as const;
