// Generated segment profile for CM0 (v2.7.1)

export const segmentId = "CM0";
export const fields = [
  {
    sequence: 1,
    id: "CM0-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - CM0",
    item: "1010",
  },
  {
    sequence: 2,
    id: "CM0-2",
    required: true,
    repeatable: false,
    datatype: "EI",
    name: "Sponsor Study ID",
    item: "1011",
  },
  {
    sequence: 3,
    id: "CM0-3",
    required: false,
    repeatable: false,
    datatype: "EI",
    name: "Alternate Study ID",
    item: "1036",
  },
  {
    sequence: 4,
    id: "CM0-4",
    required: true,
    repeatable: false,
    datatype: "ST",
    name: "Title of Study",
    item: "1013",
  },
  {
    sequence: 5,
    id: "CM0-5",
    required: false,
    repeatable: true,
    datatype: "XCN",
    name: "Chairman of Study",
    item: "1014",
  },
  {
    sequence: 6,
    id: "CM0-6",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Last IRB Approval Date",
    item: "1015",
  },
  {
    sequence: 7,
    id: "CM0-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Total Accrual to Date",
    item: "1016",
  },
  {
    sequence: 8,
    id: "CM0-8",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Last Accrual Date",
    item: "1017",
  },
  {
    sequence: 9,
    id: "CM0-9",
    required: false,
    repeatable: true,
    datatype: "XCN",
    name: "Contact for Study",
    item: "1018",
  },
  {
    sequence: 10,
    id: "CM0-10",
    required: false,
    repeatable: false,
    datatype: "XTN",
    name: "Contact's Telephone Number",
    item: "1019",
  },
  {
    sequence: 11,
    id: "CM0-11",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Contact's Address",
    item: "1020",
  },
] as const;
