// Generated segment profile for CTD (v2.7.1)

export const segmentId = "CTD";
export const fields = [
  {
    datatype: "CWE",
    id: "CTD-1",
    item: "196",
    name: "Contact Role",
    repeatable: true,
    required: true,
    sequence: 1,
    table: "HL70131",
  },
  {
    datatype: "XPN",
    id: "CTD-2",
    item: "1165",
    name: "Contact Name",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XAD",
    id: "CTD-3",
    item: "1166",
    name: "Contact Address",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "PL",
    id: "CTD-4",
    item: "1167",
    name: "Contact Location",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XTN",
    id: "CTD-5",
    item: "1168",
    name: "Contact Communication Information",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "CTD-6",
    item: "684",
    name: "Preferred Method of Contact",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70185",
  },
  {
    datatype: "PLN",
    id: "CTD-7",
    item: "1171",
    name: "Contact Identifiers",
    repeatable: true,
    required: false,
    sequence: 7,
  },
] as const;
