// Generated segment profile for MSH (v2.7.1)

export const segmentId = "MSH";
export const fields = [
  {
    datatype: "ST",
    id: "MSH-1",
    item: "1",
    maxLength: 1,
    name: "Field Separator",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ST",
    id: "MSH-2",
    item: "2",
    maxLength: 5,
    name: "Encoding Characters",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "HD",
    id: "MSH-3",
    item: "3",
    name: "Sending Application",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70361",
  },
  {
    datatype: "HD",
    id: "MSH-4",
    item: "4",
    name: "Sending Facility",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70362",
  },
  {
    datatype: "HD",
    id: "MSH-5",
    item: "5",
    name: "Receiving Application",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70361",
  },
  {
    datatype: "HD",
    id: "MSH-6",
    item: "6",
    name: "Receiving Facility",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70362",
  },
  {
    datatype: "DTM",
    id: "MSH-7",
    item: "7",
    name: "Date/Time of Message",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "MSH-8",
    item: "8",
    name: "Security",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "MSG",
    id: "MSH-9",
    item: "9",
    name: "Message Type",
    repeatable: false,
    required: true,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "MSH-10",
    item: "10",
    maxLength: 199,
    name: "Message Control ID",
    repeatable: false,
    required: true,
    sequence: 10,
  },
  {
    datatype: "PT",
    id: "MSH-11",
    item: "11",
    name: "Processing ID",
    repeatable: false,
    required: true,
    sequence: 11,
  },
  {
    datatype: "VID",
    id: "MSH-12",
    item: "12",
    name: "Version ID",
    repeatable: false,
    required: true,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "MSH-13",
    item: "13",
    name: "Sequence Number",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "MSH-14",
    item: "14",
    name: "Continuation Pointer",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ID",
    id: "MSH-15",
    item: "15",
    maxLength: 2,
    name: "Accept Acknowledgment Type",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70155",
  },
  {
    datatype: "ID",
    id: "MSH-16",
    item: "16",
    maxLength: 2,
    name: "Application Acknowledgment Type",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70155",
  },
  {
    datatype: "ID",
    id: "MSH-17",
    item: "17",
    maxLength: 3,
    name: "Country Code",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70399",
  },
  {
    datatype: "ID",
    id: "MSH-18",
    item: "692",
    maxLength: 15,
    name: "Character Set",
    repeatable: true,
    required: false,
    sequence: 18,
    table: "HL70211",
  },
  {
    datatype: "CWE",
    id: "MSH-19",
    item: "693",
    name: "Principal Language Of Message",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "MSH-20",
    item: "1317",
    maxLength: 13,
    name: "Alternate Character Set Handling Scheme",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70356",
  },
  {
    datatype: "EI",
    id: "MSH-21",
    item: "1598",
    name: "Message Profile Identifier",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "XON",
    id: "MSH-22",
    item: "1823",
    name: "Sending Responsible Organization",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "XON",
    id: "MSH-23",
    item: "1824",
    name: "Receiving Responsible Organization",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "HD",
    id: "MSH-24",
    item: "1825",
    name: "Sending Network Address",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "HD",
    id: "MSH-25",
    item: "1826",
    name: "Receiving Network Address",
    repeatable: false,
    required: false,
    sequence: 25,
  },
] as const;
