// Generated segment profile for NK1 (v2.7.1)

export const segmentId = "NK1";
export const fields = [
  {
    datatype: "SI",
    id: "NK1-1",
    item: "190",
    maxLength: 4,
    name: "Set ID - NK1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "XPN",
    id: "NK1-2",
    item: "191",
    name: "Name",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "NK1-3",
    item: "192",
    name: "Relationship",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70063",
  },
  {
    datatype: "XAD",
    id: "NK1-4",
    item: "193",
    name: "Address",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XTN",
    id: "NK1-5",
    item: "194",
    name: "Phone Number",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "XTN",
    id: "NK1-6",
    item: "195",
    name: "Business Phone Number",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "NK1-7",
    item: "196",
    name: "Contact Role",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70131",
  },
  {
    datatype: "DT",
    id: "NK1-8",
    item: "197",
    name: "Start Date",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DT",
    id: "NK1-9",
    item: "198",
    name: "End Date",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ST",
    id: "NK1-10",
    item: "199",
    name: "Next of Kin / Associated Parties Job Title",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "JCC",
    id: "NK1-11",
    item: "200",
    name: "Next of Kin / Associated Parties Job Code/Class",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CX",
    id: "NK1-12",
    item: "201",
    name: "Next of Kin / Associated Parties Employee Number",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "XON",
    id: "NK1-13",
    item: "202",
    name: "Organization Name - NK1",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CWE",
    id: "NK1-14",
    item: "119",
    name: "Marital Status",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70002",
  },
  {
    datatype: "CWE",
    id: "NK1-15",
    item: "111",
    name: "Administrative Sex",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70001",
  },
  {
    datatype: "DTM",
    id: "NK1-16",
    item: "110",
    name: "Date/Time of Birth",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CWE",
    id: "NK1-17",
    item: "755",
    name: "Living Dependency",
    repeatable: true,
    required: false,
    sequence: 17,
    table: "HL70223",
  },
  {
    datatype: "CWE",
    id: "NK1-18",
    item: "145",
    name: "Ambulatory Status",
    repeatable: true,
    required: false,
    sequence: 18,
    table: "HL70009",
  },
  {
    datatype: "CWE",
    id: "NK1-19",
    item: "129",
    name: "Citizenship",
    repeatable: true,
    required: false,
    sequence: 19,
    table: "HL70171",
  },
  {
    datatype: "CWE",
    id: "NK1-20",
    item: "118",
    name: "Primary Language",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70296",
  },
  {
    datatype: "CWE",
    id: "NK1-21",
    item: "742",
    name: "Living Arrangement",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70220",
  },
  {
    datatype: "CWE",
    id: "NK1-22",
    item: "743",
    name: "Publicity Code",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70215",
  },
  {
    datatype: "ID",
    id: "NK1-23",
    item: "744",
    maxLength: 1,
    name: "Protection Indicator",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "NK1-24",
    item: "745",
    name: "Student Indicator",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70231",
  },
  {
    datatype: "CWE",
    id: "NK1-25",
    item: "120",
    name: "Religion",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70006",
  },
  {
    datatype: "XPN",
    id: "NK1-26",
    item: "109",
    name: "Mother's Maiden Name",
    repeatable: true,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CWE",
    id: "NK1-27",
    item: "739",
    name: "Nationality",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70212",
  },
  {
    datatype: "CWE",
    id: "NK1-28",
    item: "125",
    name: "Ethnic Group",
    repeatable: true,
    required: false,
    sequence: 28,
    table: "HL70189",
  },
  {
    datatype: "CWE",
    id: "NK1-29",
    item: "747",
    name: "Contact Reason",
    repeatable: true,
    required: false,
    sequence: 29,
    table: "HL70222",
  },
  {
    datatype: "XPN",
    id: "NK1-30",
    item: "748",
    name: "Contact Person's Name",
    repeatable: true,
    required: false,
    sequence: 30,
    table: "HL70200",
  },
  {
    datatype: "XTN",
    id: "NK1-31",
    item: "749",
    name: "Contact Person's Telephone Number",
    repeatable: true,
    required: false,
    sequence: 31,
  },
  {
    datatype: "XAD",
    id: "NK1-32",
    item: "750",
    name: "Contact Person's Address",
    repeatable: true,
    required: false,
    sequence: 32,
  },
  {
    datatype: "CX",
    id: "NK1-33",
    item: "751",
    name: "Next of Kin/Associated Party's Identifiers",
    repeatable: true,
    required: false,
    sequence: 33,
  },
  {
    datatype: "CWE",
    id: "NK1-34",
    item: "752",
    name: "Job Status",
    repeatable: false,
    required: false,
    sequence: 34,
    table: "HL70311",
  },
  {
    datatype: "CWE",
    id: "NK1-35",
    item: "113",
    name: "Race",
    repeatable: true,
    required: false,
    sequence: 35,
    table: "HL70005",
  },
  {
    datatype: "CWE",
    id: "NK1-36",
    item: "753",
    name: "Handicap",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL70295",
  },
  {
    datatype: "ST",
    id: "NK1-37",
    item: "754",
    name: "Contact Person Social Security Number",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "ST",
    id: "NK1-38",
    item: "1905",
    name: "Next of Kin Birth Place",
    repeatable: false,
    required: false,
    sequence: 38,
  },
  {
    datatype: "CWE",
    id: "NK1-39",
    item: "146",
    name: "VIP Indicator",
    repeatable: false,
    required: false,
    sequence: 39,
    table: "HL70099",
  },
  {
    datatype: "XTN",
    id: "NK1-40",
    item: "2292",
    name: "Next of Kin Telecommunication Information",
    repeatable: false,
    required: false,
    sequence: 40,
  },
  {
    datatype: "XTN",
    id: "NK1-41",
    item: "2293",
    name: "Contact Person's Telecommunication Information",
    repeatable: false,
    required: false,
    sequence: 41,
  },
] as const;
