// Generated segment profile for OBX (v2.7.1)

export const segmentId = "OBX";
export const fields = [
  {
    datatype: "SI",
    id: "OBX-1",
    item: "569",
    maxLength: 4,
    name: "Set ID - OBX",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "OBX-2",
    item: "570",
    maxLength: 3,
    name: "Value Type",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70125",
  },
  {
    datatype: "CWE",
    id: "OBX-3",
    item: "571",
    name: "Observation Identifier",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "ST",
    id: "OBX-4",
    item: "572",
    name: "Observation Sub-ID",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "varies",
    id: "OBX-5",
    item: "573",
    name: "Observation Value",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "OBX-6",
    item: "574",
    name: "Units",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "OBX-7",
    item: "575",
    name: "References Range",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CWE",
    id: "OBX-8",
    item: "576",
    name: "Interpretation Codes",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70078",
  },
  {
    datatype: "NM",
    id: "OBX-9",
    item: "577",
    name: "Probability",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "OBX-10",
    item: "578",
    maxLength: 2,
    name: "Nature of Abnormal Test",
    repeatable: true,
    required: false,
    sequence: 10,
    table: "HL70080",
  },
  {
    datatype: "ID",
    id: "OBX-11",
    item: "579",
    maxLength: 1,
    name: "Observation Result Status",
    repeatable: false,
    required: true,
    sequence: 11,
    table: "HL70085",
  },
  {
    datatype: "DTM",
    id: "OBX-12",
    item: "580",
    name: "Effective Date of Reference Range",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "ST",
    id: "OBX-13",
    item: "581",
    name: "User Defined Access Checks",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DTM",
    id: "OBX-14",
    item: "582",
    name: "Date/Time of the Observation",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "OBX-15",
    item: "583",
    name: "Producer's ID",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "XCN",
    id: "OBX-16",
    item: "584",
    name: "Responsible Observer",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CWE",
    id: "OBX-17",
    item: "936",
    name: "Observation Method",
    repeatable: true,
    required: false,
    sequence: 17,
  },
  {
    datatype: "EI",
    id: "OBX-18",
    item: "1479",
    name: "Equipment Instance Identifier",
    repeatable: true,
    required: false,
    sequence: 18,
  },
  {
    datatype: "DTM",
    id: "OBX-19",
    item: "1480",
    name: "Date/Time of the Analysis",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CWE",
    id: "OBX-20",
    item: "2179",
    name: "Observation Site",
    repeatable: true,
    required: false,
    sequence: 20,
    table: "HL70163",
  },
  {
    datatype: "EI",
    id: "OBX-21",
    item: "2180",
    name: "Observation Instance Identifier",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "CNE",
    id: "OBX-22",
    item: "2182",
    name: "Mood Code",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70725",
  },
  {
    datatype: "XON",
    id: "OBX-23",
    item: "2283",
    name: "Performing Organization Name",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "XAD",
    id: "OBX-24",
    item: "2284",
    name: "Performing Organization Address",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "XCN",
    id: "OBX-25",
    item: "2285",
    name: "Performing Organization Medical Director",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "ID",
    id: "OBX-26",
    item: "2313",
    maxLength: 10,
    name: "Patient Results Release Category",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70909",
  },
] as const;
