// Generated segment profile for OM2 (v2.7.1)

export const segmentId = "OM2";
export const fields = [
  {
    datatype: "NM",
    id: "OM2-1",
    item: "586",
    name: "Sequence Number - Test/Observation Master File",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "OM2-2",
    item: "627",
    name: "Units of Measure",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "NM",
    id: "OM2-3",
    item: "628",
    name: "Range of Decimal Precision",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "OM2-4",
    item: "629",
    name: "Corresponding SI Units of Measure",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TX",
    id: "OM2-5",
    item: "630",
    name: "SI Conversion Factor",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "RFR",
    id: "OM2-6",
    item: "631",
    name: "Reference (Normal) Range for Ordinal and Continuous Observations",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "RFR",
    id: "OM2-7",
    item: "632",
    name: "Critical Range for Ordinal and Continuous Observations",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "RFR",
    id: "OM2-8",
    item: "633",
    name: "Absolute Range for Ordinal and Continuous Observations",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DLT",
    id: "OM2-9",
    item: "634",
    name: "Delta Check Criteria",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "OM2-10",
    item: "635",
    name: "Minimum Meaningful Increments",
    repeatable: false,
    required: false,
    sequence: 10,
  },
] as const;
