// Generated segment profile for PRT (v2.7.1)

export const segmentId = "PRT";
export const fields = [
  {
    sequence: 1,
    id: "PRT-1",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 4,
    name: "Participation Instance ID",
    item: "2379",
  },
  {
    sequence: 2,
    id: "PRT-2",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70287",
    name: "Action Code",
    item: "816",
  },
  {
    sequence: 3,
    id: "PRT-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Action Reason",
    item: "2380",
  },
  {
    sequence: 4,
    id: "PRT-4",
    required: true,
    repeatable: false,
    datatype: "CWE",
    table: "HL70912",
    name: "Participation",
    item: "2381",
  },
  {
    sequence: 5,
    id: "PRT-5",
    required: false,
    repeatable: true,
    datatype: "XCN",
    name: "Participation Person",
    item: "2382",
  },
  {
    sequence: 6,
    id: "PRT-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Participation Person Provider Type",
    item: "2383",
  },
  {
    sequence: 7,
    id: "PRT-7",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70406",
    name: "Participant Organization Unit Type",
    item: "2384",
  },
  {
    sequence: 8,
    id: "PRT-8",
    required: false,
    repeatable: true,
    datatype: "XON",
    name: "Participation Organization",
    item: "2385",
  },
  {
    sequence: 9,
    id: "PRT-9",
    required: false,
    repeatable: true,
    datatype: "PL",
    name: "Participant Location",
    item: "2386",
  },
  {
    sequence: 10,
    id: "PRT-10",
    required: false,
    repeatable: true,
    datatype: "EI",
    name: "Participation Device",
    item: "2348",
  },
  {
    sequence: 11,
    id: "PRT-11",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Participation Begin Date/Time (arrival time)",
    item: "2387",
  },
  {
    sequence: 12,
    id: "PRT-12",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Participation End Date/Time (departure time)",
    item: "2388",
  },
  {
    sequence: 13,
    id: "PRT-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Participation Qualitative Duration",
    item: "2389",
  },
  {
    sequence: 14,
    id: "PRT-14",
    required: false,
    repeatable: true,
    datatype: "XAD",
    name: "Participation Address",
    item: "2390",
  },
  {
    sequence: 15,
    id: "PRT-15",
    required: false,
    repeatable: true,
    datatype: "XTN",
    name: "Participant Telecommunication Address",
    item: "2391",
  },
] as const;
