// Generated segment profile for PV2 (v2.7.1)

export const segmentId = "PV2";
export const fields = [
  {
    datatype: "PL",
    id: "PV2-1",
    item: "181",
    name: "Prior Pending Location",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "PV2-2",
    item: "182",
    name: "Accommodation Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70129",
  },
  {
    datatype: "CWE",
    id: "PV2-3",
    item: "183",
    name: "Admit Reason",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "PV2-4",
    item: "184",
    name: "Transfer Reason",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "PV2-5",
    item: "185",
    name: "Patient Valuables",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "PV2-6",
    item: "186",
    name: "Patient Valuables Location",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "PV2-7",
    item: "187",
    name: "Visit User Code",
    repeatable: true,
    required: false,
    sequence: 7,
    table: "HL70130",
  },
  {
    datatype: "DTM",
    id: "PV2-8",
    item: "188",
    name: "Expected Admit Date/Time",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DTM",
    id: "PV2-9",
    item: "189",
    name: "Expected Discharge Date/Time",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "PV2-10",
    item: "711",
    name: "Estimated Length of Inpatient Stay",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "PV2-11",
    item: "712",
    name: "Actual Length of Inpatient Stay",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "PV2-12",
    item: "713",
    name: "Visit Description",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "XCN",
    id: "PV2-13",
    item: "714",
    name: "Referral Source Code",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DT",
    id: "PV2-14",
    item: "715",
    name: "Previous Service Date",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ID",
    id: "PV2-15",
    item: "716",
    maxLength: 1,
    name: "Employment Illness Related Indicator",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "PV2-16",
    item: "717",
    name: "Purge Status Code",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70213",
  },
  {
    datatype: "DT",
    id: "PV2-17",
    item: "718",
    name: "Purge Status Date",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CWE",
    id: "PV2-18",
    item: "719",
    name: "Special Program Code",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70214",
  },
  {
    datatype: "ID",
    id: "PV2-19",
    item: "720",
    maxLength: 1,
    name: "Retention Indicator",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70136",
  },
  {
    datatype: "NM",
    id: "PV2-20",
    item: "721",
    name: "Expected Number of Insurance Plans",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CWE",
    id: "PV2-21",
    item: "722",
    name: "Visit Publicity Code",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70215",
  },
  {
    datatype: "ID",
    id: "PV2-22",
    item: "723",
    maxLength: 1,
    name: "Visit Protection Indicator",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70136",
  },
  {
    datatype: "XON",
    id: "PV2-23",
    item: "724",
    name: "Clinic Organization Name",
    repeatable: true,
    required: false,
    sequence: 23,
  },
  {
    datatype: "CWE",
    id: "PV2-24",
    item: "725",
    name: "Patient Status Code",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70216",
  },
  {
    datatype: "CWE",
    id: "PV2-25",
    item: "726",
    name: "Visit Priority Code",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70217",
  },
  {
    datatype: "DT",
    id: "PV2-26",
    item: "727",
    name: "Previous Treatment Date",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CWE",
    id: "PV2-27",
    item: "728",
    name: "Expected Discharge Disposition",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70112",
  },
  {
    datatype: "DT",
    id: "PV2-28",
    item: "729",
    name: "Signature on File Date",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "DT",
    id: "PV2-29",
    item: "730",
    name: "First Similar Illness Date",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CWE",
    id: "PV2-30",
    item: "731",
    name: "Patient Charge Adjustment Code",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70218",
  },
  {
    datatype: "CWE",
    id: "PV2-31",
    item: "732",
    name: "Recurring Service Code",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70219",
  },
  {
    datatype: "ID",
    id: "PV2-32",
    item: "733",
    maxLength: 1,
    name: "Billing Media Code",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70136",
  },
  {
    datatype: "DTM",
    id: "PV2-33",
    item: "734",
    name: "Expected Surgery Date and Time",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "ID",
    id: "PV2-34",
    item: "735",
    maxLength: 1,
    name: "Military Partnership Code",
    repeatable: false,
    required: false,
    sequence: 34,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "PV2-35",
    item: "736",
    maxLength: 1,
    name: "Military Non-Availability Code",
    repeatable: false,
    required: false,
    sequence: 35,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "PV2-36",
    item: "737",
    maxLength: 1,
    name: "Newborn Baby Indicator",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "PV2-37",
    item: "738",
    maxLength: 1,
    name: "Baby Detained Indicator",
    repeatable: false,
    required: false,
    sequence: 37,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "PV2-38",
    item: "1543",
    name: "Mode of Arrival Code",
    repeatable: false,
    required: false,
    sequence: 38,
    table: "HL70430",
  },
  {
    datatype: "CWE",
    id: "PV2-39",
    item: "1544",
    name: "Recreational Drug Use Code",
    repeatable: true,
    required: false,
    sequence: 39,
    table: "HL70431",
  },
  {
    datatype: "CWE",
    id: "PV2-40",
    item: "1545",
    name: "Admission Level of Care Code",
    repeatable: false,
    required: false,
    sequence: 40,
    table: "HL70432",
  },
  {
    datatype: "CWE",
    id: "PV2-41",
    item: "1546",
    name: "Precaution Code",
    repeatable: true,
    required: false,
    sequence: 41,
    table: "HL70433",
  },
  {
    datatype: "CWE",
    id: "PV2-42",
    item: "1547",
    name: "Patient Condition Code",
    repeatable: false,
    required: false,
    sequence: 42,
    table: "HL70434",
  },
  {
    datatype: "CWE",
    id: "PV2-43",
    item: "759",
    name: "Living Will Code",
    repeatable: false,
    required: false,
    sequence: 43,
    table: "HL70315",
  },
  {
    datatype: "CWE",
    id: "PV2-44",
    item: "760",
    name: "Organ Donor Code",
    repeatable: false,
    required: false,
    sequence: 44,
    table: "HL70316",
  },
  {
    datatype: "CWE",
    id: "PV2-45",
    item: "1548",
    name: "Advance Directive Code",
    repeatable: true,
    required: false,
    sequence: 45,
    table: "HL70435",
  },
  {
    datatype: "DT",
    id: "PV2-46",
    item: "1549",
    name: "Patient Status Effective Date",
    repeatable: false,
    required: false,
    sequence: 46,
  },
  {
    datatype: "DTM",
    id: "PV2-47",
    item: "1550",
    name: "Expected LOA Return Date/Time",
    repeatable: false,
    required: false,
    sequence: 47,
  },
  {
    datatype: "DTM",
    id: "PV2-48",
    item: "1841",
    name: "Expected Pre-admission Testing Date/Time",
    repeatable: false,
    required: false,
    sequence: 48,
  },
  {
    datatype: "CWE",
    id: "PV2-49",
    item: "1842",
    name: "Notify Clergy Code",
    repeatable: true,
    required: false,
    sequence: 49,
    table: "HL70534",
  },
  {
    datatype: "DT",
    id: "PV2-50",
    item: "2141",
    name: "Advance Directive Last Verified Date",
    repeatable: false,
    required: false,
    sequence: 50,
  },
] as const;
