// Generated segment profile for RXO (v2.7.1)

export const segmentId = "RXO";
export const fields = [
  {
    datatype: "CWE",
    id: "RXO-1",
    item: "292",
    name: "Requested Give Code",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "RXO-2",
    item: "293",
    name: "Requested Give Amount - Minimum",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "NM",
    id: "RXO-3",
    item: "294",
    name: "Requested Give Amount - Maximum",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "RXO-4",
    item: "295",
    name: "Requested Give Units",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "RXO-5",
    item: "296",
    name: "Requested Dosage Form",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "RXO-6",
    item: "297",
    name: "Provider's Pharmacy/Treatment Instructions",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "RXO-7",
    item: "298",
    name: "Provider's Administration Instructions",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "LA1",
    id: "RXO-8",
    item: "299",
    name: "Deliver-To Location",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ID",
    id: "RXO-9",
    item: "300",
    maxLength: 1,
    name: "Allow Substitutions",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70161",
  },
  {
    datatype: "CWE",
    id: "RXO-10",
    item: "301",
    name: "Requested Dispense Code",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "RXO-11",
    item: "302",
    name: "Requested Dispense Amount",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "RXO-12",
    item: "303",
    name: "Requested Dispense Units",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "RXO-13",
    item: "304",
    name: "Number Of Refills",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XCN",
    id: "RXO-14",
    item: "305",
    name: "Ordering Provider's DEA Number",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "XCN",
    id: "RXO-15",
    item: "306",
    name: "Pharmacist/Treatment Supplier's Verifier ID",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "RXO-16",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70136",
  },
  {
    datatype: "ST",
    id: "RXO-17",
    item: "308",
    name: "Requested Give Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "NM",
    id: "RXO-18",
    item: "1121",
    name: "Requested Give Strength",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CWE",
    id: "RXO-19",
    item: "1122",
    name: "Requested Give Strength Units",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CWE",
    id: "RXO-20",
    item: "1123",
    name: "Indication",
    repeatable: true,
    required: false,
    sequence: 20,
  },
  {
    datatype: "ST",
    id: "RXO-21",
    item: "1218",
    name: "Requested Give Rate Amount",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "CWE",
    id: "RXO-22",
    item: "1219",
    name: "Requested Give Rate Units",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "CQ",
    id: "RXO-23",
    item: "329",
    name: "Total Daily Dose",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "CWE",
    id: "RXO-24",
    item: "1476",
    name: "Supplementary Code",
    repeatable: true,
    required: false,
    sequence: 24,
  },
  {
    datatype: "NM",
    id: "RXO-25",
    item: "1666",
    name: "Requested Drug Strength Volume",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "CWE",
    id: "RXO-26",
    item: "1667",
    name: "Requested Drug Strength Volume Units",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "ID",
    id: "RXO-27",
    item: "1668",
    maxLength: 1,
    name: "Pharmacy Order Type",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70480",
  },
  {
    datatype: "NM",
    id: "RXO-28",
    item: "1669",
    name: "Dispensing Interval",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "EI",
    id: "RXO-29",
    item: "2149",
    name: "Medication Instance Identifier",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "EI",
    id: "RXO-30",
    item: "2150",
    name: "Segment Instance Identifier",
    repeatable: false,
    required: false,
    sequence: 30,
  },
  {
    datatype: "CNE",
    id: "RXO-31",
    item: "2151",
    name: "Mood Code",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70725",
  },
  {
    datatype: "CWE",
    id: "RXO-32",
    item: "1681",
    name: "Dispensing Pharmacy",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "XAD",
    id: "RXO-33",
    item: "1682",
    name: "Dispensing Pharmacy Address",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "PL",
    id: "RXO-34",
    item: "1683",
    name: "Deliver-to Patient Location",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "XAD",
    id: "RXO-35",
    item: "1684",
    name: "Deliver-to Address",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "XTN",
    id: "RXO-36",
    item: "2309",
    name: "Pharmacy Phone Number",
    repeatable: true,
    required: false,
    sequence: 36,
  },
] as const;
