// Generated segment profile for STF (v2.7.1)

export const segmentId = "STF";
export const fields = [
  {
    datatype: "CWE",
    id: "STF-1",
    item: "671",
    name: "Primary Key Value - STF",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CX",
    id: "STF-2",
    item: "672",
    name: "Staff Identifier List",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XPN",
    id: "STF-3",
    item: "673",
    name: "Staff Name",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "STF-4",
    item: "674",
    name: "Staff Type",
    repeatable: true,
    required: false,
    sequence: 4,
    table: "HL70182",
  },
  {
    datatype: "CWE",
    id: "STF-5",
    item: "111",
    name: "Administrative Sex",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70001",
  },
  {
    datatype: "DTM",
    id: "STF-6",
    item: "110",
    name: "Date/Time of Birth",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "STF-7",
    item: "675",
    maxLength: 1,
    name: "Active/Inactive Flag",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70183",
  },
  {
    datatype: "CWE",
    id: "STF-8",
    item: "676",
    name: "Department",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70184",
  },
  {
    datatype: "CWE",
    id: "STF-9",
    item: "677",
    name: "Hospital Service - STF",
    repeatable: true,
    required: false,
    sequence: 9,
    table: "HL70069",
  },
  {
    datatype: "XTN",
    id: "STF-10",
    item: "678",
    name: "Phone",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XAD",
    id: "STF-11",
    item: "679",
    name: "Office/Home Address/Birthplace",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "DIN",
    id: "STF-12",
    item: "680",
    name: "Institution Activation Date",
    repeatable: true,
    required: false,
    sequence: 12,
    table: "HL70537",
  },
  {
    datatype: "DIN",
    id: "STF-13",
    item: "681",
    name: "Institution Inactivation Date",
    repeatable: true,
    required: false,
    sequence: 13,
    table: "HL70537",
  },
  {
    datatype: "CWE",
    id: "STF-14",
    item: "682",
    name: "Backup Person ID",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "STF-15",
    item: "683",
    name: "E-Mail Address",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CWE",
    id: "STF-16",
    item: "684",
    name: "Preferred Method of Contact",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70185",
  },
  {
    datatype: "CWE",
    id: "STF-17",
    item: "119",
    name: "Marital Status",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70002",
  },
  {
    datatype: "ST",
    id: "STF-18",
    item: "785",
    name: "Job Title",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "JCC",
    id: "STF-19",
    item: "786",
    name: "Job Code/Class",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CWE",
    id: "STF-20",
    item: "1276",
    name: "Employment Status Code",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70066",
  },
  {
    datatype: "ID",
    id: "STF-21",
    item: "1275",
    maxLength: 1,
    name: "Additional Insured on Auto",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70136",
  },
  {
    datatype: "DLN",
    id: "STF-22",
    item: "1302",
    name: "Driver's License Number - Staff",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ID",
    id: "STF-23",
    item: "1229",
    maxLength: 1,
    name: "Copy Auto Ins",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70136",
  },
  {
    datatype: "DT",
    id: "STF-24",
    item: "1232",
    name: "Auto Ins Expires",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "DT",
    id: "STF-25",
    item: "1298",
    name: "Date Last DMV Review",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "DT",
    id: "STF-26",
    item: "1234",
    name: "Date Next DMV Review",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CWE",
    id: "STF-27",
    item: "113",
    name: "Race",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70005",
  },
  {
    datatype: "CWE",
    id: "STF-28",
    item: "125",
    name: "Ethnic Group",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70189",
  },
  {
    datatype: "ID",
    id: "STF-29",
    item: "1596",
    maxLength: 1,
    name: "Re-activation Approval Indicator",
    repeatable: false,
    required: false,
    sequence: 29,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "STF-30",
    item: "129",
    name: "Citizenship",
    repeatable: true,
    required: false,
    sequence: 30,
    table: "HL70171",
  },
  {
    datatype: "DTM",
    id: "STF-31",
    item: "1886",
    name: "Date/Time of Death",
    repeatable: false,
    required: false,
    sequence: 31,
  },
  {
    datatype: "ID",
    id: "STF-32",
    item: "1887",
    maxLength: 1,
    name: "Death Indicator",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "STF-33",
    item: "1888",
    name: "Institution Relationship Type Code",
    repeatable: false,
    required: false,
    sequence: 33,
    table: "HL70538",
  },
  {
    datatype: "DR",
    id: "STF-34",
    item: "1889",
    name: "Institution Relationship Period",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "DT",
    id: "STF-35",
    item: "1890",
    name: "Expected Return Date",
    repeatable: false,
    required: false,
    sequence: 35,
  },
  {
    datatype: "CWE",
    id: "STF-36",
    item: "1891",
    name: "Cost Center Code",
    repeatable: true,
    required: false,
    sequence: 36,
    table: "HL70539",
  },
  {
    datatype: "ID",
    id: "STF-37",
    item: "1892",
    maxLength: 1,
    name: "Generic Classification Indicator",
    repeatable: false,
    required: false,
    sequence: 37,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "STF-38",
    item: "1893",
    name: "Inactive Reason Code",
    repeatable: false,
    required: false,
    sequence: 38,
    table: "HL70540",
  },
  {
    datatype: "CWE",
    id: "STF-39",
    item: "2184",
    name: "Generic resource type or category",
    repeatable: true,
    required: false,
    sequence: 39,
    table: "HL70771",
  },
  {
    datatype: "CWE",
    id: "STF-40",
    item: "120",
    name: "Religion",
    repeatable: false,
    required: false,
    sequence: 40,
    table: "HL70006",
  },
  {
    datatype: "ED",
    id: "STF-41",
    item: "1861",
    name: "Signature",
    repeatable: false,
    required: false,
    sequence: 41,
  },
] as const;
