// Generated segment profile for DG1 (v2.2)

export const segmentId = "DG1";
export const fields = [
  {
    sequence: 1,
    id: "DG1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - diagnosis",
    item: "375",
  },
  {
    sequence: 2,
    id: "DG1-2",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70053",
    name: "Diagnosis coding method",
    item: "376",
  },
  {
    sequence: 3,
    id: "DG1-3",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70051",
    name: "Diagnosis code",
    item: "377",
  },
  {
    sequence: 4,
    id: "DG1-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Diagnosis description",
    item: "378",
  },
  {
    sequence: 5,
    id: "DG1-5",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Diagnosis date / time",
    item: "379",
  },
  {
    sequence: 6,
    id: "DG1-6",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70052",
    name: "Diagnosis / DRG type",
    item: "380",
  },
  {
    sequence: 7,
    id: "DG1-7",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70118",
    name: "Major diagnostic category",
    item: "381",
  },
  {
    sequence: 8,
    id: "DG1-8",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 4,
    table: "HL70055",
    name: "Diagnostic related group",
    item: "382",
  },
  {
    sequence: 9,
    id: "DG1-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    name: "DRG approval indicator",
    item: "383",
  },
  {
    sequence: 10,
    id: "DG1-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70056",
    name: "DRG grouper review code",
    item: "384",
  },
  {
    sequence: 11,
    id: "DG1-11",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 60,
    table: "HL70083",
    name: "Outlier type",
    item: "385",
  },
  {
    sequence: 12,
    id: "DG1-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    name: "Outlier days",
    item: "386",
  },
  {
    sequence: 13,
    id: "DG1-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Outlier cost",
    item: "387",
  },
  {
    sequence: 14,
    id: "DG1-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    name: "Grouper version and type",
    item: "388",
  },
  {
    sequence: 15,
    id: "DG1-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 2,
    name: "Diagnosis / DRG priority",
    item: "389",
  },
  {
    sequence: 16,
    id: "DG1-16",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Diagnosing clinician",
    item: "390",
  },
] as const;
