// Generated segment profile for FT1 (v2.2)

export const segmentId = "FT1";
export const fields = [
  {
    sequence: 1,
    id: "FT1-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - financial transaction",
    item: "355",
  },
  {
    sequence: 2,
    id: "FT1-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 12,
    name: "Transaction ID",
    item: "356",
  },
  {
    sequence: 3,
    id: "FT1-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 10,
    name: "Transaction batch ID",
    item: "357",
  },
  {
    sequence: 4,
    id: "FT1-4",
    required: true,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Transaction date",
    item: "358",
  },
  {
    sequence: 5,
    id: "FT1-5",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Transaction posting date",
    item: "359",
  },
  {
    sequence: 6,
    id: "FT1-6",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70017",
    name: "Transaction type",
    item: "360",
  },
  {
    sequence: 7,
    id: "FT1-7",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 20,
    table: "HL70132",
    name: "Transaction code",
    item: "361",
  },
  {
    sequence: 8,
    id: "FT1-8",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Transaction description",
    item: "362",
  },
  {
    sequence: 9,
    id: "FT1-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Transaction description - alternate",
    item: "363",
  },
  {
    sequence: 10,
    id: "FT1-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Transaction quantity",
    item: "364",
  },
  {
    sequence: 11,
    id: "FT1-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Transaction amount - extended",
    item: "365",
  },
  {
    sequence: 12,
    id: "FT1-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Transaction amount - unit",
    item: "366",
  },
  {
    sequence: 13,
    id: "FT1-13",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70049",
    name: "Department code",
    item: "367",
  },
  {
    sequence: 14,
    id: "FT1-14",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 8,
    table: "HL70072",
    name: "Insurance plan ID",
    item: "368",
  },
  {
    sequence: 15,
    id: "FT1-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Insurance amount",
    item: "369",
  },
  {
    sequence: 16,
    id: "FT1-16",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 12,
    table: "HL70079",
    name: "Assigned Patient Location",
    item: "133",
  },
  {
    sequence: 17,
    id: "FT1-17",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70024",
    name: "Fee schedule",
    item: "370",
  },
  {
    sequence: 18,
    id: "FT1-18",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70018",
    name: "Patient type",
    item: "148",
  },
  {
    sequence: 19,
    id: "FT1-19",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 8,
    table: "HL70051",
    name: "Diagnosis code",
    item: "371",
  },
  {
    sequence: 20,
    id: "FT1-20",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    table: "HL70084",
    name: "Performed by code",
    item: "372",
  },
  {
    sequence: 21,
    id: "FT1-21",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Ordered by code",
    item: "373",
  },
  {
    sequence: 22,
    id: "FT1-22",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Unit cost",
    item: "374",
  },
  {
    sequence: 23,
    id: "FT1-23",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 75,
    name: "Filler Order Number",
    item: "217",
  },
] as const;
