// Generated segment profile for NK1 (v2.2)

export const segmentId = "NK1";
export const fields = [
  {
    sequence: 1,
    id: "NK1-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - Next of Kin",
    item: "190",
  },
  {
    sequence: 2,
    id: "NK1-2",
    required: false,
    repeatable: false,
    datatype: "PN",
    maxLength: 48,
    name: "Name",
    item: "191",
  },
  {
    sequence: 3,
    id: "NK1-3",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70063",
    name: "Relationship",
    item: "192",
  },
  {
    sequence: 4,
    id: "NK1-4",
    required: false,
    repeatable: false,
    datatype: "AD",
    maxLength: 106,
    name: "Address",
    item: "193",
  },
  {
    sequence: 5,
    id: "NK1-5",
    required: false,
    repeatable: true,
    datatype: "TN",
    maxLength: 40,
    name: "Phone Number",
    item: "194",
  },
  {
    sequence: 6,
    id: "NK1-6",
    required: false,
    repeatable: false,
    datatype: "TN",
    maxLength: 40,
    name: "Business Phone Number",
    item: "195",
  },
  {
    sequence: 7,
    id: "NK1-7",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70131",
    name: "Contact Role",
    item: "196",
  },
  {
    sequence: 8,
    id: "NK1-8",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Start Date",
    item: "197",
  },
  {
    sequence: 9,
    id: "NK1-9",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "End Date",
    item: "198",
  },
  {
    sequence: 10,
    id: "NK1-10",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Next of Kin",
    item: "199",
  },
  {
    sequence: 11,
    id: "NK1-11",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 60,
    name: "Next of kin job code / class",
    item: "200",
  },
  {
    sequence: 12,
    id: "NK1-12",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Next of Kin Employee Number",
    item: "201",
  },
  {
    sequence: 13,
    id: "NK1-13",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Organization Name",
    item: "202",
  },
] as const;
