// Generated segment profile for OBX (v2.2)

export const segmentId = "OBX";
export const fields = [
  {
    sequence: 1,
    id: "OBX-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - Observational Simple",
    item: "569",
  },
  {
    sequence: 2,
    id: "OBX-2",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70125",
    name: "Value Type",
    item: "570",
  },
  {
    sequence: 3,
    id: "OBX-3",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 80,
    name: "Observation Identifier",
    item: "571",
  },
  {
    sequence: 4,
    id: "OBX-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Observation Sub-ID",
    item: "572",
  },
  {
    sequence: 5,
    id: "OBX-5",
    required: false,
    repeatable: false,
    datatype: "*",
    maxLength: 65_536,
    name: "Observation Value",
    item: "573",
  },
  {
    sequence: 6,
    id: "OBX-6",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Units",
    item: "574",
  },
  {
    sequence: 7,
    id: "OBX-7",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "References Range",
    item: "575",
  },
  {
    sequence: 8,
    id: "OBX-8",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 10,
    table: "HL70078",
    name: "Abnormal Flags",
    item: "576",
  },
  {
    sequence: 9,
    id: "OBX-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "Probability",
    item: "577",
  },
  {
    sequence: 10,
    id: "OBX-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 5,
    table: "HL70080",
    name: "Nature of Abnormal Test",
    item: "578",
  },
  {
    sequence: 11,
    id: "OBX-11",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70085",
    name: "Observation result status",
    item: "579",
  },
  {
    sequence: 12,
    id: "OBX-12",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective date last observation normal values",
    item: "580",
  },
  {
    sequence: 13,
    id: "OBX-13",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "User Defined Access Checks",
    item: "581",
  },
  {
    sequence: 14,
    id: "OBX-14",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Date / time of the observation",
    item: "582",
  },
  {
    sequence: 15,
    id: "OBX-15",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Producer&apos;s ID",
    item: "583",
  },
  {
    sequence: 16,
    id: "OBX-16",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Responsible Observer",
    item: "584",
  },
] as const;
