// Generated segment profile for PRA (v2.2)

export const segmentId = "PRA";
export const fields = [
  {
    sequence: 1,
    id: "PRA-1",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "PRA - primary key value",
    item: "685",
  },
  {
    sequence: 2,
    id: "PRA-2",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 60,
    name: "Practitioner group",
    item: "686",
  },
  {
    sequence: 3,
    id: "PRA-3",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 3,
    table: "HL70186",
    name: "Practitioner Category",
    item: "687",
  },
  {
    sequence: 4,
    id: "PRA-4",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70187",
    name: "Provider Billing",
    item: "688",
  },
  {
    sequence: 5,
    id: "PRA-5",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 100,
    name: "Specialty",
    item: "689",
  },
  {
    sequence: 6,
    id: "PRA-6",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 100,
    name: "Practitioner ID Numbers",
    item: "690",
  },
  {
    sequence: 7,
    id: "PRA-7",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 20,
    name: "Privileges",
    item: "691",
  },
] as const;
