// Generated segment profile for PV2 (v2.2)

export const segmentId = "PV2";
export const fields = [
  {
    sequence: 1,
    id: "PV2-1",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 12,
    name: "Prior Pending Location",
    item: "181",
  },
  {
    sequence: 2,
    id: "PV2-2",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    table: "HL70129",
    name: "Accommodation Code",
    item: "182",
  },
  {
    sequence: 3,
    id: "PV2-3",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Admit Reason",
    item: "183",
  },
  {
    sequence: 4,
    id: "PV2-4",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Transfer Reason",
    item: "184",
  },
  {
    sequence: 5,
    id: "PV2-5",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 25,
    name: "Patient Valuables",
    item: "185",
  },
  {
    sequence: 6,
    id: "PV2-6",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 25,
    name: "Patient Valuables Location",
    item: "186",
  },
  {
    sequence: 7,
    id: "PV2-7",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70130",
    name: "Visit User Code",
    item: "187",
  },
  {
    sequence: 8,
    id: "PV2-8",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Expected Admit Date",
    item: "188",
  },
  {
    sequence: 9,
    id: "PV2-9",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Expected Discharge Date",
    item: "189",
  },
] as const;
