// Generated segment profile for RXO (v2.2)

export const segmentId = "RXO";
export const fields = [
  {
    sequence: 1,
    id: "RXO-1",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 100,
    name: "Requested Give Code",
    item: "292",
  },
  {
    sequence: 2,
    id: "RXO-2",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Requested Give Amount - Minimum",
    item: "293",
  },
  {
    sequence: 3,
    id: "RXO-3",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Requested Give Amount - Maximum",
    item: "294",
  },
  {
    sequence: 4,
    id: "RXO-4",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Requested Give Units",
    item: "295",
  },
  {
    sequence: 5,
    id: "RXO-5",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Requested Dosage Form",
    item: "296",
  },
  {
    sequence: 6,
    id: "RXO-6",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Provider&apos;s Pharmacy Instructions",
    item: "297",
  },
  {
    sequence: 7,
    id: "RXO-7",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 200,
    name: "Provider&apos;s Administration Instructions",
    item: "298",
  },
  {
    sequence: 8,
    id: "RXO-8",
    required: false,
    repeatable: false,
    datatype: "CM",
    maxLength: 12,
    name: "Deliver-to location",
    item: "299",
  },
  {
    sequence: 9,
    id: "RXO-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70161",
    name: "Allow Substitutions",
    item: "300",
  },
  {
    sequence: 10,
    id: "RXO-10",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 100,
    name: "Requested Dispense Code",
    item: "301",
  },
  {
    sequence: 11,
    id: "RXO-11",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Requested Dispense Amount",
    item: "302",
  },
  {
    sequence: 12,
    id: "RXO-12",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 60,
    name: "Requested Dispense Units",
    item: "303",
  },
  {
    sequence: 13,
    id: "RXO-13",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 3,
    name: "Number of Refills",
    item: "304",
  },
  {
    sequence: 14,
    id: "RXO-14",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Ordering Provider&apos;s DEA Number",
    item: "305",
  },
  {
    sequence: 15,
    id: "RXO-15",
    required: false,
    repeatable: false,
    datatype: "CN",
    maxLength: 60,
    name: "Pharmacist Verifier ID",
    item: "306",
  },
  {
    sequence: 16,
    id: "RXO-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    name: "Needs Human Review",
    item: "307",
  },
  {
    sequence: 17,
    id: "RXO-17",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 20,
    name: "Requested Give Per (Time Unit)",
    item: "308",
  },
] as const;
