// Generated segment profile for UB2 (v2.2)

export const segmentId = "UB2";
export const fields = [
  {
    sequence: 1,
    id: "UB2-1",
    required: false,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - UB92",
    item: "553",
  },
  {
    sequence: 2,
    id: "UB2-2",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 3,
    name: "Co-insurance days (9)",
    item: "554",
  },
  {
    sequence: 3,
    id: "UB2-3",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 2,
    table: "HL70043",
    name: "Condition code (24-30)",
    item: "555",
  },
  {
    sequence: 4,
    id: "UB2-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 3,
    name: "Covered days (7)",
    item: "556",
  },
  {
    sequence: 5,
    id: "UB2-5",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 4,
    name: "Non-covered days (8)",
    item: "557",
  },
  {
    sequence: 6,
    id: "UB2-6",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 11,
    name: "Value amount and code (39-41)",
    item: "558",
  },
  {
    sequence: 7,
    id: "UB2-7",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 11,
    name: "Occurrence code and date (32-35)",
    item: "559",
  },
  {
    sequence: 8,
    id: "UB2-8",
    required: false,
    repeatable: true,
    datatype: "CM",
    maxLength: 28,
    name: "Occurrence span code / dates (36)",
    item: "560",
  },
  {
    sequence: 9,
    id: "UB2-9",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 29,
    name: "UB92 locator 2 (state)",
    item: "561",
  },
  {
    sequence: 10,
    id: "UB2-10",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 12,
    name: "UB92 locator 11 (state)",
    item: "562",
  },
  {
    sequence: 11,
    id: "UB2-11",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 5,
    name: "UB92 locator 31 (national)",
    item: "563",
  },
  {
    sequence: 12,
    id: "UB2-12",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 23,
    name: "Document control number (37)",
    item: "564",
  },
  {
    sequence: 13,
    id: "UB2-13",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 4,
    name: "UB92 locator 49 (national)",
    item: "565",
  },
  {
    sequence: 14,
    id: "UB2-14",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 14,
    name: "UB92 locator 56 (state)",
    item: "566",
  },
  {
    sequence: 15,
    id: "UB2-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 27,
    name: "UB92 locator 57 (national)",
    item: "567",
  },
  {
    sequence: 16,
    id: "UB2-16",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 2,
    name: "UB92 Locator 78 (state)",
    item: "568",
  },
] as const;
