// Generated segment profile for AIP (v2.4)

export const segmentId = "AIP";
export const fields = [
  {
    datatype: "SI",
    id: "AIP-1",
    item: "906",
    maxLength: 4,
    name: "Set ID - AIP",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "AIP-2",
    item: "763",
    maxLength: 3,
    name: "Segment Action Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "XCN",
    id: "AIP-3",
    item: "913",
    maxLength: 250,
    name: "Personnel Resource ID",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "AIP-4",
    item: "907",
    maxLength: 250,
    name: "Resource Role",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "AIP-5",
    item: "899",
    maxLength: 250,
    name: "Resource Group",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TS",
    id: "AIP-6",
    item: "1202",
    maxLength: 26,
    name: "Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "NM",
    id: "AIP-7",
    item: "891",
    maxLength: 20,
    name: "Start Date/Time Offset",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CE",
    id: "AIP-8",
    item: "892",
    maxLength: 250,
    name: "Start Date/Time Offset Units",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "NM",
    id: "AIP-9",
    item: "893",
    maxLength: 20,
    name: "Duration",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CE",
    id: "AIP-10",
    item: "894",
    maxLength: 250,
    name: "Duration Units",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "IS",
    id: "AIP-11",
    item: "895",
    maxLength: 10,
    name: "Allow Substitution Code",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70279",
  },
  {
    datatype: "CE",
    id: "AIP-12",
    item: "889",
    maxLength: 250,
    name: "Filler Status Code",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70278",
  },
] as const;
