// Generated segment profile for CNS (v2.4)

export const segmentId = "CNS";
export const fields = [
  {
    datatype: "NM",
    id: "CNS-1",
    item: "1402",
    maxLength: 20,
    name: "Starting Notification Reference Number",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "CNS-2",
    item: "1403",
    maxLength: 20,
    name: "Ending Notification Reference Number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TS",
    id: "CNS-3",
    item: "1404",
    maxLength: 26,
    name: "Starting Notification Date/Time",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "CNS-4",
    item: "1405",
    maxLength: 26,
    name: "Ending Notification Date/Time",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "CNS-5",
    item: "1406",
    maxLength: 250,
    name: "Starting Notification Code",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "CNS-6",
    item: "1407",
    maxLength: 250,
    name: "Ending Notification Code",
    repeatable: false,
    required: false,
    sequence: 6,
  },
] as const;
