// Generated segment profile for IN1 (v2.4)

export const segmentId = "IN1";
export const fields = [
  {
    datatype: "SI",
    id: "IN1-1",
    item: "426",
    maxLength: 4,
    name: "Set ID - IN1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "IN1-2",
    item: "368",
    maxLength: 250,
    name: "Insurance Plan ID",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70072",
  },
  {
    datatype: "CX",
    id: "IN1-3",
    item: "428",
    maxLength: 250,
    name: "Insurance Company ID",
    repeatable: true,
    required: true,
    sequence: 3,
  },
  {
    datatype: "XON",
    id: "IN1-4",
    item: "429",
    maxLength: 250,
    name: "Insurance Company Name",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XAD",
    id: "IN1-5",
    item: "430",
    maxLength: 250,
    name: "Insurance Company Address",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "XPN",
    id: "IN1-6",
    item: "431",
    maxLength: 250,
    name: "Insurance Co Contact Person",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XTN",
    id: "IN1-7",
    item: "432",
    maxLength: 250,
    name: "Insurance Co Phone Number",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "IN1-8",
    item: "433",
    maxLength: 12,
    name: "Group Number",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "XON",
    id: "IN1-9",
    item: "434",
    maxLength: 250,
    name: "Group Name",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CX",
    id: "IN1-10",
    item: "435",
    maxLength: 250,
    name: "Insured&apos;s Group Emp ID",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XON",
    id: "IN1-11",
    item: "436",
    maxLength: 250,
    name: "Insured&apos;s Group Emp Name",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "DT",
    id: "IN1-12",
    item: "437",
    maxLength: 8,
    name: "Plan Effective Date",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DT",
    id: "IN1-13",
    item: "438",
    maxLength: 8,
    name: "Plan Expiration Date",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "AUI",
    id: "IN1-14",
    item: "439",
    maxLength: 250,
    name: "Authorization Information",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "IS",
    id: "IN1-15",
    item: "440",
    maxLength: 3,
    name: "Plan Type",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70086",
  },
  {
    datatype: "XPN",
    id: "IN1-16",
    item: "441",
    maxLength: 250,
    name: "Name Of Insured",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CE",
    id: "IN1-17",
    item: "442",
    maxLength: 250,
    name: "Insured&apos;s Relationship To Patient",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70063",
  },
  {
    datatype: "TS",
    id: "IN1-18",
    item: "443",
    maxLength: 26,
    name: "Insured&apos;s Date Of Birth",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "XAD",
    id: "IN1-19",
    item: "444",
    maxLength: 250,
    name: "Insured&apos;s Address",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "IS",
    id: "IN1-20",
    item: "445",
    maxLength: 2,
    name: "Assignment Of Benefits",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70135",
  },
  {
    datatype: "IS",
    id: "IN1-21",
    item: "446",
    maxLength: 2,
    name: "Coordination Of Benefits",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70173",
  },
  {
    datatype: "ST",
    id: "IN1-22",
    item: "447",
    maxLength: 2,
    name: "Coord Of Ben. Priority",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ID",
    id: "IN1-23",
    item: "448",
    maxLength: 1,
    name: "Notice Of Admission Flag",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70136",
  },
  {
    datatype: "DT",
    id: "IN1-24",
    item: "449",
    maxLength: 8,
    name: "Notice Of Admission Date",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ID",
    id: "IN1-25",
    item: "450",
    maxLength: 1,
    name: "Report Of Eligibility Flag",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70136",
  },
  {
    datatype: "DT",
    id: "IN1-26",
    item: "451",
    maxLength: 8,
    name: "Report Of Eligibility Date",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "IS",
    id: "IN1-27",
    item: "452",
    maxLength: 2,
    name: "Release Information Code",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70093",
  },
  {
    datatype: "ST",
    id: "IN1-28",
    item: "453",
    maxLength: 15,
    name: "Pre-Admit Cert (PAC)",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "TS",
    id: "IN1-29",
    item: "454",
    maxLength: 26,
    name: "Verification Date/Time",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "XCN",
    id: "IN1-30",
    item: "455",
    maxLength: 250,
    name: "Verification By",
    repeatable: true,
    required: false,
    sequence: 30,
  },
  {
    datatype: "IS",
    id: "IN1-31",
    item: "456",
    maxLength: 2,
    name: "Type Of Agreement Code",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70098",
  },
  {
    datatype: "IS",
    id: "IN1-32",
    item: "457",
    maxLength: 2,
    name: "Billing Status",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70022",
  },
  {
    datatype: "NM",
    id: "IN1-33",
    item: "458",
    maxLength: 4,
    name: "Lifetime Reserve Days",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "NM",
    id: "IN1-34",
    item: "459",
    maxLength: 4,
    name: "Delay Before L.R. Day",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "IS",
    id: "IN1-35",
    item: "460",
    maxLength: 8,
    name: "Company Plan Code",
    repeatable: false,
    required: false,
    sequence: 35,
    table: "HL70042",
  },
  {
    datatype: "ST",
    id: "IN1-36",
    item: "461",
    maxLength: 15,
    name: "Policy Number",
    repeatable: false,
    required: false,
    sequence: 36,
  },
  {
    datatype: "CP",
    id: "IN1-37",
    item: "462",
    maxLength: 12,
    name: "Policy Deductible",
    repeatable: false,
    required: false,
    sequence: 37,
  },
  {
    datatype: "CP",
    id: "IN1-38",
    item: "463",
    maxLength: 12,
    name: "Policy Limit - Amount",
    repeatable: false,
    required: false,
    sequence: 38,
  },
  {
    datatype: "NM",
    id: "IN1-39",
    item: "464",
    maxLength: 4,
    name: "Policy Limit - Days",
    repeatable: false,
    required: false,
    sequence: 39,
  },
  {
    datatype: "CP",
    id: "IN1-40",
    item: "465",
    maxLength: 12,
    name: "Room Rate - Semi-Private",
    repeatable: false,
    required: false,
    sequence: 40,
  },
  {
    datatype: "CP",
    id: "IN1-41",
    item: "466",
    maxLength: 12,
    name: "Room Rate - Private",
    repeatable: false,
    required: false,
    sequence: 41,
  },
  {
    datatype: "CE",
    id: "IN1-42",
    item: "467",
    maxLength: 250,
    name: "Insured&apos;s Employment Status",
    repeatable: false,
    required: false,
    sequence: 42,
    table: "HL70066",
  },
  {
    datatype: "IS",
    id: "IN1-43",
    item: "468",
    maxLength: 1,
    name: "Insured&apos;s Administrative Sex",
    repeatable: false,
    required: false,
    sequence: 43,
    table: "HL70001",
  },
  {
    datatype: "XAD",
    id: "IN1-44",
    item: "469",
    maxLength: 250,
    name: "Insured&apos;s Employer&apos;s Address",
    repeatable: true,
    required: false,
    sequence: 44,
  },
  {
    datatype: "ST",
    id: "IN1-45",
    item: "470",
    maxLength: 2,
    name: "Verification Status",
    repeatable: false,
    required: false,
    sequence: 45,
  },
  {
    datatype: "IS",
    id: "IN1-46",
    item: "471",
    maxLength: 8,
    name: "Prior Insurance Plan ID",
    repeatable: false,
    required: false,
    sequence: 46,
    table: "HL70072",
  },
  {
    datatype: "IS",
    id: "IN1-47",
    item: "1227",
    maxLength: 3,
    name: "Coverage Type",
    repeatable: false,
    required: false,
    sequence: 47,
    table: "HL70309",
  },
  {
    datatype: "IS",
    id: "IN1-48",
    item: "753",
    maxLength: 2,
    name: "Handicap",
    repeatable: false,
    required: false,
    sequence: 48,
    table: "HL70295",
  },
  {
    datatype: "CX",
    id: "IN1-49",
    item: "1230",
    maxLength: 250,
    name: "Insured&apos;s ID Number",
    repeatable: true,
    required: false,
    sequence: 49,
  },
] as const;
