// Generated segment profile for IN3 (v2.4)

export const segmentId = "IN3";
export const fields = [
  {
    sequence: 1,
    id: "IN3-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - IN3",
    item: "502",
  },
  {
    sequence: 2,
    id: "IN3-2",
    required: false,
    repeatable: false,
    datatype: "CX",
    maxLength: 250,
    name: "Certification Number",
    item: "503",
  },
  {
    sequence: 3,
    id: "IN3-3",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    name: "Certified By",
    item: "504",
  },
  {
    sequence: 4,
    id: "IN3-4",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Certification Required",
    item: "505",
  },
  {
    sequence: 5,
    id: "IN3-5",
    required: false,
    repeatable: false,
    datatype: "MOP",
    maxLength: 10,
    table: "HL70148",
    name: "Penalty",
    item: "506",
  },
  {
    sequence: 6,
    id: "IN3-6",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Certification Date/Time",
    item: "507",
  },
  {
    sequence: 7,
    id: "IN3-7",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Certification Modify Date/Time",
    item: "508",
  },
  {
    sequence: 8,
    id: "IN3-8",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    name: "Operator",
    item: "509",
  },
  {
    sequence: 9,
    id: "IN3-9",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Certification Begin Date",
    item: "510",
  },
  {
    sequence: 10,
    id: "IN3-10",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Certification End Date",
    item: "511",
  },
  {
    sequence: 11,
    id: "IN3-11",
    required: false,
    repeatable: false,
    datatype: "DTN",
    maxLength: 3,
    table: "HL70149",
    name: "Days",
    item: "512",
  },
  {
    sequence: 12,
    id: "IN3-12",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70233",
    name: "Non-Concur Code/Description",
    item: "513",
  },
  {
    sequence: 13,
    id: "IN3-13",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Non-Concur Effective Date/Time",
    item: "514",
  },
  {
    sequence: 14,
    id: "IN3-14",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70010",
    name: "Physician Reviewer",
    item: "515",
  },
  {
    sequence: 15,
    id: "IN3-15",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 48,
    name: "Certification Contact",
    item: "516",
  },
  {
    sequence: 16,
    id: "IN3-16",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 250,
    name: "Certification Contact Phone Number",
    item: "517",
  },
  {
    sequence: 17,
    id: "IN3-17",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70345",
    name: "Appeal Reason",
    item: "518",
  },
  {
    sequence: 18,
    id: "IN3-18",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    table: "HL70346",
    name: "Certification Agency",
    item: "519",
  },
  {
    sequence: 19,
    id: "IN3-19",
    required: false,
    repeatable: true,
    datatype: "XTN",
    maxLength: 250,
    name: "Certification Agency Phone Number",
    item: "520",
  },
  {
    sequence: 20,
    id: "IN3-20",
    required: false,
    repeatable: true,
    datatype: "PCF",
    maxLength: 40,
    table: "HL70150",
    name: "Pre-Certification Req/Window",
    item: "521",
  },
  {
    sequence: 21,
    id: "IN3-21",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 48,
    name: "Case Manager",
    item: "522",
  },
  {
    sequence: 22,
    id: "IN3-22",
    required: false,
    repeatable: false,
    datatype: "DT",
    maxLength: 8,
    name: "Second Opinion Date",
    item: "523",
  },
  {
    sequence: 23,
    id: "IN3-23",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70151",
    name: "Second Opinion Status",
    item: "524",
  },
  {
    sequence: 24,
    id: "IN3-24",
    required: false,
    repeatable: true,
    datatype: "IS",
    maxLength: 1,
    table: "HL70152",
    name: "Second Opinion Documentation Received",
    item: "525",
  },
  {
    sequence: 25,
    id: "IN3-25",
    required: false,
    repeatable: true,
    datatype: "XCN",
    maxLength: 250,
    table: "HL70010",
    name: "Second Opinion Physician",
    item: "526",
  },
] as const;
