// Generated segment profile for PRB (v2.4)

export const segmentId = "PRB";
export const fields = [
  {
    datatype: "ID",
    id: "PRB-1",
    item: "816",
    maxLength: 2,
    name: "Action Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70287",
  },
  {
    datatype: "TS",
    id: "PRB-2",
    item: "817",
    maxLength: 26,
    name: "Action Date/Time",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "CE",
    id: "PRB-3",
    item: "838",
    maxLength: 250,
    name: "Problem ID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "PRB-4",
    item: "839",
    maxLength: 60,
    name: "Problem Instance ID",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "EI",
    id: "PRB-5",
    item: "820",
    maxLength: 60,
    name: "Episode of Care ID",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "PRB-6",
    item: "841",
    maxLength: 60,
    name: "Problem List Priority",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "PRB-7",
    item: "842",
    maxLength: 26,
    name: "Problem Established Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "TS",
    id: "PRB-8",
    item: "843",
    maxLength: 26,
    name: "Anticipated Problem Resolution Date/Time",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "TS",
    id: "PRB-9",
    item: "844",
    maxLength: 26,
    name: "Actual Problem Resolution Date/Time",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CE",
    id: "PRB-10",
    item: "845",
    maxLength: 250,
    name: "Problem Classification",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CE",
    id: "PRB-11",
    item: "846",
    maxLength: 250,
    name: "Problem Management Discipline",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CE",
    id: "PRB-12",
    item: "847",
    maxLength: 250,
    name: "Problem Persistence",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CE",
    id: "PRB-13",
    item: "848",
    maxLength: 250,
    name: "Problem Confirmation Status",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CE",
    id: "PRB-14",
    item: "849",
    maxLength: 250,
    name: "Problem Life Cycle Status",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "TS",
    id: "PRB-15",
    item: "850",
    maxLength: 26,
    name: "Problem Life Cycle Status Date/Time",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "TS",
    id: "PRB-16",
    item: "851",
    maxLength: 26,
    name: "Problem Date of Onset",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ST",
    id: "PRB-17",
    item: "852",
    maxLength: 80,
    name: "Problem Onset Text",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CE",
    id: "PRB-18",
    item: "853",
    maxLength: 250,
    name: "Problem Ranking",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CE",
    id: "PRB-19",
    item: "854",
    maxLength: 250,
    name: "Certainty of Problem",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "NM",
    id: "PRB-20",
    item: "855",
    maxLength: 5,
    name: "Probability of Problem (0-1)",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CE",
    id: "PRB-21",
    item: "856",
    maxLength: 250,
    name: "Individual Awareness of Problem",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "CE",
    id: "PRB-22",
    item: "857",
    maxLength: 250,
    name: "Problem Prognosis",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "CE",
    id: "PRB-23",
    item: "858",
    maxLength: 250,
    name: "Individual Awareness of Prognosis",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ST",
    id: "PRB-24",
    item: "859",
    maxLength: 200,
    name: "Family/Significant Other Awareness of Problem/Prognosis",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "CE",
    id: "PRB-25",
    item: "823",
    maxLength: 250,
    name: "Security/Sensitivity",
    repeatable: false,
    required: false,
    sequence: 25,
  },
] as const;
