// Generated segment profile for PRD (v2.4)

export const segmentId = "PRD";
export const fields = [
  {
    datatype: "CE",
    id: "PRD-1",
    item: "1155",
    maxLength: 250,
    name: "Provider Role",
    repeatable: true,
    required: true,
    sequence: 1,
    table: "HL70286",
  },
  {
    datatype: "XPN",
    id: "PRD-2",
    item: "1156",
    maxLength: 250,
    name: "Provider Name",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XAD",
    id: "PRD-3",
    item: "1157",
    maxLength: 250,
    name: "Provider Address",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "PL",
    id: "PRD-4",
    item: "1158",
    maxLength: 60,
    name: "Provider Location",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XTN",
    id: "PRD-5",
    item: "1159",
    maxLength: 250,
    name: "Provider Communication Information",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "PRD-6",
    item: "684",
    maxLength: 250,
    name: "Preferred Method of Contact",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70185",
  },
  {
    datatype: "PI",
    id: "PRD-7",
    item: "1162",
    maxLength: 100,
    name: "Provider Identifiers",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "TS",
    id: "PRD-8",
    item: "1163",
    maxLength: 26,
    name: "Effective Start Date of Provider Role",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "TS",
    id: "PRD-9",
    item: "1164",
    maxLength: 26,
    name: "Effective End Date of Provider Role",
    repeatable: false,
    required: false,
    sequence: 9,
  },
] as const;
