// Generated segment profile for QAK (v2.4)

export const segmentId = "QAK";
export const fields = [
  {
    datatype: "ST",
    id: "QAK-1",
    item: "696",
    maxLength: 32,
    name: "Query Tag",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "QAK-2",
    item: "708",
    maxLength: 2,
    name: "Query Response Status",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70208",
  },
  {
    datatype: "CE",
    id: "QAK-3",
    item: "1375",
    maxLength: 250,
    name: "Message Query Name",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70471",
  },
  {
    datatype: "NM",
    id: "QAK-4",
    item: "1434",
    maxLength: 10,
    name: "Hit Count Total",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "QAK-5",
    item: "1622",
    maxLength: 10,
    name: "This payload",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "QAK-6",
    item: "1623",
    maxLength: 10,
    name: "Hits remaining",
    repeatable: false,
    required: false,
    sequence: 6,
  },
] as const;
