// Generated segment profile for QRF (v2.4)

export const segmentId = "QRF";
export const fields = [
  {
    sequence: 1,
    id: "QRF-1",
    required: true,
    repeatable: true,
    datatype: "ST",
    maxLength: 20,
    name: "Where Subject Filter",
    item: "37",
  },
  {
    sequence: 2,
    id: "QRF-2",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "When Data Start Date/Time",
    item: "38",
  },
  {
    sequence: 3,
    id: "QRF-3",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "When Data End Date/Time",
    item: "39",
  },
  {
    sequence: 4,
    id: "QRF-4",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 60,
    name: "What User Qualifier",
    item: "40",
  },
  {
    sequence: 5,
    id: "QRF-5",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 60,
    name: "Other QRY Subject Filter",
    item: "41",
  },
  {
    sequence: 6,
    id: "QRF-6",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 12,
    table: "HL70156",
    name: "Which Date/Time Qualifier",
    item: "42",
  },
  {
    sequence: 7,
    id: "QRF-7",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 12,
    table: "HL70157",
    name: "Which Date/Time Status Qualifier",
    item: "43",
  },
  {
    sequence: 8,
    id: "QRF-8",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 12,
    table: "HL70158",
    name: "Date/Time Selection Qualifier",
    item: "44",
  },
  {
    sequence: 9,
    id: "QRF-9",
    required: false,
    repeatable: false,
    datatype: "TQ",
    maxLength: 60,
    name: "When Quantity/Timing Qualifier",
    item: "694",
  },
  {
    sequence: 10,
    id: "QRF-10",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 10,
    name: "Search Confidence Threshold",
    item: "1442",
  },
] as const;
