// Generated segment profile for RXC (v2.4)

export const segmentId = "RXC";
export const fields = [
  {
    datatype: "ID",
    id: "RXC-1",
    item: "313",
    maxLength: 1,
    name: "RX Component Type",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70166",
  },
  {
    datatype: "CE",
    id: "RXC-2",
    item: "314",
    maxLength: 250,
    name: "Component Code",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "NM",
    id: "RXC-3",
    item: "315",
    maxLength: 20,
    name: "Component Amount",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "RXC-4",
    item: "316",
    maxLength: 250,
    name: "Component Units",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "RXC-5",
    item: "1124",
    maxLength: 20,
    name: "Component Strength",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "RXC-6",
    item: "1125",
    maxLength: 250,
    name: "Component Strength Units",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "RXC-7",
    item: "1476",
    maxLength: 250,
    name: "Supplementary Code",
    repeatable: true,
    required: false,
    sequence: 7,
  },
] as const;
