// Generated segment profile for RXG (v2.4)

export const segmentId = "RXG";
export const fields = [
  {
    datatype: "NM",
    id: "RXG-1",
    item: "342",
    maxLength: 4,
    name: "Give Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "NM",
    id: "RXG-2",
    item: "334",
    maxLength: 4,
    name: "Dispense Sub-ID Counter",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "TQ",
    id: "RXG-3",
    item: "221",
    maxLength: 200,
    name: "Quantity/Timing",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "RXG-4",
    item: "317",
    maxLength: 250,
    name: "Give Code",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70292",
  },
  {
    datatype: "NM",
    id: "RXG-5",
    item: "318",
    maxLength: 20,
    name: "Give Amount - Minimum",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "RXG-6",
    item: "319",
    maxLength: 20,
    name: "Give Amount - Maximum",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "RXG-7",
    item: "320",
    maxLength: 250,
    name: "Give Units",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "CE",
    id: "RXG-8",
    item: "321",
    maxLength: 250,
    name: "Give Dosage Form",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CE",
    id: "RXG-9",
    item: "351",
    maxLength: 250,
    name: "Administration Notes",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "RXG-10",
    item: "322",
    maxLength: 1,
    name: "Substitution Status",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70167",
  },
  {
    datatype: "LA2",
    id: "RXG-11",
    item: "1303",
    maxLength: 200,
    name: "Dispense-To Location",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ID",
    id: "RXG-12",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70136",
  },
  {
    datatype: "CE",
    id: "RXG-13",
    item: "343",
    maxLength: 250,
    name: "Pharmacy/Treatment Supplier&apos;s Special Administration Instructions",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "RXG-14",
    item: "331",
    maxLength: 20,
    name: "Give Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "RXG-15",
    item: "332",
    maxLength: 6,
    name: "Give Rate Amount",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CE",
    id: "RXG-16",
    item: "333",
    maxLength: 250,
    name: "Give Rate Units",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "NM",
    id: "RXG-17",
    item: "1126",
    maxLength: 20,
    name: "Give Strength",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CE",
    id: "RXG-18",
    item: "1127",
    maxLength: 250,
    name: "Give Strength Units",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    id: "RXG-19",
    item: "1129",
    maxLength: 20,
    name: "Substance Lot Number",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "TS",
    id: "RXG-20",
    item: "1130",
    maxLength: 26,
    name: "Substance Expiration Date",
    repeatable: true,
    required: false,
    sequence: 20,
  },
  {
    datatype: "CE",
    id: "RXG-21",
    item: "1131",
    maxLength: 250,
    name: "Substance Manufacturer Name",
    repeatable: true,
    required: false,
    sequence: 21,
    table: "HL70227",
  },
  {
    datatype: "CE",
    id: "RXG-22",
    item: "1123",
    maxLength: 250,
    name: "Indication",
    repeatable: true,
    required: false,
    sequence: 22,
  },
] as const;
