// Generated segment profile for PRC (v2.3)

export const segmentId = "PRC";
export const fields = [
  {
    sequence: 1,
    id: "PRC-1",
    required: true,
    repeatable: false,
    datatype: "CE",
    maxLength: 200,
    table: "HL70132",
    name: "Primary Key Value",
    item: "982",
  },
  {
    sequence: 2,
    id: "PRC-2",
    required: true,
    repeatable: true,
    datatype: "EI",
    maxLength: 60,
    name: "Facility ID",
    item: "1262",
  },
  {
    sequence: 3,
    id: "PRC-3",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 30,
    name: "Department",
    item: "996",
  },
  {
    sequence: 4,
    id: "PRC-4",
    required: false,
    repeatable: true,
    datatype: "ID",
    maxLength: 1,
    table: "HL70004",
    name: "Valid Patient Classes",
    item: "967",
  },
  {
    sequence: 5,
    id: "PRC-5",
    required: false,
    repeatable: true,
    datatype: "CP",
    maxLength: 12,
    name: "Price",
    item: "998",
  },
  {
    sequence: 6,
    id: "PRC-6",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 200,
    name: "Formula",
    item: "999",
  },
  {
    sequence: 7,
    id: "PRC-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Minimum Quantity",
    item: "1000",
  },
  {
    sequence: 8,
    id: "PRC-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Maximum Quantity",
    item: "1001",
  },
  {
    sequence: 9,
    id: "PRC-9",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 12,
    name: "Minimum Price",
    item: "1002",
  },
  {
    sequence: 10,
    id: "PRC-10",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 12,
    name: "Maximum Price",
    item: "1003",
  },
  {
    sequence: 11,
    id: "PRC-11",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective Start Date",
    item: "1004",
  },
  {
    sequence: 12,
    id: "PRC-12",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Effective End Date",
    item: "1005",
  },
  {
    sequence: 13,
    id: "PRC-13",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70268",
    name: "Price Override Flag",
    item: "1006",
  },
  {
    sequence: 14,
    id: "PRC-14",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 60,
    table: "HL70293",
    name: "Billing Category",
    item: "1007",
  },
  {
    sequence: 15,
    id: "PRC-15",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Chargeable Flag",
    item: "1008",
  },
  {
    sequence: 16,
    id: "PRC-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70183",
    name: "Active/Inactive Flag",
    item: "675",
  },
  {
    sequence: 17,
    id: "PRC-17",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 12,
    name: "Cost",
    item: "989",
  },
  {
    sequence: 18,
    id: "PRC-18",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70269",
    name: "Charge On Indicator",
    item: "1009",
  },
] as const;
