// Generated segment profile for BPO (v2.7)

export const segmentId = "BPO";
export const fields = [
  {
    datatype: "SI",
    id: "BPO-1",
    item: "1700",
    maxLength: 4,
    name: "Set ID - BPO",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "BPO-2",
    item: "1701",
    name: "BP Universal Service Identifier",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "BPO-3",
    item: "1702",
    name: "BP  Processing Requirements",
    repeatable: true,
    required: false,
    sequence: 3,
    table: "HL70508",
  },
  {
    datatype: "NM",
    id: "BPO-4",
    item: "1703",
    name: "BP Quantity",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "BPO-5",
    item: "1704",
    name: "BP Amount",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "BPO-6",
    item: "1705",
    name: "BP Units",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "BPO-7",
    item: "1706",
    name: "BP Intended Use Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "PL",
    id: "BPO-8",
    item: "1707",
    name: "BP Intended Dispense From Location",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "XAD",
    id: "BPO-9",
    item: "1708",
    name: "BP Intended Dispense From Address",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "DTM",
    id: "BPO-10",
    item: "1709",
    name: "BP Requested Dispense Date/Time",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "PL",
    id: "BPO-11",
    item: "1710",
    name: "BP Requested Dispense To Location",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "XAD",
    id: "BPO-12",
    item: "1711",
    name: "BP Requested Dispense To Address",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "BPO-13",
    item: "1712",
    name: "BP Indication for Use",
    repeatable: true,
    required: false,
    sequence: 13,
    table: "HL70509",
  },
  {
    datatype: "ID",
    id: "BPO-14",
    item: "1713",
    maxLength: 1,
    name: "BP Informed Consent Indicator",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70136",
  },
] as const;
