// Generated segment profile for CON (v2.7)

export const segmentId = "CON";
export const fields = [
  {
    datatype: "SI",
    id: "CON-1",
    item: "1776",
    maxLength: 4,
    name: "Set ID - CON",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "CON-2",
    item: "1777",
    name: "Consent Type",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70496",
  },
  {
    datatype: "ST",
    id: "CON-3",
    item: "1778",
    name: "Consent Form ID and Version",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "CON-4",
    item: "1779",
    name: "Consent Form Number",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "FT",
    id: "CON-5",
    item: "1780",
    name: "Consent Text",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "FT",
    id: "CON-6",
    item: "1781",
    name: "Subject-specific Consent Text",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "FT",
    id: "CON-7",
    item: "1782",
    name: "Consent Background Information",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "FT",
    id: "CON-8",
    item: "1783",
    name: "Subject-specific Consent Background Text",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "FT",
    id: "CON-9",
    item: "1784",
    name: "Consenter-imposed limitations",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CNE",
    id: "CON-10",
    item: "1785",
    name: "Consent Mode",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70497",
  },
  {
    datatype: "CNE",
    id: "CON-11",
    item: "1786",
    name: "Consent Status",
    repeatable: false,
    required: true,
    sequence: 11,
    table: "HL70498",
  },
  {
    datatype: "DTM",
    id: "CON-12",
    item: "1787",
    name: "Consent Discussion Date/Time",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DTM",
    id: "CON-13",
    item: "1788",
    name: "Consent Decision Date/Time",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DTM",
    id: "CON-14",
    item: "1789",
    name: "Consent Effective Date/Time",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "DTM",
    id: "CON-15",
    item: "1790",
    name: "Consent End Date/Time",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ID",
    id: "CON-16",
    item: "1791",
    maxLength: 1,
    name: "Subject Competence Indicator",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70136",
  },
  {
    datatype: "ID",
    id: "CON-17",
    item: "1792",
    maxLength: 1,
    name: "Translator Assistance Indicator",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "CON-18",
    item: "1793",
    name: "Language Translated To",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70296",
  },
  {
    datatype: "ID",
    id: "CON-19",
    item: "1794",
    maxLength: 1,
    name: "Informational Material Supplied Indicator",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "CON-20",
    item: "1795",
    name: "Consent Bypass Reason",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70499",
  },
  {
    datatype: "ID",
    id: "CON-21",
    item: "1796",
    maxLength: 1,
    name: "Consent Disclosure Level",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70500",
  },
  {
    datatype: "CWE",
    id: "CON-22",
    item: "1797",
    name: "Consent Non-disclosure Reason",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70501",
  },
  {
    datatype: "CWE",
    id: "CON-23",
    item: "1798",
    name: "Non-subject Consenter Reason",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70502",
  },
  {
    datatype: "XPN",
    id: "CON-24",
    item: "1909",
    name: "Consenter ID",
    repeatable: true,
    required: true,
    sequence: 24,
  },
  {
    datatype: "CWE",
    id: "CON-25",
    item: "1898",
    name: "Relationship to Subject",
    repeatable: true,
    required: true,
    sequence: 25,
    table: "HL70548",
  },
] as const;
