// Generated segment profile for DRG (v2.7)

export const segmentId = "DRG";
export const fields = [
  {
    datatype: "CNE",
    id: "DRG-1",
    item: "382",
    name: "Diagnostic Related Group",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70055",
  },
  {
    datatype: "DTM",
    id: "DRG-2",
    item: "769",
    name: "DRG Assigned Date/Time",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ID",
    id: "DRG-3",
    item: "383",
    maxLength: 1,
    name: "DRG Approval Indicator",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "DRG-4",
    item: "384",
    name: "DRG Grouper Review Code",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70056",
  },
  {
    datatype: "CWE",
    id: "DRG-5",
    item: "385",
    name: "Outlier Type",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70083",
  },
  {
    datatype: "NM",
    id: "DRG-6",
    item: "386",
    name: "Outlier Days",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CP",
    id: "DRG-7",
    item: "387",
    name: "Outlier Cost",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "CWE",
    id: "DRG-8",
    item: "770",
    name: "DRG Payor",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70229",
  },
  {
    datatype: "CP",
    id: "DRG-9",
    item: "771",
    name: "Outlier Reimbursement",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "DRG-10",
    item: "767",
    maxLength: 1,
    name: "Confidential Indicator",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "DRG-11",
    item: "1500",
    name: "DRG Transfer Type",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70415",
  },
  {
    datatype: "XPN",
    id: "DRG-12",
    item: "2156",
    name: "Name of Coder",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "DRG-13",
    item: "2157",
    name: "Grouper Status",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70734",
  },
  {
    datatype: "CWE",
    id: "DRG-14",
    item: "2158",
    name: "PCCL Value Code",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70728",
  },
  {
    datatype: "NM",
    id: "DRG-15",
    item: "2159",
    name: "Effective Weight",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "MO",
    id: "DRG-16",
    item: "2160",
    name: "Monetary Amount",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CWE",
    id: "DRG-17",
    item: "2161",
    name: "Status Patient",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70739",
  },
  {
    datatype: "ST",
    id: "DRG-18",
    item: "2162",
    name: "Grouper Software Name",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ST",
    id: "DRG-19",
    item: "2282",
    name: "Grouper Software Version",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CWE",
    id: "DRG-20",
    item: "2163",
    name: "Status Financial Calculation",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70742",
  },
  {
    datatype: "MO",
    id: "DRG-21",
    item: "2164",
    name: "Relative Discount/Surcharge",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "MO",
    id: "DRG-22",
    item: "2165",
    name: "Basic Charge",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "MO",
    id: "DRG-23",
    item: "2166",
    name: "Total Charge",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "MO",
    id: "DRG-24",
    item: "2167",
    name: "Discount/Surcharge",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "NM",
    id: "DRG-25",
    item: "2168",
    name: "Calculated Days",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "CWE",
    id: "DRG-26",
    item: "2169",
    name: "Status Gender",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70749",
  },
  {
    datatype: "CWE",
    id: "DRG-27",
    item: "2170",
    name: "Status Age",
    repeatable: false,
    required: false,
    sequence: 27,
    table: "HL70749",
  },
  {
    datatype: "CWE",
    id: "DRG-28",
    item: "2171",
    name: "Status Length of Stay",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70749",
  },
  {
    datatype: "CWE",
    id: "DRG-29",
    item: "2172",
    name: "Status Same Day Flag",
    repeatable: false,
    required: false,
    sequence: 29,
    table: "HL70749",
  },
  {
    datatype: "CWE",
    id: "DRG-30",
    item: "2173",
    name: "Status Separation Mode",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70749",
  },
  {
    datatype: "CWE",
    id: "DRG-31",
    item: "2174",
    name: "Status Weight at Birth",
    repeatable: false,
    required: false,
    sequence: 31,
    table: "HL70755",
  },
  {
    datatype: "CWE",
    id: "DRG-32",
    item: "2175",
    name: "Status Respiration Minutes",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70757",
  },
  {
    datatype: "CWE",
    id: "DRG-33",
    item: "2176",
    name: "Status Admission",
    repeatable: false,
    required: false,
    sequence: 33,
    table: "HL70759",
  },
] as const;
