// Generated segment profile for IAM (v2.7)

export const segmentId = "IAM";
export const fields = [
  {
    datatype: "SI",
    id: "IAM-1",
    item: "1612",
    maxLength: 4,
    name: "Set ID - IAM",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "IAM-2",
    item: "204",
    name: "Allergen Type Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70127",
  },
  {
    datatype: "CWE",
    id: "IAM-3",
    item: "205",
    name: "Allergen Code/Mnemonic/Description",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "IAM-4",
    item: "206",
    name: "Allergy Severity Code",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70128",
  },
  {
    datatype: "ST",
    id: "IAM-5",
    item: "207",
    name: "Allergy Reaction Code",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CNE",
    id: "IAM-6",
    item: "1551",
    name: "Allergy Action Code",
    repeatable: false,
    required: true,
    sequence: 6,
    table: "HL70206",
  },
  {
    datatype: "EI",
    id: "IAM-7",
    item: "1552",
    name: "Allergy Unique Identifier",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ST",
    id: "IAM-8",
    item: "1553",
    name: "Action Reason",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "IAM-9",
    item: "1554",
    name: "Sensitivity to Causative Agent Code",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70436",
  },
  {
    datatype: "CWE",
    id: "IAM-10",
    item: "1555",
    name: "Allergen Group Code/Mnemonic/Description",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DT",
    id: "IAM-11",
    item: "1556",
    name: "Onset Date",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "IAM-12",
    item: "1557",
    name: "Onset Date Text",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DTM",
    id: "IAM-13",
    item: "1558",
    name: "Reported Date/Time",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XPN",
    id: "IAM-14",
    item: "1559",
    name: "Reported By",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "IAM-15",
    item: "1560",
    name: "Relationship to Patient Code",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70063",
  },
  {
    datatype: "CWE",
    id: "IAM-16",
    item: "1561",
    name: "Alert Device Code",
    repeatable: false,
    required: false,
    sequence: 16,
    table: "HL70437",
  },
  {
    datatype: "CWE",
    id: "IAM-17",
    item: "1562",
    name: "Allergy Clinical Status Code",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70438",
  },
  {
    datatype: "XCN",
    id: "IAM-18",
    item: "1563",
    name: "Statused by Person",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "XON",
    id: "IAM-19",
    item: "1564",
    name: "Statused by Organization",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "DTM",
    id: "IAM-20",
    item: "1565",
    name: "Statused at Date/Time",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "XCN",
    id: "IAM-21",
    item: "2294",
    name: "Inactivated by Person",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "DTM",
    id: "IAM-22",
    item: "2295",
    name: "Inactivated Date/Time",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "XCN",
    id: "IAM-23",
    item: "2296",
    name: "Initially Recorded by Person",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "DTM",
    id: "IAM-24",
    item: "2297",
    name: "Initially Recorded Date/Time",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "XCN",
    id: "IAM-25",
    item: "2298",
    name: "Modified by Person",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "DTM",
    id: "IAM-26",
    item: "2299",
    name: "Modified Date/Time",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CWE",
    id: "IAM-27",
    item: "2300",
    name: "Clinician Identified Code",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "XON",
    id: "IAM-28",
    item: "3293",
    name: "Initially Recorded by Organization",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "XON",
    id: "IAM-29",
    item: "3294",
    name: "Modified by Organization",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "XON",
    id: "IAM-30",
    item: "3295",
    name: "Inactivated by Organization",
    repeatable: false,
    required: false,
    sequence: 30,
  },
] as const;
