// Generated segment profile for MFA (v2.7)

export const segmentId = "MFA";
export const fields = [
  {
    datatype: "ID",
    id: "MFA-1",
    item: "664",
    maxLength: 3,
    name: "Record-Level Event Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70180",
  },
  {
    datatype: "ST",
    id: "MFA-2",
    item: "665",
    name: "MFN Control ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "DTM",
    id: "MFA-3",
    item: "668",
    name: "Event Completion Date/Time",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "MFA-4",
    item: "669",
    name: "MFN Record Level Error Return",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70181",
  },
  {
    datatype: "varies",
    id: "MFA-5",
    item: "1308",
    name: "Primary Key Value - MFA",
    repeatable: true,
    required: true,
    sequence: 5,
  },
  {
    datatype: "ID",
    id: "MFA-6",
    item: "1320",
    maxLength: 3,
    name: "Primary Key Value Type - MFA",
    repeatable: true,
    required: true,
    sequence: 6,
    table: "HL70355",
  },
] as const;
