// Generated segment profile for NSC (v2.7)

export const segmentId = "NSC";
export const fields = [
  {
    datatype: "CWE",
    id: "NSC-1",
    item: "1188",
    name: "Application Change Type",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70409",
  },
  {
    datatype: "ST",
    id: "NSC-2",
    item: "1189",
    name: "Current CPU",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "NSC-3",
    item: "1190",
    name: "Current Fileserver",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "HD",
    id: "NSC-4",
    item: "1191",
    name: "Current Application",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70361",
  },
  {
    datatype: "HD",
    id: "NSC-5",
    item: "1192",
    name: "Current Facility",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70362",
  },
  {
    datatype: "ST",
    id: "NSC-6",
    item: "1193",
    name: "New CPU",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "NSC-7",
    item: "1194",
    name: "New Fileserver",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "HD",
    id: "NSC-8",
    item: "1195",
    name: "New Application",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70361",
  },
  {
    datatype: "HD",
    id: "NSC-9",
    item: "1196",
    name: "New Facility",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70362",
  },
] as const;
