// Generated segment profile for OM3 (v2.7)

export const segmentId = "OM3";
export const fields = [
  {
    datatype: "NM",
    id: "OM3-1",
    item: "586",
    name: "Sequence Number - Test/Observation Master File",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "OM3-2",
    item: "636",
    name: "Preferred Coding System",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "OM3-3",
    item: "637",
    name: "Valid Coded &quot;Answers&quot;",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "OM3-4",
    item: "638",
    name: "Normal Text/Codes for Categorical Observations",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "OM3-5",
    item: "639",
    name: "Abnormal Text/Codes for Categorical Observations",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "OM3-6",
    item: "640",
    name: "Critical Text/Codes for Categorical Observations",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ID",
    id: "OM3-7",
    item: "570",
    maxLength: 3,
    name: "Value Type",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70125",
  },
] as const;
