// Generated segment profile for PD1 (v2.7)

export const segmentId = "PD1";
export const fields = [
  {
    sequence: 1,
    id: "PD1-1",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70223",
    name: "Living Dependency",
    item: "755",
  },
  {
    sequence: 2,
    id: "PD1-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70220",
    name: "Living Arrangement",
    item: "742",
  },
  {
    sequence: 3,
    id: "PD1-3",
    required: false,
    repeatable: true,
    datatype: "XON",
    name: "Patient Primary Facility",
    item: "756",
  },
  {
    sequence: 4,
    id: "PD1-4",
    deprecated: true,
    required: false,
    repeatable: true,
    datatype: "XCN",
    name: "Patient Primary Care Provider Name &amp; ID No.",
    item: "757",
  },
  {
    sequence: 5,
    id: "PD1-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70231",
    name: "Student Indicator",
    item: "745",
  },
  {
    sequence: 6,
    id: "PD1-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70295",
    name: "Handicap",
    item: "753",
  },
  {
    sequence: 7,
    id: "PD1-7",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70315",
    name: "Living Will Code",
    item: "759",
  },
  {
    sequence: 8,
    id: "PD1-8",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70316",
    name: "Organ Donor Code",
    item: "760",
  },
  {
    sequence: 9,
    id: "PD1-9",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Separate Bill",
    item: "761",
  },
  {
    sequence: 10,
    id: "PD1-10",
    required: false,
    repeatable: true,
    datatype: "CX",
    name: "Duplicate Patient",
    item: "762",
  },
  {
    sequence: 11,
    id: "PD1-11",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70215",
    name: "Publicity Code",
    item: "743",
  },
  {
    sequence: 12,
    id: "PD1-12",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Protection Indicator",
    item: "744",
  },
  {
    sequence: 13,
    id: "PD1-13",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Protection Indicator Effective Date",
    item: "1566",
  },
  {
    sequence: 14,
    id: "PD1-14",
    required: false,
    repeatable: true,
    datatype: "XON",
    name: "Place of Worship",
    item: "1567",
  },
  {
    sequence: 15,
    id: "PD1-15",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70435",
    name: "Advance Directive Code",
    item: "1548",
  },
  {
    sequence: 16,
    id: "PD1-16",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70441",
    name: "Immunization Registry Status",
    item: "1569",
  },
  {
    sequence: 17,
    id: "PD1-17",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Immunization Registry Status Effective Date",
    item: "1570",
  },
  {
    sequence: 18,
    id: "PD1-18",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Publicity Code Effective Date",
    item: "1571",
  },
  {
    sequence: 19,
    id: "PD1-19",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70140",
    name: "Military Branch",
    item: "1572",
  },
  {
    sequence: 20,
    id: "PD1-20",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70141",
    name: "Military Rank/Grade",
    item: "486",
  },
  {
    sequence: 21,
    id: "PD1-21",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70142",
    name: "Military Status",
    item: "1573",
  },
  {
    sequence: 22,
    id: "PD1-22",
    required: false,
    repeatable: false,
    datatype: "DT",
    name: "Advance Directive Last Verified Date",
    item: "2141",
  },
] as const;
