// Generated segment profile for PRD (v2.7)

export const segmentId = "PRD";
export const fields = [
  {
    datatype: "CWE",
    id: "PRD-1",
    item: "1155",
    name: "Provider Role",
    repeatable: true,
    required: true,
    sequence: 1,
    table: "HL70286",
  },
  {
    datatype: "XPN",
    id: "PRD-2",
    item: "1156",
    name: "Provider Name",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XAD",
    id: "PRD-3",
    item: "1157",
    name: "Provider Address",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "PL",
    id: "PRD-4",
    item: "1158",
    name: "Provider Location",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XTN",
    id: "PRD-5",
    item: "1159",
    name: "Provider Communication Information",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "PRD-6",
    item: "684",
    name: "Preferred Method of Contact",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70185",
  },
  {
    datatype: "PLN",
    id: "PRD-7",
    item: "1162",
    name: "Provider Identifiers",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DTM",
    id: "PRD-8",
    item: "1163",
    name: "Effective Start Date of Provider Role",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "DTM",
    id: "PRD-9",
    item: "1164",
    name: "Effective End Date of Provider Role",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XON",
    id: "PRD-10",
    item: "2256",
    name: "Provider Organization Name and Identifier",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XAD",
    id: "PRD-11",
    item: "2257",
    name: "Provider Organization Address",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "PL",
    id: "PRD-12",
    item: "2258",
    name: "Provider Organization Location Information",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "XTN",
    id: "PRD-13",
    item: "2259",
    name: "Provider Organization Communication Information",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CWE",
    id: "PRD-14",
    item: "2260",
    name: "Provider Organization Method of Contact",
    repeatable: true,
    required: false,
    sequence: 14,
    table: "HL70185",
  },
] as const;
