// Generated segment profile for RXE (v2.7)

export const segmentId = "RXE";
export const fields = [
  {
    datatype: "TQ",
    deprecated: true,
    id: "RXE-1",
    item: "221",
    name: "Quantity/Timing",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "RXE-2",
    item: "317",
    name: "Give Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70292",
  },
  {
    datatype: "NM",
    id: "RXE-3",
    item: "318",
    name: "Give Amount - Minimum",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "RXE-4",
    item: "319",
    name: "Give Amount - Maximum",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CWE",
    id: "RXE-5",
    item: "320",
    name: "Give Units",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "CWE",
    id: "RXE-6",
    item: "321",
    name: "Give Dosage Form",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "RXE-7",
    item: "298",
    name: "Provider's Administration Instructions",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "LA1",
    deprecated: true,
    id: "RXE-8",
    item: "299",
    name: "Deliver-To Location",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ID",
    id: "RXE-9",
    item: "322",
    maxLength: 1,
    name: "Substitution Status",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70167",
  },
  {
    datatype: "NM",
    id: "RXE-10",
    item: "323",
    name: "Dispense Amount",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "RXE-11",
    item: "324",
    name: "Dispense Units",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "NM",
    id: "RXE-12",
    item: "304",
    name: "Number Of Refills",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "XCN",
    id: "RXE-13",
    item: "305",
    name: "Ordering Provider's DEA Number",
    repeatable: true,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XCN",
    id: "RXE-14",
    item: "306",
    name: "Pharmacist/Treatment Supplier's Verifier ID",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "ST",
    id: "RXE-15",
    item: "325",
    name: "Prescription Number",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "NM",
    id: "RXE-16",
    item: "326",
    name: "Number of Refills Remaining",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "NM",
    id: "RXE-17",
    item: "327",
    name: "Number of Refills/Doses Dispensed",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "DTM",
    id: "RXE-18",
    item: "328",
    name: "D/T of Most Recent Refill or Dose Dispensed",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CQ",
    id: "RXE-19",
    item: "329",
    name: "Total Daily Dose",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "RXE-20",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "RXE-21",
    item: "330",
    name: "Pharmacy/Treatment Supplier's Special Dispensing Instructions",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "ST",
    id: "RXE-22",
    item: "331",
    name: "Give Per (Time Unit)",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ST",
    id: "RXE-23",
    item: "332",
    name: "Give Rate Amount",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "CWE",
    id: "RXE-24",
    item: "333",
    name: "Give Rate Units",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "NM",
    id: "RXE-25",
    item: "1126",
    name: "Give Strength",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "CWE",
    id: "RXE-26",
    item: "1127",
    name: "Give Strength Units",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CWE",
    id: "RXE-27",
    item: "1128",
    name: "Give Indication",
    repeatable: true,
    required: false,
    sequence: 27,
  },
  {
    datatype: "NM",
    id: "RXE-28",
    item: "1220",
    name: "Dispense Package Size",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "CWE",
    id: "RXE-29",
    item: "1221",
    name: "Dispense Package Size Unit",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "ID",
    id: "RXE-30",
    item: "1222",
    maxLength: 2,
    name: "Dispense Package Method",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70321",
  },
  {
    datatype: "CWE",
    id: "RXE-31",
    item: "1476",
    name: "Supplementary Code",
    repeatable: true,
    required: false,
    sequence: 31,
  },
  {
    datatype: "DTM",
    id: "RXE-32",
    item: "1673",
    name: "Original Order Date/Time",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "NM",
    id: "RXE-33",
    item: "1674",
    name: "Give Drug Strength Volume",
    repeatable: false,
    required: false,
    sequence: 33,
  },
  {
    datatype: "CWE",
    id: "RXE-34",
    item: "1675",
    name: "Give Drug Strength Volume Units",
    repeatable: false,
    required: false,
    sequence: 34,
  },
  {
    datatype: "CWE",
    id: "RXE-35",
    item: "1676",
    name: "Controlled Substance Schedule",
    repeatable: false,
    required: false,
    sequence: 35,
    table: "HL70477",
  },
  {
    datatype: "ID",
    id: "RXE-36",
    item: "1677",
    maxLength: 1,
    name: "Formulary Status",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL70478",
  },
  {
    datatype: "CWE",
    id: "RXE-37",
    item: "1678",
    name: "Pharmaceutical Substance Alternative",
    repeatable: true,
    required: false,
    sequence: 37,
  },
  {
    datatype: "CWE",
    id: "RXE-38",
    item: "1679",
    name: "Pharmacy of Most Recent Fill",
    repeatable: false,
    required: false,
    sequence: 38,
  },
  {
    datatype: "NM",
    id: "RXE-39",
    item: "1680",
    name: "Initial Dispense Amount",
    repeatable: false,
    required: false,
    sequence: 39,
  },
  {
    datatype: "CWE",
    id: "RXE-40",
    item: "1681",
    name: "Dispensing Pharmacy",
    repeatable: false,
    required: false,
    sequence: 40,
  },
  {
    datatype: "XAD",
    id: "RXE-41",
    item: "1682",
    name: "Dispensing Pharmacy Address",
    repeatable: false,
    required: false,
    sequence: 41,
  },
  {
    datatype: "PL",
    id: "RXE-42",
    item: "1683",
    name: "Deliver-to Patient Location",
    repeatable: false,
    required: false,
    sequence: 42,
  },
  {
    datatype: "XAD",
    id: "RXE-43",
    item: "1684",
    name: "Deliver-to Address",
    repeatable: false,
    required: false,
    sequence: 43,
  },
  {
    datatype: "ID",
    id: "RXE-44",
    item: "1685",
    maxLength: 1,
    name: "Pharmacy Order Type",
    repeatable: false,
    required: false,
    sequence: 44,
    table: "HL70480",
  },
  {
    datatype: "XTN",
    id: "RXE-45",
    item: "2310",
    name: "Pharmacy Phone Number",
    repeatable: true,
    required: false,
    sequence: 45,
  },
] as const;
