// Generated segment profile for SCP (v2.7)

export const segmentId = "SCP";
export const fields = [
  {
    datatype: "NM",
    id: "SCP-1",
    item: "2087",
    name: "Number Of Decontamination/Sterilization Devices",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "SCP-2",
    item: "2088",
    name: "Labor Calculation Type",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70651",
  },
  {
    datatype: "CWE",
    id: "SCP-3",
    item: "2089",
    name: "Date Format",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70653",
  },
  {
    datatype: "EI",
    id: "SCP-4",
    item: "2090",
    name: "Device Number",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ST",
    id: "SCP-5",
    item: "2279",
    name: "Device Name",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "ST",
    id: "SCP-6",
    item: "2091",
    name: "Device Model Name",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CWE",
    id: "SCP-7",
    item: "2092",
    name: "Device Type",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70657",
  },
  {
    datatype: "CWE",
    id: "SCP-8",
    item: "2093",
    name: "Lot Control",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70659",
  },
] as const;
