// Generated segment profile for SPM (v2.7)

export const segmentId = "SPM";
export const fields = [
  {
    datatype: "SI",
    id: "SPM-1",
    item: "1754",
    maxLength: 4,
    name: "Set ID - SPM",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "EIP",
    id: "SPM-2",
    item: "1755",
    name: "Specimen ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "EIP",
    id: "SPM-3",
    item: "1756",
    name: "Specimen Parent IDs",
    repeatable: true,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "SPM-4",
    item: "1900",
    name: "Specimen Type",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70487",
  },
  {
    datatype: "CWE",
    id: "SPM-5",
    item: "1757",
    name: "Specimen Type Modifier",
    repeatable: true,
    required: false,
    sequence: 5,
    table: "HL70541",
  },
  {
    datatype: "CWE",
    id: "SPM-6",
    item: "1758",
    name: "Specimen Additives",
    repeatable: true,
    required: false,
    sequence: 6,
    table: "HL70371",
  },
  {
    datatype: "CWE",
    id: "SPM-7",
    item: "1759",
    name: "Specimen Collection Method",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70488",
  },
  {
    datatype: "CWE",
    id: "SPM-8",
    item: "1901",
    name: "Specimen Source Site",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "SPM-9",
    item: "1760",
    name: "Specimen Source Site Modifier",
    repeatable: true,
    required: false,
    sequence: 9,
    table: "HL70542",
  },
  {
    datatype: "CWE",
    id: "SPM-10",
    item: "1761",
    name: "Specimen Collection Site",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70543",
  },
  {
    datatype: "CWE",
    id: "SPM-11",
    item: "1762",
    name: "Specimen Role",
    repeatable: true,
    required: false,
    sequence: 11,
    table: "HL70369",
  },
  {
    datatype: "CQ",
    id: "SPM-12",
    item: "1902",
    name: "Specimen Collection Amount",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "NM",
    id: "SPM-13",
    item: "1763",
    name: "Grouped Specimen Count",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ST",
    id: "SPM-14",
    item: "1764",
    name: "Specimen Description",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CWE",
    id: "SPM-15",
    item: "1908",
    name: "Specimen Handling Code",
    repeatable: true,
    required: false,
    sequence: 15,
    table: "HL70376",
  },
  {
    datatype: "CWE",
    id: "SPM-16",
    item: "1903",
    name: "Specimen Risk Code",
    repeatable: true,
    required: false,
    sequence: 16,
    table: "HL70489",
  },
  {
    datatype: "DR",
    id: "SPM-17",
    item: "1765",
    name: "Specimen Collection Date/Time",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "DTM",
    id: "SPM-18",
    item: "248",
    name: "Specimen Received Date/Time",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "DTM",
    id: "SPM-19",
    item: "1904",
    name: "Specimen Expiration Date/Time",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "SPM-20",
    item: "1766",
    maxLength: 1,
    name: "Specimen Availability",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "SPM-21",
    item: "1767",
    name: "Specimen Reject Reason",
    repeatable: true,
    required: false,
    sequence: 21,
    table: "HL70490",
  },
  {
    datatype: "CWE",
    id: "SPM-22",
    item: "1768",
    name: "Specimen Quality",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70491",
  },
  {
    datatype: "CWE",
    id: "SPM-23",
    item: "1769",
    name: "Specimen Appropriateness",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70492",
  },
  {
    datatype: "CWE",
    id: "SPM-24",
    item: "1770",
    name: "Specimen Condition",
    repeatable: true,
    required: false,
    sequence: 24,
    table: "HL70493",
  },
  {
    datatype: "CQ",
    id: "SPM-25",
    item: "1771",
    name: "Specimen Current Quantity",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "NM",
    id: "SPM-26",
    item: "1772",
    name: "Number of Specimen Containers",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CWE",
    id: "SPM-27",
    item: "1773",
    name: "Container Type",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "CWE",
    id: "SPM-28",
    item: "1774",
    name: "Container Condition",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70544",
  },
  {
    datatype: "CWE",
    id: "SPM-29",
    item: "1775",
    name: "Specimen Child Role",
    repeatable: false,
    required: false,
    sequence: 29,
    table: "HL70494",
  },
  {
    datatype: "CX",
    id: "SPM-30",
    item: "2314",
    name: "Accession ID",
    repeatable: true,
    required: false,
    sequence: 30,
  },
  {
    datatype: "CX",
    id: "SPM-31",
    item: "2315",
    name: "Other Specimen ID",
    repeatable: true,
    required: false,
    sequence: 31,
  },
  {
    datatype: "EI",
    id: "SPM-32",
    item: "2316",
    name: "Shipment ID",
    repeatable: true,
    required: false,
    sequence: 32,
  },
] as const;
