// Generated segment profile for TXA (v2.7)

export const segmentId = "TXA";
export const fields = [
  {
    datatype: "SI",
    id: "TXA-1",
    item: "914",
    maxLength: 4,
    name: "Set ID- TXA",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "TXA-2",
    item: "915",
    name: "Document Type",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70270",
  },
  {
    datatype: "ID",
    id: "TXA-3",
    item: "916",
    name: "Document Content Presentation",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70191",
  },
  {
    datatype: "DTM",
    id: "TXA-4",
    item: "917",
    name: "Activity Date/Time",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XCN",
    id: "TXA-5",
    item: "918",
    name: "Primary Activity Provider Code/Name",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DTM",
    id: "TXA-6",
    item: "919",
    name: "Origination Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "TXA-7",
    item: "920",
    name: "Transcription Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DTM",
    id: "TXA-8",
    item: "921",
    name: "Edit Date/Time",
    repeatable: true,
    required: false,
    sequence: 8,
  },
  {
    datatype: "XCN",
    id: "TXA-9",
    item: "922",
    name: "Originator Code/Name",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XCN",
    id: "TXA-10",
    item: "923",
    name: "Assigned Document Authenticator",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XCN",
    id: "TXA-11",
    item: "924",
    name: "Transcriptionist Code/Name",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "EI",
    id: "TXA-12",
    item: "925",
    name: "Unique Document Number",
    repeatable: false,
    required: true,
    sequence: 12,
  },
  {
    datatype: "EI",
    id: "TXA-13",
    item: "926",
    name: "Parent Document Number",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "EI",
    id: "TXA-14",
    item: "216",
    name: "Placer Order Number",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "EI",
    id: "TXA-15",
    item: "217",
    name: "Filler Order Number",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "ST",
    id: "TXA-16",
    item: "927",
    name: "Unique Document File Name",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "TXA-17",
    item: "928",
    maxLength: 2,
    name: "Document Completion Status",
    repeatable: false,
    required: true,
    sequence: 17,
    table: "HL70271",
  },
  {
    datatype: "ID",
    id: "TXA-18",
    item: "929",
    maxLength: 1,
    name: "Document Confidentiality Status",
    repeatable: false,
    required: false,
    sequence: 18,
    table: "HL70272",
  },
  {
    datatype: "ID",
    id: "TXA-19",
    item: "930",
    maxLength: 2,
    name: "Document Availability Status",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70273",
  },
  {
    datatype: "ID",
    id: "TXA-20",
    item: "932",
    maxLength: 2,
    name: "Document Storage Status",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70275",
  },
  {
    datatype: "ST",
    id: "TXA-21",
    item: "933",
    name: "Document Change Reason",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "PPN",
    id: "TXA-22",
    item: "934",
    name: "Authentication Person, Time Stamp (set)",
    repeatable: true,
    required: false,
    sequence: 22,
  },
  {
    datatype: "XCN",
    id: "TXA-23",
    item: "935",
    name: "Distributed Copies (Code and Name of Recipient(s) )",
    repeatable: true,
    required: false,
    sequence: 23,
  },
  {
    datatype: "CWE",
    id: "TXA-24",
    item: "2378",
    name: "Folder Assignment",
    repeatable: true,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ST",
    id: "TXA-25",
    item: "3301",
    name: "Document Title",
    repeatable: true,
    required: false,
    sequence: 25,
  },
  {
    datatype: "DTM",
    id: "TXA-26",
    item: "3302",
    name: "Agreed Due Date/Time",
    repeatable: false,
    required: false,
    sequence: 26,
  },
] as const;
