// Generated segment profile for AIG (v2.5)

export const segmentId = "AIG";
export const fields = [
  {
    datatype: "SI",
    id: "AIG-1",
    item: "896",
    maxLength: 4,
    name: "Set ID - AIG",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "ID",
    id: "AIG-2",
    item: "763",
    maxLength: 3,
    name: "Segment Action Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70206",
  },
  {
    datatype: "CE",
    id: "AIG-3",
    item: "897",
    maxLength: 250,
    name: "Resource ID",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CE",
    id: "AIG-4",
    item: "898",
    maxLength: 250,
    name: "Resource Type",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "AIG-5",
    item: "899",
    maxLength: 250,
    name: "Resource Group",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "AIG-6",
    item: "900",
    maxLength: 5,
    name: "Resource Quantity",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "AIG-7",
    item: "901",
    maxLength: 250,
    name: "Resource Quantity Units",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "TS",
    id: "AIG-8",
    item: "1202",
    maxLength: 26,
    name: "Start Date/Time",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "NM",
    id: "AIG-9",
    item: "891",
    maxLength: 20,
    name: "Start Date/Time Offset",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CE",
    id: "AIG-10",
    item: "892",
    maxLength: 250,
    name: "Start Date/Time Offset Units",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "AIG-11",
    item: "893",
    maxLength: 20,
    name: "Duration",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CE",
    id: "AIG-12",
    item: "894",
    maxLength: 250,
    name: "Duration Units",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "IS",
    id: "AIG-13",
    item: "895",
    maxLength: 10,
    name: "Allow Substitution Code",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70279",
  },
  {
    datatype: "CE",
    id: "AIG-14",
    item: "889",
    maxLength: 250,
    name: "Filler Status Code",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70278",
  },
] as const;
