// Generated segment profile for DRG (v2.5)

export const segmentId = "DRG";
export const fields = [
  {
    datatype: "CE",
    id: "DRG-1",
    item: "382",
    maxLength: 250,
    name: "Diagnostic Related Group",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70055",
  },
  {
    datatype: "TS",
    id: "DRG-2",
    item: "769",
    maxLength: 26,
    name: "DRG Assigned Date/Time",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ID",
    id: "DRG-3",
    item: "383",
    maxLength: 1,
    name: "DRG Approval Indicator",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70136",
  },
  {
    datatype: "IS",
    id: "DRG-4",
    item: "384",
    maxLength: 2,
    name: "DRG Grouper Review Code",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70056",
  },
  {
    datatype: "CE",
    id: "DRG-5",
    item: "385",
    maxLength: 250,
    name: "Outlier Type",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70083",
  },
  {
    datatype: "NM",
    id: "DRG-6",
    item: "386",
    maxLength: 3,
    name: "Outlier Days",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CP",
    id: "DRG-7",
    item: "387",
    maxLength: 12,
    name: "Outlier Cost",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "IS",
    id: "DRG-8",
    item: "770",
    maxLength: 1,
    name: "DRG Payor",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70229",
  },
  {
    datatype: "CP",
    id: "DRG-9",
    item: "771",
    maxLength: 9,
    name: "Outlier Reimbursement",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "ID",
    id: "DRG-10",
    item: "767",
    maxLength: 1,
    name: "Confidential Indicator",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70136",
  },
  {
    datatype: "IS",
    id: "DRG-11",
    item: "1500",
    maxLength: 21,
    name: "DRG Transfer Type",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70415",
  },
] as const;
