// Generated segment profile for EDU (v2.5)

export const segmentId = "EDU";
export const fields = [
  {
    datatype: "SI",
    id: "EDU-1",
    item: "1448",
    maxLength: 60,
    name: "Set ID _ EDU",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "IS",
    id: "EDU-2",
    item: "1449",
    maxLength: 10,
    name: "Academic Degree",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70360",
  },
  {
    datatype: "DR",
    id: "EDU-3",
    item: "1597",
    maxLength: 52,
    name: "Academic Degree Program Date Range",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "DR",
    id: "EDU-4",
    item: "1450",
    maxLength: 52,
    name: "Academic Degree Program Participation Date Range",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "DT",
    id: "EDU-5",
    item: "1451",
    maxLength: 8,
    name: "Academic Degree Granted Date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "XON",
    id: "EDU-6",
    item: "1452",
    maxLength: 250,
    name: "School",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "CE",
    id: "EDU-7",
    item: "1453",
    maxLength: 250,
    name: "School Type Code",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70402",
  },
  {
    datatype: "XAD",
    id: "EDU-8",
    item: "1454",
    maxLength: 250,
    name: "School Address",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "EDU-9",
    item: "1885",
    maxLength: 250,
    name: "Major Field of Study",
    repeatable: true,
    required: false,
    sequence: 9,
  },
] as const;
