// Generated segment profile for IPC (v2.5)

export const segmentId = "IPC";
export const fields = [
  {
    sequence: 1,
    id: "IPC-1",
    required: true,
    repeatable: false,
    datatype: "EI",
    maxLength: 80,
    name: "Accession Identifier",
    item: "1330",
  },
  {
    sequence: 2,
    id: "IPC-2",
    required: true,
    repeatable: false,
    datatype: "EI",
    maxLength: 22,
    name: "Requested Procedure ID",
    item: "1658",
  },
  {
    sequence: 3,
    id: "IPC-3",
    required: true,
    repeatable: false,
    datatype: "EI",
    maxLength: 70,
    name: "Study Instance UID",
    item: "1659",
  },
  {
    sequence: 4,
    id: "IPC-4",
    required: true,
    repeatable: false,
    datatype: "EI",
    maxLength: 22,
    name: "Scheduled Procedure Step ID",
    item: "1660",
  },
  {
    sequence: 5,
    id: "IPC-5",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 16,
    name: "Modality",
    item: "1661",
  },
  {
    sequence: 6,
    id: "IPC-6",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    name: "Protocol Code",
    item: "1662",
  },
  {
    sequence: 7,
    id: "IPC-7",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 22,
    name: "Scheduled Station Name",
    item: "1663",
  },
  {
    sequence: 8,
    id: "IPC-8",
    required: false,
    repeatable: true,
    datatype: "CE",
    maxLength: 250,
    name: "Scheduled Procedure Step Location",
    item: "1664",
  },
  {
    sequence: 9,
    id: "IPC-9",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 16,
    name: "Scheduled AE Title",
    item: "1665",
  },
] as const;
