// Generated segment profile for ORC (v2.5)

export const segmentId = "ORC";
export const fields = [
  {
    datatype: "ID",
    id: "ORC-1",
    item: "215",
    maxLength: 2,
    name: "Order Control",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70119",
  },
  {
    datatype: "EI",
    id: "ORC-2",
    item: "216",
    maxLength: 22,
    name: "Placer Order Number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "ORC-3",
    item: "217",
    maxLength: 22,
    name: "Filler Order Number",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "ORC-4",
    item: "218",
    maxLength: 22,
    name: "Placer Group Number",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "ID",
    id: "ORC-5",
    item: "219",
    maxLength: 2,
    name: "Order Status",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70038",
  },
  {
    datatype: "ID",
    id: "ORC-6",
    item: "220",
    maxLength: 1,
    name: "Response Flag",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70121",
  },
  {
    datatype: "TQ",
    id: "ORC-7",
    item: "221",
    maxLength: 200,
    name: "Quantity/Timing",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "EIP",
    id: "ORC-8",
    item: "222",
    maxLength: 200,
    name: "Parent",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "TS",
    id: "ORC-9",
    item: "223",
    maxLength: 26,
    name: "Date/Time of Transaction",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XCN",
    id: "ORC-10",
    item: "224",
    maxLength: 250,
    name: "Entered By",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XCN",
    id: "ORC-11",
    item: "225",
    maxLength: 250,
    name: "Verified By",
    repeatable: true,
    required: false,
    sequence: 11,
  },
  {
    datatype: "XCN",
    id: "ORC-12",
    item: "226",
    maxLength: 250,
    name: "Ordering Provider",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "PL",
    id: "ORC-13",
    item: "227",
    maxLength: 80,
    name: "Enterer&apos;s Location",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "XTN",
    id: "ORC-14",
    item: "228",
    maxLength: 250,
    name: "Call Back Phone Number",
    repeatable: true,
    required: false,
    sequence: 14,
  },
  {
    datatype: "TS",
    id: "ORC-15",
    item: "229",
    maxLength: 26,
    name: "Order Effective Date/Time",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CE",
    id: "ORC-16",
    item: "230",
    maxLength: 250,
    name: "Order Control Code Reason",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CE",
    id: "ORC-17",
    item: "231",
    maxLength: 250,
    name: "Entering Organization",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CE",
    id: "ORC-18",
    item: "232",
    maxLength: 250,
    name: "Entering Device",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "XCN",
    id: "ORC-19",
    item: "233",
    maxLength: 250,
    name: "Action By",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CE",
    id: "ORC-20",
    item: "1310",
    maxLength: 250,
    name: "Advanced Beneficiary Notice Code",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70339",
  },
  {
    datatype: "XON",
    id: "ORC-21",
    item: "1311",
    maxLength: 250,
    name: "Ordering Facility Name",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "XAD",
    id: "ORC-22",
    item: "1312",
    maxLength: 250,
    name: "Ordering Facility Address",
    repeatable: true,
    required: false,
    sequence: 22,
  },
  {
    datatype: "XTN",
    id: "ORC-23",
    item: "1313",
    maxLength: 250,
    name: "Ordering Facility Phone Number",
    repeatable: true,
    required: false,
    sequence: 23,
  },
  {
    datatype: "XAD",
    id: "ORC-24",
    item: "1314",
    maxLength: 250,
    name: "Ordering Provider Address",
    repeatable: true,
    required: false,
    sequence: 24,
  },
  {
    datatype: "CWE",
    id: "ORC-25",
    item: "1473",
    maxLength: 250,
    name: "Order Status Modifier",
    repeatable: false,
    required: false,
    sequence: 25,
  },
  {
    datatype: "CWE",
    id: "ORC-26",
    item: "1641",
    maxLength: 60,
    name: "Advanced Beneficiary Notice Override Reason",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70552",
  },
  {
    datatype: "TS",
    id: "ORC-27",
    item: "1642",
    maxLength: 26,
    name: "Filler&apos;s Expected Availability Date/Time",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "CWE",
    id: "ORC-28",
    item: "615",
    maxLength: 250,
    name: "Confidentiality Code",
    repeatable: false,
    required: false,
    sequence: 28,
    table: "HL70177",
  },
  {
    datatype: "CWE",
    id: "ORC-29",
    item: "1643",
    maxLength: 250,
    name: "Order Type",
    repeatable: false,
    required: false,
    sequence: 29,
    table: "HL70482",
  },
  {
    datatype: "CNE",
    id: "ORC-30",
    item: "1644",
    maxLength: 250,
    name: "Enterer Authorization Mode",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70483",
  },
] as const;
