// Generated segment profile for OVR (v2.5)

export const segmentId = "OVR";
export const fields = [
  {
    datatype: "CWE",
    id: "OVR-1",
    item: "1829",
    maxLength: 705,
    name: "Business Rule Override Type",
    repeatable: false,
    required: false,
    sequence: 1,
    table: "HL70518",
  },
  {
    datatype: "CWE",
    id: "OVR-2",
    item: "1830",
    maxLength: 705,
    name: "Business Rule Override Code",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70521",
  },
  {
    datatype: "TX",
    id: "OVR-3",
    item: "1831",
    maxLength: 200,
    name: "Override Comments",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "XCN",
    id: "OVR-4",
    item: "1832",
    maxLength: 250,
    name: "Override Entered By",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XCN",
    id: "OVR-5",
    item: "1833",
    maxLength: 250,
    name: "Override Authorized By",
    repeatable: false,
    required: false,
    sequence: 5,
  },
] as const;
