// Generated segment profile for PCR (v2.5)

export const segmentId = "PCR";
export const fields = [
  {
    datatype: "CE",
    id: "PCR-1",
    item: "1098",
    maxLength: 250,
    name: "Implicated Product",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "IS",
    id: "PCR-2",
    item: "1099",
    maxLength: 1,
    name: "Generic Product",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70249",
  },
  {
    datatype: "CE",
    id: "PCR-3",
    item: "1100",
    maxLength: 250,
    name: "Product Class",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CQ",
    id: "PCR-4",
    item: "1101",
    maxLength: 8,
    name: "Total Duration Of Therapy",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "TS",
    id: "PCR-5",
    item: "1102",
    maxLength: 26,
    name: "Product Manufacture Date",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TS",
    id: "PCR-6",
    item: "1103",
    maxLength: 26,
    name: "Product Expiration Date",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "TS",
    id: "PCR-7",
    item: "1104",
    maxLength: 26,
    name: "Product Implantation Date",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "TS",
    id: "PCR-8",
    item: "1105",
    maxLength: 26,
    name: "Product Explantation Date",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "IS",
    id: "PCR-9",
    item: "1106",
    maxLength: 8,
    name: "Single Use Device",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70244",
  },
  {
    datatype: "CE",
    id: "PCR-10",
    item: "1107",
    maxLength: 250,
    name: "Indication For Product Use",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "IS",
    id: "PCR-11",
    item: "1108",
    maxLength: 8,
    name: "Product Problem",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70245",
  },
  {
    datatype: "ST",
    id: "PCR-12",
    item: "1109",
    maxLength: 30,
    name: "Product Serial/Lot Number",
    repeatable: true,
    required: false,
    sequence: 12,
  },
  {
    datatype: "IS",
    id: "PCR-13",
    item: "1110",
    maxLength: 1,
    name: "Product Available For Inspection",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70246",
  },
  {
    datatype: "CE",
    id: "PCR-14",
    item: "1111",
    maxLength: 250,
    name: "Product Evaluation Performed",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "CE",
    id: "PCR-15",
    item: "1112",
    maxLength: 250,
    name: "Product Evaluation Status",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70247",
  },
  {
    datatype: "CE",
    id: "PCR-16",
    item: "1113",
    maxLength: 250,
    name: "Product Evaluation Results",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ID",
    id: "PCR-17",
    item: "1114",
    maxLength: 8,
    name: "Evaluated Product Source",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70248",
  },
  {
    datatype: "TS",
    id: "PCR-18",
    item: "1115",
    maxLength: 26,
    name: "Date Product Returned To Manufacturer",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "ID",
    id: "PCR-19",
    item: "1116",
    maxLength: 1,
    name: "Device Operator Qualifications",
    repeatable: false,
    required: false,
    sequence: 19,
    table: "HL70242",
  },
  {
    datatype: "ID",
    id: "PCR-20",
    item: "1117",
    maxLength: 1,
    name: "Relatedness Assessment",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70250",
  },
  {
    datatype: "ID",
    id: "PCR-21",
    item: "1118",
    maxLength: 2,
    name: "Action Taken In Response To The Event",
    repeatable: true,
    required: false,
    sequence: 21,
    table: "HL70251",
  },
  {
    datatype: "ID",
    id: "PCR-22",
    item: "1119",
    maxLength: 2,
    name: "Event Causality Observations",
    repeatable: true,
    required: false,
    sequence: 22,
    table: "HL70252",
  },
  {
    datatype: "ID",
    id: "PCR-23",
    item: "1120",
    maxLength: 1,
    name: "Indirect Exposure Mechanism",
    repeatable: true,
    required: false,
    sequence: 23,
    table: "HL70253",
  },
] as const;
