// Generated segment profile for PTH (v2.5)

export const segmentId = "PTH";
export const fields = [
  {
    datatype: "ID",
    id: "PTH-1",
    item: "816",
    maxLength: 2,
    name: "Action Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70287",
  },
  {
    datatype: "CE",
    id: "PTH-2",
    item: "1207",
    maxLength: 250,
    name: "Pathway ID",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "EI",
    id: "PTH-3",
    item: "1208",
    maxLength: 60,
    name: "Pathway Instance ID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "TS",
    id: "PTH-4",
    item: "1209",
    maxLength: 26,
    name: "Pathway Established Date/Time",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "PTH-5",
    item: "1210",
    maxLength: 250,
    name: "Pathway Life Cycle Status",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "TS",
    id: "PTH-6",
    item: "1211",
    maxLength: 26,
    name: "Change Pathway Life Cycle Status Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
] as const;
