// Generated segment profile for RXD (v2.5)

export const segmentId = "RXD";
export const fields = [
  {
    datatype: "NM",
    id: "RXD-1",
    item: "334",
    maxLength: 4,
    name: "Dispense Sub-ID Counter",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CE",
    id: "RXD-2",
    item: "335",
    maxLength: 250,
    name: "Dispense/Give Code",
    repeatable: false,
    required: true,
    sequence: 2,
    table: "HL70292",
  },
  {
    datatype: "TS",
    id: "RXD-3",
    item: "336",
    maxLength: 26,
    name: "Date/Time Dispensed",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "RXD-4",
    item: "337",
    maxLength: 20,
    name: "Actual Dispense Amount",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CE",
    id: "RXD-5",
    item: "338",
    maxLength: 250,
    name: "Actual Dispense Units",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CE",
    id: "RXD-6",
    item: "339",
    maxLength: 250,
    name: "Actual Dosage Form",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "RXD-7",
    item: "325",
    maxLength: 20,
    name: "Prescription Number",
    repeatable: false,
    required: true,
    sequence: 7,
  },
  {
    datatype: "NM",
    id: "RXD-8",
    item: "326",
    maxLength: 20,
    name: "Number of Refills Remaining",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "RXD-9",
    item: "340",
    maxLength: 200,
    name: "Dispense Notes",
    repeatable: true,
    required: false,
    sequence: 9,
  },
  {
    datatype: "XCN",
    id: "RXD-10",
    item: "341",
    maxLength: 200,
    name: "Dispensing Provider",
    repeatable: true,
    required: false,
    sequence: 10,
  },
  {
    datatype: "ID",
    id: "RXD-11",
    item: "322",
    maxLength: 1,
    name: "Substitution Status",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70167",
  },
  {
    datatype: "CQ",
    id: "RXD-12",
    item: "329",
    maxLength: 10,
    name: "Total Daily Dose",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "LA2",
    id: "RXD-13",
    item: "1303",
    maxLength: 200,
    name: "Dispense-to Location",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "ID",
    id: "RXD-14",
    item: "307",
    maxLength: 1,
    name: "Needs Human Review",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70136",
  },
  {
    datatype: "CE",
    id: "RXD-15",
    item: "330",
    maxLength: 250,
    name: "Pharmacy/Treatment Supplier&apos;s Special Dispensing Instructions",
    repeatable: true,
    required: false,
    sequence: 15,
  },
  {
    datatype: "NM",
    id: "RXD-16",
    item: "1132",
    maxLength: 20,
    name: "Actual Strength",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CE",
    id: "RXD-17",
    item: "1133",
    maxLength: 250,
    name: "Actual Strength Unit",
    repeatable: false,
    required: false,
    sequence: 17,
  },
  {
    datatype: "ST",
    id: "RXD-18",
    item: "1129",
    maxLength: 20,
    name: "Substance Lot Number",
    repeatable: true,
    required: false,
    sequence: 18,
  },
  {
    datatype: "TS",
    id: "RXD-19",
    item: "1130",
    maxLength: 26,
    name: "Substance Expiration Date",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CE",
    id: "RXD-20",
    item: "1131",
    maxLength: 250,
    name: "Substance Manufacturer Name",
    repeatable: true,
    required: false,
    sequence: 20,
    table: "HL70227",
  },
  {
    datatype: "CE",
    id: "RXD-21",
    item: "1123",
    maxLength: 250,
    name: "Indication",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "NM",
    id: "RXD-22",
    item: "1220",
    maxLength: 20,
    name: "Dispense Package Size",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "CE",
    id: "RXD-23",
    item: "1221",
    maxLength: 250,
    name: "Dispense Package Size Unit",
    repeatable: false,
    required: false,
    sequence: 23,
  },
  {
    datatype: "ID",
    id: "RXD-24",
    item: "1222",
    maxLength: 2,
    name: "Dispense Package Method",
    repeatable: false,
    required: false,
    sequence: 24,
    table: "HL70321",
  },
  {
    datatype: "CE",
    id: "RXD-25",
    item: "1476",
    maxLength: 250,
    name: "Supplementary Code",
    repeatable: true,
    required: false,
    sequence: 25,
  },
  {
    datatype: "CE",
    id: "RXD-26",
    item: "1477",
    maxLength: 250,
    name: "Initiating Location",
    repeatable: false,
    required: false,
    sequence: 26,
  },
  {
    datatype: "CE",
    id: "RXD-27",
    item: "1478",
    maxLength: 250,
    name: "Packaging/Assembly Location",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "NM",
    id: "RXD-28",
    item: "1686",
    maxLength: 5,
    name: "Actual Drug Strength Volume",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "CWE",
    id: "RXD-29",
    item: "1687",
    maxLength: 250,
    name: "Actual Drug Strength Volume Units",
    repeatable: false,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CWE",
    id: "RXD-30",
    item: "1688",
    maxLength: 180,
    name: "Dispense to Pharmacy",
    repeatable: false,
    required: false,
    sequence: 30,
  },
  {
    datatype: "XAD",
    id: "RXD-31",
    item: "1689",
    maxLength: 106,
    name: "Dispense to Pharmacy Address",
    repeatable: false,
    required: false,
    sequence: 31,
  },
  {
    datatype: "ID",
    id: "RXD-32",
    item: "1690",
    maxLength: 1,
    name: "Pharmacy Order Type",
    repeatable: false,
    required: false,
    sequence: 32,
    table: "HL70480",
  },
  {
    datatype: "CWE",
    id: "RXD-33",
    item: "1691",
    maxLength: 250,
    name: "Dispense Type",
    repeatable: false,
    required: false,
    sequence: 33,
    table: "HL70484",
  },
] as const;
