// Generated segment profile for MSA (v2.8.1)

export const segmentId = "MSA";
export const fields = [
  {
    sequence: 1,
    id: "MSA-1",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 2,
    table: "HL70008",
    name: "Acknowledgment Code",
    item: "18",
  },
  {
    sequence: 2,
    id: "MSA-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 199,
    name: "Message Control ID",
    item: "10",
  },
  {
    sequence: 3,
    id: "MSA-4",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Expected Sequence Number",
    item: "21",
  },
  {
    sequence: 4,
    id: "MSA-7",
    required: false,
    repeatable: false,
    datatype: "NM",
    name: "Message Waiting Number",
    item: "1827",
  },
  {
    sequence: 5,
    id: "MSA-8",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70520",
    name: "Message Waiting Priority",
    item: "1828",
  },
] as const;
