// Generated segment profile for PDC (v2.8.1)

export const segmentId = "PDC";
export const fields = [
  {
    sequence: 1,
    id: "PDC-1",
    required: true,
    repeatable: true,
    datatype: "XON",
    name: "Manufacturer/Distributor",
    item: "1247",
  },
  {
    sequence: 2,
    id: "PDC-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    name: "Country",
    item: "1248",
  },
  {
    sequence: 3,
    id: "PDC-3",
    required: true,
    repeatable: false,
    datatype: "ST",
    name: "Brand Name",
    item: "1249",
  },
  {
    sequence: 4,
    id: "PDC-4",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Device Family Name",
    item: "1250",
  },
  {
    sequence: 5,
    id: "PDC-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Generic Name",
    item: "1251",
  },
  {
    sequence: 6,
    id: "PDC-6",
    required: false,
    repeatable: true,
    datatype: "ST",
    name: "Model Identifier",
    item: "1252",
  },
  {
    sequence: 7,
    id: "PDC-7",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Catalogue Identifier",
    item: "1253",
  },
  {
    sequence: 8,
    id: "PDC-8",
    required: false,
    repeatable: true,
    datatype: "ST",
    name: "Other Identifier",
    item: "1254",
  },
  {
    sequence: 9,
    id: "PDC-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    name: "Product Code",
    item: "1255",
  },
  {
    sequence: 10,
    id: "PDC-10",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 4,
    table: "HL70330",
    name: "Marketing Basis",
    item: "1256",
  },
  {
    sequence: 11,
    id: "PDC-11",
    required: false,
    repeatable: false,
    datatype: "ST",
    name: "Marketing Approval ID",
    item: "1257",
  },
  {
    sequence: 12,
    id: "PDC-12",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Labeled Shelf Life",
    item: "1258",
  },
  {
    sequence: 13,
    id: "PDC-13",
    required: false,
    repeatable: false,
    datatype: "CQ",
    name: "Expected Shelf Life",
    item: "1259",
  },
  {
    sequence: 14,
    id: "PDC-14",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Date First Marketed",
    item: "1260",
  },
  {
    sequence: 15,
    id: "PDC-15",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Date Last Marketed",
    item: "1261",
  },
] as const;
