// Generated segment profile for RF1 (v2.8.1)

export const segmentId = "RF1";
export const fields = [
  {
    sequence: 1,
    id: "RF1-1",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70283",
    name: "Referral Status",
    item: "1137",
  },
  {
    sequence: 2,
    id: "RF1-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70280",
    name: "Referral Priority",
    item: "1138",
  },
  {
    sequence: 3,
    id: "RF1-3",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70281",
    name: "Referral Type",
    item: "1139",
  },
  {
    sequence: 4,
    id: "RF1-4",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70282",
    name: "Referral Disposition",
    item: "1140",
  },
  {
    sequence: 5,
    id: "RF1-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70284",
    name: "Referral Category",
    item: "1141",
  },
  {
    sequence: 6,
    id: "RF1-6",
    required: true,
    repeatable: false,
    datatype: "EI",
    name: "Originating Referral Identifier",
    item: "1142",
  },
  {
    sequence: 7,
    id: "RF1-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Effective Date",
    item: "1143",
  },
  {
    sequence: 8,
    id: "RF1-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Expiration Date",
    item: "1144",
  },
  {
    sequence: 9,
    id: "RF1-9",
    required: false,
    repeatable: false,
    datatype: "DTM",
    name: "Process Date",
    item: "1145",
  },
  {
    sequence: 10,
    id: "RF1-10",
    required: false,
    repeatable: true,
    datatype: "CWE",
    table: "HL70336",
    name: "Referral Reason",
    item: "1228",
  },
  {
    sequence: 11,
    id: "RF1-11",
    required: false,
    repeatable: true,
    datatype: "EI",
    name: "External Referral Identifier",
    item: "1300",
  },
  {
    sequence: 12,
    id: "RF1-12",
    required: false,
    repeatable: false,
    datatype: "CWE",
    table: "HL70865",
    name: "Referral Documentation Completion Status",
    item: "2262",
  },
  {
    sequence: 13,
    id: "RF1-13",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Planned Treatment Stop Date",
    item: "3400",
  },
  {
    sequence: 14,
    id: "RF1-14",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Referral Reason Text",
    item: "3401",
  },
  {
    sequence: 15,
    id: "RF1-15",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 721,
    name: "Number of Authorized Treatments/Units",
    item: "3402",
  },
  {
    sequence: 16,
    id: "RF1-16",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 721,
    name: "Number of Used Treatments/Units",
    item: "3403",
  },
  {
    sequence: 17,
    id: "RF1-17",
    required: false,
    repeatable: false,
    datatype: "CQ",
    maxLength: 721,
    name: "Number of Schedule Treatments/Units",
    item: "3404",
  },
  {
    sequence: 18,
    id: "RF1-18",
    deprecated: true,
    required: false,
    repeatable: false,
    datatype: "MO",
    name: "Remaining Benefit Amount",
    item: "3405",
  },
  {
    sequence: 19,
    id: "RF1-19",
    required: false,
    repeatable: false,
    datatype: "XON",
    maxLength: 250,
    name: "Authorized Provider",
    item: "3406",
  },
  {
    sequence: 20,
    id: "RF1-20",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    name: "Authorized Health Professional",
    item: "3407",
  },
  {
    sequence: 21,
    id: "RF1-21",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 60,
    name: "Source Text",
    item: "3408",
  },
  {
    sequence: 22,
    id: "RF1-22",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Source Date",
    item: "3409",
  },
  {
    sequence: 23,
    id: "RF1-23",
    required: false,
    repeatable: false,
    datatype: "XTN",
    maxLength: 250,
    name: "Source Phone",
    item: "3410",
  },
  {
    sequence: 24,
    id: "RF1-24",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 250,
    name: "Comment",
    item: "3411",
  },
  {
    sequence: 25,
    id: "RF1-25",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70206",
    name: "Action Code",
    item: "3412",
  },
] as const;
