// Generated table profile for 0076 (v2.8.1)

export const id = "0076";
export const description = "Message Type";
export const type = "hl7";
export const codes = [
  { description: "General acknowledgment message", name: "ACK" },
  { description: "ADT response", name: "ADR" },
  { description: "ADT message", name: "ADT" },
  { description: "Add/change billing account", name: "BAR" },
  { description: "Blood product dispense status message", name: "BPS" },
  {
    description: "Blood product dispense status acknowledgement message",
    name: "BRP",
  },
  {
    description:
      "Blood product transfusion/disposition acknowledgement message",
    name: "BRT",
  },
  { description: "Blood product transfusion/disposition message", name: "BTS" },
  { description: "Collaborative Care Fetch", name: "CCF" },
  { description: "Collaborative Care Information", name: "CCI" },
  { description: "Collaborative Care Message", name: "CCM" },
  { description: "Collaborative Care Referral", name: "CCQ" },
  { description: "Collaborative Care Referral", name: "CCU" },
  { description: "Collaborative Care Referral", name: "CQU" },
  { description: "Clinical study registration message", name: "CRM" },
  { description: "Unsolicited study data message", name: "CSU" },
  { description: "Create Donor Record", name: "DBC" },
  { description: "Update Donor Record", name: "DBU" },
  { description: "Donor Eligibility", name: "DEL" },
  { description: "Donor Eligibility Observation", name: "DEO" },
  { description: "Donor Eligibility Request", name: "DER" },
  { description: "Detail financial transactions", name: "DFT" },
  { description: "Document response", name: "DOC" },
  { description: "Donation Procedure", name: "DPR" },
  { description: "Donor Request to Collect", name: "DRC" },
  { description: "Display response", name: "DSR" },
  { description: "Automated equipment command message", name: "EAC" },
  { description: "Automated equipment notification message", name: "EAN" },
  { description: "Automated equipment response message", name: "EAR" },
  { description: "Health Care Invoice", name: "EHC" },
  {
    description: "Automated equipment status update acknowledgment message",
    name: "ESR",
  },
  { description: "Automated equipment status update message", name: "ESU" },
  { description: "Automated equipment inventory request message", name: "INR" },
  { description: "Automated equipment inventory update message", name: "INU" },
  {
    description: "Automated equipment log/service request message",
    name: "LSR",
  },
  {
    description: "Automated equipment log/service update message",
    name: "LSU",
  },
  { description: "Medical document management", name: "MDM" },
  {
    description: "Master files delayed application acknowledgment",
    name: "MFD",
  },
  { description: "Master files application acknowledgment", name: "MFK" },
  { description: "Master files notification", name: "MFN" },
  { description: "Master files query", name: "MFQ" },
  { description: "Master files response", name: "MFR" },
  { description: "Application management data message", name: "NMD" },
  { description: "Application management query message", name: "NMQ" },
  { description: "Application management response message", name: "NMR" },
  { description: "Blood product order message", name: "OMB" },
  { description: "Dietary order", name: "OMD" },
  { description: "General clinical order message", name: "OMG" },
  { description: "Imaging order", name: "OMI" },
  { description: "Laboratory order message", name: "OML" },
  { description: "Non-stock requisition order message", name: "OMN" },
  { description: "Pharmacy/treatment order message", name: "OMP" },
  { description: "General order message with document payload", name: "OMQ" },
  { description: "Stock requisition order message", name: "OMS" },
  {
    description: "Population/Location-Based Laboratory Order Message",
    name: "OPL",
  },
  {
    description:
      "Population/Location-Based Laboratory Order Acknowledgment Message",
    name: "OPR",
  },
  {
    description:
      "Unsolicited Population/Location-Based Laboratory Observation Message",
    name: "OPU",
  },
  { description: "Observation Report Acknowledgment", name: "ORA" },
  { description: "Blood product order acknowledgement message", name: "ORB" },
  { description: "Dietary order acknowledgment message", name: "ORD" },
  { description: "Query for results of observation", name: "ORF" },
  { description: "General clinical order acknowledgment message", name: "ORG" },
  { description: "Imaging order acknowledgement message", name: "ORI" },
  {
    description: "Laboratory acknowledgment message (unsolicited)",
    name: "ORL",
  },
  { description: "Pharmacy/treatment order message", name: "ORM" },
  {
    description: "Non-stock requisition - General order acknowledgment message",
    name: "ORN",
  },
  {
    description: "Pharmacy/treatment order acknowledgment message",
    name: "ORP",
  },
  {
    description: "General order response message response to any ORM",
    name: "ORR",
  },
  {
    description: "Stock requisition - Order acknowledgment message",
    name: "ORS",
  },
  {
    description: "Unsolicited transmission of an observation message",
    name: "ORU",
  },
  {
    description: "General Order Message with Document Payload Acknowledgement",
    name: "ORX",
  },
  { description: "Specimen Shipment Message", name: "OSM" },
  { description: "Query response for order status", name: "OSQ" },
  { description: "Query response for order status", name: "OSR" },
  { description: "Order status update", name: "OSU" },
  { description: "Unsolicited laboratory observation message", name: "OUL" },
  { description: "Product experience message", name: "PEX" },
  { description: "Patient goal message", name: "PGL" },
  { description: "Patient insurance information", name: "PIN" },
  { description: "Add personnel record", name: "PMU" },
  { description: "Patient pathway message (goal-oriented)", name: "PPG" },
  { description: "Patient pathway message (problem-oriented)", name: "PPP" },
  { description: "Patient problem message", name: "PPR" },
  { description: "Patient pathway goal-oriented response", name: "PPT" },
  { description: "Patient goal response", name: "PPV" },
  { description: "Patient problem response", name: "PRR" },
  { description: "Patient pathway problem-oriented response", name: "PTR" },
  { description: "Query by parameter", name: "QBP" },
  { description: "Deferred query", name: "QCK" },
  { description: "Cancel query", name: "QCN" },
  { description: "Query, original mode", name: "QRY" },
  { description: "Create subscription", name: "QSB" },
  { description: "Cancel subscription/acknowledge message", name: "QSX" },
  { description: "Query for previous events", name: "QVR" },
  { description: "Pharmacy/treatment administration information", name: "RAR" },
  { description: "Pharmacy/treatment administration message", name: "RAS" },
  { description: "Return clinical information", name: "RCI" },
  { description: "Return clinical list", name: "RCL" },
  { description: "Pharmacy/treatment encoded order message", name: "RDE" },
  { description: "Pharmacy/treatment dispense information", name: "RDR" },
  { description: "Pharmacy/treatment dispense message", name: "RDS" },
  { description: "Display based response", name: "RDY" },
  { description: "Patient referral", name: "REF" },
  { description: "Pharmacy/treatment encoded order information", name: "RER" },
  { description: "Pharmacy/treatment dose information", name: "RGR" },
  { description: "Pharmacy/treatment give message", name: "RGV" },
  { description: "Pharmacy/treatment order response", name: "ROR" },
  { description: "Return patient authorization", name: "RPA" },
  { description: "Return patient information", name: "RPI" },
  { description: "Return patient display list", name: "RPL" },
  { description: "Return patient list", name: "RPR" },
  { description: "Request patient authorization", name: "RQA" },
  { description: "Request clinical information", name: "RQC" },
  { description: "Request patient information", name: "RQI" },
  { description: "Request patient demographics", name: "RQP" },
  {
    description: "Pharmacy/treatment administration acknowledgment message",
    name: "RRA",
  },
  {
    description: "Pharmacy/treatment dispense acknowledgment message",
    name: "RRD",
  },
  {
    description: "Pharmacy/treatment encoded order acknowledgment message",
    name: "RRE",
  },
  {
    description: "Pharmacy/treatment give acknowledgment message",
    name: "RRG",
  },
  { description: "Return referral information", name: "RRI" },
  { description: "Segment pattern response", name: "RSP" },
  { description: "Tabular response", name: "RTB" },
  {
    description: "Notification of Anti-Microbial Device Cycle Data",
    name: "SCN",
  },
  { description: "Notification of Anti-Microbial Device Data", name: "SDN" },
  {
    description: "Sterilization anti-microbial device data request",
    name: "SDR",
  },
  { description: "Schedule information unsolicited", name: "SIU" },
  { description: "Notification of New Sterilization Lot", name: "SLN" },
  { description: "Sterilization lot request", name: "SLR" },
  {
    description: "Sterilization anti-microbial device cycle data request",
    name: "SMD",
  },
  { description: "Schedule query message", name: "SQM" },
  { description: "Schedule query response", name: "SQR" },
  { description: "Schedule request message", name: "SRM" },
  { description: "Scheduled request response", name: "SRR" },
  { description: "Specimen status request message", name: "SSR" },
  { description: "Specimen status update message", name: "SSU" },
  { description: "Notification of Sterilization Configuration", name: "STC" },
  { description: "Sterilization item request", name: "STI" },
  { description: "Summary product experience report", name: "SUR" },
  { description: "Tabular data response", name: "TBR" },
  {
    description: "Automated equipment test code settings request message",
    name: "TCR",
  },
  {
    description: "Automated equipment test code settings update message",
    name: "TCU",
  },
  { description: "Unsolicited display update message", name: "UDM" },
  { description: "Query for vaccination record", name: "VXQ" },
  { description: "Vaccination record response", name: "VXR" },
  { description: "Unsolicited vaccination record update", name: "VXU" },
  {
    description: "Response for vaccination query with multiple PID matches",
    name: "VXX",
  },
] as const;
