// Generated table profile for 0496 (v2.8.1)

export const id = "0496";
export const description = "Consent Type";
export const type = "user";
export const codes = [
  {
    description:
      "Release of Information/MR / Authorization to Disclosure Protected Health Information",
    name: "001",
  },
  { description: "Medical Procedure (invasive)", name: "002" },
  { description: "Acknowledge Receipt of Privacy Notice", name: "003" },
  { description: "Abortion", name: "004" },
  { description: "Abortion/Laminaria", name: "005" },
  { description: "Accutane - Information", name: "006" },
  { description: "Accutane - Woman", name: "007" },
  { description: "Advanced Beneficiary Notice", name: "008" },
  { description: "AFP (Alpha Fetoprotein) Screening", name: "009" },
  { description: "Amniocentesis (consent & refusal)", name: "010" },
  { description: "Anatomical Gift (organ donation)", name: "011" },
  { description: "Anesthesia - Complications", name: "012" },
  { description: "Anesthesia - Questionnaire", name: "013" },
  { description: "Angiogram", name: "014" },
  { description: "Angioplasty", name: "015" },
  { description: "Anticancer Drugs", name: "016" },
  { description: "Antipsychotic Medications", name: "017" },
  { description: "Arthrogram", name: "018" },
  { description: "Autopsy", name: "019" },
  { description: "AZT Therapy", name: "020" },
  { description: "Biliary Drainage", name: "021" },
  { description: "Biliary Stone Extraction", name: "022" },
  { description: "Biopsy", name: "023" },
  { description: "Bleeding Time Test", name: "024" },
  { description: "Bronchogram", name: "025" },
  { description: "Cardiac Catheterization", name: "026" },
  { description: "Coronary Angiography", name: "027" },
  { description: '"""      """" w/o Surgery Capability"', name: "028" },
  { description: "Cataract Op/Implant of FDA Aprvd Lens", name: "029" },
  { description: "Cataract Op/Implant of Investigational Lens", name: "030" },
  { description: "Cataract Surgery", name: "031" },
  { description: "Cholera Immunization", name: "032" },
  { description: "Cholesterol Screening", name: "033" },
  { description: "Circumcision - Newborn", name: "034" },
  { description: "Colonoscopy", name: "035" },
  { description: "Contact Lenses", name: "036" },
  { description: "CT Scan - Cervical & Lumbar", name: "037" },
  { description: "CT Scan w/ IV Contrast Media into Vein", name: "038" },
  { description: "CVS (Chorionic Villus) Sampling", name: "039" },
  { description: "Cystospy", name: "040" },
  {
    description: "Disclosure of Protected Health Information to Family/Friends",
    name: "041",
  },
  { description: "D & C and Conization", name: "042" },
  { description: "Dacryocystogram", name: "043" },
  { description: "Diagnostic Isotope", name: "044" },
  { description: "Drainage of an Abscess", name: "045" },
  { description: "Drug Screening", name: "046" },
  { description: "Electronic Monitoring of Labor - Refusal", name: "047" },
  { description: "Endometrial Biopsy", name: "048" },
  { description: "Endoscopy/Sclerosis of Esophageal Varices", name: "049" },
  { description: "ERCP", name: "050" },
  { description: "Exposure to reportable Communicable Disease", name: "051" },
  { description: "External Version", name: "052" },
  { description: "Fluorescein Angioscopy", name: "053" },
  { description: "Hepatitis B - Consent/Declination", name: "054" },
  { description: "Herniogram", name: "055" },
  { description: "HIV Test - Consent Refusal", name: "056" },
  { description: "HIV Test - Disclosure", name: "057" },
  { description: "HIV Test - Prenatal", name: "058" },
  { description: "Home IV Treatment Program", name: "059" },
  { description: "Home Parenteral Treatment Program", name: "060" },
  { description: "Hysterectomy", name: "061" },
  { description: "Hysterosalpingogram", name: "062" },
  { description: "Injection Slip/ Consent", name: "063" },
  { description: "Intrauterine Device", name: "064" },
  { description: "Intrauterine Device/Sterilization", name: "065" },
  {
    description: "Intravascular Infusion of Streptokinase/Urokinase",
    name: "066",
  },
  { description: "Intravenous Cholangiogram", name: "067" },
  { description: "Intravenous Digital Angiography", name: "068" },
  { description: "Iodine Administration", name: "069" },
  { description: "ISG", name: "070" },
  { description: "IVP", name: "071" },
  { description: "Laser Photocoagulation", name: "072" },
  { description: "Laser treatment", name: "073" },
  { description: "Lithium Carbonate", name: "074" },
  { description: "Liver Biopsy", name: "075" },
  { description: "Lumbar Puncture", name: "076" },
  { description: "Lymphangiogram", name: "077" },
  { description: "MAO Inhibitors", name: "078" },
  { description: "Med, Psych, and/or Drug/Alcohol", name: "079" },
  { description: "Medical Treatment - Refusal", name: "080" },
  { description: "Morning-after Pill", name: "081" },
  { description: "MRI - Adult", name: "082" },
  { description: "MRI - Pediatric", name: "083" },
  { description: "Myelogram", name: "084" },
  { description: "Needle Biopsy", name: "085" },
  { description: "Needle Biopsy of Lung", name: "086" },
  { description: "Newborn Treatment and Release", name: "087" },
  { description: "Norplant Subdermal Birth Control Implant", name: "088" },
  { description: "Operations, Anesthesia, Transfusions", name: "089" },
  { description: "Oral Contraceptives", name: "090" },
  { description: "Organ Donation", name: "091" },
  { description: "Patient Permits, Consents", name: "092" },
  { description: "Patient Treatment Permit, Release & Admission", name: "093" },
  { description: "Penile Injections", name: "094" },
  { description: "Percutaneous Nephrostomy", name: "095" },
  { description: "Percutaneous Transhepatic Cholangiogram", name: "096" },
  { description: "Photographs", name: "097" },
  { description: "Photographs - Employee", name: "098" },
  { description: "Photographs - Medical Research", name: "099" },
  { description: "Photographs - news Media", name: "100" },
  { description: "Psychiatric Admission - Next of Kin", name: "101" },
  { description: "Psychiatric Information During Hospital Stay", name: "102" },
  { description: "Public Release of Information", name: "103" },
  { description: "Radiologic Procedure", name: "104" },
  { description: "Refusal of Treatment", name: "105" },
  { description: "Release of Body", name: "106" },
  { description: "Release of Limb", name: "107" },
  { description: "Rh Immune Globulin", name: "108" },
  { description: "Rights of Medical Research Participants", name: "109" },
  {
    description:
      "Request to Restrict Access/Disclosure to Medical Record/Protected Health Information",
    name: "110",
  },
  { description: "Request for Remain Anonymous", name: "111" },
  { description: "Seat Belt Exemption", name: "112" },
  { description: "Sialogram", name: "113" },
  { description: "Voiding Cystogram", name: "1137" },
  { description: "Sigmoidoscopy", name: "114" },
  { description: "Sterilization - Anesthesia & Medical Services", name: "115" },
  { description: "Sterilization -Federally Funded", name: "116" },
  { description: "Sterilization - Female", name: "117" },
  { description: "Sterilization - Laparoscopy/Pomeroy", name: "118" },
  { description: "Sterilization - Non-Federally Funded", name: "119" },
  { description: "Sterilization - Secondary", name: "120" },
  { description: "Tranquilizers", name: "121" },
  { description: "Transfer - Acknowledgement", name: "122" },
  { description: "Transfer - Authorization", name: "123" },
  { description: "Transfer Certification - Physician", name: "124" },
  { description: "Transfer/Discharge Request", name: "125" },
  { description: "Transfer for Non-Medical Reasons", name: "126" },
  { description: "Transfer - Interfaculty Neonatal", name: "127" },
  { description: "Transfer Refusal", name: "128" },
  { description: "Transfer Refusal of Further Treatment", name: "129" },
  { description: "Treadmill & EKG", name: "130" },
  { description: "Treadmill, Thallium-201", name: "131" },
  { description: "Typhoid", name: "132" },
  { description: "Use of Investigational Device", name: "133" },
  { description: "Use of Investigational Drug", name: "134" },
  { description: "Venogram", name: "135" },
  { description: "Videotape", name: "136" },
] as const;
