// Generated segment profile for BTX (v2.5)

export const segmentId = "BTX";
export const fields = [
  {
    sequence: 1,
    id: "BTX-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID _ BTX",
    item: "1735",
  },
  {
    sequence: 2,
    id: "BTX-2",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 22,
    name: "BC Donation ID",
    item: "1736",
  },
  {
    sequence: 3,
    id: "BTX-3",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 250,
    name: "BC Component",
    item: "1737",
  },
  {
    sequence: 4,
    id: "BTX-4",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 250,
    name: "BC Blood Group",
    item: "1738",
  },
  {
    sequence: 5,
    id: "BTX-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70512",
    name: "CP Commercial Product",
    item: "1739",
  },
  {
    sequence: 6,
    id: "BTX-6",
    required: false,
    repeatable: false,
    datatype: "XON",
    maxLength: 250,
    name: "CP Manufacturer",
    item: "1740",
  },
  {
    sequence: 7,
    id: "BTX-7",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 22,
    name: "CP Lot Number",
    item: "1741",
  },
  {
    sequence: 8,
    id: "BTX-8",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "BP Quantity",
    item: "1742",
  },
  {
    sequence: 9,
    id: "BTX-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "BP Amount",
    item: "1743",
  },
  {
    sequence: 10,
    id: "BTX-10",
    required: false,
    repeatable: false,
    datatype: "CE",
    maxLength: 250,
    name: "BP Units",
    item: "1744",
  },
  {
    sequence: 11,
    id: "BTX-11",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70513",
    name: "BP Transfusion/Disposition Status",
    item: "1745",
  },
  {
    sequence: 12,
    id: "BTX-12",
    required: true,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70511",
    name: "BP Message Status",
    item: "1746",
  },
  {
    sequence: 13,
    id: "BTX-13",
    required: true,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "BP Date/Time of Status",
    item: "1747",
  },
  {
    sequence: 14,
    id: "BTX-14",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    name: "BP Administrator",
    item: "1748",
  },
  {
    sequence: 15,
    id: "BTX-15",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 250,
    name: "BP Verifier",
    item: "1749",
  },
  {
    sequence: 16,
    id: "BTX-16",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "BP Transfusion Start Date/Time of Status",
    item: "1750",
  },
  {
    sequence: 17,
    id: "BTX-17",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "BP Transfusion End Date/Time of Status",
    item: "1751",
  },
  {
    sequence: 18,
    id: "BTX-18",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70514",
    name: "BP Adverse Reaction Type",
    item: "1752",
  },
  {
    sequence: 19,
    id: "BTX-19",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70515",
    name: "BP Transfusion Interrupted Reason",
    item: "1753",
  },
] as const;
