// Generated segment profile for CON (v2.5)

export const segmentId = "CON";
export const fields = [
  {
    sequence: 1,
    id: "CON-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set ID - CON",
    item: "1776",
  },
  {
    sequence: 2,
    id: "CON-2",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70496",
    name: "Consent Type",
    item: "1777",
  },
  {
    sequence: 3,
    id: "CON-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 40,
    name: "Consent Form ID",
    item: "1778",
  },
  {
    sequence: 4,
    id: "CON-4",
    required: false,
    repeatable: false,
    datatype: "EI",
    maxLength: 180,
    name: "Consent Form Number",
    item: "1779",
  },
  {
    sequence: 5,
    id: "CON-5",
    required: false,
    repeatable: true,
    datatype: "FT",
    maxLength: 65_536,
    name: "Consent Text",
    item: "1780",
  },
  {
    sequence: 6,
    id: "CON-6",
    required: false,
    repeatable: true,
    datatype: "FT",
    maxLength: 65_536,
    name: "Subject-specific Consent Text",
    item: "1781",
  },
  {
    sequence: 7,
    id: "CON-7",
    required: false,
    repeatable: true,
    datatype: "FT",
    maxLength: 65_536,
    name: "Consent Background",
    item: "1782",
  },
  {
    sequence: 8,
    id: "CON-8",
    required: false,
    repeatable: true,
    datatype: "FT",
    maxLength: 65_536,
    name: "Subject-specific Consent Background",
    item: "1783",
  },
  {
    sequence: 9,
    id: "CON-9",
    required: false,
    repeatable: true,
    datatype: "FT",
    maxLength: 65_536,
    name: "Consenter-imposed limitations",
    item: "1784",
  },
  {
    sequence: 10,
    id: "CON-10",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 2,
    table: "HL70497",
    name: "Consent Mode",
    item: "1785",
  },
  {
    sequence: 11,
    id: "CON-11",
    required: true,
    repeatable: false,
    datatype: "CNE",
    maxLength: 2,
    table: "HL70498",
    name: "Consent Status",
    item: "1786",
  },
  {
    sequence: 12,
    id: "CON-12",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Consent Discussion Date/Time",
    item: "1787",
  },
  {
    sequence: 13,
    id: "CON-13",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Consent Decision Date/Time",
    item: "1788",
  },
  {
    sequence: 14,
    id: "CON-14",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Consent Effective Date/Time",
    item: "1789",
  },
  {
    sequence: 15,
    id: "CON-15",
    required: false,
    repeatable: false,
    datatype: "TS",
    maxLength: 26,
    name: "Consent End Date/Time",
    item: "1790",
  },
  {
    sequence: 16,
    id: "CON-16",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Subject Competence Indicator",
    item: "1791",
  },
  {
    sequence: 17,
    id: "CON-17",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Translator Assistance Indicator",
    item: "1792",
  },
  {
    sequence: 18,
    id: "CON-18",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70296",
    name: "Language Translated To",
    item: "1793",
  },
  {
    sequence: 19,
    id: "CON-19",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Informational Material Supplied Indicator",
    item: "1794",
  },
  {
    sequence: 20,
    id: "CON-20",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70499",
    name: "Consent Bypass Reason",
    item: "1795",
  },
  {
    sequence: 21,
    id: "CON-21",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70500",
    name: "Consent Disclosure Level",
    item: "1796",
  },
  {
    sequence: 22,
    id: "CON-22",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70501",
    name: "Consent Non-disclosure Reason",
    item: "1797",
  },
  {
    sequence: 23,
    id: "CON-23",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70502",
    name: "Non-subject Consenter Reason",
    item: "1798",
  },
  {
    sequence: 24,
    id: "CON-24",
    required: true,
    repeatable: true,
    datatype: "XPN",
    maxLength: 250,
    name: "Consenter ID",
    item: "1909",
  },
  {
    sequence: 25,
    id: "CON-25",
    required: true,
    repeatable: true,
    datatype: "IS",
    maxLength: 100,
    table: "HL70548",
    name: "Relationship to Subject Table",
    item: "1898",
  },
] as const;
