// Generated segment profile for ADJ (v2.6)

export const segmentId = "ADJ";
export const fields = [
  {
    datatype: "EI",
    id: "ADJ-1",
    item: "2003",
    maxLength: 73,
    name: "Provider Adjustment Number",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "ADJ-2",
    item: "2004",
    maxLength: 73,
    name: "Payer Adjustment Number",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "SI",
    id: "ADJ-3",
    item: "2005",
    maxLength: 4,
    name: "Adjustment Sequence Number",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "IS",
    id: "ADJ-4",
    item: "2006",
    maxLength: 4,
    name: "Adjustment Category",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70564",
  },
  {
    datatype: "CP",
    id: "ADJ-5",
    item: "2007",
    maxLength: 254,
    name: "Adjustment Amount",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CQ",
    id: "ADJ-6",
    item: "2008",
    maxLength: 222,
    name: "Adjustment Quantity",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70560",
  },
  {
    datatype: "CWE",
    id: "ADJ-7",
    item: "2009",
    maxLength: 211,
    name: "Adjustment Reason PA",
    repeatable: true,
    required: false,
    sequence: 7,
    table: "HL70565",
  },
  {
    datatype: "ST",
    id: "ADJ-8",
    item: "2010",
    maxLength: 250,
    name: "Adjustment Description",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "NM",
    id: "ADJ-9",
    item: "2011",
    maxLength: 250,
    name: "Original Value",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "NM",
    id: "ADJ-10",
    item: "2012",
    maxLength: 250,
    name: "Substitute Value",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "IS",
    id: "ADJ-11",
    item: "2013",
    maxLength: 4,
    name: "Adjustment Action",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70569",
  },
  {
    datatype: "EI",
    id: "ADJ-12",
    item: "2014",
    maxLength: 73,
    name: "Provider Adjustment Number Cross Reference",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "EI",
    id: "ADJ-13",
    item: "2015",
    maxLength: 73,
    name: "Provider Product/Service Line Item Number Cross Reference",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DTM",
    id: "ADJ-14",
    item: "2016",
    maxLength: 26,
    name: "Adjustment Date",
    repeatable: false,
    required: true,
    sequence: 14,
  },
  {
    datatype: "XON",
    id: "ADJ-15",
    item: "2017",
    maxLength: 183,
    name: "Responsible Organization",
    repeatable: false,
    required: false,
    sequence: 15,
  },
] as const;
