// Generated segment profile for CNS (v2.6)

export const segmentId = "CNS";
export const fields = [
  {
    sequence: 1,
    id: "CNS-1",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Starting Notification Reference Number",
    item: "1402",
  },
  {
    sequence: 2,
    id: "CNS-2",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 20,
    name: "Ending Notification Reference Number",
    item: "1403",
  },
  {
    sequence: 3,
    id: "CNS-3",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Starting Notification Date/Time",
    item: "1404",
  },
  {
    sequence: 4,
    id: "CNS-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Ending Notification Date/Time",
    item: "1405",
  },
  {
    sequence: 5,
    id: "CNS-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    name: "Starting Notification Code",
    item: "1406",
  },
  {
    sequence: 6,
    id: "CNS-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    name: "Ending Notification Code",
    item: "1407",
  },
] as const;
