// Generated segment profile for CSR (v2.6)

export const segmentId = "CSR";
export const fields = [
  {
    datatype: "EI",
    id: "CSR-1",
    item: "1011",
    maxLength: 427,
    name: "Sponsor Study ID",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "CSR-2",
    item: "1036",
    maxLength: 427,
    name: "Alternate Study ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "CSR-3",
    item: "1037",
    maxLength: 705,
    name: "Institution Registering the Patient",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "CX",
    id: "CSR-4",
    item: "1038",
    maxLength: 1913,
    name: "Sponsor Patient ID",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "CX",
    id: "CSR-5",
    item: "1039",
    maxLength: 1913,
    name: "Alternate Patient ID - CSR",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "DTM",
    id: "CSR-6",
    item: "1040",
    maxLength: 24,
    name: "Date/Time of Patient Study Registration",
    repeatable: false,
    required: true,
    sequence: 6,
  },
  {
    datatype: "XCN",
    id: "CSR-7",
    item: "1041",
    maxLength: 3220,
    name: "Person Performing Study Registration",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "XCN",
    id: "CSR-8",
    item: "1042",
    maxLength: 3220,
    name: "Study Authorizing Provider",
    repeatable: true,
    required: true,
    sequence: 8,
  },
  {
    datatype: "DTM",
    id: "CSR-9",
    item: "1043",
    maxLength: 24,
    name: "Date/time Patient Study Consent Signed",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CWE",
    id: "CSR-10",
    item: "1044",
    maxLength: 705,
    name: "Patient Study Eligibility Status",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "DTM",
    id: "CSR-11",
    item: "1045",
    maxLength: 24,
    name: "Study Randomization Date/time",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "CSR-12",
    item: "1046",
    maxLength: 705,
    name: "Randomized Study Arm",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "CWE",
    id: "CSR-13",
    item: "1047",
    maxLength: 705,
    name: "Stratum for Study Randomization",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "CWE",
    id: "CSR-14",
    item: "1048",
    maxLength: 705,
    name: "Patient Evaluability Status",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "DTM",
    id: "CSR-15",
    item: "1049",
    maxLength: 24,
    name: "Date/time Ended Study",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CWE",
    id: "CSR-16",
    item: "1050",
    maxLength: 705,
    name: "Reason Ended Study",
    repeatable: false,
    required: false,
    sequence: 16,
  },
] as const;
