// Generated segment profile for EQU (v2.6)

export const segmentId = "EQU";
export const fields = [
  {
    datatype: "EI",
    id: "EQU-1",
    item: "1479",
    maxLength: 427,
    name: "Equipment Instance Identifier",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "DTM",
    id: "EQU-2",
    item: "1322",
    maxLength: 24,
    name: "Event Date/Time",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "EQU-3",
    item: "1323",
    maxLength: 705,
    name: "Equipment State",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70365",
  },
  {
    datatype: "CWE",
    id: "EQU-4",
    item: "1324",
    maxLength: 705,
    name: "Local/Remote Control State",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70366",
  },
  {
    datatype: "CWE",
    id: "EQU-5",
    item: "1325",
    maxLength: 705,
    name: "Alert Level",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70367",
  },
] as const;
