// Generated segment profile for GOL (v2.6)

export const segmentId = "GOL";
export const fields = [
  {
    datatype: "ID",
    id: "GOL-1",
    item: "816",
    maxLength: 2,
    name: "Action Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70287",
  },
  {
    datatype: "DTM",
    id: "GOL-2",
    item: "817",
    maxLength: 24,
    name: "Action Date/Time",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "CWE",
    id: "GOL-3",
    item: "818",
    maxLength: 705,
    name: "Goal ID",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "EI",
    id: "GOL-4",
    item: "819",
    maxLength: 60,
    name: "Goal Instance ID",
    repeatable: false,
    required: true,
    sequence: 4,
  },
  {
    datatype: "EI",
    id: "GOL-5",
    item: "820",
    maxLength: 60,
    name: "Episode of Care ID",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "GOL-6",
    item: "821",
    maxLength: 60,
    name: "Goal List Priority",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "GOL-7",
    item: "822",
    maxLength: 24,
    name: "Goal Established Date/Time",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DTM",
    id: "GOL-8",
    item: "824",
    maxLength: 24,
    name: "Expected Goal Achieve Date/Time",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "CWE",
    id: "GOL-9",
    item: "825",
    maxLength: 705,
    name: "Goal Classification",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CWE",
    id: "GOL-10",
    item: "826",
    maxLength: 705,
    name: "Goal Management Discipline",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "CWE",
    id: "GOL-11",
    item: "827",
    maxLength: 705,
    name: "Current Goal Review Status",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "DTM",
    id: "GOL-12",
    item: "828",
    maxLength: 24,
    name: "Current Goal Review Date/Time",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DTM",
    id: "GOL-13",
    item: "829",
    maxLength: 24,
    name: "Next Goal Review Date/Time",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DTM",
    id: "GOL-14",
    item: "830",
    maxLength: 24,
    name: "Previous Goal Review Date/Time",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "TQ",
    id: "GOL-15",
    item: "831",
    maxLength: 200,
    name: "Goal Review Interval",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "CWE",
    id: "GOL-16",
    item: "832",
    maxLength: 705,
    name: "Goal Evaluation",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "ST",
    id: "GOL-17",
    item: "833",
    maxLength: 300,
    name: "Goal Evaluation Comment",
    repeatable: true,
    required: false,
    sequence: 17,
  },
  {
    datatype: "CWE",
    id: "GOL-18",
    item: "834",
    maxLength: 705,
    name: "Goal Life Cycle Status",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "DTM",
    id: "GOL-19",
    item: "835",
    maxLength: 24,
    name: "Goal Life Cycle Status Date/Time",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "CWE",
    id: "GOL-20",
    item: "836",
    maxLength: 705,
    name: "Goal Target Type",
    repeatable: true,
    required: false,
    sequence: 20,
  },
  {
    datatype: "XPN",
    id: "GOL-21",
    item: "837",
    maxLength: 250,
    name: "Goal Target Name",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "CNE",
    id: "GOL-22",
    item: "2182",
    maxLength: 705,
    name: "Mood Code",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70725",
  },
] as const;
