// Generated segment profile for GT1 (v2.6)

export const segmentId = "GT1";
export const fields = [
  {
    datatype: "SI",
    id: "GT1-1",
    item: "405",
    maxLength: 4,
    name: "Set ID - GT1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CX",
    id: "GT1-2",
    item: "406",
    maxLength: 250,
    name: "Guarantor Number",
    repeatable: true,
    required: false,
    sequence: 2,
  },
  {
    datatype: "XPN",
    id: "GT1-3",
    item: "407",
    maxLength: 250,
    name: "Guarantor Name",
    repeatable: true,
    required: true,
    sequence: 3,
  },
  {
    datatype: "XPN",
    id: "GT1-4",
    item: "408",
    maxLength: 250,
    name: "Guarantor Spouse Name",
    repeatable: true,
    required: false,
    sequence: 4,
  },
  {
    datatype: "XAD",
    id: "GT1-5",
    item: "409",
    maxLength: 250,
    name: "Guarantor Address",
    repeatable: true,
    required: false,
    sequence: 5,
  },
  {
    datatype: "XTN",
    id: "GT1-6",
    item: "410",
    maxLength: 250,
    name: "Guarantor Ph Num - Home",
    repeatable: true,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XTN",
    id: "GT1-7",
    item: "411",
    maxLength: 250,
    name: "Guarantor Ph Num - Business",
    repeatable: true,
    required: false,
    sequence: 7,
  },
  {
    datatype: "DTM",
    id: "GT1-8",
    item: "412",
    maxLength: 24,
    name: "Guarantor Date/Time Of Birth",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "IS",
    id: "GT1-9",
    item: "413",
    maxLength: 1,
    name: "Guarantor Administrative Sex",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70001",
  },
  {
    datatype: "IS",
    id: "GT1-10",
    item: "414",
    maxLength: 2,
    name: "Guarantor Type",
    repeatable: false,
    required: false,
    sequence: 10,
    table: "HL70068",
  },
  {
    datatype: "CWE",
    id: "GT1-11",
    item: "415",
    maxLength: 250,
    name: "Guarantor Relationship",
    repeatable: false,
    required: false,
    sequence: 11,
    table: "HL70063",
  },
  {
    datatype: "ST",
    id: "GT1-12",
    item: "416",
    maxLength: 11,
    name: "Guarantor SSN",
    repeatable: false,
    required: false,
    sequence: 12,
  },
  {
    datatype: "DT",
    id: "GT1-13",
    item: "417",
    maxLength: 8,
    name: "Guarantor Date - Begin",
    repeatable: false,
    required: false,
    sequence: 13,
  },
  {
    datatype: "DT",
    id: "GT1-14",
    item: "418",
    maxLength: 8,
    name: "Guarantor Date - End",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "NM",
    id: "GT1-15",
    item: "419",
    maxLength: 2,
    name: "Guarantor Priority",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "XPN",
    id: "GT1-16",
    item: "420",
    maxLength: 250,
    name: "Guarantor Employer Name",
    repeatable: true,
    required: false,
    sequence: 16,
  },
  {
    datatype: "XAD",
    id: "GT1-17",
    item: "421",
    maxLength: 250,
    name: "Guarantor Employer Address",
    repeatable: true,
    required: false,
    sequence: 17,
  },
  {
    datatype: "XTN",
    id: "GT1-18",
    item: "422",
    maxLength: 250,
    name: "Guarantor Employer Phone Number",
    repeatable: true,
    required: false,
    sequence: 18,
  },
  {
    datatype: "CX",
    id: "GT1-19",
    item: "423",
    maxLength: 250,
    name: "Guarantor Employee ID Number",
    repeatable: true,
    required: false,
    sequence: 19,
  },
  {
    datatype: "IS",
    id: "GT1-20",
    item: "424",
    maxLength: 2,
    name: "Guarantor Employment Status",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70066",
  },
  {
    datatype: "XON",
    id: "GT1-21",
    item: "425",
    maxLength: 250,
    name: "Guarantor Organization Name",
    repeatable: true,
    required: false,
    sequence: 21,
  },
  {
    datatype: "ID",
    id: "GT1-22",
    item: "773",
    maxLength: 1,
    name: "Guarantor Billing Hold Flag",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "GT1-23",
    item: "774",
    maxLength: 250,
    name: "Guarantor Credit Rating Code",
    repeatable: false,
    required: false,
    sequence: 23,
    table: "HL70341",
  },
  {
    datatype: "DTM",
    id: "GT1-24",
    item: "775",
    maxLength: 24,
    name: "Guarantor Death Date And Time",
    repeatable: false,
    required: false,
    sequence: 24,
  },
  {
    datatype: "ID",
    id: "GT1-25",
    item: "776",
    maxLength: 1,
    name: "Guarantor Death Flag",
    repeatable: false,
    required: false,
    sequence: 25,
    table: "HL70136",
  },
  {
    datatype: "CWE",
    id: "GT1-26",
    item: "777",
    maxLength: 250,
    name: "Guarantor Charge Adjustment Code",
    repeatable: false,
    required: false,
    sequence: 26,
    table: "HL70218",
  },
  {
    datatype: "CP",
    id: "GT1-27",
    item: "778",
    maxLength: 10,
    name: "Guarantor Household Annual Income",
    repeatable: false,
    required: false,
    sequence: 27,
  },
  {
    datatype: "NM",
    id: "GT1-28",
    item: "779",
    maxLength: 3,
    name: "Guarantor Household Size",
    repeatable: false,
    required: false,
    sequence: 28,
  },
  {
    datatype: "CX",
    id: "GT1-29",
    item: "780",
    maxLength: 250,
    name: "Guarantor Employer ID Number",
    repeatable: true,
    required: false,
    sequence: 29,
  },
  {
    datatype: "CWE",
    id: "GT1-30",
    item: "781",
    maxLength: 250,
    name: "Guarantor Marital Status Code",
    repeatable: false,
    required: false,
    sequence: 30,
    table: "HL70002",
  },
  {
    datatype: "DT",
    id: "GT1-31",
    item: "782",
    maxLength: 8,
    name: "Guarantor Hire Effective Date",
    repeatable: false,
    required: false,
    sequence: 31,
  },
  {
    datatype: "DT",
    id: "GT1-32",
    item: "783",
    maxLength: 8,
    name: "Employment Stop Date",
    repeatable: false,
    required: false,
    sequence: 32,
  },
  {
    datatype: "IS",
    id: "GT1-33",
    item: "755",
    maxLength: 2,
    name: "Living Dependency",
    repeatable: false,
    required: false,
    sequence: 33,
    table: "HL70223",
  },
  {
    datatype: "IS",
    id: "GT1-34",
    item: "145",
    maxLength: 2,
    name: "Ambulatory Status",
    repeatable: true,
    required: false,
    sequence: 34,
    table: "HL70009",
  },
  {
    datatype: "CWE",
    id: "GT1-35",
    item: "129",
    maxLength: 705,
    name: "Citizenship",
    repeatable: true,
    required: false,
    sequence: 35,
    table: "HL70171",
  },
  {
    datatype: "CWE",
    id: "GT1-36",
    item: "118",
    maxLength: 705,
    name: "Primary Language",
    repeatable: false,
    required: false,
    sequence: 36,
    table: "HL70296",
  },
  {
    datatype: "IS",
    id: "GT1-37",
    item: "742",
    maxLength: 2,
    name: "Living Arrangement",
    repeatable: false,
    required: false,
    sequence: 37,
    table: "HL70220",
  },
  {
    datatype: "CWE",
    id: "GT1-38",
    item: "743",
    maxLength: 705,
    name: "Publicity Code",
    repeatable: false,
    required: false,
    sequence: 38,
    table: "HL70215",
  },
  {
    datatype: "ID",
    id: "GT1-39",
    item: "744",
    name: "Protection Indicator",
    repeatable: false,
    required: false,
    sequence: 39,
    table: "HL70136",
  },
  {
    datatype: "IS",
    id: "GT1-40",
    item: "745",
    maxLength: 2,
    name: "Student Indicator",
    repeatable: false,
    required: false,
    sequence: 40,
    table: "HL70231",
  },
  {
    datatype: "CWE",
    id: "GT1-41",
    item: "120",
    maxLength: 705,
    name: "Religion",
    repeatable: false,
    required: false,
    sequence: 41,
    table: "HL70006",
  },
  {
    datatype: "XPN",
    id: "GT1-42",
    item: "109",
    maxLength: 250,
    name: "Mother's Maiden Name",
    repeatable: true,
    required: false,
    sequence: 42,
  },
  {
    datatype: "CWE",
    id: "GT1-43",
    item: "739",
    name: "Nationality",
    repeatable: false,
    required: false,
    sequence: 43,
    table: "HL70212",
  },
  {
    datatype: "CWE",
    id: "GT1-44",
    item: "125",
    maxLength: 705,
    name: "Ethnic Group",
    repeatable: true,
    required: false,
    sequence: 44,
    table: "HL70189",
  },
  {
    datatype: "XPN",
    id: "GT1-45",
    item: "748",
    maxLength: 250,
    name: "Contact Person's Name",
    repeatable: true,
    required: false,
    sequence: 45,
  },
  {
    datatype: "XTN",
    id: "GT1-46",
    item: "749",
    maxLength: 250,
    name: "Contact Person's Telephone Number",
    repeatable: true,
    required: false,
    sequence: 46,
  },
  {
    datatype: "CWE",
    id: "GT1-47",
    item: "747",
    maxLength: 705,
    name: "Contact Reason",
    repeatable: false,
    required: false,
    sequence: 47,
    table: "HL70222",
  },
  {
    datatype: "IS",
    id: "GT1-48",
    item: "784",
    maxLength: 3,
    name: "Contact Relationship",
    repeatable: false,
    required: false,
    sequence: 48,
    table: "HL70063",
  },
  {
    datatype: "ST",
    id: "GT1-49",
    item: "785",
    maxLength: 20,
    name: "Job Title",
    repeatable: false,
    required: false,
    sequence: 49,
  },
  {
    datatype: "JCC",
    id: "GT1-50",
    item: "786",
    maxLength: 20,
    name: "Job Code/Class",
    repeatable: false,
    required: false,
    sequence: 50,
  },
  {
    datatype: "XON",
    id: "GT1-51",
    item: "1299",
    maxLength: 250,
    name: "Guarantor Employer's Organization Name",
    repeatable: true,
    required: false,
    sequence: 51,
  },
  {
    datatype: "IS",
    id: "GT1-52",
    item: "753",
    maxLength: 2,
    name: "Handicap",
    repeatable: false,
    required: false,
    sequence: 52,
    table: "HL70295",
  },
  {
    datatype: "IS",
    id: "GT1-53",
    item: "752",
    maxLength: 2,
    name: "Job Status",
    repeatable: false,
    required: false,
    sequence: 53,
    table: "HL70311",
  },
  {
    datatype: "FC",
    id: "GT1-54",
    item: "1231",
    maxLength: 50,
    name: "Guarantor Financial Class",
    repeatable: false,
    required: false,
    sequence: 54,
  },
  {
    datatype: "CWE",
    id: "GT1-55",
    item: "1291",
    maxLength: 250,
    name: "Guarantor Race",
    repeatable: true,
    required: false,
    sequence: 55,
    table: "HL70005",
  },
  {
    datatype: "ST",
    id: "GT1-56",
    item: "1851",
    maxLength: 250,
    name: "Guarantor Birth Place",
    repeatable: false,
    required: false,
    sequence: 56,
  },
  {
    datatype: "IS",
    id: "GT1-57",
    item: "146",
    maxLength: 2,
    name: "VIP Indicator",
    repeatable: false,
    required: false,
    sequence: 57,
    table: "HL70099",
  },
] as const;
