// Generated segment profile for IIM (v2.6)

export const segmentId = "IIM";
export const fields = [
  {
    sequence: 1,
    id: "IIM-1",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Primary Key Value - IIM",
    item: "1897",
  },
  {
    sequence: 2,
    id: "IIM-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Service Item Code",
    item: "1799",
  },
  {
    sequence: 3,
    id: "IIM-3",
    required: false,
    repeatable: false,
    datatype: "ST",
    maxLength: 250,
    name: "Inventory Lot Number",
    item: "1800",
  },
  {
    sequence: 4,
    id: "IIM-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Inventory Expiration Date",
    item: "1801",
  },
  {
    sequence: 5,
    id: "IIM-5",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Inventory Manufacturer Name",
    item: "1802",
  },
  {
    sequence: 6,
    id: "IIM-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Inventory Location",
    item: "1803",
  },
  {
    sequence: 7,
    id: "IIM-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Inventory Received Date",
    item: "1804",
  },
  {
    sequence: 8,
    id: "IIM-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Inventory Received Quantity",
    item: "1805",
  },
  {
    sequence: 9,
    id: "IIM-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Inventory Received Quantity Unit",
    item: "1806",
  },
  {
    sequence: 10,
    id: "IIM-10",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 12,
    name: "Inventory Received Item Cost",
    item: "1807",
  },
  {
    sequence: 11,
    id: "IIM-11",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Inventory On Hand Date",
    item: "1808",
  },
  {
    sequence: 12,
    id: "IIM-12",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Inventory On Hand Quantity",
    item: "1809",
  },
  {
    sequence: 13,
    id: "IIM-13",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Inventory On Hand Quantity Unit",
    item: "1810",
  },
  {
    sequence: 14,
    id: "IIM-14",
    required: false,
    repeatable: false,
    datatype: "CNE",
    maxLength: 705,
    table: "HL70088",
    name: "Procedure Code",
    item: "393",
  },
  {
    sequence: 15,
    id: "IIM-15",
    required: false,
    repeatable: true,
    datatype: "CNE",
    maxLength: 705,
    table: "HL70340",
    name: "Procedure Code Modifier",
    item: "1316",
  },
] as const;
