// Generated segment profile for ILT (v2.6)

export const segmentId = "ILT";
export const fields = [
  {
    sequence: 1,
    id: "ILT-1",
    required: true,
    repeatable: false,
    datatype: "SI",
    maxLength: 4,
    name: "Set Id - ILT",
    item: "2086",
  },
  {
    sequence: 2,
    id: "ILT-2",
    required: true,
    repeatable: false,
    datatype: "ST",
    maxLength: 250,
    name: "Inventory Lot Number",
    item: "1800",
  },
  {
    sequence: 3,
    id: "ILT-3",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Inventory Expiration Date",
    item: "1801",
  },
  {
    sequence: 4,
    id: "ILT-4",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Inventory Received Date",
    item: "1804",
  },
  {
    sequence: 5,
    id: "ILT-5",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Inventory Received Quantity",
    item: "1805",
  },
  {
    sequence: 6,
    id: "ILT-6",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Inventory Received Quantity Unit",
    item: "1806",
  },
  {
    sequence: 7,
    id: "ILT-7",
    required: false,
    repeatable: false,
    datatype: "MO",
    maxLength: 12,
    name: "Inventory Received Item Cost",
    item: "1807",
  },
  {
    sequence: 8,
    id: "ILT-8",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Inventory On Hand Date",
    item: "1808",
  },
  {
    sequence: 9,
    id: "ILT-9",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 12,
    name: "Inventory On Hand Quantity",
    item: "1809",
  },
  {
    sequence: 10,
    id: "ILT-10",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Inventory On Hand Quantity Unit",
    item: "1810",
  },
] as const;
