// Generated segment profile for MFE (v2.6)

export const segmentId = "MFE";
export const fields = [
  {
    datatype: "ID",
    id: "MFE-1",
    item: "664",
    maxLength: 3,
    name: "Record-Level Event Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70180",
  },
  {
    datatype: "ST",
    id: "MFE-2",
    item: "665",
    maxLength: 20,
    name: "MFN Control ID",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "DTM",
    id: "MFE-3",
    item: "662",
    maxLength: 24,
    name: "Effective Date/Time",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "varies",
    id: "MFE-4",
    item: "667",
    maxLength: 200,
    name: "Primary Key Value - MFE",
    repeatable: true,
    required: true,
    sequence: 4,
  },
  {
    datatype: "ID",
    id: "MFE-5",
    item: "1319",
    maxLength: 3,
    name: "Primary Key Value Type",
    repeatable: true,
    required: true,
    sequence: 5,
    table: "HL70355",
  },
  {
    datatype: "DTM",
    id: "MFE-6",
    item: "661",
    maxLength: 24,
    name: "Entered Date/Time",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "XCN",
    id: "MFE-7",
    item: "224",
    maxLength: 3220,
    name: "Entered By",
    repeatable: false,
    required: false,
    sequence: 7,
  },
] as const;
