// Generated segment profile for MSA (v2.6)

export const segmentId = "MSA";
export const fields = [
  {
    datatype: "ID",
    id: "MSA-1",
    item: "18",
    maxLength: 2,
    name: "Acknowledgment Code",
    repeatable: false,
    required: true,
    sequence: 1,
    table: "HL70008",
  },
  {
    datatype: "ST",
    id: "MSA-2",
    item: "10",
    maxLength: 199,
    name: "Message Control ID",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "MSA-3",
    item: "20",
    name: "Text Message",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "MSA-4",
    item: "21",
    maxLength: 15,
    name: "Expected Sequence Number",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "NUL",
    deprecated: true,
    id: "MSA-5",
    item: "22",
    name: "Delayed Acknowledgment Type",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CNE",
    id: "MSA-6",
    item: "23",
    name: "Error Condition",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70357",
  },
  {
    datatype: "NM",
    id: "MSA-7",
    item: "1827",
    maxLength: 5,
    name: "Message Waiting Number",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "ID",
    id: "MSA-8",
    item: "1828",
    maxLength: 1,
    name: "Message Waiting Priority",
    repeatable: false,
    required: false,
    sequence: 8,
    table: "HL70520",
  },
] as const;
