// Generated segment profile for OM7 (v2.6)

export const segmentId = "OM7";
export const fields = [
  {
    sequence: 1,
    id: "OM7-1",
    required: true,
    repeatable: false,
    datatype: "NM",
    maxLength: 4,
    name: "Sequence Number - Test/Observation Master File",
    item: "586",
  },
  {
    sequence: 2,
    id: "OM7-2",
    required: true,
    repeatable: false,
    datatype: "CWE",
    maxLength: 705,
    name: "Universal Service Identifier",
    item: "238",
  },
  {
    sequence: 3,
    id: "OM7-3",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70412",
    name: "Category Identifier",
    item: "1481",
  },
  {
    sequence: 4,
    id: "OM7-4",
    required: false,
    repeatable: false,
    datatype: "TX",
    maxLength: 200,
    name: "Category Description",
    item: "1482",
  },
  {
    sequence: 5,
    id: "OM7-5",
    required: false,
    repeatable: true,
    datatype: "ST",
    maxLength: 200,
    name: "Category Synonym",
    item: "1483",
  },
  {
    sequence: 6,
    id: "OM7-6",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Effective Test/Service Start Date/Time",
    item: "1484",
  },
  {
    sequence: 7,
    id: "OM7-7",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Effective Test/Service End Date/Time",
    item: "1485",
  },
  {
    sequence: 8,
    id: "OM7-8",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "Test/Service Default Duration Quantity",
    item: "1486",
  },
  {
    sequence: 9,
    id: "OM7-9",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    name: "Test/Service Default Duration Units",
    item: "1487",
  },
  {
    sequence: 10,
    id: "OM7-10",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 60,
    name: "Test/Service Default Frequency",
    item: "1488",
  },
  {
    sequence: 11,
    id: "OM7-11",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Consent Indicator",
    item: "1489",
  },
  {
    sequence: 12,
    id: "OM7-12",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70413",
    name: "Consent Identifier",
    item: "1490",
  },
  {
    sequence: 13,
    id: "OM7-13",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Consent Effective Start Date/Time",
    item: "1491",
  },
  {
    sequence: 14,
    id: "OM7-14",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Consent Effective End Date/Time",
    item: "1492",
  },
  {
    sequence: 15,
    id: "OM7-15",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "Consent Interval Quantity",
    item: "1493",
  },
  {
    sequence: 16,
    id: "OM7-16",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70414",
    name: "Consent Interval Units",
    item: "1494",
  },
  {
    sequence: 17,
    id: "OM7-17",
    required: false,
    repeatable: false,
    datatype: "NM",
    maxLength: 5,
    name: "Consent Waiting Period Quantity",
    item: "1495",
  },
  {
    sequence: 18,
    id: "OM7-18",
    required: false,
    repeatable: false,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70414",
    name: "Consent Waiting Period Units",
    item: "1496",
  },
  {
    sequence: 19,
    id: "OM7-19",
    required: false,
    repeatable: false,
    datatype: "DTM",
    maxLength: 24,
    name: "Effective Date/Time of Change",
    item: "607",
  },
  {
    sequence: 20,
    id: "OM7-20",
    required: false,
    repeatable: false,
    datatype: "XCN",
    maxLength: 3220,
    name: "Entered By",
    item: "224",
  },
  {
    sequence: 21,
    id: "OM7-21",
    required: false,
    repeatable: true,
    datatype: "PL",
    maxLength: 200,
    name: "Orderable-at Location",
    item: "1497",
  },
  {
    sequence: 22,
    id: "OM7-22",
    required: false,
    repeatable: false,
    datatype: "IS",
    maxLength: 1,
    table: "HL70473",
    name: "Formulary Status",
    item: "1498",
  },
  {
    sequence: 23,
    id: "OM7-23",
    required: false,
    repeatable: false,
    datatype: "ID",
    maxLength: 1,
    table: "HL70136",
    name: "Special Order Indicator",
    item: "1499",
  },
  {
    sequence: 24,
    id: "OM7-24",
    required: false,
    repeatable: true,
    datatype: "CWE",
    maxLength: 250,
    table: "HL70132",
    name: "Primary Key Value - CDM",
    item: "1306",
  },
] as const;
