// Generated segment profile for PKG (v2.6)

export const segmentId = "PKG";
export const fields = [
  {
    datatype: "SI",
    id: "PKG-1",
    item: "2221",
    maxLength: 2,
    name: "Set Id - PKG",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "CWE",
    id: "PKG-2",
    item: "2222",
    maxLength: 250,
    name: "Packaging Units",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70818",
  },
  {
    datatype: "CNE",
    id: "PKG-3",
    item: "2223",
    maxLength: 1,
    name: "Default Order Unit Of Measure Indicator",
    repeatable: false,
    required: false,
    sequence: 3,
    table: "HL70532",
  },
  {
    datatype: "NM",
    id: "PKG-4",
    item: "2224",
    maxLength: 12,
    name: "Package Quantity",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "CP",
    id: "PKG-5",
    item: "2225",
    maxLength: 12,
    name: "Price",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "CP",
    id: "PKG-6",
    item: "2226",
    maxLength: 12,
    name: "Future Item Price",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "DTM",
    id: "PKG-7",
    item: "2227",
    maxLength: 24,
    name: "Future Item Price Effective Date",
    repeatable: false,
    required: false,
    sequence: 7,
  },
] as const;
