// Generated segment profile for PMT (v2.6)

export const segmentId = "PMT";
export const fields = [
  {
    datatype: "EI",
    id: "PMT-1",
    item: "2018",
    maxLength: 73,
    name: "Payment/Remittance Advice Number",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "DTM",
    id: "PMT-2",
    item: "2019",
    maxLength: 26,
    name: "Payment/Remittance Effective Date/Time",
    repeatable: false,
    required: true,
    sequence: 2,
  },
  {
    datatype: "DTM",
    id: "PMT-3",
    item: "2020",
    maxLength: 26,
    name: "Payment/Remittance Expiration Date/Time",
    repeatable: false,
    required: true,
    sequence: 3,
  },
  {
    datatype: "CWE",
    id: "PMT-4",
    item: "2021",
    maxLength: 177,
    name: "Payment Method",
    repeatable: false,
    required: true,
    sequence: 4,
    table: "HL70570",
  },
  {
    datatype: "DTM",
    id: "PMT-5",
    item: "2022",
    maxLength: 26,
    name: "Payment/Remittance Date/Time",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "CP",
    id: "PMT-6",
    item: "2023",
    maxLength: 254,
    name: "Payment/Remittance Amount",
    repeatable: false,
    required: true,
    sequence: 6,
  },
  {
    datatype: "EI",
    id: "PMT-7",
    item: "2024",
    maxLength: 15,
    name: "Check Number",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "XON",
    id: "PMT-8",
    item: "2025",
    maxLength: 6,
    name: "Payee Bank Identification",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "ST",
    id: "PMT-9",
    item: "2026",
    maxLength: 4,
    name: "Payee Transit Number",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "CX",
    id: "PMT-10",
    item: "2027",
    maxLength: 20,
    name: "Payee Bank Account ID",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XON",
    id: "PMT-11",
    item: "2028",
    maxLength: 183,
    name: "Payment Organization",
    repeatable: false,
    required: true,
    sequence: 11,
  },
  {
    datatype: "ST",
    id: "PMT-12",
    item: "2029",
    maxLength: 100,
    name: "ESR-Code-Line",
    repeatable: false,
    required: false,
    sequence: 12,
  },
] as const;
