// Generated segment profile for PR1 (v2.6)

export const segmentId = "PR1";
export const fields = [
  {
    datatype: "SI",
    id: "PR1-1",
    item: "391",
    maxLength: 4,
    name: "Set ID - PR1",
    repeatable: false,
    required: true,
    sequence: 1,
  },
  {
    datatype: "IS",
    deprecated: true,
    id: "PR1-2",
    item: "392",
    maxLength: 3,
    name: "Procedure Coding Method",
    repeatable: false,
    required: false,
    sequence: 2,
    table: "HL70089",
  },
  {
    datatype: "CNE",
    id: "PR1-3",
    item: "393",
    maxLength: 705,
    name: "Procedure Code",
    repeatable: false,
    required: true,
    sequence: 3,
    table: "HL70088",
  },
  {
    datatype: "ST",
    deprecated: true,
    id: "PR1-4",
    item: "394",
    maxLength: 40,
    name: "Procedure Description",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "DTM",
    id: "PR1-5",
    item: "395",
    maxLength: 24,
    name: "Procedure Date/Time",
    repeatable: false,
    required: true,
    sequence: 5,
  },
  {
    datatype: "IS",
    id: "PR1-6",
    item: "396",
    maxLength: 2,
    name: "Procedure Functional Type",
    repeatable: false,
    required: false,
    sequence: 6,
    table: "HL70230",
  },
  {
    datatype: "NM",
    id: "PR1-7",
    item: "397",
    maxLength: 4,
    name: "Procedure Minutes",
    repeatable: false,
    required: false,
    sequence: 7,
  },
  {
    datatype: "XCN",
    deprecated: true,
    id: "PR1-8",
    item: "398",
    maxLength: 250,
    name: "Anesthesiologist",
    repeatable: true,
    required: false,
    sequence: 8,
    table: "HL70010",
  },
  {
    datatype: "IS",
    id: "PR1-9",
    item: "399",
    maxLength: 2,
    name: "Anesthesia Code",
    repeatable: false,
    required: false,
    sequence: 9,
    table: "HL70019",
  },
  {
    datatype: "NM",
    id: "PR1-10",
    item: "400",
    maxLength: 4,
    name: "Anesthesia Minutes",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "XCN",
    deprecated: true,
    id: "PR1-11",
    item: "401",
    maxLength: 250,
    name: "Surgeon",
    repeatable: true,
    required: false,
    sequence: 11,
    table: "HL70010",
  },
  {
    datatype: "XCN",
    deprecated: true,
    id: "PR1-12",
    item: "402",
    maxLength: 250,
    name: "Procedure Practitioner",
    repeatable: true,
    required: false,
    sequence: 12,
    table: "HL70010",
  },
  {
    datatype: "CWE",
    id: "PR1-13",
    item: "403",
    maxLength: 250,
    name: "Consent Code",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70059",
  },
  {
    datatype: "ID",
    id: "PR1-14",
    item: "404",
    maxLength: 2,
    name: "Procedure Priority",
    repeatable: false,
    required: false,
    sequence: 14,
    table: "HL70418",
  },
  {
    datatype: "CWE",
    id: "PR1-15",
    item: "772",
    maxLength: 250,
    name: "Associated Diagnosis Code",
    repeatable: false,
    required: false,
    sequence: 15,
    table: "HL70051",
  },
  {
    datatype: "CNE",
    id: "PR1-16",
    item: "1316",
    maxLength: 705,
    name: "Procedure Code Modifier",
    repeatable: true,
    required: false,
    sequence: 16,
    table: "HL70340",
  },
  {
    datatype: "IS",
    id: "PR1-17",
    item: "1501",
    maxLength: 20,
    name: "Procedure DRG Type",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70416",
  },
  {
    datatype: "CWE",
    id: "PR1-18",
    item: "1502",
    maxLength: 250,
    name: "Tissue Type Code",
    repeatable: true,
    required: false,
    sequence: 18,
    table: "HL70417",
  },
  {
    datatype: "EI",
    id: "PR1-19",
    item: "1848",
    maxLength: 427,
    name: "Procedure Identifier",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ID",
    id: "PR1-20",
    item: "1849",
    maxLength: 1,
    name: "Procedure Action Code",
    repeatable: false,
    required: false,
    sequence: 20,
    table: "HL70206",
  },
  {
    datatype: "IS",
    id: "PR1-21",
    item: "2177",
    maxLength: 20,
    name: "DRG Procedure Determination Status",
    repeatable: false,
    required: false,
    sequence: 21,
    table: "HL70761",
  },
  {
    datatype: "IS",
    id: "PR1-22",
    item: "2178",
    maxLength: 20,
    name: "DRG Procedure Relevance",
    repeatable: false,
    required: false,
    sequence: 22,
    table: "HL70763",
  },
] as const;
