// Generated segment profile for SDD (v2.6)

export const segmentId = "SDD";
export const fields = [
  {
    datatype: "EI",
    id: "SDD-1",
    item: "2098",
    maxLength: 11,
    name: "Lot Number",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "EI",
    id: "SDD-2",
    item: "2099",
    maxLength: 8,
    name: "Device Number",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "ST",
    id: "SDD-3",
    item: "2281",
    maxLength: 999,
    name: "Device Name",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "IS",
    id: "SDD-4",
    item: "2100",
    maxLength: 1,
    name: "Device Data State",
    repeatable: false,
    required: false,
    sequence: 4,
    table: "HL70667",
  },
  {
    datatype: "IS",
    id: "SDD-5",
    item: "2101",
    maxLength: 3,
    name: "Load Status",
    repeatable: false,
    required: false,
    sequence: 5,
    table: "HL70669",
  },
  {
    datatype: "NM",
    id: "SDD-6",
    item: "2102",
    maxLength: 3,
    name: "Control Code",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "ST",
    id: "SDD-7",
    item: "2103",
    maxLength: 15,
    name: "Operator Name",
    repeatable: false,
    required: false,
    sequence: 7,
  },
] as const;
