// Generated segment profile for UB1 (v2.6)

export const segmentId = "UB1";
export const fields = [
  {
    datatype: "SI",
    id: "UB1-1",
    item: "530",
    maxLength: 4,
    name: "Set ID - UB1",
    repeatable: false,
    required: false,
    sequence: 1,
  },
  {
    datatype: "NM",
    deprecated: true,
    id: "UB1-2",
    item: "531",
    maxLength: 1,
    name: "Blood Deductible  (43)",
    repeatable: false,
    required: false,
    sequence: 2,
  },
  {
    datatype: "NM",
    id: "UB1-3",
    item: "532",
    maxLength: 2,
    name: "Blood Furnished-Pints",
    repeatable: false,
    required: false,
    sequence: 3,
  },
  {
    datatype: "NM",
    id: "UB1-4",
    item: "533",
    maxLength: 2,
    name: "Blood Replaced-Pints",
    repeatable: false,
    required: false,
    sequence: 4,
  },
  {
    datatype: "NM",
    id: "UB1-5",
    item: "534",
    maxLength: 2,
    name: "Blood Not Replaced-Pints",
    repeatable: false,
    required: false,
    sequence: 5,
  },
  {
    datatype: "NM",
    id: "UB1-6",
    item: "535",
    name: "Co-Insurance Days",
    repeatable: false,
    required: false,
    sequence: 6,
  },
  {
    datatype: "IS",
    id: "UB1-7",
    item: "536",
    name: "Condition Code",
    repeatable: false,
    required: false,
    sequence: 7,
    table: "HL70043",
  },
  {
    datatype: "NM",
    id: "UB1-8",
    item: "537",
    name: "Covered Days",
    repeatable: false,
    required: false,
    sequence: 8,
  },
  {
    datatype: "NM",
    id: "UB1-9",
    item: "538",
    name: "Non Covered Days",
    repeatable: false,
    required: false,
    sequence: 9,
  },
  {
    datatype: "UVC",
    id: "UB1-10",
    item: "539",
    name: "Value Amount &amp; Code",
    repeatable: false,
    required: false,
    sequence: 10,
  },
  {
    datatype: "NM",
    id: "UB1-11",
    item: "540",
    maxLength: 2,
    name: "Number Of Grace Days",
    repeatable: false,
    required: false,
    sequence: 11,
  },
  {
    datatype: "CWE",
    id: "UB1-12",
    item: "541",
    maxLength: 250,
    name: "Special Program Indicator",
    repeatable: false,
    required: false,
    sequence: 12,
    table: "HL70348",
  },
  {
    datatype: "CWE",
    id: "UB1-13",
    item: "542",
    maxLength: 250,
    name: "PSRO/UR Approval Indicator",
    repeatable: false,
    required: false,
    sequence: 13,
    table: "HL70349",
  },
  {
    datatype: "DT",
    id: "UB1-14",
    item: "543",
    maxLength: 8,
    name: "PSRO/UR Approved Stay-Fm",
    repeatable: false,
    required: false,
    sequence: 14,
  },
  {
    datatype: "DT",
    id: "UB1-15",
    item: "544",
    maxLength: 8,
    name: "PSRO/UR Approved Stay-To",
    repeatable: false,
    required: false,
    sequence: 15,
  },
  {
    datatype: "OCD",
    id: "UB1-16",
    item: "545",
    name: "Occurrence",
    repeatable: false,
    required: false,
    sequence: 16,
  },
  {
    datatype: "CWE",
    id: "UB1-17",
    item: "546",
    name: "Occurrence Span",
    repeatable: false,
    required: false,
    sequence: 17,
    table: "HL70351",
  },
  {
    datatype: "DT",
    id: "UB1-18",
    item: "547",
    name: "Occur Span Start Date",
    repeatable: false,
    required: false,
    sequence: 18,
  },
  {
    datatype: "DT",
    id: "UB1-19",
    item: "548",
    name: "Occur Span End Date",
    repeatable: false,
    required: false,
    sequence: 19,
  },
  {
    datatype: "ST",
    id: "UB1-20",
    item: "549",
    name: "UB-82 Locator 2",
    repeatable: false,
    required: false,
    sequence: 20,
  },
  {
    datatype: "ST",
    id: "UB1-21",
    item: "550",
    name: "UB-82 Locator 9",
    repeatable: false,
    required: false,
    sequence: 21,
  },
  {
    datatype: "ST",
    id: "UB1-22",
    item: "551",
    name: "UB-82 Locator 27",
    repeatable: false,
    required: false,
    sequence: 22,
  },
  {
    datatype: "ST",
    id: "UB1-23",
    item: "552",
    name: "UB-82 Locator 45",
    repeatable: false,
    required: false,
    sequence: 23,
  },
] as const;
