export enum SegmentType {
  AIG = "AIG",
  AIL = "AIL",
  AIP = "AIP",
  AIS = "AIS",
  MSH = "MSH",
  NTE = "NTE",
  OBX = "OBX",
  ORC = "ORC",
  PID = "PID",
  PV1 = "PV1",
  RGS = "RGS",
  RXA = "RXA",
  RXR = "RXR",
  SCH = "SCH",
  ZCH = "ZCH",
  ZTP = "ZTP",
}
