// Generated table profile for 0227 (v2.5)

export const id = "0227";
export const description = "Manufacturers of Vaccines (code=MVX)";
export const type = "hl7";
export const codes = [
  { name: "AB", description: "Abbott Laboratories" },
  { name: "AD", description: "Adams Laboratories, Inc." },
  { name: "ALP", description: "Alpha Therapeutic Corporation" },
  { name: "AR", description: "Armour" },
  { name: "AVB", description: "Aventis Behring L.L.C." },
  { name: "AVI", description: "Aviron" },
  { name: "BA", description: "Baxter Healthcare Coporation]" },
  { name: "BAH", description: "Baxter Health Corporation" },
  { name: "BAY", description: "Bayer Corporation" },
  { name: "BP", description: "Berna Products" },
  { name: "BPC", description: "Berna Products Corporation" },
  { name: "CEN", description: "Centeon L.L.C." },
  { name: "CHI", description: "Chiron Corporation" },
  { name: "CMP", description: "Celltech Medeva Pharmaceuticals" },
  { name: "CON", description: "Connaught" },
  { name: "EVN", description: "Evans Medical Limited" },
  { name: "GRE", description: "Greer Laboratories, Inc." },
  { name: "IAG", description: "Immuno International AG" },
  { name: "IM", description: "Merieux" },
  { name: "IUS", description: "Immuno-U.S., Inc." },
  {
    name: "JPN",
    description:
      "The Research Foundation for Microbial Diseases of Osaka University",
  },
  { name: "KGC", description: "Korea Green Cross Corporation" },
  { name: "LED", description: "Lederle" },
  {
    name: "MA",
    description: "Massachusetts Public Health Biologic Laboratories",
  },
  { name: "MBL", description: "Massachusetts Biologic Laboratories" },
  { name: "MED", description: "MedImmune, Inc." },
  { name: "MIL", description: "Miles" },
  { name: "MIP", description: "Bioport Corporation" },
  { name: "MSD", description: "Merck & Co., Inc." },
  { name: "NAB", description: "NABI" },
  { name: "NAV", description: "North American Vaccine, Inc." },
  { name: "NOV", description: "Novartis Pharmaceutical Corporation" },
  { name: "NYB", description: "New York Blood Center" },
  { name: "ORT", description: "Ortho-Clinical Diagnostics." },
  { name: "OTC", description: "Organon Teknika Corporation" },
  { name: "OTH", description: "Other manufacturer" },
  { name: "PD", description: "Parkedale Pharmaceuticals" },
  { name: "PMC", description: "Aventis Pasteur Inc." },
  { name: "PRX", description: "Praxis Biologics" },
  { name: "PWJ", description: "PowerJect Pharamaceuticals" },
  { name: "SCL", description: "Sclavo, Inc." },
  { name: "SI", description: "Swiss Serum and Vaccine Inst." },
  { name: "SKB", description: "GlaxoSmithKline" },
  { name: "UNK", description: "Unknown manufacturer" },
  {
    name: "USA",
    description: "United States Army Medical Research and Material Command",
  },
  { name: "WA", description: "Wyeth-Ayerst" },
  { name: "WAL", description: "Wyeth-Ayerst" },
] as const;
