// Generated table profile for 0076 (v2.3)

export const id = "0076";
export const description = "Message Type";
export const type = "hl7";
export const codes = [
  { description: "General acknowledgment message", name: "ACK" },
  { description: "ADT response", name: "ADR" },
  { description: "ADT message", name: "ADT" },
  { description: "Ancillary RPT (display)", name: "ARD" },
  { description: "Add/change billing account", name: "BAR" },
  { description: "Cancel query", name: "CNQ" },
  { description: "Unsolicited clinical study data", name: "CSU" },
  { description: "Detail financial transaction", name: "DFT" },
  { description: "Document Response", name: "DOC" },
  { description: "Display response", name: "DSR" },
  { description: "Enhanced display response", name: "EDR" },
  { description: "Embedded query language query", name: "EQQ" },
  { description: "Event replay response", name: "ERP" },
  { description: "Event replay query", name: "ERQ" },
  { description: "Delayed acknowledgment", name: "MCF" },
  { description: "Documentation message", name: "MDM" },
  { description: "Master files delayed application ack", name: "MFD" },
  { description: "Master files application ack", name: "MFK" },
  { description: "Master files notification", name: "MFN" },
  { description: "Master files query", name: "MFQ" },
  { description: "Master files query response", name: "MFR" },
  { description: "Observ. result/record response", name: "ORF" },
  { description: "Order message", name: "ORM" },
  { description: "Order acknowledgment message", name: "ORR" },
  { description: "Observ result/unsolicited", name: "ORU" },
  { description: "Order status query", name: "OSQ" },
  { description: "Order status response", name: "OSR" },
  { description: "Product experience", name: "PEX" },
  { description: "Patient goal", name: "PGL" },
  { description: "Patient information", name: "PIN" },
  { description: "Patient Pathway (goal-oriented) message", name: "PPG" },
  { description: "Patient problem", name: "PPR" },
  { description: "Patient Pathway (goal oriented) response", name: "PPT" },
  { description: "Patient Goal Response", name: "PPV" },
  { description: "Patient Problem Response", name: "PRR" },
  { description: "Patient Pathway (problem-oriented) response", name: "PTR" },
  { description: "Query General  Acknowledgment", name: "QCK" },
  { description: "Query, original Mode", name: "QRY" },
  { description: "Pharmacy administration information", name: "RAR" },
  { description: "Pharmacy administration message", name: "RAS" },
  { description: "Return clinical information", name: "RCI" },
  { description: "Return clinical list", name: "RCL" },
  { description: "Pharmacy encoded order message", name: "RDE" },
  { description: "Pharmacy dispense information", name: "RDR" },
  { description: "Pharmacy dispense message", name: "RDS" },
  { description: "Patient referral", name: "REF" },
  { description: "Pharmacy encoded order information", name: "RER" },
  { description: "Pharmacy dose information", name: "RGR" },
  { description: "Pharmacy give message", name: "RGV" },
  { description: "Request clinical information", name: "ROC" },
  { description: "Request pateint demographics", name: "ROD" },
  { description: "Pharmacy prescription order response", name: "ROR" },
  { description: "Return patient authorization", name: "RPA" },
  { description: "Return patient information", name: "RPI" },
  { description: "Return patient display list", name: "RPL" },
  { description: "Return patient list", name: "RPR" },
  { description: "Request patient authorization", name: "RQA" },
  { description: "Request Clinical Information", name: "RQC" },
  { description: "Request patient information", name: "RQI" },
  { description: "Request Patient Demographics", name: "RQP" },
  { description: "??? Page 2-68", name: "RQQ" },
  { description: "Pharmacy administration acknowledgment", name: "RRA" },
  { description: "Pharmacy dispense acknowledgment", name: "RRD" },
  { description: "Pharmacy encoded order acknowledgment", name: "RRE" },
  { description: "Pharmacy give acknowledgment", name: "RRG" },
  { description: "Return patient referral", name: "RRI" },
  { description: "Schedule information unsolicited", name: "SIU" },
  { description: "Stored procedure request", name: "SPQ" },
  { description: "Schedule query", name: "SQM" },
  { description: "Schedule query response", name: "SQR" },
  { description: "Schedule request", name: "SRM" },
  { description: "Scheduled request response", name: "SRR" },
  { description: "Tabular response", name: "TBR" },
  { description: "Unsolicited display message", name: "UDM" },
  { description: "Virtual table query", name: "VQQ" },
  { description: "Query for vaccination record", name: "VXQ" },
  { description: "Vaccination query record response", name: "VXR" },
  { description: "Unsolicited vaccinnation record update", name: "VXU" },
  {
    description: "Vaccination query response with multiple PID matches",
    name: "VXX",
  },
] as const;
