// Generated table profile for 0076 (v2.3)

export const id = "0076";
export const description = "Message Type";
export const type = "hl7";
export const codes = [
  { name: "ACK", description: "General acknowledgment message" },
  { name: "ADR", description: "ADT response" },
  { name: "ADT", description: "ADT message" },
  { name: "ARD", description: "Ancillary RPT (display)" },
  { name: "BAR", description: "Add/change billing account" },
  { name: "CNQ", description: "Cancel query" },
  { name: "CSU", description: "Unsolicited clinical study data" },
  { name: "DFT", description: "Detail financial transaction" },
  { name: "DOC", description: "Document Response" },
  { name: "DSR", description: "Display response" },
  { name: "EDR", description: "Enhanced display response" },
  { name: "EQQ", description: "Embedded query language query" },
  { name: "ERP", description: "Event replay response" },
  { name: "ERQ", description: "Event replay query" },
  { name: "MCF", description: "Delayed acknowledgment" },
  { name: "MDM", description: "Documentation message" },
  { name: "MFD", description: "Master files delayed application ack" },
  { name: "MFK", description: "Master files application ack" },
  { name: "MFN", description: "Master files notification" },
  { name: "MFQ", description: "Master files query" },
  { name: "MFR", description: "Master files query response" },
  { name: "ORF", description: "Observ. result/record response" },
  { name: "ORM", description: "Order message" },
  { name: "ORR", description: "Order acknowledgment message" },
  { name: "ORU", description: "Observ result/unsolicited" },
  { name: "OSQ", description: "Order status query" },
  { name: "OSR", description: "Order status response" },
  { name: "PEX", description: "Product experience" },
  { name: "PGL", description: "Patient goal" },
  { name: "PIN", description: "Patient information" },
  { name: "PPG", description: "Patient Pathway (goal-oriented) message" },
  { name: "PPR", description: "Patient problem" },
  { name: "PPT", description: "Patient Pathway (goal oriented) response" },
  { name: "PPV", description: "Patient Goal Response" },
  { name: "PRR", description: "Patient Problem Response" },
  { name: "PTR", description: "Patient Pathway (problem-oriented) response" },
  { name: "QCK", description: "Query General  Acknowledgment" },
  { name: "QRY", description: "Query, original Mode" },
  { name: "RAR", description: "Pharmacy administration information" },
  { name: "RAS", description: "Pharmacy administration message" },
  { name: "RCI", description: "Return clinical information" },
  { name: "RCL", description: "Return clinical list" },
  { name: "RDE", description: "Pharmacy encoded order message" },
  { name: "RDR", description: "Pharmacy dispense information" },
  { name: "RDS", description: "Pharmacy dispense message" },
  { name: "REF", description: "Patient referral" },
  { name: "RER", description: "Pharmacy encoded order information" },
  { name: "RGR", description: "Pharmacy dose information" },
  { name: "RGV", description: "Pharmacy give message" },
  { name: "ROC", description: "Request clinical information" },
  { name: "ROD", description: "Request pateint demographics" },
  { name: "ROR", description: "Pharmacy prescription order response" },
  { name: "RPA", description: "Return patient authorization" },
  { name: "RPI", description: "Return patient information" },
  { name: "RPL", description: "Return patient display list" },
  { name: "RPR", description: "Return patient list" },
  { name: "RQA", description: "Request patient authorization" },
  { name: "RQC", description: "Request Clinical Information" },
  { name: "RQI", description: "Request patient information" },
  { name: "RQP", description: "Request Patient Demographics" },
  { name: "RQQ", description: "??? Page 2-68" },
  { name: "RRA", description: "Pharmacy administration acknowledgment" },
  { name: "RRD", description: "Pharmacy dispense acknowledgment" },
  { name: "RRE", description: "Pharmacy encoded order acknowledgment" },
  { name: "RRG", description: "Pharmacy give acknowledgment" },
  { name: "RRI", description: "Return patient referral" },
  { name: "SIU", description: "Schedule information unsolicited" },
  { name: "SPQ", description: "Stored procedure request" },
  { name: "SQM", description: "Schedule query" },
  { name: "SQR", description: "Schedule query response" },
  { name: "SRM", description: "Schedule request" },
  { name: "SRR", description: "Scheduled request response" },
  { name: "TBR", description: "Tabular response" },
  { name: "UDM", description: "Unsolicited display message" },
  { name: "VQQ", description: "Virtual table query" },
  { name: "VXQ", description: "Query for vaccination record" },
  { name: "VXR", description: "Vaccination query record response" },
  { name: "VXU", description: "Unsolicited vaccinnation record update" },
  {
    name: "VXX",
    description: "Vaccination query response with multiple PID matches",
  },
] as const;
