name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  testing:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 20.x
          - 22.x
          - 24.x

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: pnpm ci:install
      - name: Build
        run: pnpm build
      - name: Testing
        run: pnpm test:coverage
      - name: Bun Tests
        run: pnpm --filter @rethinkhealth/hl7v2-mllp test:bun
        timeout-minutes: 2
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  linting:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm ci:install
      - name: Linting
        run: pnpm check
      - name: Formatting
        run: pnpm fix
