name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: dist
            path: |
              dist
  
  test:
    name: Linting
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: linting
        run: pnpm test
  
  linting:
    name: Linting
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: linting
        run: pnpm lint
