// Generated profile automaton for OSM_R26 (v2.8.2)

export const start = 0;
export const finals = new Set<number>([
  6, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
  28, 29,
]);
export const alphabet = new Set<string>([
  "ARV",
  "MSH",
  "NK1",
  "OBX",
  "PAC",
  "PID",
  "PRT",
  "PV1",
  "SAC",
  "SFT",
  "SHP",
  "SPM",
  "UAC",
]);
export const transitions = new Map<number, Map<string, number>>([
  [0, new Map([["MSH", 1]])],
  [
    1,
    new Map([
      ["SFT", 4],
      ["SHP", 2],
      ["UAC", 3],
    ]),
  ],
  [2, new Map([["PRT", 5]])],
  [3, new Map([["SHP", 2]])],
  [
    4,
    new Map([
      ["SFT", 4],
      ["SHP", 2],
      ["UAC", 3],
    ]),
  ],
  [
    5,
    new Map([
      ["OBX", 7],
      ["PAC", 6],
      ["PRT", 5],
    ]),
  ],
  [
    6,
    new Map([
      ["PAC", 6],
      ["PRT", 9],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    7,
    new Map([
      ["OBX", 7],
      ["PAC", 6],
      ["PRT", 10],
    ]),
  ],
  [
    8,
    new Map([
      ["OBX", 14],
      ["PAC", 6],
      ["PID", 12],
      ["PRT", 15],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    9,
    new Map([
      ["PAC", 6],
      ["PRT", 9],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    10,
    new Map([
      ["OBX", 7],
      ["PAC", 6],
      ["PRT", 10],
    ]),
  ],
  [
    11,
    new Map([
      ["NK1", 16],
      ["OBX", 18],
      ["PAC", 6],
      ["PID", 17],
      ["PRT", 19],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    12,
    new Map([
      ["ARV", 22],
      ["NK1", 20],
      ["OBX", 21],
      ["PAC", 6],
      ["PRT", 23],
      ["PV1", 11],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    13,
    new Map([
      ["OBX", 24],
      ["PAC", 6],
      ["PID", 12],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    14,
    new Map([
      ["OBX", 14],
      ["PAC", 6],
      ["PID", 12],
      ["PRT", 25],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    15,
    new Map([
      ["OBX", 14],
      ["PAC", 6],
      ["PID", 12],
      ["PRT", 15],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    16,
    new Map([
      ["NK1", 16],
      ["PAC", 6],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    17,
    new Map([
      ["NK1", 16],
      ["PAC", 6],
      ["PRT", 26],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    18,
    new Map([
      ["NK1", 16],
      ["OBX", 18],
      ["PAC", 6],
      ["PID", 17],
      ["PRT", 27],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    19,
    new Map([
      ["NK1", 16],
      ["OBX", 18],
      ["PAC", 6],
      ["PID", 17],
      ["PRT", 19],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    20,
    new Map([
      ["NK1", 20],
      ["PAC", 6],
      ["PV1", 11],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    21,
    new Map([
      ["NK1", 20],
      ["OBX", 21],
      ["PAC", 6],
      ["PRT", 28],
      ["PV1", 11],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    22,
    new Map([
      ["ARV", 22],
      ["NK1", 20],
      ["OBX", 21],
      ["PAC", 6],
      ["PV1", 11],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    23,
    new Map([
      ["ARV", 22],
      ["NK1", 20],
      ["OBX", 21],
      ["PAC", 6],
      ["PRT", 23],
      ["PV1", 11],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    24,
    new Map([
      ["OBX", 24],
      ["PAC", 6],
      ["PID", 12],
      ["PRT", 29],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    25,
    new Map([
      ["OBX", 14],
      ["PAC", 6],
      ["PID", 12],
      ["PRT", 25],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    26,
    new Map([
      ["NK1", 16],
      ["PAC", 6],
      ["PRT", 26],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    27,
    new Map([
      ["NK1", 16],
      ["OBX", 18],
      ["PAC", 6],
      ["PID", 17],
      ["PRT", 27],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    28,
    new Map([
      ["NK1", 20],
      ["OBX", 21],
      ["PAC", 6],
      ["PRT", 28],
      ["PV1", 11],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
  [
    29,
    new Map([
      ["OBX", 24],
      ["PAC", 6],
      ["PID", 12],
      ["PRT", 29],
      ["PV1", 11],
      ["SAC", 13],
      ["SHP", 2],
      ["SPM", 8],
    ]),
  ],
]);
export const effects = {
  "1:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [],
  },
  "3:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [],
  },
  "4:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [],
  },
  "5:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: ["OSM_R26/SHIPMENT/SHIPPING_OBSERVATION"],
  },
  "5:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/SHIPPING_OBSERVATION"],
    groupsClosed: [],
  },
  "6:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [],
  },
  "6:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
    ],
  },
  "6:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "7:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/SHIPPING_OBSERVATION"],
    groupsClosed: [],
  },
  "7:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: ["OSM_R26/SHIPMENT/SHIPPING_OBSERVATION"],
  },
  "8:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "8:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "8:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "8:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "8:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
    ],
  },
  "8:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
  },
  "8:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
    groupsClosed: [],
  },
  "9:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [],
  },
  "9:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
    ],
  },
  "9:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "10:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/SHIPPING_OBSERVATION"],
    groupsClosed: [],
  },
  "10:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: ["OSM_R26/SHIPMENT/SHIPPING_OBSERVATION"],
  },
  "11:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "11:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "11:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "11:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "11:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "11:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "12:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "12:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "12:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "12:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "12:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "12:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "13:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: [],
  },
  "13:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
  },
  "13:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "13:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "13:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "13:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
  },
  "13:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "14:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
    groupsClosed: [],
  },
  "14:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "14:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "14:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "14:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "14:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
    ],
  },
  "14:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
  },
  "15:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "15:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "15:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "15:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "15:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
    ],
  },
  "15:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
  },
  "15:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
    groupsClosed: [],
  },
  "16:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "16:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "16:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "17:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "17:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "17:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "17:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "18:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "18:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "18:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "18:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "18:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "18:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "19:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "19:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "19:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "19:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "19:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "19:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "20:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "20:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "20:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "20:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "21:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "21:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "21:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "21:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "21:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "21:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "22:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "22:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "22:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "22:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "22:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "22:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "23:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "23:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "23:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "23:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "23:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "23:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "24:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "24:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: [],
  },
  "24:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
  },
  "24:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "24:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "24:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "24:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
  },
  "25:OBX": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
    groupsClosed: [],
  },
  "25:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [],
  },
  "25:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "25:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "25:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "25:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION",
    ],
  },
  "25:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SPECIMEN_OBSERVATION"],
  },
  "26:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "26:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "26:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "26:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
  },
  "27:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "27:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "27:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "27:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "27:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "27:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_INFORMATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION/PATIENT_VISIT_OBSERVATION",
    ],
  },
  "28:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "28:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "28:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "28:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "28:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "28:NK1": {
    groupsOpened: [],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION/PATIENT_OBSERVATION",
    ],
  },
  "29:OBX": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
    groupsClosed: [],
  },
  "29:SAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER"],
    groupsClosed: [],
  },
  "29:SPM": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE/SPECIMEN"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
  },
  "29:PAC": {
    groupsOpened: ["OSM_R26/SHIPMENT/PACKAGE"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "29:SHP": {
    groupsOpened: ["OSM_R26/SHIPMENT"],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
  },
  "29:PV1": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_POPULATION_OR_LOCATION_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
  },
  "29:PID": {
    groupsOpened: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/SUBJECT_PERSON_OR_ANIMAL_IDENTIFICATION",
    ],
    groupsClosed: [
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER",
      "OSM_R26/SHIPMENT/PACKAGE/SPECIMEN/CONTAINER/CONTAINER_OBSERVATION",
    ],
  },
} satisfies Readonly<
  Record<
    string,
    { groupsOpened: readonly string[]; groupsClosed: readonly string[] }
  >
>;
